# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBServiceTypeEditor.ui'
#
# Created: Wed Feb 19 22:56:06 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(320, 262)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ItemEditorDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.lblCode = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridlayout.addWidget(self.lblCode, 1, 0, 1, 1)
        self.lblName = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridlayout.addWidget(self.lblName, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 6, 0, 1, 1)
        self.cmbClass = QtGui.QComboBox(ItemEditorDialog)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbClass, 3, 1, 1, 1)
        self.edtCode = QtGui.QLineEdit(ItemEditorDialog)
        self.edtCode.setMaxLength(8)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridlayout.addWidget(self.edtCode, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 9, 0, 1, 2)
        self.txtDescription = QtGui.QTextEdit(ItemEditorDialog)
        self.txtDescription.setObjectName(_fromUtf8("txtDescription"))
        self.gridlayout.addWidget(self.txtDescription, 5, 1, 2, 1)
        self.lblSection = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSection.sizePolicy().hasHeightForWidth())
        self.lblSection.setSizePolicy(sizePolicy)
        self.lblSection.setObjectName(_fromUtf8("lblSection"))
        self.gridlayout.addWidget(self.lblSection, 0, 0, 1, 1)
        self.lblDescription = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescription.sizePolicy().hasHeightForWidth())
        self.lblDescription.setSizePolicy(sizePolicy)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.gridlayout.addWidget(self.lblDescription, 5, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(ItemEditorDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridlayout.addWidget(self.edtName, 2, 1, 1, 1)
        self.lblClass = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClass.sizePolicy().hasHeightForWidth())
        self.lblClass.setSizePolicy(sizePolicy)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridlayout.addWidget(self.lblClass, 3, 0, 1, 1)
        self.cmbSection = QtGui.QComboBox(ItemEditorDialog)
        self.cmbSection.setObjectName(_fromUtf8("cmbSection"))
        self.cmbSection.addItem(_fromUtf8(""))
        self.cmbSection.addItem(_fromUtf8(""))
        self.cmbSection.addItem(_fromUtf8(""))
        self.cmbSection.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSection, 0, 1, 1, 1)
        self.lblGroup = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGroup.sizePolicy().hasHeightForWidth())
        self.lblGroup.setSizePolicy(sizePolicy)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridlayout.addWidget(self.lblGroup, 4, 0, 1, 1)
        self.cmbGroup = CRBComboBox(ItemEditorDialog)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridlayout.addWidget(self.cmbGroup, 4, 1, 1, 1)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(ItemEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.cmbSection, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.cmbClass)
        ItemEditorDialog.setTabOrder(self.cmbClass, self.cmbGroup)
        ItemEditorDialog.setTabOrder(self.cmbGroup, self.txtDescription)
        ItemEditorDialog.setTabOrder(self.txtDescription, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(QtGui.QApplication.translate("ItemEditorDialog", "ChangeMe!", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("ItemEditorDialog", "&Код", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("ItemEditorDialog", "&Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbClass.setItemText(0, QtGui.QApplication.translate("ItemEditorDialog", "статус", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbClass.setItemText(1, QtGui.QApplication.translate("ItemEditorDialog", "диагностика", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbClass.setItemText(2, QtGui.QApplication.translate("ItemEditorDialog", "лечение", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbClass.setItemText(3, QtGui.QApplication.translate("ItemEditorDialog", "прочие мероприятия", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSection.setText(QtGui.QApplication.translate("ItemEditorDialog", "Раздел", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescription.setText(QtGui.QApplication.translate("ItemEditorDialog", "Описание", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClass.setText(QtGui.QApplication.translate("ItemEditorDialog", "Класс", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSection.setItemText(0, QtGui.QApplication.translate("ItemEditorDialog", "А - простые услуги", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSection.setItemText(1, QtGui.QApplication.translate("ItemEditorDialog", "В - сложные услуги", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSection.setItemText(2, QtGui.QApplication.translate("ItemEditorDialog", "Д - работы", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSection.setItemText(3, QtGui.QApplication.translate("ItemEditorDialog", "Ф - вспомогательные услуги", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGroup.setText(QtGui.QApplication.translate("ItemEditorDialog", "Группа", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

