# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\Samson\UP_s11\client_merge\Orgs\OrgComboBoxPopupEx.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OrgComboBoxPopupEx(object):
    def setupUi(self, OrgComboBoxPopupEx):
        OrgComboBoxPopupEx.setObjectName(_fromUtf8("OrgComboBoxPopupEx"))
        OrgComboBoxPopupEx.resize(389, 336)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(OrgComboBoxPopupEx)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(OrgComboBoxPopupEx)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabOrg = QtGui.QWidget()
        self.tabOrg.setObjectName(_fromUtf8("tabOrg"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabOrg)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblOrg = QtGui.QListView(self.tabOrg)
        self.tblOrg.setObjectName(_fromUtf8("tblOrg"))
        self.verticalLayout.addWidget(self.tblOrg)
        self.tabWidget.addTab(self.tabOrg, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblName = QtGui.QLabel(self.tabSearch)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabSearch)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 0, 1, 1, 2)
        self.lblINN = QtGui.QLabel(self.tabSearch)
        self.lblINN.setObjectName(_fromUtf8("lblINN"))
        self.gridLayout.addWidget(self.lblINN, 1, 0, 1, 1)
        self.edtINN = QtGui.QLineEdit(self.tabSearch)
        self.edtINN.setObjectName(_fromUtf8("edtINN"))
        self.gridLayout.addWidget(self.edtINN, 1, 1, 1, 2)
        self.lblOKATO = QtGui.QLabel(self.tabSearch)
        self.lblOKATO.setObjectName(_fromUtf8("lblOKATO"))
        self.gridLayout.addWidget(self.lblOKATO, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(172, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 2, 1, 1)
        self.lblOGRN = QtGui.QLabel(self.tabSearch)
        self.lblOGRN.setObjectName(_fromUtf8("lblOGRN"))
        self.gridLayout.addWidget(self.lblOGRN, 2, 0, 1, 1)
        self.edtOGRN = QtGui.QLineEdit(self.tabSearch)
        self.edtOGRN.setObjectName(_fromUtf8("edtOGRN"))
        self.gridLayout.addWidget(self.edtOGRN, 2, 1, 1, 2)
        self.edtOKATO = QtGui.QLineEdit(self.tabSearch)
        self.edtOKATO.setObjectName(_fromUtf8("edtOKATO"))
        self.gridLayout.addWidget(self.edtOKATO, 3, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.cmbHospitalBedProfile = CRBComboBox(self.tabSearch)
        self.cmbHospitalBedProfile.setObjectName(_fromUtf8("cmbHospitalBedProfile"))
        self.gridLayout.addWidget(self.cmbHospitalBedProfile, 8, 1, 1, 2)
        self.lblHospitalBedProfile = QtGui.QLabel(self.tabSearch)
        self.lblHospitalBedProfile.setObjectName(_fromUtf8("lblHospitalBedProfile"))
        self.gridLayout.addWidget(self.lblHospitalBedProfile, 8, 0, 1, 1)
        self.edtTfomsCode = QtGui.QLineEdit(self.tabSearch)
        self.edtTfomsCode.setObjectName(_fromUtf8("edtTfomsCode"))
        self.gridLayout.addWidget(self.edtTfomsCode, 4, 1, 1, 2)
        self.lblTfomsCode = QtGui.QLabel(self.tabSearch)
        self.lblTfomsCode.setObjectName(_fromUtf8("lblTfomsCode"))
        self.gridLayout.addWidget(self.lblTfomsCode, 4, 0, 1, 1)
        self.edtOKVED = QtGui.QLineEdit(self.tabSearch)
        self.edtOKVED.setObjectName(_fromUtf8("edtOKVED"))
        self.gridLayout.addWidget(self.edtOKVED, 5, 1, 1, 2)
        self.cmbIsInsurer = QtGui.QComboBox(self.tabSearch)
        self.cmbIsInsurer.setObjectName(_fromUtf8("cmbIsInsurer"))
        self.cmbIsInsurer.addItem(_fromUtf8(""))
        self.cmbIsInsurer.addItem(_fromUtf8(""))
        self.cmbIsInsurer.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsInsurer, 6, 1, 1, 2)
        self.lblOKVED = QtGui.QLabel(self.tabSearch)
        self.lblOKVED.setObjectName(_fromUtf8("lblOKVED"))
        self.gridLayout.addWidget(self.lblOKVED, 5, 0, 1, 1)
        self.lblActive = QtGui.QLabel(self.tabSearch)
        self.lblActive.setObjectName(_fromUtf8("lblActive"))
        self.gridLayout.addWidget(self.lblActive, 7, 0, 1, 1)
        self.cmbActive = QtGui.QComboBox(self.tabSearch)
        self.cmbActive.setObjectName(_fromUtf8("cmbActive"))
        self.cmbActive.addItem(_fromUtf8(""))
        self.cmbActive.addItem(_fromUtf8(""))
        self.cmbActive.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActive, 7, 1, 1, 2)
        self.lblIsInsurer = QtGui.QLabel(self.tabSearch)
        self.lblIsInsurer.setObjectName(_fromUtf8("lblIsInsurer"))
        self.gridLayout.addWidget(self.lblIsInsurer, 6, 0, 1, 1)
        self.lblIsMedical = QtGui.QLabel(self.tabSearch)
        self.lblIsMedical.setObjectName(_fromUtf8("lblIsMedical"))
        self.gridLayout.addWidget(self.lblIsMedical, 9, 0, 1, 1)
        self.cmbIsMedical = QtGui.QComboBox(self.tabSearch)
        self.cmbIsMedical.setObjectName(_fromUtf8("cmbIsMedical"))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsMedical, 9, 1, 1, 2)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.lblName.setBuddy(self.edtName)
        self.lblINN.setBuddy(self.edtINN)
        self.lblOGRN.setBuddy(self.edtOGRN)
        self.lblHospitalBedProfile.setBuddy(self.cmbHospitalBedProfile)
        self.lblTfomsCode.setBuddy(self.edtTfomsCode)
        self.lblOKVED.setBuddy(self.edtOKVED)
        self.lblActive.setBuddy(self.cmbActive)
        self.lblIsInsurer.setBuddy(self.cmbIsInsurer)
        self.lblIsMedical.setBuddy(self.cmbIsMedical)

        self.retranslateUi(OrgComboBoxPopupEx)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OrgComboBoxPopupEx)
        OrgComboBoxPopupEx.setTabOrder(self.tblOrg, self.tabWidget)
        OrgComboBoxPopupEx.setTabOrder(self.tabWidget, self.edtName)
        OrgComboBoxPopupEx.setTabOrder(self.edtName, self.edtINN)
        OrgComboBoxPopupEx.setTabOrder(self.edtINN, self.edtOGRN)
        OrgComboBoxPopupEx.setTabOrder(self.edtOGRN, self.edtOKATO)
        OrgComboBoxPopupEx.setTabOrder(self.edtOKATO, self.buttonBox)

    def retranslateUi(self, OrgComboBoxPopupEx):
        OrgComboBoxPopupEx.setWindowTitle(_translate("OrgComboBoxPopupEx", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOrg), _translate("OrgComboBoxPopupEx", "&Организации", None))
        self.lblName.setText(_translate("OrgComboBoxPopupEx", "&Название содержит", None))
        self.lblINN.setText(_translate("OrgComboBoxPopupEx", "&ИНН", None))
        self.lblOKATO.setText(_translate("OrgComboBoxPopupEx", "ОКАТО", None))
        self.lblOGRN.setText(_translate("OrgComboBoxPopupEx", "&ОГРН", None))
        self.lblHospitalBedProfile.setText(_translate("OrgComboBoxPopupEx", "Профиль койки", None))
        self.lblTfomsCode.setText(_translate("OrgComboBoxPopupEx", "Код ТФОМС", None))
        self.cmbIsInsurer.setItemText(0, _translate("OrgComboBoxPopupEx", "не задано", None))
        self.cmbIsInsurer.setItemText(1, _translate("OrgComboBoxPopupEx", "Нет", None))
        self.cmbIsInsurer.setItemText(2, _translate("OrgComboBoxPopupEx", "Да", None))
        self.lblOKVED.setText(_translate("OrgComboBoxPopupEx", "ОКВЭД", None))
        self.lblActive.setText(_translate("OrgComboBoxPopupEx", "Активность", None))
        self.cmbActive.setItemText(0, _translate("OrgComboBoxPopupEx", "не задано", None))
        self.cmbActive.setItemText(1, _translate("OrgComboBoxPopupEx", "Не активна", None))
        self.cmbActive.setItemText(2, _translate("OrgComboBoxPopupEx", "Активна", None))
        self.lblIsInsurer.setText(_translate("OrgComboBoxPopupEx", "Страховая компания", None))
        self.lblIsMedical.setText(_translate("OrgComboBoxPopupEx", "ЛПУ", None))
        self.cmbIsMedical.setItemText(0, _translate("OrgComboBoxPopupEx", "не определено", None))
        self.cmbIsMedical.setItemText(1, _translate("OrgComboBoxPopupEx", "поликлиника", None))
        self.cmbIsMedical.setItemText(2, _translate("OrgComboBoxPopupEx", "стационар", None))
        self.cmbIsMedical.setItemText(3, _translate("OrgComboBoxPopupEx", "прочая мед.организация", None))
        self.cmbIsMedical.setItemText(4, _translate("OrgComboBoxPopupEx", "СМП", None))
        self.cmbIsMedical.setItemText(5, _translate("OrgComboBoxPopupEx", "санаторного типа", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("OrgComboBoxPopupEx", "&Поиск", None))

from library.crbcombobox import CRBComboBox
