# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client_eln\Orgs\OrgEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OrgEditorDialog(object):
    def setupUi(self, OrgEditorDialog):
        OrgEditorDialog.setObjectName(_fromUtf8("OrgEditorDialog"))
        OrgEditorDialog.resize(976, 846)
        OrgEditorDialog.setSizeGripEnabled(False)
        self.gridLayout_7 = QtGui.QGridLayout(OrgEditorDialog)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.buttonBox = QtGui.QDialogButtonBox(OrgEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_7.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.lblFullName = QtGui.QLabel(OrgEditorDialog)
        self.lblFullName.setObjectName(_fromUtf8("lblFullName"))
        self.gridLayout_7.addWidget(self.lblFullName, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(OrgEditorDialog)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_7.addWidget(self.lblTitle, 2, 0, 1, 1)
        self.lblShortName = QtGui.QLabel(OrgEditorDialog)
        self.lblShortName.setObjectName(_fromUtf8("lblShortName"))
        self.gridLayout_7.addWidget(self.lblShortName, 1, 0, 1, 1)
        self.edtTitle = QtGui.QLineEdit(OrgEditorDialog)
        self.edtTitle.setObjectName(_fromUtf8("edtTitle"))
        self.gridLayout_7.addWidget(self.edtTitle, 2, 1, 1, 1)
        self.edtFullName = QtGui.QLineEdit(OrgEditorDialog)
        self.edtFullName.setObjectName(_fromUtf8("edtFullName"))
        self.gridLayout_7.addWidget(self.edtFullName, 0, 1, 1, 1)
        self.edtShortName = QtGui.QLineEdit(OrgEditorDialog)
        self.edtShortName.setObjectName(_fromUtf8("edtShortName"))
        self.gridLayout_7.addWidget(self.edtShortName, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(OrgEditorDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBaseInfo = QtGui.QWidget()
        self.tabBaseInfo.setObjectName(_fromUtf8("tabBaseInfo"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabBaseInfo)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblAddress = QtGui.QLabel(self.tabBaseInfo)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout_6.addWidget(self.lblAddress, 0, 0, 1, 1)
        self.chkKLADR = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkKLADR.setObjectName(_fromUtf8("chkKLADR"))
        self.gridLayout_6.addWidget(self.chkKLADR, 1, 0, 1, 1)
        self.cmbHead = COrgComboBox(self.tabBaseInfo)
        self.cmbHead.setEnabled(True)
        self.cmbHead.setObjectName(_fromUtf8("cmbHead"))
        self.gridLayout_6.addWidget(self.cmbHead, 2, 1, 1, 2)
        self.cmbKLADRCity = CKLADRComboBox(self.tabBaseInfo)
        self.cmbKLADRCity.setObjectName(_fromUtf8("cmbKLADRCity"))
        self.gridLayout_6.addWidget(self.cmbKLADRCity, 1, 1, 1, 1)
        self.lblHead = QtGui.QLabel(self.tabBaseInfo)
        self.lblHead.setObjectName(_fromUtf8("lblHead"))
        self.gridLayout_6.addWidget(self.lblHead, 2, 0, 1, 1)
        self.edtAddress = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtAddress.setEnabled(True)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.gridLayout_6.addWidget(self.edtAddress, 0, 1, 1, 7)
        self.lblOKATO = QtGui.QLabel(self.tabBaseInfo)
        self.lblOKATO.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOKATO.setObjectName(_fromUtf8("lblOKATO"))
        self.gridLayout_6.addWidget(self.lblOKATO, 3, 2, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblKLADRHouse = QtGui.QLabel(self.tabBaseInfo)
        self.lblKLADRHouse.setObjectName(_fromUtf8("lblKLADRHouse"))
        self.gridLayout.addWidget(self.lblKLADRHouse, 0, 0, 1, 1)
        self.edtKLADRHouse = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtKLADRHouse.setInputMask(_fromUtf8(""))
        self.edtKLADRHouse.setObjectName(_fromUtf8("edtKLADRHouse"))
        self.gridLayout.addWidget(self.edtKLADRHouse, 0, 1, 1, 1)
        self.lblKLADRCorpus = QtGui.QLabel(self.tabBaseInfo)
        self.lblKLADRCorpus.setObjectName(_fromUtf8("lblKLADRCorpus"))
        self.gridLayout.addWidget(self.lblKLADRCorpus, 0, 2, 1, 1)
        self.edtKLADRCorpus = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtKLADRCorpus.setInputMask(_fromUtf8(""))
        self.edtKLADRCorpus.setObjectName(_fromUtf8("edtKLADRCorpus"))
        self.gridLayout.addWidget(self.edtKLADRCorpus, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 1, 3, 1, 5)
        self.cmbKLADRStreet = CStreetComboBox(self.tabBaseInfo)
        self.cmbKLADRStreet.setMinimumSize(QtCore.QSize(400, 0))
        self.cmbKLADRStreet.setObjectName(_fromUtf8("cmbKLADRStreet"))
        self.gridLayout_6.addWidget(self.cmbKLADRStreet, 1, 2, 1, 1)
        self.lblOGRN = QtGui.QLabel(self.tabBaseInfo)
        self.lblOGRN.setObjectName(_fromUtf8("lblOGRN"))
        self.gridLayout_6.addWidget(self.lblOGRN, 3, 0, 1, 1)
        self.btnSelectHeadOrganisation = QtGui.QToolButton(self.tabBaseInfo)
        self.btnSelectHeadOrganisation.setEnabled(True)
        self.btnSelectHeadOrganisation.setObjectName(_fromUtf8("btnSelectHeadOrganisation"))
        self.gridLayout_6.addWidget(self.btnSelectHeadOrganisation, 2, 3, 1, 1)
        self.edtOGRN = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtOGRN.setObjectName(_fromUtf8("edtOGRN"))
        self.gridLayout_6.addWidget(self.edtOGRN, 3, 1, 1, 1)
        self.lblOKPF = QtGui.QLabel(self.tabBaseInfo)
        self.lblOKPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOKPF.setObjectName(_fromUtf8("lblOKPF"))
        self.gridLayout_6.addWidget(self.lblOKPF, 4, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(111, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 3, 6, 1, 2)
        self.cmbOKPF = CRBComboBox(self.tabBaseInfo)
        self.cmbOKPF.setObjectName(_fromUtf8("cmbOKPF"))
        self.gridLayout_6.addWidget(self.cmbOKPF, 4, 3, 1, 5)
        self.edtOKATO = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtOKATO.setObjectName(_fromUtf8("edtOKATO"))
        self.gridLayout_6.addWidget(self.edtOKATO, 3, 3, 1, 3)
        self.lblINN = QtGui.QLabel(self.tabBaseInfo)
        self.lblINN.setObjectName(_fromUtf8("lblINN"))
        self.gridLayout_6.addWidget(self.lblINN, 4, 0, 1, 1)
        self.edtINN = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtINN.setObjectName(_fromUtf8("edtINN"))
        self.gridLayout_6.addWidget(self.edtINN, 4, 1, 1, 1)
        self.lblKPP = QtGui.QLabel(self.tabBaseInfo)
        self.lblKPP.setObjectName(_fromUtf8("lblKPP"))
        self.gridLayout_6.addWidget(self.lblKPP, 5, 0, 1, 1)
        self.lblOKFS = QtGui.QLabel(self.tabBaseInfo)
        self.lblOKFS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOKFS.setObjectName(_fromUtf8("lblOKFS"))
        self.gridLayout_6.addWidget(self.lblOKFS, 5, 2, 1, 1)
        self.edtFSS = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtFSS.setObjectName(_fromUtf8("edtFSS"))
        self.gridLayout_6.addWidget(self.edtFSS, 6, 1, 1, 1)
        self.edtKPP = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtKPP.setObjectName(_fromUtf8("edtKPP"))
        self.gridLayout_6.addWidget(self.edtKPP, 5, 1, 1, 1)
        self.lblIsHospital = QtGui.QLabel(self.tabBaseInfo)
        self.lblIsHospital.setObjectName(_fromUtf8("lblIsHospital"))
        self.gridLayout_6.addWidget(self.lblIsHospital, 17, 0, 1, 1)
        self.edtTfomsExtCode = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtTfomsExtCode.setObjectName(_fromUtf8("edtTfomsExtCode"))
        self.gridLayout_6.addWidget(self.edtTfomsExtCode, 15, 3, 1, 5)
        self.cmbIsMedical = QtGui.QComboBox(self.tabBaseInfo)
        self.cmbIsMedical.setObjectName(_fromUtf8("cmbIsMedical"))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.cmbIsMedical.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbIsMedical, 17, 1, 1, 1)
        self.cmbOKFS = CRBComboBox(self.tabBaseInfo)
        self.cmbOKFS.setObjectName(_fromUtf8("cmbOKFS"))
        self.gridLayout_6.addWidget(self.cmbOKFS, 5, 3, 1, 5)
        self.lblNet = QtGui.QLabel(self.tabBaseInfo)
        self.lblNet.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNet.setObjectName(_fromUtf8("lblNet"))
        self.gridLayout_6.addWidget(self.lblNet, 17, 2, 1, 1)
        self.edtTfomsCode = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtTfomsCode.setObjectName(_fromUtf8("edtTfomsCode"))
        self.gridLayout_6.addWidget(self.edtTfomsCode, 15, 1, 1, 1)
        self.edtChief = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtChief.setObjectName(_fromUtf8("edtChief"))
        self.gridLayout_6.addWidget(self.edtChief, 9, 1, 1, 7)
        self.edtSmoCode = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtSmoCode.setEnabled(True)
        self.edtSmoCode.setMaxLength(10)
        self.edtSmoCode.setObjectName(_fromUtf8("edtSmoCode"))
        self.gridLayout_6.addWidget(self.edtSmoCode, 13, 1, 1, 1)
        self.lblMiacCode = QtGui.QLabel(self.tabBaseInfo)
        self.lblMiacCode.setObjectName(_fromUtf8("lblMiacCode"))
        self.gridLayout_6.addWidget(self.lblMiacCode, 16, 0, 1, 1)
        self.lblFSS = QtGui.QLabel(self.tabBaseInfo)
        self.lblFSS.setObjectName(_fromUtf8("lblFSS"))
        self.gridLayout_6.addWidget(self.lblFSS, 6, 0, 1, 1)
        self.lbSmoCode = QtGui.QLabel(self.tabBaseInfo)
        self.lbSmoCode.setEnabled(True)
        self.lbSmoCode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbSmoCode.setObjectName(_fromUtf8("lbSmoCode"))
        self.gridLayout_6.addWidget(self.lbSmoCode, 13, 0, 1, 1)
        self.lblTfomsExtCode = QtGui.QLabel(self.tabBaseInfo)
        self.lblTfomsExtCode.setScaledContents(False)
        self.lblTfomsExtCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTfomsExtCode.setObjectName(_fromUtf8("lblTfomsExtCode"))
        self.gridLayout_6.addWidget(self.lblTfomsExtCode, 15, 2, 1, 1)
        self.lblIsInsurer = QtGui.QLabel(self.tabBaseInfo)
        self.lblIsInsurer.setObjectName(_fromUtf8("lblIsInsurer"))
        self.gridLayout_6.addWidget(self.lblIsInsurer, 18, 0, 1, 1)
        self.cmbNet = CRBComboBox(self.tabBaseInfo)
        self.cmbNet.setObjectName(_fromUtf8("cmbNet"))
        self.gridLayout_6.addWidget(self.cmbNet, 17, 3, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(111, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 6, 6, 1, 2)
        self.lblPhone = QtGui.QLabel(self.tabBaseInfo)
        self.lblPhone.setObjectName(_fromUtf8("lblPhone"))
        self.gridLayout_6.addWidget(self.lblPhone, 11, 0, 1, 1)
        self.edtAccountant = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtAccountant.setObjectName(_fromUtf8("edtAccountant"))
        self.gridLayout_6.addWidget(self.edtAccountant, 10, 1, 1, 7)
        self.lblOKVED = QtGui.QLabel(self.tabBaseInfo)
        self.lblOKVED.setObjectName(_fromUtf8("lblOKVED"))
        self.gridLayout_6.addWidget(self.lblOKVED, 7, 0, 1, 1)
        self.lblTfomsCode = QtGui.QLabel(self.tabBaseInfo)
        self.lblTfomsCode.setScaledContents(False)
        self.lblTfomsCode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTfomsCode.setObjectName(_fromUtf8("lblTfomsCode"))
        self.gridLayout_6.addWidget(self.lblTfomsCode, 15, 0, 1, 1)
        self.lblAccountant = QtGui.QLabel(self.tabBaseInfo)
        self.lblAccountant.setObjectName(_fromUtf8("lblAccountant"))
        self.gridLayout_6.addWidget(self.lblAccountant, 10, 0, 1, 1)
        self.edtMiacCode = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtMiacCode.setObjectName(_fromUtf8("edtMiacCode"))
        self.gridLayout_6.addWidget(self.edtMiacCode, 16, 1, 1, 1)
        self.lblOKPO = QtGui.QLabel(self.tabBaseInfo)
        self.lblOKPO.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOKPO.setObjectName(_fromUtf8("lblOKPO"))
        self.gridLayout_6.addWidget(self.lblOKPO, 6, 2, 1, 1)
        self.lblUsishCode = QtGui.QLabel(self.tabBaseInfo)
        self.lblUsishCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUsishCode.setObjectName(_fromUtf8("lblUsishCode"))
        self.gridLayout_6.addWidget(self.lblUsishCode, 16, 2, 1, 1)
        self.edtPhone = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtPhone.setObjectName(_fromUtf8("edtPhone"))
        self.gridLayout_6.addWidget(self.edtPhone, 11, 1, 1, 7)
        self.edtUsishCode = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtUsishCode.setObjectName(_fromUtf8("edtUsishCode"))
        self.gridLayout_6.addWidget(self.edtUsishCode, 16, 3, 1, 5)
        self.edtOKPO = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtOKPO.setObjectName(_fromUtf8("edtOKPO"))
        self.gridLayout_6.addWidget(self.edtOKPO, 6, 3, 1, 3)
        self.edtOKVED = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtOKVED.setObjectName(_fromUtf8("edtOKVED"))
        self.gridLayout_6.addWidget(self.edtOKVED, 7, 1, 1, 1)
        self.lblNotes = QtGui.QLabel(self.tabBaseInfo)
        self.lblNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNotes.setObjectName(_fromUtf8("lblNotes"))
        self.gridLayout_6.addWidget(self.lblNotes, 23, 0, 1, 1)
        self.edtNotes = QtGui.QTextEdit(self.tabBaseInfo)
        self.edtNotes.setObjectName(_fromUtf8("edtNotes"))
        self.gridLayout_6.addWidget(self.edtNotes, 23, 1, 1, 7)
        self.lblIsSupplier = QtGui.QLabel(self.tabBaseInfo)
        self.lblIsSupplier.setObjectName(_fromUtf8("lblIsSupplier"))
        self.gridLayout_6.addWidget(self.lblIsSupplier, 20, 0, 1, 1)
        self.chkIsInsurer = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkIsInsurer.setText(_fromUtf8(""))
        self.chkIsInsurer.setObjectName(_fromUtf8("chkIsInsurer"))
        self.gridLayout_6.addWidget(self.chkIsInsurer, 18, 1, 1, 1)
        self.lblServiceStop = QtGui.QLabel(self.tabBaseInfo)
        self.lblServiceStop.setEnabled(False)
        self.lblServiceStop.setObjectName(_fromUtf8("lblServiceStop"))
        self.gridLayout_6.addWidget(self.lblServiceStop, 22, 2, 1, 1)
        self.chkCompulsoryServiceStop = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkCompulsoryServiceStop.setEnabled(False)
        self.chkCompulsoryServiceStop.setObjectName(_fromUtf8("chkCompulsoryServiceStop"))
        self.gridLayout_6.addWidget(self.chkCompulsoryServiceStop, 22, 4, 1, 1)
        self.cmbArea = CKLADRComboBox(self.tabBaseInfo)
        self.cmbArea.setEnabled(False)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout_6.addWidget(self.cmbArea, 21, 1, 1, 7)
        self.chkVoluntaryServiceStop = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkVoluntaryServiceStop.setEnabled(False)
        self.chkVoluntaryServiceStop.setObjectName(_fromUtf8("chkVoluntaryServiceStop"))
        self.gridLayout_6.addWidget(self.chkVoluntaryServiceStop, 22, 5, 1, 1)
        self.chkIsActive = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkIsActive.setText(_fromUtf8(""))
        self.chkIsActive.setObjectName(_fromUtf8("chkIsActive"))
        self.gridLayout_6.addWidget(self.chkIsActive, 19, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 22, 6, 1, 2)
        self.lblIsActive = QtGui.QLabel(self.tabBaseInfo)
        self.lblIsActive.setObjectName(_fromUtf8("lblIsActive"))
        self.gridLayout_6.addWidget(self.lblIsActive, 19, 0, 1, 1)
        self.lblArea = QtGui.QLabel(self.tabBaseInfo)
        self.lblArea.setEnabled(False)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.gridLayout_6.addWidget(self.lblArea, 21, 0, 1, 1)
        self.chkIsSupplier = QtGui.QCheckBox(self.tabBaseInfo)
        self.chkIsSupplier.setText(_fromUtf8(""))
        self.chkIsSupplier.setObjectName(_fromUtf8("chkIsSupplier"))
        self.gridLayout_6.addWidget(self.chkIsSupplier, 20, 1, 1, 1)
        self.edtEmail = QtGui.QLineEdit(self.tabBaseInfo)
        self.edtEmail.setMinimumSize(QtCore.QSize(0, 0))
        self.edtEmail.setMaximumSize(QtCore.QSize(285, 16777215))
        self.edtEmail.setObjectName(_fromUtf8("edtEmail"))
        self.gridLayout_6.addWidget(self.edtEmail, 13, 3, 1, 5)
        self.lblEmail = QtGui.QLabel(self.tabBaseInfo)
        self.lblEmail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.gridLayout_6.addWidget(self.lblEmail, 13, 2, 1, 1)
        self.lblChief = QtGui.QLabel(self.tabBaseInfo)
        self.lblChief.setObjectName(_fromUtf8("lblChief"))
        self.gridLayout_6.addWidget(self.lblChief, 8, 0, 1, 1)
        self.cmbChief = CPersonComboBoxEx(self.tabBaseInfo)
        self.cmbChief.setEnabled(True)
        self.cmbChief.setObjectName(_fromUtf8("cmbChief"))
        self.gridLayout_6.addWidget(self.cmbChief, 8, 1, 1, 7)
        self.tabWidget.addTab(self.tabBaseInfo, _fromUtf8(""))
        self.tabAccounts = QtGui.QWidget()
        self.tabAccounts.setObjectName(_fromUtf8("tabAccounts"))
        self.gridlayout = QtGui.QGridLayout(self.tabAccounts)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tblOrganisationAccounts = CInDocTableView(self.tabAccounts)
        self.tblOrganisationAccounts.setObjectName(_fromUtf8("tblOrganisationAccounts"))
        self.gridlayout.addWidget(self.tblOrganisationAccounts, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAccounts, _fromUtf8(""))
        self.tabLicense = QtGui.QWidget()
        self.tabLicense.setObjectName(_fromUtf8("tabLicense"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabLicense)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblLicense = CInDocTableView(self.tabLicense)
        self.tblLicense.setObjectName(_fromUtf8("tblLicense"))
        self.verticalLayout.addWidget(self.tblLicense)
        self.tabWidget.addTab(self.tabLicense, _fromUtf8(""))
        self.tabPolicySerials = QtGui.QWidget()
        self.tabPolicySerials.setObjectName(_fromUtf8("tabPolicySerials"))
        self.gridlayout1 = QtGui.QGridLayout(self.tabPolicySerials)
        self.gridlayout1.setMargin(4)
        self.gridlayout1.setSpacing(4)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.tblPolicySerials = CInDocTableView(self.tabPolicySerials)
        self.tblPolicySerials.setObjectName(_fromUtf8("tblPolicySerials"))
        self.gridlayout1.addWidget(self.tblPolicySerials, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPolicySerials, _fromUtf8(""))
        self.tabHospialBedProfiles = QtGui.QWidget()
        self.tabHospialBedProfiles.setObjectName(_fromUtf8("tabHospialBedProfiles"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabHospialBedProfiles)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblHospitalBedProfiles = CInDocTableView(self.tabHospialBedProfiles)
        self.tblHospitalBedProfiles.setObjectName(_fromUtf8("tblHospitalBedProfiles"))
        self.gridLayout_2.addWidget(self.tblHospitalBedProfiles, 1, 0, 1, 1)
        self.chkHBHideInactiveProfiles = QtGui.QCheckBox(self.tabHospialBedProfiles)
        self.chkHBHideInactiveProfiles.setChecked(True)
        self.chkHBHideInactiveProfiles.setObjectName(_fromUtf8("chkHBHideInactiveProfiles"))
        self.gridLayout_2.addWidget(self.chkHBHideInactiveProfiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabHospialBedProfiles, _fromUtf8(""))
        self.tabSpecialitys = QtGui.QWidget()
        self.tabSpecialitys.setObjectName(_fromUtf8("tabSpecialitys"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSpecialitys)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblSpecialitys = CInDocTableView(self.tabSpecialitys)
        self.tblSpecialitys.setObjectName(_fromUtf8("tblSpecialitys"))
        self.gridLayout_4.addWidget(self.tblSpecialitys, 1, 0, 1, 1)
        self.chkSpecHideInactiveProfiles = QtGui.QCheckBox(self.tabSpecialitys)
        self.chkSpecHideInactiveProfiles.setChecked(True)
        self.chkSpecHideInactiveProfiles.setObjectName(_fromUtf8("chkSpecHideInactiveProfiles"))
        self.gridLayout_4.addWidget(self.chkSpecHideInactiveProfiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpecialitys, _fromUtf8(""))
        self.tabServices = QtGui.QWidget()
        self.tabServices.setObjectName(_fromUtf8("tabServices"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabServices)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblServices = CInDocTableView(self.tabServices)
        self.tblServices.setObjectName(_fromUtf8("tblServices"))
        self.gridLayout_5.addWidget(self.tblServices, 1, 0, 1, 1)
        self.chkServiceHideInactiveProfiles = QtGui.QCheckBox(self.tabServices)
        self.chkServiceHideInactiveProfiles.setChecked(True)
        self.chkServiceHideInactiveProfiles.setObjectName(_fromUtf8("chkServiceHideInactiveProfiles"))
        self.gridLayout_5.addWidget(self.chkServiceHideInactiveProfiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabServices, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 3, 0, 1, 2)
        self.lblFullName.setBuddy(self.edtFullName)
        self.lblTitle.setBuddy(self.edtTitle)
        self.lblShortName.setBuddy(self.edtShortName)
        self.lblAddress.setBuddy(self.edtAddress)
        self.lblHead.setBuddy(self.cmbHead)
        self.lblOKATO.setBuddy(self.edtOKATO)
        self.lblOGRN.setBuddy(self.edtOGRN)
        self.lblOKPF.setBuddy(self.cmbOKPF)
        self.lblINN.setBuddy(self.edtINN)
        self.lblKPP.setBuddy(self.edtKPP)
        self.lblOKFS.setBuddy(self.cmbOKFS)
        self.lblIsHospital.setBuddy(self.cmbIsMedical)
        self.lblNet.setBuddy(self.cmbNet)
        self.lblMiacCode.setBuddy(self.edtMiacCode)
        self.lblFSS.setBuddy(self.edtFSS)
        self.lbSmoCode.setBuddy(self.edtSmoCode)
        self.lblTfomsExtCode.setBuddy(self.edtTfomsExtCode)
        self.lblIsInsurer.setBuddy(self.chkIsInsurer)
        self.lblPhone.setBuddy(self.edtPhone)
        self.lblOKVED.setBuddy(self.edtOKVED)
        self.lblTfomsCode.setBuddy(self.edtTfomsCode)
        self.lblAccountant.setBuddy(self.edtAccountant)
        self.lblOKPO.setBuddy(self.edtOKPO)
        self.lblUsishCode.setBuddy(self.edtUsishCode)
        self.lblNotes.setBuddy(self.edtNotes)
        self.lblServiceStop.setBuddy(self.chkCompulsoryServiceStop)
        self.lblArea.setBuddy(self.cmbArea)
        self.lblChief.setBuddy(self.edtChief)

        self.retranslateUi(OrgEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkIsInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbArea.setEnabled)
        QtCore.QObject.connect(self.chkIsInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkCompulsoryServiceStop.setEnabled)
        QtCore.QObject.connect(self.chkIsInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkVoluntaryServiceStop.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OrgEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OrgEditorDialog.reject)
        QtCore.QObject.connect(self.chkIsInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblArea.setEnabled)
        QtCore.QObject.connect(self.chkIsInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblServiceStop.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OrgEditorDialog)
        OrgEditorDialog.setTabOrder(self.edtFullName, self.edtShortName)
        OrgEditorDialog.setTabOrder(self.edtShortName, self.edtTitle)
        OrgEditorDialog.setTabOrder(self.edtTitle, self.tabWidget)
        OrgEditorDialog.setTabOrder(self.tabWidget, self.edtAddress)
        OrgEditorDialog.setTabOrder(self.edtAddress, self.chkKLADR)
        OrgEditorDialog.setTabOrder(self.chkKLADR, self.cmbKLADRCity)
        OrgEditorDialog.setTabOrder(self.cmbKLADRCity, self.cmbKLADRStreet)
        OrgEditorDialog.setTabOrder(self.cmbKLADRStreet, self.edtKLADRHouse)
        OrgEditorDialog.setTabOrder(self.edtKLADRHouse, self.edtKLADRCorpus)
        OrgEditorDialog.setTabOrder(self.edtKLADRCorpus, self.cmbHead)
        OrgEditorDialog.setTabOrder(self.cmbHead, self.btnSelectHeadOrganisation)
        OrgEditorDialog.setTabOrder(self.btnSelectHeadOrganisation, self.edtOGRN)
        OrgEditorDialog.setTabOrder(self.edtOGRN, self.edtINN)
        OrgEditorDialog.setTabOrder(self.edtINN, self.edtKPP)
        OrgEditorDialog.setTabOrder(self.edtKPP, self.edtFSS)
        OrgEditorDialog.setTabOrder(self.edtFSS, self.edtOKVED)
        OrgEditorDialog.setTabOrder(self.edtOKVED, self.edtOKATO)
        OrgEditorDialog.setTabOrder(self.edtOKATO, self.cmbOKPF)
        OrgEditorDialog.setTabOrder(self.cmbOKPF, self.cmbOKFS)
        OrgEditorDialog.setTabOrder(self.cmbOKFS, self.edtOKPO)
        OrgEditorDialog.setTabOrder(self.edtOKPO, self.cmbChief)
        OrgEditorDialog.setTabOrder(self.cmbChief, self.edtChief)
        OrgEditorDialog.setTabOrder(self.edtChief, self.edtAccountant)
        OrgEditorDialog.setTabOrder(self.edtAccountant, self.edtPhone)
        OrgEditorDialog.setTabOrder(self.edtPhone, self.edtSmoCode)
        OrgEditorDialog.setTabOrder(self.edtSmoCode, self.edtTfomsCode)
        OrgEditorDialog.setTabOrder(self.edtTfomsCode, self.edtMiacCode)
        OrgEditorDialog.setTabOrder(self.edtMiacCode, self.cmbIsMedical)
        OrgEditorDialog.setTabOrder(self.cmbIsMedical, self.edtEmail)
        OrgEditorDialog.setTabOrder(self.edtEmail, self.edtTfomsExtCode)
        OrgEditorDialog.setTabOrder(self.edtTfomsExtCode, self.edtUsishCode)
        OrgEditorDialog.setTabOrder(self.edtUsishCode, self.cmbNet)
        OrgEditorDialog.setTabOrder(self.cmbNet, self.chkIsInsurer)
        OrgEditorDialog.setTabOrder(self.chkIsInsurer, self.chkIsActive)
        OrgEditorDialog.setTabOrder(self.chkIsActive, self.chkIsSupplier)
        OrgEditorDialog.setTabOrder(self.chkIsSupplier, self.cmbArea)
        OrgEditorDialog.setTabOrder(self.cmbArea, self.chkCompulsoryServiceStop)
        OrgEditorDialog.setTabOrder(self.chkCompulsoryServiceStop, self.chkVoluntaryServiceStop)
        OrgEditorDialog.setTabOrder(self.chkVoluntaryServiceStop, self.edtNotes)
        OrgEditorDialog.setTabOrder(self.edtNotes, self.tblOrganisationAccounts)
        OrgEditorDialog.setTabOrder(self.tblOrganisationAccounts, self.tblLicense)
        OrgEditorDialog.setTabOrder(self.tblLicense, self.tblPolicySerials)
        OrgEditorDialog.setTabOrder(self.tblPolicySerials, self.chkHBHideInactiveProfiles)
        OrgEditorDialog.setTabOrder(self.chkHBHideInactiveProfiles, self.tblHospitalBedProfiles)
        OrgEditorDialog.setTabOrder(self.tblHospitalBedProfiles, self.chkSpecHideInactiveProfiles)
        OrgEditorDialog.setTabOrder(self.chkSpecHideInactiveProfiles, self.tblSpecialitys)
        OrgEditorDialog.setTabOrder(self.tblSpecialitys, self.chkServiceHideInactiveProfiles)
        OrgEditorDialog.setTabOrder(self.chkServiceHideInactiveProfiles, self.tblServices)
        OrgEditorDialog.setTabOrder(self.tblServices, self.tblIdentification)
        OrgEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, OrgEditorDialog):
        OrgEditorDialog.setWindowTitle(_translate("OrgEditorDialog", "ChangeMe!", None))
        self.lblFullName.setText(_translate("OrgEditorDialog", "&Полное наименование", None))
        self.lblTitle.setText(_translate("OrgEditorDialog", "Наименование для печати", None))
        self.lblShortName.setText(_translate("OrgEditorDialog", "&Наименование", None))
        self.lblAddress.setText(_translate("OrgEditorDialog", "Адрес", None))
        self.chkKLADR.setText(_translate("OrgEditorDialog", "КЛАДР", None))
        self.lblHead.setText(_translate("OrgEditorDialog", "&Головная организация", None))
        self.lblOKATO.setText(_translate("OrgEditorDialog", "ОКАТО", None))
        self.lblKLADRHouse.setText(_translate("OrgEditorDialog", "дом", None))
        self.lblKLADRCorpus.setText(_translate("OrgEditorDialog", "корп", None))
        self.lblOGRN.setText(_translate("OrgEditorDialog", "ОГРН", None))
        self.btnSelectHeadOrganisation.setText(_translate("OrgEditorDialog", "...", None))
        self.edtOGRN.setInputMask(_translate("OrgEditorDialog", "999999999999900; ", None))
        self.lblOKPF.setText(_translate("OrgEditorDialog", "ОКПФ", None))
        self.edtOKATO.setInputMask(_translate("OrgEditorDialog", "99999999999; ", None))
        self.lblINN.setText(_translate("OrgEditorDialog", "ИНН", None))
        self.edtINN.setInputMask(_translate("OrgEditorDialog", "999999999900; ", None))
        self.lblKPP.setText(_translate("OrgEditorDialog", "КПП", None))
        self.lblOKFS.setText(_translate("OrgEditorDialog", "ОКФС", None))
        self.edtFSS.setInputMask(_translate("OrgEditorDialog", "9999999999; ", None))
        self.edtKPP.setInputMask(_translate("OrgEditorDialog", "999999999; ", None))
        self.lblIsHospital.setText(_translate("OrgEditorDialog", "ЛПУ", None))
        self.edtTfomsExtCode.setToolTip(_translate("OrgEditorDialog", "Код в тер.фонде", None))
        self.cmbIsMedical.setItemText(0, _translate("OrgEditorDialog", "не определено", None))
        self.cmbIsMedical.setItemText(1, _translate("OrgEditorDialog", "поликлиника", None))
        self.cmbIsMedical.setItemText(2, _translate("OrgEditorDialog", "стационар", None))
        self.cmbIsMedical.setItemText(3, _translate("OrgEditorDialog", "прочая мед.организация", None))
        self.cmbIsMedical.setItemText(4, _translate("OrgEditorDialog", "СМП", None))
        self.cmbIsMedical.setItemText(5, _translate("OrgEditorDialog", "санаторного типа", None))
        self.lblNet.setText(_translate("OrgEditorDialog", "&Сеть", None))
        self.edtTfomsCode.setToolTip(_translate("OrgEditorDialog", "Код в тер.фонде", None))
        self.lblMiacCode.setText(_translate("OrgEditorDialog", "Код &МИАЦ", None))
        self.lblFSS.setText(_translate("OrgEditorDialog", "СФР", None))
        self.lbSmoCode.setText(_translate("OrgEditorDialog", "Код ФФОМС", None))
        self.lblTfomsExtCode.setToolTip(_translate("OrgEditorDialog", "<html><head/><body><p>Дополнительный код в ТФОМС,<br/>нужно в СПб</p></body></html>", None))
        self.lblTfomsExtCode.setText(_translate("OrgEditorDialog", "Дополнительный код ТФОМС", None))
        self.lblIsInsurer.setText(_translate("OrgEditorDialog", "Страховая компания", None))
        self.lblPhone.setText(_translate("OrgEditorDialog", "Телефон", None))
        self.lblOKVED.setText(_translate("OrgEditorDialog", "ОКВЭД", None))
        self.lblTfomsCode.setToolTip(_translate("OrgEditorDialog", "<html><head/><body><p>Код в ТФОМС</p></body></html>", None))
        self.lblTfomsCode.setText(_translate("OrgEditorDialog", "Код ТФОМС", None))
        self.lblAccountant.setText(_translate("OrgEditorDialog", "Гл.бухгалтер", None))
        self.lblOKPO.setText(_translate("OrgEditorDialog", "ОКПО", None))
        self.lblUsishCode.setText(_translate("OrgEditorDialog", "Код ЕГИСЗ", None))
        self.edtOKPO.setInputMask(_translate("OrgEditorDialog", "99999999; ", None))
        self.lblNotes.setText(_translate("OrgEditorDialog", "Примечания", None))
        self.lblIsSupplier.setText(_translate("OrgEditorDialog", "Поставщик", None))
        self.lblServiceStop.setText(_translate("OrgEditorDialog", "Приостановить обслуживание: ", None))
        self.chkCompulsoryServiceStop.setText(_translate("OrgEditorDialog", "ОМС", None))
        self.chkVoluntaryServiceStop.setText(_translate("OrgEditorDialog", "ДМС", None))
        self.lblIsActive.setText(_translate("OrgEditorDialog", "Организация активна", None))
        self.lblArea.setText(_translate("OrgEditorDialog", "Регион", None))
        self.lblEmail.setText(_translate("OrgEditorDialog", "E-mail", None))
        self.lblChief.setText(_translate("OrgEditorDialog", "Руководитель", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBaseInfo), _translate("OrgEditorDialog", "Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAccounts), _translate("OrgEditorDialog", "Раcчетные счета", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLicense), _translate("OrgEditorDialog", "Лицензии", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPolicySerials), _translate("OrgEditorDialog", "Серии полисов", None))
        self.chkHBHideInactiveProfiles.setText(_translate("OrgEditorDialog", "Скрывать не действующие профили", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospialBedProfiles), _translate("OrgEditorDialog", "Профили коек", None))
        self.chkSpecHideInactiveProfiles.setText(_translate("OrgEditorDialog", "Скрывать не действующие профили", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpecialitys), _translate("OrgEditorDialog", "Специальности", None))
        self.chkServiceHideInactiveProfiles.setText(_translate("OrgEditorDialog", "Скрывать не действующие профили", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServices), _translate("OrgEditorDialog", "Услуги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("OrgEditorDialog", "Идентификация", None))

from KLADR.kladrComboxes import CKLADRComboBox, CStreetComboBox
from OrgComboBox import COrgComboBox
from PersonComboBoxEx import CPersonComboBoxEx
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
