# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Orgs\ParamsContractDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParamsContractDialog(object):
    def setupUi(self, ParamsContractDialog):
        ParamsContractDialog.setObjectName(_fromUtf8("ParamsContractDialog"))
        ParamsContractDialog.resize(353, 269)
        self.gridLayout = QtGui.QGridLayout(ParamsContractDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ParamsContractDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 4)
        self.chkBase = QtGui.QCheckBox(ParamsContractDialog)
        self.chkBase.setChecked(False)
        self.chkBase.setObjectName(_fromUtf8("chkBase"))
        self.gridLayout.addWidget(self.chkBase, 1, 0, 1, 2)
        self.chkNumber = QtGui.QCheckBox(ParamsContractDialog)
        self.chkNumber.setObjectName(_fromUtf8("chkNumber"))
        self.gridLayout.addWidget(self.chkNumber, 2, 0, 1, 2)
        self.edtNumber = QtGui.QLineEdit(ParamsContractDialog)
        self.edtNumber.setEnabled(False)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 2, 2, 1, 2)
        self.edtDate = CDateEdit(ParamsContractDialog)
        self.edtDate.setEnabled(False)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 3, 2, 1, 2)
        self.edtBase = QtGui.QLineEdit(ParamsContractDialog)
        self.edtBase.setEnabled(False)
        self.edtBase.setObjectName(_fromUtf8("edtBase"))
        self.gridLayout.addWidget(self.edtBase, 1, 2, 1, 2)
        self.chkDate = QtGui.QCheckBox(ParamsContractDialog)
        self.chkDate.setObjectName(_fromUtf8("chkDate"))
        self.gridLayout.addWidget(self.chkDate, 3, 0, 1, 2)
        self.chkBegDate = QtGui.QCheckBox(ParamsContractDialog)
        self.chkBegDate.setObjectName(_fromUtf8("chkBegDate"))
        self.gridLayout.addWidget(self.chkBegDate, 4, 0, 1, 2)
        self.chkEndDate = QtGui.QCheckBox(ParamsContractDialog)
        self.chkEndDate.setObjectName(_fromUtf8("chkEndDate"))
        self.gridLayout.addWidget(self.chkEndDate, 5, 0, 1, 2)
        self.chkCoefficient = QtGui.QCheckBox(ParamsContractDialog)
        self.chkCoefficient.setObjectName(_fromUtf8("chkCoefficient"))
        self.gridLayout.addWidget(self.chkCoefficient, 6, 0, 1, 2)
        self.chkCoefficientEx = QtGui.QCheckBox(ParamsContractDialog)
        self.chkCoefficientEx.setObjectName(_fromUtf8("chkCoefficientEx"))
        self.gridLayout.addWidget(self.chkCoefficientEx, 7, 0, 1, 2)
        self.edtCoefficientEx = QtGui.QDoubleSpinBox(ParamsContractDialog)
        self.edtCoefficientEx.setEnabled(False)
        self.edtCoefficientEx.setDecimals(4)
        self.edtCoefficientEx.setMinimum(-99.9999)
        self.edtCoefficientEx.setMaximum(99.9999)
        self.edtCoefficientEx.setSingleStep(0.01)
        self.edtCoefficientEx.setProperty("value", 1.0)
        self.edtCoefficientEx.setObjectName(_fromUtf8("edtCoefficientEx"))
        self.gridLayout.addWidget(self.edtCoefficientEx, 7, 2, 1, 2)
        self.edtCoefficient = QtGui.QDoubleSpinBox(ParamsContractDialog)
        self.edtCoefficient.setEnabled(False)
        self.edtCoefficient.setDecimals(4)
        self.edtCoefficient.setMinimum(-99.9999)
        self.edtCoefficient.setMaximum(99.9999)
        self.edtCoefficient.setSingleStep(0.01)
        self.edtCoefficient.setProperty("value", 1.0)
        self.edtCoefficient.setObjectName(_fromUtf8("edtCoefficient"))
        self.gridLayout.addWidget(self.edtCoefficient, 6, 2, 1, 2)
        self.edtBegDate = CDateEdit(ParamsContractDialog)
        self.edtBegDate.setEnabled(False)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 4, 2, 1, 2)
        self.edtEndDate = CDateEdit(ParamsContractDialog)
        self.edtEndDate.setEnabled(False)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 5, 2, 1, 2)
        self.chkContractGroup = QtGui.QCheckBox(ParamsContractDialog)
        self.chkContractGroup.setObjectName(_fromUtf8("chkContractGroup"))
        self.gridLayout.addWidget(self.chkContractGroup, 0, 0, 1, 2)
        self.edtContractGroup = QtGui.QLineEdit(ParamsContractDialog)
        self.edtContractGroup.setEnabled(False)
        self.edtContractGroup.setObjectName(_fromUtf8("edtContractGroup"))
        self.gridLayout.addWidget(self.edtContractGroup, 0, 2, 1, 2)
        self.chkCoefficientEx2 = QtGui.QCheckBox(ParamsContractDialog)
        self.chkCoefficientEx2.setObjectName(_fromUtf8("chkCoefficientEx2"))
        self.gridLayout.addWidget(self.chkCoefficientEx2, 9, 0, 1, 2)
        self.edtCoefficientEx2 = QtGui.QDoubleSpinBox(ParamsContractDialog)
        self.edtCoefficientEx2.setEnabled(False)
        self.edtCoefficientEx2.setDecimals(4)
        self.edtCoefficientEx2.setMinimum(-99.9999)
        self.edtCoefficientEx2.setMaximum(99.9999)
        self.edtCoefficientEx2.setSingleStep(0.01)
        self.edtCoefficientEx2.setProperty("value", 1.0)
        self.edtCoefficientEx2.setObjectName(_fromUtf8("edtCoefficientEx2"))
        self.gridLayout.addWidget(self.edtCoefficientEx2, 9, 2, 1, 2)

        self.retranslateUi(ParamsContractDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ParamsContractDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ParamsContractDialog.reject)
        QtCore.QObject.connect(self.chkBase, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBase.setEnabled)
        QtCore.QObject.connect(self.chkNumber, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtNumber.setEnabled)
        QtCore.QObject.connect(self.chkDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtDate.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDate.setEnabled)
        QtCore.QObject.connect(self.chkEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDate.setEnabled)
        QtCore.QObject.connect(self.chkCoefficient, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCoefficient.setEnabled)
        QtCore.QObject.connect(self.chkCoefficientEx, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCoefficientEx.setEnabled)
        QtCore.QObject.connect(self.chkCoefficientEx2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCoefficientEx2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ParamsContractDialog)
        ParamsContractDialog.setTabOrder(self.chkContractGroup, self.edtContractGroup)
        ParamsContractDialog.setTabOrder(self.edtContractGroup, self.chkBase)
        ParamsContractDialog.setTabOrder(self.chkBase, self.edtBase)
        ParamsContractDialog.setTabOrder(self.edtBase, self.chkNumber)
        ParamsContractDialog.setTabOrder(self.chkNumber, self.edtNumber)
        ParamsContractDialog.setTabOrder(self.edtNumber, self.chkDate)
        ParamsContractDialog.setTabOrder(self.chkDate, self.edtDate)
        ParamsContractDialog.setTabOrder(self.edtDate, self.chkBegDate)
        ParamsContractDialog.setTabOrder(self.chkBegDate, self.edtBegDate)
        ParamsContractDialog.setTabOrder(self.edtBegDate, self.chkEndDate)
        ParamsContractDialog.setTabOrder(self.chkEndDate, self.edtEndDate)
        ParamsContractDialog.setTabOrder(self.edtEndDate, self.chkCoefficient)
        ParamsContractDialog.setTabOrder(self.chkCoefficient, self.edtCoefficient)
        ParamsContractDialog.setTabOrder(self.edtCoefficient, self.chkCoefficientEx)
        ParamsContractDialog.setTabOrder(self.chkCoefficientEx, self.edtCoefficientEx)
        ParamsContractDialog.setTabOrder(self.edtCoefficientEx, self.chkCoefficientEx2)
        ParamsContractDialog.setTabOrder(self.chkCoefficientEx2, self.edtCoefficientEx2)
        ParamsContractDialog.setTabOrder(self.edtCoefficientEx2, self.buttonBox)

    def retranslateUi(self, ParamsContractDialog):
        ParamsContractDialog.setWindowTitle(_translate("ParamsContractDialog", "Параметры", None))
        self.chkBase.setText(_translate("ParamsContractDialog", "Основание", None))
        self.chkNumber.setText(_translate("ParamsContractDialog", "Номер", None))
        self.chkDate.setText(_translate("ParamsContractDialog", "Дата", None))
        self.chkBegDate.setText(_translate("ParamsContractDialog", "Нач.дата", None))
        self.chkEndDate.setText(_translate("ParamsContractDialog", "Кон.дата", None))
        self.chkCoefficient.setText(_translate("ParamsContractDialog", "Коэффициент тарифа", None))
        self.chkCoefficientEx.setText(_translate("ParamsContractDialog", "Коэффициент расшир. тарифа", None))
        self.chkContractGroup.setText(_translate("ParamsContractDialog", "Группа", None))
        self.chkCoefficientEx2.setText(_translate("ParamsContractDialog", "Коэффициент второго расшир. тарифа", None))

from library.DateEdit import CDateEdit
