# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\appendix\regional\r23\importReestr\importRegistry.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(748, 863)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -119, 711, 921))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gbSnilsImport = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbSnilsImport.setObjectName(_fromUtf8("gbSnilsImport"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbSnilsImport)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblSnilsImport = QtGui.QLabel(self.gbSnilsImport)
        self.lblSnilsImport.setObjectName(_fromUtf8("lblSnilsImport"))
        self.horizontalLayout_2.addWidget(self.lblSnilsImport)
        self.edtSnilsFileName = QtGui.QLineEdit(self.gbSnilsImport)
        self.edtSnilsFileName.setObjectName(_fromUtf8("edtSnilsFileName"))
        self.horizontalLayout_2.addWidget(self.edtSnilsFileName)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnSelectSnilsFile = QtGui.QToolButton(self.gbSnilsImport)
        self.btnSelectSnilsFile.setObjectName(_fromUtf8("btnSelectSnilsFile"))
        self.horizontalLayout_2.addWidget(self.btnSelectSnilsFile)
        self.btnImportSnils = QtGui.QPushButton(self.gbSnilsImport)
        self.btnImportSnils.setEnabled(False)
        self.btnImportSnils.setObjectName(_fromUtf8("btnImportSnils"))
        self.horizontalLayout_2.addWidget(self.btnImportSnils)
        self.gridLayout_5.addWidget(self.gbSnilsImport, 6, 0, 1, 3)
        self.gbPrikImport = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbPrikImport.setObjectName(_fromUtf8("gbPrikImport"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbPrikImport)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnSelectPrikFile = QtGui.QToolButton(self.gbPrikImport)
        self.btnSelectPrikFile.setObjectName(_fromUtf8("btnSelectPrikFile"))
        self.gridLayout_3.addWidget(self.btnSelectPrikFile, 1, 2, 1, 1)
        self.btnImportPrik = QtGui.QPushButton(self.gbPrikImport)
        self.btnImportPrik.setEnabled(False)
        self.btnImportPrik.setObjectName(_fromUtf8("btnImportPrik"))
        self.gridLayout_3.addWidget(self.btnImportPrik, 1, 3, 1, 1)
        self.edtPrikFileName = QtGui.QLineEdit(self.gbPrikImport)
        self.edtPrikFileName.setObjectName(_fromUtf8("edtPrikFileName"))
        self.gridLayout_3.addWidget(self.edtPrikFileName, 1, 1, 1, 1)
        self.lblPrikDir = QtGui.QLabel(self.gbPrikImport)
        self.lblPrikDir.setObjectName(_fromUtf8("lblPrikDir"))
        self.gridLayout_3.addWidget(self.lblPrikDir, 1, 0, 1, 1)
        self.cbUpdate = QtGui.QCheckBox(self.gbPrikImport)
        self.cbUpdate.setObjectName(_fromUtf8("cbUpdate"))
        self.gridLayout_3.addWidget(self.cbUpdate, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbPrikImport, 5, 0, 1, 3)
        self.gbServiceImport = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbServiceImport.setObjectName(_fromUtf8("gbServiceImport"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbServiceImport)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblServiceDir = QtGui.QLabel(self.gbServiceImport)
        self.lblServiceDir.setObjectName(_fromUtf8("lblServiceDir"))
        self.gridLayout_2.addWidget(self.lblServiceDir, 6, 0, 1, 1)
        self.btnSelectServiceFile = QtGui.QToolButton(self.gbServiceImport)
        self.btnSelectServiceFile.setObjectName(_fromUtf8("btnSelectServiceFile"))
        self.gridLayout_2.addWidget(self.btnSelectServiceFile, 6, 2, 1, 1)
        self.edtServiceFileName = QtGui.QLineEdit(self.gbServiceImport)
        self.edtServiceFileName.setObjectName(_fromUtf8("edtServiceFileName"))
        self.gridLayout_2.addWidget(self.edtServiceFileName, 6, 1, 1, 1)
        self.btnImportService = QtGui.QPushButton(self.gbServiceImport)
        self.btnImportService.setEnabled(False)
        self.btnImportService.setObjectName(_fromUtf8("btnImportService"))
        self.gridLayout_2.addWidget(self.btnImportService, 6, 3, 1, 1)
        self.chkCopyToMes = QtGui.QCheckBox(self.gbServiceImport)
        self.chkCopyToMes.setObjectName(_fromUtf8("chkCopyToMes"))
        self.gridLayout_2.addWidget(self.chkCopyToMes, 4, 0, 1, 1)
        self.chkRecognizeNomenclature = QtGui.QCheckBox(self.gbServiceImport)
        self.chkRecognizeNomenclature.setEnabled(False)
        self.chkRecognizeNomenclature.setChecked(True)
        self.chkRecognizeNomenclature.setObjectName(_fromUtf8("chkRecognizeNomenclature"))
        self.gridLayout_2.addWidget(self.chkRecognizeNomenclature, 1, 0, 1, 1)
        self.chkCopyToActionType = QtGui.QCheckBox(self.gbServiceImport)
        self.chkCopyToActionType.setObjectName(_fromUtf8("chkCopyToActionType"))
        self.gridLayout_2.addWidget(self.chkCopyToActionType, 3, 0, 1, 1)
        self.chkfillEIS = QtGui.QCheckBox(self.gbServiceImport)
        self.chkfillEIS.setChecked(True)
        self.chkfillEIS.setObjectName(_fromUtf8("chkfillEIS"))
        self.gridLayout_2.addWidget(self.chkfillEIS, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbServiceImport, 4, 0, 1, 3)
        self.gbAttachImport = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbAttachImport.setObjectName(_fromUtf8("gbAttachImport"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbAttachImport)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 3)
        self.btnImportAttach = QtGui.QPushButton(self.gbAttachImport)
        self.btnImportAttach.setEnabled(False)
        self.btnImportAttach.setObjectName(_fromUtf8("btnImportAttach"))
        self.gridLayout_4.addWidget(self.btnImportAttach, 2, 3, 1, 1)
        self.edtAttachURL = QtGui.QLineEdit(self.gbAttachImport)
        self.edtAttachURL.setObjectName(_fromUtf8("edtAttachURL"))
        self.gridLayout_4.addWidget(self.edtAttachURL, 1, 0, 1, 4)
        self.edtImportAttachActDate = QtGui.QDateEdit(self.gbAttachImport)
        self.edtImportAttachActDate.setObjectName(_fromUtf8("edtImportAttachActDate"))
        self.gridLayout_4.addWidget(self.edtImportAttachActDate, 4, 2, 1, 1)
        self.prbAttachImport = QtGui.QProgressBar(self.gbAttachImport)
        self.prbAttachImport.setProperty("value", 24)
        self.prbAttachImport.setTextVisible(True)
        self.prbAttachImport.setObjectName(_fromUtf8("prbAttachImport"))
        self.gridLayout_4.addWidget(self.prbAttachImport, 7, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 0, 1, 1)
        self.lblAttachImport = QtGui.QLabel(self.gbAttachImport)
        self.lblAttachImport.setObjectName(_fromUtf8("lblAttachImport"))
        self.gridLayout_4.addWidget(self.lblAttachImport, 0, 0, 1, 3)
        self.label = QtGui.QLabel(self.gbAttachImport)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 1, 1, 1)
        self.btnImportAttachAct = QtGui.QPushButton(self.gbAttachImport)
        self.btnImportAttachAct.setEnabled(False)
        self.btnImportAttachAct.setObjectName(_fromUtf8("btnImportAttachAct"))
        self.gridLayout_4.addWidget(self.btnImportAttachAct, 4, 3, 1, 1)
        self.gbImportClientKTFOMS = QtGui.QGroupBox(self.gbAttachImport)
        self.gbImportClientKTFOMS.setObjectName(_fromUtf8("gbImportClientKTFOMS"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gbImportClientKTFOMS)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cbSetAttach = QtGui.QCheckBox(self.gbImportClientKTFOMS)
        self.cbSetAttach.setObjectName(_fromUtf8("cbSetAttach"))
        self.horizontalLayout_5.addWidget(self.cbSetAttach)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btnImportClient = QtGui.QPushButton(self.gbImportClientKTFOMS)
        self.btnImportClient.setObjectName(_fromUtf8("btnImportClient"))
        self.horizontalLayout_5.addWidget(self.btnImportClient)
        self.gridLayout_4.addWidget(self.gbImportClientKTFOMS, 8, 0, 1, 4)
        self.btnImportDeattachMO = QtGui.QPushButton(self.gbAttachImport)
        self.btnImportDeattachMO.setEnabled(False)
        self.btnImportDeattachMO.setObjectName(_fromUtf8("btnImportDeattachMO"))
        self.gridLayout_4.addWidget(self.btnImportDeattachMO, 5, 3, 1, 1)
        self.lblDeattachMO = QtGui.QLabel(self.gbAttachImport)
        self.lblDeattachMO.setObjectName(_fromUtf8("lblDeattachMO"))
        self.gridLayout_4.addWidget(self.lblDeattachMO, 5, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 5, 0, 1, 2)
        self.gridLayout_5.addWidget(self.gbAttachImport, 8, 0, 1, 3)
        self.gbMedpolImport = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbMedpolImport.setObjectName(_fromUtf8("gbMedpolImport"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gbMedpolImport)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblMedpolImport = QtGui.QLabel(self.gbMedpolImport)
        self.lblMedpolImport.setObjectName(_fromUtf8("lblMedpolImport"))
        self.horizontalLayout_3.addWidget(self.lblMedpolImport)
        self.edtMedpolFileName = QtGui.QLineEdit(self.gbMedpolImport)
        self.edtMedpolFileName.setObjectName(_fromUtf8("edtMedpolFileName"))
        self.horizontalLayout_3.addWidget(self.edtMedpolFileName)
        self.btnSelectMedpolFile = QtGui.QToolButton(self.gbMedpolImport)
        self.btnSelectMedpolFile.setObjectName(_fromUtf8("btnSelectMedpolFile"))
        self.horizontalLayout_3.addWidget(self.btnSelectMedpolFile)
        self.btnImportMedpol = QtGui.QPushButton(self.gbMedpolImport)
        self.btnImportMedpol.setEnabled(False)
        self.btnImportMedpol.setObjectName(_fromUtf8("btnImportMedpol"))
        self.horizontalLayout_3.addWidget(self.btnImportMedpol)
        self.gridLayout_5.addWidget(self.gbMedpolImport, 7, 0, 1, 3)
        self.gbUpdateParusPerson = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbUpdateParusPerson.setObjectName(_fromUtf8("gbUpdateParusPerson"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbUpdateParusPerson)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.btnUpdateParusPerson = QtGui.QPushButton(self.gbUpdateParusPerson)
        self.btnUpdateParusPerson.setObjectName(_fromUtf8("btnUpdateParusPerson"))
        self.horizontalLayout_4.addWidget(self.btnUpdateParusPerson)
        self.gridLayout_5.addWidget(self.gbUpdateParusPerson, 9, 0, 1, 3)
        self.gbImportDispSettings = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbImportDispSettings.setObjectName(_fromUtf8("gbImportDispSettings"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.gbImportDispSettings)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblImportDispSettings = QtGui.QLabel(self.gbImportDispSettings)
        self.lblImportDispSettings.setObjectName(_fromUtf8("lblImportDispSettings"))
        self.horizontalLayout_6.addWidget(self.lblImportDispSettings)
        self.edtDispSettingsFileName = QtGui.QLineEdit(self.gbImportDispSettings)
        self.edtDispSettingsFileName.setObjectName(_fromUtf8("edtDispSettingsFileName"))
        self.horizontalLayout_6.addWidget(self.edtDispSettingsFileName)
        self.btnSelectImportDispFile = QtGui.QToolButton(self.gbImportDispSettings)
        self.btnSelectImportDispFile.setObjectName(_fromUtf8("btnSelectImportDispFile"))
        self.horizontalLayout_6.addWidget(self.btnSelectImportDispFile)
        self.btnImportDispSettings = QtGui.QPushButton(self.gbImportDispSettings)
        self.btnImportDispSettings.setEnabled(False)
        self.btnImportDispSettings.setObjectName(_fromUtf8("btnImportDispSettings"))
        self.horizontalLayout_6.addWidget(self.btnImportDispSettings)
        self.gridLayout_5.addWidget(self.gbImportDispSettings, 10, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(268, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btnImport = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnImport.setEnabled(False)
        self.btnImport.setCheckable(False)
        self.btnImport.setAutoDefault(True)
        self.btnImport.setDefault(True)
        self.btnImport.setFlat(False)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.horizontalLayout.addWidget(self.btnImport)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 0, 1, 3)
        self.btnSelectMainDataFile = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectMainDataFile.setObjectName(_fromUtf8("btnSelectMainDataFile"))
        self.gridLayout_5.addWidget(self.btnSelectMainDataFile, 2, 2, 1, 1)
        self.edtMainDataFileName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtMainDataFileName.setEnabled(True)
        self.edtMainDataFileName.setObjectName(_fromUtf8("edtMainDataFileName"))
        self.gridLayout_5.addWidget(self.edtMainDataFileName, 2, 1, 1, 1)
        self.lblMainDataFileName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblMainDataFileName.setEnabled(True)
        self.lblMainDataFileName.setObjectName(_fromUtf8("lblMainDataFileName"))
        self.gridLayout_5.addWidget(self.lblMainDataFileName, 2, 0, 1, 1)
        self.chkImportClients = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkImportClients.setObjectName(_fromUtf8("chkImportClients"))
        self.gridLayout_5.addWidget(self.chkImportClients, 1, 0, 1, 3)
        self.btnSelectRBDir = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnSelectRBDir.setObjectName(_fromUtf8("btnSelectRBDir"))
        self.gridLayout_5.addWidget(self.btnSelectRBDir, 0, 2, 1, 1)
        self.edtRBDirName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtRBDirName.setObjectName(_fromUtf8("edtRBDirName"))
        self.gridLayout_5.addWidget(self.edtRBDirName, 0, 1, 1, 1)
        self.lblRefBooksDirName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblRefBooksDirName.setObjectName(_fromUtf8("lblRefBooksDirName"))
        self.gridLayout_5.addWidget(self.lblRefBooksDirName, 0, 0, 1, 1)
        self.gbImportCovidReestr = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.gbImportCovidReestr.setObjectName(_fromUtf8("gbImportCovidReestr"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gbImportCovidReestr)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblImportCovidReestr = QtGui.QLabel(self.gbImportCovidReestr)
        self.lblImportCovidReestr.setObjectName(_fromUtf8("lblImportCovidReestr"))
        self.horizontalLayout_7.addWidget(self.lblImportCovidReestr)
        self.edtCovidReestrFileName = QtGui.QLineEdit(self.gbImportCovidReestr)
        self.edtCovidReestrFileName.setObjectName(_fromUtf8("edtCovidReestrFileName"))
        self.horizontalLayout_7.addWidget(self.edtCovidReestrFileName)
        self.btnSelectImportCovidReestrFile = QtGui.QToolButton(self.gbImportCovidReestr)
        self.btnSelectImportCovidReestrFile.setObjectName(_fromUtf8("btnSelectImportCovidReestrFile"))
        self.horizontalLayout_7.addWidget(self.btnSelectImportCovidReestrFile)
        self.btnImportCovidReestr = QtGui.QPushButton(self.gbImportCovidReestr)
        self.btnImportCovidReestr.setEnabled(False)
        self.btnImportCovidReestr.setObjectName(_fromUtf8("btnImportCovidReestr"))
        self.horizontalLayout_7.addWidget(self.btnImportCovidReestr)
        self.gridLayout_5.addWidget(self.gbImportCovidReestr, 11, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actLogin = QtGui.QAction(MainWindow)
        self.actLogin.setObjectName(_fromUtf8("actLogin"))
        self.actLogout = QtGui.QAction(MainWindow)
        self.actLogout.setObjectName(_fromUtf8("actLogout"))
        self.actQuit = QtGui.QAction(MainWindow)
        self.actQuit.setObjectName(_fromUtf8("actQuit"))
        self.actConnection = QtGui.QAction(MainWindow)
        self.actConnection.setObjectName(_fromUtf8("actConnection"))
        self.actDecor = QtGui.QAction(MainWindow)
        self.actDecor.setObjectName(_fromUtf8("actDecor"))
        self.menuFile.addAction(self.actLogin)
        self.menuFile.addAction(self.actLogout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actQuit)
        self.menuPreferences.addAction(self.actConnection)
        self.menuPreferences.addAction(self.actDecor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.label.setBuddy(self.edtImportAttachActDate)
        self.lblMainDataFileName.setBuddy(self.edtMainDataFileName)
        self.lblRefBooksDirName.setBuddy(self.edtRBDirName)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.chkImportClients, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMainDataFileName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Импорт реестра застрахованного населения для Краснодарского края", None))
        self.gbSnilsImport.setTitle(_translate("MainWindow", "Импорт базы льготников ПФР", None))
        self.lblSnilsImport.setText(_translate("MainWindow", "Файл с реестром льготников", None))
        self.btnSelectSnilsFile.setText(_translate("MainWindow", "...", None))
        self.btnImportSnils.setText(_translate("MainWindow", "Импорт", None))
        self.gbPrikImport.setTitle(_translate("MainWindow", "Импорт прикрепленного населения", None))
        self.btnSelectPrikFile.setText(_translate("MainWindow", "...", None))
        self.btnImportPrik.setText(_translate("MainWindow", "Импорт", None))
        self.edtPrikFileName.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Укажите местонахождение файла</span><span style=\" font-size:8pt; font-weight:600;\"> spr18.dbf </span><span style=\" font-size:8pt;\">в формате, определенном Положением о порядке информационного обмена в системе обязательного медицинского страхования на территории Краснодарского края Версии 8.0</span></p></body></html>", None))
        self.lblPrikDir.setText(_translate("MainWindow", "Файл с реестром населения", None))
        self.cbUpdate.setText(_translate("MainWindow", "Обновлять полисные и паспортные данные идентифицированных пациентов", None))
        self.gbServiceImport.setTitle(_translate("MainWindow", "Импорт услуг", None))
        self.lblServiceDir.setText(_translate("MainWindow", "Справочник с услугами", None))
        self.btnSelectServiceFile.setText(_translate("MainWindow", "...", None))
        self.edtServiceFileName.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Укажите местонахождение файла</span><span style=\" font-size:8pt; font-weight:600;\"> spr18.dbf </span><span style=\" font-size:8pt;\">в формате, определенном Положением о порядке информационного обмена в системе обязательного медицинского страхования на территории Краснодарского края Версии 8.0</span></p></body></html>", None))
        self.btnImportService.setText(_translate("MainWindow", "Импорт", None))
        self.chkCopyToMes.setText(_translate("MainWindow", "Дублировать в МЭС", None))
        self.chkRecognizeNomenclature.setText(_translate("MainWindow", "Идентифицировать номенклатурные услуги", None))
        self.chkCopyToActionType.setText(_translate("MainWindow", "Дублировать в типы действий", None))
        self.chkfillEIS.setText(_translate("MainWindow", "Заполнять наследование ЕИС", None))
        self.gbAttachImport.setTitle(_translate("MainWindow", "Регистр прикрепленного населения ТФОМС", None))
        self.btnImportAttach.setText(_translate("MainWindow", "Импорт", None))
        self.prbAttachImport.setFormat(_translate("MainWindow", "%v из %m", None))
        self.lblAttachImport.setText(_translate("MainWindow", "Путь к сервису", None))
        self.label.setText(_translate("MainWindow", "Импорт согласно актам-сверок:", None))
        self.btnImportAttachAct.setText(_translate("MainWindow", "Импорт", None))
        self.gbImportClientKTFOMS.setTitle(_translate("MainWindow", "Импорт прикрепленных граждан по версии ТФОМС, отсутствующих в МИС", None))
        self.cbSetAttach.setText(_translate("MainWindow", "Прикреплять людей к участку", None))
        self.btnImportClient.setText(_translate("MainWindow", "Импорт", None))
        self.btnImportDeattachMO.setText(_translate("MainWindow", "Импорт", None))
        self.lblDeattachMO.setText(_translate("MainWindow", "Получить запросы на открепление из других МО:", None))
        self.gbMedpolImport.setTitle(_translate("MainWindow", "Импорт справочников медикаментов", None))
        self.lblMedpolImport.setText(_translate("MainWindow", "Файл со справочниками", None))
        self.btnSelectMedpolFile.setText(_translate("MainWindow", "...", None))
        self.btnImportMedpol.setText(_translate("MainWindow", "Импорт", None))
        self.gbUpdateParusPerson.setTitle(_translate("MainWindow", "Импорт мед работников из Парус-8", None))
        self.btnUpdateParusPerson.setText(_translate("MainWindow", "Импорт", None))
        self.gbImportDispSettings.setTitle(_translate("MainWindow", "Импорт настроек всеобщей диспансеризации", None))
        self.lblImportDispSettings.setText(_translate("MainWindow", "Файл с настройками всеобщей диспансеризации", None))
        self.btnSelectImportDispFile.setText(_translate("MainWindow", "...", None))
        self.btnImportDispSettings.setText(_translate("MainWindow", "Импорт", None))
        self.btnImport.setText(_translate("MainWindow", "Начать импорт", None))
        self.btnSelectMainDataFile.setText(_translate("MainWindow", "...", None))
        self.edtMainDataFileName.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Файл с реестром населения в формате</span><span style=\" font-size:8pt; font-style:italic;\"> </span><span style=\" font-size:8pt; font-weight:600;\">DBF</span><span style=\" font-size:8pt;\">, содержащий следующие необходимые поля: SNILS, FAM, IM, OTCH, POL, DATR, POLIS_S, POLIS_N, SMO, DATN, DATK, INNRAB,KPPRAB,MRAB,OKVED</span></p></body></html>", None))
        self.lblMainDataFileName.setText(_translate("MainWindow", "Файл с реестром населения", None))
        self.chkImportClients.setText(_translate("MainWindow", "Импорт населения", None))
        self.btnSelectRBDir.setText(_translate("MainWindow", "...", None))
        self.edtRBDirName.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Каталог, содержащий следующие справочники:<span style=\" font-weight:600;\"> spr01.dbf</span>, <span style=\" font-weight:600;\">spr02.dbf</span>, <span style=\" font-weight:600;\">spr81.dbf </span>в форматах, определенных Положением о порядке информационного обмена в системе обязательного медицинского страхования на территории Краснодарского края Версии 19.0</p></body></html>", None))
        self.lblRefBooksDirName.setText(_translate("MainWindow", "Каталог со справочниками", None))
        self.gbImportCovidReestr.setTitle(_translate("MainWindow", "Импорт данных Ковидного регистра", None))
        self.lblImportCovidReestr.setText(_translate("MainWindow", "Путь к файлу", None))
        self.btnSelectImportCovidReestrFile.setText(_translate("MainWindow", "...", None))
        self.btnImportCovidReestr.setText(_translate("MainWindow", "Импорт", None))
        self.menuFile.setTitle(_translate("MainWindow", "Сессия", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Настройки", None))
        self.actLogin.setText(_translate("MainWindow", "Подключиться к базе данных", None))
        self.actLogout.setText(_translate("MainWindow", "Отключиться от базы данных", None))
        self.actQuit.setText(_translate("MainWindow", "Закрыть программу", None))
        self.actConnection.setText(_translate("MainWindow", "База данных", None))
        self.actDecor.setText(_translate("MainWindow", "Внешний вид", None))

