# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dmitrii/s11/Notifications/NotificationRuleEditorDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NotificationRuleEditorDialog(object):
    def setupUi(self, NotificationRuleEditorDialog):
        NotificationRuleEditorDialog.setObjectName(_fromUtf8("NotificationRuleEditorDialog"))
        NotificationRuleEditorDialog.resize(513, 798)
        NotificationRuleEditorDialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(NotificationRuleEditorDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblClass = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 1, 0, 1, 2)
        self.cmbType = QtGui.QComboBox(NotificationRuleEditorDialog)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbType, 2, 2, 1, 1)
        self.lblMultiplicity = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblMultiplicity.setObjectName(_fromUtf8("lblMultiplicity"))
        self.gridLayout.addWidget(self.lblMultiplicity, 6, 0, 1, 2)
        self.edtMultiplicity = QtGui.QSpinBox(NotificationRuleEditorDialog)
        self.edtMultiplicity.setEnabled(False)
        self.edtMultiplicity.setObjectName(_fromUtf8("edtMultiplicity"))
        self.gridLayout.addWidget(self.edtMultiplicity, 6, 2, 1, 1)
        self.cmbActionType = CRBComboBox(NotificationRuleEditorDialog)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 4, 2, 1, 1)
        self.lblType = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 2, 0, 1, 2)
        self.lblTerm = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblTerm.setObjectName(_fromUtf8("lblTerm"))
        self.gridLayout.addWidget(self.lblTerm, 7, 0, 1, 2)
        self.cmbClass = QtGui.QComboBox(NotificationRuleEditorDialog)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClass, 1, 2, 1, 1)
        self.cmbCondition = QtGui.QComboBox(NotificationRuleEditorDialog)
        self.cmbCondition.setObjectName(_fromUtf8("cmbCondition"))
        self.cmbCondition.addItem(_fromUtf8(""))
        self.cmbCondition.addItem(_fromUtf8(""))
        self.cmbCondition.addItem(_fromUtf8(""))
        self.cmbCondition.addItem(_fromUtf8(""))
        self.cmbCondition.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbCondition, 3, 2, 1, 1)
        self.lblActionType = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 4, 0, 1, 2)
        self.lblTemplate = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblTemplate.setObjectName(_fromUtf8("lblTemplate"))
        self.gridLayout.addWidget(self.lblTemplate, 19, 0, 1, 2)
        self.edtTerm = QtGui.QSpinBox(NotificationRuleEditorDialog)
        self.edtTerm.setEnabled(False)
        self.edtTerm.setObjectName(_fromUtf8("edtTerm"))
        self.gridLayout.addWidget(self.edtTerm, 7, 2, 1, 1)
        self.cmbAppointmentType = QtGui.QComboBox(NotificationRuleEditorDialog)
        self.cmbAppointmentType.setObjectName(_fromUtf8("cmbAppointmentType"))
        self.gridLayout.addWidget(self.cmbAppointmentType, 8, 2, 1, 1)
        self.chkIsRestricted = QtGui.QCheckBox(NotificationRuleEditorDialog)
        self.chkIsRestricted.setObjectName(_fromUtf8("chkIsRestricted"))
        self.gridLayout.addWidget(self.chkIsRestricted, 9, 0, 1, 3)
        self.lblAttachedFile = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblAttachedFile.setObjectName(_fromUtf8("lblAttachedFile"))
        self.gridLayout.addWidget(self.lblAttachedFile, 16, 0, 1, 2)
        self.cmbAttachedFile = QtGui.QComboBox(NotificationRuleEditorDialog)
        self.cmbAttachedFile.setObjectName(_fromUtf8("cmbAttachedFile"))
        self.cmbAttachedFile.addItem(_fromUtf8(""))
        self.cmbAttachedFile.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAttachedFile, 16, 2, 1, 1)
        self.lblAppointmentType = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblAppointmentType.setObjectName(_fromUtf8("lblAppointmentType"))
        self.gridLayout.addWidget(self.lblAppointmentType, 8, 0, 1, 2)
        self.lblKind = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout.addWidget(self.lblKind, 17, 0, 1, 2)
        self.tblNotificationKind = CInDocTableView(NotificationRuleEditorDialog)
        self.tblNotificationKind.setObjectName(_fromUtf8("tblNotificationKind"))
        self.gridLayout.addWidget(self.tblNotificationKind, 18, 0, 1, 3)
        self.edtTemplate = QtGui.QTextEdit(NotificationRuleEditorDialog)
        self.edtTemplate.setObjectName(_fromUtf8("edtTemplate"))
        self.gridLayout.addWidget(self.edtTemplate, 20, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(NotificationRuleEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 21, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(103, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 22, 0, 1, 2)
        self.edtName = QtGui.QLineEdit(NotificationRuleEditorDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 0, 2, 1, 1)
        self.lblReceivingActionType = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblReceivingActionType.setObjectName(_fromUtf8("lblReceivingActionType"))
        self.gridLayout.addWidget(self.lblReceivingActionType, 14, 0, 1, 2)
        self.lblName = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 2)
        self.lblCondition = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblCondition.setObjectName(_fromUtf8("lblCondition"))
        self.gridLayout.addWidget(self.lblCondition, 3, 0, 1, 2)
        self.lblExpiration = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblExpiration.setObjectName(_fromUtf8("lblExpiration"))
        self.gridLayout.addWidget(self.lblExpiration, 5, 0, 1, 2)
        self.edtExpiration = QtGui.QSpinBox(NotificationRuleEditorDialog)
        self.edtExpiration.setEnabled(False)
        self.edtExpiration.setObjectName(_fromUtf8("edtExpiration"))
        self.gridLayout.addWidget(self.edtExpiration, 5, 2, 1, 1)
        self.chkIgnoreToday = QtGui.QCheckBox(NotificationRuleEditorDialog)
        self.chkIgnoreToday.setObjectName(_fromUtf8("chkIgnoreToday"))
        self.gridLayout.addWidget(self.chkIgnoreToday, 10, 0, 1, 3)
        self.chkAllowConfirm = QtGui.QCheckBox(NotificationRuleEditorDialog)
        self.chkAllowConfirm.setObjectName(_fromUtf8("chkAllowConfirm"))
        self.gridLayout.addWidget(self.chkAllowConfirm, 11, 0, 1, 3)
        self.chkTransferred = QtGui.QCheckBox(NotificationRuleEditorDialog)
        self.chkTransferred.setObjectName(_fromUtf8("chkTransferred"))
        self.gridLayout.addWidget(self.chkTransferred, 12, 0, 2, 2)
        self.cmbReceivingActionType = CActionTypeComboBox(NotificationRuleEditorDialog)
        self.cmbReceivingActionType.setObjectName(_fromUtf8("cmbReceivingActionType"))
        self.gridLayout.addWidget(self.cmbReceivingActionType, 14, 2, 1, 1)
        self.lblObsDescr = QtGui.QLabel(NotificationRuleEditorDialog)
        self.lblObsDescr.setObjectName(_fromUtf8("lblObsDescr"))
        self.gridLayout.addWidget(self.lblObsDescr, 15, 0, 1, 2)
        self.edtObsDescr = QtGui.QLineEdit(NotificationRuleEditorDialog)
        self.edtObsDescr.setObjectName(_fromUtf8("edtObsDescr"))
        self.gridLayout.addWidget(self.edtObsDescr, 15, 2, 1, 1)

        self.retranslateUi(NotificationRuleEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NotificationRuleEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NotificationRuleEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NotificationRuleEditorDialog)

    def retranslateUi(self, NotificationRuleEditorDialog):
        NotificationRuleEditorDialog.setWindowTitle(_translate("NotificationRuleEditorDialog", "Правило оповещения", None))
        self.lblClass.setText(_translate("NotificationRuleEditorDialog", "Класс", None))
        self.cmbType.setItemText(0, _translate("NotificationRuleEditorDialog", "расписание", None))
        self.cmbType.setItemText(1, _translate("NotificationRuleEditorDialog", "картотека", None))
        self.cmbType.setItemText(2, _translate("NotificationRuleEditorDialog", "действие", None))
        self.lblMultiplicity.setText(_translate("NotificationRuleEditorDialog", "Кратность", None))
        self.cmbActionType.setWhatsThis(_translate("NotificationRuleEditorDialog", "результат осмотра", None))
        self.lblType.setText(_translate("NotificationRuleEditorDialog", "Тип", None))
        self.lblTerm.setText(_translate("NotificationRuleEditorDialog", "Срок", None))
        self.cmbClass.setItemText(0, _translate("NotificationRuleEditorDialog", "ручной", None))
        self.cmbClass.setItemText(1, _translate("NotificationRuleEditorDialog", "автоматический", None))
        self.cmbCondition.setItemText(0, _translate("NotificationRuleEditorDialog", "подтверждение записи", None))
        self.cmbCondition.setItemText(1, _translate("NotificationRuleEditorDialog", "напоминание", None))
        self.cmbCondition.setItemText(2, _translate("NotificationRuleEditorDialog", "отмена записи", None))
        self.cmbCondition.setItemText(3, _translate("NotificationRuleEditorDialog", "опрос", None))
        self.cmbCondition.setItemText(4, _translate("NotificationRuleEditorDialog", "отправка результата", None))
        self.lblActionType.setText(_translate("NotificationRuleEditorDialog", "Тип действия", None))
        self.lblTemplate.setText(_translate("NotificationRuleEditorDialog", "Шаблон", None))
        self.chkIsRestricted.setText(_translate("NotificationRuleEditorDialog", "Обрабатывать только при наличии прав", None))
        self.lblAttachedFile.setText(_translate("NotificationRuleEditorDialog", "Прикрепление файла", None))
        self.cmbAttachedFile.setItemText(0, _translate("NotificationRuleEditorDialog", "Нет", None))
        self.cmbAttachedFile.setItemText(1, _translate("NotificationRuleEditorDialog", "Да", None))
        self.lblAppointmentType.setText(_translate("NotificationRuleEditorDialog", "Тип приёма", None))
        self.lblKind.setText(_translate("NotificationRuleEditorDialog", "Вид", None))
        self.lblReceivingActionType.setText(_translate("NotificationRuleEditorDialog", "Тип действия для подтверждения", None))
        self.lblName.setText(_translate("NotificationRuleEditorDialog", "Наименование", None))
        self.lblCondition.setText(_translate("NotificationRuleEditorDialog", "Условие", None))
        self.lblExpiration.setText(_translate("NotificationRuleEditorDialog", "Период отправки опроса", None))
        self.chkIgnoreToday.setText(_translate("NotificationRuleEditorDialog", "Ограничение отправки при записи на текущий день", None))
        self.chkAllowConfirm.setText(_translate("NotificationRuleEditorDialog", "Разрешено ручное подтверждение оповещения", None))
        self.chkTransferred.setText(_translate("NotificationRuleEditorDialog", "Передавать в мед. карту", None))
        self.lblObsDescr.setText(_translate("NotificationRuleEditorDialog", "Описание свойства действия", None))

from Events.ActionTypeComboBox import CActionTypeComboBox
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NotificationRuleEditorDialog = QtGui.QDialog()
    ui = Ui_NotificationRuleEditorDialog()
    ui.setupUi(NotificationRuleEditorDialog)
    NotificationRuleEditorDialog.show()
    sys.exit(app.exec_())

