# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_stock\RefBooks\ActionType\ActionTypeListDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionTypeListDialog(object):
    def setupUi(self, ActionTypeListDialog):
        ActionTypeListDialog.setObjectName(_fromUtf8("ActionTypeListDialog"))
        ActionTypeListDialog.resize(702, 427)
        ActionTypeListDialog.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ActionTypeListDialog)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(ActionTypeListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pnlTree = QtGui.QWidget(self.splitter)
        self.pnlTree.setObjectName(_fromUtf8("pnlTree"))
        self.gridLayout = QtGui.QGridLayout(self.pnlTree)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblService = QtGui.QLabel(self.pnlTree)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout.addWidget(self.lblService, 1, 0, 1, 1)
        self.cmbService = CRBComboBox(self.pnlTree)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout.addWidget(self.cmbService, 1, 1, 1, 2)
        self.treeItems = CTreeView(self.pnlTree)
        self.treeItems.setObjectName(_fromUtf8("treeItems"))
        self.gridLayout.addWidget(self.treeItems, 0, 0, 1, 3)
        self.cmbServiceType = CActionServiceTypeComboBox(self.pnlTree)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridLayout.addWidget(self.cmbServiceType, 4, 1, 1, 2)
        self.lblIsPreferable = QtGui.QLabel(self.pnlTree)
        self.lblIsPreferable.setObjectName(_fromUtf8("lblIsPreferable"))
        self.gridLayout.addWidget(self.lblIsPreferable, 5, 0, 1, 1)
        self.lblQuotaType = QtGui.QLabel(self.pnlTree)
        self.lblQuotaType.setObjectName(_fromUtf8("lblQuotaType"))
        self.gridLayout.addWidget(self.lblQuotaType, 2, 0, 1, 1)
        self.cmbTissueType = CRBComboBox(self.pnlTree)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout.addWidget(self.cmbTissueType, 3, 1, 1, 2)
        self.lblServiceType = QtGui.QLabel(self.pnlTree)
        self.lblServiceType.setObjectName(_fromUtf8("lblServiceType"))
        self.gridLayout.addWidget(self.lblServiceType, 4, 0, 1, 1)
        self.cmbQuotaType = CRBComboBox(self.pnlTree)
        self.cmbQuotaType.setObjectName(_fromUtf8("cmbQuotaType"))
        self.gridLayout.addWidget(self.cmbQuotaType, 2, 1, 1, 2)
        self.cmbIsPreferable = QtGui.QComboBox(self.pnlTree)
        self.cmbIsPreferable.setObjectName(_fromUtf8("cmbIsPreferable"))
        self.cmbIsPreferable.addItem(_fromUtf8(""))
        self.cmbIsPreferable.setItemText(0, _fromUtf8(""))
        self.cmbIsPreferable.addItem(_fromUtf8(""))
        self.cmbIsPreferable.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsPreferable, 5, 1, 1, 2)
        self.lblTissueType = QtGui.QLabel(self.pnlTree)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueType.sizePolicy().hasHeightForWidth())
        self.lblTissueType.setSizePolicy(sizePolicy)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout.addWidget(self.lblTissueType, 3, 0, 1, 1)
        self.cmbShowInForm = QtGui.QComboBox(self.pnlTree)
        self.cmbShowInForm.setObjectName(_fromUtf8("cmbShowInForm"))
        self.cmbShowInForm.addItem(_fromUtf8(""))
        self.cmbShowInForm.setItemText(0, _fromUtf8(""))
        self.cmbShowInForm.addItem(_fromUtf8(""))
        self.cmbShowInForm.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbShowInForm, 6, 1, 1, 2)
        self.lblShowInForm = QtGui.QLabel(self.pnlTree)
        self.lblShowInForm.setObjectName(_fromUtf8("lblShowInForm"))
        self.gridLayout.addWidget(self.lblShowInForm, 6, 0, 1, 1)
        self.lblContract = QtGui.QLabel(self.pnlTree)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 7, 0, 1, 1)
        self.cmbContract = QtGui.QComboBox(self.pnlTree)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.cmbContract.setItemText(0, _fromUtf8(""))
        self.cmbContract.addItem(_fromUtf8(""))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbContract, 7, 1, 1, 2)
        self.pnlList = QtGui.QWidget(self.splitter)
        self.pnlList.setObjectName(_fromUtf8("pnlList"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pnlList)
        self.gridLayout_2.setContentsMargins(2, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCountRows = QtGui.QLabel(self.pnlList)
        self.lblCountRows.setText(_fromUtf8(""))
        self.lblCountRows.setObjectName(_fromUtf8("lblCountRows"))
        self.gridLayout_2.addWidget(self.lblCountRows, 1, 0, 1, 1)
        self.lblCountSelectedRows = QtGui.QLabel(self.pnlList)
        self.lblCountSelectedRows.setText(_fromUtf8(""))
        self.lblCountSelectedRows.setObjectName(_fromUtf8("lblCountSelectedRows"))
        self.gridLayout_2.addWidget(self.lblCountSelectedRows, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.tblItems = CTableView(self.pnlList)
        self.tblItems.setTabKeyNavigation(False)
        self.tblItems.setAlternatingRowColors(True)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout_2.addWidget(self.tblItems, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.splitter)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.btnFind = QtGui.QPushButton(ActionTypeListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFind.sizePolicy().hasHeightForWidth())
        self.btnFind.setSizePolicy(sizePolicy)
        self.btnFind.setObjectName(_fromUtf8("btnFind"))
        self.hboxlayout.addWidget(self.btnFind)
        self.btnSelect = QtGui.QPushButton(ActionTypeListDialog)
        self.btnSelect.setObjectName(_fromUtf8("btnSelect"))
        self.hboxlayout.addWidget(self.btnSelect)
        self.btnFilter = QtGui.QPushButton(ActionTypeListDialog)
        self.btnFilter.setObjectName(_fromUtf8("btnFilter"))
        self.hboxlayout.addWidget(self.btnFilter)
        self.btnEdit = QtGui.QPushButton(ActionTypeListDialog)
        self.btnEdit.setDefault(True)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.hboxlayout.addWidget(self.btnEdit)
        self.btnNew = QtGui.QPushButton(ActionTypeListDialog)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.hboxlayout.addWidget(self.btnNew)
        self.btnCancel = QtGui.QPushButton(ActionTypeListDialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.hboxlayout.addWidget(self.btnCancel)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.statusBar = QtGui.QStatusBar(ActionTypeListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_3.addWidget(self.statusBar)
        self.lblService.setBuddy(self.cmbService)
        self.lblQuotaType.setBuddy(self.cmbQuotaType)
        self.lblTissueType.setBuddy(self.cmbTissueType)

        self.retranslateUi(ActionTypeListDialog)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), ActionTypeListDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ActionTypeListDialog)
        ActionTypeListDialog.setTabOrder(self.treeItems, self.cmbService)
        ActionTypeListDialog.setTabOrder(self.cmbService, self.cmbQuotaType)
        ActionTypeListDialog.setTabOrder(self.cmbQuotaType, self.cmbTissueType)
        ActionTypeListDialog.setTabOrder(self.cmbTissueType, self.tblItems)
        ActionTypeListDialog.setTabOrder(self.tblItems, self.btnFind)
        ActionTypeListDialog.setTabOrder(self.btnFind, self.btnSelect)
        ActionTypeListDialog.setTabOrder(self.btnSelect, self.btnFilter)
        ActionTypeListDialog.setTabOrder(self.btnFilter, self.btnEdit)
        ActionTypeListDialog.setTabOrder(self.btnEdit, self.btnNew)
        ActionTypeListDialog.setTabOrder(self.btnNew, self.btnCancel)

    def retranslateUi(self, ActionTypeListDialog):
        ActionTypeListDialog.setWindowTitle(_translate("ActionTypeListDialog", "Dialog", None))
        self.lblService.setText(_translate("ActionTypeListDialog", "Профиль оплаты", None))
        self.lblIsPreferable.setText(_translate("ActionTypeListDialog", "Является предпочитаемым(-ой)", None))
        self.lblQuotaType.setText(_translate("ActionTypeListDialog", "Вид квоты", None))
        self.lblServiceType.setText(_translate("ActionTypeListDialog", "Вид услуги", None))
        self.cmbIsPreferable.setItemText(1, _translate("ActionTypeListDialog", "Да", None))
        self.cmbIsPreferable.setItemText(2, _translate("ActionTypeListDialog", "Нет", None))
        self.lblTissueType.setText(_translate("ActionTypeListDialog", "Тип биоматериала", None))
        self.cmbShowInForm.setItemText(1, _translate("ActionTypeListDialog", "Да", None))
        self.cmbShowInForm.setItemText(2, _translate("ActionTypeListDialog", "Нет", None))
        self.lblShowInForm.setText(_translate("ActionTypeListDialog", "Разрешается выбор в формах ввода событий", None))
        self.lblContract.setText(_translate("ActionTypeListDialog", "Договор", None))
        self.cmbContract.setItemText(1, _translate("ActionTypeListDialog", "Да", None))
        self.cmbContract.setItemText(2, _translate("ActionTypeListDialog", "Нет", None))
        self.tblItems.setWhatsThis(_translate("ActionTypeListDialog", "список записей", "ура!"))
        self.btnFind.setText(_translate("ActionTypeListDialog", "Поиск", None))
        self.btnSelect.setWhatsThis(_translate("ActionTypeListDialog", "выбрать текущую запись", None))
        self.btnSelect.setText(_translate("ActionTypeListDialog", "Выбор", None))
        self.btnFilter.setWhatsThis(_translate("ActionTypeListDialog", "изменить условие отбора записей для показа в списке", None))
        self.btnFilter.setText(_translate("ActionTypeListDialog", "Фильтр", None))
        self.btnEdit.setWhatsThis(_translate("ActionTypeListDialog", "изменить текущую запись", None))
        self.btnEdit.setText(_translate("ActionTypeListDialog", "Правка F4", None))
        self.btnEdit.setShortcut(_translate("ActionTypeListDialog", "F4", None))
        self.btnNew.setWhatsThis(_translate("ActionTypeListDialog", "добавить новую запись", None))
        self.btnNew.setText(_translate("ActionTypeListDialog", "Вставка F9", None))
        self.btnNew.setShortcut(_translate("ActionTypeListDialog", "F9", None))
        self.btnCancel.setWhatsThis(_translate("ActionTypeListDialog", "выйти из списка без выбора", None))
        self.btnCancel.setText(_translate("ActionTypeListDialog", "Закрыть", None))
        self.statusBar.setToolTip(_translate("ActionTypeListDialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("ActionTypeListDialog", "A status bar.", None))

from Events.ActionServiceType import CActionServiceTypeComboBox
from library.TableView import CTableView
from library.TreeView import CTreeView
from library.crbcombobox import CRBComboBox
