# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\RefBooks\RBJobPurposeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBJobPurposeEditorDialog(object):
    def setupUi(self, RBJobPurposeEditorDialog):
        RBJobPurposeEditorDialog.setObjectName(_fromUtf8("RBJobPurposeEditorDialog"))
        RBJobPurposeEditorDialog.resize(539, 272)
        RBJobPurposeEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_4 = QtGui.QGridLayout(RBJobPurposeEditorDialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblCode = QtGui.QLabel(RBJobPurposeEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_4.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(RBJobPurposeEditorDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_4.addWidget(self.edtName, 1, 1, 2, 1)
        self.buttonBox = QtGui.QDialogButtonBox(RBJobPurposeEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.edtCode = QtGui.QLineEdit(RBJobPurposeEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_4.addWidget(self.edtCode, 0, 1, 1, 1)
        self.lblName = QtGui.QLabel(RBJobPurposeEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_4.addWidget(self.lblName, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(RBJobPurposeEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPatient = QtGui.QWidget()
        self.tabPatient.setObjectName(_fromUtf8("tabPatient"))
        self.gridLayout = QtGui.QGridLayout(self.tabPatient)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBegAgeUnit, 1, 1, 1, 1)
        self.lblAge = QtGui.QLabel(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 1, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 0, 1, 1, 1)
        self.edtBegAgeCount = QtGui.QLineEdit(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout.addWidget(self.edtBegAgeCount, 1, 2, 1, 1)
        self.lblAgeSep = QtGui.QLabel(self.tabPatient)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout.addWidget(self.lblAgeSep, 1, 3, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEndAgeUnit, 1, 4, 1, 1)
        self.lblSex = QtGui.QLabel(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(412, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 5)
        self.edtEndAgeCount = QtGui.QLineEdit(self.tabPatient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout.addWidget(self.edtEndAgeCount, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 6, 1, 1)
        self.lblPrematurelyClosingThreshold = QtGui.QLabel(self.tabPatient)
        self.lblPrematurelyClosingThreshold.setObjectName(_fromUtf8("lblPrematurelyClosingThreshold"))
        self.gridLayout.addWidget(self.lblPrematurelyClosingThreshold, 2, 0, 1, 1)
        self.edtPrematurelyClosingThreshold = QtGui.QSpinBox(self.tabPatient)
        self.edtPrematurelyClosingThreshold.setMaximum(255)
        self.edtPrematurelyClosingThreshold.setObjectName(_fromUtf8("edtPrematurelyClosingThreshold"))
        self.gridLayout.addWidget(self.edtPrematurelyClosingThreshold, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tabPatient, _fromUtf8(""))
        self.tabPractices = QtGui.QWidget()
        self.tabPractices.setObjectName(_fromUtf8("tabPractices"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabPractices)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblPractices = CInDocTableView(self.tabPractices)
        self.tblPractices.setObjectName(_fromUtf8("tblPractices"))
        self.gridLayout_2.addWidget(self.tblPractices, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPractices, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 3, 0, 1, 2)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblSex.setBuddy(self.cmbSex)

        self.retranslateUi(RBJobPurposeEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBJobPurposeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBJobPurposeEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RBJobPurposeEditorDialog)
        RBJobPurposeEditorDialog.setTabOrder(self.edtCode, self.edtName)
        RBJobPurposeEditorDialog.setTabOrder(self.edtName, self.tabWidget)
        RBJobPurposeEditorDialog.setTabOrder(self.tabWidget, self.cmbSex)
        RBJobPurposeEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        RBJobPurposeEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        RBJobPurposeEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        RBJobPurposeEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        RBJobPurposeEditorDialog.setTabOrder(self.edtEndAgeCount, self.edtPrematurelyClosingThreshold)
        RBJobPurposeEditorDialog.setTabOrder(self.edtPrematurelyClosingThreshold, self.tblPractices)
        RBJobPurposeEditorDialog.setTabOrder(self.tblPractices, self.buttonBox)

    def retranslateUi(self, RBJobPurposeEditorDialog):
        RBJobPurposeEditorDialog.setWindowTitle(_translate("RBJobPurposeEditorDialog", "ChangeMe!", None))
        self.lblCode.setText(_translate("RBJobPurposeEditorDialog", "&Код", None))
        self.lblName.setText(_translate("RBJobPurposeEditorDialog", "На&именование", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("RBJobPurposeEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("RBJobPurposeEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("RBJobPurposeEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("RBJobPurposeEditorDialog", "Г", None))
        self.lblAge.setText(_translate("RBJobPurposeEditorDialog", "&Возраст", None))
        self.cmbSex.setItemText(1, _translate("RBJobPurposeEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("RBJobPurposeEditorDialog", "Ж", None))
        self.edtBegAgeCount.setInputMask(_translate("RBJobPurposeEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("RBJobPurposeEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("RBJobPurposeEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("RBJobPurposeEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("RBJobPurposeEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("RBJobPurposeEditorDialog", "Г", None))
        self.lblSex.setText(_translate("RBJobPurposeEditorDialog", "&Пол", None))
        self.edtEndAgeCount.setInputMask(_translate("RBJobPurposeEditorDialog", "000; ", None))
        self.lblPrematurelyClosingThreshold.setToolTip(_translate("RBJobPurposeEditorDialog", "Освобождать номерок пациента, если он пришел раньше указанного времени (в часах)", None))
        self.lblPrematurelyClosingThreshold.setText(_translate("RBJobPurposeEditorDialog", "Перенос номерка", None))
        self.edtPrematurelyClosingThreshold.setToolTip(_translate("RBJobPurposeEditorDialog", "Освобождать номерок пациента, если он пришел раньше указанного времени (в часах)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPatient), _translate("RBJobPurposeEditorDialog", "Пациент", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPractices), _translate("RBJobPurposeEditorDialog", "Применение", None))

from library.InDocTable import CInDocTableView
