# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\TissueJournal\LaboratoryCalculator\CalculatorWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalculatorWidget(object):
    def setupUi(self, CalculatorWidget):
        CalculatorWidget.setObjectName(_fromUtf8("CalculatorWidget"))
        CalculatorWidget.resize(532, 315)
        self.gridLayout_2 = QtGui.QGridLayout(CalculatorWidget)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtGG = QtGui.QDoubleSpinBox(CalculatorWidget)
        self.edtGG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtGG.setMaximum(9999.99)
        self.edtGG.setObjectName(_fromUtf8("edtGG"))
        self.gridLayout_2.addWidget(self.edtGG, 5, 2, 1, 1)
        self.lblCI = QtGui.QLabel(CalculatorWidget)
        self.lblCI.setEnabled(True)
        self.lblCI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCI.setObjectName(_fromUtf8("lblCI"))
        self.gridLayout_2.addWidget(self.lblCI, 7, 1, 1, 1)
        self.lblEE = QtGui.QLabel(CalculatorWidget)
        self.lblEE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEE.setObjectName(_fromUtf8("lblEE"))
        self.gridLayout_2.addWidget(self.lblEE, 6, 1, 1, 1)
        self.edtCI = QtGui.QDoubleSpinBox(CalculatorWidget)
        self.edtCI.setEnabled(False)
        self.edtCI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtCI.setMinimum(0.0)
        self.edtCI.setMaximum(10.0)
        self.edtCI.setSingleStep(0.1)
        self.edtCI.setProperty("value", 0.0)
        self.edtCI.setObjectName(_fromUtf8("edtCI"))
        self.gridLayout_2.addWidget(self.edtCI, 7, 2, 1, 1)
        self.edtEE = QtGui.QDoubleSpinBox(CalculatorWidget)
        self.edtEE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtEE.setMaximum(9999.99)
        self.edtEE.setObjectName(_fromUtf8("edtEE"))
        self.gridLayout_2.addWidget(self.edtEE, 6, 2, 1, 1)
        self.lblMaxGroupValue = QtGui.QLabel(CalculatorWidget)
        self.lblMaxGroupValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMaxGroupValue.setObjectName(_fromUtf8("lblMaxGroupValue"))
        self.gridLayout_2.addWidget(self.lblMaxGroupValue, 1, 1, 1, 1)
        self.tableView = CLaboratoryCalculatorTableView(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 9, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 1, 1, 1)
        self.edtMaxGroupValue = CMaxGroupValueSpinBox(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMaxGroupValue.sizePolicy().hasHeightForWidth())
        self.edtMaxGroupValue.setSizePolicy(sizePolicy)
        self.edtMaxGroupValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtMaxGroupValue.setMaximum(9999999)
        self.edtMaxGroupValue.setProperty("value", 100)
        self.edtMaxGroupValue.setObjectName(_fromUtf8("edtMaxGroupValue"))
        self.gridLayout_2.addWidget(self.edtMaxGroupValue, 1, 2, 1, 1)
        self.pnlButtons = QtGui.QWidget(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlButtons.sizePolicy().hasHeightForWidth())
        self.pnlButtons.setSizePolicy(sizePolicy)
        self.pnlButtons.setObjectName(_fromUtf8("pnlButtons"))
        self.gridLayout = QtGui.QGridLayout(self.pnlButtons)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnPlus = CControlButton(self.pnlButtons)
        self.btnPlus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlus.sizePolicy().hasHeightForWidth())
        self.btnPlus.setSizePolicy(sizePolicy)
        self.btnPlus.setObjectName(_fromUtf8("btnPlus"))
        self.gridLayout.addWidget(self.btnPlus, 1, 3, 2, 1)
        self.btnSix = CControlButton(self.pnlButtons)
        self.btnSix.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSix.sizePolicy().hasHeightForWidth())
        self.btnSix.setSizePolicy(sizePolicy)
        self.btnSix.setObjectName(_fromUtf8("btnSix"))
        self.gridLayout.addWidget(self.btnSix, 2, 2, 1, 1)
        self.btnEight = CControlButton(self.pnlButtons)
        self.btnEight.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEight.sizePolicy().hasHeightForWidth())
        self.btnEight.setSizePolicy(sizePolicy)
        self.btnEight.setObjectName(_fromUtf8("btnEight"))
        self.gridLayout.addWidget(self.btnEight, 1, 1, 1, 1)
        self.btnSeven = CControlButton(self.pnlButtons)
        self.btnSeven.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSeven.sizePolicy().hasHeightForWidth())
        self.btnSeven.setSizePolicy(sizePolicy)
        self.btnSeven.setObjectName(_fromUtf8("btnSeven"))
        self.gridLayout.addWidget(self.btnSeven, 1, 0, 1, 1)
        self.btnThree = CControlButton(self.pnlButtons)
        self.btnThree.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThree.sizePolicy().hasHeightForWidth())
        self.btnThree.setSizePolicy(sizePolicy)
        self.btnThree.setObjectName(_fromUtf8("btnThree"))
        self.gridLayout.addWidget(self.btnThree, 3, 2, 1, 1)
        self.btnTwo = CControlButton(self.pnlButtons)
        self.btnTwo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTwo.sizePolicy().hasHeightForWidth())
        self.btnTwo.setSizePolicy(sizePolicy)
        self.btnTwo.setObjectName(_fromUtf8("btnTwo"))
        self.gridLayout.addWidget(self.btnTwo, 3, 1, 1, 1)
        self.btnNine = CControlButton(self.pnlButtons)
        self.btnNine.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNine.sizePolicy().hasHeightForWidth())
        self.btnNine.setSizePolicy(sizePolicy)
        self.btnNine.setObjectName(_fromUtf8("btnNine"))
        self.gridLayout.addWidget(self.btnNine, 1, 2, 1, 1)
        self.btnFour = CControlButton(self.pnlButtons)
        self.btnFour.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFour.sizePolicy().hasHeightForWidth())
        self.btnFour.setSizePolicy(sizePolicy)
        self.btnFour.setObjectName(_fromUtf8("btnFour"))
        self.gridLayout.addWidget(self.btnFour, 2, 0, 1, 1)
        self.btnOne = CControlButton(self.pnlButtons)
        self.btnOne.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOne.sizePolicy().hasHeightForWidth())
        self.btnOne.setSizePolicy(sizePolicy)
        self.btnOne.setObjectName(_fromUtf8("btnOne"))
        self.gridLayout.addWidget(self.btnOne, 3, 0, 1, 1)
        self.btnFive = CControlButton(self.pnlButtons)
        self.btnFive.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFive.sizePolicy().hasHeightForWidth())
        self.btnFive.setSizePolicy(sizePolicy)
        self.btnFive.setObjectName(_fromUtf8("btnFive"))
        self.gridLayout.addWidget(self.btnFive, 2, 1, 1, 1)
        self.btnZero = CControlButton(self.pnlButtons)
        self.btnZero.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZero.sizePolicy().hasHeightForWidth())
        self.btnZero.setSizePolicy(sizePolicy)
        self.btnZero.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnZero.setAutoRaise(False)
        self.btnZero.setArrowType(QtCore.Qt.NoArrow)
        self.btnZero.setObjectName(_fromUtf8("btnZero"))
        self.gridLayout.addWidget(self.btnZero, 4, 0, 1, 2)
        self.btnReset = QtGui.QToolButton(self.pnlButtons)
        self.btnReset.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset.sizePolicy().hasHeightForWidth())
        self.btnReset.setSizePolicy(sizePolicy)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.gridLayout.addWidget(self.btnReset, 4, 2, 1, 1)
        self.btnDiv = CControlButton(self.pnlButtons)
        self.btnDiv.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDiv.sizePolicy().hasHeightForWidth())
        self.btnDiv.setSizePolicy(sizePolicy)
        self.btnDiv.setObjectName(_fromUtf8("btnDiv"))
        self.gridLayout.addWidget(self.btnDiv, 0, 1, 1, 1)
        self.btnMultiply = CControlButton(self.pnlButtons)
        self.btnMultiply.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMultiply.sizePolicy().hasHeightForWidth())
        self.btnMultiply.setSizePolicy(sizePolicy)
        self.btnMultiply.setObjectName(_fromUtf8("btnMultiply"))
        self.gridLayout.addWidget(self.btnMultiply, 0, 2, 1, 1)
        self.btnMinus = CControlButton(self.pnlButtons)
        self.btnMinus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMinus.sizePolicy().hasHeightForWidth())
        self.btnMinus.setSizePolicy(sizePolicy)
        self.btnMinus.setObjectName(_fromUtf8("btnMinus"))
        self.gridLayout.addWidget(self.btnMinus, 0, 3, 1, 1)
        self.btnEnter = QtGui.QToolButton(self.pnlButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnter.sizePolicy().hasHeightForWidth())
        self.btnEnter.setSizePolicy(sizePolicy)
        self.btnEnter.setObjectName(_fromUtf8("btnEnter"))
        self.gridLayout.addWidget(self.btnEnter, 3, 3, 2, 1)
        self.btnCancel = QtGui.QToolButton(self.pnlButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout.addWidget(self.btnCancel, 6, 0, 1, 4)
        self.btnResetAdditional = QtGui.QToolButton(self.pnlButtons)
        self.btnResetAdditional.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetAdditional.sizePolicy().hasHeightForWidth())
        self.btnResetAdditional.setSizePolicy(sizePolicy)
        self.btnResetAdditional.setObjectName(_fromUtf8("btnResetAdditional"))
        self.gridLayout.addWidget(self.btnResetAdditional, 7, 0, 1, 4)
        self.gridLayout_2.addWidget(self.pnlButtons, 0, 1, 1, 2)
        self.lblRounding = QtGui.QLabel(CalculatorWidget)
        self.lblRounding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRounding.setObjectName(_fromUtf8("lblRounding"))
        self.gridLayout_2.addWidget(self.lblRounding, 2, 1, 1, 1)
        self.edtRounding = QtGui.QSpinBox(CalculatorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRounding.sizePolicy().hasHeightForWidth())
        self.edtRounding.setSizePolicy(sizePolicy)
        self.edtRounding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtRounding.setMaximum(9)
        self.edtRounding.setObjectName(_fromUtf8("edtRounding"))
        self.gridLayout_2.addWidget(self.edtRounding, 2, 2, 1, 1)
        self.lblLeukocytes = QtGui.QLabel(CalculatorWidget)
        self.lblLeukocytes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLeukocytes.setObjectName(_fromUtf8("lblLeukocytes"))
        self.gridLayout_2.addWidget(self.lblLeukocytes, 3, 1, 1, 1)
        self.edtLeukocytes = QtGui.QDoubleSpinBox(CalculatorWidget)
        self.edtLeukocytes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtLeukocytes.setMaximum(9999.99)
        self.edtLeukocytes.setSingleStep(1.0)
        self.edtLeukocytes.setObjectName(_fromUtf8("edtLeukocytes"))
        self.gridLayout_2.addWidget(self.edtLeukocytes, 3, 2, 1, 1)
        self.lblGG = QtGui.QLabel(CalculatorWidget)
        self.lblGG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGG.setObjectName(_fromUtf8("lblGG"))
        self.gridLayout_2.addWidget(self.lblGG, 5, 1, 1, 1)
        self.line = QtGui.QFrame(CalculatorWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 4, 1, 1, 2)
        self.lblMaxGroupValue.setBuddy(self.edtMaxGroupValue)
        self.lblRounding.setBuddy(self.edtRounding)
        self.lblLeukocytes.setBuddy(self.edtLeukocytes)

        self.retranslateUi(CalculatorWidget)
        QtCore.QMetaObject.connectSlotsByName(CalculatorWidget)
        CalculatorWidget.setTabOrder(self.tableView, self.btnDiv)
        CalculatorWidget.setTabOrder(self.btnDiv, self.btnMultiply)
        CalculatorWidget.setTabOrder(self.btnMultiply, self.btnMinus)
        CalculatorWidget.setTabOrder(self.btnMinus, self.btnSeven)
        CalculatorWidget.setTabOrder(self.btnSeven, self.btnEight)
        CalculatorWidget.setTabOrder(self.btnEight, self.btnNine)
        CalculatorWidget.setTabOrder(self.btnNine, self.btnPlus)
        CalculatorWidget.setTabOrder(self.btnPlus, self.btnFour)
        CalculatorWidget.setTabOrder(self.btnFour, self.btnFive)
        CalculatorWidget.setTabOrder(self.btnFive, self.btnSix)
        CalculatorWidget.setTabOrder(self.btnSix, self.btnOne)
        CalculatorWidget.setTabOrder(self.btnOne, self.btnTwo)
        CalculatorWidget.setTabOrder(self.btnTwo, self.btnThree)
        CalculatorWidget.setTabOrder(self.btnThree, self.btnEnter)
        CalculatorWidget.setTabOrder(self.btnEnter, self.btnZero)
        CalculatorWidget.setTabOrder(self.btnZero, self.btnReset)
        CalculatorWidget.setTabOrder(self.btnReset, self.btnCancel)
        CalculatorWidget.setTabOrder(self.btnCancel, self.edtMaxGroupValue)

    def retranslateUi(self, CalculatorWidget):
        CalculatorWidget.setWindowTitle(_translate("CalculatorWidget", "Form", None))
        self.lblCI.setText(_translate("CalculatorWidget", "Цветовой показатель", None))
        self.lblEE.setText(_translate("CalculatorWidget", "Эритроциты", None))
        self.lblMaxGroupValue.setText(_translate("CalculatorWidget", "Групповой предел: ", None))
        self.btnPlus.setText(_translate("CalculatorWidget", "+", None))
        self.btnPlus.setShortcut(_translate("CalculatorWidget", "+", None))
        self.btnSix.setText(_translate("CalculatorWidget", "6", None))
        self.btnSix.setShortcut(_translate("CalculatorWidget", "6", None))
        self.btnEight.setText(_translate("CalculatorWidget", "8", None))
        self.btnEight.setShortcut(_translate("CalculatorWidget", "8", None))
        self.btnSeven.setText(_translate("CalculatorWidget", "7", None))
        self.btnSeven.setShortcut(_translate("CalculatorWidget", "7", None))
        self.btnThree.setText(_translate("CalculatorWidget", "3", None))
        self.btnThree.setShortcut(_translate("CalculatorWidget", "3", None))
        self.btnTwo.setText(_translate("CalculatorWidget", "2", None))
        self.btnTwo.setShortcut(_translate("CalculatorWidget", "2", None))
        self.btnNine.setText(_translate("CalculatorWidget", "9", None))
        self.btnNine.setShortcut(_translate("CalculatorWidget", "9", None))
        self.btnFour.setText(_translate("CalculatorWidget", "4", None))
        self.btnFour.setShortcut(_translate("CalculatorWidget", "4", None))
        self.btnOne.setText(_translate("CalculatorWidget", "1", None))
        self.btnOne.setShortcut(_translate("CalculatorWidget", "1", None))
        self.btnFive.setText(_translate("CalculatorWidget", "5", None))
        self.btnFive.setShortcut(_translate("CalculatorWidget", "5", None))
        self.btnZero.setText(_translate("CalculatorWidget", "0", None))
        self.btnZero.setShortcut(_translate("CalculatorWidget", "0", None))
        self.btnReset.setText(_translate("CalculatorWidget", ".", None))
        self.btnReset.setShortcut(_translate("CalculatorWidget", ".", None))
        self.btnDiv.setText(_translate("CalculatorWidget", "/", None))
        self.btnDiv.setShortcut(_translate("CalculatorWidget", "/", None))
        self.btnMultiply.setText(_translate("CalculatorWidget", "*", None))
        self.btnMultiply.setShortcut(_translate("CalculatorWidget", "*", None))
        self.btnMinus.setText(_translate("CalculatorWidget", "-", None))
        self.btnMinus.setShortcut(_translate("CalculatorWidget", "-", None))
        self.btnEnter.setText(_translate("CalculatorWidget", "E", None))
        self.btnEnter.setShortcut(_translate("CalculatorWidget", "Enter", None))
        self.btnCancel.setText(_translate("CalculatorWidget", "Отменить", None))
        self.btnCancel.setShortcut(_translate("CalculatorWidget", "Backspace", None))
        self.btnResetAdditional.setText(_translate("CalculatorWidget", "Отменить назначения", None))
        self.lblRounding.setText(_translate("CalculatorWidget", "Округление:", None))
        self.lblLeukocytes.setText(_translate("CalculatorWidget", "Лейкоциты", None))
        self.lblGG.setText(_translate("CalculatorWidget", "Гемоглобин", None))

from TissueJournal.LaboratoryCalculator.LaboratoryCalculatorTable import CLaboratoryCalculatorTableView
from TissueJournal.LaboratoryCalculator.Utils import CControlButton, CMaxGroupValueSpinBox
