# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\SurgeryJournal\SurgeryJournalDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SurgeryJournalDialog(object):
    def setupUi(self, SurgeryJournalDialog):
        SurgeryJournalDialog.setObjectName(_fromUtf8("SurgeryJournalDialog"))
        SurgeryJournalDialog.setWindowModality(QtCore.Qt.WindowModal)
        SurgeryJournalDialog.resize(761, 622)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SurgeryJournalDialog.sizePolicy().hasHeightForWidth())
        SurgeryJournalDialog.setSizePolicy(sizePolicy)
        SurgeryJournalDialog.setMinimumSize(QtCore.QSize(761, 622))
        SurgeryJournalDialog.setModal(True)
        self.gridLayout_4 = QtGui.QGridLayout(SurgeryJournalDialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabSurgeryJournal = QtGui.QTabWidget(SurgeryJournalDialog)
        self.tabSurgeryJournal.setObjectName(_fromUtf8("tabSurgeryJournal"))
        self.tabJournal = QtGui.QWidget()
        self.tabJournal.setObjectName(_fromUtf8("tabJournal"))
        self.gridLayout = QtGui.QGridLayout(self.tabJournal)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblPeriodJournal = QtGui.QLabel(self.tabJournal)
        self.lblPeriodJournal.setObjectName(_fromUtf8("lblPeriodJournal"))
        self.gridLayout.addWidget(self.lblPeriodJournal, 0, 0, 1, 1)
        self.edtEndDateJournal = CDateEdit(self.tabJournal)
        self.edtEndDateJournal.setCalendarPopup(True)
        self.edtEndDateJournal.setObjectName(_fromUtf8("edtEndDateJournal"))
        self.gridLayout.addWidget(self.edtEndDateJournal, 0, 2, 1, 1)
        self.tblJournal = CTableView(self.tabJournal)
        self.tblJournal.setObjectName(_fromUtf8("tblJournal"))
        self.gridLayout.addWidget(self.tblJournal, 5, 0, 1, 12)
        self.edtBegDateJournal = CDateEdit(self.tabJournal)
        self.edtBegDateJournal.setCalendarPopup(True)
        self.edtBegDateJournal.setObjectName(_fromUtf8("edtBegDateJournal"))
        self.gridLayout.addWidget(self.edtBegDateJournal, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 11, 1, 1)
        self.cmbActionStatusJournal = CActionStatusComboBox(self.tabJournal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionStatusJournal.sizePolicy().hasHeightForWidth())
        self.cmbActionStatusJournal.setSizePolicy(sizePolicy)
        self.cmbActionStatusJournal.setObjectName(_fromUtf8("cmbActionStatusJournal"))
        self.gridLayout.addWidget(self.cmbActionStatusJournal, 0, 10, 1, 1)
        self.cmbPersonJournal = CPersonComboBoxEx(self.tabJournal)
        self.cmbPersonJournal.setObjectName(_fromUtf8("cmbPersonJournal"))
        self.cmbPersonJournal.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPersonJournal, 2, 1, 1, 2)
        self.lblPersonJournal = QtGui.QLabel(self.tabJournal)
        self.lblPersonJournal.setObjectName(_fromUtf8("lblPersonJournal"))
        self.gridLayout.addWidget(self.lblPersonJournal, 2, 0, 1, 1)
        self.lblMKBJournal = QtGui.QLabel(self.tabJournal)
        self.lblMKBJournal.setObjectName(_fromUtf8("lblMKBJournal"))
        self.gridLayout.addWidget(self.lblMKBJournal, 0, 3, 1, 1)
        self.lblOrgStructureJournal = QtGui.QLabel(self.tabJournal)
        self.lblOrgStructureJournal.setObjectName(_fromUtf8("lblOrgStructureJournal"))
        self.gridLayout.addWidget(self.lblOrgStructureJournal, 2, 3, 1, 1)
        self.cmbMKBFilterJournal = QtGui.QComboBox(self.tabJournal)
        self.cmbMKBFilterJournal.setObjectName(_fromUtf8("cmbMKBFilterJournal"))
        self.cmbMKBFilterJournal.addItem(_fromUtf8(""))
        self.cmbMKBFilterJournal.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMKBFilterJournal, 0, 4, 1, 1)
        self.edtMKBToJournal = CICDCodeEdit(self.tabJournal)
        self.edtMKBToJournal.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBToJournal.sizePolicy().hasHeightForWidth())
        self.edtMKBToJournal.setSizePolicy(sizePolicy)
        self.edtMKBToJournal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBToJournal.setMaxLength(6)
        self.edtMKBToJournal.setObjectName(_fromUtf8("edtMKBToJournal"))
        self.gridLayout.addWidget(self.edtMKBToJournal, 0, 6, 1, 1)
        self.edtMKBFromJournal = CICDCodeEdit(self.tabJournal)
        self.edtMKBFromJournal.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFromJournal.sizePolicy().hasHeightForWidth())
        self.edtMKBFromJournal.setSizePolicy(sizePolicy)
        self.edtMKBFromJournal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFromJournal.setMaxLength(6)
        self.edtMKBFromJournal.setObjectName(_fromUtf8("edtMKBFromJournal"))
        self.gridLayout.addWidget(self.edtMKBFromJournal, 0, 5, 1, 1)
        self.lblActionStatusJournal = QtGui.QLabel(self.tabJournal)
        self.lblActionStatusJournal.setObjectName(_fromUtf8("lblActionStatusJournal"))
        self.gridLayout.addWidget(self.lblActionStatusJournal, 0, 7, 1, 3)
        self.cmbActionTypeJournal = CActionTypeComboBoxEx(self.tabJournal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionTypeJournal.sizePolicy().hasHeightForWidth())
        self.cmbActionTypeJournal.setSizePolicy(sizePolicy)
        self.cmbActionTypeJournal.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbActionTypeJournal.setObjectName(_fromUtf8("cmbActionTypeJournal"))
        self.gridLayout.addWidget(self.cmbActionTypeJournal, 2, 8, 1, 4)
        self.lblActionTypeJournal = QtGui.QLabel(self.tabJournal)
        self.lblActionTypeJournal.setObjectName(_fromUtf8("lblActionTypeJournal"))
        self.gridLayout.addWidget(self.lblActionTypeJournal, 2, 7, 1, 1)
        self.cmbOrgStructureJournal = COrgStructureComboBox(self.tabJournal)
        self.cmbOrgStructureJournal.setObjectName(_fromUtf8("cmbOrgStructureJournal"))
        self.gridLayout.addWidget(self.cmbOrgStructureJournal, 2, 4, 1, 3)
        self.tabSurgeryJournal.addTab(self.tabJournal, _fromUtf8(""))
        self.tabCanceled = QtGui.QWidget()
        self.tabCanceled.setObjectName(_fromUtf8("tabCanceled"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabCanceled)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblPeriodCanceled = QtGui.QLabel(self.tabCanceled)
        self.lblPeriodCanceled.setObjectName(_fromUtf8("lblPeriodCanceled"))
        self.gridLayout_2.addWidget(self.lblPeriodCanceled, 0, 0, 1, 1)
        self.edtBegDateCanceled = CDateEdit(self.tabCanceled)
        self.edtBegDateCanceled.setCalendarPopup(True)
        self.edtBegDateCanceled.setObjectName(_fromUtf8("edtBegDateCanceled"))
        self.gridLayout_2.addWidget(self.edtBegDateCanceled, 0, 1, 1, 1)
        self.cmbMKBFilterCanceled = QtGui.QComboBox(self.tabCanceled)
        self.cmbMKBFilterCanceled.setObjectName(_fromUtf8("cmbMKBFilterCanceled"))
        self.cmbMKBFilterCanceled.addItem(_fromUtf8(""))
        self.cmbMKBFilterCanceled.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbMKBFilterCanceled, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 10, 1, 1)
        self.edtEndDateCanceled = CDateEdit(self.tabCanceled)
        self.edtEndDateCanceled.setCalendarPopup(True)
        self.edtEndDateCanceled.setObjectName(_fromUtf8("edtEndDateCanceled"))
        self.gridLayout_2.addWidget(self.edtEndDateCanceled, 0, 2, 1, 1)
        self.lblMKBCanceled = QtGui.QLabel(self.tabCanceled)
        self.lblMKBCanceled.setObjectName(_fromUtf8("lblMKBCanceled"))
        self.gridLayout_2.addWidget(self.lblMKBCanceled, 0, 3, 1, 1)
        self.chkActionStatusCanceled = QtGui.QCheckBox(self.tabCanceled)
        self.chkActionStatusCanceled.setChecked(True)
        self.chkActionStatusCanceled.setObjectName(_fromUtf8("chkActionStatusCanceled"))
        self.gridLayout_2.addWidget(self.chkActionStatusCanceled, 0, 8, 1, 1)
        self.chkActionStatusRefused = QtGui.QCheckBox(self.tabCanceled)
        self.chkActionStatusRefused.setChecked(True)
        self.chkActionStatusRefused.setObjectName(_fromUtf8("chkActionStatusRefused"))
        self.gridLayout_2.addWidget(self.chkActionStatusRefused, 0, 9, 1, 1)
        self.edtMKBToCanceled = CICDCodeEdit(self.tabCanceled)
        self.edtMKBToCanceled.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBToCanceled.sizePolicy().hasHeightForWidth())
        self.edtMKBToCanceled.setSizePolicy(sizePolicy)
        self.edtMKBToCanceled.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBToCanceled.setMaxLength(6)
        self.edtMKBToCanceled.setObjectName(_fromUtf8("edtMKBToCanceled"))
        self.gridLayout_2.addWidget(self.edtMKBToCanceled, 0, 7, 1, 1)
        self.edtMKBFromCanceled = CICDCodeEdit(self.tabCanceled)
        self.edtMKBFromCanceled.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFromCanceled.sizePolicy().hasHeightForWidth())
        self.edtMKBFromCanceled.setSizePolicy(sizePolicy)
        self.edtMKBFromCanceled.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFromCanceled.setMaxLength(6)
        self.edtMKBFromCanceled.setObjectName(_fromUtf8("edtMKBFromCanceled"))
        self.gridLayout_2.addWidget(self.edtMKBFromCanceled, 0, 6, 1, 1)
        self.lblPersonCanceled = QtGui.QLabel(self.tabCanceled)
        self.lblPersonCanceled.setObjectName(_fromUtf8("lblPersonCanceled"))
        self.gridLayout_2.addWidget(self.lblPersonCanceled, 1, 0, 1, 1)
        self.tblCanceled = CTableView(self.tabCanceled)
        self.tblCanceled.setObjectName(_fromUtf8("tblCanceled"))
        self.gridLayout_2.addWidget(self.tblCanceled, 2, 0, 1, 11)
        self.cmbPersonCanceled = CPersonComboBoxEx(self.tabCanceled)
        self.cmbPersonCanceled.setObjectName(_fromUtf8("cmbPersonCanceled"))
        self.cmbPersonCanceled.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPersonCanceled, 1, 1, 1, 2)
        self.cmbActionTypeCanceled = CActionTypeComboBoxEx(self.tabCanceled)
        self.cmbActionTypeCanceled.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbActionTypeCanceled.setObjectName(_fromUtf8("cmbActionTypeCanceled"))
        self.gridLayout_2.addWidget(self.cmbActionTypeCanceled, 1, 8, 1, 3)
        self.lblActionTypeCanceled = QtGui.QLabel(self.tabCanceled)
        self.lblActionTypeCanceled.setObjectName(_fromUtf8("lblActionTypeCanceled"))
        self.gridLayout_2.addWidget(self.lblActionTypeCanceled, 1, 7, 1, 1)
        self.cmbOrgStructureCanceled = COrgStructureComboBox(self.tabCanceled)
        self.cmbOrgStructureCanceled.setObjectName(_fromUtf8("cmbOrgStructureCanceled"))
        self.gridLayout_2.addWidget(self.cmbOrgStructureCanceled, 1, 5, 1, 2)
        self.lblOrgStructureCanceled = QtGui.QLabel(self.tabCanceled)
        self.lblOrgStructureCanceled.setObjectName(_fromUtf8("lblOrgStructureCanceled"))
        self.gridLayout_2.addWidget(self.lblOrgStructureCanceled, 1, 3, 1, 2)
        self.tabSurgeryJournal.addTab(self.tabCanceled, _fromUtf8(""))
        self.tabPlan = QtGui.QWidget()
        self.tabPlan.setObjectName(_fromUtf8("tabPlan"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabPlan)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblPeriodPlan = QtGui.QLabel(self.tabPlan)
        self.lblPeriodPlan.setObjectName(_fromUtf8("lblPeriodPlan"))
        self.gridLayout_3.addWidget(self.lblPeriodPlan, 0, 0, 1, 1)
        self.edtBegDatePlan = CDateEdit(self.tabPlan)
        self.edtBegDatePlan.setCalendarPopup(True)
        self.edtBegDatePlan.setObjectName(_fromUtf8("edtBegDatePlan"))
        self.gridLayout_3.addWidget(self.edtBegDatePlan, 0, 1, 1, 1)
        self.edtEndDatePlan = CDateEdit(self.tabPlan)
        self.edtEndDatePlan.setCalendarPopup(True)
        self.edtEndDatePlan.setObjectName(_fromUtf8("edtEndDatePlan"))
        self.gridLayout_3.addWidget(self.edtEndDatePlan, 0, 2, 1, 1)
        self.lblActionStatusPlan = QtGui.QLabel(self.tabPlan)
        self.lblActionStatusPlan.setObjectName(_fromUtf8("lblActionStatusPlan"))
        self.gridLayout_3.addWidget(self.lblActionStatusPlan, 0, 3, 1, 1)
        self.cmbActionStatusPlan = CActionStatusComboBox(self.tabPlan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionStatusPlan.sizePolicy().hasHeightForWidth())
        self.cmbActionStatusPlan.setSizePolicy(sizePolicy)
        self.cmbActionStatusPlan.setObjectName(_fromUtf8("cmbActionStatusPlan"))
        self.gridLayout_3.addWidget(self.cmbActionStatusPlan, 0, 4, 1, 1)
        self.tblPlan = CTableView(self.tabPlan)
        self.tblPlan.setObjectName(_fromUtf8("tblPlan"))
        self.gridLayout_3.addWidget(self.tblPlan, 1, 0, 1, 6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.tabSurgeryJournal.addTab(self.tabPlan, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabSurgeryJournal, 0, 0, 1, 2)
        self.lblCountRecordList = QtGui.QLabel(SurgeryJournalDialog)
        self.lblCountRecordList.setObjectName(_fromUtf8("lblCountRecordList"))
        self.gridLayout_4.addWidget(self.lblCountRecordList, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(SurgeryJournalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.lblPersonJournal.setBuddy(self.cmbPersonJournal)
        self.lblMKBJournal.setBuddy(self.cmbMKBFilterJournal)
        self.lblActionTypeJournal.setBuddy(self.cmbActionTypeJournal)
        self.lblMKBCanceled.setBuddy(self.cmbMKBFilterJournal)
        self.lblPersonCanceled.setBuddy(self.cmbPersonJournal)
        self.lblActionTypeCanceled.setBuddy(self.cmbActionTypeJournal)

        self.retranslateUi(SurgeryJournalDialog)
        self.tabSurgeryJournal.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SurgeryJournalDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SurgeryJournalDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SurgeryJournalDialog)
        SurgeryJournalDialog.setTabOrder(self.tabSurgeryJournal, self.buttonBox)
        SurgeryJournalDialog.setTabOrder(self.buttonBox, self.edtBegDateJournal)
        SurgeryJournalDialog.setTabOrder(self.edtBegDateJournal, self.tblJournal)
        SurgeryJournalDialog.setTabOrder(self.tblJournal, self.cmbMKBFilterJournal)
        SurgeryJournalDialog.setTabOrder(self.cmbMKBFilterJournal, self.edtEndDateJournal)
        SurgeryJournalDialog.setTabOrder(self.edtEndDateJournal, self.edtMKBFromJournal)
        SurgeryJournalDialog.setTabOrder(self.edtMKBFromJournal, self.edtMKBToJournal)
        SurgeryJournalDialog.setTabOrder(self.edtMKBToJournal, self.cmbPersonJournal)
        SurgeryJournalDialog.setTabOrder(self.cmbPersonJournal, self.cmbOrgStructureJournal)
        SurgeryJournalDialog.setTabOrder(self.cmbOrgStructureJournal, self.cmbActionStatusJournal)
        SurgeryJournalDialog.setTabOrder(self.cmbActionStatusJournal, self.cmbActionTypeJournal)
        SurgeryJournalDialog.setTabOrder(self.cmbActionTypeJournal, self.edtBegDateCanceled)
        SurgeryJournalDialog.setTabOrder(self.edtBegDateCanceled, self.edtEndDateCanceled)
        SurgeryJournalDialog.setTabOrder(self.edtEndDateCanceled, self.cmbMKBFilterCanceled)
        SurgeryJournalDialog.setTabOrder(self.cmbMKBFilterCanceled, self.edtMKBFromCanceled)
        SurgeryJournalDialog.setTabOrder(self.edtMKBFromCanceled, self.edtMKBToCanceled)
        SurgeryJournalDialog.setTabOrder(self.edtMKBToCanceled, self.chkActionStatusCanceled)
        SurgeryJournalDialog.setTabOrder(self.chkActionStatusCanceled, self.chkActionStatusRefused)
        SurgeryJournalDialog.setTabOrder(self.chkActionStatusRefused, self.cmbPersonCanceled)
        SurgeryJournalDialog.setTabOrder(self.cmbPersonCanceled, self.cmbOrgStructureCanceled)
        SurgeryJournalDialog.setTabOrder(self.cmbOrgStructureCanceled, self.cmbActionTypeCanceled)
        SurgeryJournalDialog.setTabOrder(self.cmbActionTypeCanceled, self.tblCanceled)
        SurgeryJournalDialog.setTabOrder(self.tblCanceled, self.edtBegDatePlan)
        SurgeryJournalDialog.setTabOrder(self.edtBegDatePlan, self.edtEndDatePlan)
        SurgeryJournalDialog.setTabOrder(self.edtEndDatePlan, self.cmbActionStatusPlan)
        SurgeryJournalDialog.setTabOrder(self.cmbActionStatusPlan, self.tblPlan)

    def retranslateUi(self, SurgeryJournalDialog):
        SurgeryJournalDialog.setWindowTitle(_translate("SurgeryJournalDialog", "Журнал операций", None))
        self.lblPeriodJournal.setText(_translate("SurgeryJournalDialog", "Период", None))
        self.edtEndDateJournal.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.edtBegDateJournal.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.cmbPersonJournal.setItemText(0, _translate("SurgeryJournalDialog", "Врач", None))
        self.lblPersonJournal.setText(_translate("SurgeryJournalDialog", "&Врач", None))
        self.lblMKBJournal.setText(_translate("SurgeryJournalDialog", "Коды диагнозов по &МКБ", None))
        self.lblOrgStructureJournal.setText(_translate("SurgeryJournalDialog", "Подразделение", None))
        self.cmbMKBFilterJournal.setItemText(0, _translate("SurgeryJournalDialog", "Игнор.", None))
        self.cmbMKBFilterJournal.setItemText(1, _translate("SurgeryJournalDialog", "Интервал", None))
        self.edtMKBToJournal.setInputMask(_translate("SurgeryJournalDialog", "a00.00; ", None))
        self.edtMKBToJournal.setText(_translate("SurgeryJournalDialog", "Z99.9", None))
        self.edtMKBFromJournal.setInputMask(_translate("SurgeryJournalDialog", "a00.00; ", None))
        self.edtMKBFromJournal.setText(_translate("SurgeryJournalDialog", "A.", None))
        self.lblActionStatusJournal.setText(_translate("SurgeryJournalDialog", "Состояние", None))
        self.lblActionTypeJournal.setText(_translate("SurgeryJournalDialog", "&Мероприятие", None))
        self.tabSurgeryJournal.setTabText(self.tabSurgeryJournal.indexOf(self.tabJournal), _translate("SurgeryJournalDialog", "Журнал", None))
        self.lblPeriodCanceled.setText(_translate("SurgeryJournalDialog", "Период", None))
        self.edtBegDateCanceled.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.cmbMKBFilterCanceled.setItemText(0, _translate("SurgeryJournalDialog", "Игнор.", None))
        self.cmbMKBFilterCanceled.setItemText(1, _translate("SurgeryJournalDialog", "Интервал", None))
        self.edtEndDateCanceled.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.lblMKBCanceled.setText(_translate("SurgeryJournalDialog", "Коды диагнозов по &МКБ", None))
        self.chkActionStatusCanceled.setText(_translate("SurgeryJournalDialog", "Отмена", None))
        self.chkActionStatusRefused.setText(_translate("SurgeryJournalDialog", "Отказ", None))
        self.edtMKBToCanceled.setInputMask(_translate("SurgeryJournalDialog", "a00.00; ", None))
        self.edtMKBToCanceled.setText(_translate("SurgeryJournalDialog", "Z99.9", None))
        self.edtMKBFromCanceled.setInputMask(_translate("SurgeryJournalDialog", "a00.00; ", None))
        self.edtMKBFromCanceled.setText(_translate("SurgeryJournalDialog", "A.", None))
        self.lblPersonCanceled.setText(_translate("SurgeryJournalDialog", "&Врач", None))
        self.cmbPersonCanceled.setItemText(0, _translate("SurgeryJournalDialog", "Врач", None))
        self.lblActionTypeCanceled.setText(_translate("SurgeryJournalDialog", "&Мероприятие", None))
        self.lblOrgStructureCanceled.setText(_translate("SurgeryJournalDialog", "Подразделение", None))
        self.tabSurgeryJournal.setTabText(self.tabSurgeryJournal.indexOf(self.tabCanceled), _translate("SurgeryJournalDialog", "Отмена", None))
        self.lblPeriodPlan.setText(_translate("SurgeryJournalDialog", "Период", None))
        self.edtBegDatePlan.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.edtEndDatePlan.setDisplayFormat(_translate("SurgeryJournalDialog", "dd.MM.yyyy", None))
        self.lblActionStatusPlan.setText(_translate("SurgeryJournalDialog", "Состояние", None))
        self.tabSurgeryJournal.setTabText(self.tabSurgeryJournal.indexOf(self.tabPlan), _translate("SurgeryJournalDialog", "План", None))
        self.lblCountRecordList.setText(_translate("SurgeryJournalDialog", "Количество записей        0", None))

from Events.ActionStatus import CActionStatusComboBox
from Events.ActionTypeComboBoxEx import CActionTypeComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.TableView import CTableView
