# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\soc-inform\Registry\HomeCallRequestsWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HomeCallRequestsWindow(object):
    def setupUi(self, HomeCallRequestsWindow):
        HomeCallRequestsWindow.setObjectName(_fromUtf8("HomeCallRequestsWindow"))
        HomeCallRequestsWindow.resize(699, 812)
        self.gridLayout_4 = QtGui.QGridLayout(HomeCallRequestsWindow)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_3 = QtGui.QSplitter(HomeCallRequestsWindow)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.grpTables = QtGui.QWidget(self.splitter_3)
        self.grpTables.setObjectName(_fromUtf8("grpTables"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTables)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.grpTables)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(4)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tblHomeCallRequests = CTableView(self.splitter)
        self.tblHomeCallRequests.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblHomeCallRequests.setObjectName(_fromUtf8("tblHomeCallRequests"))
        self.tabBeforeRecord = QtGui.QTabWidget(self.splitter_2)
        self.tabBeforeRecord.setObjectName(_fromUtf8("tabBeforeRecord"))
        self.tabBeforeRecordClient = QtGui.QWidget()
        self.tabBeforeRecordClient.setObjectName(_fromUtf8("tabBeforeRecordClient"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tabBeforeRecordClient)
        self.gridLayout_21.setMargin(4)
        self.gridLayout_21.setSpacing(4)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.tblSchedules = CTableView(self.tabBeforeRecordClient)
        self.tblSchedules.setObjectName(_fromUtf8("tblSchedules"))
        self.gridLayout_21.addWidget(self.tblSchedules, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabBeforeRecordClient, _fromUtf8(""))
        self.tabVisitBeforeRecordClient = QtGui.QWidget()
        self.tabVisitBeforeRecordClient.setObjectName(_fromUtf8("tabVisitBeforeRecordClient"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tabVisitBeforeRecordClient)
        self.gridLayout_22.setMargin(4)
        self.gridLayout_22.setSpacing(4)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tblVisitsBySchedules = CTableView(self.tabVisitBeforeRecordClient)
        self.tblVisitsBySchedules.setObjectName(_fromUtf8("tblVisitsBySchedules"))
        self.gridLayout_22.addWidget(self.tblVisitsBySchedules, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabVisitBeforeRecordClient, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 2)
        self.lblRecordCount = QtGui.QLabel(self.grpTables)
        self.lblRecordCount.setObjectName(_fromUtf8("lblRecordCount"))
        self.gridLayout_3.addWidget(self.lblRecordCount, 1, 0, 1, 2)
        self.btnPrint = CPrintButton(self.grpTables)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_3.addWidget(self.btnPrint, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(216, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.grpFilter = QtGui.QGroupBox(self.splitter_3)
        self.grpFilter.setFlat(False)
        self.grpFilter.setObjectName(_fromUtf8("grpFilter"))
        self.gridLayout = QtGui.QGridLayout(self.grpFilter)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBoxFilter = CApplyResetDialogButtonBox(self.grpFilter)
        self.buttonBoxFilter.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxFilter.setObjectName(_fromUtf8("buttonBoxFilter"))
        self.gridLayout.addWidget(self.buttonBoxFilter, 1, 0, 1, 1)
        self.tabFilter = QtGui.QTabWidget(self.grpFilter)
        self.tabFilter.setTabPosition(QtGui.QTabWidget.North)
        self.tabFilter.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabFind = QtGui.QWidget()
        self.tabFind.setObjectName(_fromUtf8("tabFind"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabFind)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblFilterStatus = QtGui.QLabel(self.tabFind)
        self.lblFilterStatus.setObjectName(_fromUtf8("lblFilterStatus"))
        self.gridLayout_2.addWidget(self.lblFilterStatus, 16, 0, 1, 1)
        self.chkFilterSex = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.gridLayout_2.addWidget(self.chkFilterSex, 8, 0, 1, 1)
        self.chkFilterEndBirthDay = QtGui.QCheckBox(self.tabFind)
        self.chkFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterEndBirthDay.setObjectName(_fromUtf8("chkFilterEndBirthDay"))
        self.gridLayout_2.addWidget(self.chkFilterEndBirthDay, 7, 0, 1, 1)
        self.edtFilterEndBirthDay = CDateEdit(self.tabFind)
        self.edtFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterEndBirthDay.setCalendarPopup(True)
        self.edtFilterEndBirthDay.setObjectName(_fromUtf8("edtFilterEndBirthDay"))
        self.gridLayout_2.addWidget(self.edtFilterEndBirthDay, 7, 1, 1, 2)
        self.cmbFilterSex = QtGui.QComboBox(self.tabFind)
        self.cmbFilterSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbFilterSex.setSizePolicy(sizePolicy)
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterSex, 8, 1, 1, 2)
        self.edtFilterFirstName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterFirstName.setEnabled(False)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.gridLayout_2.addWidget(self.edtFilterFirstName, 3, 0, 1, 3)
        self.edtFilterLastName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterLastName.setEnabled(False)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.gridLayout_2.addWidget(self.edtFilterLastName, 1, 0, 1, 3)
        self.chkFilterFirstName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.gridLayout_2.addWidget(self.chkFilterFirstName, 2, 0, 1, 3)
        self.chkFilterApplicantPhone = QtGui.QCheckBox(self.tabFind)
        self.chkFilterApplicantPhone.setObjectName(_fromUtf8("chkFilterApplicantPhone"))
        self.gridLayout_2.addWidget(self.chkFilterApplicantPhone, 9, 0, 1, 1)
        self.edtFilterBegBirthDay = CDateEdit(self.tabFind)
        self.edtFilterBegBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBegBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBegBirthDay.setCalendarPopup(True)
        self.edtFilterBegBirthDay.setObjectName(_fromUtf8("edtFilterBegBirthDay"))
        self.gridLayout_2.addWidget(self.edtFilterBegBirthDay, 6, 1, 1, 2)
        self.chkFilterBirthDay = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.gridLayout_2.addWidget(self.chkFilterBirthDay, 6, 0, 1, 1)
        self.chkFilterPatrName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.gridLayout_2.addWidget(self.chkFilterPatrName, 4, 0, 1, 3)
        self.edtFilterPatrName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterPatrName.setEnabled(False)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.gridLayout_2.addWidget(self.edtFilterPatrName, 5, 0, 1, 3)
        self.chkFilterOrgStructure = QtGui.QCheckBox(self.tabFind)
        self.chkFilterOrgStructure.setObjectName(_fromUtf8("chkFilterOrgStructure"))
        self.gridLayout_2.addWidget(self.chkFilterOrgStructure, 10, 0, 1, 3)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.tabFind)
        self.cmbFilterOrgStructure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbFilterOrgStructure, 11, 0, 1, 3)
        self.edtFilterApplicantPhone = QtGui.QLineEdit(self.tabFind)
        self.edtFilterApplicantPhone.setEnabled(False)
        self.edtFilterApplicantPhone.setObjectName(_fromUtf8("edtFilterApplicantPhone"))
        self.gridLayout_2.addWidget(self.edtFilterApplicantPhone, 9, 1, 1, 2)
        self.cmbFilterPerson = CPersonComboBoxEx(self.tabFind)
        self.cmbFilterPerson.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPerson.sizePolicy().hasHeightForWidth())
        self.cmbFilterPerson.setSizePolicy(sizePolicy)
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.gridLayout_2.addWidget(self.cmbFilterPerson, 15, 0, 1, 3)
        self.cmbFilterSpeciality = CRBComboBox(self.tabFind)
        self.cmbFilterSpeciality.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbFilterSpeciality.setSizePolicy(sizePolicy)
        self.cmbFilterSpeciality.setObjectName(_fromUtf8("cmbFilterSpeciality"))
        self.gridLayout_2.addWidget(self.cmbFilterSpeciality, 13, 0, 1, 3)
        self.chkFilterSpeciality = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSpeciality.setObjectName(_fromUtf8("chkFilterSpeciality"))
        self.gridLayout_2.addWidget(self.chkFilterSpeciality, 12, 0, 1, 3)
        self.chkFilterPerson = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPerson.setObjectName(_fromUtf8("chkFilterPerson"))
        self.gridLayout_2.addWidget(self.chkFilterPerson, 14, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 17, 0, 1, 3)
        self.chkFilterLastName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.gridLayout_2.addWidget(self.chkFilterLastName, 0, 0, 1, 3)
        self.cmbFilterStatus = QtGui.QComboBox(self.tabFind)
        self.cmbFilterStatus.setObjectName(_fromUtf8("cmbFilterStatus"))
        self.gridLayout_2.addWidget(self.cmbFilterStatus, 16, 1, 1, 2)
        self.edtFilterLastName.raise_()
        self.cmbFilterPerson.raise_()
        self.chkFilterSex.raise_()
        self.cmbFilterSex.raise_()
        self.chkFilterApplicantPhone.raise_()
        self.chkFilterPerson.raise_()
        self.chkFilterPatrName.raise_()
        self.edtFilterPatrName.raise_()
        self.edtFilterApplicantPhone.raise_()
        self.edtFilterBegBirthDay.raise_()
        self.chkFilterFirstName.raise_()
        self.edtFilterFirstName.raise_()
        self.chkFilterEndBirthDay.raise_()
        self.chkFilterLastName.raise_()
        self.chkFilterBirthDay.raise_()
        self.edtFilterEndBirthDay.raise_()
        self.chkFilterOrgStructure.raise_()
        self.cmbFilterOrgStructure.raise_()
        self.chkFilterSpeciality.raise_()
        self.cmbFilterSpeciality.raise_()
        self.cmbFilterStatus.raise_()
        self.lblFilterStatus.raise_()
        self.tabFilter.addTab(self.tabFind, _fromUtf8(""))
        self.tabFindEx = QtGui.QWidget()
        self.tabFindEx.setObjectName(_fromUtf8("tabFindEx"))
        self.gridLayout_27 = QtGui.QGridLayout(self.tabFindEx)
        self.gridLayout_27.setMargin(1)
        self.gridLayout_27.setSpacing(1)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.edtFilterExEndCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterExEndCreateDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExEndCreateDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExEndCreateDate.setSizePolicy(sizePolicy)
        self.edtFilterExEndCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExEndCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExEndCreateDate.setCalendarPopup(True)
        self.edtFilterExEndCreateDate.setObjectName(_fromUtf8("edtFilterExEndCreateDate"))
        self.gridLayout_27.addWidget(self.edtFilterExEndCreateDate, 1, 1, 1, 1)
        self.edtFilterExBegCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterExBegCreateDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExBegCreateDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExBegCreateDate.setSizePolicy(sizePolicy)
        self.edtFilterExBegCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExBegCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExBegCreateDate.setCalendarPopup(True)
        self.edtFilterExBegCreateDate.setObjectName(_fromUtf8("edtFilterExBegCreateDate"))
        self.gridLayout_27.addWidget(self.edtFilterExBegCreateDate, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(84, 181, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem2, 3, 0, 1, 3)
        self.chkFilterExCreateDate = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterExCreateDate.setObjectName(_fromUtf8("chkFilterExCreateDate"))
        self.gridLayout_27.addWidget(self.chkFilterExCreateDate, 0, 0, 1, 3)
        self.tabFilter.addTab(self.tabFindEx, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabFilter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.lblFilterStatus.setBuddy(self.cmbFilterStatus)

        self.retranslateUi(HomeCallRequestsWindow)
        self.tabBeforeRecord.setCurrentIndex(1)
        self.tabFilter.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkFilterLastName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterLastName.setEnabled)
        QtCore.QObject.connect(self.chkFilterFirstName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterFirstName.setEnabled)
        QtCore.QObject.connect(self.chkFilterPatrName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterPatrName.setEnabled)
        QtCore.QObject.connect(self.chkFilterBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterBegBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFilterEndBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterEndBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEndBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterSex.setEnabled)
        QtCore.QObject.connect(self.chkFilterApplicantPhone, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterApplicantPhone.setEnabled)
        QtCore.QObject.connect(self.chkFilterOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkFilterSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkFilterPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterPerson.setEnabled)
        QtCore.QObject.connect(self.chkFilterExCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExBegCreateDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterExCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExEndCreateDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(HomeCallRequestsWindow)
        HomeCallRequestsWindow.setTabOrder(self.txtClientInfoBrowser, self.tblHomeCallRequests)
        HomeCallRequestsWindow.setTabOrder(self.tblHomeCallRequests, self.tabBeforeRecord)
        HomeCallRequestsWindow.setTabOrder(self.tabBeforeRecord, self.tblSchedules)
        HomeCallRequestsWindow.setTabOrder(self.tblSchedules, self.tblVisitsBySchedules)
        HomeCallRequestsWindow.setTabOrder(self.tblVisitsBySchedules, self.tabFilter)
        HomeCallRequestsWindow.setTabOrder(self.tabFilter, self.chkFilterLastName)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterPatrName, self.chkFilterBirthDay)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterBirthDay, self.edtFilterBegBirthDay)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterBegBirthDay, self.chkFilterEndBirthDay)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterEndBirthDay, self.edtFilterEndBirthDay)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterEndBirthDay, self.chkFilterSex)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterSex, self.cmbFilterSex)
        HomeCallRequestsWindow.setTabOrder(self.cmbFilterSex, self.chkFilterApplicantPhone)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterApplicantPhone, self.edtFilterApplicantPhone)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterApplicantPhone, self.chkFilterOrgStructure)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterOrgStructure, self.cmbFilterOrgStructure)
        HomeCallRequestsWindow.setTabOrder(self.cmbFilterOrgStructure, self.chkFilterSpeciality)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterSpeciality, self.cmbFilterSpeciality)
        HomeCallRequestsWindow.setTabOrder(self.cmbFilterSpeciality, self.chkFilterPerson)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterPerson, self.cmbFilterPerson)
        HomeCallRequestsWindow.setTabOrder(self.cmbFilterPerson, self.cmbFilterStatus)
        HomeCallRequestsWindow.setTabOrder(self.cmbFilterStatus, self.chkFilterExCreateDate)
        HomeCallRequestsWindow.setTabOrder(self.chkFilterExCreateDate, self.edtFilterExBegCreateDate)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterExBegCreateDate, self.edtFilterExEndCreateDate)
        HomeCallRequestsWindow.setTabOrder(self.edtFilterExEndCreateDate, self.buttonBoxFilter)

    def retranslateUi(self, HomeCallRequestsWindow):
        HomeCallRequestsWindow.setWindowTitle(_translate("HomeCallRequestsWindow", "Журнал вызова врача на дом", None))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabBeforeRecordClient), _translate("HomeCallRequestsWindow", "Предварительная запись", None))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabVisitBeforeRecordClient), _translate("HomeCallRequestsWindow", "Выполнение записи", None))
        self.lblRecordCount.setText(_translate("HomeCallRequestsWindow", "Список пуст", None))
        self.btnPrint.setText(_translate("HomeCallRequestsWindow", "Печать (F6)", None))
        self.btnPrint.setShortcut(_translate("HomeCallRequestsWindow", "F6", None))
        self.grpFilter.setTitle(_translate("HomeCallRequestsWindow", "Фильтр", None))
        self.lblFilterStatus.setText(_translate("HomeCallRequestsWindow", "Статус", None))
        self.chkFilterSex.setText(_translate("HomeCallRequestsWindow", "Пол", None))
        self.chkFilterEndBirthDay.setText(_translate("HomeCallRequestsWindow", "по", None))
        self.cmbFilterSex.setItemText(1, _translate("HomeCallRequestsWindow", "М", None))
        self.cmbFilterSex.setItemText(2, _translate("HomeCallRequestsWindow", "Ж", None))
        self.chkFilterFirstName.setText(_translate("HomeCallRequestsWindow", "Имя", None))
        self.chkFilterApplicantPhone.setText(_translate("HomeCallRequestsWindow", "Телефон", None))
        self.chkFilterBirthDay.setText(_translate("HomeCallRequestsWindow", "Дата рожд", None))
        self.chkFilterPatrName.setText(_translate("HomeCallRequestsWindow", "Отчество", None))
        self.chkFilterOrgStructure.setText(_translate("HomeCallRequestsWindow", "Подразделение ", None))
        self.chkFilterSpeciality.setText(_translate("HomeCallRequestsWindow", "Специальность", None))
        self.chkFilterPerson.setText(_translate("HomeCallRequestsWindow", "Врач", None))
        self.chkFilterLastName.setText(_translate("HomeCallRequestsWindow", "Фамилия", None))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFind), _translate("HomeCallRequestsWindow", "&Поиск", None))
        self.chkFilterExCreateDate.setText(_translate("HomeCallRequestsWindow", "Дата создания", None))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFindEx), _translate("HomeCallRequestsWindow", "&Расширенный поиск", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.PrintTemplates import CPrintButton
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
