# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\Registry\IdentityPatientService.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IdentityPatientServiceDialog(object):
    def setupUi(self, IdentityPatientServiceDialog):
        IdentityPatientServiceDialog.setObjectName(_fromUtf8("IdentityPatientServiceDialog"))
        IdentityPatientServiceDialog.resize(1008, 823)
        self.gridLayout = QtGui.QGridLayout(IdentityPatientServiceDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_Main = QtGui.QHBoxLayout()
        self.horizontalLayout_Main.setObjectName(_fromUtf8("horizontalLayout_Main"))
        self.verticalLayout_TableArea = QtGui.QVBoxLayout()
        self.verticalLayout_TableArea.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_TableArea.setObjectName(_fromUtf8("verticalLayout_TableArea"))
        self.horizontalLayout_TopButtons = QtGui.QHBoxLayout()
        self.horizontalLayout_TopButtons.setSpacing(6)
        self.horizontalLayout_TopButtons.setObjectName(_fromUtf8("horizontalLayout_TopButtons"))
        self.btnRefreshData = QtGui.QPushButton(IdentityPatientServiceDialog)
        self.btnRefreshData.setObjectName(_fromUtf8("btnRefreshData"))
        self.horizontalLayout_TopButtons.addWidget(self.btnRefreshData)
        self.btnGetDataFromService = QtGui.QPushButton(IdentityPatientServiceDialog)
        self.btnGetDataFromService.setObjectName(_fromUtf8("btnGetDataFromService"))
        self.horizontalLayout_TopButtons.addWidget(self.btnGetDataFromService)
        self.btnGetDataFromServiceAll = QtGui.QPushButton(IdentityPatientServiceDialog)
        self.btnGetDataFromServiceAll.setObjectName(_fromUtf8("btnGetDataFromServiceAll"))
        self.horizontalLayout_TopButtons.addWidget(self.btnGetDataFromServiceAll)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_TopButtons.addItem(spacerItem)
        self.verticalLayout_TableArea.addLayout(self.horizontalLayout_TopButtons)
        self.tblIdentityPatient = CTableView(IdentityPatientServiceDialog)
        self.tblIdentityPatient.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tblIdentityPatient.setObjectName(_fromUtf8("tblIdentityPatient"))
        self.verticalLayout_TableArea.addWidget(self.tblIdentityPatient)
        self.horizontalLayout_Data = QtGui.QHBoxLayout()
        self.horizontalLayout_Data.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_Data.setObjectName(_fromUtf8("horizontalLayout_Data"))
        self.groupBox_DataToService = QtGui.QGroupBox(IdentityPatientServiceDialog)
        self.groupBox_DataToService.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_DataToService.setObjectName(_fromUtf8("groupBox_DataToService"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_DataToService)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_DataToService = QtGui.QVBoxLayout()
        self.verticalLayout_DataToService.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_DataToService.setObjectName(_fromUtf8("verticalLayout_DataToService"))
        self.horizontalLayout_RequestDate = QtGui.QHBoxLayout()
        self.horizontalLayout_RequestDate.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_RequestDate.setObjectName(_fromUtf8("horizontalLayout_RequestDate"))
        self.lblRequestDate = QtGui.QLabel(self.groupBox_DataToService)
        self.lblRequestDate.setMinimumSize(QtCore.QSize(80, 20))
        self.lblRequestDate.setObjectName(_fromUtf8("lblRequestDate"))
        self.horizontalLayout_RequestDate.addWidget(self.lblRequestDate)
        self.edtRequestDate = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtRequestDate.setObjectName(_fromUtf8("edtRequestDate"))
        self.horizontalLayout_RequestDate.addWidget(self.edtRequestDate)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_RequestDate)
        self.horizontalLayout_Fio = QtGui.QHBoxLayout()
        self.horizontalLayout_Fio.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_Fio.setObjectName(_fromUtf8("horizontalLayout_Fio"))
        self.lblFio = QtGui.QLabel(self.groupBox_DataToService)
        self.lblFio.setMinimumSize(QtCore.QSize(0, 20))
        self.lblFio.setObjectName(_fromUtf8("lblFio"))
        self.horizontalLayout_Fio.addWidget(self.lblFio)
        self.edtLastName = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtLastName.setReadOnly(True)
        self.edtLastName.setObjectName(_fromUtf8("edtLastName"))
        self.horizontalLayout_Fio.addWidget(self.edtLastName)
        self.edtFirstName = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtFirstName.setReadOnly(True)
        self.edtFirstName.setObjectName(_fromUtf8("edtFirstName"))
        self.horizontalLayout_Fio.addWidget(self.edtFirstName)
        self.edtPatrName = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtPatrName.setReadOnly(True)
        self.edtPatrName.setObjectName(_fromUtf8("edtPatrName"))
        self.horizontalLayout_Fio.addWidget(self.edtPatrName)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_Fio)
        self.horizontalLayout_BirthDate = QtGui.QHBoxLayout()
        self.horizontalLayout_BirthDate.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_BirthDate.setObjectName(_fromUtf8("horizontalLayout_BirthDate"))
        self.lblBirthDate = QtGui.QLabel(self.groupBox_DataToService)
        self.lblBirthDate.setMinimumSize(QtCore.QSize(80, 20))
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.horizontalLayout_BirthDate.addWidget(self.lblBirthDate)
        self.edtBirthDate = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtBirthDate.setObjectName(_fromUtf8("edtBirthDate"))
        self.horizontalLayout_BirthDate.addWidget(self.edtBirthDate)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_BirthDate)
        self.horizontalLayout_ClientId = QtGui.QHBoxLayout()
        self.horizontalLayout_ClientId.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_ClientId.setObjectName(_fromUtf8("horizontalLayout_ClientId"))
        self.lblClientId = QtGui.QLabel(self.groupBox_DataToService)
        self.lblClientId.setMinimumSize(QtCore.QSize(0, 20))
        self.lblClientId.setObjectName(_fromUtf8("lblClientId"))
        self.horizontalLayout_ClientId.addWidget(self.lblClientId)
        self.edtClientId = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtClientId.setReadOnly(True)
        self.edtClientId.setObjectName(_fromUtf8("edtClientId"))
        self.horizontalLayout_ClientId.addWidget(self.edtClientId)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_ClientId)
        self.horizontalLayout_DocumentTypeCode = QtGui.QHBoxLayout()
        self.horizontalLayout_DocumentTypeCode.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_DocumentTypeCode.setObjectName(_fromUtf8("horizontalLayout_DocumentTypeCode"))
        self.lblDocumentTypeCode = QtGui.QLabel(self.groupBox_DataToService)
        self.lblDocumentTypeCode.setMinimumSize(QtCore.QSize(80, 20))
        self.lblDocumentTypeCode.setObjectName(_fromUtf8("lblDocumentTypeCode"))
        self.horizontalLayout_DocumentTypeCode.addWidget(self.lblDocumentTypeCode)
        self.edtDocumentTypeCode = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtDocumentTypeCode.setReadOnly(True)
        self.edtDocumentTypeCode.setObjectName(_fromUtf8("edtDocumentTypeCode"))
        self.horizontalLayout_DocumentTypeCode.addWidget(self.edtDocumentTypeCode)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_DocumentTypeCode)
        self.horizontalLayout_Serial = QtGui.QHBoxLayout()
        self.horizontalLayout_Serial.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_Serial.setObjectName(_fromUtf8("horizontalLayout_Serial"))
        self.lblSerial = QtGui.QLabel(self.groupBox_DataToService)
        self.lblSerial.setMinimumSize(QtCore.QSize(80, 20))
        self.lblSerial.setObjectName(_fromUtf8("lblSerial"))
        self.horizontalLayout_Serial.addWidget(self.lblSerial)
        self.edtSerial = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtSerial.setReadOnly(True)
        self.edtSerial.setObjectName(_fromUtf8("edtSerial"))
        self.horizontalLayout_Serial.addWidget(self.edtSerial)
        self.lblNumber = QtGui.QLabel(self.groupBox_DataToService)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.horizontalLayout_Serial.addWidget(self.lblNumber)
        self.edtNumber = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtNumber.setReadOnly(True)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.horizontalLayout_Serial.addWidget(self.edtNumber)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_Serial)
        self.horizontalLayout_PolicyKindCode = QtGui.QHBoxLayout()
        self.horizontalLayout_PolicyKindCode.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_PolicyKindCode.setObjectName(_fromUtf8("horizontalLayout_PolicyKindCode"))
        self.lblPolicyKindCode = QtGui.QLabel(self.groupBox_DataToService)
        self.lblPolicyKindCode.setMinimumSize(QtCore.QSize(80, 20))
        self.lblPolicyKindCode.setObjectName(_fromUtf8("lblPolicyKindCode"))
        self.horizontalLayout_PolicyKindCode.addWidget(self.lblPolicyKindCode)
        self.edtPolicyKindCode = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtPolicyKindCode.setReadOnly(True)
        self.edtPolicyKindCode.setObjectName(_fromUtf8("edtPolicyKindCode"))
        self.horizontalLayout_PolicyKindCode.addWidget(self.edtPolicyKindCode)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_PolicyKindCode)
        self.horizontalLayout_PolicySerial = QtGui.QHBoxLayout()
        self.horizontalLayout_PolicySerial.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_PolicySerial.setObjectName(_fromUtf8("horizontalLayout_PolicySerial"))
        self.lblPolicySerial = QtGui.QLabel(self.groupBox_DataToService)
        self.lblPolicySerial.setMinimumSize(QtCore.QSize(80, 20))
        self.lblPolicySerial.setObjectName(_fromUtf8("lblPolicySerial"))
        self.horizontalLayout_PolicySerial.addWidget(self.lblPolicySerial)
        self.edtPolicySerial = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtPolicySerial.setReadOnly(True)
        self.edtPolicySerial.setObjectName(_fromUtf8("edtPolicySerial"))
        self.horizontalLayout_PolicySerial.addWidget(self.edtPolicySerial)
        self.lblPolicyNumber = QtGui.QLabel(self.groupBox_DataToService)
        self.lblPolicyNumber.setObjectName(_fromUtf8("lblPolicyNumber"))
        self.horizontalLayout_PolicySerial.addWidget(self.lblPolicyNumber)
        self.edtPolicyNumber = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtPolicyNumber.setReadOnly(True)
        self.edtPolicyNumber.setObjectName(_fromUtf8("edtPolicyNumber"))
        self.horizontalLayout_PolicySerial.addWidget(self.edtPolicyNumber)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_PolicySerial)
        self.horizontalLayout_CodeMO = QtGui.QHBoxLayout()
        self.horizontalLayout_CodeMO.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_CodeMO.setObjectName(_fromUtf8("horizontalLayout_CodeMO"))
        self.lblCodeMO = QtGui.QLabel(self.groupBox_DataToService)
        self.lblCodeMO.setMinimumSize(QtCore.QSize(80, 20))
        self.lblCodeMO.setObjectName(_fromUtf8("lblCodeMO"))
        self.horizontalLayout_CodeMO.addWidget(self.lblCodeMO)
        self.edtCodeMO = QtGui.QLineEdit(self.groupBox_DataToService)
        self.edtCodeMO.setReadOnly(True)
        self.edtCodeMO.setObjectName(_fromUtf8("edtCodeMO"))
        self.horizontalLayout_CodeMO.addWidget(self.edtCodeMO)
        self.verticalLayout_DataToService.addLayout(self.horizontalLayout_CodeMO)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_DataToService.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.verticalLayout_DataToService, 0, 0, 1, 1)
        self.horizontalLayout_Data.addWidget(self.groupBox_DataToService)
        self.groupBox_DataFromService = QtGui.QGroupBox(IdentityPatientServiceDialog)
        self.groupBox_DataFromService.setObjectName(_fromUtf8("groupBox_DataFromService"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_DataFromService)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_DataFromService = QtGui.QVBoxLayout()
        self.verticalLayout_DataFromService.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_DataFromService.setObjectName(_fromUtf8("verticalLayout_DataFromService"))
        self.horizontalLayout_ServerId = QtGui.QHBoxLayout()
        self.horizontalLayout_ServerId.setObjectName(_fromUtf8("horizontalLayout_ServerId"))
        self.lblServerId = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblServerId.setMinimumSize(QtCore.QSize(80, 0))
        self.lblServerId.setObjectName(_fromUtf8("lblServerId"))
        self.horizontalLayout_ServerId.addWidget(self.lblServerId)
        self.edtServerId = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtServerId.setReadOnly(True)
        self.edtServerId.setObjectName(_fromUtf8("edtServerId"))
        self.horizontalLayout_ServerId.addWidget(self.edtServerId)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_ServerId)
        self.horizontalLayout_ErrorDate = QtGui.QHBoxLayout()
        self.horizontalLayout_ErrorDate.setObjectName(_fromUtf8("horizontalLayout_ErrorDate"))
        self.lblErrorDate = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblErrorDate.setObjectName(_fromUtf8("lblErrorDate"))
        self.horizontalLayout_ErrorDate.addWidget(self.lblErrorDate)
        self.edtErrorDate = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtErrorDate.setObjectName(_fromUtf8("edtErrorDate"))
        self.horizontalLayout_ErrorDate.addWidget(self.edtErrorDate)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_ErrorDate)
        self.horizontalLayout_Error = QtGui.QHBoxLayout()
        self.horizontalLayout_Error.setObjectName(_fromUtf8("horizontalLayout_Error"))
        self.lblError = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblError.setMinimumSize(QtCore.QSize(80, 0))
        self.lblError.setObjectName(_fromUtf8("lblError"))
        self.horizontalLayout_Error.addWidget(self.lblError)
        self.edtError = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtError.setReadOnly(True)
        self.edtError.setObjectName(_fromUtf8("edtError"))
        self.horizontalLayout_Error.addWidget(self.edtError)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_Error)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblResponseInfoDate = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponseInfoDate.setObjectName(_fromUtf8("lblResponseInfoDate"))
        self.horizontalLayout_2.addWidget(self.lblResponseInfoDate)
        self.edtResponseInfoDate = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseInfoDate.setReadOnly(True)
        self.edtResponseInfoDate.setObjectName(_fromUtf8("edtResponseInfoDate"))
        self.horizontalLayout_2.addWidget(self.edtResponseInfoDate)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblResponsePolicyType = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponsePolicyType.setMinimumSize(QtCore.QSize(80, 0))
        self.lblResponsePolicyType.setObjectName(_fromUtf8("lblResponsePolicyType"))
        self.horizontalLayout_3.addWidget(self.lblResponsePolicyType)
        self.edtResponsePolicyType = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponsePolicyType.setReadOnly(True)
        self.edtResponsePolicyType.setObjectName(_fromUtf8("edtResponsePolicyType"))
        self.horizontalLayout_3.addWidget(self.edtResponsePolicyType)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblResponsePolicySerial = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponsePolicySerial.setMinimumSize(QtCore.QSize(80, 0))
        self.lblResponsePolicySerial.setObjectName(_fromUtf8("lblResponsePolicySerial"))
        self.horizontalLayout_4.addWidget(self.lblResponsePolicySerial)
        self.edtResponsePolicySerial = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponsePolicySerial.setReadOnly(True)
        self.edtResponsePolicySerial.setObjectName(_fromUtf8("edtResponsePolicySerial"))
        self.horizontalLayout_4.addWidget(self.edtResponsePolicySerial)
        self.lblResponsePolicyNumber = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponsePolicyNumber.setMinimumSize(QtCore.QSize(90, 0))
        self.lblResponsePolicyNumber.setObjectName(_fromUtf8("lblResponsePolicyNumber"))
        self.horizontalLayout_4.addWidget(self.lblResponsePolicyNumber)
        self.edtResponsePolicyNumber = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponsePolicyNumber.setReadOnly(True)
        self.edtResponsePolicyNumber.setObjectName(_fromUtf8("edtResponsePolicyNumber"))
        self.horizontalLayout_4.addWidget(self.edtResponsePolicyNumber)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblResponseBegDate = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponseBegDate.setMinimumSize(QtCore.QSize(80, 0))
        self.lblResponseBegDate.setObjectName(_fromUtf8("lblResponseBegDate"))
        self.horizontalLayout_5.addWidget(self.lblResponseBegDate)
        self.edtResponseBegDate = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseBegDate.setReadOnly(True)
        self.edtResponseBegDate.setObjectName(_fromUtf8("edtResponseBegDate"))
        self.horizontalLayout_5.addWidget(self.edtResponseBegDate)
        self.lblResponseEndDate = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponseEndDate.setMinimumSize(QtCore.QSize(90, 0))
        self.lblResponseEndDate.setObjectName(_fromUtf8("lblResponseEndDate"))
        self.horizontalLayout_5.addWidget(self.lblResponseEndDate)
        self.edtResponseEndDate = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseEndDate.setReadOnly(True)
        self.edtResponseEndDate.setObjectName(_fromUtf8("edtResponseEndDate"))
        self.horizontalLayout_5.addWidget(self.edtResponseEndDate)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblResponseOKATO = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponseOKATO.setObjectName(_fromUtf8("lblResponseOKATO"))
        self.horizontalLayout_6.addWidget(self.lblResponseOKATO)
        self.edtResponseOKATO = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseOKATO.setReadOnly(True)
        self.edtResponseOKATO.setObjectName(_fromUtf8("edtResponseOKATO"))
        self.horizontalLayout_6.addWidget(self.edtResponseOKATO)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblResponseCodeSMO = QtGui.QLabel(self.groupBox_DataFromService)
        self.lblResponseCodeSMO.setMinimumSize(QtCore.QSize(80, 0))
        self.lblResponseCodeSMO.setObjectName(_fromUtf8("lblResponseCodeSMO"))
        self.horizontalLayout_7.addWidget(self.lblResponseCodeSMO)
        self.edtResponseCodeSMO = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseCodeSMO.setReadOnly(True)
        self.edtResponseCodeSMO.setObjectName(_fromUtf8("edtResponseCodeSMO"))
        self.horizontalLayout_7.addWidget(self.edtResponseCodeSMO)
        self.edtResponseCodeSMOInfo = QtGui.QLineEdit(self.groupBox_DataFromService)
        self.edtResponseCodeSMOInfo.setReadOnly(True)
        self.edtResponseCodeSMOInfo.setObjectName(_fromUtf8("edtResponseCodeSMOInfo"))
        self.horizontalLayout_7.addWidget(self.edtResponseCodeSMOInfo)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_7.setStretch(2, 5)
        self.verticalLayout_DataFromService.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_DataFromService.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.verticalLayout_DataFromService, 0, 0, 1, 1)
        self.horizontalLayout_Data.addWidget(self.groupBox_DataFromService)
        self.verticalLayout_TableArea.addLayout(self.horizontalLayout_Data)
        self.horizontalLayout_Main.addLayout(self.verticalLayout_TableArea)
        self.groupBox_Filters = QtGui.QGroupBox(IdentityPatientServiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Filters.sizePolicy().hasHeightForWidth())
        self.groupBox_Filters.setSizePolicy(sizePolicy)
        self.groupBox_Filters.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_Filters.setObjectName(_fromUtf8("groupBox_Filters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_Filters)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_Filters = QtGui.QVBoxLayout()
        self.verticalLayout_Filters.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_Filters.setSpacing(6)
        self.verticalLayout_Filters.setObjectName(_fromUtf8("verticalLayout_Filters"))
        self.lblFilterLastName = QtGui.QLabel(self.groupBox_Filters)
        self.lblFilterLastName.setObjectName(_fromUtf8("lblFilterLastName"))
        self.verticalLayout_Filters.addWidget(self.lblFilterLastName)
        self.horizontalLayout_FilterLastName = QtGui.QHBoxLayout()
        self.horizontalLayout_FilterLastName.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_FilterLastName.setObjectName(_fromUtf8("horizontalLayout_FilterLastName"))
        self.edtFilterLastName = QtGui.QLineEdit(self.groupBox_Filters)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.horizontalLayout_FilterLastName.addWidget(self.edtFilterLastName)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout_FilterLastName)
        self.lblFilterFirstName = QtGui.QLabel(self.groupBox_Filters)
        self.lblFilterFirstName.setObjectName(_fromUtf8("lblFilterFirstName"))
        self.verticalLayout_Filters.addWidget(self.lblFilterFirstName)
        self.horizontalLayout_FilterFirstName = QtGui.QHBoxLayout()
        self.horizontalLayout_FilterFirstName.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_FilterFirstName.setObjectName(_fromUtf8("horizontalLayout_FilterFirstName"))
        self.edtFilterFirstName = QtGui.QLineEdit(self.groupBox_Filters)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.horizontalLayout_FilterFirstName.addWidget(self.edtFilterFirstName)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout_FilterFirstName)
        self.lblFilterPatrName = QtGui.QLabel(self.groupBox_Filters)
        self.lblFilterPatrName.setObjectName(_fromUtf8("lblFilterPatrName"))
        self.verticalLayout_Filters.addWidget(self.lblFilterPatrName)
        self.horizontalLayout_FilterPatrName = QtGui.QHBoxLayout()
        self.horizontalLayout_FilterPatrName.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_FilterPatrName.setObjectName(_fromUtf8("horizontalLayout_FilterPatrName"))
        self.edtFilterPatrName = QtGui.QLineEdit(self.groupBox_Filters)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.horizontalLayout_FilterPatrName.addWidget(self.edtFilterPatrName)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout_FilterPatrName)
        self.lblFilterRequestDate = QtGui.QLabel(self.groupBox_Filters)
        self.lblFilterRequestDate.setObjectName(_fromUtf8("lblFilterRequestDate"))
        self.verticalLayout_Filters.addWidget(self.lblFilterRequestDate)
        self.horizontalLayout_FilterRequestDates = QtGui.QHBoxLayout()
        self.horizontalLayout_FilterRequestDates.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_FilterRequestDates.setObjectName(_fromUtf8("horizontalLayout_FilterRequestDates"))
        self.lblFilterRequestBegDate = QtGui.QLabel(self.groupBox_Filters)
        self.lblFilterRequestBegDate.setMinimumSize(QtCore.QSize(20, 0))
        self.lblFilterRequestBegDate.setObjectName(_fromUtf8("lblFilterRequestBegDate"))
        self.horizontalLayout_FilterRequestDates.addWidget(self.lblFilterRequestBegDate)
        self.edtFilterRequestBegDate = CDateEdit(self.groupBox_Filters)
        self.edtFilterRequestBegDate.setCalendarPopup(True)
        self.edtFilterRequestBegDate.setObjectName(_fromUtf8("edtFilterRequestBegDate"))
        self.horizontalLayout_FilterRequestDates.addWidget(self.edtFilterRequestBegDate)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_FilterRequestDates.addItem(spacerItem3)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout_FilterRequestDates)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblRequestEndDate = QtGui.QLabel(self.groupBox_Filters)
        self.lblRequestEndDate.setMinimumSize(QtCore.QSize(20, 0))
        self.lblRequestEndDate.setObjectName(_fromUtf8("lblRequestEndDate"))
        self.horizontalLayout.addWidget(self.lblRequestEndDate)
        self.edtFilterRequestEndDate = CDateEdit(self.groupBox_Filters)
        self.edtFilterRequestEndDate.setCalendarPopup(True)
        self.edtFilterRequestEndDate.setObjectName(_fromUtf8("edtFilterRequestEndDate"))
        self.horizontalLayout.addWidget(self.edtFilterRequestEndDate)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout)
        self.lblResponseFilter = QtGui.QLabel(self.groupBox_Filters)
        self.lblResponseFilter.setObjectName(_fromUtf8("lblResponseFilter"))
        self.verticalLayout_Filters.addWidget(self.lblResponseFilter)
        self.horizontalLayout_RequestFilter = QtGui.QHBoxLayout()
        self.horizontalLayout_RequestFilter.setObjectName(_fromUtf8("horizontalLayout_RequestFilter"))
        self.cmbResponseFilter = QtGui.QComboBox(self.groupBox_Filters)
        self.cmbResponseFilter.setObjectName(_fromUtf8("cmbResponseFilter"))
        self.cmbResponseFilter.addItem(_fromUtf8(""))
        self.cmbResponseFilter.addItem(_fromUtf8(""))
        self.cmbResponseFilter.addItem(_fromUtf8(""))
        self.cmbResponseFilter.addItem(_fromUtf8(""))
        self.horizontalLayout_RequestFilter.addWidget(self.cmbResponseFilter)
        self.verticalLayout_Filters.addLayout(self.horizontalLayout_RequestFilter)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_Filters.addItem(spacerItem5)
        self.buttonBoxClient = CApplyResetDialogButtonBox(self.groupBox_Filters)
        self.buttonBoxClient.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxClient.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxClient.setObjectName(_fromUtf8("buttonBoxClient"))
        self.verticalLayout_Filters.addWidget(self.buttonBoxClient)
        self.gridLayout_2.addLayout(self.verticalLayout_Filters, 0, 0, 1, 1)
        self.horizontalLayout_Main.addWidget(self.groupBox_Filters)
        self.gridLayout.addLayout(self.horizontalLayout_Main, 0, 1, 1, 1)

        self.retranslateUi(IdentityPatientServiceDialog)
        QtCore.QMetaObject.connectSlotsByName(IdentityPatientServiceDialog)

    def retranslateUi(self, IdentityPatientServiceDialog):
        IdentityPatientServiceDialog.setWindowTitle(_translate("IdentityPatientServiceDialog", "Идентификация граждан в сфере ОМС", None))
        self.btnRefreshData.setText(_translate("IdentityPatientServiceDialog", "Обновить данные в БД", None))
        self.btnGetDataFromService.setText(_translate("IdentityPatientServiceDialog", "Получить информацию из сервиса", None))
        self.btnGetDataFromServiceAll.setText(_translate("IdentityPatientServiceDialog", "Получить информацию по 100 последним запросам", None))
        self.groupBox_DataToService.setTitle(_translate("IdentityPatientServiceDialog", "Данные отправленные в сервис", None))
        self.lblRequestDate.setText(_translate("IdentityPatientServiceDialog", "Дата запроса", None))
        self.lblFio.setText(_translate("IdentityPatientServiceDialog", "ФИО", None))
        self.lblBirthDate.setText(_translate("IdentityPatientServiceDialog", "Дата рождения", None))
        self.lblClientId.setText(_translate("IdentityPatientServiceDialog", "Идентификатор пациента в МИС", None))
        self.lblDocumentTypeCode.setText(_translate("IdentityPatientServiceDialog", "Тип документа", None))
        self.lblSerial.setText(_translate("IdentityPatientServiceDialog", "Серия", None))
        self.lblNumber.setText(_translate("IdentityPatientServiceDialog", "Номер", None))
        self.lblPolicyKindCode.setText(_translate("IdentityPatientServiceDialog", "Тип полиса", None))
        self.lblPolicySerial.setText(_translate("IdentityPatientServiceDialog", "Серия", None))
        self.lblPolicyNumber.setText(_translate("IdentityPatientServiceDialog", "Номер", None))
        self.lblCodeMO.setText(_translate("IdentityPatientServiceDialog", "Код МО", None))
        self.groupBox_DataFromService.setTitle(_translate("IdentityPatientServiceDialog", "Данные полученные из сервиса", None))
        self.lblServerId.setText(_translate("IdentityPatientServiceDialog", "Серверный ID", None))
        self.lblErrorDate.setText(_translate("IdentityPatientServiceDialog", "Дата получения ошибки", None))
        self.lblError.setText(_translate("IdentityPatientServiceDialog", "Ошибка", None))
        self.lblResponseInfoDate.setText(_translate("IdentityPatientServiceDialog", "Дата получения информации", None))
        self.lblResponsePolicyType.setText(_translate("IdentityPatientServiceDialog", "Тип полиса", None))
        self.lblResponsePolicySerial.setText(_translate("IdentityPatientServiceDialog", "Серия", None))
        self.lblResponsePolicyNumber.setText(_translate("IdentityPatientServiceDialog", "Номер", None))
        self.lblResponseBegDate.setText(_translate("IdentityPatientServiceDialog", "Дата начала", None))
        self.lblResponseEndDate.setText(_translate("IdentityPatientServiceDialog", "Дата окончания", None))
        self.lblResponseOKATO.setText(_translate("IdentityPatientServiceDialog", "Код субъекта РФ по ОКАТО", None))
        self.lblResponseCodeSMO.setText(_translate("IdentityPatientServiceDialog", "Код СМО", None))
        self.groupBox_Filters.setTitle(_translate("IdentityPatientServiceDialog", "Фильтры", None))
        self.lblFilterLastName.setText(_translate("IdentityPatientServiceDialog", "Фамилия:", None))
        self.lblFilterFirstName.setText(_translate("IdentityPatientServiceDialog", "Имя:", None))
        self.lblFilterPatrName.setText(_translate("IdentityPatientServiceDialog", "Отчество:", None))
        self.lblFilterRequestDate.setText(_translate("IdentityPatientServiceDialog", "Дата запроса:", None))
        self.lblFilterRequestBegDate.setText(_translate("IdentityPatientServiceDialog", "с", None))
        self.lblRequestEndDate.setText(_translate("IdentityPatientServiceDialog", "по", None))
        self.lblResponseFilter.setText(_translate("IdentityPatientServiceDialog", "Показать запросы:", None))
        self.cmbResponseFilter.setItemText(0, _translate("IdentityPatientServiceDialog", "Все", None))
        self.cmbResponseFilter.setItemText(1, _translate("IdentityPatientServiceDialog", "Не обработанные", None))
        self.cmbResponseFilter.setItemText(2, _translate("IdentityPatientServiceDialog", "Без ошибок", None))
        self.cmbResponseFilter.setItemText(3, _translate("IdentityPatientServiceDialog", "С ошибками", None))

from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.TableView import CTableView
