# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\Samson\UP_s11\client_merge\Registry\SuspendedAppointment.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SuspenedAppointmentWindow(object):
    def setupUi(self, SuspenedAppointmentWindow):
        SuspenedAppointmentWindow.setObjectName(_fromUtf8("SuspenedAppointmentWindow"))
        SuspenedAppointmentWindow.resize(642, 812)
        self.gridLayout_3 = QtGui.QGridLayout(SuspenedAppointmentWindow)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grpTables = QtGui.QWidget(SuspenedAppointmentWindow)
        self.grpTables.setObjectName(_fromUtf8("grpTables"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpTables)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_2 = QtGui.QSplitter(self.grpTables)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(4)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tblSuspendedAppointments = CTableView(self.splitter)
        self.tblSuspendedAppointments.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblSuspendedAppointments.setObjectName(_fromUtf8("tblSuspendedAppointments"))
        self.tabBeforeRecord = QtGui.QTabWidget(self.splitter_2)
        self.tabBeforeRecord.setObjectName(_fromUtf8("tabBeforeRecord"))
        self.tabBeforeRecordClient = QtGui.QWidget()
        self.tabBeforeRecordClient.setObjectName(_fromUtf8("tabBeforeRecordClient"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tabBeforeRecordClient)
        self.gridLayout_21.setMargin(4)
        self.gridLayout_21.setSpacing(4)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.tblSchedules = CSchedulesTableView(self.tabBeforeRecordClient)
        self.tblSchedules.setObjectName(_fromUtf8("tblSchedules"))
        self.gridLayout_21.addWidget(self.tblSchedules, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabBeforeRecordClient, _fromUtf8(""))
        self.tabVisitBeforeRecordClient = QtGui.QWidget()
        self.tabVisitBeforeRecordClient.setObjectName(_fromUtf8("tabVisitBeforeRecordClient"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tabVisitBeforeRecordClient)
        self.gridLayout_22.setMargin(4)
        self.gridLayout_22.setSpacing(4)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tblVisitsBySchedules = CSchedulesTableView(self.tabVisitBeforeRecordClient)
        self.tblVisitsBySchedules.setObjectName(_fromUtf8("tblVisitsBySchedules"))
        self.gridLayout_22.addWidget(self.tblVisitsBySchedules, 0, 0, 1, 1)
        self.tabBeforeRecord.addTab(self.tabVisitBeforeRecordClient, _fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter_2)
        self.lblRecordCount = QtGui.QLabel(self.grpTables)
        self.lblRecordCount.setObjectName(_fromUtf8("lblRecordCount"))
        self.verticalLayout.addWidget(self.lblRecordCount)
        self.gridLayout_3.addWidget(self.grpTables, 0, 0, 1, 3)
        self.grpFilter = QtGui.QGroupBox(SuspenedAppointmentWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpFilter.sizePolicy().hasHeightForWidth())
        self.grpFilter.setSizePolicy(sizePolicy)
        self.grpFilter.setMinimumSize(QtCore.QSize(100, 0))
        self.grpFilter.setMaximumSize(QtCore.QSize(250, 16777215))
        self.grpFilter.setFlat(False)
        self.grpFilter.setObjectName(_fromUtf8("grpFilter"))
        self.gridLayout = QtGui.QGridLayout(self.grpFilter)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabFilter = QtGui.QTabWidget(self.grpFilter)
        self.tabFilter.setTabPosition(QtGui.QTabWidget.North)
        self.tabFilter.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabFind = QtGui.QWidget()
        self.tabFind.setObjectName(_fromUtf8("tabFind"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabFind)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtFilterPatrName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterPatrName.setEnabled(False)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.gridLayout_2.addWidget(self.edtFilterPatrName, 5, 0, 1, 3)
        self.edtFilterBegBirthDay = CDateEdit(self.tabFind)
        self.edtFilterBegBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBegBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBegBirthDay.setCalendarPopup(True)
        self.edtFilterBegBirthDay.setObjectName(_fromUtf8("edtFilterBegBirthDay"))
        self.gridLayout_2.addWidget(self.edtFilterBegBirthDay, 6, 1, 1, 2)
        self.edtFilterLastName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterLastName.setEnabled(False)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.gridLayout_2.addWidget(self.edtFilterLastName, 1, 0, 1, 3)
        self.chkFilterFirstName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.gridLayout_2.addWidget(self.chkFilterFirstName, 2, 0, 1, 3)
        self.edtFilterFirstName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterFirstName.setEnabled(False)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.gridLayout_2.addWidget(self.edtFilterFirstName, 3, 0, 1, 3)
        self.chkFilterPatrName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.gridLayout_2.addWidget(self.chkFilterPatrName, 4, 0, 1, 3)
        self.chkFilterExternalUserRole = QtGui.QCheckBox(self.tabFind)
        self.chkFilterExternalUserRole.setObjectName(_fromUtf8("chkFilterExternalUserRole"))
        self.gridLayout_2.addWidget(self.chkFilterExternalUserRole, 21, 0, 1, 3)
        self.edtFilterExternalUserName = QtGui.QLineEdit(self.tabFind)
        self.edtFilterExternalUserName.setEnabled(False)
        self.edtFilterExternalUserName.setObjectName(_fromUtf8("edtFilterExternalUserName"))
        self.gridLayout_2.addWidget(self.edtFilterExternalUserName, 24, 0, 1, 3)
        self.cmbFilterProcessed = QtGui.QComboBox(self.tabFind)
        self.cmbFilterProcessed.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterProcessed.sizePolicy().hasHeightForWidth())
        self.cmbFilterProcessed.setSizePolicy(sizePolicy)
        self.cmbFilterProcessed.setObjectName(_fromUtf8("cmbFilterProcessed"))
        self.cmbFilterProcessed.addItem(_fromUtf8(""))
        self.cmbFilterProcessed.addItem(_fromUtf8(""))
        self.cmbFilterProcessed.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterProcessed, 25, 2, 1, 1)
        self.chkFilterBirthDay = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.gridLayout_2.addWidget(self.chkFilterBirthDay, 6, 0, 1, 1)
        self.cmbFilterScheduled = QtGui.QComboBox(self.tabFind)
        self.cmbFilterScheduled.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterScheduled.sizePolicy().hasHeightForWidth())
        self.cmbFilterScheduled.setSizePolicy(sizePolicy)
        self.cmbFilterScheduled.setObjectName(_fromUtf8("cmbFilterScheduled"))
        self.cmbFilterScheduled.addItem(_fromUtf8(""))
        self.cmbFilterScheduled.addItem(_fromUtf8(""))
        self.cmbFilterScheduled.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterScheduled, 27, 2, 1, 1)
        self.chkFilterEndBirthDay = QtGui.QCheckBox(self.tabFind)
        self.chkFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterEndBirthDay.setObjectName(_fromUtf8("chkFilterEndBirthDay"))
        self.gridLayout_2.addWidget(self.chkFilterEndBirthDay, 7, 0, 1, 1)
        self.edtFilterEndBirthDay = CDateEdit(self.tabFind)
        self.edtFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterEndBirthDay.setCalendarPopup(True)
        self.edtFilterEndBirthDay.setObjectName(_fromUtf8("edtFilterEndBirthDay"))
        self.gridLayout_2.addWidget(self.edtFilterEndBirthDay, 7, 1, 1, 2)
        self.chkFilterSex = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.gridLayout_2.addWidget(self.chkFilterSex, 8, 0, 1, 1)
        self.cmbFilterSex = QtGui.QComboBox(self.tabFind)
        self.cmbFilterSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbFilterSex.setSizePolicy(sizePolicy)
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterSex, 8, 1, 1, 2)
        self.chkFilterContact = QtGui.QCheckBox(self.tabFind)
        self.chkFilterContact.setObjectName(_fromUtf8("chkFilterContact"))
        self.gridLayout_2.addWidget(self.chkFilterContact, 9, 0, 1, 1)
        self.edtFilterContact = QtGui.QLineEdit(self.tabFind)
        self.edtFilterContact.setEnabled(False)
        self.edtFilterContact.setObjectName(_fromUtf8("edtFilterContact"))
        self.gridLayout_2.addWidget(self.edtFilterContact, 9, 1, 1, 2)
        self.chkFilterBegDateRange = QtGui.QCheckBox(self.tabFind)
        self.chkFilterBegDateRange.setObjectName(_fromUtf8("chkFilterBegDateRange"))
        self.gridLayout_2.addWidget(self.chkFilterBegDateRange, 10, 0, 1, 3)
        self.edtFilterBegBegDate = CDateEdit(self.tabFind)
        self.edtFilterBegBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBegBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterBegBegDate.setSizePolicy(sizePolicy)
        self.edtFilterBegBegDate.setCalendarPopup(True)
        self.edtFilterBegBegDate.setObjectName(_fromUtf8("edtFilterBegBegDate"))
        self.gridLayout_2.addWidget(self.edtFilterBegBegDate, 11, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 30, 0, 1, 3)
        self.chkFilterOrgStructure = QtGui.QCheckBox(self.tabFind)
        self.chkFilterOrgStructure.setObjectName(_fromUtf8("chkFilterOrgStructure"))
        self.gridLayout_2.addWidget(self.chkFilterOrgStructure, 15, 0, 1, 3)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.tabFind)
        self.cmbFilterOrgStructure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbFilterOrgStructure, 16, 0, 1, 3)
        self.chkFilterSpeciality = QtGui.QCheckBox(self.tabFind)
        self.chkFilterSpeciality.setObjectName(_fromUtf8("chkFilterSpeciality"))
        self.gridLayout_2.addWidget(self.chkFilterSpeciality, 17, 0, 1, 3)
        self.cmbFilterSpeciality = CRBComboBox(self.tabFind)
        self.cmbFilterSpeciality.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbFilterSpeciality.setSizePolicy(sizePolicy)
        self.cmbFilterSpeciality.setObjectName(_fromUtf8("cmbFilterSpeciality"))
        self.gridLayout_2.addWidget(self.cmbFilterSpeciality, 18, 0, 1, 3)
        self.chkFilterPerson = QtGui.QCheckBox(self.tabFind)
        self.chkFilterPerson.setObjectName(_fromUtf8("chkFilterPerson"))
        self.gridLayout_2.addWidget(self.chkFilterPerson, 19, 0, 1, 3)
        self.cmbFilterPerson = CPersonComboBoxEx(self.tabFind)
        self.cmbFilterPerson.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPerson.sizePolicy().hasHeightForWidth())
        self.cmbFilterPerson.setSizePolicy(sizePolicy)
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.gridLayout_2.addWidget(self.cmbFilterPerson, 20, 0, 1, 3)
        self.edtFilterExternalUserRole = QtGui.QLineEdit(self.tabFind)
        self.edtFilterExternalUserRole.setEnabled(False)
        self.edtFilterExternalUserRole.setObjectName(_fromUtf8("edtFilterExternalUserRole"))
        self.gridLayout_2.addWidget(self.edtFilterExternalUserRole, 22, 0, 1, 3)
        self.chkFilterExternalUserName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterExternalUserName.setObjectName(_fromUtf8("chkFilterExternalUserName"))
        self.gridLayout_2.addWidget(self.chkFilterExternalUserName, 23, 0, 1, 3)
        self.lblFilterProcessed = QtGui.QLabel(self.tabFind)
        self.lblFilterProcessed.setObjectName(_fromUtf8("lblFilterProcessed"))
        self.gridLayout_2.addWidget(self.lblFilterProcessed, 25, 0, 1, 1)
        self.lblFilterScheduled = QtGui.QLabel(self.tabFind)
        self.lblFilterScheduled.setObjectName(_fromUtf8("lblFilterScheduled"))
        self.gridLayout_2.addWidget(self.lblFilterScheduled, 27, 0, 1, 1)
        self.chkFilterLastName = QtGui.QCheckBox(self.tabFind)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.gridLayout_2.addWidget(self.chkFilterLastName, 0, 0, 1, 3)
        self.cmbFilterNotification = QtGui.QComboBox(self.tabFind)
        self.cmbFilterNotification.setObjectName(_fromUtf8("cmbFilterNotification"))
        self.cmbFilterNotification.addItem(_fromUtf8(""))
        self.cmbFilterNotification.addItem(_fromUtf8(""))
        self.cmbFilterNotification.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterNotification, 26, 2, 1, 1)
        self.lblFilterNotification = QtGui.QLabel(self.tabFind)
        self.lblFilterNotification.setObjectName(_fromUtf8("lblFilterNotification"))
        self.gridLayout_2.addWidget(self.lblFilterNotification, 26, 0, 1, 1)
        self.chkFilterNote = QtGui.QCheckBox(self.tabFind)
        self.chkFilterNote.setObjectName(_fromUtf8("chkFilterNote"))
        self.gridLayout_2.addWidget(self.chkFilterNote, 28, 0, 1, 3)
        self.edtFilterNote = QtGui.QLineEdit(self.tabFind)
        self.edtFilterNote.setEnabled(False)
        self.edtFilterNote.setObjectName(_fromUtf8("edtFilterNote"))
        self.gridLayout_2.addWidget(self.edtFilterNote, 29, 0, 1, 3)
        self.edtFilterEndBegDate = CDateEdit(self.tabFind)
        self.edtFilterEndBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterEndBegDate.setSizePolicy(sizePolicy)
        self.edtFilterEndBegDate.setCalendarPopup(True)
        self.edtFilterEndBegDate.setObjectName(_fromUtf8("edtFilterEndBegDate"))
        self.gridLayout_2.addWidget(self.edtFilterEndBegDate, 11, 1, 1, 2)
        self.chkFilterEndDateRange = QtGui.QCheckBox(self.tabFind)
        self.chkFilterEndDateRange.setObjectName(_fromUtf8("chkFilterEndDateRange"))
        self.gridLayout_2.addWidget(self.chkFilterEndDateRange, 12, 0, 1, 3)
        self.edtFilterBegEndDate = CDateEdit(self.tabFind)
        self.edtFilterBegEndDate.setEnabled(False)
        self.edtFilterBegEndDate.setCalendarPopup(True)
        self.edtFilterBegEndDate.setObjectName(_fromUtf8("edtFilterBegEndDate"))
        self.gridLayout_2.addWidget(self.edtFilterBegEndDate, 13, 0, 1, 1)
        self.edtFilterEndEndDate = CDateEdit(self.tabFind)
        self.edtFilterEndEndDate.setEnabled(False)
        self.edtFilterEndEndDate.setCalendarPopup(True)
        self.edtFilterEndEndDate.setObjectName(_fromUtf8("edtFilterEndEndDate"))
        self.gridLayout_2.addWidget(self.edtFilterEndEndDate, 13, 2, 1, 1)
        self.edtFilterLastName.raise_()
        self.cmbFilterPerson.raise_()
        self.chkFilterSex.raise_()
        self.cmbFilterSex.raise_()
        self.chkFilterContact.raise_()
        self.chkFilterPerson.raise_()
        self.chkFilterPatrName.raise_()
        self.edtFilterPatrName.raise_()
        self.edtFilterContact.raise_()
        self.edtFilterBegBirthDay.raise_()
        self.chkFilterFirstName.raise_()
        self.edtFilterFirstName.raise_()
        self.chkFilterEndBirthDay.raise_()
        self.chkFilterLastName.raise_()
        self.chkFilterBirthDay.raise_()
        self.cmbFilterProcessed.raise_()
        self.cmbFilterScheduled.raise_()
        self.edtFilterEndBirthDay.raise_()
        self.chkFilterBegDateRange.raise_()
        self.edtFilterBegBegDate.raise_()
        self.edtFilterEndBegDate.raise_()
        self.chkFilterOrgStructure.raise_()
        self.cmbFilterOrgStructure.raise_()
        self.chkFilterSpeciality.raise_()
        self.cmbFilterSpeciality.raise_()
        self.chkFilterExternalUserRole.raise_()
        self.edtFilterExternalUserRole.raise_()
        self.chkFilterExternalUserName.raise_()
        self.edtFilterExternalUserName.raise_()
        self.lblFilterProcessed.raise_()
        self.lblFilterScheduled.raise_()
        self.cmbFilterNotification.raise_()
        self.lblFilterNotification.raise_()
        self.chkFilterNote.raise_()
        self.edtFilterNote.raise_()
        self.chkFilterEndDateRange.raise_()
        self.edtFilterBegEndDate.raise_()
        self.edtFilterEndEndDate.raise_()
        self.tabFilter.addTab(self.tabFind, _fromUtf8(""))
        self.tabFindEx = QtGui.QWidget()
        self.tabFindEx.setObjectName(_fromUtf8("tabFindEx"))
        self.gridLayout_27 = QtGui.QGridLayout(self.tabFindEx)
        self.gridLayout_27.setMargin(1)
        self.gridLayout_27.setSpacing(1)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.edtFilterExEndCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterExEndCreateDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExEndCreateDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExEndCreateDate.setSizePolicy(sizePolicy)
        self.edtFilterExEndCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExEndCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExEndCreateDate.setCalendarPopup(True)
        self.edtFilterExEndCreateDate.setObjectName(_fromUtf8("edtFilterExEndCreateDate"))
        self.gridLayout_27.addWidget(self.edtFilterExEndCreateDate, 3, 1, 1, 1)
        self.edtFilterExBegCreateDate = CDateEdit(self.tabFindEx)
        self.edtFilterExBegCreateDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExBegCreateDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExBegCreateDate.setSizePolicy(sizePolicy)
        self.edtFilterExBegCreateDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExBegCreateDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExBegCreateDate.setCalendarPopup(True)
        self.edtFilterExBegCreateDate.setObjectName(_fromUtf8("edtFilterExBegCreateDate"))
        self.gridLayout_27.addWidget(self.edtFilterExBegCreateDate, 3, 0, 1, 1)
        self.edtFilterExEndModifyDate = CDateEdit(self.tabFindEx)
        self.edtFilterExEndModifyDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExEndModifyDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExEndModifyDate.setSizePolicy(sizePolicy)
        self.edtFilterExEndModifyDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExEndModifyDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExEndModifyDate.setCalendarPopup(True)
        self.edtFilterExEndModifyDate.setObjectName(_fromUtf8("edtFilterExEndModifyDate"))
        self.gridLayout_27.addWidget(self.edtFilterExEndModifyDate, 7, 1, 1, 1)
        self.edtFilterExBegModifyDate = CDateEdit(self.tabFindEx)
        self.edtFilterExBegModifyDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterExBegModifyDate.sizePolicy().hasHeightForWidth())
        self.edtFilterExBegModifyDate.setSizePolicy(sizePolicy)
        self.edtFilterExBegModifyDate.setMinimumSize(QtCore.QSize(0, 0))
        self.edtFilterExBegModifyDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtFilterExBegModifyDate.setCalendarPopup(True)
        self.edtFilterExBegModifyDate.setObjectName(_fromUtf8("edtFilterExBegModifyDate"))
        self.gridLayout_27.addWidget(self.edtFilterExBegModifyDate, 7, 0, 1, 1)
        self.cmbFilterExCreatePerson = CPersonComboBoxEx(self.tabFindEx)
        self.cmbFilterExCreatePerson.setEnabled(False)
        self.cmbFilterExCreatePerson.setObjectName(_fromUtf8("cmbFilterExCreatePerson"))
        self.gridLayout_27.addWidget(self.cmbFilterExCreatePerson, 1, 0, 1, 3)
        self.chkFilterExCreatePerson = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterExCreatePerson.setObjectName(_fromUtf8("chkFilterExCreatePerson"))
        self.gridLayout_27.addWidget(self.chkFilterExCreatePerson, 0, 0, 1, 3)
        self.chkFilterExCreateDate = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterExCreateDate.setObjectName(_fromUtf8("chkFilterExCreateDate"))
        self.gridLayout_27.addWidget(self.chkFilterExCreateDate, 2, 0, 1, 3)
        self.chkFilterExModifyPerson = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterExModifyPerson.setObjectName(_fromUtf8("chkFilterExModifyPerson"))
        self.gridLayout_27.addWidget(self.chkFilterExModifyPerson, 4, 0, 1, 3)
        self.cmbFilterExModifyPerson = CPersonComboBoxEx(self.tabFindEx)
        self.cmbFilterExModifyPerson.setEnabled(False)
        self.cmbFilterExModifyPerson.setObjectName(_fromUtf8("cmbFilterExModifyPerson"))
        self.gridLayout_27.addWidget(self.cmbFilterExModifyPerson, 5, 0, 1, 3)
        self.chkFilterExModifyDate = QtGui.QCheckBox(self.tabFindEx)
        self.chkFilterExModifyDate.setObjectName(_fromUtf8("chkFilterExModifyDate"))
        self.gridLayout_27.addWidget(self.chkFilterExModifyDate, 6, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(84, 181, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem1, 9, 0, 1, 3)
        self.tabFilter.addTab(self.tabFindEx, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabFilter, 0, 0, 1, 1)
        self.buttonBoxFilter = CApplyResetDialogButtonBox(self.grpFilter)
        self.buttonBoxFilter.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxFilter.setObjectName(_fromUtf8("buttonBoxFilter"))
        self.gridLayout.addWidget(self.buttonBoxFilter, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grpFilter, 0, 3, 2, 1)
        self.btnFindAppointments = QtGui.QPushButton(SuspenedAppointmentWindow)
        self.btnFindAppointments.setObjectName(_fromUtf8("btnFindAppointments"))
        self.gridLayout_3.addWidget(self.btnFindAppointments, 1, 0, 1, 1)
        self.btnPrint = CPrintButton(SuspenedAppointmentWindow)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_3.addWidget(self.btnPrint, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(216, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.lblFilterProcessed.setBuddy(self.cmbFilterProcessed)
        self.lblFilterScheduled.setBuddy(self.cmbFilterScheduled)
        self.lblFilterNotification.setBuddy(self.cmbFilterNotification)

        self.retranslateUi(SuspenedAppointmentWindow)
        self.tabBeforeRecord.setCurrentIndex(0)
        self.tabFilter.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkFilterLastName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterLastName.setEnabled)
        QtCore.QObject.connect(self.chkFilterFirstName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterFirstName.setEnabled)
        QtCore.QObject.connect(self.chkFilterPatrName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterPatrName.setEnabled)
        QtCore.QObject.connect(self.chkFilterBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterBegBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFilterEndBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterEndBirthDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEndBirthDay.setEnabled)
        QtCore.QObject.connect(self.chkFilterSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterSex.setEnabled)
        QtCore.QObject.connect(self.chkFilterContact, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterContact.setEnabled)
        QtCore.QObject.connect(self.chkFilterBegDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterBegBegDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterBegDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEndBegDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkFilterSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkFilterPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterPerson.setEnabled)
        QtCore.QObject.connect(self.chkFilterExternalUserRole, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExternalUserRole.setEnabled)
        QtCore.QObject.connect(self.chkFilterExternalUserName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExternalUserName.setEnabled)
        QtCore.QObject.connect(self.chkFilterExCreatePerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterExCreatePerson.setEnabled)
        QtCore.QObject.connect(self.chkFilterExCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExBegCreateDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterExCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExEndCreateDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterExModifyPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterExModifyPerson.setEnabled)
        QtCore.QObject.connect(self.chkFilterExModifyDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExBegModifyDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterExModifyDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterExEndModifyDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterNote, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterNote.setEnabled)
        QtCore.QObject.connect(self.chkFilterEndDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterBegEndDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterEndDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEndEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SuspenedAppointmentWindow)
        SuspenedAppointmentWindow.setTabOrder(self.txtClientInfoBrowser, self.tblSuspendedAppointments)
        SuspenedAppointmentWindow.setTabOrder(self.tblSuspendedAppointments, self.tabBeforeRecord)
        SuspenedAppointmentWindow.setTabOrder(self.tabBeforeRecord, self.tblSchedules)
        SuspenedAppointmentWindow.setTabOrder(self.tblSchedules, self.tblVisitsBySchedules)
        SuspenedAppointmentWindow.setTabOrder(self.tblVisitsBySchedules, self.tabFilter)
        SuspenedAppointmentWindow.setTabOrder(self.tabFilter, self.chkFilterLastName)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterPatrName, self.chkFilterBirthDay)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterBirthDay, self.edtFilterBegBirthDay)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterBegBirthDay, self.chkFilterEndBirthDay)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterEndBirthDay, self.edtFilterEndBirthDay)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterEndBirthDay, self.chkFilterSex)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterSex, self.cmbFilterSex)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterSex, self.chkFilterContact)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterContact, self.edtFilterContact)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterContact, self.chkFilterBegDateRange)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterBegDateRange, self.edtFilterBegBegDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterBegBegDate, self.edtFilterEndBegDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterEndBegDate, self.chkFilterEndDateRange)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterEndDateRange, self.edtFilterEndEndDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterEndEndDate, self.edtFilterBegEndDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterBegEndDate, self.chkFilterOrgStructure)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterOrgStructure, self.cmbFilterOrgStructure)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterOrgStructure, self.chkFilterSpeciality)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterSpeciality, self.cmbFilterSpeciality)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterSpeciality, self.chkFilterPerson)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterPerson, self.cmbFilterPerson)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterPerson, self.chkFilterExternalUserRole)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExternalUserRole, self.edtFilterExternalUserRole)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExternalUserRole, self.chkFilterExternalUserName)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExternalUserName, self.edtFilterExternalUserName)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExternalUserName, self.cmbFilterProcessed)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterProcessed, self.cmbFilterNotification)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterNotification, self.cmbFilterScheduled)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterScheduled, self.chkFilterNote)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterNote, self.edtFilterNote)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterNote, self.chkFilterExCreateDate)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExCreateDate, self.edtFilterExBegCreateDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExBegCreateDate, self.edtFilterExEndCreateDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExEndCreateDate, self.chkFilterExModifyPerson)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExModifyPerson, self.cmbFilterExModifyPerson)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterExModifyPerson, self.chkFilterExModifyDate)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExModifyDate, self.edtFilterExBegModifyDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExBegModifyDate, self.edtFilterExEndModifyDate)
        SuspenedAppointmentWindow.setTabOrder(self.edtFilterExEndModifyDate, self.buttonBoxFilter)
        SuspenedAppointmentWindow.setTabOrder(self.buttonBoxFilter, self.chkFilterExCreatePerson)
        SuspenedAppointmentWindow.setTabOrder(self.chkFilterExCreatePerson, self.cmbFilterExCreatePerson)
        SuspenedAppointmentWindow.setTabOrder(self.cmbFilterExCreatePerson, self.btnFindAppointments)
        SuspenedAppointmentWindow.setTabOrder(self.btnFindAppointments, self.btnPrint)

    def retranslateUi(self, SuspenedAppointmentWindow):
        SuspenedAppointmentWindow.setWindowTitle(_translate("SuspenedAppointmentWindow", "Журнал отложенной записи", None))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabBeforeRecordClient), _translate("SuspenedAppointmentWindow", "Предварительная запись", None))
        self.tabBeforeRecord.setTabText(self.tabBeforeRecord.indexOf(self.tabVisitBeforeRecordClient), _translate("SuspenedAppointmentWindow", "Выполнение записи", None))
        self.lblRecordCount.setText(_translate("SuspenedAppointmentWindow", "Список пуст", None))
        self.grpFilter.setTitle(_translate("SuspenedAppointmentWindow", "Фильтр", None))
        self.chkFilterFirstName.setText(_translate("SuspenedAppointmentWindow", "Имя", None))
        self.chkFilterPatrName.setText(_translate("SuspenedAppointmentWindow", "Отчество", None))
        self.chkFilterExternalUserRole.setText(_translate("SuspenedAppointmentWindow", "Роль внешнего пользователя", None))
        self.cmbFilterProcessed.setItemText(0, _translate("SuspenedAppointmentWindow", "Все", None))
        self.cmbFilterProcessed.setItemText(1, _translate("SuspenedAppointmentWindow", "Неотработанные", None))
        self.cmbFilterProcessed.setItemText(2, _translate("SuspenedAppointmentWindow", "Отработанные", None))
        self.chkFilterBirthDay.setText(_translate("SuspenedAppointmentWindow", "Дата рожд", None))
        self.cmbFilterScheduled.setItemText(0, _translate("SuspenedAppointmentWindow", "-", None))
        self.cmbFilterScheduled.setItemText(1, _translate("SuspenedAppointmentWindow", "Не произведена", None))
        self.cmbFilterScheduled.setItemText(2, _translate("SuspenedAppointmentWindow", "Произведена", None))
        self.chkFilterEndBirthDay.setText(_translate("SuspenedAppointmentWindow", "по", None))
        self.chkFilterSex.setText(_translate("SuspenedAppointmentWindow", "Пол", None))
        self.cmbFilterSex.setItemText(1, _translate("SuspenedAppointmentWindow", "М", None))
        self.cmbFilterSex.setItemText(2, _translate("SuspenedAppointmentWindow", "Ж", None))
        self.chkFilterContact.setText(_translate("SuspenedAppointmentWindow", "Контакт", None))
        self.chkFilterBegDateRange.setText(_translate("SuspenedAppointmentWindow", "Дата начала периода визита", None))
        self.edtFilterBegBegDate.setDisplayFormat(_translate("SuspenedAppointmentWindow", "dd.MM.yyyy", None))
        self.chkFilterOrgStructure.setText(_translate("SuspenedAppointmentWindow", "Подразделение ", None))
        self.chkFilterSpeciality.setText(_translate("SuspenedAppointmentWindow", "Специальность", None))
        self.chkFilterPerson.setText(_translate("SuspenedAppointmentWindow", "Врач", None))
        self.chkFilterExternalUserName.setText(_translate("SuspenedAppointmentWindow", "Внешний пользователь", None))
        self.lblFilterProcessed.setText(_translate("SuspenedAppointmentWindow", "Отображать", None))
        self.lblFilterScheduled.setText(_translate("SuspenedAppointmentWindow", "Запись", None))
        self.chkFilterLastName.setText(_translate("SuspenedAppointmentWindow", "Фамилия", None))
        self.cmbFilterNotification.setItemText(0, _translate("SuspenedAppointmentWindow", "-", None))
        self.cmbFilterNotification.setItemText(1, _translate("SuspenedAppointmentWindow", "Нет", None))
        self.cmbFilterNotification.setItemText(2, _translate("SuspenedAppointmentWindow", "Произведено", None))
        self.lblFilterNotification.setText(_translate("SuspenedAppointmentWindow", "Оповещение", None))
        self.chkFilterNote.setText(_translate("SuspenedAppointmentWindow", "Примечание", None))
        self.edtFilterEndBegDate.setDisplayFormat(_translate("SuspenedAppointmentWindow", "dd.MM.yyyy", None))
        self.chkFilterEndDateRange.setText(_translate("SuspenedAppointmentWindow", "Дата окончания периода визита", None))
        self.edtFilterBegEndDate.setDisplayFormat(_translate("SuspenedAppointmentWindow", "dd.MM.yyyy", None))
        self.edtFilterEndEndDate.setDisplayFormat(_translate("SuspenedAppointmentWindow", "dd.MM.yyyy", None))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFind), _translate("SuspenedAppointmentWindow", "&Поиск", None))
        self.chkFilterExCreatePerson.setText(_translate("SuspenedAppointmentWindow", "Автор", None))
        self.chkFilterExCreateDate.setText(_translate("SuspenedAppointmentWindow", "Дата создания", None))
        self.chkFilterExModifyPerson.setText(_translate("SuspenedAppointmentWindow", "Автор последнего изменения", None))
        self.chkFilterExModifyDate.setText(_translate("SuspenedAppointmentWindow", "Дата последнего изменения", None))
        self.tabFilter.setTabText(self.tabFilter.indexOf(self.tabFindEx), _translate("SuspenedAppointmentWindow", "&Расширенный поиск", None))
        self.btnFindAppointments.setText(_translate("SuspenedAppointmentWindow", "Отработка", None))
        self.btnPrint.setText(_translate("SuspenedAppointmentWindow", "Печать (F6)", None))
        self.btnPrint.setShortcut(_translate("SuspenedAppointmentWindow", "F6", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.RegistryTable import CSchedulesTableView
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.PrintTemplates import CPrintButton
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
