# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client_eln\appendix\fsselnv2\localPreferences\appPreferencesDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_appPreferencesDialog(object):
    def setupUi(self, appPreferencesDialog):
        appPreferencesDialog.setObjectName(_fromUtf8("appPreferencesDialog"))
        appPreferencesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        appPreferencesDialog.resize(496, 494)
        appPreferencesDialog.setAutoFillBackground(False)
        appPreferencesDialog.setSizeGripEnabled(False)
        appPreferencesDialog.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(appPreferencesDialog)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(appPreferencesDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblOrganisation = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisation.sizePolicy().hasHeightForWidth())
        self.lblOrganisation.setSizePolicy(sizePolicy)
        self.lblOrganisation.setMinimumSize(QtCore.QSize(130, 0))
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout_2.addWidget(self.lblOrganisation, 0, 0, 1, 1)
        self.cmbOrganisation = CPolyclinicComboBox(self.tabMain)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout_2.addWidget(self.cmbOrganisation, 0, 1, 1, 2)
        self.btnSelectOrganisation = QtGui.QToolButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout_2.addWidget(self.btnSelectOrganisation, 0, 3, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_2.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.tabMain)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbOrgStructure, 1, 1, 1, 3)
        self.lblRequestedNumbersQuantity = QtGui.QLabel(self.tabMain)
        self.lblRequestedNumbersQuantity.setObjectName(_fromUtf8("lblRequestedNumbersQuantity"))
        self.gridLayout_2.addWidget(self.lblRequestedNumbersQuantity, 2, 0, 1, 1)
        self.edtRequestedNumbersQuantity = QtGui.QSpinBox(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRequestedNumbersQuantity.sizePolicy().hasHeightForWidth())
        self.edtRequestedNumbersQuantity.setSizePolicy(sizePolicy)
        self.edtRequestedNumbersQuantity.setMinimum(1)
        self.edtRequestedNumbersQuantity.setMaximum(1000)
        self.edtRequestedNumbersQuantity.setProperty("value", 5)
        self.edtRequestedNumbersQuantity.setObjectName(_fromUtf8("edtRequestedNumbersQuantity"))
        self.gridLayout_2.addWidget(self.edtRequestedNumbersQuantity, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(61, 174, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabCryptography = QtGui.QWidget()
        self.tabCryptography.setObjectName(_fromUtf8("tabCryptography"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCryptography)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rbnOwnPK = QtGui.QRadioButton(self.tabCryptography)
        self.rbnOwnPK.setChecked(True)
        self.rbnOwnPK.setObjectName(_fromUtf8("rbnOwnPK"))
        self.gridLayout_3.addWidget(self.rbnOwnPK, 1, 0, 1, 1)
        self.cmbCsp = QtGui.QComboBox(self.tabCryptography)
        self.cmbCsp.setObjectName(_fromUtf8("cmbCsp"))
        self.gridLayout_3.addWidget(self.cmbCsp, 0, 1, 1, 2)
        self.lblCsp = QtGui.QLabel(self.tabCryptography)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCsp.sizePolicy().hasHeightForWidth())
        self.lblCsp.setSizePolicy(sizePolicy)
        self.lblCsp.setMinimumSize(QtCore.QSize(130, 0))
        self.lblCsp.setObjectName(_fromUtf8("lblCsp"))
        self.gridLayout_3.addWidget(self.lblCsp, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.rbnCustomPK = QtGui.QRadioButton(self.tabCryptography)
        self.rbnCustomPK.setObjectName(_fromUtf8("rbnCustomPK"))
        self.gridLayout_3.addWidget(self.rbnCustomPK, 2, 0, 1, 1)
        self.cmbUserCert = CCertComboBox(self.tabCryptography)
        self.cmbUserCert.setObjectName(_fromUtf8("cmbUserCert"))
        self.gridLayout_3.addWidget(self.cmbUserCert, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tabCryptography, _fromUtf8(""))
        self.tabFss = QtGui.QWidget()
        self.tabFss.setObjectName(_fromUtf8("tabFss"))
        self.gridLayout = QtGui.QGridLayout(self.tabFss)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtProxyAddress = QtGui.QLineEdit(self.tabFss)
        self.edtProxyAddress.setEnabled(False)
        self.edtProxyAddress.setObjectName(_fromUtf8("edtProxyAddress"))
        self.gridLayout.addWidget(self.edtProxyAddress, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        self.lblServiceUrl = QtGui.QLabel(self.tabFss)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServiceUrl.sizePolicy().hasHeightForWidth())
        self.lblServiceUrl.setSizePolicy(sizePolicy)
        self.lblServiceUrl.setMinimumSize(QtCore.QSize(130, 0))
        self.lblServiceUrl.setObjectName(_fromUtf8("lblServiceUrl"))
        self.gridLayout.addWidget(self.lblServiceUrl, 0, 0, 1, 1)
        self.lblFssCert = QtGui.QLabel(self.tabFss)
        self.lblFssCert.setEnabled(False)
        self.lblFssCert.setObjectName(_fromUtf8("lblFssCert"))
        self.gridLayout.addWidget(self.lblFssCert, 2, 0, 1, 1)
        self.edtProxyLogin = QtGui.QLineEdit(self.tabFss)
        self.edtProxyLogin.setEnabled(False)
        self.edtProxyLogin.setObjectName(_fromUtf8("edtProxyLogin"))
        self.gridLayout.addWidget(self.edtProxyLogin, 6, 1, 1, 1)
        self.lblProxyPort = QtGui.QLabel(self.tabFss)
        self.lblProxyPort.setEnabled(False)
        self.lblProxyPort.setObjectName(_fromUtf8("lblProxyPort"))
        self.gridLayout.addWidget(self.lblProxyPort, 4, 3, 1, 1)
        self.cmbFssCert = CCertComboBox(self.tabFss)
        self.cmbFssCert.setEnabled(False)
        self.cmbFssCert.setObjectName(_fromUtf8("cmbFssCert"))
        self.gridLayout.addWidget(self.cmbFssCert, 2, 1, 1, 4)
        self.edtServiceUrl = QtGui.QLineEdit(self.tabFss)
        self.edtServiceUrl.setObjectName(_fromUtf8("edtServiceUrl"))
        self.gridLayout.addWidget(self.edtServiceUrl, 0, 1, 1, 4)
        self.chkUseEncryption = QtGui.QCheckBox(self.tabFss)
        self.chkUseEncryption.setObjectName(_fromUtf8("chkUseEncryption"))
        self.gridLayout.addWidget(self.chkUseEncryption, 1, 0, 1, 5)
        self.chkUseProxy = QtGui.QCheckBox(self.tabFss)
        self.chkUseProxy.setObjectName(_fromUtf8("chkUseProxy"))
        self.gridLayout.addWidget(self.chkUseProxy, 3, 0, 1, 5)
        self.lblProxyAddress = QtGui.QLabel(self.tabFss)
        self.lblProxyAddress.setEnabled(False)
        self.lblProxyAddress.setObjectName(_fromUtf8("lblProxyAddress"))
        self.gridLayout.addWidget(self.lblProxyAddress, 4, 0, 1, 1)
        self.edtProxyPort = QtGui.QSpinBox(self.tabFss)
        self.edtProxyPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtProxyPort.sizePolicy().hasHeightForWidth())
        self.edtProxyPort.setSizePolicy(sizePolicy)
        self.edtProxyPort.setMinimum(0)
        self.edtProxyPort.setMaximum(65535)
        self.edtProxyPort.setProperty("value", 3128)
        self.edtProxyPort.setObjectName(_fromUtf8("edtProxyPort"))
        self.gridLayout.addWidget(self.edtProxyPort, 4, 4, 1, 1)
        self.chkProxyUseAuth = QtGui.QCheckBox(self.tabFss)
        self.chkProxyUseAuth.setEnabled(False)
        self.chkProxyUseAuth.setObjectName(_fromUtf8("chkProxyUseAuth"))
        self.gridLayout.addWidget(self.chkProxyUseAuth, 5, 0, 1, 5)
        self.lblProxyLogin = QtGui.QLabel(self.tabFss)
        self.lblProxyLogin.setEnabled(False)
        self.lblProxyLogin.setObjectName(_fromUtf8("lblProxyLogin"))
        self.gridLayout.addWidget(self.lblProxyLogin, 6, 0, 1, 1)
        self.lblProxyPassword = QtGui.QLabel(self.tabFss)
        self.lblProxyPassword.setEnabled(False)
        self.lblProxyPassword.setObjectName(_fromUtf8("lblProxyPassword"))
        self.gridLayout.addWidget(self.lblProxyPassword, 6, 3, 1, 1)
        self.edtProxyPassword = QtGui.QLineEdit(self.tabFss)
        self.edtProxyPassword.setEnabled(False)
        self.edtProxyPassword.setObjectName(_fromUtf8("edtProxyPassword"))
        self.gridLayout.addWidget(self.edtProxyPassword, 6, 4, 1, 1)
        self.tabWidget.addTab(self.tabFss, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(appPreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblRequestedNumbersQuantity.setBuddy(self.edtRequestedNumbersQuantity)
        self.lblCsp.setBuddy(self.cmbCsp)
        self.lblServiceUrl.setBuddy(self.edtServiceUrl)
        self.lblFssCert.setBuddy(self.cmbFssCert)
        self.lblProxyPort.setBuddy(self.edtProxyPort)
        self.lblProxyAddress.setBuddy(self.edtProxyAddress)
        self.lblProxyLogin.setBuddy(self.edtProxyLogin)
        self.lblProxyPassword.setBuddy(self.edtProxyPassword)

        self.retranslateUi(appPreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), appPreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), appPreferencesDialog.reject)
        QtCore.QObject.connect(self.chkUseEncryption, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFssCert.setEnabled)
        QtCore.QObject.connect(self.chkUseEncryption, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblFssCert.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(appPreferencesDialog)
        appPreferencesDialog.setTabOrder(self.tabWidget, self.cmbOrganisation)
        appPreferencesDialog.setTabOrder(self.cmbOrganisation, self.btnSelectOrganisation)
        appPreferencesDialog.setTabOrder(self.btnSelectOrganisation, self.cmbOrgStructure)
        appPreferencesDialog.setTabOrder(self.cmbOrgStructure, self.edtRequestedNumbersQuantity)
        appPreferencesDialog.setTabOrder(self.edtRequestedNumbersQuantity, self.cmbCsp)
        appPreferencesDialog.setTabOrder(self.cmbCsp, self.rbnOwnPK)
        appPreferencesDialog.setTabOrder(self.rbnOwnPK, self.rbnCustomPK)
        appPreferencesDialog.setTabOrder(self.rbnCustomPK, self.cmbUserCert)
        appPreferencesDialog.setTabOrder(self.cmbUserCert, self.edtServiceUrl)
        appPreferencesDialog.setTabOrder(self.edtServiceUrl, self.chkUseEncryption)
        appPreferencesDialog.setTabOrder(self.chkUseEncryption, self.cmbFssCert)
        appPreferencesDialog.setTabOrder(self.cmbFssCert, self.chkUseProxy)
        appPreferencesDialog.setTabOrder(self.chkUseProxy, self.edtProxyAddress)
        appPreferencesDialog.setTabOrder(self.edtProxyAddress, self.edtProxyPort)
        appPreferencesDialog.setTabOrder(self.edtProxyPort, self.chkProxyUseAuth)
        appPreferencesDialog.setTabOrder(self.chkProxyUseAuth, self.edtProxyLogin)
        appPreferencesDialog.setTabOrder(self.edtProxyLogin, self.edtProxyPassword)
        appPreferencesDialog.setTabOrder(self.edtProxyPassword, self.buttonBox)

    def retranslateUi(self, appPreferencesDialog):
        appPreferencesDialog.setWindowTitle(_translate("appPreferencesDialog", "Умолчания", None))
        self.lblOrganisation.setText(_translate("appPreferencesDialog", "&ЛПУ", None))
        self.btnSelectOrganisation.setText(_translate("appPreferencesDialog", "...", None))
        self.lblOrgStructure.setText(_translate("appPreferencesDialog", "&Подразделение", None))
        self.lblRequestedNumbersQuantity.setText(_translate("appPreferencesDialog", "&Запрашиваемое количество", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("appPreferencesDialog", "&Основные настройки", None))
        self.rbnOwnPK.setText(_translate("appPreferencesDialog", "Ключ по &СНИЛС", None))
        self.lblCsp.setText(_translate("appPreferencesDialog", "Крипто&провайдер", None))
        self.rbnCustomPK.setText(_translate("appPreferencesDialog", "&Произвольный ключ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCryptography), _translate("appPreferencesDialog", "&Криптография", None))
        self.lblServiceUrl.setText(_translate("appPreferencesDialog", "&URL сервиса", None))
        self.lblFssCert.setText(_translate("appPreferencesDialog", "&Сертификат СФР", None))
        self.lblProxyPort.setText(_translate("appPreferencesDialog", "&порт", None))
        self.chkUseEncryption.setText(_translate("appPreferencesDialog", "Использовать &шифрование сообщений", None))
        self.chkUseProxy.setText(_translate("appPreferencesDialog", "Использовать прокси-&сервер", None))
        self.lblProxyAddress.setText(_translate("appPreferencesDialog", "&Адрес сервера", None))
        self.chkProxyUseAuth.setText(_translate("appPreferencesDialog", "Прокси-сервер требует ау&тентификацию", None))
        self.lblProxyLogin.setText(_translate("appPreferencesDialog", "&Имя", None))
        self.lblProxyPassword.setText(_translate("appPreferencesDialog", "па&роль", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFss), _translate("appPreferencesDialog", "Доступ к сервису &СФР", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.CertComboBox import CCertComboBox
