# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/Stock/IncomingInvoice.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IncomingInvoiceDialog(object):
    def setupUi(self, IncomingInvoiceDialog):
        IncomingInvoiceDialog.setObjectName(_fromUtf8("IncomingInvoiceDialog"))
        IncomingInvoiceDialog.resize(559, 500)
        self.gridLayout = QtGui.QGridLayout(IncomingInvoiceDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDate = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 9, 0, 1, 1)
        self.cmbReceiver = CStorageComboBox(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout.addWidget(self.cmbReceiver, 11, 1, 1, 5)
        self.lblReason = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 3, 0, 1, 1)
        self.lblNote = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 13, 0, 1, 1)
        self.lblReceiverPerson = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblReceiverPerson.setObjectName(_fromUtf8("lblReceiverPerson"))
        self.gridLayout.addWidget(self.lblReceiverPerson, 12, 0, 1, 1)
        self.lblSupplierOrg = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSupplierOrg.setObjectName(_fromUtf8("lblSupplierOrg"))
        self.gridLayout.addWidget(self.lblSupplierOrg, 1, 0, 1, 1)
        self.lblReceiver = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReceiver.sizePolicy().hasHeightForWidth())
        self.lblReceiver.setSizePolicy(sizePolicy)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout.addWidget(self.lblReceiver, 11, 0, 1, 1)
        self.lblSupplierOrgPerson = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSupplierOrgPerson.setObjectName(_fromUtf8("lblSupplierOrgPerson"))
        self.gridLayout.addWidget(self.lblSupplierOrgPerson, 2, 0, 1, 1)
        self.lblConfirmationOrder = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblConfirmationOrder.setObjectName(_fromUtf8("lblConfirmationOrder"))
        self.gridLayout.addWidget(self.lblConfirmationOrder, 7, 0, 1, 1)
        self.lblNumber = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.cmbSupplierOrg = COrgComboBox(IncomingInvoiceDialog)
        self.cmbSupplierOrg.setObjectName(_fromUtf8("cmbSupplierOrg"))
        self.gridLayout.addWidget(self.cmbSupplierOrg, 1, 1, 1, 5)
        self.cmbReceiverPerson = CPersonComboBoxEx(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiverPerson.sizePolicy().hasHeightForWidth())
        self.cmbReceiverPerson.setSizePolicy(sizePolicy)
        self.cmbReceiverPerson.setObjectName(_fromUtf8("cmbReceiverPerson"))
        self.gridLayout.addWidget(self.cmbReceiverPerson, 12, 1, 1, 5)
        self.lblSummaryInfo = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout.addWidget(self.lblSummaryInfo, 15, 0, 1, 6)
        self.edtTime = QtGui.QTimeEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 9, 2, 1, 1)
        self.cmbReason = CStockPurchaseContractComboBox(IncomingInvoiceDialog)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridLayout.addWidget(self.cmbReason, 3, 1, 1, 5)
        self.edtNote = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 13, 1, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(IncomingInvoiceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 16, 0, 1, 6)
        self.edtDate = CDateEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 9, 1, 1, 1)
        self.edtDocDate = CDateEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDocDate.sizePolicy().hasHeightForWidth())
        self.edtDocDate.setSizePolicy(sizePolicy)
        self.edtDocDate.setCalendarPopup(True)
        self.edtDocDate.setObjectName(_fromUtf8("edtDocDate"))
        self.gridLayout.addWidget(self.edtDocDate, 0, 5, 1, 1)
        self.tblItems = CInDocTableView(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 14, 0, 1, 6)
        self.lblDocDate = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocDate.sizePolicy().hasHeightForWidth())
        self.lblDocDate.setSizePolicy(sizePolicy)
        self.lblDocDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDocDate.setObjectName(_fromUtf8("lblDocDate"))
        self.gridLayout.addWidget(self.lblDocDate, 0, 4, 1, 1)
        self.edtNumber = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 3)
        self.edtSupplierOrgPerson = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtSupplierOrgPerson.setObjectName(_fromUtf8("edtSupplierOrgPerson"))
        self.gridLayout.addWidget(self.edtSupplierOrgPerson, 2, 1, 1, 3)
        self.cmbConfirmationOrder = QtGui.QComboBox(IncomingInvoiceDialog)
        self.cmbConfirmationOrder.setObjectName(_fromUtf8("cmbConfirmationOrder"))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbConfirmationOrder, 7, 1, 1, 3)
        self.lblFinance = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 4, 0, 1, 1)
        self.cmbFinance = CRBComboBox(IncomingInvoiceDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 4, 1, 1, 3)
        self.lblDate.setBuddy(self.edtDate)
        self.lblReason.setBuddy(self.cmbReason)
        self.lblNote.setBuddy(self.edtNote)
        self.lblReceiverPerson.setBuddy(self.cmbReceiverPerson)
        self.lblSupplierOrg.setBuddy(self.cmbSupplierOrg)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblSupplierOrgPerson.setBuddy(self.edtSupplierOrgPerson)
        self.lblConfirmationOrder.setBuddy(self.cmbConfirmationOrder)
        self.lblNumber.setBuddy(self.edtNumber)
        self.lblDocDate.setBuddy(self.edtDocDate)

        self.retranslateUi(IncomingInvoiceDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), IncomingInvoiceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), IncomingInvoiceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(IncomingInvoiceDialog)
        IncomingInvoiceDialog.setTabOrder(self.edtNumber, self.edtDocDate)
        IncomingInvoiceDialog.setTabOrder(self.edtDocDate, self.cmbSupplierOrg)
        IncomingInvoiceDialog.setTabOrder(self.cmbSupplierOrg, self.edtSupplierOrgPerson)
        IncomingInvoiceDialog.setTabOrder(self.edtSupplierOrgPerson, self.cmbReason)
        IncomingInvoiceDialog.setTabOrder(self.cmbReason, self.cmbFinance)
        IncomingInvoiceDialog.setTabOrder(self.cmbFinance, self.cmbConfirmationOrder)
        IncomingInvoiceDialog.setTabOrder(self.cmbConfirmationOrder, self.edtDate)
        IncomingInvoiceDialog.setTabOrder(self.edtDate, self.edtTime)
        IncomingInvoiceDialog.setTabOrder(self.edtTime, self.cmbReceiver)
        IncomingInvoiceDialog.setTabOrder(self.cmbReceiver, self.cmbReceiverPerson)
        IncomingInvoiceDialog.setTabOrder(self.cmbReceiverPerson, self.edtNote)
        IncomingInvoiceDialog.setTabOrder(self.edtNote, self.tblItems)
        IncomingInvoiceDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, IncomingInvoiceDialog):
        IncomingInvoiceDialog.setWindowTitle(_translate("IncomingInvoiceDialog", "Приходная накладная от внешнего поставщика", None))
        self.lblDate.setText(_translate("IncomingInvoiceDialog", "Дата при&ходования", None))
        self.lblReason.setText(_translate("IncomingInvoiceDialog", "О&снование", None))
        self.lblNote.setText(_translate("IncomingInvoiceDialog", "При&мечания", None))
        self.lblReceiverPerson.setText(_translate("IncomingInvoiceDialog", "О&тветственный", None))
        self.lblSupplierOrg.setText(_translate("IncomingInvoiceDialog", "Внешний &поставщик", None))
        self.lblReceiver.setText(_translate("IncomingInvoiceDialog", "По&лучатель", None))
        self.lblSupplierOrgPerson.setText(_translate("IncomingInvoiceDialog", "&Ответственный", None))
        self.lblConfirmationOrder.setText(_translate("IncomingInvoiceDialog", "По&рядок подтверждения", None))
        self.lblNumber.setText(_translate("IncomingInvoiceDialog", "&Номер", None))
        self.edtTime.setDisplayFormat(_translate("IncomingInvoiceDialog", "HH:mm", None))
        self.lblDocDate.setText(_translate("IncomingInvoiceDialog", "&Дата документа", None))
        self.cmbConfirmationOrder.setItemText(0, _translate("IncomingInvoiceDialog", "-", None))
        self.cmbConfirmationOrder.setItemText(1, _translate("IncomingInvoiceDialog", "Прямой", None))
        self.cmbConfirmationOrder.setItemText(2, _translate("IncomingInvoiceDialog", "Обратный", None))
        self.lblFinance.setText(_translate("IncomingInvoiceDialog", "Тип финансирования", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Stock.StockPurchaseContractComboBox import CStockPurchaseContractComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    IncomingInvoiceDialog = QtGui.QDialog()
    ui = Ui_IncomingInvoiceDialog()
    ui.setupUi(IncomingInvoiceDialog)
    IncomingInvoiceDialog.show()
    sys.exit(app.exec_())

