# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\appendix\regional\r23\fixAccounts\fixAccounts.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(603, 589)
        self.wMain = QtGui.QWidget(MainWindow)
        self.wMain.setObjectName(_fromUtf8("wMain"))
        self.lMain = QtGui.QVBoxLayout(self.wMain)
        self.lMain.setObjectName(_fromUtf8("lMain"))
        self.lTop = QtGui.QHBoxLayout()
        self.lTop.setObjectName(_fromUtf8("lTop"))
        self.lblBeginDate = QtGui.QLabel(self.wMain)
        self.lblBeginDate.setObjectName(_fromUtf8("lblBeginDate"))
        self.lTop.addWidget(self.lblBeginDate)
        self.edtBeginDate = CDateEdit(self.wMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBeginDate.sizePolicy().hasHeightForWidth())
        self.edtBeginDate.setSizePolicy(sizePolicy)
        self.edtBeginDate.setMaximumSize(QtCore.QSize(83, 16777215))
        self.edtBeginDate.setCalendarPopup(True)
        self.edtBeginDate.setObjectName(_fromUtf8("edtBeginDate"))
        self.lTop.addWidget(self.edtBeginDate)
        self.lblEndDate = QtGui.QLabel(self.wMain)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.lTop.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(self.wMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setMaximumSize(QtCore.QSize(83, 16777215))
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.lTop.addWidget(self.edtEndDate)
        self.btnRefresh = QtGui.QPushButton(self.wMain)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.lTop.addWidget(self.btnRefresh)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.lTop.addItem(spacerItem)
        self.btnProcess = QtGui.QPushButton(self.wMain)
        self.btnProcess.setEnabled(True)
        self.btnProcess.setObjectName(_fromUtf8("btnProcess"))
        self.lTop.addWidget(self.btnProcess)
        self.btnCancel = QtGui.QPushButton(self.wMain)
        self.btnCancel.setEnabled(True)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.lTop.addWidget(self.btnCancel)
        self.lMain.addLayout(self.lTop)
        self.spMain = QtGui.QSplitter(self.wMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMain.sizePolicy().hasHeightForWidth())
        self.spMain.setSizePolicy(sizePolicy)
        self.spMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.spMain.setOrientation(QtCore.Qt.Horizontal)
        self.spMain.setObjectName(_fromUtf8("spMain"))
        self.gbLeft = QtGui.QGroupBox(self.spMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbLeft.sizePolicy().hasHeightForWidth())
        self.gbLeft.setSizePolicy(sizePolicy)
        self.gbLeft.setMinimumSize(QtCore.QSize(0, 0))
        self.gbLeft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.gbLeft.setFlat(False)
        self.gbLeft.setCheckable(False)
        self.gbLeft.setObjectName(_fromUtf8("gbLeft"))
        self.lLeft = QtGui.QVBoxLayout(self.gbLeft)
        self.lLeft.setObjectName(_fromUtf8("lLeft"))
        self.lwAccounts = QtGui.QListWidget(self.gbLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwAccounts.sizePolicy().hasHeightForWidth())
        self.lwAccounts.setSizePolicy(sizePolicy)
        self.lwAccounts.setMinimumSize(QtCore.QSize(0, 0))
        self.lwAccounts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lwAccounts.setObjectName(_fromUtf8("lwAccounts"))
        self.lLeft.addWidget(self.lwAccounts)
        self.gbRight = QtGui.QGroupBox(self.spMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbRight.sizePolicy().hasHeightForWidth())
        self.gbRight.setSizePolicy(sizePolicy)
        self.gbRight.setMinimumSize(QtCore.QSize(0, 0))
        self.gbRight.setObjectName(_fromUtf8("gbRight"))
        self.lRight = QtGui.QVBoxLayout(self.gbRight)
        self.lRight.setObjectName(_fromUtf8("lRight"))
        self.tbLog = QtGui.QTextBrowser(self.gbRight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLog.sizePolicy().hasHeightForWidth())
        self.tbLog.setSizePolicy(sizePolicy)
        self.tbLog.setMinimumSize(QtCore.QSize(0, 0))
        self.tbLog.setObjectName(_fromUtf8("tbLog"))
        self.lRight.addWidget(self.tbLog)
        self.lMain.addWidget(self.spMain)
        MainWindow.setCentralWidget(self.wMain)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actLogin = QtGui.QAction(MainWindow)
        self.actLogin.setObjectName(_fromUtf8("actLogin"))
        self.actLogout = QtGui.QAction(MainWindow)
        self.actLogout.setObjectName(_fromUtf8("actLogout"))
        self.actQuit = QtGui.QAction(MainWindow)
        self.actQuit.setObjectName(_fromUtf8("actQuit"))
        self.actConnection = QtGui.QAction(MainWindow)
        self.actConnection.setObjectName(_fromUtf8("actConnection"))
        self.menuFile.addAction(self.actLogin)
        self.menuFile.addAction(self.actLogout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actQuit)
        self.menuPreferences.addAction(self.actConnection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Проверка счетов для Краснодарского края", None))
        self.lblBeginDate.setText(_translate("MainWindow", "С", None))
        self.lblEndDate.setText(_translate("MainWindow", "По", None))
        self.btnRefresh.setText(_translate("MainWindow", "Обновить", None))
        self.btnProcess.setText(_translate("MainWindow", "Обработать", None))
        self.btnCancel.setText(_translate("MainWindow", "Отмена", None))
        self.gbLeft.setTitle(_translate("MainWindow", "Счета", None))
        self.gbRight.setTitle(_translate("MainWindow", "Вывод", None))
        self.menuFile.setTitle(_translate("MainWindow", "Сессия", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Настройки", None))
        self.actLogin.setText(_translate("MainWindow", "Подключиться к базе данных", None))
        self.actLogout.setText(_translate("MainWindow", "Отключиться от базы данных", None))
        self.actQuit.setText(_translate("MainWindow", "Закрыть программу", None))
        self.actConnection.setText(_translate("MainWindow", "База данных", None))

from library.DateEdit import CDateEdit
