# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/ContractCoefficientTestDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ContractCoefficientTestDialog(object):
    def setupUi(self, ContractCoefficientTestDialog):
        ContractCoefficientTestDialog.setObjectName(_fromUtf8("ContractCoefficientTestDialog"))
        ContractCoefficientTestDialog.resize(355, 328)
        self.gridLayout = QtGui.QGridLayout(ContractCoefficientTestDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtDuration = QtGui.QSpinBox(ContractCoefficientTestDialog)
        self.edtDuration.setMaximum(999)
        self.edtDuration.setProperty("value", 12)
        self.edtDuration.setObjectName(_fromUtf8("edtDuration"))
        self.gridLayout.addWidget(self.edtDuration, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ContractCoefficientTestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 3)
        self.lblMaxDuration = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxDuration.sizePolicy().hasHeightForWidth())
        self.lblMaxDuration.setSizePolicy(sizePolicy)
        self.lblMaxDuration.setObjectName(_fromUtf8("lblMaxDuration"))
        self.gridLayout.addWidget(self.lblMaxDuration, 4, 0, 1, 1)
        self.edtMaxDuration = QtGui.QSpinBox(ContractCoefficientTestDialog)
        self.edtMaxDuration.setMaximum(999)
        self.edtMaxDuration.setProperty("value", 15)
        self.edtMaxDuration.setObjectName(_fromUtf8("edtMaxDuration"))
        self.gridLayout.addWidget(self.edtMaxDuration, 4, 1, 1, 1)
        self.lblAvgDuration = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAvgDuration.sizePolicy().hasHeightForWidth())
        self.lblAvgDuration.setSizePolicy(sizePolicy)
        self.lblAvgDuration.setObjectName(_fromUtf8("lblAvgDuration"))
        self.gridLayout.addWidget(self.lblAvgDuration, 5, 0, 1, 1)
        self.edtAvgDuration = QtGui.QDoubleSpinBox(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAvgDuration.sizePolicy().hasHeightForWidth())
        self.edtAvgDuration.setSizePolicy(sizePolicy)
        self.edtAvgDuration.setDecimals(3)
        self.edtAvgDuration.setMaximum(999.99)
        self.edtAvgDuration.setProperty("value", 10.0)
        self.edtAvgDuration.setObjectName(_fromUtf8("edtAvgDuration"))
        self.gridLayout.addWidget(self.edtAvgDuration, 5, 1, 1, 1)
        self.lblEvaluated = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEvaluated.sizePolicy().hasHeightForWidth())
        self.lblEvaluated.setSizePolicy(sizePolicy)
        self.lblEvaluated.setObjectName(_fromUtf8("lblEvaluated"))
        self.gridLayout.addWidget(self.lblEvaluated, 6, 0, 1, 1)
        self.edtK = QtGui.QDoubleSpinBox(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtK.sizePolicy().hasHeightForWidth())
        self.edtK.setSizePolicy(sizePolicy)
        self.edtK.setDecimals(3)
        self.edtK.setMaximum(999.99)
        self.edtK.setSingleStep(0.01)
        self.edtK.setProperty("value", 0.75)
        self.edtK.setObjectName(_fromUtf8("edtK"))
        self.gridLayout.addWidget(self.edtK, 1, 1, 1, 1)
        self.edtMinDuration = QtGui.QSpinBox(ContractCoefficientTestDialog)
        self.edtMinDuration.setMaximum(999)
        self.edtMinDuration.setProperty("value", 5)
        self.edtMinDuration.setObjectName(_fromUtf8("edtMinDuration"))
        self.gridLayout.addWidget(self.edtMinDuration, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblDuration = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDuration.sizePolicy().hasHeightForWidth())
        self.lblDuration.setSizePolicy(sizePolicy)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridLayout.addWidget(self.lblDuration, 2, 0, 1, 1)
        self.lblMinDuration = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinDuration.sizePolicy().hasHeightForWidth())
        self.lblMinDuration.setSizePolicy(sizePolicy)
        self.lblMinDuration.setObjectName(_fromUtf8("lblMinDuration"))
        self.gridLayout.addWidget(self.lblMinDuration, 3, 0, 1, 1)
        self.edtAlgorithm = QtGui.QPlainTextEdit(ContractCoefficientTestDialog)
        self.edtAlgorithm.setObjectName(_fromUtf8("edtAlgorithm"))
        self.gridLayout.addWidget(self.edtAlgorithm, 0, 0, 1, 3)
        self.lblK = QtGui.QLabel(ContractCoefficientTestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblK.sizePolicy().hasHeightForWidth())
        self.lblK.setSizePolicy(sizePolicy)
        self.lblK.setIndent(-1)
        self.lblK.setObjectName(_fromUtf8("lblK"))
        self.gridLayout.addWidget(self.lblK, 1, 0, 1, 1)
        self.lblResult = QtGui.QLabel(ContractCoefficientTestDialog)
        self.lblResult.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblResult.setText(_fromUtf8(""))
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout.addWidget(self.lblResult, 6, 1, 1, 2)
        self.lblMaxDuration.setBuddy(self.edtMaxDuration)
        self.lblAvgDuration.setBuddy(self.edtAvgDuration)
        self.lblDuration.setBuddy(self.edtDuration)
        self.lblMinDuration.setBuddy(self.edtMinDuration)
        self.lblK.setBuddy(self.edtK)

        self.retranslateUi(ContractCoefficientTestDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ContractCoefficientTestDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ContractCoefficientTestDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ContractCoefficientTestDialog)
        ContractCoefficientTestDialog.setTabOrder(self.edtAlgorithm, self.edtK)
        ContractCoefficientTestDialog.setTabOrder(self.edtK, self.edtDuration)
        ContractCoefficientTestDialog.setTabOrder(self.edtDuration, self.edtMinDuration)
        ContractCoefficientTestDialog.setTabOrder(self.edtMinDuration, self.edtMaxDuration)
        ContractCoefficientTestDialog.setTabOrder(self.edtMaxDuration, self.edtAvgDuration)
        ContractCoefficientTestDialog.setTabOrder(self.edtAvgDuration, self.buttonBox)

    def retranslateUi(self, ContractCoefficientTestDialog):
        ContractCoefficientTestDialog.setWindowTitle(_translate("ContractCoefficientTestDialog", "Проверка алгоритма вычисления коэффициента", None))
        self.lblMaxDuration.setText(_translate("ContractCoefficientTestDialog", "ma&xDuration", None))
        self.lblAvgDuration.setText(_translate("ContractCoefficientTestDialog", "&avgDuration", None))
        self.lblEvaluated.setText(_translate("ContractCoefficientTestDialog", "Результат", None))
        self.lblDuration.setText(_translate("ContractCoefficientTestDialog", "&duration", None))
        self.lblMinDuration.setText(_translate("ContractCoefficientTestDialog", "mi&nDuration", None))
        self.lblK.setText(_translate("ContractCoefficientTestDialog", "&k", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ContractCoefficientTestDialog = QtGui.QDialog()
    ui = Ui_ContractCoefficientTestDialog()
    ui.setupUi(ContractCoefficientTestDialog)
    ContractCoefficientTestDialog.show()
    sys.exit(app.exec_())

