# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Exchange\ExportXmlEmc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(630, 438)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDateFrom = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateFrom.sizePolicy().hasHeightForWidth())
        self.lblDateFrom.setSizePolicy(sizePolicy)
        self.lblDateFrom.setObjectName(_fromUtf8("lblDateFrom"))
        self.gridLayout.addWidget(self.lblDateFrom, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 5)
        self.lblDateTo = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateTo.sizePolicy().hasHeightForWidth())
        self.lblDateTo.setSizePolicy(sizePolicy)
        self.lblDateTo.setObjectName(_fromUtf8("lblDateTo"))
        self.gridLayout.addWidget(self.lblDateTo, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 5)
        self.lblFilePath = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilePath.sizePolicy().hasHeightForWidth())
        self.lblFilePath.setSizePolicy(sizePolicy)
        self.lblFilePath.setObjectName(_fromUtf8("lblFilePath"))
        self.gridLayout.addWidget(self.lblFilePath, 2, 0, 1, 1)
        self.edtFileName = QtGui.QLineEdit(Dialog)
        self.edtFileName.setObjectName(_fromUtf8("edtFileName"))
        self.gridLayout.addWidget(self.edtFileName, 2, 1, 1, 5)
        self.btnOpenFilePath = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenFilePath.sizePolicy().hasHeightForWidth())
        self.btnOpenFilePath.setSizePolicy(sizePolicy)
        self.btnOpenFilePath.setObjectName(_fromUtf8("btnOpenFilePath"))
        self.gridLayout.addWidget(self.btnOpenFilePath, 2, 6, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventPurpose.sizePolicy().hasHeightForWidth())
        self.lblEventPurpose.setSizePolicy(sizePolicy)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 3, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(Dialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 3, 1, 1, 6)
        self.lblEventType = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 4, 0, 1, 1)
        self.cmbEventType = CRBComboBox(Dialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 4, 1, 1, 6)
        self.lblEventProfile = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventProfile.sizePolicy().hasHeightForWidth())
        self.lblEventProfile.setSizePolicy(sizePolicy)
        self.lblEventProfile.setObjectName(_fromUtf8("lblEventProfile"))
        self.gridLayout.addWidget(self.lblEventProfile, 5, 0, 1, 1)
        self.cmbEventProfile = CRBComboBox(Dialog)
        self.cmbEventProfile.setObjectName(_fromUtf8("cmbEventProfile"))
        self.gridLayout.addWidget(self.cmbEventProfile, 5, 1, 1, 6)
        self.lblMes = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMes.sizePolicy().hasHeightForWidth())
        self.lblMes.setSizePolicy(sizePolicy)
        self.lblMes.setObjectName(_fromUtf8("lblMes"))
        self.gridLayout.addWidget(self.lblMes, 6, 0, 1, 1)
        self.cmbMes = CMESComboBox(Dialog)
        self.cmbMes.setObjectName(_fromUtf8("cmbMes"))
        self.gridLayout.addWidget(self.cmbMes, 6, 1, 1, 6)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 2, 7)
        self.cmbSpeciality = CRBComboBox(Dialog)
        self.cmbSpeciality.setEnabled(False)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 8, 1, 2, 6)
        self.chkSpeciality = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSpeciality.sizePolicy().hasHeightForWidth())
        self.chkSpeciality.setSizePolicy(sizePolicy)
        self.chkSpeciality.setObjectName(_fromUtf8("chkSpeciality"))
        self.gridLayout.addWidget(self.chkSpeciality, 9, 0, 1, 1)
        self.chkDoctor = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDoctor.sizePolicy().hasHeightForWidth())
        self.chkDoctor.setSizePolicy(sizePolicy)
        self.chkDoctor.setObjectName(_fromUtf8("chkDoctor"))
        self.gridLayout.addWidget(self.chkDoctor, 10, 0, 1, 1)
        self.cmbDoctor = CPersonComboBoxEx(Dialog)
        self.cmbDoctor.setEnabled(False)
        self.cmbDoctor.setObjectName(_fromUtf8("cmbDoctor"))
        self.gridLayout.addWidget(self.cmbDoctor, 10, 1, 1, 6)
        self.chkSex = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSex.sizePolicy().hasHeightForWidth())
        self.chkSex.setSizePolicy(sizePolicy)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 11, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(Dialog)
        self.cmbSex.setEnabled(False)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 11, 1, 1, 1)
        self.chkAge = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAge.sizePolicy().hasHeightForWidth())
        self.chkAge.setSizePolicy(sizePolicy)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 12, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtBegAge = QtGui.QSpinBox(Dialog)
        self.edtBegAge.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAge.sizePolicy().hasHeightForWidth())
        self.edtBegAge.setSizePolicy(sizePolicy)
        self.edtBegAge.setMaximum(150)
        self.edtBegAge.setObjectName(_fromUtf8("edtBegAge"))
        self.horizontalLayout.addWidget(self.edtBegAge)
        self.label_5 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.edtEndAge = QtGui.QSpinBox(Dialog)
        self.edtEndAge.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAge.sizePolicy().hasHeightForWidth())
        self.edtEndAge.setSizePolicy(sizePolicy)
        self.edtEndAge.setMaximum(150)
        self.edtEndAge.setProperty("value", 150)
        self.edtEndAge.setObjectName(_fromUtf8("edtEndAge"))
        self.horizontalLayout.addWidget(self.edtEndAge)
        self.label = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 12, 3, 1, 4)
        self.chkInsurer = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkInsurer.sizePolicy().hasHeightForWidth())
        self.chkInsurer.setSizePolicy(sizePolicy)
        self.chkInsurer.setObjectName(_fromUtf8("chkInsurer"))
        self.gridLayout.addWidget(self.chkInsurer, 13, 0, 1, 1)
        self.cmbInsurer = CInsurerComboBox(Dialog)
        self.cmbInsurer.setEnabled(False)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 13, 1, 1, 3)
        self.cmbPolicyType = QtGui.QComboBox(Dialog)
        self.cmbPolicyType.setEnabled(False)
        self.cmbPolicyType.setObjectName(_fromUtf8("cmbPolicyType"))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPolicyType, 13, 4, 1, 3)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 14, 0, 1, 7)
        self.progressBar = CProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 15, 0, 1, 7)
        self.chkMakeRar = QtGui.QCheckBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkMakeRar.sizePolicy().hasHeightForWidth())
        self.chkMakeRar.setSizePolicy(sizePolicy)
        self.chkMakeRar.setObjectName(_fromUtf8("chkMakeRar"))
        self.gridLayout.addWidget(self.chkMakeRar, 16, 0, 1, 7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 17, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 18, 0, 1, 1)
        self.btnClose = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 18, 5, 1, 2)
        self.btnStart = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.gridLayout.addWidget(self.btnStart, 18, 4, 1, 1)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblMes.setBuddy(self.cmbMes)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.chkSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkDoctor, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDoctor.setEnabled)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegAge.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndAge.setEnabled)
        QtCore.QObject.connect(self.chkInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbInsurer.setEnabled)
        QtCore.QObject.connect(self.chkInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPolicyType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtFileName)
        Dialog.setTabOrder(self.edtFileName, self.btnOpenFilePath)
        Dialog.setTabOrder(self.btnOpenFilePath, self.cmbEventPurpose)
        Dialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        Dialog.setTabOrder(self.cmbEventType, self.cmbEventProfile)
        Dialog.setTabOrder(self.cmbEventProfile, self.cmbMes)
        Dialog.setTabOrder(self.cmbMes, self.chkSpeciality)
        Dialog.setTabOrder(self.chkSpeciality, self.cmbSpeciality)
        Dialog.setTabOrder(self.cmbSpeciality, self.chkDoctor)
        Dialog.setTabOrder(self.chkDoctor, self.cmbDoctor)
        Dialog.setTabOrder(self.cmbDoctor, self.chkSex)
        Dialog.setTabOrder(self.chkSex, self.cmbSex)
        Dialog.setTabOrder(self.cmbSex, self.chkAge)
        Dialog.setTabOrder(self.chkAge, self.edtBegAge)
        Dialog.setTabOrder(self.edtBegAge, self.edtEndAge)
        Dialog.setTabOrder(self.edtEndAge, self.chkInsurer)
        Dialog.setTabOrder(self.chkInsurer, self.cmbInsurer)
        Dialog.setTabOrder(self.cmbInsurer, self.cmbPolicyType)
        Dialog.setTabOrder(self.cmbPolicyType, self.chkMakeRar)
        Dialog.setTabOrder(self.chkMakeRar, self.btnStart)
        Dialog.setTabOrder(self.btnStart, self.btnClose)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.lblDateFrom.setText(_translate("Dialog", "Дата начала периода", None))
        self.lblDateTo.setText(_translate("Dialog", "Дата окончания периода", None))
        self.lblFilePath.setText(_translate("Dialog", "Файл экспорта", None))
        self.btnOpenFilePath.setText(_translate("Dialog", "...", None))
        self.lblEventPurpose.setText(_translate("Dialog", "Назначение события", None))
        self.lblEventType.setText(_translate("Dialog", "Тип события", None))
        self.lblEventProfile.setText(_translate("Dialog", "Профиль МЭС", None))
        self.lblMes.setText(_translate("Dialog", "МЭС", None))
        self.chkSpeciality.setText(_translate("Dialog", "Специальность", None))
        self.chkDoctor.setText(_translate("Dialog", "Врач", None))
        self.chkSex.setText(_translate("Dialog", "Пол", None))
        self.cmbSex.setItemText(1, _translate("Dialog", "М", None))
        self.cmbSex.setItemText(2, _translate("Dialog", "Ж", None))
        self.chkAge.setText(_translate("Dialog", "Возраст с", None))
        self.label_5.setText(_translate("Dialog", "по", None))
        self.label.setText(_translate("Dialog", "лет", None))
        self.chkInsurer.setText(_translate("Dialog", "Страховая компания", None))
        self.cmbPolicyType.setItemText(0, _translate("Dialog", "Не задано", None))
        self.cmbPolicyType.setItemText(1, _translate("Dialog", "ОМС", None))
        self.cmbPolicyType.setItemText(2, _translate("Dialog", "ДМС", None))
        self.chkMakeRar.setText(_translate("Dialog", "Архивировать в rar", None))
        self.btnClose.setText(_translate("Dialog", "Закрыть", None))
        self.btnStart.setText(_translate("Dialog", "Начать", None))

from Orgs.OrgComboBox import CInsurerComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.MES.MESComboBox import CMESComboBox
from library.ProgressBar import CProgressBar
from library.crbcombobox import CRBComboBox
