# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Exchange\ExportPrimaryDocInXml.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExportPrimaryDocInXmlDialog(object):
    def setupUi(self, ExportPrimaryDocInXmlDialog):
        ExportPrimaryDocInXmlDialog.setObjectName(_fromUtf8("ExportPrimaryDocInXmlDialog"))
        ExportPrimaryDocInXmlDialog.resize(532, 641)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExportPrimaryDocInXmlDialog.sizePolicy().hasHeightForWidth())
        ExportPrimaryDocInXmlDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(ExportPrimaryDocInXmlDialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDateFrom = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateFrom.sizePolicy().hasHeightForWidth())
        self.lblDateFrom.setSizePolicy(sizePolicy)
        self.lblDateFrom.setObjectName(_fromUtf8("lblDateFrom"))
        self.gridLayout.addWidget(self.lblDateFrom, 0, 0, 1, 1)
        self.edtDateFrom = CDateEdit(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDateFrom.sizePolicy().hasHeightForWidth())
        self.edtDateFrom.setSizePolicy(sizePolicy)
        self.edtDateFrom.setObjectName(_fromUtf8("edtDateFrom"))
        self.gridLayout.addWidget(self.edtDateFrom, 0, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(284, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 8)
        self.lblDateTo = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateTo.sizePolicy().hasHeightForWidth())
        self.lblDateTo.setSizePolicy(sizePolicy)
        self.lblDateTo.setObjectName(_fromUtf8("lblDateTo"))
        self.gridLayout.addWidget(self.lblDateTo, 1, 0, 1, 1)
        self.edtDateTo = CDateEdit(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDateTo.sizePolicy().hasHeightForWidth())
        self.edtDateTo.setSizePolicy(sizePolicy)
        self.edtDateTo.setObjectName(_fromUtf8("edtDateTo"))
        self.gridLayout.addWidget(self.edtDateTo, 1, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(284, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 8)
        self.lblFilePath = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilePath.sizePolicy().hasHeightForWidth())
        self.lblFilePath.setSizePolicy(sizePolicy)
        self.lblFilePath.setObjectName(_fromUtf8("lblFilePath"))
        self.gridLayout.addWidget(self.lblFilePath, 2, 0, 1, 1)
        self.edtFilePath = QtGui.QLineEdit(ExportPrimaryDocInXmlDialog)
        self.edtFilePath.setObjectName(_fromUtf8("edtFilePath"))
        self.gridLayout.addWidget(self.edtFilePath, 2, 1, 1, 10)
        self.btnOpenFilePath = QtGui.QPushButton(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenFilePath.sizePolicy().hasHeightForWidth())
        self.btnOpenFilePath.setSizePolicy(sizePolicy)
        self.btnOpenFilePath.setObjectName(_fromUtf8("btnOpenFilePath"))
        self.gridLayout.addWidget(self.btnOpenFilePath, 2, 11, 1, 1)
        self.label_3 = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.cmbPersonSpecialityCode = QtGui.QComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbPersonSpecialityCode.setObjectName(_fromUtf8("cmbPersonSpecialityCode"))
        self.gridLayout.addWidget(self.cmbPersonSpecialityCode, 3, 1, 1, 11)
        self.chkOnlyMes = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkOnlyMes.sizePolicy().hasHeightForWidth())
        self.chkOnlyMes.setSizePolicy(sizePolicy)
        self.chkOnlyMes.setChecked(True)
        self.chkOnlyMes.setObjectName(_fromUtf8("chkOnlyMes"))
        self.gridLayout.addWidget(self.chkOnlyMes, 4, 0, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventPurpose.sizePolicy().hasHeightForWidth())
        self.lblEventPurpose.setSizePolicy(sizePolicy)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 5, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 5, 1, 1, 11)
        self.lblEventType = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 6, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 6, 1, 1, 11)
        self.lblEventProfile = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventProfile.sizePolicy().hasHeightForWidth())
        self.lblEventProfile.setSizePolicy(sizePolicy)
        self.lblEventProfile.setObjectName(_fromUtf8("lblEventProfile"))
        self.gridLayout.addWidget(self.lblEventProfile, 7, 0, 1, 1)
        self.cmbEventProfile = CRBComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbEventProfile.setObjectName(_fromUtf8("cmbEventProfile"))
        self.gridLayout.addWidget(self.cmbEventProfile, 7, 1, 1, 11)
        self.lblMes = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMes.sizePolicy().hasHeightForWidth())
        self.lblMes.setSizePolicy(sizePolicy)
        self.lblMes.setObjectName(_fromUtf8("lblMes"))
        self.gridLayout.addWidget(self.lblMes, 8, 0, 1, 1)
        self.cmbMes = CMESComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbMes.setObjectName(_fromUtf8("cmbMes"))
        self.gridLayout.addWidget(self.cmbMes, 8, 1, 1, 11)
        self.line = QtGui.QFrame(ExportPrimaryDocInXmlDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 9, 0, 2, 12)
        self.cmbSpeciality = CRBComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbSpeciality.setEnabled(False)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 10, 1, 2, 11)
        self.chkSpeciality = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSpeciality.sizePolicy().hasHeightForWidth())
        self.chkSpeciality.setSizePolicy(sizePolicy)
        self.chkSpeciality.setObjectName(_fromUtf8("chkSpeciality"))
        self.gridLayout.addWidget(self.chkSpeciality, 11, 0, 1, 1)
        self.chkDoctor = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDoctor.sizePolicy().hasHeightForWidth())
        self.chkDoctor.setSizePolicy(sizePolicy)
        self.chkDoctor.setObjectName(_fromUtf8("chkDoctor"))
        self.gridLayout.addWidget(self.chkDoctor, 12, 0, 1, 1)
        self.cmbDoctor = CPersonComboBoxEx(ExportPrimaryDocInXmlDialog)
        self.cmbDoctor.setEnabled(False)
        self.cmbDoctor.setObjectName(_fromUtf8("cmbDoctor"))
        self.gridLayout.addWidget(self.cmbDoctor, 12, 1, 1, 11)
        self.chkSex = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSex.sizePolicy().hasHeightForWidth())
        self.chkSex.setSizePolicy(sizePolicy)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 13, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbSex.setEnabled(False)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 13, 1, 1, 1)
        self.chkAge = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAge.sizePolicy().hasHeightForWidth())
        self.chkAge.setSizePolicy(sizePolicy)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 14, 0, 1, 1)
        self.edtAgeBegin = QtGui.QSpinBox(ExportPrimaryDocInXmlDialog)
        self.edtAgeBegin.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeBegin.sizePolicy().hasHeightForWidth())
        self.edtAgeBegin.setSizePolicy(sizePolicy)
        self.edtAgeBegin.setMaximum(150)
        self.edtAgeBegin.setObjectName(_fromUtf8("edtAgeBegin"))
        self.gridLayout.addWidget(self.edtAgeBegin, 14, 1, 1, 1)
        self.label_5 = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 14, 2, 1, 1)
        self.edtAgeEnd = QtGui.QSpinBox(ExportPrimaryDocInXmlDialog)
        self.edtAgeEnd.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeEnd.sizePolicy().hasHeightForWidth())
        self.edtAgeEnd.setSizePolicy(sizePolicy)
        self.edtAgeEnd.setMaximum(150)
        self.edtAgeEnd.setProperty("value", 150)
        self.edtAgeEnd.setObjectName(_fromUtf8("edtAgeEnd"))
        self.gridLayout.addWidget(self.edtAgeEnd, 14, 3, 1, 2)
        self.label = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 14, 5, 1, 1)
        self.chkInsurer = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkInsurer.sizePolicy().hasHeightForWidth())
        self.chkInsurer.setSizePolicy(sizePolicy)
        self.chkInsurer.setObjectName(_fromUtf8("chkInsurer"))
        self.gridLayout.addWidget(self.chkInsurer, 15, 0, 1, 1)
        self.cmbInsurer = CInsurerComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbInsurer.setEnabled(False)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 15, 1, 1, 8)
        self.cmbPolicyType = QtGui.QComboBox(ExportPrimaryDocInXmlDialog)
        self.cmbPolicyType.setEnabled(False)
        self.cmbPolicyType.setObjectName(_fromUtf8("cmbPolicyType"))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.cmbPolicyType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPolicyType, 15, 9, 1, 3)
        self.chkExportClientData = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExportClientData.sizePolicy().hasHeightForWidth())
        self.chkExportClientData.setSizePolicy(sizePolicy)
        self.chkExportClientData.setChecked(True)
        self.chkExportClientData.setObjectName(_fromUtf8("chkExportClientData"))
        self.gridLayout.addWidget(self.chkExportClientData, 16, 0, 1, 5)
        self.chkExportActions = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExportActions.sizePolicy().hasHeightForWidth())
        self.chkExportActions.setSizePolicy(sizePolicy)
        self.chkExportActions.setChecked(True)
        self.chkExportActions.setObjectName(_fromUtf8("chkExportActions"))
        self.gridLayout.addWidget(self.chkExportActions, 17, 0, 1, 1)
        self.chkActionExecPerson = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActionExecPerson.sizePolicy().hasHeightForWidth())
        self.chkActionExecPerson.setSizePolicy(sizePolicy)
        self.chkActionExecPerson.setChecked(True)
        self.chkActionExecPerson.setObjectName(_fromUtf8("chkActionExecPerson"))
        self.gridLayout.addWidget(self.chkActionExecPerson, 17, 1, 1, 6)
        self.chkOnlyNomenclativeActions = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkOnlyNomenclativeActions.sizePolicy().hasHeightForWidth())
        self.chkOnlyNomenclativeActions.setSizePolicy(sizePolicy)
        self.chkOnlyNomenclativeActions.setObjectName(_fromUtf8("chkOnlyNomenclativeActions"))
        self.gridLayout.addWidget(self.chkOnlyNomenclativeActions, 17, 7, 1, 4)
        self.chkExportVisits = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExportVisits.sizePolicy().hasHeightForWidth())
        self.chkExportVisits.setSizePolicy(sizePolicy)
        self.chkExportVisits.setChecked(True)
        self.chkExportVisits.setObjectName(_fromUtf8("chkExportVisits"))
        self.gridLayout.addWidget(self.chkExportVisits, 18, 0, 1, 1)
        self.chkExportTempInvalid = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        self.chkExportTempInvalid.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExportTempInvalid.sizePolicy().hasHeightForWidth())
        self.chkExportTempInvalid.setSizePolicy(sizePolicy)
        self.chkExportTempInvalid.setObjectName(_fromUtf8("chkExportTempInvalid"))
        self.gridLayout.addWidget(self.chkExportTempInvalid, 19, 0, 1, 1)
        self.chkExportOnlyExecutedTempInvalid = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        self.chkExportOnlyExecutedTempInvalid.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkExportOnlyExecutedTempInvalid.sizePolicy().hasHeightForWidth())
        self.chkExportOnlyExecutedTempInvalid.setSizePolicy(sizePolicy)
        self.chkExportOnlyExecutedTempInvalid.setChecked(True)
        self.chkExportOnlyExecutedTempInvalid.setObjectName(_fromUtf8("chkExportOnlyExecutedTempInvalid"))
        self.gridLayout.addWidget(self.chkExportOnlyExecutedTempInvalid, 19, 1, 1, 5)
        self.chkOnlyEndDiagnostic = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkOnlyEndDiagnostic.sizePolicy().hasHeightForWidth())
        self.chkOnlyEndDiagnostic.setSizePolicy(sizePolicy)
        self.chkOnlyEndDiagnostic.setChecked(True)
        self.chkOnlyEndDiagnostic.setObjectName(_fromUtf8("chkOnlyEndDiagnostic"))
        self.gridLayout.addWidget(self.chkOnlyEndDiagnostic, 20, 0, 1, 5)
        self.line_2 = QtGui.QFrame(ExportPrimaryDocInXmlDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 21, 0, 1, 12)
        self.lblDetail = QtGui.QLabel(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetail.sizePolicy().hasHeightForWidth())
        self.lblDetail.setSizePolicy(sizePolicy)
        self.lblDetail.setObjectName(_fromUtf8("lblDetail"))
        self.gridLayout.addWidget(self.lblDetail, 22, 0, 1, 1)
        self.chkAddressDetail = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        self.chkAddressDetail.setObjectName(_fromUtf8("chkAddressDetail"))
        self.gridLayout.addWidget(self.chkAddressDetail, 22, 1, 1, 2)
        self.chkPolicyDetail = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        self.chkPolicyDetail.setObjectName(_fromUtf8("chkPolicyDetail"))
        self.gridLayout.addWidget(self.chkPolicyDetail, 22, 4, 1, 2)
        self.chkDocumentDetail = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        self.chkDocumentDetail.setObjectName(_fromUtf8("chkDocumentDetail"))
        self.gridLayout.addWidget(self.chkDocumentDetail, 22, 7, 1, 2)
        self.progressBar = CProgressBar(ExportPrimaryDocInXmlDialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 23, 0, 1, 12)
        self.chkMakeRar = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkMakeRar.sizePolicy().hasHeightForWidth())
        self.chkMakeRar.setSizePolicy(sizePolicy)
        self.chkMakeRar.setObjectName(_fromUtf8("chkMakeRar"))
        self.gridLayout.addWidget(self.chkMakeRar, 24, 0, 1, 1)
        self.chkSendEmail = QtGui.QCheckBox(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSendEmail.sizePolicy().hasHeightForWidth())
        self.chkSendEmail.setSizePolicy(sizePolicy)
        self.chkSendEmail.setObjectName(_fromUtf8("chkSendEmail"))
        self.gridLayout.addWidget(self.chkSendEmail, 25, 0, 1, 1)
        self.edtSendEmail = QtGui.QLineEdit(ExportPrimaryDocInXmlDialog)
        self.edtSendEmail.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSendEmail.sizePolicy().hasHeightForWidth())
        self.edtSendEmail.setSizePolicy(sizePolicy)
        self.edtSendEmail.setObjectName(_fromUtf8("edtSendEmail"))
        self.gridLayout.addWidget(self.edtSendEmail, 25, 1, 1, 11)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 26, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 27, 0, 1, 8)
        self.btnStart = QtGui.QPushButton(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.gridLayout.addWidget(self.btnStart, 27, 8, 1, 2)
        self.btnClose = QtGui.QPushButton(ExportPrimaryDocInXmlDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 27, 10, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 14, 6, 1, 6)
        self.lblDateFrom.setBuddy(self.edtDateFrom)
        self.lblDateTo.setBuddy(self.edtDateTo)
        self.lblFilePath.setBuddy(self.edtFilePath)
        self.label_3.setBuddy(self.cmbPersonSpecialityCode)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblEventProfile.setBuddy(self.cmbEventProfile)
        self.lblMes.setBuddy(self.cmbMes)

        self.retranslateUi(ExportPrimaryDocInXmlDialog)
        QtCore.QObject.connect(self.chkSendEmail, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtSendEmail.setEnabled)
        QtCore.QObject.connect(self.chkSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkDoctor, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDoctor.setEnabled)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAgeBegin.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAgeEnd.setEnabled)
        QtCore.QObject.connect(self.chkOnlyMes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbEventPurpose.setEnabled)
        QtCore.QObject.connect(self.chkOnlyMes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbEventType.setEnabled)
        QtCore.QObject.connect(self.chkOnlyMes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbEventProfile.setEnabled)
        QtCore.QObject.connect(self.chkOnlyMes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbMes.setEnabled)
        QtCore.QObject.connect(self.chkExportTempInvalid, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkExportOnlyExecutedTempInvalid.setEnabled)
        QtCore.QObject.connect(self.chkExportActions, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkOnlyNomenclativeActions.setEnabled)
        QtCore.QObject.connect(self.chkInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbInsurer.setEnabled)
        QtCore.QObject.connect(self.chkInsurer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPolicyType.setEnabled)
        QtCore.QObject.connect(self.chkExportActions, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkActionExecPerson.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ExportPrimaryDocInXmlDialog)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtDateFrom, self.edtDateTo)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtDateTo, self.edtFilePath)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtFilePath, self.btnOpenFilePath)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.btnOpenFilePath, self.cmbPersonSpecialityCode)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbPersonSpecialityCode, self.chkOnlyMes)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkOnlyMes, self.cmbEventPurpose)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbEventType, self.cmbEventProfile)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbEventProfile, self.cmbMes)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbMes, self.chkSpeciality)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkSpeciality, self.cmbSpeciality)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbSpeciality, self.chkDoctor)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkDoctor, self.cmbDoctor)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbDoctor, self.chkSex)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkSex, self.cmbSex)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbSex, self.chkAge)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkAge, self.edtAgeBegin)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtAgeBegin, self.edtAgeEnd)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtAgeEnd, self.chkInsurer)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkInsurer, self.cmbInsurer)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbInsurer, self.cmbPolicyType)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.cmbPolicyType, self.chkExportClientData)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkExportClientData, self.chkExportActions)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkExportActions, self.chkActionExecPerson)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkActionExecPerson, self.chkOnlyNomenclativeActions)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkOnlyNomenclativeActions, self.chkExportVisits)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkExportVisits, self.chkExportTempInvalid)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkExportTempInvalid, self.chkExportOnlyExecutedTempInvalid)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkExportOnlyExecutedTempInvalid, self.chkOnlyEndDiagnostic)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkOnlyEndDiagnostic, self.chkAddressDetail)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkAddressDetail, self.chkPolicyDetail)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkPolicyDetail, self.chkDocumentDetail)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkDocumentDetail, self.chkMakeRar)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkMakeRar, self.chkSendEmail)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.chkSendEmail, self.edtSendEmail)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.edtSendEmail, self.btnStart)
        ExportPrimaryDocInXmlDialog.setTabOrder(self.btnStart, self.btnClose)

    def retranslateUi(self, ExportPrimaryDocInXmlDialog):
        ExportPrimaryDocInXmlDialog.setWindowTitle(_translate("ExportPrimaryDocInXmlDialog", "Dialog", None))
        self.lblDateFrom.setText(_translate("ExportPrimaryDocInXmlDialog", "Дата начала периода", None))
        self.lblDateTo.setText(_translate("ExportPrimaryDocInXmlDialog", "Дата окончания периода", None))
        self.lblFilePath.setText(_translate("ExportPrimaryDocInXmlDialog", "Файл экспорта", None))
        self.btnOpenFilePath.setText(_translate("ExportPrimaryDocInXmlDialog", "...", None))
        self.label_3.setText(_translate("ExportPrimaryDocInXmlDialog", "Интерпретация кода специальности врача", None))
        self.chkOnlyMes.setText(_translate("ExportPrimaryDocInXmlDialog", "Только МЭС", None))
        self.lblEventPurpose.setText(_translate("ExportPrimaryDocInXmlDialog", "Назначение события", None))
        self.lblEventType.setText(_translate("ExportPrimaryDocInXmlDialog", "Тип события", None))
        self.lblEventProfile.setText(_translate("ExportPrimaryDocInXmlDialog", "Профиль МЭС", None))
        self.lblMes.setText(_translate("ExportPrimaryDocInXmlDialog", "МЭС", None))
        self.chkSpeciality.setText(_translate("ExportPrimaryDocInXmlDialog", "Специальность", None))
        self.chkDoctor.setText(_translate("ExportPrimaryDocInXmlDialog", "Врач", None))
        self.chkSex.setText(_translate("ExportPrimaryDocInXmlDialog", "Пол", None))
        self.cmbSex.setItemText(1, _translate("ExportPrimaryDocInXmlDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ExportPrimaryDocInXmlDialog", "Ж", None))
        self.chkAge.setText(_translate("ExportPrimaryDocInXmlDialog", "Возраст с", None))
        self.label_5.setText(_translate("ExportPrimaryDocInXmlDialog", "по", None))
        self.label.setText(_translate("ExportPrimaryDocInXmlDialog", "лет", None))
        self.chkInsurer.setText(_translate("ExportPrimaryDocInXmlDialog", "Страховая компания", None))
        self.cmbPolicyType.setItemText(0, _translate("ExportPrimaryDocInXmlDialog", "Не задано", None))
        self.cmbPolicyType.setItemText(1, _translate("ExportPrimaryDocInXmlDialog", "ОМС", None))
        self.cmbPolicyType.setItemText(2, _translate("ExportPrimaryDocInXmlDialog", "ДМС", None))
        self.chkExportClientData.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать персональные данные пациента", None))
        self.chkExportActions.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать действия", None))
        self.chkActionExecPerson.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать испольнителя", None))
        self.chkOnlyNomenclativeActions.setText(_translate("ExportPrimaryDocInXmlDialog", "Только номенклатурные", None))
        self.chkExportVisits.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать визиты", None))
        self.chkExportTempInvalid.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать ВУТ", None))
        self.chkExportOnlyExecutedTempInvalid.setText(_translate("ExportPrimaryDocInXmlDialog", "Только законченые", None))
        self.chkOnlyEndDiagnostic.setText(_translate("ExportPrimaryDocInXmlDialog", "Выгружать только заключительный диагноз", None))
        self.lblDetail.setText(_translate("ExportPrimaryDocInXmlDialog", "Детализировать: ", None))
        self.chkAddressDetail.setText(_translate("ExportPrimaryDocInXmlDialog", "Адрес", None))
        self.chkPolicyDetail.setText(_translate("ExportPrimaryDocInXmlDialog", "Полис", None))
        self.chkDocumentDetail.setText(_translate("ExportPrimaryDocInXmlDialog", "Документ", None))
        self.chkMakeRar.setText(_translate("ExportPrimaryDocInXmlDialog", "Архивировать в rar", None))
        self.chkSendEmail.setText(_translate("ExportPrimaryDocInXmlDialog", "Переслать по почте", None))
        self.btnStart.setText(_translate("ExportPrimaryDocInXmlDialog", "Начать", None))
        self.btnClose.setText(_translate("ExportPrimaryDocInXmlDialog", "Закрыть", None))

from Orgs.OrgComboBox import CInsurerComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.MES.MESComboBox import CMESComboBox
from library.ProgressBar import CProgressBar
from library.crbcombobox import CRBComboBox
