# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportTariffsR29Filter.ui'
#
# Created: Thu Apr 18 14:32:21 2019
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FilterDialog(object):
    def setupUi(self, FilterDialog):
        FilterDialog.setObjectName(_fromUtf8("FilterDialog"))
        FilterDialog.resize(626, 420)
        self.gridLayout = QtGui.QGridLayout(FilterDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnAdd = QtGui.QPushButton(FilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.gridLayout.addWidget(self.btnAdd, 14, 0, 1, 1)
        self.cmbMES = QtGui.QComboBox(FilterDialog)
        self.cmbMES.setObjectName(_fromUtf8("cmbMES"))
        self.cmbMES.addItem(_fromUtf8(""))
        self.cmbMES.addItem(_fromUtf8(""))
        self.cmbMES.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMES, 4, 1, 1, 2)
        self.lblMES = QtGui.QLabel(FilterDialog)
        self.lblMES.setObjectName(_fromUtf8("lblMES"))
        self.gridLayout.addWidget(self.lblMES, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 3)
        self.btnContinue = QtGui.QPushButton(FilterDialog)
        self.btnContinue.setObjectName(_fromUtf8("btnContinue"))
        self.gridLayout.addWidget(self.btnContinue, 18, 3, 1, 1)
        self.lblEventType = QtGui.QLabel(FilterDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 1, 0, 1, 1)
        self.lblInfis = QtGui.QLabel(FilterDialog)
        self.lblInfis.setObjectName(_fromUtf8("lblInfis"))
        self.gridLayout.addWidget(self.lblInfis, 0, 0, 1, 1)
        self.lblTariffType = QtGui.QLabel(FilterDialog)
        self.lblTariffType.setObjectName(_fromUtf8("lblTariffType"))
        self.gridLayout.addWidget(self.lblTariffType, 2, 0, 1, 1)
        self.edtInfis = QtGui.QLineEdit(FilterDialog)
        self.edtInfis.setObjectName(_fromUtf8("edtInfis"))
        self.gridLayout.addWidget(self.edtInfis, 0, 1, 1, 3)
        self.cmbTariffType = QtGui.QComboBox(FilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTariffType.sizePolicy().hasHeightForWidth())
        self.cmbTariffType.setSizePolicy(sizePolicy)
        self.cmbTariffType.setObjectName(_fromUtf8("cmbTariffType"))
        self.gridLayout.addWidget(self.cmbTariffType, 2, 1, 1, 3)
        self.cmbEventType = CRBComboBox(FilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 1, 1, 1, 3)
        self.cmbDepartment = CRBComboBox(FilterDialog)
        self.cmbDepartment.setObjectName(_fromUtf8("cmbDepartment"))
        self.gridLayout.addWidget(self.cmbDepartment, 3, 1, 1, 3)
        self.lstService = QtGui.QListWidget(FilterDialog)
        self.lstService.setObjectName(_fromUtf8("lstService"))
        self.gridLayout.addWidget(self.lstService, 17, 0, 1, 4)
        self.lblDepartment = QtGui.QLabel(FilterDialog)
        self.lblDepartment.setObjectName(_fromUtf8("lblDepartment"))
        self.gridLayout.addWidget(self.lblDepartment, 3, 0, 1, 1)
        self.lblAmount = QtGui.QLabel(FilterDialog)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.gridLayout.addWidget(self.lblAmount, 12, 0, 1, 1)
        self.spbAmount = QtGui.QSpinBox(FilterDialog)
        self.spbAmount.setMinimum(0)
        self.spbAmount.setObjectName(_fromUtf8("spbAmount"))
        self.gridLayout.addWidget(self.spbAmount, 12, 1, 1, 1)
        self.lblGroup = QtGui.QLabel(FilterDialog)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridLayout.addWidget(self.lblGroup, 12, 2, 1, 1)
        self.edtGroup = QtGui.QLineEdit(FilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtGroup.sizePolicy().hasHeightForWidth())
        self.edtGroup.setSizePolicy(sizePolicy)
        self.edtGroup.setObjectName(_fromUtf8("edtGroup"))
        self.gridLayout.addWidget(self.edtGroup, 12, 3, 1, 1)
        self.btnDelete = QtGui.QPushButton(FilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.gridLayout.addWidget(self.btnDelete, 14, 1, 1, 1)
        self.chkSpecOrgStructure = QtGui.QCheckBox(FilterDialog)
        self.chkSpecOrgStructure.setObjectName(_fromUtf8("chkSpecOrgStructure"))
        self.gridLayout.addWidget(self.chkSpecOrgStructure, 6, 1, 1, 1)
        self.chkIncompleteCaseStomotology = QtGui.QCheckBox(FilterDialog)
        self.chkIncompleteCaseStomotology.setObjectName(_fromUtf8("chkIncompleteCaseStomotology"))
        self.gridLayout.addWidget(self.chkIncompleteCaseStomotology, 11, 1, 1, 2)
        self.chkIsStac = QtGui.QCheckBox(FilterDialog)
        self.chkIsStac.setObjectName(_fromUtf8("chkIsStac"))
        self.gridLayout.addWidget(self.chkIsStac, 5, 1, 1, 1)

        self.retranslateUi(FilterDialog)
        QtCore.QObject.connect(self.btnContinue, QtCore.SIGNAL(_fromUtf8("clicked()")), FilterDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(FilterDialog)

    def retranslateUi(self, FilterDialog):
        FilterDialog.setWindowTitle(QtGui.QApplication.translate("FilterDialog", "Фильтр импорта тарифов для Архангельской области", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("FilterDialog", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMES.setItemText(0, QtGui.QApplication.translate("FilterDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMES.setItemText(1, QtGui.QApplication.translate("FilterDialog", "Нет или не выполнен", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMES.setItemText(2, QtGui.QApplication.translate("FilterDialog", "Выполнен", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMES.setText(QtGui.QApplication.translate("FilterDialog", "МЭС", None, QtGui.QApplication.UnicodeUTF8))
        self.btnContinue.setText(QtGui.QApplication.translate("FilterDialog", "Продолжить", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventType.setText(QtGui.QApplication.translate("FilterDialog", "Тип события", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfis.setText(QtGui.QApplication.translate("FilterDialog", "Код ИНФИС", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTariffType.setText(QtGui.QApplication.translate("FilterDialog", "Тарификация", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDepartment.setText(QtGui.QApplication.translate("FilterDialog", "Группа услуг", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAmount.setText(QtGui.QApplication.translate("FilterDialog", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGroup.setText(QtGui.QApplication.translate("FilterDialog", "Группа", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("FilterDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSpecOrgStructure.setText(QtGui.QApplication.translate("FilterDialog", "Подгрузить тариф для выделенного подразделения", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIncompleteCaseStomotology.setText(QtGui.QApplication.translate("FilterDialog", "Подгрузить тариф для незаконченного случая(только для стоматологии)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIsStac.setText(QtGui.QApplication.translate("FilterDialog", "Подгрузить тарифы для стационара/дненовго стационара", None, QtGui.QApplication.UnicodeUTF8))

from library.crbcombobox import CRBComboBox
