# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\Exchange\ImportTariffsR51.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 529)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabNormal = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabNormal.sizePolicy().hasHeightForWidth())
        self.tabNormal.setSizePolicy(sizePolicy)
        self.tabNormal.setObjectName(_fromUtf8("tabNormal"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabNormal)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tabNormal)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.edtFileName = QtGui.QLineEdit(self.tabNormal)
        self.edtFileName.setText(_fromUtf8(""))
        self.edtFileName.setReadOnly(True)
        self.edtFileName.setObjectName(_fromUtf8("edtFileName"))
        self.gridLayout_2.addWidget(self.edtFileName, 0, 1, 1, 1)
        self.btnSelectFile = QtGui.QToolButton(self.tabNormal)
        self.btnSelectFile.setObjectName(_fromUtf8("btnSelectFile"))
        self.gridLayout_2.addWidget(self.btnSelectFile, 0, 2, 1, 1)
        self.btnView = QtGui.QPushButton(self.tabNormal)
        self.btnView.setObjectName(_fromUtf8("btnView"))
        self.gridLayout_2.addWidget(self.btnView, 0, 3, 1, 1)
        self.lblLpuCode = QtGui.QLabel(self.tabNormal)
        self.lblLpuCode.setObjectName(_fromUtf8("lblLpuCode"))
        self.gridLayout_2.addWidget(self.lblLpuCode, 1, 0, 1, 1)
        self.edtLpuCode = QtGui.QLineEdit(self.tabNormal)
        self.edtLpuCode.setObjectName(_fromUtf8("edtLpuCode"))
        self.gridLayout_2.addWidget(self.edtLpuCode, 1, 1, 1, 3)
        self.gbTariffType = QtGui.QGroupBox(self.tabNormal)
        self.gbTariffType.setObjectName(_fromUtf8("gbTariffType"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbTariffType)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkTariffVisit = QtGui.QRadioButton(self.gbTariffType)
        self.chkTariffVisit.setChecked(True)
        self.chkTariffVisit.setObjectName(_fromUtf8("chkTariffVisit"))
        self.verticalLayout.addWidget(self.chkTariffVisit)
        self.chkTariffService = QtGui.QRadioButton(self.gbTariffType)
        self.chkTariffService.setObjectName(_fromUtf8("chkTariffService"))
        self.verticalLayout.addWidget(self.chkTariffService)
        self.gridLayout_2.addWidget(self.gbTariffType, 2, 0, 1, 4)
        self.tabWidget.addTab(self.tabNormal, _fromUtf8(""))
        self.tabTooth = QtGui.QWidget()
        self.tabTooth.setObjectName(_fromUtf8("tabTooth"))
        self.gridLayout = QtGui.QGridLayout(self.tabTooth)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblToothRbDir = QtGui.QLabel(self.tabTooth)
        self.lblToothRbDir.setObjectName(_fromUtf8("lblToothRbDir"))
        self.gridLayout.addWidget(self.lblToothRbDir, 0, 0, 1, 1)
        self.edtToothRbDir = QtGui.QLineEdit(self.tabTooth)
        self.edtToothRbDir.setObjectName(_fromUtf8("edtToothRbDir"))
        self.gridLayout.addWidget(self.edtToothRbDir, 0, 1, 1, 1)
        self.btnSelectToothRbDir = QtGui.QToolButton(self.tabTooth)
        self.btnSelectToothRbDir.setObjectName(_fromUtf8("btnSelectToothRbDir"))
        self.gridLayout.addWidget(self.btnSelectToothRbDir, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabTooth, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.frmOptions = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmOptions.sizePolicy().hasHeightForWidth())
        self.frmOptions.setSizePolicy(sizePolicy)
        self.frmOptions.setObjectName(_fromUtf8("frmOptions"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmOptions)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbAge = QtGui.QGroupBox(self.frmOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbAge.sizePolicy().hasHeightForWidth())
        self.gbAge.setSizePolicy(sizePolicy)
        self.gbAge.setObjectName(_fromUtf8("gbAge"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbAge)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chkLoadChildren = QtGui.QRadioButton(self.gbAge)
        self.chkLoadChildren.setChecked(True)
        self.chkLoadChildren.setObjectName(_fromUtf8("chkLoadChildren"))
        self.verticalLayout_3.addWidget(self.chkLoadChildren)
        self.chkLoadMature = QtGui.QRadioButton(self.gbAge)
        self.chkLoadMature.setObjectName(_fromUtf8("chkLoadMature"))
        self.verticalLayout_3.addWidget(self.chkLoadMature)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.gbAge)
        self.gbPeriod = QtGui.QGroupBox(self.frmOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbPeriod.sizePolicy().hasHeightForWidth())
        self.gbPeriod.setSizePolicy(sizePolicy)
        self.gbPeriod.setObjectName(_fromUtf8("gbPeriod"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbPeriod)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblEndDate = QtGui.QLabel(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_3.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtBegDate = CDateEdit(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_3.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.edtEndDate = CDateEdit(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_3.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.gbPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_3.addWidget(self.lblBegDate, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gbPeriod)
        self.gbDublicates = QtGui.QGroupBox(self.frmOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbDublicates.sizePolicy().hasHeightForWidth())
        self.gbDublicates.setSizePolicy(sizePolicy)
        self.gbDublicates.setObjectName(_fromUtf8("gbDublicates"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbDublicates)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkUpdate = QtGui.QRadioButton(self.gbDublicates)
        self.chkUpdate.setChecked(True)
        self.chkUpdate.setObjectName(_fromUtf8("chkUpdate"))
        self.verticalLayout_2.addWidget(self.chkUpdate)
        self.chkSkip = QtGui.QRadioButton(self.gbDublicates)
        self.chkSkip.setObjectName(_fromUtf8("chkSkip"))
        self.verticalLayout_2.addWidget(self.chkSkip)
        self.chkAskUser = QtGui.QRadioButton(self.gbDublicates)
        self.chkAskUser.setObjectName(_fromUtf8("chkAskUser"))
        self.verticalLayout_2.addWidget(self.chkAskUser)
        self.horizontalLayout.addWidget(self.gbDublicates)
        self.gridLayout_4.addWidget(self.frmOptions, 1, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_4.addWidget(self.progressBar, 2, 0, 1, 1)
        self.statusLabel = QtGui.QLabel(Dialog)
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout_4.addWidget(self.statusLabel, 3, 0, 1, 1)
        self.log = QtGui.QTextBrowser(Dialog)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridLayout_4.addWidget(self.log, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnImport = QtGui.QPushButton(Dialog)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.horizontalLayout_2.addWidget(self.btnImport)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.labelNum = QtGui.QLabel(Dialog)
        self.labelNum.setObjectName(_fromUtf8("labelNum"))
        self.horizontalLayout_2.addWidget(self.labelNum)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btnClose = QtGui.QPushButton(Dialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.label.setBuddy(self.edtFileName)
        self.lblLpuCode.setBuddy(self.edtLpuCode)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.edtFileName)
        Dialog.setTabOrder(self.edtFileName, self.btnSelectFile)
        Dialog.setTabOrder(self.btnSelectFile, self.btnView)
        Dialog.setTabOrder(self.btnView, self.edtLpuCode)
        Dialog.setTabOrder(self.edtLpuCode, self.chkTariffVisit)
        Dialog.setTabOrder(self.chkTariffVisit, self.chkTariffService)
        Dialog.setTabOrder(self.chkTariffService, self.edtToothRbDir)
        Dialog.setTabOrder(self.edtToothRbDir, self.btnSelectToothRbDir)
        Dialog.setTabOrder(self.btnSelectToothRbDir, self.chkLoadChildren)
        Dialog.setTabOrder(self.chkLoadChildren, self.chkLoadMature)
        Dialog.setTabOrder(self.chkLoadMature, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.chkUpdate)
        Dialog.setTabOrder(self.chkUpdate, self.chkSkip)
        Dialog.setTabOrder(self.chkSkip, self.chkAskUser)
        Dialog.setTabOrder(self.chkAskUser, self.log)
        Dialog.setTabOrder(self.log, self.btnImport)
        Dialog.setTabOrder(self.btnImport, self.btnClose)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Загрузка тарифов для Мурманской области", None))
        self.label.setText(_translate("Dialog", "Импортировать из", None))
        self.btnSelectFile.setText(_translate("Dialog", "...", None))
        self.btnView.setText(_translate("Dialog", "Просмотр", None))
        self.lblLpuCode.setText(_translate("Dialog", "Код ЛПУ", None))
        self.gbTariffType.setTitle(_translate("Dialog", "Тип тарифа", None))
        self.chkTariffVisit.setText(_translate("Dialog", "Визиты", None))
        self.chkTariffService.setText(_translate("Dialog", "Услуги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNormal), _translate("Dialog", "Стандарт", None))
        self.lblToothRbDir.setText(_translate("Dialog", "директорий", None))
        self.edtToothRbDir.setToolTip(_translate("Dialog", "<html><head/><body><p>укажите путь к справочникам <span style=\" font-weight:600;\">R_SERV.DBF </span>и <span style=\" font-weight:600;\">STOMAT_TAR.DBF</span></p></body></html>", None))
        self.btnSelectToothRbDir.setText(_translate("Dialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTooth), _translate("Dialog", "Стоматология", None))
        self.gbAge.setTitle(_translate("Dialog", "Загружать", None))
        self.chkLoadChildren.setText(_translate("Dialog", "детские", None))
        self.chkLoadMature.setText(_translate("Dialog", "взрослые", None))
        self.gbPeriod.setTitle(_translate("Dialog", "Период", None))
        self.lblEndDate.setText(_translate("Dialog", "по", None))
        self.lblBegDate.setText(_translate("Dialog", "с", None))
        self.gbDublicates.setTitle(_translate("Dialog", "Совпадающие записи", None))
        self.chkUpdate.setText(_translate("Dialog", "Обновить", None))
        self.chkSkip.setText(_translate("Dialog", "Пропустить", None))
        self.chkAskUser.setText(_translate("Dialog", "Спросить у пользователя", None))
        self.btnImport.setText(_translate("Dialog", "начать импортирование", None))
        self.labelNum.setText(_translate("Dialog", "всего записей в источнике:", None))
        self.btnClose.setText(_translate("Dialog", "закрыть", None))

from library.DateEdit import CDateEdit
