# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\Exchange\ImportPayRefuseR29.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(653, 589)
        self.gridlayout = QtGui.QGridLayout(Dialog)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout.addWidget(self.label)
        self.edtFileName = QtGui.QLineEdit(Dialog)
        self.edtFileName.setObjectName(_fromUtf8("edtFileName"))
        self.hboxlayout.addWidget(self.edtFileName)
        self.btnSelectFile = QtGui.QToolButton(Dialog)
        self.btnSelectFile.setObjectName(_fromUtf8("btnSelectFile"))
        self.hboxlayout.addWidget(self.btnSelectFile)
        self.gridlayout.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.chkProcessRelevant = QtGui.QCheckBox(Dialog)
        self.chkProcessRelevant.setObjectName(_fromUtf8("chkProcessRelevant"))
        self.gridlayout.addWidget(self.chkProcessRelevant, 7, 0, 1, 1)
        self.chkImportPayed = QtGui.QCheckBox(Dialog)
        self.chkImportPayed.setEnabled(False)
        self.chkImportPayed.setChecked(True)
        self.chkImportPayed.setObjectName(_fromUtf8("chkImportPayed"))
        self.gridlayout.addWidget(self.chkImportPayed, 5, 0, 1, 1)
        self.stat = QtGui.QLabel(Dialog)
        self.stat.setText(_fromUtf8(""))
        self.stat.setObjectName(_fromUtf8("stat"))
        self.gridlayout.addWidget(self.stat, 14, 0, 1, 1)
        self.layoutConfirmation = QtGui.QHBoxLayout()
        self.layoutConfirmation.setObjectName(_fromUtf8("layoutConfirmation"))
        self.lblConfirmationDir = QtGui.QLabel(Dialog)
        self.lblConfirmationDir.setObjectName(_fromUtf8("lblConfirmationDir"))
        self.layoutConfirmation.addWidget(self.lblConfirmationDir)
        self.edtConfirmationDir = QtGui.QLineEdit(Dialog)
        self.edtConfirmationDir.setObjectName(_fromUtf8("edtConfirmationDir"))
        self.layoutConfirmation.addWidget(self.edtConfirmationDir)
        self.btnSelectConfirmationDir = QtGui.QToolButton(Dialog)
        self.btnSelectConfirmationDir.setObjectName(_fromUtf8("btnSelectConfirmationDir"))
        self.layoutConfirmation.addWidget(self.btnSelectConfirmationDir)
        self.btnManualConfirmation = QtGui.QPushButton(Dialog)
        self.btnManualConfirmation.setObjectName(_fromUtf8("btnManualConfirmation"))
        self.layoutConfirmation.addWidget(self.btnManualConfirmation)
        self.gridlayout.addLayout(self.layoutConfirmation, 8, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblChief = QtGui.QLabel(Dialog)
        self.lblChief.setObjectName(_fromUtf8("lblChief"))
        self.horizontalLayout.addWidget(self.lblChief)
        self.cmbChief = CPersonComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbChief.sizePolicy().hasHeightForWidth())
        self.cmbChief.setSizePolicy(sizePolicy)
        self.cmbChief.setObjectName(_fromUtf8("cmbChief"))
        self.horizontalLayout.addWidget(self.cmbChief)
        self.gridlayout.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        self.chkImportRefused = QtGui.QCheckBox(Dialog)
        self.chkImportRefused.setChecked(True)
        self.chkImportRefused.setObjectName(_fromUtf8("chkImportRefused"))
        self.gridlayout.addWidget(self.chkImportRefused, 6, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.btnImport = QtGui.QPushButton(Dialog)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.hboxlayout1.addWidget(self.btnImport)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.labelNum = QtGui.QLabel(Dialog)
        self.labelNum.setObjectName(_fromUtf8("labelNum"))
        self.hboxlayout1.addWidget(self.labelNum)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.btnClose = QtGui.QPushButton(Dialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.hboxlayout1.addWidget(self.btnClose)
        self.gridlayout.addLayout(self.hboxlayout1, 21, 0, 1, 1)
        self.log = QtGui.QTextBrowser(Dialog)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridlayout.addWidget(self.log, 20, 0, 1, 1)
        self.progressBar = CProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridlayout.addWidget(self.progressBar, 13, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout2.addWidget(self.label_2)
        self.edtConfirmation = QtGui.QLineEdit(Dialog)
        self.edtConfirmation.setObjectName(_fromUtf8("edtConfirmation"))
        self.hboxlayout2.addWidget(self.edtConfirmation)
        self.gridlayout.addLayout(self.hboxlayout2, 1, 0, 1, 1)
        self.hlDelegate = QtGui.QHBoxLayout()
        self.hlDelegate.setObjectName(_fromUtf8("hlDelegate"))
        self.lblDelegate = QtGui.QLabel(Dialog)
        self.lblDelegate.setObjectName(_fromUtf8("lblDelegate"))
        self.hlDelegate.addWidget(self.lblDelegate)
        self.cmbDelegate = CPersonComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDelegate.sizePolicy().hasHeightForWidth())
        self.cmbDelegate.setSizePolicy(sizePolicy)
        self.cmbDelegate.setObjectName(_fromUtf8("cmbDelegate"))
        self.hlDelegate.addWidget(self.cmbDelegate)
        self.gridlayout.addLayout(self.hlDelegate, 10, 0, 1, 1)
        self.chkOnlyCurrentAccount = QtGui.QCheckBox(Dialog)
        self.chkOnlyCurrentAccount.setChecked(True)
        self.chkOnlyCurrentAccount.setObjectName(_fromUtf8("chkOnlyCurrentAccount"))
        self.gridlayout.addWidget(self.chkOnlyCurrentAccount, 3, 0, 1, 1)
        self.chkImportInsurance = QtGui.QCheckBox(Dialog)
        self.chkImportInsurance.setObjectName(_fromUtf8("chkImportInsurance"))
        self.gridlayout.addWidget(self.chkImportInsurance, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Загрузка отказов оплаты для Архангельской области", None))
        self.label.setText(_translate("Dialog", "импортировать из", None))
        self.btnSelectFile.setText(_translate("Dialog", "...", None))
        self.chkProcessRelevant.setText(_translate("Dialog", "обработать по подходящим", None))
        self.chkImportPayed.setText(_translate("Dialog", "загружать оплаченные", None))
        self.lblConfirmationDir.setText(_translate("Dialog", "сохранить уведомление о получении пакета в", None))
        self.btnSelectConfirmationDir.setText(_translate("Dialog", "...", None))
        self.btnManualConfirmation.setText(_translate("Dialog", "Сформировать", None))
        self.lblChief.setText(_translate("Dialog", "руководитель", None))
        self.chkImportRefused.setText(_translate("Dialog", "загружать отказы", None))
        self.btnImport.setText(_translate("Dialog", "начать импортирование", None))
        self.labelNum.setText(_translate("Dialog", "всего записей в источнике:", None))
        self.btnClose.setText(_translate("Dialog", "закрыть", None))
        self.label_2.setText(_translate("Dialog", "подтверждение", None))
        self.edtConfirmation.setText(_translate("Dialog", "б/н", None))
        self.lblDelegate.setText(_translate("Dialog", "уполномоченное лицо", None))
        self.chkOnlyCurrentAccount.setText(_translate("Dialog", "только текущий счёт", None))
        self.chkImportInsurance.setText(_translate("Dialog", "импорт страховой принадлжености", None))

from Orgs.PersonComboBox import CPersonComboBox
from library.ProgressBar import CProgressBar
