# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_stock\RefBooks\MKB\MKBEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(507, 477)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCode = QtGui.QLabel(self.tabMain)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 0, 1, 1, 1)
        self.chkPrim = QtGui.QCheckBox(self.tabMain)
        self.chkPrim.setObjectName(_fromUtf8("chkPrim"))
        self.gridLayout_2.addWidget(self.chkPrim, 0, 2, 1, 4)
        self.lblName = QtGui.QLabel(self.tabMain)
        self.lblName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 1, 0, 1, 1)
        self.edtName = QtGui.QTextEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 1, 1, 1, 5)
        self.label = QtGui.QLabel(self.tabMain)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.cmbMKBSubclass = CRBComboBox(self.tabMain)
        self.cmbMKBSubclass.setObjectName(_fromUtf8("cmbMKBSubclass"))
        self.gridLayout_2.addWidget(self.cmbMKBSubclass, 2, 1, 1, 5)
        self.lblExSubclass = QtGui.QLabel(self.tabMain)
        self.lblExSubclass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblExSubclass.setWordWrap(True)
        self.lblExSubclass.setObjectName(_fromUtf8("lblExSubclass"))
        self.gridLayout_2.addWidget(self.lblExSubclass, 3, 0, 1, 1)
        self.tblExSubclass = CMKBExSubclassInDocTableView(self.tabMain)
        self.tblExSubclass.setObjectName(_fromUtf8("tblExSubclass"))
        self.gridLayout_2.addWidget(self.tblExSubclass, 3, 1, 1, 5)
        self.lblCharacters = QtGui.QLabel(self.tabMain)
        self.lblCharacters.setObjectName(_fromUtf8("lblCharacters"))
        self.gridLayout_2.addWidget(self.lblCharacters, 4, 0, 1, 1)
        self.cmbCharacters = QtGui.QComboBox(self.tabMain)
        self.cmbCharacters.setObjectName(_fromUtf8("cmbCharacters"))
        self.gridLayout_2.addWidget(self.cmbCharacters, 4, 1, 1, 5)
        self.lblEndDate = QtGui.QLabel(self.tabMain)
        self.lblEndDate.setWordWrap(True)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 5, 0, 1, 1)
        self.edtEndDate = CDateEdit(self.tabMain)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_2.addWidget(self.edtEndDate, 5, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(122, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 3, 1, 1)
        self.lblDuration = QtGui.QLabel(self.tabMain)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridLayout_2.addWidget(self.lblDuration, 6, 0, 1, 1)
        self.edtDuration = QtGui.QSpinBox(self.tabMain)
        self.edtDuration.setMaximum(999)
        self.edtDuration.setObjectName(_fromUtf8("edtDuration"))
        self.gridLayout_2.addWidget(self.edtDuration, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(223, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 6, 2, 1, 4)
        self.lblSex = QtGui.QLabel(self.tabMain)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout_2.addWidget(self.lblSex, 7, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.tabMain)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbSex, 7, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(223, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 7, 2, 1, 4)
        self.lblAge = QtGui.QLabel(self.tabMain)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout_2.addWidget(self.lblAge, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.tabMain)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbBegAgeUnit)
        self.edtBegAgeCount = QtGui.QLineEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.horizontalLayout_3.addWidget(self.edtBegAgeCount)
        self.lblAgeSep = QtGui.QLabel(self.tabMain)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.horizontalLayout_3.addWidget(self.lblAgeSep)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.tabMain)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbEndAgeUnit)
        self.edtEndAgeCount = QtGui.QLineEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.horizontalLayout_3.addWidget(self.edtEndAgeCount)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 8, 1, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(86, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 8, 5, 1, 1)
        self.lblService = QtGui.QLabel(self.tabMain)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout_2.addWidget(self.lblService, 9, 0, 1, 1)
        self.cmbService = CRBComboBox(self.tabMain)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout_2.addWidget(self.cmbService, 9, 1, 1, 3)
        self.btnSelectService = QtGui.QToolButton(self.tabMain)
        self.btnSelectService.setObjectName(_fromUtf8("btnSelectService"))
        self.gridLayout_2.addWidget(self.btnSelectService, 9, 4, 1, 2)
        self.lblRequiresFillingDispanser = QtGui.QLabel(self.tabMain)
        self.lblRequiresFillingDispanser.setObjectName(_fromUtf8("lblRequiresFillingDispanser"))
        self.gridLayout_2.addWidget(self.lblRequiresFillingDispanser, 10, 0, 1, 1)
        self.cmblRequiresFillingDispanser = QtGui.QComboBox(self.tabMain)
        self.cmblRequiresFillingDispanser.setObjectName(_fromUtf8("cmblRequiresFillingDispanser"))
        self.cmblRequiresFillingDispanser.addItem(_fromUtf8(""))
        self.cmblRequiresFillingDispanser.addItem(_fromUtf8(""))
        self.cmblRequiresFillingDispanser.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmblRequiresFillingDispanser, 10, 1, 1, 5)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.label.setBuddy(self.cmbMKBSubclass)
        self.lblCharacters.setBuddy(self.cmbCharacters)
        self.lblDuration.setBuddy(self.edtDuration)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblService.setBuddy(self.cmbService)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.chkPrim.setWhatsThis(_translate("ItemEditorDialog", "В справочнике МКБ обычно отмечается звёздочкой", None))
        self.chkPrim.setText(_translate("ItemEditorDialog", "уточняется в других рубриках", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.label.setText(_translate("ItemEditorDialog", "Cу&бклассификация\n"
"МКБ по 5 знаку", None))
        self.cmbMKBSubclass.setWhatsThis(_translate("ItemEditorDialog", "Последующее уточнение кода диагноза, не предписанное справочником МКБ", None))
        self.lblExSubclass.setText(_translate("ItemEditorDialog", "Расширенная субклассификация", None))
        self.lblCharacters.setText(_translate("ItemEditorDialog", "&Характер", None))
        self.cmbCharacters.setWhatsThis(_translate("ItemEditorDialog", "Допустимый характер заболевания, применяется для контроля ввода", None))
        self.lblEndDate.setText(_translate("ItemEditorDialog", "Дата окончания применения", None))
        self.edtEndDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lblDuration.setText(_translate("ItemEditorDialog", "&Длительность", None))
        self.lblSex.setText(_translate("ItemEditorDialog", "&Пол", None))
        self.cmbSex.setItemText(1, _translate("ItemEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ItemEditorDialog", "Ж", None))
        self.lblAge.setText(_translate("ItemEditorDialog", "Возраст", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ItemEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ItemEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ItemEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ItemEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("ItemEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("ItemEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ItemEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ItemEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ItemEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ItemEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("ItemEditorDialog", "000; ", None))
        self.lblService.setText(_translate("ItemEditorDialog", "&Услуга", None))
        self.btnSelectService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblRequiresFillingDispanser.setText(_translate("ItemEditorDialog", "Требует заполнения ДН", None))
        self.cmblRequiresFillingDispanser.setItemText(0, _translate("ItemEditorDialog", "Никогда", None))
        self.cmblRequiresFillingDispanser.setItemText(1, _translate("ItemEditorDialog", "Иногда", None))
        self.cmblRequiresFillingDispanser.setItemText(2, _translate("ItemEditorDialog", "Всегда", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "Идентификация", None))

from RefBooks.MKB.MKBExSubclassInDocTableView import CMKBExSubclassInDocTableView
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
