# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\AnaliticReportsSurgery.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AnaliticReportsSurgeryDialog(object):
    def setupUi(self, AnaliticReportsSurgeryDialog):
        AnaliticReportsSurgeryDialog.setObjectName(_fromUtf8("AnaliticReportsSurgeryDialog"))
        AnaliticReportsSurgeryDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AnaliticReportsSurgeryDialog.resize(536, 316)
        AnaliticReportsSurgeryDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(AnaliticReportsSurgeryDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblTypeSurgery = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblTypeSurgery.setObjectName(_fromUtf8("lblTypeSurgery"))
        self.gridLayout.addWidget(self.lblTypeSurgery, 8, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(AnaliticReportsSurgeryDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 1, 1, 3)
        self.cmbFinance = CRBComboBox(AnaliticReportsSurgeryDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 6, 1, 1, 3)
        self.lblOrgStructure = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 3, 0, 1, 1)
        self.btnEventTypeList = QtGui.QPushButton(AnaliticReportsSurgeryDialog)
        self.btnEventTypeList.setObjectName(_fromUtf8("btnEventTypeList"))
        self.gridLayout.addWidget(self.btnEventTypeList, 10, 0, 1, 1)
        self.edtBegDate = CDateEdit(AnaliticReportsSurgeryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblPerson = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 2)
        self.lblEventTypeList = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventTypeList.sizePolicy().hasHeightForWidth())
        self.lblEventTypeList.setSizePolicy(sizePolicy)
        self.lblEventTypeList.setWordWrap(True)
        self.lblEventTypeList.setObjectName(_fromUtf8("lblEventTypeList"))
        self.gridLayout.addWidget(self.lblEventTypeList, 10, 1, 1, 3)
        self.edtEndDate = CDateEdit(AnaliticReportsSurgeryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.cmbSelectType = QtGui.QComboBox(AnaliticReportsSurgeryDialog)
        self.cmbSelectType.setObjectName(_fromUtf8("cmbSelectType"))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSelectType, 2, 1, 1, 3)
        self.lblEndDate = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 13, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 2)
        self.cmbTypeSurgery = QtGui.QComboBox(AnaliticReportsSurgeryDialog)
        self.cmbTypeSurgery.setObjectName(_fromUtf8("cmbTypeSurgery"))
        self.cmbTypeSurgery.addItem(_fromUtf8(""))
        self.cmbTypeSurgery.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTypeSurgery, 8, 1, 1, 3)
        self.lblSpecialDeliverClient = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblSpecialDeliverClient.setObjectName(_fromUtf8("lblSpecialDeliverClient"))
        self.gridLayout.addWidget(self.lblSpecialDeliverClient, 5, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(AnaliticReportsSurgeryDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 3, 1, 1, 3)
        self.lblSelectType = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblSelectType.setObjectName(_fromUtf8("lblSelectType"))
        self.gridLayout.addWidget(self.lblSelectType, 2, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(AnaliticReportsSurgeryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 0, 1, 4)
        self.cmbSpecialDeliverClient = QtGui.QComboBox(AnaliticReportsSurgeryDialog)
        self.cmbSpecialDeliverClient.setObjectName(_fromUtf8("cmbSpecialDeliverClient"))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSpecialDeliverClient, 5, 1, 1, 3)
        self.lblFinance = QtGui.QLabel(AnaliticReportsSurgeryDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 6, 0, 1, 1)
        self.chkExistFlatCode = QtGui.QCheckBox(AnaliticReportsSurgeryDialog)
        self.chkExistFlatCode.setEnabled(True)
        self.chkExistFlatCode.setChecked(False)
        self.chkExistFlatCode.setObjectName(_fromUtf8("chkExistFlatCode"))
        self.gridLayout.addWidget(self.chkExistFlatCode, 9, 1, 1, 1)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(AnaliticReportsSurgeryDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), AnaliticReportsSurgeryDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), AnaliticReportsSurgeryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AnaliticReportsSurgeryDialog)
        AnaliticReportsSurgeryDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        AnaliticReportsSurgeryDialog.setTabOrder(self.edtEndDate, self.cmbSelectType)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbSelectType, self.cmbOrgStructure)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbPerson, self.buttonBox)
        AnaliticReportsSurgeryDialog.setTabOrder(self.buttonBox, self.cmbFinance)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbFinance, self.cmbTypeSurgery)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbTypeSurgery, self.cmbSpecialDeliverClient)
        AnaliticReportsSurgeryDialog.setTabOrder(self.cmbSpecialDeliverClient, self.btnEventTypeList)

    def retranslateUi(self, AnaliticReportsSurgeryDialog):
        AnaliticReportsSurgeryDialog.setWindowTitle(_translate("AnaliticReportsSurgeryDialog", "параметры отчёта", None))
        self.lblTypeSurgery.setText(_translate("AnaliticReportsSurgeryDialog", "Учет операций", None))
        self.lblOrgStructure.setText(_translate("AnaliticReportsSurgeryDialog", "&Подразделение", None))
        self.btnEventTypeList.setText(_translate("AnaliticReportsSurgeryDialog", "Тип события", None))
        self.edtBegDate.setDisplayFormat(_translate("AnaliticReportsSurgeryDialog", "dd.MM.yyyy", None))
        self.lblPerson.setText(_translate("AnaliticReportsSurgeryDialog", "Врач", None))
        self.lblEventTypeList.setText(_translate("AnaliticReportsSurgeryDialog", "  не задано", None))
        self.edtEndDate.setDisplayFormat(_translate("AnaliticReportsSurgeryDialog", "dd.MM.yyyy", None))
        self.cmbSelectType.setItemText(0, _translate("AnaliticReportsSurgeryDialog", "по врачу ответственному за действие", None))
        self.cmbSelectType.setItemText(1, _translate("AnaliticReportsSurgeryDialog", "по врачу ответственному за событие", None))
        self.lblEndDate.setText(_translate("AnaliticReportsSurgeryDialog", "Дата &окончания периода", None))
        self.cmbTypeSurgery.setItemText(0, _translate("AnaliticReportsSurgeryDialog", "Номенклатурный", None))
        self.cmbTypeSurgery.setItemText(1, _translate("AnaliticReportsSurgeryDialog", "Пользовательский", None))
        self.lblSpecialDeliverClient.setText(_translate("AnaliticReportsSurgeryDialog", "Учет экстренных пациентов", None))
        self.lblSelectType.setText(_translate("AnaliticReportsSurgeryDialog", "Выбор", None))
        self.lblBegDate.setText(_translate("AnaliticReportsSurgeryDialog", "Дата &начала периода", None))
        self.cmbSpecialDeliverClient.setItemText(0, _translate("AnaliticReportsSurgeryDialog", "не задано", None))
        self.cmbSpecialDeliverClient.setItemText(1, _translate("AnaliticReportsSurgeryDialog", "по свойству \"Доставлен по экстренным показаниям\"", None))
        self.cmbSpecialDeliverClient.setItemText(2, _translate("AnaliticReportsSurgeryDialog", "по атрибуту События \"экстренно\"", None))
        self.lblFinance.setText(_translate("AnaliticReportsSurgeryDialog", "Тип финансирования", None))
        self.chkExistFlatCode.setText(_translate("AnaliticReportsSurgeryDialog", "Учитывать только заполненный \"Код для отчётов\"", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
