# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\FinanceSummarySetupDialogOld.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FinanceSummarySetupDialogOld(object):
    def setupUi(self, FinanceSummarySetupDialogOld):
        FinanceSummarySetupDialogOld.setObjectName(_fromUtf8("FinanceSummarySetupDialogOld"))
        FinanceSummarySetupDialogOld.setWindowModality(QtCore.Qt.ApplicationModal)
        FinanceSummarySetupDialogOld.resize(514, 486)
        FinanceSummarySetupDialogOld.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(FinanceSummarySetupDialogOld)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(FinanceSummarySetupDialogOld)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 17, 0, 1, 4)
        self.cmbSpeciality = CRBComboBox(FinanceSummarySetupDialogOld)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 2, 1, 2)
        self.cmbClientOrganisation = COrgComboBox(FinanceSummarySetupDialogOld)
        self.cmbClientOrganisation.setObjectName(_fromUtf8("cmbClientOrganisation"))
        self.gridLayout.addWidget(self.cmbClientOrganisation, 5, 2, 1, 2)
        self.edtBegDate = CDateEdit(FinanceSummarySetupDialogOld)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.chkConfirmation = QtGui.QCheckBox(FinanceSummarySetupDialogOld)
        self.chkConfirmation.setObjectName(_fromUtf8("chkConfirmation"))
        self.gridLayout.addWidget(self.chkConfirmation, 11, 1, 1, 3)
        self.chkDetailService = QtGui.QCheckBox(FinanceSummarySetupDialogOld)
        self.chkDetailService.setObjectName(_fromUtf8("chkDetailService"))
        self.gridLayout.addWidget(self.chkDetailService, 8, 1, 1, 3)
        self.lblEndDate = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.lblPerson = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.edtEndDate = CDateEdit(FinanceSummarySetupDialogOld)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        self.lblInsurerDoctors = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblInsurerDoctors.setObjectName(_fromUtf8("lblInsurerDoctors"))
        self.gridLayout.addWidget(self.lblInsurerDoctors, 7, 0, 1, 1)
        self.lblRefuseType = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblRefuseType.setEnabled(False)
        self.lblRefuseType.setObjectName(_fromUtf8("lblRefuseType"))
        self.gridLayout.addWidget(self.lblRefuseType, 15, 0, 1, 1)
        self.lblConfirmationType = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblConfirmationType.setEnabled(False)
        self.lblConfirmationType.setObjectName(_fromUtf8("lblConfirmationType"))
        self.gridLayout.addWidget(self.lblConfirmationType, 12, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 2)
        self.chkDetailFedTariff = QtGui.QCheckBox(FinanceSummarySetupDialogOld)
        self.chkDetailFedTariff.setObjectName(_fromUtf8("chkDetailFedTariff"))
        self.gridLayout.addWidget(self.chkDetailFedTariff, 9, 1, 1, 3)
        self.lblSpeciality = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 2)
        self.lblClientOrganisation = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblClientOrganisation.setObjectName(_fromUtf8("lblClientOrganisation"))
        self.gridLayout.addWidget(self.lblClientOrganisation, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 16, 2, 1, 1)
        self.chkFreeInputWork = QtGui.QCheckBox(FinanceSummarySetupDialogOld)
        self.chkFreeInputWork.setObjectName(_fromUtf8("chkFreeInputWork"))
        self.gridLayout.addWidget(self.chkFreeInputWork, 6, 0, 1, 1)
        self.edtConfirmationBegDate = CDateEdit(FinanceSummarySetupDialogOld)
        self.edtConfirmationBegDate.setEnabled(False)
        self.edtConfirmationBegDate.setObjectName(_fromUtf8("edtConfirmationBegDate"))
        self.gridLayout.addWidget(self.edtConfirmationBegDate, 13, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(FinanceSummarySetupDialogOld)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 2, 1, 2)
        self.cmbPerson = CPersonComboBoxEx(FinanceSummarySetupDialogOld)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 2, 1, 2)
        self.cmbConfirmationType = QtGui.QComboBox(FinanceSummarySetupDialogOld)
        self.cmbConfirmationType.setEnabled(False)
        self.cmbConfirmationType.setObjectName(_fromUtf8("cmbConfirmationType"))
        self.gridLayout.addWidget(self.cmbConfirmationType, 12, 2, 1, 2)
        self.edtConfirmationEndDate = CDateEdit(FinanceSummarySetupDialogOld)
        self.edtConfirmationEndDate.setEnabled(False)
        self.edtConfirmationEndDate.setObjectName(_fromUtf8("edtConfirmationEndDate"))
        self.gridLayout.addWidget(self.edtConfirmationEndDate, 14, 2, 1, 1)
        self.lblEndDateConfirmation = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblEndDateConfirmation.setEnabled(False)
        self.lblEndDateConfirmation.setObjectName(_fromUtf8("lblEndDateConfirmation"))
        self.gridLayout.addWidget(self.lblEndDateConfirmation, 14, 0, 1, 1)
        self.lblBegDateConfirmation = QtGui.QLabel(FinanceSummarySetupDialogOld)
        self.lblBegDateConfirmation.setEnabled(False)
        self.lblBegDateConfirmation.setObjectName(_fromUtf8("lblBegDateConfirmation"))
        self.gridLayout.addWidget(self.lblBegDateConfirmation, 13, 0, 1, 1)
        self.cmbInsurerDoctors = CInsurerComboBox(FinanceSummarySetupDialogOld)
        self.cmbInsurerDoctors.setObjectName(_fromUtf8("cmbInsurerDoctors"))
        self.gridLayout.addWidget(self.cmbInsurerDoctors, 7, 2, 1, 2)
        self.cmbRefuseType = CRBComboBox(FinanceSummarySetupDialogOld)
        self.cmbRefuseType.setEnabled(False)
        self.cmbRefuseType.setObjectName(_fromUtf8("cmbRefuseType"))
        self.gridLayout.addWidget(self.cmbRefuseType, 15, 2, 1, 2)
        self.edtFreeInputWork = QtGui.QLineEdit(FinanceSummarySetupDialogOld)
        self.edtFreeInputWork.setEnabled(False)
        self.edtFreeInputWork.setObjectName(_fromUtf8("edtFreeInputWork"))
        self.gridLayout.addWidget(self.edtFreeInputWork, 6, 2, 1, 2)
        self.chkDetailFinance = QtGui.QCheckBox(FinanceSummarySetupDialogOld)
        self.chkDetailFinance.setObjectName(_fromUtf8("chkDetailFinance"))
        self.gridLayout.addWidget(self.chkDetailFinance, 10, 1, 1, 3)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblInsurerDoctors.setBuddy(self.cmbInsurerDoctors)
        self.lblRefuseType.setBuddy(self.cmbRefuseType)
        self.lblConfirmationType.setBuddy(self.cmbConfirmationType)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblClientOrganisation.setBuddy(self.cmbClientOrganisation)
        self.lblEndDateConfirmation.setBuddy(self.edtConfirmationEndDate)
        self.lblBegDateConfirmation.setBuddy(self.edtConfirmationBegDate)

        self.retranslateUi(FinanceSummarySetupDialogOld)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FinanceSummarySetupDialogOld.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FinanceSummarySetupDialogOld.reject)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), FinanceSummarySetupDialogOld.onStateChanged)
        QtCore.QObject.connect(self.chkFreeInputWork, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFreeInputWork.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FinanceSummarySetupDialogOld)
        FinanceSummarySetupDialogOld.setTabOrder(self.edtBegDate, self.edtEndDate)
        FinanceSummarySetupDialogOld.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbPerson, self.cmbClientOrganisation)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbClientOrganisation, self.chkFreeInputWork)
        FinanceSummarySetupDialogOld.setTabOrder(self.chkFreeInputWork, self.edtFreeInputWork)
        FinanceSummarySetupDialogOld.setTabOrder(self.edtFreeInputWork, self.cmbInsurerDoctors)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbInsurerDoctors, self.chkDetailService)
        FinanceSummarySetupDialogOld.setTabOrder(self.chkDetailService, self.chkDetailFedTariff)
        FinanceSummarySetupDialogOld.setTabOrder(self.chkDetailFedTariff, self.chkDetailFinance)
        FinanceSummarySetupDialogOld.setTabOrder(self.chkDetailFinance, self.chkConfirmation)
        FinanceSummarySetupDialogOld.setTabOrder(self.chkConfirmation, self.cmbConfirmationType)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbConfirmationType, self.edtConfirmationBegDate)
        FinanceSummarySetupDialogOld.setTabOrder(self.edtConfirmationBegDate, self.edtConfirmationEndDate)
        FinanceSummarySetupDialogOld.setTabOrder(self.edtConfirmationEndDate, self.cmbRefuseType)
        FinanceSummarySetupDialogOld.setTabOrder(self.cmbRefuseType, self.buttonBox)

    def retranslateUi(self, FinanceSummarySetupDialogOld):
        FinanceSummarySetupDialogOld.setWindowTitle(_translate("FinanceSummarySetupDialogOld", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("FinanceSummarySetupDialogOld", "Дата &начала периода", None))
        self.cmbSpeciality.setWhatsThis(_translate("FinanceSummarySetupDialogOld", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.chkConfirmation.setText(_translate("FinanceSummarySetupDialogOld", "Подтверждение оплаты", None))
        self.chkDetailService.setText(_translate("FinanceSummarySetupDialogOld", "Детализировать услуги", None))
        self.lblEndDate.setText(_translate("FinanceSummarySetupDialogOld", "Дата &окончания периода", None))
        self.lblPerson.setText(_translate("FinanceSummarySetupDialogOld", "&Врач", None))
        self.lblInsurerDoctors.setText(_translate("FinanceSummarySetupDialogOld", "Плательщик по договору", None))
        self.lblRefuseType.setText(_translate("FinanceSummarySetupDialogOld", "Причина отказа:", None))
        self.lblConfirmationType.setText(_translate("FinanceSummarySetupDialogOld", "Тип подтверждения:", None))
        self.lblOrgStructure.setText(_translate("FinanceSummarySetupDialogOld", "&Подразделение", None))
        self.chkDetailFedTariff.setText(_translate("FinanceSummarySetupDialogOld", "Детализировать федеральный тариф", None))
        self.lblSpeciality.setText(_translate("FinanceSummarySetupDialogOld", "&Специальность", None))
        self.lblClientOrganisation.setText(_translate("FinanceSummarySetupDialogOld", "Место работы", None))
        self.chkFreeInputWork.setText(_translate("FinanceSummarySetupDialogOld", "место работы по названию", None))
        self.lblEndDateConfirmation.setText(_translate("FinanceSummarySetupDialogOld", "Окончание периода подтверждения:", None))
        self.lblBegDateConfirmation.setText(_translate("FinanceSummarySetupDialogOld", "Начало периода подтверждения:", None))
        self.chkDetailFinance.setText(_translate("FinanceSummarySetupDialogOld", "Детализировать по типам финансирования", None))

from Orgs.OrgComboBox import CInsurerComboBox, COrgComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
