# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Rabota\s11\Reports\NomenclatureReportSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NomenclatureReportDialog(object):
    def setupUi(self, NomenclatureReportDialog):
        NomenclatureReportDialog.setObjectName(_fromUtf8("NomenclatureReportDialog"))
        NomenclatureReportDialog.resize(411, 635)
        self.gridLayout = QtGui.QGridLayout(NomenclatureReportDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblMonth = QtGui.QLabel(NomenclatureReportDialog)
        self.lblMonth.setObjectName(_fromUtf8("lblMonth"))
        self.gridLayout.addWidget(self.lblMonth, 0, 0, 1, 1)
        self.lblReceiverPerson = QtGui.QLabel(NomenclatureReportDialog)
        self.lblReceiverPerson.setObjectName(_fromUtf8("lblReceiverPerson"))
        self.gridLayout.addWidget(self.lblReceiverPerson, 17, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 20, 0, 1, 1)
        self.cmbSupplierOrg = COrgComboBoxEx(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierOrg.sizePolicy().hasHeightForWidth())
        self.cmbSupplierOrg.setSizePolicy(sizePolicy)
        self.cmbSupplierOrg.setObjectName(_fromUtf8("cmbSupplierOrg"))
        self.gridLayout.addWidget(self.cmbSupplierOrg, 15, 1, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(NomenclatureReportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 21, 0, 1, 4)
        self.cmbReceiver = COrgStructureComboBox(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout.addWidget(self.cmbReceiver, 16, 1, 1, 3)
        self.lblFinance = QtGui.QLabel(NomenclatureReportDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 18, 0, 1, 1)
        self.lblClientId = QtGui.QLabel(NomenclatureReportDialog)
        self.lblClientId.setObjectName(_fromUtf8("lblClientId"))
        self.gridLayout.addWidget(self.lblClientId, 7, 0, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(NomenclatureReportDialog)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 3, 2, 1, 1)
        self.lblSupplierOrg = QtGui.QLabel(NomenclatureReportDialog)
        self.lblSupplierOrg.setObjectName(_fromUtf8("lblSupplierOrg"))
        self.gridLayout.addWidget(self.lblSupplierOrg, 15, 0, 1, 1)
        self.cmbSupplier = COrgStructureComboBox(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 14, 1, 1, 3)
        self.edtClientId = QtGui.QLineEdit(NomenclatureReportDialog)
        self.edtClientId.setObjectName(_fromUtf8("edtClientId"))
        self.gridLayout.addWidget(self.edtClientId, 7, 1, 1, 3)
        self.chkEndDate = QtGui.QCheckBox(NomenclatureReportDialog)
        self.chkEndDate.setCheckable(True)
        self.chkEndDate.setChecked(False)
        self.chkEndDate.setObjectName(_fromUtf8("chkEndDate"))
        self.gridLayout.addWidget(self.chkEndDate, 6, 0, 1, 1)
        self.lblSigna = QtGui.QLabel(NomenclatureReportDialog)
        self.lblSigna.setObjectName(_fromUtf8("lblSigna"))
        self.gridLayout.addWidget(self.lblSigna, 13, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(NomenclatureReportDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 8, 1, 1, 3)
        self.edtEndDate = CDateEdit(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 3, 1, 1, 1)
        self.edtMonth = QtGui.QDateEdit(NomenclatureReportDialog)
        self.edtMonth.setCalendarPopup(True)
        self.edtMonth.setObjectName(_fromUtf8("edtMonth"))
        self.gridLayout.addWidget(self.edtMonth, 0, 1, 1, 2)
        self.lblNomenclature = QtGui.QLabel(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNomenclature.sizePolicy().hasHeightForWidth())
        self.lblNomenclature.setSizePolicy(sizePolicy)
        self.lblNomenclature.setObjectName(_fromUtf8("lblNomenclature"))
        self.gridLayout.addWidget(self.lblNomenclature, 9, 0, 1, 1)
        self.edtSigna = QtGui.QLineEdit(NomenclatureReportDialog)
        self.edtSigna.setObjectName(_fromUtf8("edtSigna"))
        self.gridLayout.addWidget(self.edtSigna, 13, 1, 1, 3)
        self.edtBegDate = CDateEdit(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 2, 1, 1, 1)
        self.cmbNomenclature = CNomenclatureComboBox(NomenclatureReportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbNomenclature.sizePolicy().hasHeightForWidth())
        self.cmbNomenclature.setSizePolicy(sizePolicy)
        self.cmbNomenclature.setObjectName(_fromUtf8("cmbNomenclature"))
        self.gridLayout.addWidget(self.cmbNomenclature, 9, 1, 1, 3)
        self.lblEndDate = QtGui.QLabel(NomenclatureReportDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 3, 0, 1, 1)
        self.cmbReceiverPerson = CPersonComboBoxEx(NomenclatureReportDialog)
        self.cmbReceiverPerson.setObjectName(_fromUtf8("cmbReceiverPerson"))
        self.gridLayout.addWidget(self.cmbReceiverPerson, 17, 1, 1, 3)
        self.edtEndDateOption = CDateEdit(NomenclatureReportDialog)
        self.edtEndDateOption.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateOption.sizePolicy().hasHeightForWidth())
        self.edtEndDateOption.setSizePolicy(sizePolicy)
        self.edtEndDateOption.setCalendarPopup(True)
        self.edtEndDateOption.setObjectName(_fromUtf8("edtEndDateOption"))
        self.gridLayout.addWidget(self.edtEndDateOption, 6, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(NomenclatureReportDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 8, 0, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(NomenclatureReportDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 2, 2, 1, 1)
        self.lblBegDate = QtGui.QLabel(NomenclatureReportDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.chkBegDate = QtGui.QCheckBox(NomenclatureReportDialog)
        self.chkBegDate.setObjectName(_fromUtf8("chkBegDate"))
        self.gridLayout.addWidget(self.chkBegDate, 5, 0, 1, 1)
        self.lblReceiver = QtGui.QLabel(NomenclatureReportDialog)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout.addWidget(self.lblReceiver, 16, 0, 1, 1)
        self.lblSupplier = QtGui.QLabel(NomenclatureReportDialog)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 14, 0, 1, 1)
        self.edtMonthOption = QtGui.QDateEdit(NomenclatureReportDialog)
        self.edtMonthOption.setEnabled(False)
        self.edtMonthOption.setCalendarPopup(True)
        self.edtMonthOption.setObjectName(_fromUtf8("edtMonthOption"))
        self.gridLayout.addWidget(self.edtMonthOption, 4, 1, 1, 1)
        self.chkMonth = QtGui.QCheckBox(NomenclatureReportDialog)
        self.chkMonth.setObjectName(_fromUtf8("chkMonth"))
        self.gridLayout.addWidget(self.chkMonth, 4, 0, 1, 1)
        self.cmbFinance = CRBComboBox(NomenclatureReportDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 18, 1, 1, 3)
        self.edtBegDateOption = CDateEdit(NomenclatureReportDialog)
        self.edtBegDateOption.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateOption.sizePolicy().hasHeightForWidth())
        self.edtBegDateOption.setSizePolicy(sizePolicy)
        self.edtBegDateOption.setCalendarPopup(True)
        self.edtBegDateOption.setObjectName(_fromUtf8("edtBegDateOption"))
        self.gridLayout.addWidget(self.edtBegDateOption, 5, 1, 1, 1)
        self.lblDatePeriod = QtGui.QLabel(NomenclatureReportDialog)
        self.lblDatePeriod.setObjectName(_fromUtf8("lblDatePeriod"))
        self.gridLayout.addWidget(self.lblDatePeriod, 1, 0, 1, 1)
        self.cmbDatePeriod = QtGui.QComboBox(NomenclatureReportDialog)
        self.cmbDatePeriod.setObjectName(_fromUtf8("cmbDatePeriod"))
        self.cmbDatePeriod.addItem(_fromUtf8(""))
        self.cmbDatePeriod.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDatePeriod, 1, 1, 1, 3)
        self.cmbNomenclatureKind = CRBComboBox(NomenclatureReportDialog)
        self.cmbNomenclatureKind.setObjectName(_fromUtf8("cmbNomenclatureKind"))
        self.gridLayout.addWidget(self.cmbNomenclatureKind, 11, 1, 1, 3)
        self.cmbNomenclatureType = CRBComboBox(NomenclatureReportDialog)
        self.cmbNomenclatureType.setObjectName(_fromUtf8("cmbNomenclatureType"))
        self.gridLayout.addWidget(self.cmbNomenclatureType, 12, 1, 1, 3)
        self.cmbNomenclatureClass = CRBComboBox(NomenclatureReportDialog)
        self.cmbNomenclatureClass.setObjectName(_fromUtf8("cmbNomenclatureClass"))
        self.gridLayout.addWidget(self.cmbNomenclatureClass, 10, 1, 1, 3)
        self.lblNomenclatureKind = QtGui.QLabel(NomenclatureReportDialog)
        self.lblNomenclatureKind.setObjectName(_fromUtf8("lblNomenclatureKind"))
        self.gridLayout.addWidget(self.lblNomenclatureKind, 11, 0, 1, 1)
        self.lblNomenclatureClass = QtGui.QLabel(NomenclatureReportDialog)
        self.lblNomenclatureClass.setObjectName(_fromUtf8("lblNomenclatureClass"))
        self.gridLayout.addWidget(self.lblNomenclatureClass, 10, 0, 1, 1)
        self.lblNomenclatureType = QtGui.QLabel(NomenclatureReportDialog)
        self.lblNomenclatureType.setObjectName(_fromUtf8("lblNomenclatureType"))
        self.gridLayout.addWidget(self.lblNomenclatureType, 12, 0, 1, 1)
        self.chkCountingTotal = QtGui.QCheckBox(NomenclatureReportDialog)
        self.chkCountingTotal.setObjectName(_fromUtf8("chkCountingTotal"))
        self.gridLayout.addWidget(self.chkCountingTotal, 19, 1, 1, 3)
        self.lblNomenclature.setBuddy(self.cmbNomenclature)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblDatePeriod.setBuddy(self.edtBegDate)

        self.retranslateUi(NomenclatureReportDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NomenclatureReportDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NomenclatureReportDialog.reject)
        QtCore.QObject.connect(self.chkMonth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMonthOption.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDateOption.setEnabled)
        QtCore.QObject.connect(self.chkEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDateOption.setEnabled)
        QtCore.QObject.connect(self.chkMonth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkBegDate.setDisabled)
        QtCore.QObject.connect(self.chkMonth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEndDate.setDisabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkMonth.setDisabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEndDate.setChecked)
        QtCore.QMetaObject.connectSlotsByName(NomenclatureReportDialog)
        NomenclatureReportDialog.setTabOrder(self.edtMonth, self.edtBegDate)
        NomenclatureReportDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        NomenclatureReportDialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        NomenclatureReportDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        NomenclatureReportDialog.setTabOrder(self.edtEndTime, self.chkMonth)
        NomenclatureReportDialog.setTabOrder(self.chkMonth, self.edtMonthOption)
        NomenclatureReportDialog.setTabOrder(self.edtMonthOption, self.chkBegDate)
        NomenclatureReportDialog.setTabOrder(self.chkBegDate, self.edtBegDateOption)
        NomenclatureReportDialog.setTabOrder(self.edtBegDateOption, self.chkEndDate)
        NomenclatureReportDialog.setTabOrder(self.chkEndDate, self.edtEndDateOption)
        NomenclatureReportDialog.setTabOrder(self.edtEndDateOption, self.edtClientId)
        NomenclatureReportDialog.setTabOrder(self.edtClientId, self.cmbOrgStructure)
        NomenclatureReportDialog.setTabOrder(self.cmbOrgStructure, self.cmbNomenclature)
        NomenclatureReportDialog.setTabOrder(self.cmbNomenclature, self.cmbNomenclatureClass)
        NomenclatureReportDialog.setTabOrder(self.cmbNomenclatureClass, self.cmbNomenclatureKind)
        NomenclatureReportDialog.setTabOrder(self.cmbNomenclatureKind, self.cmbNomenclatureType)
        NomenclatureReportDialog.setTabOrder(self.cmbNomenclatureType, self.edtSigna)
        NomenclatureReportDialog.setTabOrder(self.edtSigna, self.cmbSupplier)
        NomenclatureReportDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierOrg)
        NomenclatureReportDialog.setTabOrder(self.cmbSupplierOrg, self.cmbReceiver)
        NomenclatureReportDialog.setTabOrder(self.cmbReceiver, self.cmbFinance)
        NomenclatureReportDialog.setTabOrder(self.cmbFinance, self.chkCountingTotal)
        NomenclatureReportDialog.setTabOrder(self.chkCountingTotal, self.buttonBox)
        NomenclatureReportDialog.setTabOrder(self.buttonBox, self.cmbReceiverPerson)
        NomenclatureReportDialog.setTabOrder(self.cmbReceiverPerson, self.cmbDatePeriod)

    def retranslateUi(self, NomenclatureReportDialog):
        NomenclatureReportDialog.setWindowTitle(_translate("NomenclatureReportDialog", "Dialog", None))
        self.lblMonth.setText(_translate("NomenclatureReportDialog", "Месяц", None))
        self.lblReceiverPerson.setText(_translate("NomenclatureReportDialog", "Ответственный", None))
        self.lblFinance.setText(_translate("NomenclatureReportDialog", "Тип финанисирования", None))
        self.lblClientId.setText(_translate("NomenclatureReportDialog", "Код пациента", None))
        self.lblSupplierOrg.setText(_translate("NomenclatureReportDialog", "Внешний поставщик", None))
        self.chkEndDate.setText(_translate("NomenclatureReportDialog", "Дата окончания периода", None))
        self.lblSigna.setText(_translate("NomenclatureReportDialog", "Способ применения", None))
        self.edtMonth.setDisplayFormat(_translate("NomenclatureReportDialog", "yyyy.MM", None))
        self.lblNomenclature.setText(_translate("NomenclatureReportDialog", "Но&менклатура", None))
        self.lblEndDate.setText(_translate("NomenclatureReportDialog", "Дата &окончания периода", None))
        self.lblOrgStructure.setText(_translate("NomenclatureReportDialog", "Подразделение", None))
        self.lblBegDate.setText(_translate("NomenclatureReportDialog", "Дата &начала периода", None))
        self.chkBegDate.setText(_translate("NomenclatureReportDialog", "Дата начала периода", None))
        self.lblReceiver.setText(_translate("NomenclatureReportDialog", "Получатель", None))
        self.lblSupplier.setText(_translate("NomenclatureReportDialog", "Поставщик", None))
        self.edtMonthOption.setDisplayFormat(_translate("NomenclatureReportDialog", "yyyy.MM", None))
        self.chkMonth.setText(_translate("NomenclatureReportDialog", "Месяц", None))
        self.lblDatePeriod.setText(_translate("NomenclatureReportDialog", "Период по дате", None))
        self.cmbDatePeriod.setItemText(0, _translate("NomenclatureReportDialog", "начала госпитализации", None))
        self.cmbDatePeriod.setItemText(1, _translate("NomenclatureReportDialog", "окончания госпитализации", None))
        self.lblNomenclatureKind.setText(_translate("NomenclatureReportDialog", "Номенклатура Вид", None))
        self.lblNomenclatureClass.setText(_translate("NomenclatureReportDialog", "Номенклатура Класс", None))
        self.lblNomenclatureType.setText(_translate("NomenclatureReportDialog", "Номенклатура Тип", None))
        self.chkCountingTotal.setText(_translate("NomenclatureReportDialog", "Подсчет ИТОГО", None))

from Orgs.OrgComboBox import COrgComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Stock.NomenclatureComboBox import CNomenclatureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NomenclatureReportDialog = QtGui.QDialog()
    ui = Ui_NomenclatureReportDialog()
    ui.setupUi(NomenclatureReportDialog)
    NomenclatureReportDialog.show()
    sys.exit(app.exec_())

