# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\PreRecordUsersSetupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreRecordUsersSetupDialog(object):
    def setupUi(self, PreRecordUsersSetupDialog):
        PreRecordUsersSetupDialog.setObjectName(_fromUtf8("PreRecordUsersSetupDialog"))
        PreRecordUsersSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreRecordUsersSetupDialog.resize(447, 222)
        PreRecordUsersSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PreRecordUsersSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbPerson = CPersonComboBoxEx(PreRecordUsersSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 1, 1, 4)
        self.chkDetailCallCenter = QtGui.QCheckBox(PreRecordUsersSetupDialog)
        self.chkDetailCallCenter.setObjectName(_fromUtf8("chkDetailCallCenter"))
        self.gridLayout.addWidget(self.chkDetailCallCenter, 6, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(PreRecordUsersSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.edtBegRecordDate = CDateEdit(PreRecordUsersSetupDialog)
        self.edtBegRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegRecordDate.sizePolicy().hasHeightForWidth())
        self.edtBegRecordDate.setSizePolicy(sizePolicy)
        self.edtBegRecordDate.setCalendarPopup(True)
        self.edtBegRecordDate.setObjectName(_fromUtf8("edtBegRecordDate"))
        self.gridLayout.addWidget(self.edtBegRecordDate, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PreRecordUsersSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 5)
        self.edtBegScheduleDate = CDateEdit(PreRecordUsersSetupDialog)
        self.edtBegScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtBegScheduleDate.setSizePolicy(sizePolicy)
        self.edtBegScheduleDate.setCalendarPopup(True)
        self.edtBegScheduleDate.setObjectName(_fromUtf8("edtBegScheduleDate"))
        self.gridLayout.addWidget(self.edtBegScheduleDate, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(21, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.lblSpeciality = QtGui.QLabel(PreRecordUsersSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 1)
        self.lblEndScheduleDate = QtGui.QLabel(PreRecordUsersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.lblEndScheduleDate.setSizePolicy(sizePolicy)
        self.lblEndScheduleDate.setObjectName(_fromUtf8("lblEndScheduleDate"))
        self.gridLayout.addWidget(self.lblEndScheduleDate, 1, 2, 1, 1)
        self.lblEndRecordDate = QtGui.QLabel(PreRecordUsersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndRecordDate.sizePolicy().hasHeightForWidth())
        self.lblEndRecordDate.setSizePolicy(sizePolicy)
        self.lblEndRecordDate.setObjectName(_fromUtf8("lblEndRecordDate"))
        self.gridLayout.addWidget(self.lblEndRecordDate, 0, 2, 1, 1)
        self.chkSchedulePeriod = QtGui.QCheckBox(PreRecordUsersSetupDialog)
        self.chkSchedulePeriod.setChecked(False)
        self.chkSchedulePeriod.setObjectName(_fromUtf8("chkSchedulePeriod"))
        self.gridLayout.addWidget(self.chkSchedulePeriod, 1, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(PreRecordUsersSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 1, 1, 4)
        self.lblPerson = QtGui.QLabel(PreRecordUsersSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.edtEndRecordDate = CDateEdit(PreRecordUsersSetupDialog)
        self.edtEndRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndRecordDate.sizePolicy().hasHeightForWidth())
        self.edtEndRecordDate.setSizePolicy(sizePolicy)
        self.edtEndRecordDate.setCalendarPopup(True)
        self.edtEndRecordDate.setObjectName(_fromUtf8("edtEndRecordDate"))
        self.gridLayout.addWidget(self.edtEndRecordDate, 0, 3, 1, 2)
        self.edtEndScheduleDate = CDateEdit(PreRecordUsersSetupDialog)
        self.edtEndScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtEndScheduleDate.setSizePolicy(sizePolicy)
        self.edtEndScheduleDate.setCalendarPopup(True)
        self.edtEndScheduleDate.setObjectName(_fromUtf8("edtEndScheduleDate"))
        self.gridLayout.addWidget(self.edtEndScheduleDate, 1, 3, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(PreRecordUsersSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 4)
        self.chkRecordPeriod = QtGui.QCheckBox(PreRecordUsersSetupDialog)
        self.chkRecordPeriod.setChecked(True)
        self.chkRecordPeriod.setObjectName(_fromUtf8("chkRecordPeriod"))
        self.gridLayout.addWidget(self.chkRecordPeriod, 0, 0, 1, 1)
        self.chkSpecialityFilter = QtGui.QCheckBox(PreRecordUsersSetupDialog)
        self.chkSpecialityFilter.setObjectName(_fromUtf8("chkSpecialityFilter"))
        self.gridLayout.addWidget(self.chkSpecialityFilter, 5, 1, 1, 4)
        self.chkShowDeleted = QtGui.QCheckBox(PreRecordUsersSetupDialog)
        self.chkShowDeleted.setObjectName(_fromUtf8("chkShowDeleted"))
        self.gridLayout.addWidget(self.chkShowDeleted, 7, 1, 1, 4)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblEndRecordDate.setBuddy(self.edtEndRecordDate)
        self.lblPerson.setBuddy(self.cmbPerson)

        self.retranslateUi(PreRecordUsersSetupDialog)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegScheduleDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndScheduleDate.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreRecordUsersSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreRecordUsersSetupDialog.reject)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegScheduleDate.setFocus)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegRecordDate.setFocus)
        QtCore.QMetaObject.connectSlotsByName(PreRecordUsersSetupDialog)
        PreRecordUsersSetupDialog.setTabOrder(self.chkRecordPeriod, self.edtBegRecordDate)
        PreRecordUsersSetupDialog.setTabOrder(self.edtBegRecordDate, self.edtEndRecordDate)
        PreRecordUsersSetupDialog.setTabOrder(self.edtEndRecordDate, self.chkSchedulePeriod)
        PreRecordUsersSetupDialog.setTabOrder(self.chkSchedulePeriod, self.edtBegScheduleDate)
        PreRecordUsersSetupDialog.setTabOrder(self.edtBegScheduleDate, self.edtEndScheduleDate)
        PreRecordUsersSetupDialog.setTabOrder(self.edtEndScheduleDate, self.cmbOrgStructure)
        PreRecordUsersSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        PreRecordUsersSetupDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        PreRecordUsersSetupDialog.setTabOrder(self.cmbPerson, self.chkSpecialityFilter)
        PreRecordUsersSetupDialog.setTabOrder(self.chkSpecialityFilter, self.chkDetailCallCenter)
        PreRecordUsersSetupDialog.setTabOrder(self.chkDetailCallCenter, self.buttonBox)

    def retranslateUi(self, PreRecordUsersSetupDialog):
        PreRecordUsersSetupDialog.setWindowTitle(_translate("PreRecordUsersSetupDialog", "параметры отчёта", None))
        self.chkDetailCallCenter.setText(_translate("PreRecordUsersSetupDialog", "Детализировать Call-центр", None))
        self.lblOrgStructure.setText(_translate("PreRecordUsersSetupDialog", "&Подразделение", None))
        self.edtBegRecordDate.setDisplayFormat(_translate("PreRecordUsersSetupDialog", "dd.MM.yyyy", None))
        self.edtBegScheduleDate.setDisplayFormat(_translate("PreRecordUsersSetupDialog", "dd.MM.yyyy", None))
        self.lblSpeciality.setText(_translate("PreRecordUsersSetupDialog", "&Специальность", None))
        self.lblEndScheduleDate.setText(_translate("PreRecordUsersSetupDialog", "по", None))
        self.lblEndRecordDate.setText(_translate("PreRecordUsersSetupDialog", "по", None))
        self.chkSchedulePeriod.setText(_translate("PreRecordUsersSetupDialog", "Период планируемого приёма с", None))
        self.cmbSpeciality.setWhatsThis(_translate("PreRecordUsersSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblPerson.setText(_translate("PreRecordUsersSetupDialog", "&Врач", None))
        self.edtEndRecordDate.setDisplayFormat(_translate("PreRecordUsersSetupDialog", "dd.MM.yyyy", None))
        self.edtEndScheduleDate.setDisplayFormat(_translate("PreRecordUsersSetupDialog", "dd.MM.yyyy", None))
        self.chkRecordPeriod.setText(_translate("PreRecordUsersSetupDialog", "Период постановки в очередь с", None))
        self.chkSpecialityFilter.setText(_translate("PreRecordUsersSetupDialog", "Врачи-специалисты", None))
        self.chkShowDeleted.setText(_translate("PreRecordUsersSetupDialog", "Учитывать удаленные записи", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
