# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportMonitoredContingentSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportMonitoredContingentSetupDialog(object):
    def setupUi(self, ReportMonitoredContingentSetupDialog):
        ReportMonitoredContingentSetupDialog.setObjectName(_fromUtf8("ReportMonitoredContingentSetupDialog"))
        ReportMonitoredContingentSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportMonitoredContingentSetupDialog.resize(413, 305)
        ReportMonitoredContingentSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportMonitoredContingentSetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cmbFilterContingentType = CRBComboBox(ReportMonitoredContingentSetupDialog)
        self.cmbFilterContingentType.setObjectName(_fromUtf8("cmbFilterContingentType"))
        self.gridlayout.addWidget(self.cmbFilterContingentType, 5, 1, 1, 2)
        self.cmbSpeciality = CRBComboBox(ReportMonitoredContingentSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout.addWidget(self.cmbSpeciality, 8, 1, 1, 2)
        self.lblSpeciality = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridlayout.addWidget(self.lblSpeciality, 8, 0, 1, 1)
        self.lblFilterContingentType = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblFilterContingentType.setObjectName(_fromUtf8("lblFilterContingentType"))
        self.gridlayout.addWidget(self.lblFilterContingentType, 5, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportMonitoredContingentSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 12, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportMonitoredContingentSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.frmAge = QtGui.QFrame(ReportMonitoredContingentSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2)
        self.gridlayout.addWidget(self.frmAge, 9, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportMonitoredContingentSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 4, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportMonitoredContingentSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 13, 0, 1, 3)
        self.lblAge = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 9, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportMonitoredContingentSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridlayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.chkAttache = QtGui.QCheckBox(ReportMonitoredContingentSetupDialog)
        self.chkAttache.setChecked(True)
        self.chkAttache.setObjectName(_fromUtf8("chkAttache"))
        self.gridlayout.addWidget(self.chkAttache, 10, 1, 1, 2)
        self.lblFinance = QtGui.QLabel(ReportMonitoredContingentSetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridlayout.addWidget(self.lblFinance, 6, 0, 1, 1)
        self.cmbFinance = CRBComboBox(ReportMonitoredContingentSetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridlayout.addWidget(self.cmbFinance, 6, 1, 1, 2)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblAge.setBuddy(self.edtAgeFrom)

        self.retranslateUi(ReportMonitoredContingentSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportMonitoredContingentSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportMonitoredContingentSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportMonitoredContingentSetupDialog)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbFilterContingentType)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.cmbFilterContingentType, self.cmbFinance)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.cmbFinance, self.cmbPerson)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.cmbPerson, self.cmbSpeciality)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.cmbSpeciality, self.edtAgeFrom)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.edtAgeTo, self.chkAttache)
        ReportMonitoredContingentSetupDialog.setTabOrder(self.chkAttache, self.buttonBox)

    def retranslateUi(self, ReportMonitoredContingentSetupDialog):
        ReportMonitoredContingentSetupDialog.setWindowTitle(_translate("ReportMonitoredContingentSetupDialog", "параметры отчёта", None))
        self.lblSpeciality.setText(_translate("ReportMonitoredContingentSetupDialog", "Специальность", None))
        self.lblFilterContingentType.setText(_translate("ReportMonitoredContingentSetupDialog", "Тип контингента", None))
        self.lblBegDate.setText(_translate("ReportMonitoredContingentSetupDialog", "Дата начала периода", None))
        self.lblAgeTo.setText(_translate("ReportMonitoredContingentSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportMonitoredContingentSetupDialog", "лет", None))
        self.lblOrgStructure.setText(_translate("ReportMonitoredContingentSetupDialog", "Подразделение", None))
        self.lblEndDate.setText(_translate("ReportMonitoredContingentSetupDialog", "Дата окончания периода", None))
        self.lblAge.setText(_translate("ReportMonitoredContingentSetupDialog", "Во&зраст с", None))
        self.lblPerson.setText(_translate("ReportMonitoredContingentSetupDialog", "Врач", None))
        self.chkAttache.setText(_translate("ReportMonitoredContingentSetupDialog", "Прикрепление к ЛПУ", None))
        self.lblFinance.setText(_translate("ReportMonitoredContingentSetupDialog", "Тип финансирования", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
