# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportMedicalAidSizeByRegion.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportMedicalAidSizeByRegionDialog(object):
    def setupUi(self, ReportMedicalAidSizeByRegionDialog):
        ReportMedicalAidSizeByRegionDialog.setObjectName(_fromUtf8("ReportMedicalAidSizeByRegionDialog"))
        ReportMedicalAidSizeByRegionDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportMedicalAidSizeByRegionDialog.resize(387, 392)
        ReportMedicalAidSizeByRegionDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportMedicalAidSizeByRegionDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.buttonBox = QtGui.QDialogButtonBox(ReportMedicalAidSizeByRegionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 17, 0, 1, 3)
        self.frmAge = QtGui.QFrame(ReportMedicalAidSizeByRegionDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.gridlayout.addWidget(self.frmAge, 9, 1, 1, 2)
        self.chkIsSpecialityDetail = QtGui.QCheckBox(ReportMedicalAidSizeByRegionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkIsSpecialityDetail.sizePolicy().hasHeightForWidth())
        self.chkIsSpecialityDetail.setSizePolicy(sizePolicy)
        self.chkIsSpecialityDetail.setObjectName(_fromUtf8("chkIsSpecialityDetail"))
        self.gridlayout.addWidget(self.chkIsSpecialityDetail, 15, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ReportMedicalAidSizeByRegionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 8, 1, 1, 1)
        self.lblEventType = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridlayout.addWidget(self.lblEventType, 4, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ReportMedicalAidSizeByRegionDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridlayout.addWidget(self.cmbEventType, 4, 1, 1, 2)
        self.cmbPerson = CPersonComboBoxEx(ReportMedicalAidSizeByRegionDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportMedicalAidSizeByRegionDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 5, 1, 1, 2)
        self.edtBegDate = CDateEdit(ReportMedicalAidSizeByRegionDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblAge = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 16, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.lblSex = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 8, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.edtEndDate = CDateEdit(ReportMedicalAidSizeByRegionDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(ReportMedicalAidSizeByRegionDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout.addWidget(self.cmbSpeciality, 6, 1, 1, 2)
        self.label = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_2 = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 11, 0, 1, 1)
        self.cmbFinance = CRBComboBox(ReportMedicalAidSizeByRegionDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridlayout.addWidget(self.cmbFinance, 11, 1, 1, 2)
        self.label_3 = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 12, 0, 1, 1)
        self.cmbIsFineshedCase = QtGui.QComboBox(ReportMedicalAidSizeByRegionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbIsFineshedCase.sizePolicy().hasHeightForWidth())
        self.cmbIsFineshedCase.setSizePolicy(sizePolicy)
        self.cmbIsFineshedCase.setObjectName(_fromUtf8("cmbIsFineshedCase"))
        self.gridlayout.addWidget(self.cmbIsFineshedCase, 12, 1, 1, 2)
        self.chbIsDetail = QtGui.QCheckBox(ReportMedicalAidSizeByRegionDialog)
        self.chbIsDetail.setObjectName(_fromUtf8("chbIsDetail"))
        self.gridlayout.addWidget(self.chbIsDetail, 14, 1, 1, 1)
        self.cmbAddress = QtGui.QComboBox(ReportMedicalAidSizeByRegionDialog)
        self.cmbAddress.setObjectName(_fromUtf8("cmbAddress"))
        self.gridlayout.addWidget(self.cmbAddress, 13, 1, 1, 2)
        self.label_4 = QtGui.QLabel(ReportMedicalAidSizeByRegionDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout.addWidget(self.label_4, 13, 0, 1, 1)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEndDate.setBuddy(self.edtEndDate)

        self.retranslateUi(ReportMedicalAidSizeByRegionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportMedicalAidSizeByRegionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportMedicalAidSizeByRegionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportMedicalAidSizeByRegionDialog)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.edtEndDate, self.cmbEventType)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbPerson, self.cmbSex)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.edtAgeTo, self.cmbFinance)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbFinance, self.cmbIsFineshedCase)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbIsFineshedCase, self.cmbAddress)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.cmbAddress, self.chbIsDetail)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.chbIsDetail, self.chkIsSpecialityDetail)
        ReportMedicalAidSizeByRegionDialog.setTabOrder(self.chkIsSpecialityDetail, self.buttonBox)

    def retranslateUi(self, ReportMedicalAidSizeByRegionDialog):
        ReportMedicalAidSizeByRegionDialog.setWindowTitle(_translate("ReportMedicalAidSizeByRegionDialog", "параметры отчёта", None))
        self.lblAgeTo.setText(_translate("ReportMedicalAidSizeByRegionDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportMedicalAidSizeByRegionDialog", "лет", None))
        self.chkIsSpecialityDetail.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Детализировать по специальностям", None))
        self.lblBegDate.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Дата &начала периода", None))
        self.cmbSex.setItemText(1, _translate("ReportMedicalAidSizeByRegionDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportMedicalAidSizeByRegionDialog", "Ж", None))
        self.lblEventType.setText(_translate("ReportMedicalAidSizeByRegionDialog", "&Тип обращения", None))
        self.cmbPerson.setItemText(0, _translate("ReportMedicalAidSizeByRegionDialog", "Врач", None))
        self.lblOrgStructure.setText(_translate("ReportMedicalAidSizeByRegionDialog", "&Подразделение", None))
        self.lblAge.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Во&зраст с", None))
        self.lblPerson.setText(_translate("ReportMedicalAidSizeByRegionDialog", "&Врач", None))
        self.lblSex.setText(_translate("ReportMedicalAidSizeByRegionDialog", "По&л", None))
        self.lblEndDate.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Дата &окончания периода", None))
        self.label.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Специальность", None))
        self.label_2.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Тип финансирования", None))
        self.label_3.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Выводить по", None))
        self.chbIsDetail.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Детализировать по нас. пунктам", None))
        self.label_4.setText(_translate("ReportMedicalAidSizeByRegionDialog", "Адрес", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
