# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportPayersSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportPayersSetupDialog(object):
    def setupUi(self, ReportPayersSetupDialog):
        ReportPayersSetupDialog.setObjectName(_fromUtf8("ReportPayersSetupDialog"))
        ReportPayersSetupDialog.resize(556, 331)
        ReportPayersSetupDialog.setMinimumSize(QtCore.QSize(383, 0))
        self.gridLayout = QtGui.QGridLayout(ReportPayersSetupDialog)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbFinance = CRBComboBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFinance.sizePolicy().hasHeightForWidth())
        self.cmbFinance.setSizePolicy(sizePolicy)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 3, 1, 1, 2)
        self.chkPrintPayerResult = QtGui.QCheckBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPrintPayerResult.sizePolicy().hasHeightForWidth())
        self.chkPrintPayerResult.setSizePolicy(sizePolicy)
        self.chkPrintPayerResult.setObjectName(_fromUtf8("chkPrintPayerResult"))
        self.gridLayout.addWidget(self.chkPrintPayerResult, 9, 1, 1, 2)
        self.cmbServicesIsVAT = QtGui.QComboBox(ReportPayersSetupDialog)
        self.cmbServicesIsVAT.setObjectName(_fromUtf8("cmbServicesIsVAT"))
        self.cmbServicesIsVAT.addItem(_fromUtf8(""))
        self.cmbServicesIsVAT.addItem(_fromUtf8(""))
        self.cmbServicesIsVAT.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbServicesIsVAT, 11, 1, 1, 2)
        self.chkIsVAT = QtGui.QCheckBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkIsVAT.sizePolicy().hasHeightForWidth())
        self.chkIsVAT.setSizePolicy(sizePolicy)
        self.chkIsVAT.setObjectName(_fromUtf8("chkIsVAT"))
        self.gridLayout.addWidget(self.chkIsVAT, 12, 1, 1, 2)
        self.lblServicesIsVAT = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblServicesIsVAT.setObjectName(_fromUtf8("lblServicesIsVAT"))
        self.gridLayout.addWidget(self.lblServicesIsVAT, 11, 0, 1, 1)
        self.chkDetailContracts = QtGui.QCheckBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDetailContracts.sizePolicy().hasHeightForWidth())
        self.chkDetailContracts.setSizePolicy(sizePolicy)
        self.chkDetailContracts.setObjectName(_fromUtf8("chkDetailContracts"))
        self.gridLayout.addWidget(self.chkDetailContracts, 4, 1, 1, 2)
        self.lblClientOrganisation = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblClientOrganisation.setObjectName(_fromUtf8("lblClientOrganisation"))
        self.gridLayout.addWidget(self.lblClientOrganisation, 6, 0, 1, 1)
        self.lblContract = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 5, 0, 1, 1)
        self.lblInsurer = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblInsurer.setObjectName(_fromUtf8("lblInsurer"))
        self.gridLayout.addWidget(self.lblInsurer, 8, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 3, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.edtEndDate = CDateEdit(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.chkFreeInputWork = QtGui.QCheckBox(ReportPayersSetupDialog)
        self.chkFreeInputWork.setObjectName(_fromUtf8("chkFreeInputWork"))
        self.gridLayout.addWidget(self.chkFreeInputWork, 7, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ReportPayersSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 2)
        self.cmbContract = CIndependentContractComboBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbContract.sizePolicy().hasHeightForWidth())
        self.cmbContract.setSizePolicy(sizePolicy)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 5, 1, 1, 2)
        self.cmbInsurer = CInsurerComboBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbInsurer.sizePolicy().hasHeightForWidth())
        self.cmbInsurer.setSizePolicy(sizePolicy)
        self.cmbInsurer.setObjectName(_fromUtf8("cmbInsurer"))
        self.gridLayout.addWidget(self.cmbInsurer, 8, 1, 1, 2)
        self.cmbClientOrganisation = COrgComboBox(ReportPayersSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientOrganisation.sizePolicy().hasHeightForWidth())
        self.cmbClientOrganisation.setSizePolicy(sizePolicy)
        self.cmbClientOrganisation.setObjectName(_fromUtf8("cmbClientOrganisation"))
        self.gridLayout.addWidget(self.cmbClientOrganisation, 6, 1, 1, 2)
        self.edtFreeInputWork = QtGui.QLineEdit(ReportPayersSetupDialog)
        self.edtFreeInputWork.setObjectName(_fromUtf8("edtFreeInputWork"))
        self.gridLayout.addWidget(self.edtFreeInputWork, 7, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(368, 96, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(ReportPayersSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)

        self.retranslateUi(ReportPayersSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportPayersSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportPayersSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportPayersSetupDialog)
        ReportPayersSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportPayersSetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        ReportPayersSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbFinance)
        ReportPayersSetupDialog.setTabOrder(self.cmbFinance, self.chkDetailContracts)
        ReportPayersSetupDialog.setTabOrder(self.chkDetailContracts, self.cmbContract)
        ReportPayersSetupDialog.setTabOrder(self.cmbContract, self.cmbClientOrganisation)
        ReportPayersSetupDialog.setTabOrder(self.cmbClientOrganisation, self.chkFreeInputWork)
        ReportPayersSetupDialog.setTabOrder(self.chkFreeInputWork, self.edtFreeInputWork)
        ReportPayersSetupDialog.setTabOrder(self.edtFreeInputWork, self.cmbInsurer)
        ReportPayersSetupDialog.setTabOrder(self.cmbInsurer, self.chkPrintPayerResult)
        ReportPayersSetupDialog.setTabOrder(self.chkPrintPayerResult, self.cmbServicesIsVAT)
        ReportPayersSetupDialog.setTabOrder(self.cmbServicesIsVAT, self.chkIsVAT)
        ReportPayersSetupDialog.setTabOrder(self.chkIsVAT, self.buttonBox)

    def retranslateUi(self, ReportPayersSetupDialog):
        self.chkPrintPayerResult.setText(_translate("ReportPayersSetupDialog", "Выводить итоги по плательщику", None))
        self.cmbServicesIsVAT.setItemText(0, _translate("ReportPayersSetupDialog", "не задано", None))
        self.cmbServicesIsVAT.setItemText(1, _translate("ReportPayersSetupDialog", "без НДС", None))
        self.cmbServicesIsVAT.setItemText(2, _translate("ReportPayersSetupDialog", "с НДС", None))
        self.chkIsVAT.setText(_translate("ReportPayersSetupDialog", "Выводить колонку  НДС", None))
        self.lblServicesIsVAT.setText(_translate("ReportPayersSetupDialog", "Услуги и НДС", None))
        self.chkDetailContracts.setText(_translate("ReportPayersSetupDialog", "Детализировать по договорам", None))
        self.lblClientOrganisation.setText(_translate("ReportPayersSetupDialog", "Место работы", None))
        self.lblContract.setText(_translate("ReportPayersSetupDialog", "Договор", None))
        self.lblInsurer.setText(_translate("ReportPayersSetupDialog", "Плательщик по договору", None))
        self.lblBegDate.setText(_translate("ReportPayersSetupDialog", "Дата &начала периода", None))
        self.lblFinance.setText(_translate("ReportPayersSetupDialog", "Тип финансирования", None))
        self.edtBegDate.setDisplayFormat(_translate("ReportPayersSetupDialog", "dd.MM.yyyy", None))
        self.edtEndDate.setDisplayFormat(_translate("ReportPayersSetupDialog", "dd.MM.yyyy", None))
        self.lblEndDate.setText(_translate("ReportPayersSetupDialog", "Дата &окончания периода", None))
        self.chkFreeInputWork.setText(_translate("ReportPayersSetupDialog", "место работы по названию", None))
        self.lblOrgStructure.setText(_translate("ReportPayersSetupDialog", "Подразделение", None))

from Orgs.OrgComboBox import CIndependentContractComboBox, CInsurerComboBox, COrgComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
