# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportPGGSetup.ui'
#
# Created: Thu Nov 29 16:03:32 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReportPGGSetupDialog(object):
    def setupUi(self, ReportPGGSetupDialog):
        ReportPGGSetupDialog.setObjectName(_fromUtf8("ReportPGGSetupDialog"))
        ReportPGGSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportPGGSetupDialog.resize(474, 426)
        ReportPGGSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportPGGSetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportPGGSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 17, 0, 1, 3)
        self.frmAge = QtGui.QFrame(ReportPGGSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setSpacing(4)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem1)
        self.gridlayout.addWidget(self.frmAge, 11, 1, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportPGGSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 7, 1, 1, 2)
        self.lblAge = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 11, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ReportPGGSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridlayout.addWidget(self.cmbEventType, 6, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ReportPGGSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setMinimumContentsLength(0)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 9, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 7, 0, 1, 1)
        self.edtBegDate = CDateEdit(ReportPGGSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.cmbEventPurpose = CRBComboBox(ReportPGGSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridlayout.addWidget(self.cmbEventPurpose, 3, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 8, 0, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridlayout.addWidget(self.lblEventPurpose, 3, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportPGGSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblSex = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 9, 0, 1, 1)
        self.lblEventType = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridlayout.addWidget(self.lblEventType, 6, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportPGGSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 8, 1, 1, 2)
        self.lblBegDate = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.chbIncludeHoliday = QtGui.QCheckBox(ReportPGGSetupDialog)
        self.chbIncludeHoliday.setEnabled(False)
        self.chbIncludeHoliday.setObjectName(_fromUtf8("chbIncludeHoliday"))
        self.gridlayout.addWidget(self.chbIncludeHoliday, 2, 1, 1, 2)
        self.cmbSpeciality = CRBComboBox(ReportPGGSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout.addWidget(self.cmbSpeciality, 10, 1, 1, 2)
        self.lblSpecilaty = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblSpecilaty.setObjectName(_fromUtf8("lblSpecilaty"))
        self.gridlayout.addWidget(self.lblSpecilaty, 10, 0, 1, 1)
        self.cmbFinanceId = CRBComboBox(ReportPGGSetupDialog)
        self.cmbFinanceId.setObjectName(_fromUtf8("cmbFinanceId"))
        self.gridlayout.addWidget(self.cmbFinanceId, 13, 1, 1, 2)
        self.lblFinanceType = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblFinanceType.setObjectName(_fromUtf8("lblFinanceType"))
        self.gridlayout.addWidget(self.lblFinanceType, 13, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 15, 2, 1, 1)
        self.cmbColumnBy = QtGui.QComboBox(ReportPGGSetupDialog)
        self.cmbColumnBy.setEnabled(True)
        self.cmbColumnBy.setObjectName(_fromUtf8("cmbColumnBy"))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.setItemText(0, _fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.cmbColumnBy.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbColumnBy, 14, 1, 1, 2)
        self.lblColumnBy = QtGui.QLabel(ReportPGGSetupDialog)
        self.lblColumnBy.setEnabled(True)
        self.lblColumnBy.setObjectName(_fromUtf8("lblColumnBy"))
        self.gridlayout.addWidget(self.lblColumnBy, 14, 0, 1, 1)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(ReportPGGSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportPGGSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportPGGSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportPGGSetupDialog)
        ReportPGGSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportPGGSetupDialog.setTabOrder(self.edtEndDate, self.chbIncludeHoliday)
        ReportPGGSetupDialog.setTabOrder(self.chbIncludeHoliday, self.cmbEventPurpose)
        ReportPGGSetupDialog.setTabOrder(self.cmbEventPurpose, self.cmbEventType)
        ReportPGGSetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportPGGSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ReportPGGSetupDialog.setTabOrder(self.cmbPerson, self.cmbSex)
        ReportPGGSetupDialog.setTabOrder(self.cmbSex, self.cmbSpeciality)
        ReportPGGSetupDialog.setTabOrder(self.cmbSpeciality, self.edtAgeFrom)
        ReportPGGSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportPGGSetupDialog.setTabOrder(self.edtAgeTo, self.buttonBox)

    def retranslateUi(self, ReportPGGSetupDialog):
        ReportPGGSetupDialog.setWindowTitle(QtGui.QApplication.translate("ReportPGGSetupDialog", "параметры отчёта", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeTo.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeYears.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "лет", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAge.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Возраст с", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Дата &окончания периода", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(1, QtGui.QApplication.translate("ReportPGGSetupDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(2, QtGui.QApplication.translate("ReportPGGSetupDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOrgStructure.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "&Подразделение", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerson.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "&Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventPurpose.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "&Назначение обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSex.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "По&л", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEventType.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "&Тип обращения", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPerson.setItemText(0, QtGui.QApplication.translate("ReportPGGSetupDialog", "Врач", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBegDate.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Дата &начала периода", None, QtGui.QApplication.UnicodeUTF8))
        self.chbIncludeHoliday.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Включать выходные", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpecilaty.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Специальность", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFinanceType.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Тип финансирования", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(1, QtGui.QApplication.translate("ReportPGGSetupDialog", "Страховым", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(2, QtGui.QApplication.translate("ReportPGGSetupDialog", "Врачам", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(3, QtGui.QApplication.translate("ReportPGGSetupDialog", "Специальностям", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(4, QtGui.QApplication.translate("ReportPGGSetupDialog", "По группам услуг", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(5, QtGui.QApplication.translate("ReportPGGSetupDialog", "По услуге", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbColumnBy.setItemText(6, QtGui.QApplication.translate("ReportPGGSetupDialog", "По специальностям и страховым", None, QtGui.QApplication.UnicodeUTF8))
        self.lblColumnBy.setText(QtGui.QApplication.translate("ReportPGGSetupDialog", "Столбцы по", None, QtGui.QApplication.UnicodeUTF8))

from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
