# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportF30Setup.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportF30SetupDialog(object):
    def setupUi(self, ReportF30SetupDialog):
        ReportF30SetupDialog.setObjectName(_fromUtf8("ReportF30SetupDialog"))
        ReportF30SetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportF30SetupDialog.resize(517, 703)
        ReportF30SetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportF30SetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.grpUseInputDate = QtGui.QGroupBox(ReportF30SetupDialog)
        self.grpUseInputDate.setCheckable(True)
        self.grpUseInputDate.setChecked(False)
        self.grpUseInputDate.setObjectName(_fromUtf8("grpUseInputDate"))
        self.gridLayout = QtGui.QGridLayout(self.grpUseInputDate)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtBegInputDate = CDateEdit(self.grpUseInputDate)
        self.edtBegInputDate.setCalendarPopup(True)
        self.edtBegInputDate.setObjectName(_fromUtf8("edtBegInputDate"))
        self.gridLayout.addWidget(self.edtBegInputDate, 0, 1, 1, 1)
        self.lblBegInputDate = QtGui.QLabel(self.grpUseInputDate)
        self.lblBegInputDate.setObjectName(_fromUtf8("lblBegInputDate"))
        self.gridLayout.addWidget(self.lblBegInputDate, 0, 0, 1, 1)
        self.lblEndInputDate = QtGui.QLabel(self.grpUseInputDate)
        self.lblEndInputDate.setObjectName(_fromUtf8("lblEndInputDate"))
        self.gridLayout.addWidget(self.lblEndInputDate, 1, 0, 1, 1)
        self.edtEndInputDate = CDateEdit(self.grpUseInputDate)
        self.edtEndInputDate.setCalendarPopup(True)
        self.edtEndInputDate.setObjectName(_fromUtf8("edtEndInputDate"))
        self.gridLayout.addWidget(self.edtEndInputDate, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(80, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridlayout.addWidget(self.grpUseInputDate, 2, 0, 1, 3)
        self.frmAge = QtGui.QFrame(ReportF30SetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2)
        self.gridlayout.addWidget(self.frmAge, 16, 1, 1, 2)
        self.lblTypeFinance = QtGui.QLabel(ReportF30SetupDialog)
        self.lblTypeFinance.setObjectName(_fromUtf8("lblTypeFinance"))
        self.gridlayout.addWidget(self.lblTypeFinance, 20, 0, 1, 1)
        self.lblSex = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 15, 0, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridlayout.addWidget(self.lblEventPurpose, 8, 0, 1, 1)
        self.lblVisitPayStatus = QtGui.QLabel(ReportF30SetupDialog)
        self.lblVisitPayStatus.setObjectName(_fromUtf8("lblVisitPayStatus"))
        self.gridlayout.addWidget(self.lblVisitPayStatus, 22, 0, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridlayout.addWidget(self.lblSocStatusClass, 17, 0, 1, 1)
        self.cmbTariff = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbTariff.setObjectName(_fromUtf8("cmbTariff"))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.cmbTariff.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbTariff, 21, 1, 1, 2)
        self.lblTariff = QtGui.QLabel(ReportF30SetupDialog)
        self.lblTariff.setObjectName(_fromUtf8("lblTariff"))
        self.gridlayout.addWidget(self.lblTariff, 21, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportF30SetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 27, 0, 1, 3)
        self.lblAge = QtGui.QLabel(ReportF30SetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 16, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportF30SetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 26, 0, 1, 1)
        self.chkVisitHospital = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkVisitHospital.setObjectName(_fromUtf8("chkVisitHospital"))
        self.gridlayout.addWidget(self.chkVisitHospital, 6, 1, 1, 2)
        self.chkAmbulator = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkAmbulator.setChecked(True)
        self.chkAmbulator.setObjectName(_fromUtf8("chkAmbulator"))
        self.gridlayout.addWidget(self.chkAmbulator, 7, 1, 1, 2)
        self.cmbSocStatusClass = CSocStatusComboBox(ReportF30SetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridlayout.addWidget(self.cmbSocStatusClass, 17, 1, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportF30SetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 12, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblScene = QtGui.QLabel(ReportF30SetupDialog)
        self.lblScene.setObjectName(_fromUtf8("lblScene"))
        self.gridlayout.addWidget(self.lblScene, 14, 0, 1, 1)
        self.cmbScene = CRBComboBox(ReportF30SetupDialog)
        self.cmbScene.setObjectName(_fromUtf8("cmbScene"))
        self.gridlayout.addWidget(self.cmbScene, 14, 1, 1, 2)
        self.btnEventTypeList = QtGui.QPushButton(ReportF30SetupDialog)
        self.btnEventTypeList.setObjectName(_fromUtf8("btnEventTypeList"))
        self.gridlayout.addWidget(self.btnEventTypeList, 9, 0, 1, 1)
        self.lblEventTypeList = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEventTypeList.setWordWrap(True)
        self.lblEventTypeList.setObjectName(_fromUtf8("lblEventTypeList"))
        self.gridlayout.addWidget(self.lblEventTypeList, 9, 1, 1, 2)
        self.btnSpecialityList = QtGui.QPushButton(ReportF30SetupDialog)
        self.btnSpecialityList.setObjectName(_fromUtf8("btnSpecialityList"))
        self.gridlayout.addWidget(self.btnSpecialityList, 13, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ReportF30SetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 12, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridlayout.addWidget(self.lblSocStatusType, 18, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ReportF30SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 15, 1, 1, 1)
        self.chkDetailChildren = QtGui.QCheckBox(ReportF30SetupDialog)
        self.chkDetailChildren.setObjectName(_fromUtf8("chkDetailChildren"))
        self.gridlayout.addWidget(self.chkDetailChildren, 5, 1, 1, 2)
        self.cmbVisitPayStatus = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbVisitPayStatus.setObjectName(_fromUtf8("cmbVisitPayStatus"))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.cmbVisitPayStatus.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbVisitPayStatus, 22, 1, 1, 2)
        self.cmbEventPurpose = CRBComboBox(ReportF30SetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridlayout.addWidget(self.cmbEventPurpose, 8, 1, 1, 2)
        self.lblIsEventClosed = QtGui.QLabel(ReportF30SetupDialog)
        self.lblIsEventClosed.setObjectName(_fromUtf8("lblIsEventClosed"))
        self.gridlayout.addWidget(self.lblIsEventClosed, 24, 0, 1, 1)
        self.cmbIsEventClosed = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbIsEventClosed.setObjectName(_fromUtf8("cmbIsEventClosed"))
        self.cmbIsEventClosed.addItem(_fromUtf8(""))
        self.cmbIsEventClosed.addItem(_fromUtf8(""))
        self.cmbIsEventClosed.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbIsEventClosed, 24, 1, 1, 2)
        self.lblSpecialityList = QtGui.QLabel(ReportF30SetupDialog)
        self.lblSpecialityList.setWordWrap(True)
        self.lblSpecialityList.setObjectName(_fromUtf8("lblSpecialityList"))
        self.gridlayout.addWidget(self.lblSpecialityList, 13, 1, 1, 2)
        self.edtEndDate = CDateEdit(ReportF30SetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.cmbEventType = CRBComboBox(ReportF30SetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridlayout.addWidget(self.cmbEventType, 11, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.cmbTypeFinance = CRBComboBox(ReportF30SetupDialog)
        self.cmbTypeFinance.setObjectName(_fromUtf8("cmbTypeFinance"))
        self.gridlayout.addWidget(self.cmbTypeFinance, 20, 1, 1, 2)
        self.cmbGrouping = QtGui.QComboBox(ReportF30SetupDialog)
        self.cmbGrouping.setObjectName(_fromUtf8("cmbGrouping"))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.cmbGrouping.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbGrouping, 23, 1, 1, 2)
        self.lblEventType = QtGui.QLabel(ReportF30SetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridlayout.addWidget(self.lblEventType, 11, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(ReportF30SetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridlayout.addWidget(self.cmbSocStatusType, 18, 1, 1, 2)
        self.edtBegDate = CDateEdit(ReportF30SetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblGrouping = QtGui.QLabel(ReportF30SetupDialog)
        self.lblGrouping.setObjectName(_fromUtf8("lblGrouping"))
        self.gridlayout.addWidget(self.lblGrouping, 23, 0, 1, 1)
        self.btnContingentTypeList = QtGui.QPushButton(ReportF30SetupDialog)
        self.btnContingentTypeList.setObjectName(_fromUtf8("btnContingentTypeList"))
        self.gridlayout.addWidget(self.btnContingentTypeList, 25, 0, 1, 1)
        self.lblContingentTypeList = QtGui.QLabel(ReportF30SetupDialog)
        self.lblContingentTypeList.setWordWrap(True)
        self.lblContingentTypeList.setObjectName(_fromUtf8("lblContingentTypeList"))
        self.gridlayout.addWidget(self.lblContingentTypeList, 25, 1, 1, 2)
        self.lblBegInputDate.setBuddy(self.edtBegInputDate)
        self.lblEndInputDate.setBuddy(self.edtEndInputDate)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblEventType.setBuddy(self.cmbEventType)

        self.retranslateUi(ReportF30SetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportF30SetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportF30SetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportF30SetupDialog)
        ReportF30SetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportF30SetupDialog.setTabOrder(self.edtEndDate, self.chkDetailChildren)
        ReportF30SetupDialog.setTabOrder(self.chkDetailChildren, self.chkVisitHospital)
        ReportF30SetupDialog.setTabOrder(self.chkVisitHospital, self.chkAmbulator)
        ReportF30SetupDialog.setTabOrder(self.chkAmbulator, self.cmbEventPurpose)
        ReportF30SetupDialog.setTabOrder(self.cmbEventPurpose, self.btnEventTypeList)
        ReportF30SetupDialog.setTabOrder(self.btnEventTypeList, self.cmbEventType)
        ReportF30SetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportF30SetupDialog.setTabOrder(self.cmbOrgStructure, self.btnSpecialityList)
        ReportF30SetupDialog.setTabOrder(self.btnSpecialityList, self.cmbScene)
        ReportF30SetupDialog.setTabOrder(self.cmbScene, self.cmbSex)
        ReportF30SetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportF30SetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportF30SetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        ReportF30SetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        ReportF30SetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbTypeFinance)
        ReportF30SetupDialog.setTabOrder(self.cmbTypeFinance, self.cmbTariff)
        ReportF30SetupDialog.setTabOrder(self.cmbTariff, self.cmbVisitPayStatus)
        ReportF30SetupDialog.setTabOrder(self.cmbVisitPayStatus, self.cmbGrouping)
        ReportF30SetupDialog.setTabOrder(self.cmbGrouping, self.cmbIsEventClosed)
        ReportF30SetupDialog.setTabOrder(self.cmbIsEventClosed, self.buttonBox)

    def retranslateUi(self, ReportF30SetupDialog):
        ReportF30SetupDialog.setWindowTitle(_translate("ReportF30SetupDialog", "параметры отчёта", None))
        self.grpUseInputDate.setTitle(_translate("ReportF30SetupDialog", "Использовать дату ввода", None))
        self.lblBegInputDate.setText(_translate("ReportF30SetupDialog", "Минимальная дата ввода", None))
        self.lblEndInputDate.setText(_translate("ReportF30SetupDialog", "Максимальная дата ввода", None))
        self.lblAgeTo.setText(_translate("ReportF30SetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportF30SetupDialog", "лет", None))
        self.lblTypeFinance.setText(_translate("ReportF30SetupDialog", "Тип финансирования", None))
        self.lblSex.setText(_translate("ReportF30SetupDialog", "По&л", None))
        self.lblEventPurpose.setText(_translate("ReportF30SetupDialog", "&Назначение обращения", None))
        self.lblVisitPayStatus.setText(_translate("ReportF30SetupDialog", "Флаг финансирования", None))
        self.lblSocStatusClass.setText(_translate("ReportF30SetupDialog", "Класс соц.статуса", None))
        self.cmbTariff.setItemText(0, _translate("ReportF30SetupDialog", "не учитывать", None))
        self.cmbTariff.setItemText(1, _translate("ReportF30SetupDialog", "тарифицированные", None))
        self.cmbTariff.setItemText(2, _translate("ReportF30SetupDialog", "не тарифицированные", None))
        self.lblTariff.setText(_translate("ReportF30SetupDialog", "Тарификация", None))
        self.lblAge.setText(_translate("ReportF30SetupDialog", "Во&зраст с", None))
        self.lblBegDate.setText(_translate("ReportF30SetupDialog", "Дата начала периода", None))
        self.chkVisitHospital.setText(_translate("ReportF30SetupDialog", "Учитывать посещения ДС", None))
        self.chkAmbulator.setText(_translate("ReportF30SetupDialog", "Выделить амбулаторные визиты", None))
        self.lblEndDate.setText(_translate("ReportF30SetupDialog", "Дата окончания периода", None))
        self.lblScene.setText(_translate("ReportF30SetupDialog", "Место посещения", None))
        self.btnEventTypeList.setText(_translate("ReportF30SetupDialog", "Тип обращения", None))
        self.lblEventTypeList.setText(_translate("ReportF30SetupDialog", "Не задано", None))
        self.btnSpecialityList.setText(_translate("ReportF30SetupDialog", "Специальность", None))
        self.lblOrgStructure.setText(_translate("ReportF30SetupDialog", "Подразделение", None))
        self.lblSocStatusType.setText(_translate("ReportF30SetupDialog", "Тип соц.статуса", None))
        self.cmbSex.setItemText(1, _translate("ReportF30SetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportF30SetupDialog", "Ж", None))
        self.chkDetailChildren.setText(_translate("ReportF30SetupDialog", "Детализация по подросткам", None))
        self.cmbVisitPayStatus.setItemText(0, _translate("ReportF30SetupDialog", "не задано", None))
        self.cmbVisitPayStatus.setItemText(1, _translate("ReportF30SetupDialog", "не выставлено", None))
        self.cmbVisitPayStatus.setItemText(2, _translate("ReportF30SetupDialog", "выставлено", None))
        self.cmbVisitPayStatus.setItemText(3, _translate("ReportF30SetupDialog", "отказано", None))
        self.cmbVisitPayStatus.setItemText(4, _translate("ReportF30SetupDialog", "оплачено", None))
        self.lblIsEventClosed.setText(_translate("ReportF30SetupDialog", "Закрытие события", None))
        self.cmbIsEventClosed.setItemText(0, _translate("ReportF30SetupDialog", "не учитывать", None))
        self.cmbIsEventClosed.setItemText(1, _translate("ReportF30SetupDialog", "только завершённые", None))
        self.cmbIsEventClosed.setItemText(2, _translate("ReportF30SetupDialog", "только незавершённые", None))
        self.lblSpecialityList.setText(_translate("ReportF30SetupDialog", "Не задано", None))
        self.cmbGrouping.setItemText(0, _translate("ReportF30SetupDialog", "по специальности", None))
        self.cmbGrouping.setItemText(1, _translate("ReportF30SetupDialog", "по должности", None))
        self.cmbGrouping.setItemText(2, _translate("ReportF30SetupDialog", "по профилю оплаты", None))
        self.cmbGrouping.setItemText(3, _translate("ReportF30SetupDialog", "по страховым", None))
        self.lblEventType.setText(_translate("ReportF30SetupDialog", "&Тип обращения", None))
        self.lblGrouping.setText(_translate("ReportF30SetupDialog", "Группировка", None))
        self.btnContingentTypeList.setText(_translate("ReportF30SetupDialog", "Наблюдаемый контингент", None))
        self.lblContingentTypeList.setText(_translate("ReportF30SetupDialog", "Не задано", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReportF30SetupDialog = QtGui.QDialog()
    ui = Ui_ReportF30SetupDialog()
    ui.setupUi(ReportF30SetupDialog)
    ReportF30SetupDialog.show()
    sys.exit(app.exec_())

