# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportExternalDirectionsSetupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExternalDirectionsReportSetupDialog(object):
    def setupUi(self, ExternalDirectionsReportSetupDialog):
        ExternalDirectionsReportSetupDialog.setObjectName(_fromUtf8("ExternalDirectionsReportSetupDialog"))
        ExternalDirectionsReportSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ExternalDirectionsReportSetupDialog.resize(458, 380)
        ExternalDirectionsReportSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ExternalDirectionsReportSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.lblBegDate = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        self.lblOrganisation = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout.addWidget(self.lblOrganisation, 6, 0, 1, 2)
        self.edtBegTime = QtGui.QTimeEdit(ExternalDirectionsReportSetupDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 3, 1, 1)
        self.lblPerson = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 5, 0, 1, 2)
        self.lblActionType = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 2, 0, 1, 2)
        self.chkSortFIO = QtGui.QCheckBox(ExternalDirectionsReportSetupDialog)
        self.chkSortFIO.setObjectName(_fromUtf8("chkSortFIO"))
        self.gridLayout.addWidget(self.chkSortFIO, 8, 2, 1, 3)
        self.chkDetalLPU = QtGui.QCheckBox(ExternalDirectionsReportSetupDialog)
        self.chkDetalLPU.setChecked(True)
        self.chkDetalLPU.setObjectName(_fromUtf8("chkDetalLPU"))
        self.gridLayout.addWidget(self.chkDetalLPU, 7, 2, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.edtEndDate = CDateEdit(ExternalDirectionsReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setMinimumSize(QtCore.QSize(95, 0))
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 4, 0, 1, 2)
        self.edtBegDate = CDateEdit(ExternalDirectionsReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setMinimumSize(QtCore.QSize(95, 0))
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.cmbPerson = CPersonComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 5, 2, 1, 3)
        self.cmbOrgStructure = COrgStructureComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 4, 2, 1, 3)
        self.cmbActionType = QtGui.QComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 2, 2, 1, 3)
        self.cmbOrganisation = COrgIsMedicalComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout.addWidget(self.cmbOrganisation, 6, 2, 1, 3)
        self.lblEndDate = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.lblActionStatus = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblActionStatus.setObjectName(_fromUtf8("lblActionStatus"))
        self.gridLayout.addWidget(self.lblActionStatus, 3, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ExternalDirectionsReportSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 0, 1, 5)
        self.cmbActionStatus = CActionStatusComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbActionStatus.setObjectName(_fromUtf8("cmbActionStatus"))
        self.gridLayout.addWidget(self.cmbActionStatus, 3, 2, 1, 3)
        self.edtEndTime = QtGui.QTimeEdit(ExternalDirectionsReportSetupDialog)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 3, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.edtMKBTo = CICDCodeEdit(ExternalDirectionsReportSetupDialog)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout_4.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(ExternalDirectionsReportSetupDialog)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout_4.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.cmbMKBFilter = QtGui.QComboBox(ExternalDirectionsReportSetupDialog)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 11, 2, 1, 3)
        self.lblAge = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 10, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.edtAgeFrom = QtGui.QSpinBox(ExternalDirectionsReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.gridLayout_5.addWidget(self.edtAgeFrom, 0, 0, 1, 1)
        self.lblAgeTo = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeTo.sizePolicy().hasHeightForWidth())
        self.lblAgeTo.setSizePolicy(sizePolicy)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.gridLayout_5.addWidget(self.lblAgeTo, 0, 1, 1, 1)
        self.edtAgeTo = QtGui.QSpinBox(ExternalDirectionsReportSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.gridLayout_5.addWidget(self.edtAgeTo, 0, 2, 1, 1)
        self.lblAgeYears = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.gridLayout_5.addWidget(self.lblAgeYears, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 10, 2, 1, 3)
        self.lblMKBFilter = QtGui.QLabel(ExternalDirectionsReportSetupDialog)
        self.lblMKBFilter.setObjectName(_fromUtf8("lblMKBFilter"))
        self.gridLayout.addWidget(self.lblMKBFilter, 11, 1, 1, 1)
        self.chkCalculationNotes = QtGui.QCheckBox(ExternalDirectionsReportSetupDialog)
        self.chkCalculationNotes.setObjectName(_fromUtf8("chkCalculationNotes"))
        self.gridLayout.addWidget(self.chkCalculationNotes, 9, 2, 1, 3)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblMKBFilter.setBuddy(self.cmbMKBFilter)

        self.retranslateUi(ExternalDirectionsReportSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ExternalDirectionsReportSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ExternalDirectionsReportSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExternalDirectionsReportSetupDialog)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtEndTime, self.cmbActionType)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbActionType, self.cmbActionStatus)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbActionStatus, self.cmbOrgStructure)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbPerson, self.cmbOrganisation)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbOrganisation, self.chkDetalLPU)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.chkDetalLPU, self.chkSortFIO)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.chkSortFIO, self.chkCalculationNotes)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.chkCalculationNotes, self.edtAgeFrom)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtAgeTo, self.cmbMKBFilter)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        ExternalDirectionsReportSetupDialog.setTabOrder(self.edtMKBTo, self.buttonBox)

    def retranslateUi(self, ExternalDirectionsReportSetupDialog):
        ExternalDirectionsReportSetupDialog.setWindowTitle(_translate("ExternalDirectionsReportSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("ExternalDirectionsReportSetupDialog", "Дата &начала периода", None))
        self.lblOrganisation.setText(_translate("ExternalDirectionsReportSetupDialog", "&Целевое ЛПУ", None))
        self.lblPerson.setText(_translate("ExternalDirectionsReportSetupDialog", "Направитель", None))
        self.lblActionType.setText(_translate("ExternalDirectionsReportSetupDialog", "Тип направления", None))
        self.chkSortFIO.setText(_translate("ExternalDirectionsReportSetupDialog", "Сортировать по ФИО", None))
        self.chkDetalLPU.setText(_translate("ExternalDirectionsReportSetupDialog", "Детализировать по Целевым ЛПУ", None))
        self.edtEndDate.setDisplayFormat(_translate("ExternalDirectionsReportSetupDialog", "dd.MM.yyyy", None))
        self.lblOrgStructure.setText(_translate("ExternalDirectionsReportSetupDialog", "Подразделение", None))
        self.edtBegDate.setDisplayFormat(_translate("ExternalDirectionsReportSetupDialog", "dd.MM.yyyy", None))
        self.lblEndDate.setText(_translate("ExternalDirectionsReportSetupDialog", "Дата &окончания периода", None))
        self.lblActionStatus.setText(_translate("ExternalDirectionsReportSetupDialog", "Состояние", None))
        self.edtMKBTo.setInputMask(_translate("ExternalDirectionsReportSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ExternalDirectionsReportSetupDialog", "Z99.9", None))
        self.edtMKBFrom.setInputMask(_translate("ExternalDirectionsReportSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ExternalDirectionsReportSetupDialog", "A.", None))
        self.cmbMKBFilter.setItemText(0, _translate("ExternalDirectionsReportSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ExternalDirectionsReportSetupDialog", "Интервал", None))
        self.lblAge.setText(_translate("ExternalDirectionsReportSetupDialog", "Возраст с", None))
        self.lblAgeTo.setText(_translate("ExternalDirectionsReportSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ExternalDirectionsReportSetupDialog", "лет", None))
        self.lblMKBFilter.setText(_translate("ExternalDirectionsReportSetupDialog", "Коды диагнозов по &МКБ", None))
        self.chkCalculationNotes.setText(_translate("ExternalDirectionsReportSetupDialog", "Подсчет по наименованию свойства действия", None))

from Events.ActionStatus import CActionStatusComboBox
from Orgs.OrgComboBox import COrgIsMedicalComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBox import CPersonComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
