# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportOnServiceTypeSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportOnServiceTypeSetupDialog(object):
    def setupUi(self, ReportOnServiceTypeSetupDialog):
        ReportOnServiceTypeSetupDialog.setObjectName(_fromUtf8("ReportOnServiceTypeSetupDialog"))
        ReportOnServiceTypeSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportOnServiceTypeSetupDialog.resize(528, 360)
        ReportOnServiceTypeSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportOnServiceTypeSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEventNumber = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblEventNumber.setObjectName(_fromUtf8("lblEventNumber"))
        self.gridLayout.addWidget(self.lblEventNumber, 5, 0, 1, 1)
        self.lblHospitalBedProfile = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblHospitalBedProfile.setObjectName(_fromUtf8("lblHospitalBedProfile"))
        self.gridLayout.addWidget(self.lblHospitalBedProfile, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(74, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.cmbFinance = CRBComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 7, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportOnServiceTypeSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 1, 1, 4)
        self.isPersonDetail = QtGui.QCheckBox(ReportOnServiceTypeSetupDialog)
        self.isPersonDetail.setObjectName(_fromUtf8("isPersonDetail"))
        self.gridLayout.addWidget(self.isPersonDetail, 10, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.lblFinance = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 7, 0, 1, 1)
        self.isProfileDetail = QtGui.QCheckBox(ReportOnServiceTypeSetupDialog)
        self.isProfileDetail.setObjectName(_fromUtf8("isProfileDetail"))
        self.gridLayout.addWidget(self.isProfileDetail, 8, 1, 1, 4)
        self.lblEndDate = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 1, 1, 1)
        self.isServiceDetail = QtGui.QCheckBox(ReportOnServiceTypeSetupDialog)
        self.isServiceDetail.setObjectName(_fromUtf8("isServiceDetail"))
        self.gridLayout.addWidget(self.isServiceDetail, 11, 1, 1, 4)
        self.edtBegDate = CDateEdit(ReportOnServiceTypeSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.cmbHospitalBedProfile = CRBComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbHospitalBedProfile.setObjectName(_fromUtf8("cmbHospitalBedProfile"))
        self.gridLayout.addWidget(self.cmbHospitalBedProfile, 3, 1, 1, 4)
        self.lblServiceType = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblServiceType.setObjectName(_fromUtf8("lblServiceType"))
        self.gridLayout.addWidget(self.lblServiceType, 4, 0, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(ReportOnServiceTypeSetupDialog)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 3, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(ReportOnServiceTypeSetupDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 13, 0, 1, 2)
        self.edtEndDate = CDateEdit(ReportOnServiceTypeSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        self.edtEventNumber = QtGui.QLineEdit(ReportOnServiceTypeSetupDialog)
        self.edtEventNumber.setObjectName(_fromUtf8("edtEventNumber"))
        self.gridLayout.addWidget(self.edtEventNumber, 5, 3, 1, 2)
        self.lblBegDate = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 1, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 4)
        self.cmbOrder = QtGui.QComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.setItemText(0, _fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOrder, 6, 1, 1, 4)
        self.cmbServiceType = CActionServiceTypeComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridLayout.addWidget(self.cmbServiceType, 4, 1, 1, 4)
        self.lblOrder = QtGui.QLabel(ReportOnServiceTypeSetupDialog)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout.addWidget(self.lblOrder, 6, 0, 1, 1)
        self.cmbTypeNumberEvent = QtGui.QComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbTypeNumberEvent.setObjectName(_fromUtf8("cmbTypeNumberEvent"))
        self.cmbTypeNumberEvent.addItem(_fromUtf8(""))
        self.cmbTypeNumberEvent.addItem(_fromUtf8(""))
        self.cmbTypeNumberEvent.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTypeNumberEvent, 5, 1, 1, 2)
        self.cmbDateType = QtGui.QComboBox(ReportOnServiceTypeSetupDialog)
        self.cmbDateType.setObjectName(_fromUtf8("cmbDateType"))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDateType, 0, 0, 1, 1)
        self.isMKBDetail = QtGui.QCheckBox(ReportOnServiceTypeSetupDialog)
        self.isMKBDetail.setObjectName(_fromUtf8("isMKBDetail"))
        self.gridLayout.addWidget(self.isMKBDetail, 12, 1, 1, 4)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)

        self.retranslateUi(ReportOnServiceTypeSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportOnServiceTypeSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportOnServiceTypeSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportOnServiceTypeSetupDialog)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbDateType, self.edtBegDate)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.edtEndTime, self.cmbOrgStructure)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbHospitalBedProfile)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbHospitalBedProfile, self.cmbServiceType)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbServiceType, self.cmbTypeNumberEvent)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbTypeNumberEvent, self.edtEventNumber)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.edtEventNumber, self.cmbOrder)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbOrder, self.cmbFinance)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.cmbFinance, self.isProfileDetail)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.isProfileDetail, self.isPersonDetail)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.isPersonDetail, self.isServiceDetail)
        ReportOnServiceTypeSetupDialog.setTabOrder(self.isServiceDetail, self.buttonBox)

    def retranslateUi(self, ReportOnServiceTypeSetupDialog):
        ReportOnServiceTypeSetupDialog.setWindowTitle(_translate("ReportOnServiceTypeSetupDialog", "параметры отчёта", None))
        self.lblEventNumber.setText(_translate("ReportOnServiceTypeSetupDialog", "Номер обращения", None))
        self.lblHospitalBedProfile.setText(_translate("ReportOnServiceTypeSetupDialog", "Профиль", None))
        self.lblOrgStructure.setText(_translate("ReportOnServiceTypeSetupDialog", "&Подразделение", None))
        self.isPersonDetail.setText(_translate("ReportOnServiceTypeSetupDialog", "Детализация по исполнителям", None))
        self.lblFinance.setText(_translate("ReportOnServiceTypeSetupDialog", "Тип финансирования", None))
        self.isProfileDetail.setText(_translate("ReportOnServiceTypeSetupDialog", "Детализация по профилям", None))
        self.lblEndDate.setText(_translate("ReportOnServiceTypeSetupDialog", "Конец периода", None))
        self.isServiceDetail.setText(_translate("ReportOnServiceTypeSetupDialog", "Детализация по услугам", None))
        self.edtBegDate.setDisplayFormat(_translate("ReportOnServiceTypeSetupDialog", "dd.MM.yyyy", None))
        self.lblServiceType.setText(_translate("ReportOnServiceTypeSetupDialog", "Вид услуги", None))
        self.edtEndDate.setDisplayFormat(_translate("ReportOnServiceTypeSetupDialog", "dd.MM.yyyy", None))
        self.lblBegDate.setText(_translate("ReportOnServiceTypeSetupDialog", "Начало периода", None))
        self.cmbOrder.setItemText(1, _translate("ReportOnServiceTypeSetupDialog", "Плановый", None))
        self.cmbOrder.setItemText(2, _translate("ReportOnServiceTypeSetupDialog", "Экстренный", None))
        self.cmbOrder.setItemText(3, _translate("ReportOnServiceTypeSetupDialog", "Самотёком", None))
        self.cmbOrder.setItemText(4, _translate("ReportOnServiceTypeSetupDialog", "Принудительный", None))
        self.cmbOrder.setItemText(5, _translate("ReportOnServiceTypeSetupDialog", "Внутренний перевод", None))
        self.cmbOrder.setItemText(6, _translate("ReportOnServiceTypeSetupDialog", "Неотложная", None))
        self.lblOrder.setText(_translate("ReportOnServiceTypeSetupDialog", "Порядок", None))
        self.cmbTypeNumberEvent.setItemText(0, _translate("ReportOnServiceTypeSetupDialog", "не задано", None))
        self.cmbTypeNumberEvent.setItemText(1, _translate("ReportOnServiceTypeSetupDialog", "номер документа", None))
        self.cmbTypeNumberEvent.setItemText(2, _translate("ReportOnServiceTypeSetupDialog", "код карточки", None))
        self.cmbDateType.setItemText(0, _translate("ReportOnServiceTypeSetupDialog", "Дата выполнения", None))
        self.cmbDateType.setItemText(1, _translate("ReportOnServiceTypeSetupDialog", "Дата начала", None))
        self.isMKBDetail.setText(_translate("ReportOnServiceTypeSetupDialog", "Детализация по кодам МКБ", None))

from Events.ActionServiceType import CActionServiceTypeComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
