# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportSetupDoneActionsForRauh.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportSetupDoneActionsForRauh(object):
    def setupUi(self, ReportSetupDoneActionsForRauh):
        ReportSetupDoneActionsForRauh.setObjectName(_fromUtf8("ReportSetupDoneActionsForRauh"))
        ReportSetupDoneActionsForRauh.resize(576, 733)
        self.gridLayout = QtGui.QGridLayout(ReportSetupDoneActionsForRauh)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbDateType = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbDateType.setObjectName(_fromUtf8("cmbDateType"))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDateType, 0, 1, 1, 5)
        self.cmbReportType = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbReportType.setObjectName(_fromUtf8("cmbReportType"))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbReportType, 17, 1, 1, 5)
        self.lblEventIdentifierType = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblEventIdentifierType.setObjectName(_fromUtf8("lblEventIdentifierType"))
        self.gridLayout.addWidget(self.lblEventIdentifierType, 16, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.chkGroupByPatient = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkGroupByPatient.setObjectName(_fromUtf8("chkGroupByPatient"))
        self.gridLayout.addWidget(self.chkGroupByPatient, 21, 1, 1, 5)
        self.chkClass = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClass.sizePolicy().hasHeightForWidth())
        self.chkClass.setSizePolicy(sizePolicy)
        self.chkClass.setObjectName(_fromUtf8("chkClass"))
        self.gridLayout.addWidget(self.chkClass, 10, 0, 1, 1)
        self.chkAllOrgStructure = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkAllOrgStructure.setEnabled(False)
        self.chkAllOrgStructure.setObjectName(_fromUtf8("chkAllOrgStructure"))
        self.gridLayout.addWidget(self.chkAllOrgStructure, 18, 1, 1, 5)
        self.chkOrgStructure = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkOrgStructure.setObjectName(_fromUtf8("chkOrgStructure"))
        self.gridLayout.addWidget(self.chkOrgStructure, 14, 0, 1, 1)
        self.lblContract = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 4, 0, 1, 1)
        self.cmbEventIdentifierType = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbEventIdentifierType.setObjectName(_fromUtf8("cmbEventIdentifierType"))
        self.cmbEventIdentifierType.addItem(_fromUtf8(""))
        self.cmbEventIdentifierType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEventIdentifierType, 16, 1, 1, 5)
        self.cmbStatus = CActionStatusComboBox(ReportSetupDoneActionsForRauh)
        self.cmbStatus.setEnabled(False)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.gridLayout.addWidget(self.cmbStatus, 12, 1, 1, 5)
        self.lblConfirmationType = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblConfirmationType.setObjectName(_fromUtf8("lblConfirmationType"))
        self.gridLayout.addWidget(self.lblConfirmationType, 7, 0, 1, 1)
        self.chkDetailPerson = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkDetailPerson.setObjectName(_fromUtf8("chkDetailPerson"))
        self.gridLayout.addWidget(self.chkDetailPerson, 19, 1, 1, 5)
        self.chkConfirmation = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkConfirmation.setObjectName(_fromUtf8("chkConfirmation"))
        self.gridLayout.addWidget(self.chkConfirmation, 6, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 26, 0, 1, 1)
        self.lblBegDateConfirmation = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblBegDateConfirmation.setObjectName(_fromUtf8("lblBegDateConfirmation"))
        self.gridLayout.addWidget(self.lblBegDateConfirmation, 8, 0, 1, 1)
        self.cmbClientAgeCategory = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbClientAgeCategory.setObjectName(_fromUtf8("cmbClientAgeCategory"))
        self.cmbClientAgeCategory.addItem(_fromUtf8(""))
        self.cmbClientAgeCategory.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClientAgeCategory, 24, 1, 1, 5)
        self.cmbPerson = CPersonComboBoxEx(ReportSetupDoneActionsForRauh)
        self.cmbPerson.setEnabled(False)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 15, 1, 1, 5)
        self.chkCoefficient = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkCoefficient.setObjectName(_fromUtf8("chkCoefficient"))
        self.gridLayout.addWidget(self.chkCoefficient, 23, 1, 1, 5)
        self.chkStatus = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout.addWidget(self.chkStatus, 12, 0, 1, 1)
        self.cmbContract = CContractComboBox(ReportSetupDoneActionsForRauh)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 4, 1, 1, 5)
        self.chkDetailService = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkDetailService.setEnabled(False)
        self.chkDetailService.setObjectName(_fromUtf8("chkDetailService"))
        self.gridLayout.addWidget(self.chkDetailService, 22, 1, 1, 5)
        self.cmbOrgStructure = COrgStructureComboBox(ReportSetupDoneActionsForRauh)
        self.cmbOrgStructure.setEnabled(False)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 14, 1, 1, 5)
        self.cmbClass = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbClass.setEnabled(False)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClass, 10, 1, 1, 5)
        self.lblEndDate = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 3, 0, 1, 1)
        self.chkOnlyClientAsPersonInLPU = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkOnlyClientAsPersonInLPU.setObjectName(_fromUtf8("chkOnlyClientAsPersonInLPU"))
        self.gridLayout.addWidget(self.chkOnlyClientAsPersonInLPU, 25, 0, 1, 6)
        self.chkClientAgeCategory = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkClientAgeCategory.setObjectName(_fromUtf8("chkClientAgeCategory"))
        self.gridLayout.addWidget(self.chkClientAgeCategory, 24, 0, 1, 1)
        self.chkPerson = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkPerson.setObjectName(_fromUtf8("chkPerson"))
        self.gridLayout.addWidget(self.chkPerson, 15, 0, 1, 1)
        self.cmbActionTypeGroup = CActionTypeComboBoxMCL(ReportSetupDoneActionsForRauh)
        self.cmbActionTypeGroup.setEnabled(False)
        self.cmbActionTypeGroup.setObjectName(_fromUtf8("cmbActionTypeGroup"))
        self.gridLayout.addWidget(self.cmbActionTypeGroup, 11, 1, 1, 5)
        self.chkPatientInfo = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkPatientInfo.setObjectName(_fromUtf8("chkPatientInfo"))
        self.gridLayout.addWidget(self.chkPatientInfo, 20, 1, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(ReportSetupDoneActionsForRauh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 27, 0, 1, 6)
        self.lblDateType = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblDateType.setObjectName(_fromUtf8("lblDateType"))
        self.gridLayout.addWidget(self.lblDateType, 0, 0, 1, 1)
        self.lblReportType = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblReportType.setObjectName(_fromUtf8("lblReportType"))
        self.gridLayout.addWidget(self.lblReportType, 17, 0, 1, 1)
        self.chkEventStatus = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        self.chkEventStatus.setObjectName(_fromUtf8("chkEventStatus"))
        self.gridLayout.addWidget(self.chkEventStatus, 13, 0, 1, 1)
        self.cmbEventStatus = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbEventStatus.setEnabled(False)
        self.cmbEventStatus.setObjectName(_fromUtf8("cmbEventStatus"))
        self.cmbEventStatus.addItem(_fromUtf8(""))
        self.cmbEventStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEventStatus, 13, 1, 1, 5)
        self.chkActionTypeGroup = QtGui.QCheckBox(ReportSetupDoneActionsForRauh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActionTypeGroup.sizePolicy().hasHeightForWidth())
        self.chkActionTypeGroup.setSizePolicy(sizePolicy)
        self.chkActionTypeGroup.setObjectName(_fromUtf8("chkActionTypeGroup"))
        self.gridLayout.addWidget(self.chkActionTypeGroup, 11, 0, 1, 1)
        self.lblEndDateConfirmation = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblEndDateConfirmation.setObjectName(_fromUtf8("lblEndDateConfirmation"))
        self.gridLayout.addWidget(self.lblEndDateConfirmation, 9, 0, 1, 1)
        self.edtConfirmationBegDate = CDateEdit(ReportSetupDoneActionsForRauh)
        self.edtConfirmationBegDate.setEnabled(False)
        self.edtConfirmationBegDate.setObjectName(_fromUtf8("edtConfirmationBegDate"))
        self.gridLayout.addWidget(self.edtConfirmationBegDate, 8, 1, 1, 1)
        self.edtConfirmationEndDate = CDateEdit(ReportSetupDoneActionsForRauh)
        self.edtConfirmationEndDate.setEnabled(False)
        self.edtConfirmationEndDate.setObjectName(_fromUtf8("edtConfirmationEndDate"))
        self.gridLayout.addWidget(self.edtConfirmationEndDate, 9, 1, 1, 1)
        self.cmbConfirmationPeriodType = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbConfirmationPeriodType.setEnabled(False)
        self.cmbConfirmationPeriodType.setObjectName(_fromUtf8("cmbConfirmationPeriodType"))
        self.cmbConfirmationPeriodType.addItem(_fromUtf8(""))
        self.cmbConfirmationPeriodType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbConfirmationPeriodType, 8, 2, 1, 1)
        self.btnFinanceTypeList = QtGui.QPushButton(ReportSetupDoneActionsForRauh)
        self.btnFinanceTypeList.setObjectName(_fromUtf8("btnFinanceTypeList"))
        self.gridLayout.addWidget(self.btnFinanceTypeList, 5, 0, 1, 1)
        self.lblFinanceTypeList = QtGui.QLabel(ReportSetupDoneActionsForRauh)
        self.lblFinanceTypeList.setObjectName(_fromUtf8("lblFinanceTypeList"))
        self.gridLayout.addWidget(self.lblFinanceTypeList, 5, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 3, 1, 3)
        self.cmbConfirmationType = QtGui.QComboBox(ReportSetupDoneActionsForRauh)
        self.cmbConfirmationType.setEnabled(False)
        self.cmbConfirmationType.setObjectName(_fromUtf8("cmbConfirmationType"))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbConfirmationType, 7, 1, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 2, 1, 3)
        self.edtBegDate = CDateEdit(ReportSetupDoneActionsForRauh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 4)
        self.edtEndDate = CDateEdit(ReportSetupDoneActionsForRauh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 4)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblContract.setBuddy(self.cmbContract)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblReportType.setBuddy(self.cmbReportType)

        self.retranslateUi(ReportSetupDoneActionsForRauh)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportSetupDoneActionsForRauh.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportSetupDoneActionsForRauh.reject)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.chkOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkClientAgeCategory, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClientAgeCategory.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPerson.setEnabled)
        QtCore.QObject.connect(self.chkGroupByPatient, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkDetailService.setEnabled)
        QtCore.QObject.connect(self.chkEventStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbEventStatus.setEnabled)
        QtCore.QObject.connect(self.chkClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClass.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionTypeGroup.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbConfirmationType.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbConfirmationPeriodType.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtConfirmationBegDate.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtConfirmationEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ReportSetupDoneActionsForRauh)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbDateType, self.edtBegDate)
        ReportSetupDoneActionsForRauh.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportSetupDoneActionsForRauh.setTabOrder(self.edtEndDate, self.cmbContract)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbContract, self.btnFinanceTypeList)
        ReportSetupDoneActionsForRauh.setTabOrder(self.btnFinanceTypeList, self.chkConfirmation)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkConfirmation, self.cmbConfirmationType)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbConfirmationType, self.edtConfirmationBegDate)
        ReportSetupDoneActionsForRauh.setTabOrder(self.edtConfirmationBegDate, self.edtConfirmationEndDate)
        ReportSetupDoneActionsForRauh.setTabOrder(self.edtConfirmationEndDate, self.cmbConfirmationPeriodType)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbConfirmationPeriodType, self.chkClass)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkClass, self.cmbClass)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbClass, self.chkActionTypeGroup)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkActionTypeGroup, self.cmbActionTypeGroup)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbActionTypeGroup, self.chkStatus)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkStatus, self.cmbStatus)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbStatus, self.chkEventStatus)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkEventStatus, self.cmbEventStatus)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbEventStatus, self.chkOrgStructure)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkOrgStructure, self.cmbOrgStructure)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbOrgStructure, self.chkPerson)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkPerson, self.cmbPerson)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbPerson, self.cmbEventIdentifierType)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbEventIdentifierType, self.cmbReportType)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbReportType, self.chkAllOrgStructure)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkAllOrgStructure, self.chkDetailPerson)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkDetailPerson, self.chkPatientInfo)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkPatientInfo, self.chkGroupByPatient)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkGroupByPatient, self.chkDetailService)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkDetailService, self.chkCoefficient)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkCoefficient, self.chkClientAgeCategory)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkClientAgeCategory, self.cmbClientAgeCategory)
        ReportSetupDoneActionsForRauh.setTabOrder(self.cmbClientAgeCategory, self.chkOnlyClientAsPersonInLPU)
        ReportSetupDoneActionsForRauh.setTabOrder(self.chkOnlyClientAsPersonInLPU, self.buttonBox)

    def retranslateUi(self, ReportSetupDoneActionsForRauh):
        ReportSetupDoneActionsForRauh.setWindowTitle(_translate("ReportSetupDoneActionsForRauh", "Dialog", None))
        self.cmbDateType.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "даты оказания услуги", None))
        self.cmbDateType.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "даты события", None))
        self.cmbReportType.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "отделениям выполнившего действие врача", None))
        self.cmbReportType.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "отделениям за которым закреплено действие", None))
        self.lblEventIdentifierType.setText(_translate("ReportSetupDoneActionsForRauh", "Номер обращения", None))
        self.lblBegDate.setText(_translate("ReportSetupDoneActionsForRauh", "Дата &начала периода", None))
        self.chkGroupByPatient.setText(_translate("ReportSetupDoneActionsForRauh", "Группировать по пациентам", None))
        self.chkClass.setText(_translate("ReportSetupDoneActionsForRauh", "Класс", None))
        self.chkAllOrgStructure.setText(_translate("ReportSetupDoneActionsForRauh", "Учитывать все возможные подразделения", None))
        self.chkOrgStructure.setText(_translate("ReportSetupDoneActionsForRauh", "Подразделение", None))
        self.lblContract.setText(_translate("ReportSetupDoneActionsForRauh", "Контракт", None))
        self.cmbEventIdentifierType.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "Код обращения", None))
        self.cmbEventIdentifierType.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "Номер документа", None))
        self.lblConfirmationType.setText(_translate("ReportSetupDoneActionsForRauh", "Тип подтверждения:", None))
        self.chkDetailPerson.setText(_translate("ReportSetupDoneActionsForRauh", "Детализировать по исполнителю", None))
        self.chkConfirmation.setText(_translate("ReportSetupDoneActionsForRauh", "Подтверждение оплаты", None))
        self.lblBegDateConfirmation.setText(_translate("ReportSetupDoneActionsForRauh", "Начало периода подтверждения:", None))
        self.cmbClientAgeCategory.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "Дети от 0 до 17 лет", None))
        self.cmbClientAgeCategory.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "Взрослые от 18 лет", None))
        self.chkCoefficient.setText(_translate("ReportSetupDoneActionsForRauh", "Учитывать коэффициенты", None))
        self.chkStatus.setText(_translate("ReportSetupDoneActionsForRauh", "Статус действия", None))
        self.chkDetailService.setText(_translate("ReportSetupDoneActionsForRauh", "Детализировать услуги", None))
        self.cmbClass.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "Статус", None))
        self.cmbClass.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "Диагностика", None))
        self.cmbClass.setItemText(2, _translate("ReportSetupDoneActionsForRauh", "Лечение", None))
        self.cmbClass.setItemText(3, _translate("ReportSetupDoneActionsForRauh", "Прочие мероприятия", None))
        self.cmbClass.setItemText(4, _translate("ReportSetupDoneActionsForRauh", "Назначено", None))
        self.lblEndDate.setText(_translate("ReportSetupDoneActionsForRauh", "Дата &окончания периода", None))
        self.chkOnlyClientAsPersonInLPU.setText(_translate("ReportSetupDoneActionsForRauh", "Только пациенты сотрудники учереждения", None))
        self.chkClientAgeCategory.setText(_translate("ReportSetupDoneActionsForRauh", "Возраст пациента", None))
        self.chkPerson.setText(_translate("ReportSetupDoneActionsForRauh", "Исполнитель", None))
        self.chkPatientInfo.setText(_translate("ReportSetupDoneActionsForRauh", "Информация о пациенте", None))
        self.lblDateType.setText(_translate("ReportSetupDoneActionsForRauh", "Тип даты", None))
        self.lblReportType.setText(_translate("ReportSetupDoneActionsForRauh", "Формировать отчет по", None))
        self.chkEventStatus.setText(_translate("ReportSetupDoneActionsForRauh", "Статус события", None))
        self.cmbEventStatus.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "Закрытые", None))
        self.cmbEventStatus.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "Открытые", None))
        self.chkActionTypeGroup.setText(_translate("ReportSetupDoneActionsForRauh", "Группа", None))
        self.lblEndDateConfirmation.setText(_translate("ReportSetupDoneActionsForRauh", "Окончание периода подтверждения:", None))
        self.edtConfirmationBegDate.setDisplayFormat(_translate("ReportSetupDoneActionsForRauh", "dd.MM.yyyy", None))
        self.edtConfirmationEndDate.setDisplayFormat(_translate("ReportSetupDoneActionsForRauh", "dd.MM.yyyy", None))
        self.cmbConfirmationPeriodType.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "по дате формирования счета", None))
        self.cmbConfirmationPeriodType.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "по дате подтверждения оплаты", None))
        self.btnFinanceTypeList.setText(_translate("ReportSetupDoneActionsForRauh", "Тип финансирования", None))
        self.lblFinanceTypeList.setText(_translate("ReportSetupDoneActionsForRauh", "  не задано", None))
        self.cmbConfirmationType.setItemText(0, _translate("ReportSetupDoneActionsForRauh", "не выставлено", None))
        self.cmbConfirmationType.setItemText(1, _translate("ReportSetupDoneActionsForRauh", "выставлено", None))
        self.cmbConfirmationType.setItemText(2, _translate("ReportSetupDoneActionsForRauh", "оплачено", None))
        self.cmbConfirmationType.setItemText(3, _translate("ReportSetupDoneActionsForRauh", "отказано", None))
        self.edtBegDate.setDisplayFormat(_translate("ReportSetupDoneActionsForRauh", "dd.MM.yyyy", None))
        self.edtEndDate.setDisplayFormat(_translate("ReportSetupDoneActionsForRauh", "dd.MM.yyyy", None))

from Accounting.ContractComboBox import CContractComboBox
from Events.ActionStatus import CActionStatusComboBox
from Events.ActionTypeComboBox import CActionTypeComboBoxMCL
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
