# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/Reports/ReportUETActions.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportUETActions(object):
    def setupUi(self, ReportUETActions):
        ReportUETActions.setObjectName(_fromUtf8("ReportUETActions"))
        ReportUETActions.resize(632, 460)
        self.gridLayout = QtGui.QGridLayout(ReportUETActions)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblFinance = QtGui.QLabel(ReportUETActions)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 22, 0, 1, 3)
        self.cmbFinance = CRBComboBox(ReportUETActions)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 4, 1, 1, 2)
        self.lblPersonParam = QtGui.QLabel(ReportUETActions)
        self.lblPersonParam.setObjectName(_fromUtf8("lblPersonParam"))
        self.gridLayout.addWidget(self.lblPersonParam, 2, 0, 1, 1)
        self.chkDetailByOrgStructures = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByOrgStructures.setObjectName(_fromUtf8("chkDetailByOrgStructures"))
        self.gridLayout.addWidget(self.chkDetailByOrgStructures, 9, 1, 1, 1)
        self.cmbPersonParam = QtGui.QComboBox(ReportUETActions)
        self.cmbPersonParam.setObjectName(_fromUtf8("cmbPersonParam"))
        self.cmbPersonParam.addItem(_fromUtf8(""))
        self.cmbPersonParam.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPersonParam, 2, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportUETActions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 23, 0, 1, 3)
        self.chkDetailByMedicalAidType = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByMedicalAidType.setObjectName(_fromUtf8("chkDetailByMedicalAidType"))
        self.gridLayout.addWidget(self.chkDetailByMedicalAidType, 11, 1, 1, 2)
        self.lblActionStatusList = QtGui.QLabel(ReportUETActions)
        self.lblActionStatusList.setWordWrap(True)
        self.lblActionStatusList.setObjectName(_fromUtf8("lblActionStatusList"))
        self.gridLayout.addWidget(self.lblActionStatusList, 7, 1, 1, 2)
        self.chkDetailByActionType = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByActionType.setObjectName(_fromUtf8("chkDetailByActionType"))
        self.gridLayout.addWidget(self.chkDetailByActionType, 14, 1, 1, 2)
        self.btnActionStatusList = QtGui.QPushButton(ReportUETActions)
        self.btnActionStatusList.setObjectName(_fromUtf8("btnActionStatusList"))
        self.gridLayout.addWidget(self.btnActionStatusList, 7, 0, 1, 1)
        self.cmbPostParam = QtGui.QComboBox(ReportUETActions)
        self.cmbPostParam.setObjectName(_fromUtf8("cmbPostParam"))
        self.cmbPostParam.addItem(_fromUtf8(""))
        self.cmbPostParam.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPostParam, 6, 1, 1, 2)
        self.edtBegDate = CDateEdit(ReportUETActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(ReportUETActions)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 3, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportUETActions)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 3, 1, 1, 2)
        self.edtEndDate = CDateEdit(ReportUETActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 2)
        self.lblMedicalAidType = QtGui.QLabel(ReportUETActions)
        self.lblMedicalAidType.setObjectName(_fromUtf8("lblMedicalAidType"))
        self.gridLayout.addWidget(self.lblMedicalAidType, 5, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportUETActions)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportUETActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbMedicalAidType = CRBComboBox(ReportUETActions)
        self.cmbMedicalAidType.setObjectName(_fromUtf8("cmbMedicalAidType"))
        self.gridLayout.addWidget(self.cmbMedicalAidType, 5, 1, 1, 2)
        self.chkDetailByFinance = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByFinance.setObjectName(_fromUtf8("chkDetailByFinance"))
        self.gridLayout.addWidget(self.chkDetailByFinance, 8, 1, 1, 1)
        self.lblPostParam = QtGui.QLabel(ReportUETActions)
        self.lblPostParam.setObjectName(_fromUtf8("lblPostParam"))
        self.gridLayout.addWidget(self.lblPostParam, 6, 0, 1, 1)
        self.chkDetailByActionTypeClasses = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByActionTypeClasses.setObjectName(_fromUtf8("chkDetailByActionTypeClasses"))
        self.gridLayout.addWidget(self.chkDetailByActionTypeClasses, 12, 1, 1, 1)
        self.chkDetailByClient = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByClient.setObjectName(_fromUtf8("chkDetailByClient"))
        self.gridLayout.addWidget(self.chkDetailByClient, 18, 1, 1, 2)
        self.chkActionClass = QtGui.QCheckBox(ReportUETActions)
        self.chkActionClass.setObjectName(_fromUtf8("chkActionClass"))
        self.gridLayout.addWidget(self.chkActionClass, 19, 0, 1, 3)
        self.lblActionTypeClass = QtGui.QLabel(ReportUETActions)
        self.lblActionTypeClass.setObjectName(_fromUtf8("lblActionTypeClass"))
        self.gridLayout.addWidget(self.lblActionTypeClass, 20, 0, 1, 1)
        self.lblActionType = QtGui.QLabel(ReportUETActions)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 21, 0, 1, 1)
        self.cmbActionTypeClass = QtGui.QComboBox(ReportUETActions)
        self.cmbActionTypeClass.setEnabled(False)
        self.cmbActionTypeClass.setObjectName(_fromUtf8("cmbActionTypeClass"))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActionTypeClass, 20, 1, 1, 2)
        self.cmbActionType = CActionTypeComboBoxEx(ReportUETActions)
        self.cmbActionType.setEnabled(False)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 21, 1, 1, 2)
        self.chkDetailByActionTypeGroup = QtGui.QCheckBox(ReportUETActions)
        self.chkDetailByActionTypeGroup.setObjectName(_fromUtf8("chkDetailByActionTypeGroup"))
        self.gridLayout.addWidget(self.chkDetailByActionTypeGroup, 13, 1, 1, 2)
        self.lblPersonParam.setBuddy(self.cmbOrgStructure)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblPostParam.setBuddy(self.cmbOrgStructure)
        self.lblActionTypeClass.setBuddy(self.cmbActionTypeClass)

        self.retranslateUi(ReportUETActions)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportUETActions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportUETActions.reject)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionTypeClass.setEnabled)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ReportUETActions)
        ReportUETActions.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportUETActions.setTabOrder(self.edtEndDate, self.cmbPersonParam)
        ReportUETActions.setTabOrder(self.cmbPersonParam, self.cmbOrgStructure)
        ReportUETActions.setTabOrder(self.cmbOrgStructure, self.cmbFinance)
        ReportUETActions.setTabOrder(self.cmbFinance, self.cmbMedicalAidType)
        ReportUETActions.setTabOrder(self.cmbMedicalAidType, self.cmbPostParam)
        ReportUETActions.setTabOrder(self.cmbPostParam, self.btnActionStatusList)
        ReportUETActions.setTabOrder(self.btnActionStatusList, self.chkDetailByFinance)
        ReportUETActions.setTabOrder(self.chkDetailByFinance, self.chkDetailByOrgStructures)
        ReportUETActions.setTabOrder(self.chkDetailByOrgStructures, self.chkDetailByMedicalAidType)
        ReportUETActions.setTabOrder(self.chkDetailByMedicalAidType, self.chkDetailByActionTypeClasses)
        ReportUETActions.setTabOrder(self.chkDetailByActionTypeClasses, self.chkDetailByActionTypeGroup)
        ReportUETActions.setTabOrder(self.chkDetailByActionTypeGroup, self.chkDetailByActionType)
        ReportUETActions.setTabOrder(self.chkDetailByActionType, self.chkDetailByClient)
        ReportUETActions.setTabOrder(self.chkDetailByClient, self.chkActionClass)
        ReportUETActions.setTabOrder(self.chkActionClass, self.cmbActionTypeClass)
        ReportUETActions.setTabOrder(self.cmbActionTypeClass, self.cmbActionType)
        ReportUETActions.setTabOrder(self.cmbActionType, self.buttonBox)

    def retranslateUi(self, ReportUETActions):
        ReportUETActions.setWindowTitle(_translate("ReportUETActions", "Dialog", None))
        self.lblFinance.setText(_translate("ReportUETActions", "Тип финансирования", None))
        self.lblPersonParam.setText(_translate("ReportUETActions", "Формировать по", None))
        self.chkDetailByOrgStructures.setText(_translate("ReportUETActions", "Детализировать по подразделениям", None))
        self.cmbPersonParam.setItemText(0, _translate("ReportUETActions", "исполнителям", None))
        self.cmbPersonParam.setItemText(1, _translate("ReportUETActions", "ассистентам", None))
        self.chkDetailByMedicalAidType.setText(_translate("ReportUETActions", "Детализировать по типам мед помощи", None))
        self.lblActionStatusList.setText(_translate("ReportUETActions", "Не задано", None))
        self.chkDetailByActionType.setText(_translate("ReportUETActions", "Детализировать по типам действий", None))
        self.btnActionStatusList.setText(_translate("ReportUETActions", "Статус действия", None))
        self.cmbPostParam.setItemText(0, _translate("ReportUETActions", "врач", None))
        self.cmbPostParam.setItemText(1, _translate("ReportUETActions", "средний мед персонал", None))
        self.lblOrgStructure.setText(_translate("ReportUETActions", "&Подразделение", None))
        self.lblMedicalAidType.setText(_translate("ReportUETActions", "Тип мед помощи", None))
        self.lblEndDate.setText(_translate("ReportUETActions", "Дата &окончания периода", None))
        self.lblBegDate.setText(_translate("ReportUETActions", "Дата &начала периода", None))
        self.chkDetailByFinance.setText(_translate("ReportUETActions", "Детализировать по типам финансирования", None))
        self.lblPostParam.setText(_translate("ReportUETActions", "Должность", None))
        self.chkDetailByActionTypeClasses.setText(_translate("ReportUETActions", "Детализировать по классам типов действий", None))
        self.chkDetailByClient.setText(_translate("ReportUETActions", "Детализировать по пациенту", None))
        self.chkActionClass.setText(_translate("ReportUETActions", "Учитывать класс", None))
        self.lblActionTypeClass.setText(_translate("ReportUETActions", "Класс", None))
        self.lblActionType.setText(_translate("ReportUETActions", "Мероприятие", None))
        self.cmbActionTypeClass.setItemText(0, _translate("ReportUETActions", "Статус", None))
        self.cmbActionTypeClass.setItemText(1, _translate("ReportUETActions", "Диагностика", None))
        self.cmbActionTypeClass.setItemText(2, _translate("ReportUETActions", "Лечение", None))
        self.cmbActionTypeClass.setItemText(3, _translate("ReportUETActions", "Прочие мероприятия", None))
        self.chkDetailByActionTypeGroup.setText(_translate("ReportUETActions", "Детализировать по группам типов действий", None))

from Events.ActionTypeComboBoxEx import CActionTypeComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReportUETActions = QtGui.QDialog()
    ui = Ui_ReportUETActions()
    ui.setupUi(ReportUETActions)
    ReportUETActions.show()
    sys.exit(app.exec_())

