# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportsBeingInStationary.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportsBeingInStationaryDialog(object):
    def setupUi(self, ReportsBeingInStationaryDialog):
        ReportsBeingInStationaryDialog.setObjectName(_fromUtf8("ReportsBeingInStationaryDialog"))
        ReportsBeingInStationaryDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportsBeingInStationaryDialog.resize(543, 274)
        ReportsBeingInStationaryDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportsBeingInStationaryDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblActionTypeList = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblActionTypeList.setWordWrap(True)
        self.lblActionTypeList.setObjectName(_fromUtf8("lblActionTypeList"))
        self.gridLayout.addWidget(self.lblActionTypeList, 9, 1, 1, 4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 5, 1, 1)
        self.edtEndDate = CDateEdit(ReportsBeingInStationaryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportsBeingInStationaryDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 6, 1, 1, 5)
        self.lblOrgStructure = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 3)
        self.btnActionTypeList = QtGui.QPushButton(ReportsBeingInStationaryDialog)
        self.btnActionTypeList.setObjectName(_fromUtf8("btnActionTypeList"))
        self.gridLayout.addWidget(self.btnActionTypeList, 9, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportsBeingInStationaryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 6)
        self.edtBegDate = CDateEdit(ReportsBeingInStationaryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblMKB = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 8, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblSelectType = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblSelectType.setObjectName(_fromUtf8("lblSelectType"))
        self.gridLayout.addWidget(self.lblSelectType, 4, 0, 1, 1)
        self.cmbSelectType = QtGui.QComboBox(ReportsBeingInStationaryDialog)
        self.cmbSelectType.setObjectName(_fromUtf8("cmbSelectType"))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSelectType, 4, 1, 1, 5)
        self.cmbOrgStructure = COrgStructureComboBox(ReportsBeingInStationaryDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 5, 1, 1, 5)
        self.lblPerson = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 6, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbMKBFilter = QtGui.QComboBox(ReportsBeingInStationaryDialog)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMKBFilter, 8, 1, 1, 1)
        self.edtLimitDays = QtGui.QSpinBox(ReportsBeingInStationaryDialog)
        self.edtLimitDays.setObjectName(_fromUtf8("edtLimitDays"))
        self.gridLayout.addWidget(self.edtLimitDays, 2, 1, 1, 1)
        self.lblLimitDays = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.lblLimitDays.setObjectName(_fromUtf8("lblLimitDays"))
        self.gridLayout.addWidget(self.lblLimitDays, 2, 0, 1, 1)
        self.label = QtGui.QLabel(ReportsBeingInStationaryDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 4)
        spacerItem5 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 4)
        self.edtMKBFrom = CICDCodeEdit(ReportsBeingInStationaryDialog)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout.addWidget(self.edtMKBFrom, 8, 2, 1, 1)
        self.edtMKBTo = CICDCodeEdit(ReportsBeingInStationaryDialog)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout.addWidget(self.edtMKBTo, 8, 3, 1, 1)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(ReportsBeingInStationaryDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportsBeingInStationaryDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportsBeingInStationaryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportsBeingInStationaryDialog)
        ReportsBeingInStationaryDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportsBeingInStationaryDialog.setTabOrder(self.edtEndDate, self.edtLimitDays)
        ReportsBeingInStationaryDialog.setTabOrder(self.edtLimitDays, self.cmbSelectType)
        ReportsBeingInStationaryDialog.setTabOrder(self.cmbSelectType, self.cmbOrgStructure)
        ReportsBeingInStationaryDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ReportsBeingInStationaryDialog.setTabOrder(self.cmbPerson, self.cmbMKBFilter)
        ReportsBeingInStationaryDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        ReportsBeingInStationaryDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        ReportsBeingInStationaryDialog.setTabOrder(self.edtMKBTo, self.btnActionTypeList)
        ReportsBeingInStationaryDialog.setTabOrder(self.btnActionTypeList, self.buttonBox)

    def retranslateUi(self, ReportsBeingInStationaryDialog):
        ReportsBeingInStationaryDialog.setWindowTitle(_translate("ReportsBeingInStationaryDialog", "параметры отчёта", None))
        self.lblActionTypeList.setText(_translate("ReportsBeingInStationaryDialog", "  не задано", None))
        self.edtEndDate.setDisplayFormat(_translate("ReportsBeingInStationaryDialog", "dd.MM.yyyy", None))
        self.lblOrgStructure.setText(_translate("ReportsBeingInStationaryDialog", "&Подразделение", None))
        self.btnActionTypeList.setText(_translate("ReportsBeingInStationaryDialog", "Операция", None))
        self.edtBegDate.setDisplayFormat(_translate("ReportsBeingInStationaryDialog", "dd.MM.yyyy", None))
        self.lblMKB.setText(_translate("ReportsBeingInStationaryDialog", "Коды диагнозов по &МКБ", None))
        self.lblEndDate.setText(_translate("ReportsBeingInStationaryDialog", "Дата &окончания периода", None))
        self.lblSelectType.setText(_translate("ReportsBeingInStationaryDialog", "Выбор", None))
        self.cmbSelectType.setItemText(0, _translate("ReportsBeingInStationaryDialog", "по врачу ответственному за действие", None))
        self.cmbSelectType.setItemText(1, _translate("ReportsBeingInStationaryDialog", "по врачу ответственному за событие", None))
        self.lblPerson.setText(_translate("ReportsBeingInStationaryDialog", "Врач", None))
        self.lblBegDate.setText(_translate("ReportsBeingInStationaryDialog", "Дата &начала периода", None))
        self.cmbMKBFilter.setItemText(0, _translate("ReportsBeingInStationaryDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ReportsBeingInStationaryDialog", "Интервал", None))
        self.lblLimitDays.setText(_translate("ReportsBeingInStationaryDialog", "Находился менее", None))
        self.label.setText(_translate("ReportsBeingInStationaryDialog", "суток", None))
        self.edtMKBFrom.setInputMask(_translate("ReportsBeingInStationaryDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ReportsBeingInStationaryDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("ReportsBeingInStationaryDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ReportsBeingInStationaryDialog", "Z99.9", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
