# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportDoctorPreCalcSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportDoctorPreCalcSetupDialog(object):
    def setupUi(self, ReportDoctorPreCalcSetupDialog):
        ReportDoctorPreCalcSetupDialog.setObjectName(_fromUtf8("ReportDoctorPreCalcSetupDialog"))
        ReportDoctorPreCalcSetupDialog.resize(457, 664)
        self.gridLayout_3 = QtGui.QGridLayout(ReportDoctorPreCalcSetupDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pnlPodtv = QtGui.QWidget(ReportDoctorPreCalcSetupDialog)
        self.pnlPodtv.setObjectName(_fromUtf8("pnlPodtv"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pnlPodtv)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblBegDateConfirmation = QtGui.QLabel(self.pnlPodtv)
        self.lblBegDateConfirmation.setEnabled(True)
        self.lblBegDateConfirmation.setObjectName(_fromUtf8("lblBegDateConfirmation"))
        self.gridLayout_4.addWidget(self.lblBegDateConfirmation, 1, 0, 1, 1)
        self.lblEndDateConfirmation = QtGui.QLabel(self.pnlPodtv)
        self.lblEndDateConfirmation.setEnabled(True)
        self.lblEndDateConfirmation.setObjectName(_fromUtf8("lblEndDateConfirmation"))
        self.gridLayout_4.addWidget(self.lblEndDateConfirmation, 2, 0, 1, 1)
        self.edtConfirmationEndDate = CDateEdit(self.pnlPodtv)
        self.edtConfirmationEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtConfirmationEndDate.sizePolicy().hasHeightForWidth())
        self.edtConfirmationEndDate.setSizePolicy(sizePolicy)
        self.edtConfirmationEndDate.setObjectName(_fromUtf8("edtConfirmationEndDate"))
        self.gridLayout_4.addWidget(self.edtConfirmationEndDate, 2, 1, 1, 1)
        self.lblConfirmationType = QtGui.QLabel(self.pnlPodtv)
        self.lblConfirmationType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConfirmationType.sizePolicy().hasHeightForWidth())
        self.lblConfirmationType.setSizePolicy(sizePolicy)
        self.lblConfirmationType.setObjectName(_fromUtf8("lblConfirmationType"))
        self.gridLayout_4.addWidget(self.lblConfirmationType, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 2, 1, 1)
        self.edtConfirmationBegDate = CDateEdit(self.pnlPodtv)
        self.edtConfirmationBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtConfirmationBegDate.sizePolicy().hasHeightForWidth())
        self.edtConfirmationBegDate.setSizePolicy(sizePolicy)
        self.edtConfirmationBegDate.setObjectName(_fromUtf8("edtConfirmationBegDate"))
        self.gridLayout_4.addWidget(self.edtConfirmationBegDate, 1, 1, 1, 2)
        self.cmbConfirmationType = QtGui.QComboBox(self.pnlPodtv)
        self.cmbConfirmationType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConfirmationType.sizePolicy().hasHeightForWidth())
        self.cmbConfirmationType.setSizePolicy(sizePolicy)
        self.cmbConfirmationType.setObjectName(_fromUtf8("cmbConfirmationType"))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.cmbConfirmationType.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbConfirmationType, 0, 1, 1, 2)
        self.gridLayout_3.addWidget(self.pnlPodtv, 9, 0, 1, 4)
        self.pnlDate = QtGui.QWidget(ReportDoctorPreCalcSetupDialog)
        self.pnlDate.setObjectName(_fromUtf8("pnlDate"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pnlDate)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbDateType = QtGui.QComboBox(self.pnlDate)
        self.cmbDateType.setObjectName(_fromUtf8("cmbDateType"))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDateType, 1, 0, 1, 3)
        self.lblEndDate = QtGui.QLabel(self.pnlDate)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 4, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.pnlDate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 3, 0, 1, 1)
        self.edtEndDate = CDateEdit(self.pnlDate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_2.addWidget(self.edtEndDate, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 2, 1, 1)
        self.edtBegDate = CDateEdit(self.pnlDate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_2.addWidget(self.edtBegDate, 3, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.pnlDate)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_2.addWidget(self.lblDate, 0, 0, 1, 1)
        self.chkTariffing = QtGui.QCheckBox(self.pnlDate)
        self.chkTariffing.setObjectName(_fromUtf8("chkTariffing"))
        self.gridLayout_2.addWidget(self.chkTariffing, 5, 0, 1, 1)
        self.cmbTariffing = QtGui.QComboBox(self.pnlDate)
        self.cmbTariffing.setEnabled(False)
        self.cmbTariffing.setObjectName(_fromUtf8("cmbTariffing"))
        self.cmbTariffing.addItem(_fromUtf8(""))
        self.cmbTariffing.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbTariffing, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.pnlDate)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 3)
        self.gridLayout_3.addWidget(self.pnlDate, 0, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(ReportDoctorPreCalcSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 19, 0, 1, 4)
        self.cmbIdentifierType = CRBComboBox(ReportDoctorPreCalcSetupDialog)
        self.cmbIdentifierType.setObjectName(_fromUtf8("cmbIdentifierType"))
        self.gridLayout_3.addWidget(self.cmbIdentifierType, 7, 1, 1, 3)
        self.cmbActionType = CActionTypeComboBoxEx(ReportDoctorPreCalcSetupDialog)
        self.cmbActionType.setEnabled(False)
        self.cmbActionType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout_3.addWidget(self.cmbActionType, 15, 1, 1, 3)
        self.line = QtGui.QFrame(ReportDoctorPreCalcSetupDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 4)
        self.cmbActionTypeClass = QtGui.QComboBox(ReportDoctorPreCalcSetupDialog)
        self.cmbActionTypeClass.setEnabled(False)
        self.cmbActionTypeClass.setObjectName(_fromUtf8("cmbActionTypeClass"))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.cmbActionTypeClass.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbActionTypeClass, 14, 1, 1, 3)
        self.chkConfirmation = QtGui.QCheckBox(ReportDoctorPreCalcSetupDialog)
        self.chkConfirmation.setObjectName(_fromUtf8("chkConfirmation"))
        self.gridLayout_3.addWidget(self.chkConfirmation, 8, 0, 1, 3)
        self.lblActionTypeClass = QtGui.QLabel(ReportDoctorPreCalcSetupDialog)
        self.lblActionTypeClass.setObjectName(_fromUtf8("lblActionTypeClass"))
        self.gridLayout_3.addWidget(self.lblActionTypeClass, 14, 0, 1, 1)
        self.lblIdentifierType = QtGui.QLabel(ReportDoctorPreCalcSetupDialog)
        self.lblIdentifierType.setObjectName(_fromUtf8("lblIdentifierType"))
        self.gridLayout_3.addWidget(self.lblIdentifierType, 7, 0, 1, 1)
        self.chkDetailActions = QtGui.QCheckBox(ReportDoctorPreCalcSetupDialog)
        self.chkDetailActions.setObjectName(_fromUtf8("chkDetailActions"))
        self.gridLayout_3.addWidget(self.chkDetailActions, 16, 0, 1, 4)
        self.chkDetailFinance = QtGui.QCheckBox(ReportDoctorPreCalcSetupDialog)
        self.chkDetailFinance.setObjectName(_fromUtf8("chkDetailFinance"))
        self.gridLayout_3.addWidget(self.chkDetailFinance, 17, 0, 1, 4)
        self.lblActionType = QtGui.QLabel(ReportDoctorPreCalcSetupDialog)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout_3.addWidget(self.lblActionType, 15, 0, 1, 1)
        self.chkActionClass = QtGui.QCheckBox(ReportDoctorPreCalcSetupDialog)
        self.chkActionClass.setObjectName(_fromUtf8("chkActionClass"))
        self.gridLayout_3.addWidget(self.chkActionClass, 13, 0, 1, 2)
        self.pnlPerson = QtGui.QWidget(ReportDoctorPreCalcSetupDialog)
        self.pnlPerson.setObjectName(_fromUtf8("pnlPerson"))
        self.gridLayout = QtGui.QGridLayout(self.pnlPerson)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSpeciality = QtGui.QLabel(self.pnlPerson)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.pnlPerson)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 3, 3, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.pnlPerson)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 5, 3, 1, 1)
        self.lblDoctor = QtGui.QLabel(self.pnlPerson)
        self.lblDoctor.setObjectName(_fromUtf8("lblDoctor"))
        self.gridLayout.addWidget(self.lblDoctor, 5, 0, 1, 1)
        self.lblSetPerson = QtGui.QLabel(self.pnlPerson)
        self.lblSetPerson.setObjectName(_fromUtf8("lblSetPerson"))
        self.gridLayout.addWidget(self.lblSetPerson, 2, 1, 1, 1)
        self.cmbSetSpeciality = CRBComboBox(self.pnlPerson)
        self.cmbSetSpeciality.setObjectName(_fromUtf8("cmbSetSpeciality"))
        self.gridLayout.addWidget(self.cmbSetSpeciality, 4, 1, 1, 1)
        self.cmbSpeciality = CRBComboBox(self.pnlPerson)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 4, 3, 1, 1)
        self.line_3 = QtGui.QFrame(self.pnlPerson)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 3, 2, 3, 1)
        self.cmbSetPerson = CPersonComboBoxEx(self.pnlPerson)
        self.cmbSetPerson.setObjectName(_fromUtf8("cmbSetPerson"))
        self.gridLayout.addWidget(self.cmbSetPerson, 5, 1, 1, 1)
        self.lblPerson = QtGui.QLabel(self.pnlPerson)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 2, 3, 1, 1)
        self.cmbSetOrgStructure = COrgStructureComboBox(self.pnlPerson)
        self.cmbSetOrgStructure.setObjectName(_fromUtf8("cmbSetOrgStructure"))
        self.gridLayout.addWidget(self.cmbSetOrgStructure, 3, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.pnlPerson)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 3, 0, 1, 1)
        self.chkDetailOrgStructure = QtGui.QCheckBox(self.pnlPerson)
        self.chkDetailOrgStructure.setEnabled(True)
        self.chkDetailOrgStructure.setObjectName(_fromUtf8("chkDetailOrgStructure"))
        self.gridLayout.addWidget(self.chkDetailOrgStructure, 0, 0, 1, 4)
        self.chkDetailSpeciality = QtGui.QCheckBox(self.pnlPerson)
        self.chkDetailSpeciality.setObjectName(_fromUtf8("chkDetailSpeciality"))
        self.gridLayout.addWidget(self.chkDetailSpeciality, 1, 0, 1, 4)
        self.gridLayout_3.addWidget(self.pnlPerson, 2, 0, 2, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 18, 1, 1, 1)
        self.line_2 = QtGui.QFrame(ReportDoctorPreCalcSetupDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 4)
        self.btnFinanceTypeList = QtGui.QPushButton(ReportDoctorPreCalcSetupDialog)
        self.btnFinanceTypeList.setObjectName(_fromUtf8("btnFinanceTypeList"))
        self.gridLayout_3.addWidget(self.btnFinanceTypeList, 6, 0, 1, 1)
        self.lblFinanceTypeList = QtGui.QLabel(ReportDoctorPreCalcSetupDialog)
        self.lblFinanceTypeList.setWordWrap(True)
        self.lblFinanceTypeList.setObjectName(_fromUtf8("lblFinanceTypeList"))
        self.gridLayout_3.addWidget(self.lblFinanceTypeList, 6, 1, 1, 3)
        self.btnEventTypeList = QtGui.QPushButton(ReportDoctorPreCalcSetupDialog)
        self.btnEventTypeList.setObjectName(_fromUtf8("btnEventTypeList"))
        self.gridLayout_3.addWidget(self.btnEventTypeList, 5, 0, 1, 1)
        self.lblEventTypeList = QtGui.QLabel(ReportDoctorPreCalcSetupDialog)
        self.lblEventTypeList.setWordWrap(True)
        self.lblEventTypeList.setObjectName(_fromUtf8("lblEventTypeList"))
        self.gridLayout_3.addWidget(self.lblEventTypeList, 5, 1, 1, 3)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblActionTypeClass.setBuddy(self.cmbActionTypeClass)
        self.lblActionType.setBuddy(self.cmbActionType)

        self.retranslateUi(ReportDoctorPreCalcSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportDoctorPreCalcSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportDoctorPreCalcSetupDialog.reject)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbConfirmationType.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtConfirmationBegDate.setEnabled)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtConfirmationEndDate.setEnabled)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionTypeClass.setEnabled)
        QtCore.QObject.connect(self.chkActionClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionType.setEnabled)
        QtCore.QObject.connect(self.chkTariffing, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbTariffing.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ReportDoctorPreCalcSetupDialog)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbDateType, self.edtBegDate)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.edtEndDate, self.chkTariffing)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkTariffing, self.cmbTariffing)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbTariffing, self.chkDetailOrgStructure)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkDetailOrgStructure, self.chkDetailSpeciality)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkDetailSpeciality, self.cmbSetOrgStructure)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbSetOrgStructure, self.cmbOrgStructure)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSetSpeciality)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbSetSpeciality, self.cmbSpeciality)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbSpeciality, self.cmbSetPerson)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbSetPerson, self.cmbPerson)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbPerson, self.btnEventTypeList)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.btnEventTypeList, self.btnFinanceTypeList)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.btnFinanceTypeList, self.cmbIdentifierType)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbIdentifierType, self.chkConfirmation)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkConfirmation, self.cmbConfirmationType)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbConfirmationType, self.edtConfirmationBegDate)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.edtConfirmationBegDate, self.edtConfirmationEndDate)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.edtConfirmationEndDate, self.chkActionClass)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkActionClass, self.cmbActionTypeClass)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbActionTypeClass, self.cmbActionType)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.cmbActionType, self.chkDetailActions)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkDetailActions, self.chkDetailFinance)
        ReportDoctorPreCalcSetupDialog.setTabOrder(self.chkDetailFinance, self.buttonBox)

    def retranslateUi(self, ReportDoctorPreCalcSetupDialog):
        ReportDoctorPreCalcSetupDialog.setWindowTitle(_translate("ReportDoctorPreCalcSetupDialog", "Dialog", None))
        self.lblBegDateConfirmation.setText(_translate("ReportDoctorPreCalcSetupDialog", "Начало периода подтверждения:", None))
        self.lblEndDateConfirmation.setText(_translate("ReportDoctorPreCalcSetupDialog", "Окончание периода подтверждения:", None))
        self.lblConfirmationType.setText(_translate("ReportDoctorPreCalcSetupDialog", "Тип подтверждения:", None))
        self.cmbConfirmationType.setItemText(0, _translate("ReportDoctorPreCalcSetupDialog", "не выставлено", None))
        self.cmbConfirmationType.setItemText(1, _translate("ReportDoctorPreCalcSetupDialog", "выставлено", None))
        self.cmbConfirmationType.setItemText(2, _translate("ReportDoctorPreCalcSetupDialog", "оплачено", None))
        self.cmbConfirmationType.setItemText(3, _translate("ReportDoctorPreCalcSetupDialog", "отказано", None))
        self.cmbDateType.setItemText(0, _translate("ReportDoctorPreCalcSetupDialog", "Выполнения", None))
        self.cmbDateType.setItemText(1, _translate("ReportDoctorPreCalcSetupDialog", "Назначения", None))
        self.cmbDateType.setItemText(2, _translate("ReportDoctorPreCalcSetupDialog", "Начала", None))
        self.cmbDateType.setItemText(3, _translate("ReportDoctorPreCalcSetupDialog", "Планирования", None))
        self.lblEndDate.setText(_translate("ReportDoctorPreCalcSetupDialog", "Дата &окончания периода", None))
        self.lblBegDate.setText(_translate("ReportDoctorPreCalcSetupDialog", "Дата &начала периода", None))
        self.lblDate.setText(_translate("ReportDoctorPreCalcSetupDialog", "Дата мероприятия:", None))
        self.chkTariffing.setText(_translate("ReportDoctorPreCalcSetupDialog", "Тарифицируемость", None))
        self.cmbTariffing.setItemText(0, _translate("ReportDoctorPreCalcSetupDialog", "Нет", None))
        self.cmbTariffing.setItemText(1, _translate("ReportDoctorPreCalcSetupDialog", "Да", None))
        self.label.setText(_translate("ReportDoctorPreCalcSetupDialog", "Обращения отбираются по дате выполнения", None))
        self.cmbActionTypeClass.setItemText(0, _translate("ReportDoctorPreCalcSetupDialog", "Статус", None))
        self.cmbActionTypeClass.setItemText(1, _translate("ReportDoctorPreCalcSetupDialog", "Диагностика", None))
        self.cmbActionTypeClass.setItemText(2, _translate("ReportDoctorPreCalcSetupDialog", "Лечение", None))
        self.cmbActionTypeClass.setItemText(3, _translate("ReportDoctorPreCalcSetupDialog", "Прочие мероприятия", None))
        self.chkConfirmation.setText(_translate("ReportDoctorPreCalcSetupDialog", "Подтверждение оплаты", None))
        self.lblActionTypeClass.setText(_translate("ReportDoctorPreCalcSetupDialog", "Кла&сс", None))
        self.lblIdentifierType.setText(_translate("ReportDoctorPreCalcSetupDialog", "Тип идентификатора", None))
        self.chkDetailActions.setText(_translate("ReportDoctorPreCalcSetupDialog", "Детализировать услуги", None))
        self.chkDetailFinance.setText(_translate("ReportDoctorPreCalcSetupDialog", "Детализировать по типу финансирования", None))
        self.lblActionType.setText(_translate("ReportDoctorPreCalcSetupDialog", "&Мероприятие", None))
        self.chkActionClass.setText(_translate("ReportDoctorPreCalcSetupDialog", "Учитывать класс", None))
        self.lblSpeciality.setText(_translate("ReportDoctorPreCalcSetupDialog", "Специальность", None))
        self.lblDoctor.setText(_translate("ReportDoctorPreCalcSetupDialog", "Врач", None))
        self.lblSetPerson.setText(_translate("ReportDoctorPreCalcSetupDialog", "Назначил", None))
        self.lblPerson.setText(_translate("ReportDoctorPreCalcSetupDialog", "Выполнил", None))
        self.lblOrgStructure.setText(_translate("ReportDoctorPreCalcSetupDialog", "Подразделение", None))
        self.chkDetailOrgStructure.setText(_translate("ReportDoctorPreCalcSetupDialog", "Группировать по подразделениям", None))
        self.chkDetailSpeciality.setText(_translate("ReportDoctorPreCalcSetupDialog", "Группировать по специальности", None))
        self.btnFinanceTypeList.setText(_translate("ReportDoctorPreCalcSetupDialog", "Тип финансирования", None))
        self.lblFinanceTypeList.setText(_translate("ReportDoctorPreCalcSetupDialog", "  не задано", None))
        self.btnEventTypeList.setText(_translate("ReportDoctorPreCalcSetupDialog", "&Тип события", None))
        self.lblEventTypeList.setText(_translate("ReportDoctorPreCalcSetupDialog", "  не задано", None))

from Events.ActionTypeComboBoxEx import CActionTypeComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
