# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportLengthOfStayInHospital.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportLengthOfStayInHospitalDialog(object):
    def setupUi(self, ReportLengthOfStayInHospitalDialog):
        ReportLengthOfStayInHospitalDialog.setObjectName(_fromUtf8("ReportLengthOfStayInHospitalDialog"))
        ReportLengthOfStayInHospitalDialog.resize(408, 312)
        self.gridLayout = QtGui.QGridLayout(ReportLengthOfStayInHospitalDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegSetDateInfo = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblBegSetDateInfo.setObjectName(_fromUtf8("lblBegSetDateInfo"))
        self.gridLayout.addWidget(self.lblBegSetDateInfo, 0, 2, 1, 2)
        self.lblBegSetDate = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblBegSetDate.setObjectName(_fromUtf8("lblBegSetDate"))
        self.gridLayout.addWidget(self.lblBegSetDate, 0, 0, 1, 1)
        self.lblEndSetDateInfo = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEndSetDateInfo.setObjectName(_fromUtf8("lblEndSetDateInfo"))
        self.gridLayout.addWidget(self.lblEndSetDateInfo, 1, 2, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportLengthOfStayInHospitalDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 7, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportLengthOfStayInHospitalDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 7, 1, 1, 3)
        self.edtEndSetDate = CDateEdit(ReportLengthOfStayInHospitalDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndSetDate.sizePolicy().hasHeightForWidth())
        self.edtEndSetDate.setSizePolicy(sizePolicy)
        self.edtEndSetDate.setCalendarPopup(True)
        self.edtEndSetDate.setObjectName(_fromUtf8("edtEndSetDate"))
        self.gridLayout.addWidget(self.edtEndSetDate, 1, 1, 1, 1)
        self.lblEventType = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 5, 0, 1, 1)
        self.cmbEventType = CRBComboBox(ReportLengthOfStayInHospitalDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 5, 1, 1, 3)
        self.lblBegExecDate = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblBegExecDate.setObjectName(_fromUtf8("lblBegExecDate"))
        self.gridLayout.addWidget(self.lblBegExecDate, 3, 0, 1, 1)
        self.edtBegExecDate = QtGui.QDateEdit(ReportLengthOfStayInHospitalDialog)
        self.edtBegExecDate.setObjectName(_fromUtf8("edtBegExecDate"))
        self.gridLayout.addWidget(self.edtBegExecDate, 3, 1, 1, 1)
        self.lblEndExecDateInfo = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEndExecDateInfo.setObjectName(_fromUtf8("lblEndExecDateInfo"))
        self.gridLayout.addWidget(self.lblEndExecDateInfo, 4, 2, 1, 2)
        self.lblEndExecDate = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEndExecDate.setObjectName(_fromUtf8("lblEndExecDate"))
        self.gridLayout.addWidget(self.lblEndExecDate, 4, 0, 1, 1)
        self.edtEndExecDate = QtGui.QDateEdit(ReportLengthOfStayInHospitalDialog)
        self.edtEndExecDate.setObjectName(_fromUtf8("edtEndExecDate"))
        self.gridLayout.addWidget(self.edtEndExecDate, 4, 1, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 8, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportLengthOfStayInHospitalDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 8, 1, 1, 3)
        self.lblMKB = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 9, 0, 1, 1)
        self.lblBegExecDateInfo = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblBegExecDateInfo.setObjectName(_fromUtf8("lblBegExecDateInfo"))
        self.gridLayout.addWidget(self.lblBegExecDateInfo, 3, 2, 1, 2)
        self.cmbMKBFilter = QtGui.QComboBox(ReportLengthOfStayInHospitalDialog)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMKBFilter, 9, 1, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(ReportLengthOfStayInHospitalDialog)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout.addWidget(self.edtMKBFrom, 9, 2, 1, 1)
        self.edtMKBTo = CICDCodeEdit(ReportLengthOfStayInHospitalDialog)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout.addWidget(self.edtMKBTo, 9, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.edtBegSetDate = CDateEdit(ReportLengthOfStayInHospitalDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegSetDate.sizePolicy().hasHeightForWidth())
        self.edtBegSetDate.setSizePolicy(sizePolicy)
        self.edtBegSetDate.setCalendarPopup(True)
        self.edtBegSetDate.setObjectName(_fromUtf8("edtBegSetDate"))
        self.gridLayout.addWidget(self.edtBegSetDate, 0, 1, 1, 1)
        self.lblEndSetDate = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEndSetDate.setObjectName(_fromUtf8("lblEndSetDate"))
        self.gridLayout.addWidget(self.lblEndSetDate, 1, 0, 1, 1)
        self.cmbEventStatus = QtGui.QComboBox(ReportLengthOfStayInHospitalDialog)
        self.cmbEventStatus.setObjectName(_fromUtf8("cmbEventStatus"))
        self.cmbEventStatus.addItem(_fromUtf8(""))
        self.cmbEventStatus.addItem(_fromUtf8(""))
        self.cmbEventStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEventStatus, 2, 1, 1, 3)
        self.lblEventStatus = QtGui.QLabel(ReportLengthOfStayInHospitalDialog)
        self.lblEventStatus.setObjectName(_fromUtf8("lblEventStatus"))
        self.gridLayout.addWidget(self.lblEventStatus, 2, 0, 1, 1)
        self.lblBegSetDate.setBuddy(self.edtBegSetDate)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblEndSetDate.setBuddy(self.edtEndSetDate)

        self.retranslateUi(ReportLengthOfStayInHospitalDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportLengthOfStayInHospitalDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportLengthOfStayInHospitalDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportLengthOfStayInHospitalDialog)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtBegSetDate, self.edtEndSetDate)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtEndSetDate, self.cmbEventStatus)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.cmbEventStatus, self.edtBegExecDate)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtBegExecDate, self.edtEndExecDate)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtEndExecDate, self.cmbEventType)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.cmbPerson, self.cmbMKBFilter)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        ReportLengthOfStayInHospitalDialog.setTabOrder(self.edtMKBTo, self.buttonBox)

    def retranslateUi(self, ReportLengthOfStayInHospitalDialog):
        ReportLengthOfStayInHospitalDialog.setWindowTitle(_translate("ReportLengthOfStayInHospitalDialog", "Dialog", None))
        self.lblBegSetDateInfo.setText(_translate("ReportLengthOfStayInHospitalDialog", "Начало события", None))
        self.lblBegSetDate.setText(_translate("ReportLengthOfStayInHospitalDialog", "Дата &начала периода", None))
        self.lblEndSetDateInfo.setText(_translate("ReportLengthOfStayInHospitalDialog", "Начало события", None))
        self.lblOrgStructure.setText(_translate("ReportLengthOfStayInHospitalDialog", "Подразделение", None))
        self.edtEndSetDate.setDisplayFormat(_translate("ReportLengthOfStayInHospitalDialog", "dd.MM.yyyy", None))
        self.lblEventType.setText(_translate("ReportLengthOfStayInHospitalDialog", "Тип события", None))
        self.lblBegExecDate.setText(_translate("ReportLengthOfStayInHospitalDialog", "Дата начала периода", None))
        self.lblEndExecDateInfo.setText(_translate("ReportLengthOfStayInHospitalDialog", "Окончание события", None))
        self.lblEndExecDate.setText(_translate("ReportLengthOfStayInHospitalDialog", "Дата окончания периода", None))
        self.lblPerson.setText(_translate("ReportLengthOfStayInHospitalDialog", "Врач", None))
        self.lblMKB.setText(_translate("ReportLengthOfStayInHospitalDialog", "Коды диагнозов по &МКБ", None))
        self.lblBegExecDateInfo.setText(_translate("ReportLengthOfStayInHospitalDialog", "Окончание события", None))
        self.cmbMKBFilter.setItemText(0, _translate("ReportLengthOfStayInHospitalDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("ReportLengthOfStayInHospitalDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("ReportLengthOfStayInHospitalDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("ReportLengthOfStayInHospitalDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("ReportLengthOfStayInHospitalDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("ReportLengthOfStayInHospitalDialog", "Z99.9", None))
        self.edtBegSetDate.setDisplayFormat(_translate("ReportLengthOfStayInHospitalDialog", "dd.MM.yyyy", None))
        self.lblEndSetDate.setText(_translate("ReportLengthOfStayInHospitalDialog", "Дата &окончания периода", None))
        self.cmbEventStatus.setItemText(0, _translate("ReportLengthOfStayInHospitalDialog", "не задано", None))
        self.cmbEventStatus.setItemText(1, _translate("ReportLengthOfStayInHospitalDialog", "закрытые", None))
        self.cmbEventStatus.setItemText(2, _translate("ReportLengthOfStayInHospitalDialog", "открытые", None))
        self.lblEventStatus.setText(_translate("ReportLengthOfStayInHospitalDialog", "Статус события", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox
