# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\ReportNumberResidentsAddressSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportNumberResidentsAddressSetup(object):
    def setupUi(self, ReportNumberResidentsAddressSetup):
        ReportNumberResidentsAddressSetup.setObjectName(_fromUtf8("ReportNumberResidentsAddressSetup"))
        ReportNumberResidentsAddressSetup.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportNumberResidentsAddressSetup.resize(440, 250)
        ReportNumberResidentsAddressSetup.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ReportNumberResidentsAddressSetup)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frmAge = QtGui.QFrame(ReportNumberResidentsAddressSetup)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setContentsMargins(0, 0, 0, 4)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frmAge, 1, 1, 1, 3)
        self.cmbAttachType = CRBComboBox(ReportNumberResidentsAddressSetup)
        self.cmbAttachType.setObjectName(_fromUtf8("cmbAttachType"))
        self.gridLayout.addWidget(self.cmbAttachType, 6, 1, 1, 3)
        self.label = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.lblArea = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.gridLayout.addWidget(self.lblArea, 3, 0, 1, 1)
        self.lblSex = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 0, 0, 1, 1)
        self.cmbAttachCategory = QtGui.QComboBox(ReportNumberResidentsAddressSetup)
        self.cmbAttachCategory.setObjectName(_fromUtf8("cmbAttachCategory"))
        self.cmbAttachCategory.addItem(_fromUtf8(""))
        self.cmbAttachCategory.addItem(_fromUtf8(""))
        self.cmbAttachCategory.addItem(_fromUtf8(""))
        self.cmbAttachCategory.addItem(_fromUtf8(""))
        self.cmbAttachCategory.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAttachCategory, 4, 1, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 2)
        self.lblAttachType = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.lblAttachType.setObjectName(_fromUtf8("lblAttachType"))
        self.gridLayout.addWidget(self.lblAttachType, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtAttachBegDate = CDateEdit(ReportNumberResidentsAddressSetup)
        self.edtAttachBegDate.setCalendarPopup(True)
        self.edtAttachBegDate.setObjectName(_fromUtf8("edtAttachBegDate"))
        self.horizontalLayout.addWidget(self.edtAttachBegDate)
        self.label_3 = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.edtAttachEndDate = CDateEdit(ReportNumberResidentsAddressSetup)
        self.edtAttachEndDate.setCalendarPopup(True)
        self.edtAttachEndDate.setObjectName(_fromUtf8("edtAttachEndDate"))
        self.horizontalLayout.addWidget(self.edtAttachEndDate)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 3)
        self.cmbArea = CPolyclinicComboBox(ReportNumberResidentsAddressSetup)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout.addWidget(self.cmbArea, 3, 1, 1, 3)
        self.cmbSex = QtGui.QComboBox(ReportNumberResidentsAddressSetup)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 0, 1, 1, 1)
        self.lblAge = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportNumberResidentsAddressSetup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 3, 1, 1)
        self.lblAddressType = QtGui.QLabel(ReportNumberResidentsAddressSetup)
        self.lblAddressType.setObjectName(_fromUtf8("lblAddressType"))
        self.gridLayout.addWidget(self.lblAddressType, 2, 0, 1, 1)
        self.cmbAddressType = QtGui.QComboBox(ReportNumberResidentsAddressSetup)
        self.cmbAddressType.setObjectName(_fromUtf8("cmbAddressType"))
        self.cmbAddressType.addItem(_fromUtf8(""))
        self.cmbAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAddressType, 2, 1, 1, 3)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblArea.setBuddy(self.cmbArea)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)

        self.retranslateUi(ReportNumberResidentsAddressSetup)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportNumberResidentsAddressSetup.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportNumberResidentsAddressSetup.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportNumberResidentsAddressSetup)
        ReportNumberResidentsAddressSetup.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportNumberResidentsAddressSetup.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportNumberResidentsAddressSetup.setTabOrder(self.edtAgeTo, self.cmbArea)
        ReportNumberResidentsAddressSetup.setTabOrder(self.cmbArea, self.cmbAttachCategory)
        ReportNumberResidentsAddressSetup.setTabOrder(self.cmbAttachCategory, self.edtAttachBegDate)
        ReportNumberResidentsAddressSetup.setTabOrder(self.edtAttachBegDate, self.edtAttachEndDate)
        ReportNumberResidentsAddressSetup.setTabOrder(self.edtAttachEndDate, self.cmbAttachType)
        ReportNumberResidentsAddressSetup.setTabOrder(self.cmbAttachType, self.buttonBox)

    def retranslateUi(self, ReportNumberResidentsAddressSetup):
        ReportNumberResidentsAddressSetup.setWindowTitle(_translate("ReportNumberResidentsAddressSetup", "параметры отчёта", None))
        self.lblAgeTo.setText(_translate("ReportNumberResidentsAddressSetup", "по", None))
        self.lblAgeYears.setText(_translate("ReportNumberResidentsAddressSetup", "лет", None))
        self.label.setText(_translate("ReportNumberResidentsAddressSetup", "Дата прикрепления", None))
        self.lblArea.setText(_translate("ReportNumberResidentsAddressSetup", "ЛПУ прикрепления", None))
        self.lblSex.setText(_translate("ReportNumberResidentsAddressSetup", "По&л", None))
        self.cmbAttachCategory.setItemText(0, _translate("ReportNumberResidentsAddressSetup", "не задано", None))
        self.cmbAttachCategory.setItemText(1, _translate("ReportNumberResidentsAddressSetup", "-", None))
        self.cmbAttachCategory.setItemText(2, _translate("ReportNumberResidentsAddressSetup", "Постоянное", None))
        self.cmbAttachCategory.setItemText(3, _translate("ReportNumberResidentsAddressSetup", "Временное", None))
        self.cmbAttachCategory.setItemText(4, _translate("ReportNumberResidentsAddressSetup", "Выбыл", None))
        self.lblAttachType.setText(_translate("ReportNumberResidentsAddressSetup", "Прикрепление категория", None))
        self.label_2.setText(_translate("ReportNumberResidentsAddressSetup", "Тип прикрепления", None))
        self.edtAttachBegDate.setDisplayFormat(_translate("ReportNumberResidentsAddressSetup", "dd.MM.yyyy", None))
        self.label_3.setText(_translate("ReportNumberResidentsAddressSetup", "по", None))
        self.edtAttachEndDate.setDisplayFormat(_translate("ReportNumberResidentsAddressSetup", "dd.MM.yyyy", None))
        self.cmbSex.setItemText(1, _translate("ReportNumberResidentsAddressSetup", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportNumberResidentsAddressSetup", "Ж", None))
        self.lblAge.setText(_translate("ReportNumberResidentsAddressSetup", "Во&зраст с", None))
        self.lblAddressType.setText(_translate("ReportNumberResidentsAddressSetup", "Тип адреса", None))
        self.cmbAddressType.setItemText(0, _translate("ReportNumberResidentsAddressSetup", "Регистрация", None))
        self.cmbAddressType.setItemText(1, _translate("ReportNumberResidentsAddressSetup", "Проживание", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
