# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\SpendingToClients.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SpendingToClientsSetup(object):
    def setupUi(self, SpendingToClientsSetup):
        SpendingToClientsSetup.setObjectName(_fromUtf8("SpendingToClientsSetup"))
        SpendingToClientsSetup.setWindowModality(QtCore.Qt.ApplicationModal)
        SpendingToClientsSetup.resize(420, 415)
        SpendingToClientsSetup.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(SpendingToClientsSetup)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(SpendingToClientsSetup)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        self.lblFinance = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 10, 0, 1, 2)
        self.lblClientId = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClientId.sizePolicy().hasHeightForWidth())
        self.lblClientId.setSizePolicy(sizePolicy)
        self.lblClientId.setObjectName(_fromUtf8("lblClientId"))
        self.gridLayout.addWidget(self.lblClientId, 12, 0, 1, 2)
        self.edtReasonDate = CDateEdit(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReasonDate.sizePolicy().hasHeightForWidth())
        self.edtReasonDate.setSizePolicy(sizePolicy)
        self.edtReasonDate.setCalendarPopup(True)
        self.edtReasonDate.setObjectName(_fromUtf8("edtReasonDate"))
        self.gridLayout.addWidget(self.edtReasonDate, 9, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(SpendingToClientsSetup)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 2)
        self.lblClass = QtGui.QLabel(SpendingToClientsSetup)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 3, 0, 1, 1)
        self.edtEndDate = CDateEdit(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        self.cmbNomenclature = CNomenclatureComboBox(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbNomenclature.sizePolicy().hasHeightForWidth())
        self.cmbNomenclature.setSizePolicy(sizePolicy)
        self.cmbNomenclature.setObjectName(_fromUtf8("cmbNomenclature"))
        self.gridLayout.addWidget(self.cmbNomenclature, 6, 2, 1, 1)
        self.edtReason = QtGui.QLineEdit(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReason.sizePolicy().hasHeightForWidth())
        self.edtReason.setSizePolicy(sizePolicy)
        self.edtReason.setObjectName(_fromUtf8("edtReason"))
        self.gridLayout.addWidget(self.edtReason, 8, 2, 1, 1)
        self.lblNomenclature = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNomenclature.sizePolicy().hasHeightForWidth())
        self.lblNomenclature.setSizePolicy(sizePolicy)
        self.lblNomenclature.setObjectName(_fromUtf8("lblNomenclature"))
        self.gridLayout.addWidget(self.lblNomenclature, 6, 0, 1, 1)
        self.cmbFinance = CRBComboBox(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFinance.sizePolicy().hasHeightForWidth())
        self.cmbFinance.setSizePolicy(sizePolicy)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 10, 2, 1, 1)
        self.lblType = QtGui.QLabel(SpendingToClientsSetup)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 5, 0, 1, 1)
        self.cmbType = CRBComboBox(SpendingToClientsSetup)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout.addWidget(self.cmbType, 5, 2, 1, 1)
        self.lblReason = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReason.sizePolicy().hasHeightForWidth())
        self.lblReason.setSizePolicy(sizePolicy)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 8, 0, 1, 1)
        self.lblReasonDate = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReasonDate.sizePolicy().hasHeightForWidth())
        self.lblReasonDate.setSizePolicy(sizePolicy)
        self.lblReasonDate.setObjectName(_fromUtf8("lblReasonDate"))
        self.gridLayout.addWidget(self.lblReasonDate, 9, 0, 1, 2)
        self.edtBegDate = CDateEdit(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(SpendingToClientsSetup)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.edtClientId = QtGui.QLineEdit(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtClientId.sizePolicy().hasHeightForWidth())
        self.edtClientId.setSizePolicy(sizePolicy)
        self.edtClientId.setObjectName(_fromUtf8("edtClientId"))
        self.gridLayout.addWidget(self.edtClientId, 12, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(SpendingToClientsSetup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 0, 1, 3)
        self.cmbOrgStructure = CStorageComboBox(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 2, 1, 1)
        self.cmbClass = CRBComboBox(SpendingToClientsSetup)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout.addWidget(self.cmbClass, 3, 2, 1, 1)
        self.lblKind = QtGui.QLabel(SpendingToClientsSetup)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout.addWidget(self.lblKind, 4, 0, 1, 1)
        self.cmbKind = CRBComboBox(SpendingToClientsSetup)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.gridLayout.addWidget(self.cmbKind, 4, 2, 1, 1)
        self.chkAdjustRefund = QtGui.QCheckBox(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAdjustRefund.sizePolicy().hasHeightForWidth())
        self.chkAdjustRefund.setSizePolicy(sizePolicy)
        self.chkAdjustRefund.setChecked(True)
        self.chkAdjustRefund.setObjectName(_fromUtf8("chkAdjustRefund"))
        self.gridLayout.addWidget(self.chkAdjustRefund, 11, 2, 1, 1)
        self.lblAdjustRefund = QtGui.QLabel(SpendingToClientsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAdjustRefund.sizePolicy().hasHeightForWidth())
        self.lblAdjustRefund.setSizePolicy(sizePolicy)
        self.lblAdjustRefund.setObjectName(_fromUtf8("lblAdjustRefund"))
        self.gridLayout.addWidget(self.lblAdjustRefund, 11, 0, 1, 2)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblFinance.setBuddy(self.cmbFinance)
        self.lblClientId.setBuddy(self.edtClientId)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblNomenclature.setBuddy(self.cmbNomenclature)
        self.lblType.setBuddy(self.cmbType)
        self.lblReason.setBuddy(self.edtReason)
        self.lblReasonDate.setBuddy(self.edtReasonDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblKind.setBuddy(self.cmbKind)
        self.lblAdjustRefund.setBuddy(self.chkAdjustRefund)

        self.retranslateUi(SpendingToClientsSetup)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SpendingToClientsSetup.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SpendingToClientsSetup.reject)
        QtCore.QMetaObject.connectSlotsByName(SpendingToClientsSetup)
        SpendingToClientsSetup.setTabOrder(self.edtBegDate, self.edtEndDate)
        SpendingToClientsSetup.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        SpendingToClientsSetup.setTabOrder(self.cmbOrgStructure, self.cmbClass)
        SpendingToClientsSetup.setTabOrder(self.cmbClass, self.cmbKind)
        SpendingToClientsSetup.setTabOrder(self.cmbKind, self.cmbType)
        SpendingToClientsSetup.setTabOrder(self.cmbType, self.cmbNomenclature)
        SpendingToClientsSetup.setTabOrder(self.cmbNomenclature, self.edtReason)
        SpendingToClientsSetup.setTabOrder(self.edtReason, self.edtReasonDate)
        SpendingToClientsSetup.setTabOrder(self.edtReasonDate, self.cmbFinance)
        SpendingToClientsSetup.setTabOrder(self.cmbFinance, self.chkAdjustRefund)
        SpendingToClientsSetup.setTabOrder(self.chkAdjustRefund, self.edtClientId)
        SpendingToClientsSetup.setTabOrder(self.edtClientId, self.buttonBox)

    def retranslateUi(self, SpendingToClientsSetup):
        SpendingToClientsSetup.setWindowTitle(_translate("SpendingToClientsSetup", "u\'Реестр списания ЛСиИМН на пациентов\'", None))
        self.lblBegDate.setText(_translate("SpendingToClientsSetup", "Дата &начала периода", None))
        self.lblFinance.setText(_translate("SpendingToClientsSetup", "Тип &финансирования", None))
        self.lblClientId.setText(_translate("SpendingToClientsSetup", "&Идентификатор пациента", None))
        self.lblOrgStructure.setText(_translate("SpendingToClientsSetup", "&Подразделение", None))
        self.lblClass.setText(_translate("SpendingToClientsSetup", "&Класс", None))
        self.lblNomenclature.setText(_translate("SpendingToClientsSetup", "Но&менклатура", None))
        self.lblType.setText(_translate("SpendingToClientsSetup", "&Тип", None))
        self.lblReason.setText(_translate("SpendingToClientsSetup", "&Основание", None))
        self.lblReasonDate.setText(_translate("SpendingToClientsSetup", "Д&ата основания", None))
        self.lblEndDate.setText(_translate("SpendingToClientsSetup", "Дата &окончания периода", None))
        self.edtClientId.setInputMask(_translate("SpendingToClientsSetup", "00000000000; ", None))
        self.lblKind.setText(_translate("SpendingToClientsSetup", "&Вид", None))
        self.chkAdjustRefund.setText(_translate("SpendingToClientsSetup", " ", None))
        self.lblAdjustRefund.setText(_translate("SpendingToClientsSetup", "Учитывать возврат", None))

from Orgs.OrgStructComboBoxes import CStorageComboBox
from Stock.NomenclatureComboBox import CNomenclatureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
