# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\SetupReportYearActions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SetupReportYearActionsDialog(object):
    def setupUi(self, SetupReportYearActionsDialog):
        SetupReportYearActionsDialog.setObjectName(_fromUtf8("SetupReportYearActionsDialog"))
        SetupReportYearActionsDialog.resize(483, 489)
        self.gridLayout = QtGui.QGridLayout(SetupReportYearActionsDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbTissueType = CRBComboBox(SetupReportYearActionsDialog)
        self.cmbTissueType.setEnabled(False)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout.addWidget(self.cmbTissueType, 8, 1, 1, 4)
        self.chkPersonDetail = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkPersonDetail.setObjectName(_fromUtf8("chkPersonDetail"))
        self.gridLayout.addWidget(self.chkPersonDetail, 15, 1, 1, 4)
        self.chkPerson = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPerson.sizePolicy().hasHeightForWidth())
        self.chkPerson.setSizePolicy(sizePolicy)
        self.chkPerson.setObjectName(_fromUtf8("chkPerson"))
        self.gridLayout.addWidget(self.chkPerson, 6, 0, 1, 1)
        self.cmbActionTypeGroup = CActionTypeComboBox(SetupReportYearActionsDialog)
        self.cmbActionTypeGroup.setEnabled(False)
        self.cmbActionTypeGroup.setObjectName(_fromUtf8("cmbActionTypeGroup"))
        self.gridLayout.addWidget(self.cmbActionTypeGroup, 3, 1, 1, 4)
        self.chkStatus = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkStatus.sizePolicy().hasHeightForWidth())
        self.chkStatus.setSizePolicy(sizePolicy)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout.addWidget(self.chkStatus, 4, 0, 1, 1)
        self.chkActionTypeGroup = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActionTypeGroup.sizePolicy().hasHeightForWidth())
        self.chkActionTypeGroup.setSizePolicy(sizePolicy)
        self.chkActionTypeGroup.setObjectName(_fromUtf8("chkActionTypeGroup"))
        self.gridLayout.addWidget(self.chkActionTypeGroup, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.chkPersonOSDetail = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkPersonOSDetail.setObjectName(_fromUtf8("chkPersonOSDetail"))
        self.gridLayout.addWidget(self.chkPersonOSDetail, 13, 1, 1, 4)
        self.chkTissueType = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkTissueType.setObjectName(_fromUtf8("chkTissueType"))
        self.gridLayout.addWidget(self.chkTissueType, 8, 0, 1, 1)
        self.cmbStatus = CActionStatusComboBox(SetupReportYearActionsDialog)
        self.cmbStatus.setEnabled(False)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.gridLayout.addWidget(self.cmbStatus, 4, 1, 1, 4)
        self.chkClass = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClass.sizePolicy().hasHeightForWidth())
        self.chkClass.setSizePolicy(sizePolicy)
        self.chkClass.setObjectName(_fromUtf8("chkClass"))
        self.gridLayout.addWidget(self.chkClass, 2, 0, 1, 1)
        self.edtBegDate = CDateEdit(SetupReportYearActionsDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.chkPersonDateDetail = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkPersonDateDetail.setEnabled(False)
        self.chkPersonDateDetail.setObjectName(_fromUtf8("chkPersonDateDetail"))
        self.gridLayout.addWidget(self.chkPersonDateDetail, 16, 1, 1, 4)
        self.chkFinance = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFinance.sizePolicy().hasHeightForWidth())
        self.chkFinance.setSizePolicy(sizePolicy)
        self.chkFinance.setObjectName(_fromUtf8("chkFinance"))
        self.gridLayout.addWidget(self.chkFinance, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(SetupReportYearActionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 18, 0, 1, 5)
        self.label = QtGui.QLabel(SetupReportYearActionsDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(SetupReportYearActionsDialog)
        self.cmbPerson.setEnabled(False)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 6, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 17, 0, 1, 5)
        self.chkOrgStructure = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkOrgStructure.sizePolicy().hasHeightForWidth())
        self.chkOrgStructure.setSizePolicy(sizePolicy)
        self.chkOrgStructure.setObjectName(_fromUtf8("chkOrgStructure"))
        self.gridLayout.addWidget(self.chkOrgStructure, 5, 0, 1, 1)
        self.chkAssistant = QtGui.QCheckBox(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAssistant.sizePolicy().hasHeightForWidth())
        self.chkAssistant.setSizePolicy(sizePolicy)
        self.chkAssistant.setObjectName(_fromUtf8("chkAssistant"))
        self.gridLayout.addWidget(self.chkAssistant, 7, 0, 1, 1)
        self.cmbClass = QtGui.QComboBox(SetupReportYearActionsDialog)
        self.cmbClass.setEnabled(False)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClass, 2, 1, 1, 4)
        self.lblDate = QtGui.QLabel(SetupReportYearActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.chkPersonOverall = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkPersonOverall.setObjectName(_fromUtf8("chkPersonOverall"))
        self.gridLayout.addWidget(self.chkPersonOverall, 14, 1, 1, 4)
        self.cmbOrgStructure = COrgStructureComboBox(SetupReportYearActionsDialog)
        self.cmbOrgStructure.setEnabled(False)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 5, 1, 1, 4)
        self.chkSex = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 11, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(SetupReportYearActionsDialog)
        self.cmbSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 11, 1, 1, 4)
        self.chkAge = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 10, 0, 1, 1)
        self.frmAge = QtGui.QFrame(SetupReportYearActionsDialog)
        self.frmAge.setEnabled(False)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lblAge = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.hboxlayout.addWidget(self.lblAge)
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeTo.sizePolicy().hasHeightForWidth())
        self.lblAgeTo.setSizePolicy(sizePolicy)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setProperty("value", 150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeYears.sizePolicy().hasHeightForWidth())
        self.lblAgeYears.setSizePolicy(sizePolicy)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frmAge, 10, 1, 1, 4)
        self.cmbFinance = CRBComboBox(SetupReportYearActionsDialog)
        self.cmbFinance.setEnabled(False)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 1, 1, 1, 4)
        self.edtEndDate = CDateEdit(SetupReportYearActionsDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 0, 3, 1, 1)
        self.cmbAssistant = CPersonComboBoxEx(SetupReportYearActionsDialog)
        self.cmbAssistant.setEnabled(False)
        self.cmbAssistant.setObjectName(_fromUtf8("cmbAssistant"))
        self.gridLayout.addWidget(self.cmbAssistant, 7, 1, 1, 4)
        self.chkLocality = QtGui.QCheckBox(SetupReportYearActionsDialog)
        self.chkLocality.setObjectName(_fromUtf8("chkLocality"))
        self.gridLayout.addWidget(self.chkLocality, 12, 0, 1, 1)
        self.cmbLocality = QtGui.QComboBox(SetupReportYearActionsDialog)
        self.cmbLocality.setEnabled(False)
        self.cmbLocality.setObjectName(_fromUtf8("cmbLocality"))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLocality, 12, 1, 1, 4)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)

        self.retranslateUi(SetupReportYearActionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SetupReportYearActionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SetupReportYearActionsDialog.reject)
        QtCore.QObject.connect(self.chkFinance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFinance.setEnabled)
        QtCore.QObject.connect(self.chkClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClass.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionTypeGroup.setEnabled)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.chkOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPerson.setEnabled)
        QtCore.QObject.connect(self.chkAssistant, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAssistant.setEnabled)
        QtCore.QObject.connect(self.chkTissueType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbTissueType.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frmAge.setEnabled)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkPersonDetail, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkPersonDateDetail.setEnabled)
        QtCore.QObject.connect(self.chkLocality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbLocality.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SetupReportYearActionsDialog)
        SetupReportYearActionsDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        SetupReportYearActionsDialog.setTabOrder(self.edtEndDate, self.chkFinance)
        SetupReportYearActionsDialog.setTabOrder(self.chkFinance, self.cmbFinance)
        SetupReportYearActionsDialog.setTabOrder(self.cmbFinance, self.chkClass)
        SetupReportYearActionsDialog.setTabOrder(self.chkClass, self.cmbClass)
        SetupReportYearActionsDialog.setTabOrder(self.cmbClass, self.chkActionTypeGroup)
        SetupReportYearActionsDialog.setTabOrder(self.chkActionTypeGroup, self.cmbActionTypeGroup)
        SetupReportYearActionsDialog.setTabOrder(self.cmbActionTypeGroup, self.chkStatus)
        SetupReportYearActionsDialog.setTabOrder(self.chkStatus, self.cmbStatus)
        SetupReportYearActionsDialog.setTabOrder(self.cmbStatus, self.chkOrgStructure)
        SetupReportYearActionsDialog.setTabOrder(self.chkOrgStructure, self.cmbOrgStructure)
        SetupReportYearActionsDialog.setTabOrder(self.cmbOrgStructure, self.chkPerson)
        SetupReportYearActionsDialog.setTabOrder(self.chkPerson, self.cmbPerson)
        SetupReportYearActionsDialog.setTabOrder(self.cmbPerson, self.chkAssistant)
        SetupReportYearActionsDialog.setTabOrder(self.chkAssistant, self.cmbAssistant)
        SetupReportYearActionsDialog.setTabOrder(self.cmbAssistant, self.chkTissueType)
        SetupReportYearActionsDialog.setTabOrder(self.chkTissueType, self.cmbTissueType)
        SetupReportYearActionsDialog.setTabOrder(self.cmbTissueType, self.chkAge)
        SetupReportYearActionsDialog.setTabOrder(self.chkAge, self.edtAgeFrom)
        SetupReportYearActionsDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        SetupReportYearActionsDialog.setTabOrder(self.edtAgeTo, self.chkSex)
        SetupReportYearActionsDialog.setTabOrder(self.chkSex, self.cmbSex)
        SetupReportYearActionsDialog.setTabOrder(self.cmbSex, self.chkLocality)
        SetupReportYearActionsDialog.setTabOrder(self.chkLocality, self.cmbLocality)
        SetupReportYearActionsDialog.setTabOrder(self.cmbLocality, self.chkPersonOSDetail)
        SetupReportYearActionsDialog.setTabOrder(self.chkPersonOSDetail, self.chkPersonOverall)
        SetupReportYearActionsDialog.setTabOrder(self.chkPersonOverall, self.chkPersonDetail)
        SetupReportYearActionsDialog.setTabOrder(self.chkPersonDetail, self.chkPersonDateDetail)
        SetupReportYearActionsDialog.setTabOrder(self.chkPersonDateDetail, self.buttonBox)

    def retranslateUi(self, SetupReportYearActionsDialog):
        SetupReportYearActionsDialog.setWindowTitle(_translate("SetupReportYearActionsDialog", "Dialog", None))
        self.chkPersonDetail.setText(_translate("SetupReportYearActionsDialog", "Отдельно по врачам", None))
        self.chkPerson.setText(_translate("SetupReportYearActionsDialog", "Исполнитель", None))
        self.chkStatus.setText(_translate("SetupReportYearActionsDialog", "Статус", None))
        self.chkActionTypeGroup.setText(_translate("SetupReportYearActionsDialog", "Группа", None))
        self.chkPersonOSDetail.setText(_translate("SetupReportYearActionsDialog", "Детализировать по подразделениям", None))
        self.chkTissueType.setText(_translate("SetupReportYearActionsDialog", "Тип биоматериала", None))
        self.chkClass.setText(_translate("SetupReportYearActionsDialog", "Класс", None))
        self.edtBegDate.setDisplayFormat(_translate("SetupReportYearActionsDialog", "dd.MM.yyyy", None))
        self.chkPersonDateDetail.setText(_translate("SetupReportYearActionsDialog", "Детализировать по датам", None))
        self.chkFinance.setText(_translate("SetupReportYearActionsDialog", "Тип финансирования", None))
        self.label.setText(_translate("SetupReportYearActionsDialog", "по", None))
        self.chkOrgStructure.setText(_translate("SetupReportYearActionsDialog", "Подразделение", None))
        self.chkAssistant.setText(_translate("SetupReportYearActionsDialog", "Ассистент", None))
        self.cmbClass.setItemText(0, _translate("SetupReportYearActionsDialog", "Статус", None))
        self.cmbClass.setItemText(1, _translate("SetupReportYearActionsDialog", "Диагностика", None))
        self.cmbClass.setItemText(2, _translate("SetupReportYearActionsDialog", "Лечение", None))
        self.cmbClass.setItemText(3, _translate("SetupReportYearActionsDialog", "Прочие мероприятия", None))
        self.cmbClass.setItemText(4, _translate("SetupReportYearActionsDialog", "Назначено", None))
        self.lblDate.setText(_translate("SetupReportYearActionsDialog", "Период", None))
        self.chkPersonOverall.setText(_translate("SetupReportYearActionsDialog", "Общий по врачам", None))
        self.chkSex.setText(_translate("SetupReportYearActionsDialog", "Пол", None))
        self.cmbSex.setItemText(1, _translate("SetupReportYearActionsDialog", "Мужской", None))
        self.cmbSex.setItemText(2, _translate("SetupReportYearActionsDialog", "Женский", None))
        self.chkAge.setText(_translate("SetupReportYearActionsDialog", "Возраст ", None))
        self.lblAge.setText(_translate("SetupReportYearActionsDialog", "с", None))
        self.lblAgeTo.setText(_translate("SetupReportYearActionsDialog", "по", None))
        self.lblAgeYears.setText(_translate("SetupReportYearActionsDialog", "лет", None))
        self.edtEndDate.setDisplayFormat(_translate("SetupReportYearActionsDialog", "dd.MM.yyyy", None))
        self.chkLocality.setText(_translate("SetupReportYearActionsDialog", "Местность", None))
        self.cmbLocality.setItemText(0, _translate("SetupReportYearActionsDialog", "не учитывать", None))
        self.cmbLocality.setItemText(1, _translate("SetupReportYearActionsDialog", "городские", None))
        self.cmbLocality.setItemText(2, _translate("SetupReportYearActionsDialog", "сельские", None))

from Events.ActionStatus import CActionStatusComboBox
from Events.ActionTypeComboBox import CActionTypeComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
