# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\StatReportF131RaionSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StatReportF131RaionSetupDialog(object):
    def setupUi(self, StatReportF131RaionSetupDialog):
        StatReportF131RaionSetupDialog.setObjectName(_fromUtf8("StatReportF131RaionSetupDialog"))
        StatReportF131RaionSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StatReportF131RaionSetupDialog.resize(415, 372)
        StatReportF131RaionSetupDialog.setSizeGripEnabled(True)
        StatReportF131RaionSetupDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(StatReportF131RaionSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblEndDate = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblEventType = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 2, 0, 1, 1)
        self.cmbEventType = CRBComboBox(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 2, 1, 1, 1)
        self.chkOnlyPayedEvents = QtGui.QCheckBox(StatReportF131RaionSetupDialog)
        self.chkOnlyPayedEvents.setObjectName(_fromUtf8("chkOnlyPayedEvents"))
        self.gridLayout.addWidget(self.chkOnlyPayedEvents, 4, 1, 1, 1)
        self.lblBegPayDate = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegPayDate.sizePolicy().hasHeightForWidth())
        self.lblBegPayDate.setSizePolicy(sizePolicy)
        self.lblBegPayDate.setObjectName(_fromUtf8("lblBegPayDate"))
        self.gridLayout.addWidget(self.lblBegPayDate, 5, 0, 1, 1)
        self.edtBegPayDate = CDateEdit(StatReportF131RaionSetupDialog)
        self.edtBegPayDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegPayDate.sizePolicy().hasHeightForWidth())
        self.edtBegPayDate.setSizePolicy(sizePolicy)
        self.edtBegPayDate.setCalendarPopup(True)
        self.edtBegPayDate.setObjectName(_fromUtf8("edtBegPayDate"))
        self.gridLayout.addWidget(self.edtBegPayDate, 5, 1, 1, 1)
        self.lblEndPayDate = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndPayDate.sizePolicy().hasHeightForWidth())
        self.lblEndPayDate.setSizePolicy(sizePolicy)
        self.lblEndPayDate.setObjectName(_fromUtf8("lblEndPayDate"))
        self.gridLayout.addWidget(self.lblEndPayDate, 6, 0, 1, 1)
        self.edtEndPayDate = CDateEdit(StatReportF131RaionSetupDialog)
        self.edtEndPayDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndPayDate.sizePolicy().hasHeightForWidth())
        self.edtEndPayDate.setSizePolicy(sizePolicy)
        self.edtEndPayDate.setCalendarPopup(True)
        self.edtEndPayDate.setObjectName(_fromUtf8("edtEndPayDate"))
        self.gridLayout.addWidget(self.edtEndPayDate, 6, 1, 1, 1)
        self.label = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.cmbRaion = QtGui.QComboBox(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRaion.sizePolicy().hasHeightForWidth())
        self.cmbRaion.setSizePolicy(sizePolicy)
        self.cmbRaion.setObjectName(_fromUtf8("cmbRaion"))
        self.gridLayout.addWidget(self.cmbRaion, 7, 1, 1, 1)
        self.label_2 = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.ledtYearForDD = QtGui.QLineEdit(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledtYearForDD.sizePolicy().hasHeightForWidth())
        self.ledtYearForDD.setSizePolicy(sizePolicy)
        self.ledtYearForDD.setMaxLength(10)
        self.ledtYearForDD.setObjectName(_fromUtf8("ledtYearForDD"))
        self.gridLayout.addWidget(self.ledtYearForDD, 9, 1, 1, 1)
        self.cmbPermanentAttach = QtGui.QComboBox(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPermanentAttach.sizePolicy().hasHeightForWidth())
        self.cmbPermanentAttach.setSizePolicy(sizePolicy)
        self.cmbPermanentAttach.setObjectName(_fromUtf8("cmbPermanentAttach"))
        self.gridLayout.addWidget(self.cmbPermanentAttach, 8, 1, 1, 1)
        self.lblYearForDD = QtGui.QLabel(StatReportF131RaionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblYearForDD.sizePolicy().hasHeightForWidth())
        self.lblYearForDD.setSizePolicy(sizePolicy)
        self.lblYearForDD.setObjectName(_fromUtf8("lblYearForDD"))
        self.gridLayout.addWidget(self.lblYearForDD, 9, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(StatReportF131RaionSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(StatReportF131RaionSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 3, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(StatReportF131RaionSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 3, 1, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblBegPayDate.setBuddy(self.edtBegPayDate)
        self.lblEndPayDate.setBuddy(self.edtEndPayDate)

        self.retranslateUi(StatReportF131RaionSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StatReportF131RaionSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StatReportF131RaionSetupDialog.reject)
        QtCore.QObject.connect(self.chkOnlyPayedEvents, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndPayDate.setEnabled)
        QtCore.QObject.connect(self.chkOnlyPayedEvents, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegPayDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StatReportF131RaionSetupDialog)
        StatReportF131RaionSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        StatReportF131RaionSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventType)
        StatReportF131RaionSetupDialog.setTabOrder(self.cmbEventType, self.cmbOrgStructure)
        StatReportF131RaionSetupDialog.setTabOrder(self.cmbOrgStructure, self.chkOnlyPayedEvents)
        StatReportF131RaionSetupDialog.setTabOrder(self.chkOnlyPayedEvents, self.edtBegPayDate)
        StatReportF131RaionSetupDialog.setTabOrder(self.edtBegPayDate, self.edtEndPayDate)
        StatReportF131RaionSetupDialog.setTabOrder(self.edtEndPayDate, self.cmbRaion)
        StatReportF131RaionSetupDialog.setTabOrder(self.cmbRaion, self.cmbPermanentAttach)
        StatReportF131RaionSetupDialog.setTabOrder(self.cmbPermanentAttach, self.ledtYearForDD)
        StatReportF131RaionSetupDialog.setTabOrder(self.ledtYearForDD, self.buttonBox)

    def retranslateUi(self, StatReportF131RaionSetupDialog):
        StatReportF131RaionSetupDialog.setWindowTitle(_translate("StatReportF131RaionSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("StatReportF131RaionSetupDialog", "Дата &начала периода", None))
        self.lblEndDate.setText(_translate("StatReportF131RaionSetupDialog", "Дата &окончания периода", None))
        self.lblEventType.setText(_translate("StatReportF131RaionSetupDialog", "&Тип обращения", None))
        self.chkOnlyPayedEvents.setText(_translate("StatReportF131RaionSetupDialog", "Только опла&ченные", None))
        self.lblBegPayDate.setText(_translate("StatReportF131RaionSetupDialog", "Оплачено в период с", None))
        self.lblEndPayDate.setText(_translate("StatReportF131RaionSetupDialog", "по", None))
        self.label.setText(_translate("StatReportF131RaionSetupDialog", "Район", None))
        self.label_2.setText(_translate("StatReportF131RaionSetupDialog", "Прикрепление к", None))
        self.lblYearForDD.setText(_translate("StatReportF131RaionSetupDialog", "Префикс формы 131", None))
        self.lblOrgStructure.setText(_translate("StatReportF131RaionSetupDialog", "Подразделение", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
