# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\StationaryPatientsCompositionSetupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationaryPatientsCompositionSetupDialog(object):
    def setupUi(self, StationaryPatientsCompositionSetupDialog):
        StationaryPatientsCompositionSetupDialog.setObjectName(_fromUtf8("StationaryPatientsCompositionSetupDialog"))
        StationaryPatientsCompositionSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StationaryPatientsCompositionSetupDialog.resize(471, 303)
        StationaryPatientsCompositionSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(StationaryPatientsCompositionSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbOrgStructure = COrgStructureComboBox(StationaryPatientsCompositionSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 2, 1, 5)
        self.lblAgeTo = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.gridLayout.addWidget(self.lblAgeTo, 8, 3, 1, 1)
        self.lblAgeYears = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.gridLayout.addWidget(self.lblAgeYears, 8, 5, 1, 2)
        self.lblGroupMKB = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblGroupMKB.setObjectName(_fromUtf8("lblGroupMKB"))
        self.gridLayout.addWidget(self.lblGroupMKB, 6, 0, 1, 2)
        self.cmbGroupMKB = QtGui.QComboBox(StationaryPatientsCompositionSetupDialog)
        self.cmbGroupMKB.setObjectName(_fromUtf8("cmbGroupMKB"))
        self.cmbGroupMKB.addItem(_fromUtf8(""))
        self.cmbGroupMKB.addItem(_fromUtf8(""))
        self.cmbGroupMKB.addItem(_fromUtf8(""))
        self.cmbGroupMKB.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbGroupMKB, 6, 2, 1, 5)
        self.edtAgeTo = QtGui.QSpinBox(StationaryPatientsCompositionSetupDialog)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setProperty("value", 150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.gridLayout.addWidget(self.edtAgeTo, 8, 4, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(StationaryPatientsCompositionSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 3)
        self.chkPerson = QtGui.QCheckBox(StationaryPatientsCompositionSetupDialog)
        self.chkPerson.setObjectName(_fromUtf8("chkPerson"))
        self.gridLayout.addWidget(self.chkPerson, 4, 0, 1, 1)
        self.edtEndDate = CDateEdit(StationaryPatientsCompositionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 3)
        self.cmbSelectType = QtGui.QComboBox(StationaryPatientsCompositionSetupDialog)
        self.cmbSelectType.setEnabled(False)
        self.cmbSelectType.setObjectName(_fromUtf8("cmbSelectType"))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.cmbSelectType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSelectType, 5, 2, 1, 5)
        self.lblEndDate = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.edtMKBFrom = QtGui.QLineEdit(StationaryPatientsCompositionSetupDialog)
        self.edtMKBFrom.setEnabled(False)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout.addWidget(self.edtMKBFrom, 7, 2, 1, 4)
        self.lblAge = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 8, 0, 1, 1)
        self.edtMKBTo = QtGui.QLineEdit(StationaryPatientsCompositionSetupDialog)
        self.edtMKBTo.setEnabled(False)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout.addWidget(self.edtMKBTo, 7, 6, 1, 1)
        self.edtAgeFrom = QtGui.QSpinBox(StationaryPatientsCompositionSetupDialog)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.gridLayout.addWidget(self.edtAgeFrom, 8, 2, 1, 1)
        self.edtBegDate = CDateEdit(StationaryPatientsCompositionSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 3)
        self.lblOrgStructure = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.lblHospitalBedProfileList = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblHospitalBedProfileList.setWordWrap(True)
        self.lblHospitalBedProfileList.setObjectName(_fromUtf8("lblHospitalBedProfileList"))
        self.gridLayout.addWidget(self.lblHospitalBedProfileList, 3, 2, 1, 1)
        self.lblBegDate = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 1, 1, 1)
        self.lblSelectType = QtGui.QLabel(StationaryPatientsCompositionSetupDialog)
        self.lblSelectType.setEnabled(False)
        self.lblSelectType.setObjectName(_fromUtf8("lblSelectType"))
        self.gridLayout.addWidget(self.lblSelectType, 5, 0, 1, 2)
        self.chkMKBFilter = QtGui.QCheckBox(StationaryPatientsCompositionSetupDialog)
        self.chkMKBFilter.setObjectName(_fromUtf8("chkMKBFilter"))
        self.gridLayout.addWidget(self.chkMKBFilter, 7, 0, 1, 2)
        self.btnHospitalBedProfileList = QtGui.QPushButton(StationaryPatientsCompositionSetupDialog)
        self.btnHospitalBedProfileList.setObjectName(_fromUtf8("btnHospitalBedProfileList"))
        self.gridLayout.addWidget(self.btnHospitalBedProfileList, 3, 0, 1, 2)
        self.cmbPerson = CPersonComboBoxEx(StationaryPatientsCompositionSetupDialog)
        self.cmbPerson.setEnabled(False)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 2, 1, 5)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(StationaryPatientsCompositionSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StationaryPatientsCompositionSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StationaryPatientsCompositionSetupDialog.reject)
        QtCore.QObject.connect(self.chkMKBFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKBFrom.setEnabled)
        QtCore.QObject.connect(self.chkMKBFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKBTo.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPerson.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSelectType.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblSelectType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StationaryPatientsCompositionSetupDialog)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.cmbOrgStructure, self.btnHospitalBedProfileList)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.btnHospitalBedProfileList, self.cmbPerson)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.cmbPerson, self.cmbGroupMKB)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.cmbGroupMKB, self.edtMKBFrom)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.edtMKBFrom, self.chkMKBFilter)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.chkMKBFilter, self.edtMKBTo)
        StationaryPatientsCompositionSetupDialog.setTabOrder(self.edtMKBTo, self.buttonBox)

    def retranslateUi(self, StationaryPatientsCompositionSetupDialog):
        StationaryPatientsCompositionSetupDialog.setWindowTitle(_translate("StationaryPatientsCompositionSetupDialog", "параметры отчёта", None))
        self.lblAgeTo.setText(_translate("StationaryPatientsCompositionSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("StationaryPatientsCompositionSetupDialog", "лет", None))
        self.lblGroupMKB.setText(_translate("StationaryPatientsCompositionSetupDialog", "Группировать диагнозы", None))
        self.cmbGroupMKB.setItemText(0, _translate("StationaryPatientsCompositionSetupDialog", "не группировать", None))
        self.cmbGroupMKB.setItemText(1, _translate("StationaryPatientsCompositionSetupDialog", "группировать по рубрикам", None))
        self.cmbGroupMKB.setItemText(2, _translate("StationaryPatientsCompositionSetupDialog", "группировать по блокам", None))
        self.cmbGroupMKB.setItemText(3, _translate("StationaryPatientsCompositionSetupDialog", "группировать по классам", None))
        self.chkPerson.setText(_translate("StationaryPatientsCompositionSetupDialog", "Врач", None))
        self.edtEndDate.setDisplayFormat(_translate("StationaryPatientsCompositionSetupDialog", "dd.MM.yyyy", None))
        self.cmbSelectType.setItemText(0, _translate("StationaryPatientsCompositionSetupDialog", "ответственному за действие", None))
        self.cmbSelectType.setItemText(1, _translate("StationaryPatientsCompositionSetupDialog", "ответственному за событие", None))
        self.lblEndDate.setText(_translate("StationaryPatientsCompositionSetupDialog", "Дата &окончания периода", None))
        self.edtMKBFrom.setInputMask(_translate("StationaryPatientsCompositionSetupDialog", ">A<00.00; ", None))
        self.edtMKBFrom.setText(_translate("StationaryPatientsCompositionSetupDialog", "A00.00", None))
        self.lblAge.setText(_translate("StationaryPatientsCompositionSetupDialog", "Возраст с", None))
        self.edtMKBTo.setInputMask(_translate("StationaryPatientsCompositionSetupDialog", ">A<00.00; ", None))
        self.edtMKBTo.setText(_translate("StationaryPatientsCompositionSetupDialog", "Z99.99", None))
        self.edtBegDate.setDisplayFormat(_translate("StationaryPatientsCompositionSetupDialog", "dd.MM.yyyy", None))
        self.lblOrgStructure.setText(_translate("StationaryPatientsCompositionSetupDialog", "&Подразделение", None))
        self.lblHospitalBedProfileList.setText(_translate("StationaryPatientsCompositionSetupDialog", " не задано", None))
        self.lblBegDate.setText(_translate("StationaryPatientsCompositionSetupDialog", "Дата &начала периода", None))
        self.lblSelectType.setText(_translate("StationaryPatientsCompositionSetupDialog", "Выбор по врачу", None))
        self.chkMKBFilter.setText(_translate("StationaryPatientsCompositionSetupDialog", "Диапазон диагнозов", None))
        self.btnHospitalBedProfileList.setText(_translate("StationaryPatientsCompositionSetupDialog", "Профиль койки", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
