# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetupReportMonthActions.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SetupReportMonthActionsDialog(object):
    def setupUi(self, SetupReportMonthActionsDialog):
        SetupReportMonthActionsDialog.setObjectName(_fromUtf8("SetupReportMonthActionsDialog"))
        SetupReportMonthActionsDialog.resize(507, 583)
        self.gridLayout = QtGui.QGridLayout(SetupReportMonthActionsDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frmAge = QtGui.QFrame(SetupReportMonthActionsDialog)
        self.frmAge.setEnabled(False)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lblAge = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.hboxlayout.addWidget(self.lblAge)
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeTo.sizePolicy().hasHeightForWidth())
        self.lblAgeTo.setSizePolicy(sizePolicy)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setProperty("value", 150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeYears.sizePolicy().hasHeightForWidth())
        self.lblAgeYears.setSizePolicy(sizePolicy)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frmAge, 11, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(SetupReportMonthActionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 23, 0, 1, 5)
        self.chkPersonOSDetail = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkPersonOSDetail.setObjectName(_fromUtf8("chkPersonOSDetail"))
        self.gridLayout.addWidget(self.chkPersonOSDetail, 16, 1, 1, 4)
        self.cmbSex = QtGui.QComboBox(SetupReportMonthActionsDialog)
        self.cmbSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 12, 1, 1, 4)
        self.chkLocality = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkLocality.setObjectName(_fromUtf8("chkLocality"))
        self.gridLayout.addWidget(self.chkLocality, 13, 0, 1, 1)
        self.chkSex = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout.addWidget(self.chkSex, 12, 0, 1, 1)
        self.chkAge = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 11, 0, 1, 1)
        self.cmbLocality = QtGui.QComboBox(SetupReportMonthActionsDialog)
        self.cmbLocality.setEnabled(False)
        self.cmbLocality.setObjectName(_fromUtf8("cmbLocality"))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.cmbLocality.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLocality, 13, 1, 1, 4)
        self.chkShowVisits = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkShowVisits.setObjectName(_fromUtf8("chkShowVisits"))
        self.gridLayout.addWidget(self.chkShowVisits, 21, 1, 1, 4)
        self.cmbUET = QtGui.QComboBox(SetupReportMonthActionsDialog)
        self.cmbUET.setEnabled(True)
        self.cmbUET.setObjectName(_fromUtf8("cmbUET"))
        self.cmbUET.addItem(_fromUtf8(""))
        self.cmbUET.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbUET, 14, 1, 1, 4)
        self.lblUET = QtGui.QLabel(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUET.sizePolicy().hasHeightForWidth())
        self.lblUET.setSizePolicy(sizePolicy)
        self.lblUET.setObjectName(_fromUtf8("lblUET"))
        self.gridLayout.addWidget(self.lblUET, 14, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 22, 0, 1, 5)
        self.chkPersonOverall = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkPersonOverall.setObjectName(_fromUtf8("chkPersonOverall"))
        self.gridLayout.addWidget(self.chkPersonOverall, 17, 1, 1, 4)
        self.chkPersonDetail = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkPersonDetail.setObjectName(_fromUtf8("chkPersonDetail"))
        self.gridLayout.addWidget(self.chkPersonDetail, 18, 1, 1, 4)
        self.chkPersonMonthDetail = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkPersonMonthDetail.setObjectName(_fromUtf8("chkPersonMonthDetail"))
        self.gridLayout.addWidget(self.chkPersonMonthDetail, 19, 1, 1, 4)
        self.chkPersonDateDetail = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkPersonDateDetail.setEnabled(False)
        self.chkPersonDateDetail.setObjectName(_fromUtf8("chkPersonDateDetail"))
        self.gridLayout.addWidget(self.chkPersonDateDetail, 20, 1, 1, 4)
        self.cmbAssistant = CPersonComboBoxEx(SetupReportMonthActionsDialog)
        self.cmbAssistant.setEnabled(False)
        self.cmbAssistant.setObjectName(_fromUtf8("cmbAssistant"))
        self.gridLayout.addWidget(self.cmbAssistant, 8, 1, 1, 4)
        self.chkAssistant = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAssistant.sizePolicy().hasHeightForWidth())
        self.chkAssistant.setSizePolicy(sizePolicy)
        self.chkAssistant.setObjectName(_fromUtf8("chkAssistant"))
        self.gridLayout.addWidget(self.chkAssistant, 8, 0, 1, 1)
        self.cmbClass = QtGui.QComboBox(SetupReportMonthActionsDialog)
        self.cmbClass.setEnabled(False)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClass, 2, 1, 1, 4)
        self.chkStatus = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkStatus.sizePolicy().hasHeightForWidth())
        self.chkStatus.setSizePolicy(sizePolicy)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout.addWidget(self.chkStatus, 4, 0, 1, 1)
        self.chkClass = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClass.sizePolicy().hasHeightForWidth())
        self.chkClass.setSizePolicy(sizePolicy)
        self.chkClass.setObjectName(_fromUtf8("chkClass"))
        self.gridLayout.addWidget(self.chkClass, 2, 0, 1, 1)
        self.cmbActionTypeGroup = CActionTypeComboBox(SetupReportMonthActionsDialog)
        self.cmbActionTypeGroup.setEnabled(False)
        self.cmbActionTypeGroup.setObjectName(_fromUtf8("cmbActionTypeGroup"))
        self.gridLayout.addWidget(self.cmbActionTypeGroup, 3, 1, 1, 4)
        self.chkActionTypeGroup = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActionTypeGroup.sizePolicy().hasHeightForWidth())
        self.chkActionTypeGroup.setSizePolicy(sizePolicy)
        self.chkActionTypeGroup.setObjectName(_fromUtf8("chkActionTypeGroup"))
        self.gridLayout.addWidget(self.chkActionTypeGroup, 3, 0, 1, 1)
        self.cmbStatus = CActionStatusComboBox(SetupReportMonthActionsDialog)
        self.cmbStatus.setEnabled(False)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.gridLayout.addWidget(self.cmbStatus, 4, 1, 1, 4)
        self.chkFinance = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFinance.sizePolicy().hasHeightForWidth())
        self.chkFinance.setSizePolicy(sizePolicy)
        self.chkFinance.setObjectName(_fromUtf8("chkFinance"))
        self.gridLayout.addWidget(self.chkFinance, 1, 0, 1, 1)
        self.edtBegDate = CDateEdit(SetupReportMonthActionsDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.label = QtGui.QLabel(SetupReportMonthActionsDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.cmbFinance = CRBComboBox(SetupReportMonthActionsDialog)
        self.cmbFinance.setEnabled(False)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 1, 1, 1, 4)
        self.lblDate = QtGui.QLabel(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.edtEndDate = CDateEdit(SetupReportMonthActionsDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 0, 3, 1, 1)
        self.chkTissueType = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        self.chkTissueType.setObjectName(_fromUtf8("chkTissueType"))
        self.gridLayout.addWidget(self.chkTissueType, 9, 0, 1, 1)
        self.btnSpecialityList = QtGui.QPushButton(SetupReportMonthActionsDialog)
        self.btnSpecialityList.setObjectName(_fromUtf8("btnSpecialityList"))
        self.gridLayout.addWidget(self.btnSpecialityList, 7, 0, 1, 1)
        self.chkPerson = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPerson.sizePolicy().hasHeightForWidth())
        self.chkPerson.setSizePolicy(sizePolicy)
        self.chkPerson.setObjectName(_fromUtf8("chkPerson"))
        self.gridLayout.addWidget(self.chkPerson, 6, 0, 1, 1)
        self.lblSpecialityList = QtGui.QLabel(SetupReportMonthActionsDialog)
        self.lblSpecialityList.setWordWrap(True)
        self.lblSpecialityList.setObjectName(_fromUtf8("lblSpecialityList"))
        self.gridLayout.addWidget(self.lblSpecialityList, 7, 1, 1, 4)
        self.cmbOrgStructure = COrgStructureComboBox(SetupReportMonthActionsDialog)
        self.cmbOrgStructure.setEnabled(False)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 5, 1, 1, 4)
        self.chkOrgStructure = QtGui.QCheckBox(SetupReportMonthActionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkOrgStructure.sizePolicy().hasHeightForWidth())
        self.chkOrgStructure.setSizePolicy(sizePolicy)
        self.chkOrgStructure.setObjectName(_fromUtf8("chkOrgStructure"))
        self.gridLayout.addWidget(self.chkOrgStructure, 5, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(SetupReportMonthActionsDialog)
        self.cmbPerson.setEnabled(False)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 6, 1, 1, 4)
        self.cmbTissueType = CRBComboBox(SetupReportMonthActionsDialog)
        self.cmbTissueType.setEnabled(False)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout.addWidget(self.cmbTissueType, 9, 1, 1, 4)
        self.cmbContract = CARMSContractTreeFindComboBox(SetupReportMonthActionsDialog)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 15, 1, 1, 4)
        self.lblContract = QtGui.QLabel(SetupReportMonthActionsDialog)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 15, 0, 1, 1)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)

        self.retranslateUi(SetupReportMonthActionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SetupReportMonthActionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SetupReportMonthActionsDialog.reject)
        QtCore.QObject.connect(self.chkFinance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFinance.setEnabled)
        QtCore.QObject.connect(self.chkClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClass.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActionTypeGroup.setEnabled)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.chkOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPerson.setEnabled)
        QtCore.QObject.connect(self.chkAssistant, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAssistant.setEnabled)
        QtCore.QObject.connect(self.chkTissueType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbTissueType.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frmAge.setEnabled)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkPersonDetail, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkPersonDateDetail.setEnabled)
        QtCore.QObject.connect(self.chkLocality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbLocality.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SetupReportMonthActionsDialog)
        SetupReportMonthActionsDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        SetupReportMonthActionsDialog.setTabOrder(self.edtEndDate, self.chkFinance)
        SetupReportMonthActionsDialog.setTabOrder(self.chkFinance, self.cmbFinance)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbFinance, self.chkClass)
        SetupReportMonthActionsDialog.setTabOrder(self.chkClass, self.cmbClass)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbClass, self.chkActionTypeGroup)
        SetupReportMonthActionsDialog.setTabOrder(self.chkActionTypeGroup, self.cmbActionTypeGroup)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbActionTypeGroup, self.chkStatus)
        SetupReportMonthActionsDialog.setTabOrder(self.chkStatus, self.cmbStatus)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbStatus, self.chkOrgStructure)
        SetupReportMonthActionsDialog.setTabOrder(self.chkOrgStructure, self.cmbOrgStructure)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbOrgStructure, self.chkPerson)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPerson, self.cmbPerson)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbPerson, self.chkAssistant)
        SetupReportMonthActionsDialog.setTabOrder(self.chkAssistant, self.cmbAssistant)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbAssistant, self.chkTissueType)
        SetupReportMonthActionsDialog.setTabOrder(self.chkTissueType, self.cmbTissueType)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbTissueType, self.chkAge)
        SetupReportMonthActionsDialog.setTabOrder(self.chkAge, self.edtAgeFrom)
        SetupReportMonthActionsDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        SetupReportMonthActionsDialog.setTabOrder(self.edtAgeTo, self.chkSex)
        SetupReportMonthActionsDialog.setTabOrder(self.chkSex, self.cmbSex)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbSex, self.chkLocality)
        SetupReportMonthActionsDialog.setTabOrder(self.chkLocality, self.cmbLocality)
        SetupReportMonthActionsDialog.setTabOrder(self.cmbLocality, self.chkPersonOSDetail)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPersonOSDetail, self.chkPersonOverall)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPersonOverall, self.chkPersonDetail)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPersonDetail, self.chkPersonMonthDetail)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPersonMonthDetail, self.chkPersonDateDetail)
        SetupReportMonthActionsDialog.setTabOrder(self.chkPersonDateDetail, self.buttonBox)

    def retranslateUi(self, SetupReportMonthActionsDialog):
        SetupReportMonthActionsDialog.setWindowTitle(_translate("SetupReportMonthActionsDialog", "Dialog", None))
        self.lblAge.setText(_translate("SetupReportMonthActionsDialog", "с", None))
        self.lblAgeTo.setText(_translate("SetupReportMonthActionsDialog", "по", None))
        self.lblAgeYears.setText(_translate("SetupReportMonthActionsDialog", "лет", None))
        self.chkPersonOSDetail.setText(_translate("SetupReportMonthActionsDialog", "Детализировать по подразделениям", None))
        self.cmbSex.setItemText(1, _translate("SetupReportMonthActionsDialog", "Мужской", None))
        self.cmbSex.setItemText(2, _translate("SetupReportMonthActionsDialog", "Женский", None))
        self.chkLocality.setText(_translate("SetupReportMonthActionsDialog", "Местность", None))
        self.chkSex.setText(_translate("SetupReportMonthActionsDialog", "Пол", None))
        self.chkAge.setText(_translate("SetupReportMonthActionsDialog", "Возраст ", None))
        self.cmbLocality.setItemText(0, _translate("SetupReportMonthActionsDialog", "не учитывать", None))
        self.cmbLocality.setItemText(1, _translate("SetupReportMonthActionsDialog", "городские", None))
        self.cmbLocality.setItemText(2, _translate("SetupReportMonthActionsDialog", "сельские", None))
        self.chkShowVisits.setText(_translate("SetupReportMonthActionsDialog", "Отображать визиты", None))
        self.cmbUET.setItemText(0, _translate("SetupReportMonthActionsDialog", "по договору", None))
        self.cmbUET.setItemText(1, _translate("SetupReportMonthActionsDialog", "по нормативу", None))
        self.lblUET.setText(_translate("SetupReportMonthActionsDialog", "Учитывать УЕТ", None))
        self.chkPersonOverall.setText(_translate("SetupReportMonthActionsDialog", "Общий по врачам", None))
        self.chkPersonDetail.setText(_translate("SetupReportMonthActionsDialog", "Отдельно по врачам", None))
        self.chkPersonMonthDetail.setText(_translate("SetupReportMonthActionsDialog", "Детализировать по месяцам", None))
        self.chkPersonDateDetail.setText(_translate("SetupReportMonthActionsDialog", "Детализировать по датам", None))
        self.chkAssistant.setText(_translate("SetupReportMonthActionsDialog", "Ассистент", None))
        self.cmbClass.setItemText(0, _translate("SetupReportMonthActionsDialog", "Статус", None))
        self.cmbClass.setItemText(1, _translate("SetupReportMonthActionsDialog", "Диагностика", None))
        self.cmbClass.setItemText(2, _translate("SetupReportMonthActionsDialog", "Лечение", None))
        self.cmbClass.setItemText(3, _translate("SetupReportMonthActionsDialog", "Прочие мероприятия", None))
        self.cmbClass.setItemText(4, _translate("SetupReportMonthActionsDialog", "Назначено", None))
        self.chkStatus.setText(_translate("SetupReportMonthActionsDialog", "Статус", None))
        self.chkClass.setText(_translate("SetupReportMonthActionsDialog", "Класс", None))
        self.chkActionTypeGroup.setText(_translate("SetupReportMonthActionsDialog", "Группа", None))
        self.chkFinance.setText(_translate("SetupReportMonthActionsDialog", "Тип финансирования", None))
        self.edtBegDate.setDisplayFormat(_translate("SetupReportMonthActionsDialog", "dd.MM.yyyy", None))
        self.label.setText(_translate("SetupReportMonthActionsDialog", "по", None))
        self.lblDate.setText(_translate("SetupReportMonthActionsDialog", "Период", None))
        self.edtEndDate.setDisplayFormat(_translate("SetupReportMonthActionsDialog", "dd.MM.yyyy", None))
        self.chkTissueType.setText(_translate("SetupReportMonthActionsDialog", "Тип биоматериала", None))
        self.btnSpecialityList.setText(_translate("SetupReportMonthActionsDialog", "Специальность", None))
        self.chkPerson.setText(_translate("SetupReportMonthActionsDialog", "Исполнитель", None))
        self.lblSpecialityList.setText(_translate("SetupReportMonthActionsDialog", "не задано", None))
        self.chkOrgStructure.setText(_translate("SetupReportMonthActionsDialog", "Подразделение", None))
        self.lblContract.setText(_translate("SetupReportMonthActionsDialog", "Договор", None))

from Events.ActionStatus import CActionStatusComboBox
from Events.ActionTypeComboBox import CActionTypeComboBox
from Orgs.ContractFindComboBox import CARMSContractTreeFindComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SetupReportMonthActionsDialog = QtGui.QDialog()
    ui = Ui_SetupReportMonthActionsDialog()
    ui.setupUi(SetupReportMonthActionsDialog)
    SetupReportMonthActionsDialog.show()
    sys.exit(app.exec_())

