# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Reports\StationaryF14Setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationaryF14SetupDialog(object):
    def setupUi(self, StationaryF14SetupDialog):
        StationaryF14SetupDialog.setObjectName(_fromUtf8("StationaryF14SetupDialog"))
        StationaryF14SetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StationaryF14SetupDialog.resize(551, 386)
        StationaryF14SetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(StationaryF14SetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(StationaryF14SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.cmbTypeSurgery = QtGui.QComboBox(StationaryF14SetupDialog)
        self.cmbTypeSurgery.setObjectName(_fromUtf8("cmbTypeSurgery"))
        self.cmbTypeSurgery.addItem(_fromUtf8(""))
        self.cmbTypeSurgery.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbTypeSurgery, 7, 1, 1, 4)
        self.cmbIsTypeOS = QtGui.QComboBox(StationaryF14SetupDialog)
        self.cmbIsTypeOS.setObjectName(_fromUtf8("cmbIsTypeOS"))
        self.cmbIsTypeOS.addItem(_fromUtf8(""))
        self.cmbIsTypeOS.addItem(_fromUtf8(""))
        self.cmbIsTypeOS.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsTypeOS, 9, 1, 1, 4)
        self.cmbSelectActionType = QtGui.QComboBox(StationaryF14SetupDialog)
        self.cmbSelectActionType.setObjectName(_fromUtf8("cmbSelectActionType"))
        self.cmbSelectActionType.addItem(_fromUtf8(""))
        self.cmbSelectActionType.addItem(_fromUtf8(""))
        self.cmbSelectActionType.addItem(_fromUtf8(""))
        self.cmbSelectActionType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSelectActionType, 8, 1, 1, 4)
        self.cmbSocStatusClass = CRBComboBox(StationaryF14SetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 3, 1, 1, 4)
        self.lblTypeSurgery = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblTypeSurgery.setObjectName(_fromUtf8("lblTypeSurgery"))
        self.gridLayout.addWidget(self.lblTypeSurgery, 7, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 3, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(StationaryF14SetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 4, 1, 1, 4)
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 2)
        self.lblSpecialDeliverClient = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblSpecialDeliverClient.setObjectName(_fromUtf8("lblSpecialDeliverClient"))
        self.gridLayout.addWidget(self.lblSpecialDeliverClient, 5, 0, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 4, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 6, 0, 1, 1)
        self.cmbFinance = CRBComboBox(StationaryF14SetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 6, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(StationaryF14SetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 4)
        self.lblSelectActionType = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblSelectActionType.setObjectName(_fromUtf8("lblSelectActionType"))
        self.gridLayout.addWidget(self.lblSelectActionType, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 12, 0, 1, 1)
        self.edtEndDate = CDateEdit(StationaryF14SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.chkMedicalAidType = QtGui.QCheckBox(StationaryF14SetupDialog)
        self.chkMedicalAidType.setObjectName(_fromUtf8("chkMedicalAidType"))
        self.gridLayout.addWidget(self.chkMedicalAidType, 10, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(StationaryF14SetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 0, 1, 5)
        self.lblIsTypeOS = QtGui.QLabel(StationaryF14SetupDialog)
        self.lblIsTypeOS.setObjectName(_fromUtf8("lblIsTypeOS"))
        self.gridLayout.addWidget(self.lblIsTypeOS, 9, 0, 1, 1)
        self.cmbSpecialDeliverClient = QtGui.QComboBox(StationaryF14SetupDialog)
        self.cmbSpecialDeliverClient.setObjectName(_fromUtf8("cmbSpecialDeliverClient"))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.cmbSpecialDeliverClient.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSpecialDeliverClient, 5, 1, 1, 4)
        self.chkExistFlatCode = QtGui.QCheckBox(StationaryF14SetupDialog)
        self.chkExistFlatCode.setObjectName(_fromUtf8("chkExistFlatCode"))
        self.gridLayout.addWidget(self.chkExistFlatCode, 11, 1, 1, 4)
        self.edtBegTime = QtGui.QTimeEdit(StationaryF14SetupDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 2, 1, 1)
        self.edtTimeEdit = QtGui.QTimeEdit(StationaryF14SetupDialog)
        self.edtTimeEdit.setObjectName(_fromUtf8("edtTimeEdit"))
        self.gridLayout.addWidget(self.edtTimeEdit, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)

        self.retranslateUi(StationaryF14SetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StationaryF14SetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StationaryF14SetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StationaryF14SetupDialog)
        StationaryF14SetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        StationaryF14SetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        StationaryF14SetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSocStatusClass)
        StationaryF14SetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        StationaryF14SetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbSpecialDeliverClient)
        StationaryF14SetupDialog.setTabOrder(self.cmbSpecialDeliverClient, self.cmbFinance)
        StationaryF14SetupDialog.setTabOrder(self.cmbFinance, self.cmbTypeSurgery)
        StationaryF14SetupDialog.setTabOrder(self.cmbTypeSurgery, self.cmbSelectActionType)
        StationaryF14SetupDialog.setTabOrder(self.cmbSelectActionType, self.cmbIsTypeOS)
        StationaryF14SetupDialog.setTabOrder(self.cmbIsTypeOS, self.chkMedicalAidType)
        StationaryF14SetupDialog.setTabOrder(self.chkMedicalAidType, self.chkExistFlatCode)
        StationaryF14SetupDialog.setTabOrder(self.chkExistFlatCode, self.buttonBox)

    def retranslateUi(self, StationaryF14SetupDialog):
        StationaryF14SetupDialog.setWindowTitle(_translate("StationaryF14SetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("StationaryF14SetupDialog", "Дата &начала периода", None))
        self.edtBegDate.setDisplayFormat(_translate("StationaryF14SetupDialog", "dd.MM.yyyy", None))
        self.cmbTypeSurgery.setItemText(0, _translate("StationaryF14SetupDialog", "Номенклатурный", None))
        self.cmbTypeSurgery.setItemText(1, _translate("StationaryF14SetupDialog", "Пользовательский", None))
        self.cmbIsTypeOS.setItemText(0, _translate("StationaryF14SetupDialog", "не задано", None))
        self.cmbIsTypeOS.setItemText(1, _translate("StationaryF14SetupDialog", "круглосуточный", None))
        self.cmbIsTypeOS.setItemText(2, _translate("StationaryF14SetupDialog", "дневной", None))
        self.cmbSelectActionType.setItemText(0, _translate("StationaryF14SetupDialog", "Операция", None))
        self.cmbSelectActionType.setItemText(1, _translate("StationaryF14SetupDialog", "Поступление", None))
        self.cmbSelectActionType.setItemText(2, _translate("StationaryF14SetupDialog", "Движение", None))
        self.cmbSelectActionType.setItemText(3, _translate("StationaryF14SetupDialog", "Выписка", None))
        self.lblTypeSurgery.setText(_translate("StationaryF14SetupDialog", "Учет операций", None))
        self.lblEndDate.setText(_translate("StationaryF14SetupDialog", "Дата &окончания периода", None))
        self.lblSocStatusClass.setText(_translate("StationaryF14SetupDialog", "Класс соц.статуса", None))
        self.lblSpecialDeliverClient.setText(_translate("StationaryF14SetupDialog", "Учет экстренных пациентов", None))
        self.lblSocStatusType.setText(_translate("StationaryF14SetupDialog", "Тип соц.статуса", None))
        self.lblFinance.setText(_translate("StationaryF14SetupDialog", "Тип финансирования", None))
        self.lblOrgStructure.setText(_translate("StationaryF14SetupDialog", "&Подразделение", None))
        self.lblSelectActionType.setText(_translate("StationaryF14SetupDialog", "Отбор по", None))
        self.edtEndDate.setDisplayFormat(_translate("StationaryF14SetupDialog", "dd.MM.yyyy", None))
        self.chkMedicalAidType.setText(_translate("StationaryF14SetupDialog", "Учитывать только Стационарные События", None))
        self.lblIsTypeOS.setText(_translate("StationaryF14SetupDialog", "Стационар", None))
        self.cmbSpecialDeliverClient.setItemText(0, _translate("StationaryF14SetupDialog", "не задано", None))
        self.cmbSpecialDeliverClient.setItemText(1, _translate("StationaryF14SetupDialog", "по свойству \"Доставлен по экстренным показаниям\"", None))
        self.cmbSpecialDeliverClient.setItemText(2, _translate("StationaryF14SetupDialog", "по атрибуту События \"экстренно\"", None))
        self.chkExistFlatCode.setText(_translate("StationaryF14SetupDialog", "Учитывать только заполненный \"Код для отчётов\"", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
