# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\StationaryReportForMIACSetupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationaryReportForMIACSetupDialog(object):
    def setupUi(self, StationaryReportForMIACSetupDialog):
        StationaryReportForMIACSetupDialog.setObjectName(_fromUtf8("StationaryReportForMIACSetupDialog"))
        StationaryReportForMIACSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StationaryReportForMIACSetupDialog.resize(505, 399)
        StationaryReportForMIACSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(StationaryReportForMIACSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(StationaryReportForMIACSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(StationaryReportForMIACSetupDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 2, 1, 2)
        self.lblEndDate = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(StationaryReportForMIACSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.edtTimeEdit = QtGui.QTimeEdit(StationaryReportForMIACSetupDialog)
        self.edtTimeEdit.setObjectName(_fromUtf8("edtTimeEdit"))
        self.gridLayout.addWidget(self.edtTimeEdit, 1, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(56, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.btnOrgStructureList = QtGui.QPushButton(StationaryReportForMIACSetupDialog)
        self.btnOrgStructureList.setObjectName(_fromUtf8("btnOrgStructureList"))
        self.gridLayout.addWidget(self.btnOrgStructureList, 2, 0, 1, 1)
        self.lblOrgStructureList = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblOrgStructureList.setWordWrap(True)
        self.lblOrgStructureList.setObjectName(_fromUtf8("lblOrgStructureList"))
        self.gridLayout.addWidget(self.lblOrgStructureList, 2, 1, 1, 4)
        self.btnHospitalBedProfileList = QtGui.QPushButton(StationaryReportForMIACSetupDialog)
        self.btnHospitalBedProfileList.setObjectName(_fromUtf8("btnHospitalBedProfileList"))
        self.gridLayout.addWidget(self.btnHospitalBedProfileList, 3, 0, 1, 1)
        self.lblHospitalBedProfileList = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblHospitalBedProfileList.setWordWrap(True)
        self.lblHospitalBedProfileList.setObjectName(_fromUtf8("lblHospitalBedProfileList"))
        self.gridLayout.addWidget(self.lblHospitalBedProfileList, 3, 1, 1, 4)
        self.lblSchedule = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblSchedule.setObjectName(_fromUtf8("lblSchedule"))
        self.gridLayout.addWidget(self.lblSchedule, 4, 0, 1, 1)
        self.cmbSchedule = QtGui.QComboBox(StationaryReportForMIACSetupDialog)
        self.cmbSchedule.setObjectName(_fromUtf8("cmbSchedule"))
        self.cmbSchedule.addItem(_fromUtf8(""))
        self.cmbSchedule.addItem(_fromUtf8(""))
        self.cmbSchedule.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSchedule, 4, 1, 1, 4)
        self.chkNoProfileBed = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkNoProfileBed.setChecked(True)
        self.chkNoProfileBed.setObjectName(_fromUtf8("chkNoProfileBed"))
        self.gridLayout.addWidget(self.chkNoProfileBed, 5, 1, 1, 4)
        self.chkIsPermanentBed = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkIsPermanentBed.setObjectName(_fromUtf8("chkIsPermanentBed"))
        self.gridLayout.addWidget(self.chkIsPermanentBed, 6, 1, 1, 4)
        self.chkNoPrintCaption = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkNoPrintCaption.setChecked(True)
        self.chkNoPrintCaption.setObjectName(_fromUtf8("chkNoPrintCaption"))
        self.gridLayout.addWidget(self.chkNoPrintCaption, 7, 1, 1, 4)
        self.chkNoPrintFilterParameters = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkNoPrintFilterParameters.setObjectName(_fromUtf8("chkNoPrintFilterParameters"))
        self.gridLayout.addWidget(self.chkNoPrintFilterParameters, 8, 1, 1, 4)
        self.chkIsGroupingOS = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkIsGroupingOS.setObjectName(_fromUtf8("chkIsGroupingOS"))
        self.gridLayout.addWidget(self.chkIsGroupingOS, 9, 1, 1, 4)
        self.chkFinance = QtGui.QCheckBox(StationaryReportForMIACSetupDialog)
        self.chkFinance.setEnabled(True)
        self.chkFinance.setCheckable(True)
        self.chkFinance.setObjectName(_fromUtf8("chkFinance"))
        self.gridLayout.addWidget(self.chkFinance, 10, 0, 1, 1)
        self.cmbFinance = CCheckableComboBox(StationaryReportForMIACSetupDialog)
        self.cmbFinance.setEnabled(False)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 10, 1, 1, 4)
        self.lblStationaryType = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblStationaryType.setObjectName(_fromUtf8("lblStationaryType"))
        self.gridLayout.addWidget(self.lblStationaryType, 11, 0, 1, 1)
        self.cmbStationaryType = QtGui.QComboBox(StationaryReportForMIACSetupDialog)
        self.cmbStationaryType.setObjectName(_fromUtf8("cmbStationaryType"))
        self.cmbStationaryType.addItem(_fromUtf8(""))
        self.cmbStationaryType.addItem(_fromUtf8(""))
        self.cmbStationaryType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbStationaryType, 11, 1, 1, 4)
        self.lblAgePresence = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.lblAgePresence.setObjectName(_fromUtf8("lblAgePresence"))
        self.gridLayout.addWidget(self.lblAgePresence, 12, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edtBedAgeFor = QtGui.QSpinBox(StationaryReportForMIACSetupDialog)
        self.edtBedAgeFor.setMaximum(150)
        self.edtBedAgeFor.setObjectName(_fromUtf8("edtBedAgeFor"))
        self.horizontalLayout.addWidget(self.edtBedAgeFor)
        self.label_2 = QtGui.QLabel(StationaryReportForMIACSetupDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.edtBedAgeTo = QtGui.QSpinBox(StationaryReportForMIACSetupDialog)
        self.edtBedAgeTo.setMinimum(0)
        self.edtBedAgeTo.setMaximum(150)
        self.edtBedAgeTo.setObjectName(_fromUtf8("edtBedAgeTo"))
        self.horizontalLayout.addWidget(self.edtBedAgeTo)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(142, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 12, 3, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 13, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(StationaryReportForMIACSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 0, 1, 5)

        self.retranslateUi(StationaryReportForMIACSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StationaryReportForMIACSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StationaryReportForMIACSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StationaryReportForMIACSetupDialog)
        StationaryReportForMIACSetupDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        StationaryReportForMIACSetupDialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        StationaryReportForMIACSetupDialog.setTabOrder(self.edtEndDate, self.edtTimeEdit)
        StationaryReportForMIACSetupDialog.setTabOrder(self.edtTimeEdit, self.btnOrgStructureList)
        StationaryReportForMIACSetupDialog.setTabOrder(self.btnOrgStructureList, self.btnHospitalBedProfileList)
        StationaryReportForMIACSetupDialog.setTabOrder(self.btnHospitalBedProfileList, self.cmbSchedule)
        StationaryReportForMIACSetupDialog.setTabOrder(self.cmbSchedule, self.chkNoProfileBed)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkNoProfileBed, self.chkIsPermanentBed)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkIsPermanentBed, self.chkNoPrintCaption)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkNoPrintCaption, self.chkNoPrintFilterParameters)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkNoPrintFilterParameters, self.chkIsGroupingOS)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkIsGroupingOS, self.chkFinance)
        StationaryReportForMIACSetupDialog.setTabOrder(self.chkFinance, self.cmbFinance)
        StationaryReportForMIACSetupDialog.setTabOrder(self.cmbFinance, self.cmbStationaryType)
        StationaryReportForMIACSetupDialog.setTabOrder(self.cmbStationaryType, self.buttonBox)

    def retranslateUi(self, StationaryReportForMIACSetupDialog):
        StationaryReportForMIACSetupDialog.setWindowTitle(_translate("StationaryReportForMIACSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("StationaryReportForMIACSetupDialog", "Дата начала", None))
        self.edtBegDate.setDisplayFormat(_translate("StationaryReportForMIACSetupDialog", "dd.MM.yyyy", None))
        self.lblEndDate.setText(_translate("StationaryReportForMIACSetupDialog", "Текущий день", None))
        self.edtEndDate.setDisplayFormat(_translate("StationaryReportForMIACSetupDialog", "dd.MM.yyyy", None))
        self.btnOrgStructureList.setText(_translate("StationaryReportForMIACSetupDialog", "Подразделение", None))
        self.lblOrgStructureList.setText(_translate("StationaryReportForMIACSetupDialog", " ЛПУ", None))
        self.btnHospitalBedProfileList.setText(_translate("StationaryReportForMIACSetupDialog", "Профиль койки", None))
        self.lblHospitalBedProfileList.setText(_translate("StationaryReportForMIACSetupDialog", " не задано", None))
        self.lblSchedule.setText(_translate("StationaryReportForMIACSetupDialog", "Режим койки", None))
        self.cmbSchedule.setItemText(0, _translate("StationaryReportForMIACSetupDialog", "Не учитывать", None))
        self.cmbSchedule.setItemText(1, _translate("StationaryReportForMIACSetupDialog", "Круглосуточные", None))
        self.cmbSchedule.setItemText(2, _translate("StationaryReportForMIACSetupDialog", "Не круглосуточные", None))
        self.chkNoProfileBed.setText(_translate("StationaryReportForMIACSetupDialog", "Учитывать койки без профиля", None))
        self.chkIsPermanentBed.setText(_translate("StationaryReportForMIACSetupDialog", "Добавить внештатные койки в коечный фонд", None))
        self.chkNoPrintCaption.setText(_translate("StationaryReportForMIACSetupDialog", "Не печатать заголовок отчета", None))
        self.chkNoPrintFilterParameters.setText(_translate("StationaryReportForMIACSetupDialog", "Не печатать параметры фильтра", None))
        self.chkIsGroupingOS.setText(_translate("StationaryReportForMIACSetupDialog", "Группировка по подразделениям", None))
        self.chkFinance.setText(_translate("StationaryReportForMIACSetupDialog", "Тип финансирования", None))
        self.lblStationaryType.setText(_translate("StationaryReportForMIACSetupDialog", "Тип стационара", None))
        self.cmbStationaryType.setItemText(0, _translate("StationaryReportForMIACSetupDialog", "Не задано", None))
        self.cmbStationaryType.setItemText(1, _translate("StationaryReportForMIACSetupDialog", "Дневной", None))
        self.cmbStationaryType.setItemText(2, _translate("StationaryReportForMIACSetupDialog", "Круглосуточный", None))
        self.lblAgePresence.setText(_translate("StationaryReportForMIACSetupDialog", "Возраст", None))
        self.label.setText(_translate("StationaryReportForMIACSetupDialog", "с", None))
        self.label_2.setText(_translate("StationaryReportForMIACSetupDialog", "по", None))

from Reports.Utils import CCheckableComboBox
from library.DateEdit import CDateEdit
