# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Reports\VisitByPurposeEventsDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VisitByPurposeEventsSetupDialog(object):
    def setupUi(self, VisitByPurposeEventsSetupDialog):
        VisitByPurposeEventsSetupDialog.setObjectName(_fromUtf8("VisitByPurposeEventsSetupDialog"))
        VisitByPurposeEventsSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        VisitByPurposeEventsSetupDialog.resize(539, 355)
        VisitByPurposeEventsSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(VisitByPurposeEventsSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEndDateConfirmation = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblEndDateConfirmation.setEnabled(False)
        self.lblEndDateConfirmation.setObjectName(_fromUtf8("lblEndDateConfirmation"))
        self.gridLayout.addWidget(self.lblEndDateConfirmation, 11, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 2, 1, 1)
        self.edtBegDate = CDateEdit(VisitByPurposeEventsSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 2)
        self.lblPerson = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(VisitByPurposeEventsSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 2, 1, 2)
        self.lblSpeciality = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 2)
        self.lblEndDate = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.lblBegDate = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(VisitByPurposeEventsSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 15, 0, 1, 4)
        self.lblRefuseType = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblRefuseType.setEnabled(False)
        self.lblRefuseType.setObjectName(_fromUtf8("lblRefuseType"))
        self.gridLayout.addWidget(self.lblRefuseType, 12, 0, 1, 1)
        self.lblBegDateConfirmation = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblBegDateConfirmation.setEnabled(False)
        self.lblBegDateConfirmation.setObjectName(_fromUtf8("lblBegDateConfirmation"))
        self.gridLayout.addWidget(self.lblBegDateConfirmation, 10, 0, 1, 1)
        self.lblConfirmationType = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblConfirmationType.setEnabled(False)
        self.lblConfirmationType.setObjectName(_fromUtf8("lblConfirmationType"))
        self.gridLayout.addWidget(self.lblConfirmationType, 9, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(VisitByPurposeEventsSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 2, 1, 2)
        self.edtConfirmationBegDate = CDateEdit(VisitByPurposeEventsSetupDialog)
        self.edtConfirmationBegDate.setEnabled(False)
        self.edtConfirmationBegDate.setObjectName(_fromUtf8("edtConfirmationBegDate"))
        self.gridLayout.addWidget(self.edtConfirmationBegDate, 10, 2, 1, 1)
        self.cmbSpeciality = CRBComboBox(VisitByPurposeEventsSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 2, 1, 2)
        self.edtEndDate = CDateEdit(VisitByPurposeEventsSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        self.edtConfirmationEndDate = CDateEdit(VisitByPurposeEventsSetupDialog)
        self.edtConfirmationEndDate.setEnabled(False)
        self.edtConfirmationEndDate.setObjectName(_fromUtf8("edtConfirmationEndDate"))
        self.gridLayout.addWidget(self.edtConfirmationEndDate, 11, 2, 1, 1)
        self.chkConfirmation = QtGui.QCheckBox(VisitByPurposeEventsSetupDialog)
        self.chkConfirmation.setObjectName(_fromUtf8("chkConfirmation"))
        self.gridLayout.addWidget(self.chkConfirmation, 7, 1, 1, 3)
        self.cmbConfirmationType = QtGui.QComboBox(VisitByPurposeEventsSetupDialog)
        self.cmbConfirmationType.setEnabled(False)
        self.cmbConfirmationType.setObjectName(_fromUtf8("cmbConfirmationType"))
        self.gridLayout.addWidget(self.cmbConfirmationType, 9, 2, 1, 2)
        self.lblFilterAgeFrom = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblFilterAgeFrom.setEnabled(True)
        self.lblFilterAgeFrom.setObjectName(_fromUtf8("lblFilterAgeFrom"))
        self.gridLayout.addWidget(self.lblFilterAgeFrom, 13, 0, 1, 1)
        self.cmbRefuseType = CRBComboBox(VisitByPurposeEventsSetupDialog)
        self.cmbRefuseType.setEnabled(False)
        self.cmbRefuseType.setObjectName(_fromUtf8("cmbRefuseType"))
        self.gridLayout.addWidget(self.cmbRefuseType, 12, 2, 1, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edtFilterEndAge = QtGui.QSpinBox(VisitByPurposeEventsSetupDialog)
        self.edtFilterEndAge.setEnabled(True)
        self.edtFilterEndAge.setMaximum(150)
        self.edtFilterEndAge.setProperty("value", 150)
        self.edtFilterEndAge.setObjectName(_fromUtf8("edtFilterEndAge"))
        self.gridLayout_3.addWidget(self.edtFilterEndAge, 0, 3, 1, 1)
        self.edtFilterBegAge = QtGui.QSpinBox(VisitByPurposeEventsSetupDialog)
        self.edtFilterBegAge.setEnabled(True)
        self.edtFilterBegAge.setMaximum(150)
        self.edtFilterBegAge.setObjectName(_fromUtf8("edtFilterBegAge"))
        self.gridLayout_3.addWidget(self.edtFilterBegAge, 0, 1, 1, 1)
        self.lblFilterAgeTo = QtGui.QLabel(VisitByPurposeEventsSetupDialog)
        self.lblFilterAgeTo.setEnabled(True)
        self.lblFilterAgeTo.setObjectName(_fromUtf8("lblFilterAgeTo"))
        self.gridLayout_3.addWidget(self.lblFilterAgeTo, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 13, 2, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.lblEndDateConfirmation.setBuddy(self.edtConfirmationEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblRefuseType.setBuddy(self.cmbRefuseType)
        self.lblBegDateConfirmation.setBuddy(self.edtConfirmationBegDate)
        self.lblConfirmationType.setBuddy(self.cmbConfirmationType)
        self.lblFilterAgeFrom.setBuddy(self.edtFilterBegAge)
        self.lblFilterAgeTo.setBuddy(self.edtFilterEndAge)

        self.retranslateUi(VisitByPurposeEventsSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), VisitByPurposeEventsSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), VisitByPurposeEventsSetupDialog.reject)
        QtCore.QObject.connect(self.chkConfirmation, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), VisitByPurposeEventsSetupDialog.onStateChanged)
        QtCore.QMetaObject.connectSlotsByName(VisitByPurposeEventsSetupDialog)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.cmbPerson, self.chkConfirmation)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.chkConfirmation, self.cmbConfirmationType)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.cmbConfirmationType, self.edtConfirmationBegDate)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtConfirmationBegDate, self.edtConfirmationEndDate)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtConfirmationEndDate, self.cmbRefuseType)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.cmbRefuseType, self.edtFilterBegAge)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtFilterBegAge, self.edtFilterEndAge)
        VisitByPurposeEventsSetupDialog.setTabOrder(self.edtFilterEndAge, self.buttonBox)

    def retranslateUi(self, VisitByPurposeEventsSetupDialog):
        VisitByPurposeEventsSetupDialog.setWindowTitle(_translate("VisitByPurposeEventsSetupDialog", "параметры отчёта", None))
        self.lblEndDateConfirmation.setText(_translate("VisitByPurposeEventsSetupDialog", "Окончание периода подтверждения:", None))
        self.lblOrgStructure.setText(_translate("VisitByPurposeEventsSetupDialog", "&Подразделение", None))
        self.lblPerson.setText(_translate("VisitByPurposeEventsSetupDialog", "&Врач", None))
        self.lblSpeciality.setText(_translate("VisitByPurposeEventsSetupDialog", "&Специальность", None))
        self.lblEndDate.setText(_translate("VisitByPurposeEventsSetupDialog", "Дата &окончания периода", None))
        self.lblBegDate.setText(_translate("VisitByPurposeEventsSetupDialog", "Дата &начала периода", None))
        self.lblRefuseType.setText(_translate("VisitByPurposeEventsSetupDialog", "Причина отказа:", None))
        self.lblBegDateConfirmation.setText(_translate("VisitByPurposeEventsSetupDialog", "Начало периода подтверждения:", None))
        self.lblConfirmationType.setText(_translate("VisitByPurposeEventsSetupDialog", "Тип подтверждения:", None))
        self.cmbSpeciality.setWhatsThis(_translate("VisitByPurposeEventsSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.chkConfirmation.setText(_translate("VisitByPurposeEventsSetupDialog", "Подтверждение оплаты", None))
        self.lblFilterAgeFrom.setText(_translate("VisitByPurposeEventsSetupDialog", "Возраст с", None))
        self.lblFilterAgeTo.setText(_translate("VisitByPurposeEventsSetupDialog", "по", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
