# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F027.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(872, 869)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_3 = QtGui.QSplitter(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.scrollArea = QtGui.QScrollArea(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.tabWidget = QtGui.QTabWidget()
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 862, 713))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabToken)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter_2 = QtGui.QSplitter(self.tabToken)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frameBaseAndDiagnosises = QtGui.QFrame(self.splitter_2)
        self.frameBaseAndDiagnosises.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBaseAndDiagnosises.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBaseAndDiagnosises.setObjectName(_fromUtf8("frameBaseAndDiagnosises"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameBaseAndDiagnosises)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.grpBase = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout = QtGui.QGridLayout(self.grpBase)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblRelegateOrg = QtGui.QLabel(self.grpBase)
        self.lblRelegateOrg.setObjectName(_fromUtf8("lblRelegateOrg"))
        self.gridLayout.addWidget(self.lblRelegateOrg, 0, 0, 1, 1)
        self.cmbRelegateOrg = CPolyclinicComboBox(self.grpBase)
        self.cmbRelegateOrg.setEnabled(True)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.gridLayout.addWidget(self.cmbRelegateOrg, 0, 1, 1, 4)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.grpBase)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtBegDate = CDateEdit(self.frame_2)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_2.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frame_2)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setCalendarPopup(False)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_2.addWidget(self.edtBegTime)
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 4)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 3, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.grpBase)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtEndDate = CDateEdit(self.frame_3)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_3.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frame_3)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setCalendarPopup(False)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_3.addWidget(self.edtEndTime)
        self.gridLayout.addWidget(self.frame_3, 3, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 5, 1, 1)
        self.chkPrimary = QtGui.QCheckBox(self.grpBase)
        self.chkPrimary.setObjectName(_fromUtf8("chkPrimary"))
        self.gridLayout.addWidget(self.chkPrimary, 6, 0, 1, 2)
        self.lblOrder = QtGui.QLabel(self.grpBase)
        self.lblOrder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout.addWidget(self.lblOrder, 6, 3, 1, 3)
        self.cmbOrder = CROComboBox(self.grpBase)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOrder, 7, 0, 1, 6)
        self.lblPatientModel = QtGui.QLabel(self.grpBase)
        self.lblPatientModel.setObjectName(_fromUtf8("lblPatientModel"))
        self.gridLayout.addWidget(self.lblPatientModel, 8, 0, 1, 2)
        self.cmbPatientModel = CPatientModelComboBox(self.grpBase)
        self.cmbPatientModel.setObjectName(_fromUtf8("cmbPatientModel"))
        self.gridLayout.addWidget(self.cmbPatientModel, 8, 2, 1, 4)
        self.lblCureType = QtGui.QLabel(self.grpBase)
        self.lblCureType.setObjectName(_fromUtf8("lblCureType"))
        self.gridLayout.addWidget(self.lblCureType, 9, 0, 1, 2)
        self.cmbCureType = CRBComboBox(self.grpBase)
        self.cmbCureType.setObjectName(_fromUtf8("cmbCureType"))
        self.gridLayout.addWidget(self.cmbCureType, 9, 2, 1, 4)
        self.lblCureMethod = QtGui.QLabel(self.grpBase)
        self.lblCureMethod.setObjectName(_fromUtf8("lblCureMethod"))
        self.gridLayout.addWidget(self.lblCureMethod, 10, 0, 1, 2)
        self.cmbCureMethod = CRBComboBox(self.grpBase)
        self.cmbCureMethod.setObjectName(_fromUtf8("cmbCureMethod"))
        self.gridLayout.addWidget(self.cmbCureMethod, 10, 2, 1, 4)
        self.lblPersonMedicineHead = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPersonMedicineHead.sizePolicy().hasHeightForWidth())
        self.lblPersonMedicineHead.setSizePolicy(sizePolicy)
        self.lblPersonMedicineHead.setObjectName(_fromUtf8("lblPersonMedicineHead"))
        self.gridLayout.addWidget(self.lblPersonMedicineHead, 13, 0, 1, 2)
        self.cmbPersonMedicineHead = CPersonComboBoxEx(self.grpBase)
        self.cmbPersonMedicineHead.setObjectName(_fromUtf8("cmbPersonMedicineHead"))
        self.cmbPersonMedicineHead.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPersonMedicineHead, 13, 2, 1, 4)
        self.lblPersonManager = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPersonManager.sizePolicy().hasHeightForWidth())
        self.lblPersonManager.setSizePolicy(sizePolicy)
        self.lblPersonManager.setObjectName(_fromUtf8("lblPersonManager"))
        self.gridLayout.addWidget(self.lblPersonManager, 14, 0, 1, 2)
        self.cmbPersonManager = CPersonComboBoxEx(self.grpBase)
        self.cmbPersonManager.setObjectName(_fromUtf8("cmbPersonManager"))
        self.cmbPersonManager.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPersonManager, 14, 2, 1, 4)
        self.lblPersonCurator = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPersonCurator.sizePolicy().hasHeightForWidth())
        self.lblPersonCurator.setSizePolicy(sizePolicy)
        self.lblPersonCurator.setObjectName(_fromUtf8("lblPersonCurator"))
        self.gridLayout.addWidget(self.lblPersonCurator, 15, 0, 1, 1)
        self.lblPersonExpert = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPersonExpert.sizePolicy().hasHeightForWidth())
        self.lblPersonExpert.setSizePolicy(sizePolicy)
        self.lblPersonExpert.setObjectName(_fromUtf8("lblPersonExpert"))
        self.gridLayout.addWidget(self.lblPersonExpert, 16, 0, 1, 1)
        self.cmbPersonExpert = CPersonComboBoxEx(self.grpBase)
        self.cmbPersonExpert.setObjectName(_fromUtf8("cmbPersonExpert"))
        self.cmbPersonExpert.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPersonExpert, 16, 2, 1, 4)
        self.lblEventAssistantIdValue = QtGui.QLabel(self.grpBase)
        self.lblEventAssistantIdValue.setObjectName(_fromUtf8("lblEventAssistantIdValue"))
        self.gridLayout.addWidget(self.lblEventAssistantIdValue, 17, 0, 1, 2)
        self.cmbEventAssistant = CPersonComboBoxEx(self.grpBase)
        self.cmbEventAssistant.setObjectName(_fromUtf8("cmbEventAssistant"))
        self.gridLayout.addWidget(self.cmbEventAssistant, 17, 2, 1, 4)
        self.lblResult = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResult.sizePolicy().hasHeightForWidth())
        self.lblResult.setSizePolicy(sizePolicy)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout.addWidget(self.lblResult, 18, 0, 1, 2)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbResult, 18, 2, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 19, 1, 1, 3)
        self.btnSelectRelegateOrg = QtGui.QToolButton(self.grpBase)
        self.btnSelectRelegateOrg.setObjectName(_fromUtf8("btnSelectRelegateOrg"))
        self.gridLayout.addWidget(self.btnSelectRelegateOrg, 0, 5, 1, 1)
        self.edtEventExternalIdValue = QtGui.QLineEdit(self.grpBase)
        self.edtEventExternalIdValue.setObjectName(_fromUtf8("edtEventExternalIdValue"))
        self.gridLayout.addWidget(self.edtEventExternalIdValue, 4, 1, 1, 5)
        self.lblEventId = QtGui.QLabel(self.grpBase)
        self.lblEventId.setObjectName(_fromUtf8("lblEventId"))
        self.gridLayout.addWidget(self.lblEventId, 4, 0, 1, 1)
        self.cmbEventCurator = CPersonComboBoxEx(self.grpBase)
        self.cmbEventCurator.setObjectName(_fromUtf8("cmbEventCurator"))
        self.gridLayout.addWidget(self.cmbEventCurator, 12, 2, 1, 4)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPerson, 15, 2, 1, 4)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 12, 0, 1, 2)
        self.gridLayout_5.addWidget(self.grpBase, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.frameBaseAndDiagnosises)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.grpActions = QtGui.QGroupBox(self.frame)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpActions)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tblActions = CActionPropertiesTableView(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblActions.sizePolicy().hasHeightForWidth())
        self.tblActions.setSizePolicy(sizePolicy)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.gridLayout_6.addWidget(self.tblActions, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grpActions, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grpInspections_2 = QtGui.QGroupBox(self.splitter)
        self.grpInspections_2.setObjectName(_fromUtf8("grpInspections_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpInspections_2)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblPreliminaryDiagnostics = CDiagnosticsInDocTableView(self.grpInspections_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPreliminaryDiagnostics.sizePolicy().hasHeightForWidth())
        self.tblPreliminaryDiagnostics.setSizePolicy(sizePolicy)
        self.tblPreliminaryDiagnostics.setMinimumSize(QtCore.QSize(0, 100))
        self.tblPreliminaryDiagnostics.setObjectName(_fromUtf8("tblPreliminaryDiagnostics"))
        self.gridLayout_2.addWidget(self.tblPreliminaryDiagnostics, 0, 0, 1, 1)
        self.grpInspections = QtGui.QGroupBox(self.splitter)
        self.grpInspections.setObjectName(_fromUtf8("grpInspections"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpInspections)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblFinalDiagnostics = CDiagnosticsInDocTableView(self.grpInspections)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFinalDiagnostics.sizePolicy().hasHeightForWidth())
        self.tblFinalDiagnostics.setSizePolicy(sizePolicy)
        self.tblFinalDiagnostics.setMinimumSize(QtCore.QSize(0, 100))
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self.gridLayout_3.addWidget(self.tblFinalDiagnostics, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMisc = CActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabNotes = CEventNotesPageProtocol()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.scrollArea.setWidget(self.tabWidget)
        self.gridLayout_4.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout.addWidget(self.statusBar)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lblProlongateEvent = QtGui.QLabel(Dialog)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout.addWidget(self.lblValueExternalId)
        self.lblValueMesCode = QtGui.QLabel(Dialog)
        self.lblValueMesCode.setText(_fromUtf8(""))
        self.lblValueMesCode.setObjectName(_fromUtf8("lblValueMesCode"))
        self.horizontalLayout.addWidget(self.lblValueMesCode)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.lblRelegateOrg.setBuddy(self.cmbRelegateOrg)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrder.setBuddy(self.cmbOrder)
        self.lblPatientModel.setBuddy(self.cmbPatientModel)
        self.lblCureType.setBuddy(self.cmbCureType)
        self.lblCureMethod.setBuddy(self.cmbCureMethod)
        self.lblPersonMedicineHead.setBuddy(self.cmbPerson)
        self.lblPersonManager.setBuddy(self.cmbPerson)
        self.lblPersonCurator.setBuddy(self.cmbPerson)
        self.lblPersonExpert.setBuddy(self.cmbPerson)
        self.lblEventAssistantIdValue.setBuddy(self.cmbEventAssistant)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblPerson.setBuddy(self.cmbPerson)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtClientInfoBrowser, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        Dialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        Dialog.setTabOrder(self.edtEndTime, self.chkPrimary)
        Dialog.setTabOrder(self.chkPrimary, self.cmbOrder)
        Dialog.setTabOrder(self.cmbOrder, self.cmbResult)
        Dialog.setTabOrder(self.cmbResult, self.tblFinalDiagnostics)
        Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblActions)
        Dialog.setTabOrder(self.tblActions, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.027", None))
        self.lblRelegateOrg.setText(_translate("Dialog", "Направитель", None))
        self.lblBegDate.setText(_translate("Dialog", "Открыт", None))
        self.edtBegDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblEndDate.setText(_translate("Dialog", "Закрыт", None))
        self.edtEndDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.chkPrimary.setText(_translate("Dialog", "Пе&рвичный", None))
        self.lblOrder.setText(_translate("Dialog", "П&орядок", None))
        self.cmbOrder.setItemText(0, _translate("Dialog", "Плановый", None))
        self.cmbOrder.setItemText(1, _translate("Dialog", "Экстренный", None))
        self.cmbOrder.setItemText(2, _translate("Dialog", "Самотёком", None))
        self.cmbOrder.setItemText(3, _translate("Dialog", "Принудительный", None))
        self.cmbOrder.setItemText(4, _translate("Dialog", "Внутренний перевод", None))
        self.cmbOrder.setItemText(5, _translate("Dialog", "Неотложная", None))
        self.lblPatientModel.setText(_translate("Dialog", "Модель пациента", None))
        self.lblCureType.setText(_translate("Dialog", "Вид лечения", None))
        self.lblCureMethod.setText(_translate("Dialog", "Метод лечения", None))
        self.lblPersonMedicineHead.setText(_translate("Dialog", "Нач.мед.", None))
        self.cmbPersonMedicineHead.setWhatsThis(_translate("Dialog", "назначивший действие \"протокол\"", None))
        self.cmbPersonMedicineHead.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblPersonManager.setText(_translate("Dialog", "Зав.отд.", None))
        self.cmbPersonManager.setWhatsThis(_translate("Dialog", "ответственный за Действие \"протокол\"", None))
        self.cmbPersonManager.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblPersonCurator.setText(_translate("Dialog", "Лечащий врач", None))
        self.lblPersonExpert.setText(_translate("Dialog", "Специалист", None))
        self.cmbPersonExpert.setWhatsThis(_translate("Dialog", "ассистент Действия протокол\"", None))
        self.cmbPersonExpert.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblEventAssistantIdValue.setText(_translate("Dialog", "Зам.гл.врача по КЭР", None))
        self.cmbEventAssistant.setWhatsThis(_translate("Dialog", "ассистент События", None))
        self.lblResult.setText(_translate("Dialog", "Результат", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.btnSelectRelegateOrg.setText(_translate("Dialog", "...", None))
        self.lblEventId.setText(_translate("Dialog", "Номер", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblPerson.setText(_translate("Dialog", "Председатель", None))
        self.grpActions.setTitle(_translate("Dialog", "Протокол", None))
        self.grpInspections_2.setTitle(_translate("Dialog", "&Предварительный диагноз", None))
        self.grpInspections.setTitle(_translate("Dialog", "&Заключительный диагноз", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Протокол", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionsPage import CActionsPage
from Events.AmbCardPage import CAmbCardPage
from Events.EventDiagnosticsTable import CDiagnosticsInDocTableView
from Events.widgets.PatientModelComboBox import CPatientModelComboBox
from F027.EventNotesPageProtocol import CEventNotesPageProtocol
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ROComboBox import CROComboBox
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
