# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\Samson\UP_s11\client_merge\Resources\JobsOperatingDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobsOperatingDialog(object):
    def setupUi(self, JobsOperatingDialog):
        JobsOperatingDialog.setObjectName(_fromUtf8("JobsOperatingDialog"))
        JobsOperatingDialog.resize(1126, 884)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JobsOperatingDialog.sizePolicy().hasHeightForWidth())
        JobsOperatingDialog.setSizePolicy(sizePolicy)
        JobsOperatingDialog.setMinimumSize(QtCore.QSize(700, 500))
        JobsOperatingDialog.setBaseSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtGui.QVBoxLayout(JobsOperatingDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(JobsOperatingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1087, 853))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitter_2 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pnlFilter = QtGui.QWidget(self.splitter_2)
        self.pnlFilter.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlFilter.sizePolicy().hasHeightForWidth())
        self.pnlFilter.setSizePolicy(sizePolicy)
        self.pnlFilter.setObjectName(_fromUtf8("pnlFilter"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlFilter)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pnlSmartFilter = QtGui.QWidget(self.pnlFilter)
        self.pnlSmartFilter.setObjectName(_fromUtf8("pnlSmartFilter"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pnlSmartFilter)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitter = QtGui.QSplitter(self.pnlSmartFilter)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeOrgStructure = QtGui.QTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.treeOrgStructure.sizePolicy().hasHeightForWidth())
        self.treeOrgStructure.setSizePolicy(sizePolicy)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.tabDateClientFilter = QtGui.QTabWidget(self.splitter)
        self.tabDateClientFilter.setObjectName(_fromUtf8("tabDateClientFilter"))
        self.tabDateFilter = QtGui.QWidget()
        self.tabDateFilter.setObjectName(_fromUtf8("tabDateFilter"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabDateFilter)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.pnlDateRange = QtGui.QWidget(self.tabDateFilter)
        self.pnlDateRange.setEnabled(False)
        self.pnlDateRange.setObjectName(_fromUtf8("pnlDateRange"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pnlDateRange)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblDateRangeFrom = QtGui.QLabel(self.pnlDateRange)
        self.lblDateRangeFrom.setObjectName(_fromUtf8("lblDateRangeFrom"))
        self.horizontalLayout_2.addWidget(self.lblDateRangeFrom)
        self.edtBegDate = CDateEdit(self.pnlDateRange)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_2.addWidget(self.edtBegDate)
        self.lblDateRangeTo = QtGui.QLabel(self.pnlDateRange)
        self.lblDateRangeTo.setObjectName(_fromUtf8("lblDateRangeTo"))
        self.horizontalLayout_2.addWidget(self.lblDateRangeTo)
        self.edtEndDate = CDateEdit(self.pnlDateRange)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_2.addWidget(self.edtEndDate)
        self.gridLayout_7.addWidget(self.pnlDateRange, 3, 1, 1, 1)
        self.btnCalendarDate = QtGui.QRadioButton(self.tabDateFilter)
        self.btnCalendarDate.setText(_fromUtf8(""))
        self.btnCalendarDate.setCheckable(True)
        self.btnCalendarDate.setChecked(True)
        self.btnCalendarDate.setObjectName(_fromUtf8("btnCalendarDate"))
        self.gridLayout_7.addWidget(self.btnCalendarDate, 1, 0, 1, 1)
        self.btnDateRange = QtGui.QRadioButton(self.tabDateFilter)
        self.btnDateRange.setText(_fromUtf8(""))
        self.btnDateRange.setObjectName(_fromUtf8("btnDateRange"))
        self.gridLayout_7.addWidget(self.btnDateRange, 3, 0, 1, 1)
        self.calendar = CCalendarWidget(self.tabDateFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendar.setGridVisible(False)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.gridLayout_7.addWidget(self.calendar, 1, 1, 2, 1)
        self.cmbDateType = QtGui.QComboBox(self.tabDateFilter)
        self.cmbDateType.setObjectName(_fromUtf8("cmbDateType"))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.cmbDateType.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbDateType, 0, 0, 1, 2)
        self.tabDateClientFilter.addTab(self.tabDateFilter, _fromUtf8(""))
        self.tabClientFilter = QtGui.QWidget()
        self.tabClientFilter.setObjectName(_fromUtf8("tabClientFilter"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabClientFilter)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.edtClientId = QtGui.QLineEdit(self.tabClientFilter)
        self.edtClientId.setEnabled(False)
        self.edtClientId.setInputMask(_fromUtf8(""))
        self.edtClientId.setMaxLength(32767)
        self.edtClientId.setObjectName(_fromUtf8("edtClientId"))
        self.gridLayout_8.addWidget(self.edtClientId, 1, 0, 1, 2)
        self.cmbClientAccountingSystem = CRBComboBox(self.tabClientFilter)
        self.cmbClientAccountingSystem.setEnabled(False)
        self.cmbClientAccountingSystem.setObjectName(_fromUtf8("cmbClientAccountingSystem"))
        self.gridLayout_8.addWidget(self.cmbClientAccountingSystem, 0, 1, 1, 1)
        self.chkClientId = QtGui.QCheckBox(self.tabClientFilter)
        self.chkClientId.setObjectName(_fromUtf8("chkClientId"))
        self.gridLayout_8.addWidget(self.chkClientId, 0, 0, 1, 1)
        self.chkClientLastName = QtGui.QCheckBox(self.tabClientFilter)
        self.chkClientLastName.setObjectName(_fromUtf8("chkClientLastName"))
        self.gridLayout_8.addWidget(self.chkClientLastName, 2, 0, 1, 1)
        self.edtClientLastName = QtGui.QLineEdit(self.tabClientFilter)
        self.edtClientLastName.setEnabled(False)
        self.edtClientLastName.setObjectName(_fromUtf8("edtClientLastName"))
        self.gridLayout_8.addWidget(self.edtClientLastName, 2, 1, 1, 1)
        self.chkClientFirstName = QtGui.QCheckBox(self.tabClientFilter)
        self.chkClientFirstName.setObjectName(_fromUtf8("chkClientFirstName"))
        self.gridLayout_8.addWidget(self.chkClientFirstName, 3, 0, 1, 1)
        self.edtClientFirstName = QtGui.QLineEdit(self.tabClientFilter)
        self.edtClientFirstName.setEnabled(False)
        self.edtClientFirstName.setObjectName(_fromUtf8("edtClientFirstName"))
        self.gridLayout_8.addWidget(self.edtClientFirstName, 3, 1, 1, 1)
        self.chkClientPatrName = QtGui.QCheckBox(self.tabClientFilter)
        self.chkClientPatrName.setObjectName(_fromUtf8("chkClientPatrName"))
        self.gridLayout_8.addWidget(self.chkClientPatrName, 4, 0, 1, 1)
        self.edtClientPatrName = QtGui.QLineEdit(self.tabClientFilter)
        self.edtClientPatrName.setEnabled(False)
        self.edtClientPatrName.setObjectName(_fromUtf8("edtClientPatrName"))
        self.gridLayout_8.addWidget(self.edtClientPatrName, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 7, 0, 1, 1)
        self.chkExternalEventId = QtGui.QCheckBox(self.tabClientFilter)
        self.chkExternalEventId.setObjectName(_fromUtf8("chkExternalEventId"))
        self.gridLayout_8.addWidget(self.chkExternalEventId, 5, 0, 1, 1)
        self.edtExternalEventId = QtGui.QLineEdit(self.tabClientFilter)
        self.edtExternalEventId.setEnabled(False)
        self.edtExternalEventId.setObjectName(_fromUtf8("edtExternalEventId"))
        self.gridLayout_8.addWidget(self.edtExternalEventId, 5, 1, 1, 1)
        self.chkClientBirthDate = QtGui.QCheckBox(self.tabClientFilter)
        self.chkClientBirthDate.setObjectName(_fromUtf8("chkClientBirthDate"))
        self.gridLayout_8.addWidget(self.chkClientBirthDate, 6, 0, 1, 1)
        self.edtClientBirthDate = CDateEdit(self.tabClientFilter)
        self.edtClientBirthDate.setEnabled(False)
        self.edtClientBirthDate.setCalendarPopup(True)
        self.edtClientBirthDate.setObjectName(_fromUtf8("edtClientBirthDate"))
        self.gridLayout_8.addWidget(self.edtClientBirthDate, 6, 1, 1, 1)
        self.tabDateClientFilter.addTab(self.tabClientFilter, _fromUtf8(""))
        self.tblJobTypes = CTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tblJobTypes.sizePolicy().hasHeightForWidth())
        self.tblJobTypes.setSizePolicy(sizePolicy)
        self.tblJobTypes.setObjectName(_fromUtf8("tblJobTypes"))
        self.gridLayout_6.addWidget(self.splitter, 1, 0, 1, 1)
        self.cmbOrgStructureType = QtGui.QComboBox(self.pnlSmartFilter)
        self.cmbOrgStructureType.setObjectName(_fromUtf8("cmbOrgStructureType"))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbOrgStructureType, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.pnlSmartFilter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout_3 = QtGui.QFormLayout(self.widget)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbOnScanSelect = QtGui.QComboBox(self.widget)
        self.cmbOnScanSelect.setObjectName(_fromUtf8("cmbOnScanSelect"))
        self.cmbOnScanSelect.addItem(_fromUtf8(""))
        self.cmbOnScanSelect.addItem(_fromUtf8(""))
        self.cmbOnScanSelect.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbOnScanSelect)
        self.cmbOnScan = QtGui.QComboBox(self.widget)
        self.cmbOnScan.setObjectName(_fromUtf8("cmbOnScan"))
        self.cmbOnScan.addItem(_fromUtf8(""))
        self.cmbOnScan.addItem(_fromUtf8(""))
        self.cmbOnScan.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbOnScan)
        self.lblOnScan = QtGui.QLabel(self.widget)
        self.lblOnScan.setObjectName(_fromUtf8("lblOnScan"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblOnScan)
        self.gridLayout_6.addWidget(self.widget, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.pnlSmartFilter)
        self.grpStaticFilter = QtGui.QGroupBox(self.pnlFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpStaticFilter.sizePolicy().hasHeightForWidth())
        self.grpStaticFilter.setSizePolicy(sizePolicy)
        self.grpStaticFilter.setObjectName(_fromUtf8("grpStaticFilter"))
        self.gridLayout_9 = QtGui.QGridLayout(self.grpStaticFilter)
        self.gridLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblAge = QtGui.QLabel(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout_9.addWidget(self.lblAge, 14, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.grpStaticFilter)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_9.addWidget(self.cmbOrgStructure, 9, 2, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.grpStaticFilter)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbPerson, 12, 2, 1, 1)
        self.buttonBoxFilter = CApplyResetDialogButtonBox(self.grpStaticFilter)
        self.buttonBoxFilter.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxFilter.setObjectName(_fromUtf8("buttonBoxFilter"))
        self.gridLayout_9.addWidget(self.buttonBoxFilter, 15, 0, 1, 3)
        self.chkAwaiting = QtGui.QCheckBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAwaiting.sizePolicy().hasHeightForWidth())
        self.chkAwaiting.setSizePolicy(sizePolicy)
        self.chkAwaiting.setChecked(True)
        self.chkAwaiting.setObjectName(_fromUtf8("chkAwaiting"))
        self.gridLayout_9.addWidget(self.chkAwaiting, 2, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_9.addWidget(self.lblOrgStructure, 9, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_9.addWidget(self.lblPerson, 12, 0, 1, 1)
        self.cmbJobPurpose = CRBComboBox(self.grpStaticFilter)
        self.cmbJobPurpose.setObjectName(_fromUtf8("cmbJobPurpose"))
        self.gridLayout_9.addWidget(self.cmbJobPurpose, 7, 0, 1, 1)
        self.cmbTakenTissueType = CRBComboBox(self.grpStaticFilter)
        self.cmbTakenTissueType.setObjectName(_fromUtf8("cmbTakenTissueType"))
        self.gridLayout_9.addWidget(self.cmbTakenTissueType, 5, 0, 1, 1)
        self.chkEnueued = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkEnueued.setObjectName(_fromUtf8("chkEnueued"))
        self.gridLayout_9.addWidget(self.chkEnueued, 3, 2, 1, 1)
        self.line = QtGui.QFrame(self.grpStaticFilter)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_9.addWidget(self.line, 2, 1, 6, 1)
        self.lblSpeciality = QtGui.QLabel(self.grpStaticFilter)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout_9.addWidget(self.lblSpeciality, 10, 0, 1, 1)
        self.lblSex = QtGui.QLabel(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout_9.addWidget(self.lblSex, 13, 0, 1, 1)
        self.chkInProgress = QtGui.QCheckBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkInProgress.sizePolicy().hasHeightForWidth())
        self.chkInProgress.setSizePolicy(sizePolicy)
        self.chkInProgress.setAutoFillBackground(False)
        self.chkInProgress.setObjectName(_fromUtf8("chkInProgress"))
        self.gridLayout_9.addWidget(self.chkInProgress, 4, 2, 1, 1)
        self.lblTissueType = QtGui.QLabel(self.grpStaticFilter)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout_9.addWidget(self.lblTissueType, 2, 0, 1, 1)
        self.chkOnlyUrgent = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkOnlyUrgent.setObjectName(_fromUtf8("chkOnlyUrgent"))
        self.gridLayout_9.addWidget(self.chkOnlyUrgent, 6, 2, 1, 1)
        self.chkDone = QtGui.QCheckBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDone.sizePolicy().hasHeightForWidth())
        self.chkDone.setSizePolicy(sizePolicy)
        self.chkDone.setObjectName(_fromUtf8("chkDone"))
        self.gridLayout_9.addWidget(self.chkDone, 5, 2, 1, 1)
        self.cmbTissueType = CRBComboBox(self.grpStaticFilter)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout_9.addWidget(self.cmbTissueType, 3, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.grpStaticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbSex, 13, 2, 1, 1)
        self.chkJobTicketId = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkJobTicketId.setObjectName(_fromUtf8("chkJobTicketId"))
        self.gridLayout_9.addWidget(self.chkJobTicketId, 0, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(self.grpStaticFilter)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout_9.addWidget(self.cmbSpeciality, 10, 2, 1, 1)
        self.lblJobPurpose = QtGui.QLabel(self.grpStaticFilter)
        self.lblJobPurpose.setObjectName(_fromUtf8("lblJobPurpose"))
        self.gridLayout_9.addWidget(self.lblJobPurpose, 6, 0, 1, 1)
        self.lblTakenTissueType = QtGui.QLabel(self.grpStaticFilter)
        self.lblTakenTissueType.setObjectName(_fromUtf8("lblTakenTissueType"))
        self.gridLayout_9.addWidget(self.lblTakenTissueType, 4, 0, 1, 1)
        self.chkExpired = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkExpired.setStatusTip(_fromUtf8(""))
        self.chkExpired.setChecked(False)
        self.chkExpired.setTristate(False)
        self.chkExpired.setObjectName(_fromUtf8("chkExpired"))
        self.gridLayout_9.addWidget(self.chkExpired, 8, 2, 1, 1)
        self.chkHideDoneActions = QtGui.QCheckBox(self.grpStaticFilter)
        self.chkHideDoneActions.setStatusTip(_fromUtf8(""))
        self.chkHideDoneActions.setChecked(True)
        self.chkHideDoneActions.setTristate(False)
        self.chkHideDoneActions.setObjectName(_fromUtf8("chkHideDoneActions"))
        self.gridLayout_9.addWidget(self.chkHideDoneActions, 7, 2, 1, 1)
        self.frmAge = QtGui.QFrame(self.grpStaticFilter)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2)
        self.gridLayout_9.addWidget(self.frmAge, 14, 2, 1, 1)
        self.edtJobTicketId = QtGui.QLineEdit(self.grpStaticFilter)
        self.edtJobTicketId.setEnabled(False)
        self.edtJobTicketId.setObjectName(_fromUtf8("edtJobTicketId"))
        self.gridLayout_9.addWidget(self.edtJobTicketId, 1, 2, 1, 1)
        self.cmbScanBarcode = QtGui.QComboBox(self.grpStaticFilter)
        self.cmbScanBarcode.setEnabled(False)
        self.cmbScanBarcode.setObjectName(_fromUtf8("cmbScanBarcode"))
        self.cmbScanBarcode.addItem(_fromUtf8(""))
        self.cmbScanBarcode.addItem(_fromUtf8(""))
        self.cmbScanBarcode.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbScanBarcode, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpStaticFilter)
        self.pnlJobTickets = QtGui.QWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlJobTickets.sizePolicy().hasHeightForWidth())
        self.pnlJobTickets.setSizePolicy(sizePolicy)
        self.pnlJobTickets.setObjectName(_fromUtf8("pnlJobTickets"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pnlJobTickets)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter_3 = QtGui.QSplitter(self.pnlJobTickets)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pnlTickets = QtGui.QWidget(self.splitter_3)
        self.pnlTickets.setObjectName(_fromUtf8("pnlTickets"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pnlTickets)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tblJobTickets = CTableView(self.pnlTickets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblJobTickets.sizePolicy().hasHeightForWidth())
        self.tblJobTickets.setSizePolicy(sizePolicy)
        self.tblJobTickets.setObjectName(_fromUtf8("tblJobTickets"))
        self.verticalLayout_8.addWidget(self.tblJobTickets)
        self.lblTicketsCount = QtGui.QLabel(self.pnlTickets)
        self.lblTicketsCount.setObjectName(_fromUtf8("lblTicketsCount"))
        self.verticalLayout_8.addWidget(self.lblTicketsCount)
        self.pnlActions = QtGui.QWidget(self.splitter_3)
        self.pnlActions.setObjectName(_fromUtf8("pnlActions"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.pnlActions)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tblJobTicketActions = CTableView(self.pnlActions)
        self.tblJobTicketActions.setObjectName(_fromUtf8("tblJobTicketActions"))
        self.verticalLayout_9.addWidget(self.tblJobTicketActions)
        self.lblActionsCount = QtGui.QLabel(self.pnlActions)
        self.lblActionsCount.setObjectName(_fromUtf8("lblActionsCount"))
        self.verticalLayout_9.addWidget(self.lblActionsCount)
        self.verticalLayout_7.addWidget(self.splitter_3)
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(JobsOperatingDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblTissueType.setBuddy(self.cmbTissueType)
        self.lblJobPurpose.setBuddy(self.cmbJobPurpose)
        self.lblTakenTissueType.setBuddy(self.cmbTakenTissueType)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)

        self.retranslateUi(JobsOperatingDialog)
        self.tabDateClientFilter.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), JobsOperatingDialog.reject)
        QtCore.QObject.connect(self.chkClientId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClientAccountingSystem.setEnabled)
        QtCore.QObject.connect(self.chkClientId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientId.setEnabled)
        QtCore.QObject.connect(self.chkClientLastName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientLastName.setEnabled)
        QtCore.QObject.connect(self.chkClientFirstName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientFirstName.setEnabled)
        QtCore.QObject.connect(self.chkClientPatrName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientPatrName.setEnabled)
        QtCore.QObject.connect(self.chkClientId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClientAccountingSystem.setFocus)
        QtCore.QObject.connect(self.chkClientLastName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientLastName.setFocus)
        QtCore.QObject.connect(self.chkClientFirstName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientFirstName.setFocus)
        QtCore.QObject.connect(self.chkClientPatrName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientPatrName.setFocus)
        QtCore.QObject.connect(self.chkJobTicketId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtJobTicketId.setEnabled)
        QtCore.QObject.connect(self.btnCalendarDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calendar.setEnabled)
        QtCore.QObject.connect(self.btnCalendarDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pnlDateRange.setDisabled)
        QtCore.QObject.connect(self.btnDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pnlDateRange.setEnabled)
        QtCore.QObject.connect(self.btnDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calendar.setDisabled)
        QtCore.QObject.connect(self.treeOrgStructure, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), JobsOperatingDialog.updateJobTicketList)
        QtCore.QObject.connect(self.chkExternalEventId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtExternalEventId.setEnabled)
        QtCore.QObject.connect(self.chkExternalEventId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtExternalEventId.setFocus)
        QtCore.QObject.connect(self.chkClientBirthDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientBirthDate.setEnabled)
        QtCore.QObject.connect(self.chkClientBirthDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtClientBirthDate.setFocus)
        QtCore.QMetaObject.connectSlotsByName(JobsOperatingDialog)
        JobsOperatingDialog.setTabOrder(self.cmbOrgStructureType, self.treeOrgStructure)
        JobsOperatingDialog.setTabOrder(self.treeOrgStructure, self.tabDateClientFilter)
        JobsOperatingDialog.setTabOrder(self.tabDateClientFilter, self.cmbDateType)
        JobsOperatingDialog.setTabOrder(self.cmbDateType, self.btnCalendarDate)
        JobsOperatingDialog.setTabOrder(self.btnCalendarDate, self.calendar)
        JobsOperatingDialog.setTabOrder(self.calendar, self.btnDateRange)
        JobsOperatingDialog.setTabOrder(self.btnDateRange, self.edtBegDate)
        JobsOperatingDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        JobsOperatingDialog.setTabOrder(self.edtEndDate, self.chkClientId)
        JobsOperatingDialog.setTabOrder(self.chkClientId, self.cmbClientAccountingSystem)
        JobsOperatingDialog.setTabOrder(self.cmbClientAccountingSystem, self.edtClientId)
        JobsOperatingDialog.setTabOrder(self.edtClientId, self.chkClientLastName)
        JobsOperatingDialog.setTabOrder(self.chkClientLastName, self.edtClientLastName)
        JobsOperatingDialog.setTabOrder(self.edtClientLastName, self.chkClientFirstName)
        JobsOperatingDialog.setTabOrder(self.chkClientFirstName, self.edtClientFirstName)
        JobsOperatingDialog.setTabOrder(self.edtClientFirstName, self.chkClientPatrName)
        JobsOperatingDialog.setTabOrder(self.chkClientPatrName, self.edtClientPatrName)
        JobsOperatingDialog.setTabOrder(self.edtClientPatrName, self.chkExternalEventId)
        JobsOperatingDialog.setTabOrder(self.chkExternalEventId, self.edtExternalEventId)
        JobsOperatingDialog.setTabOrder(self.edtExternalEventId, self.tblJobTypes)
        JobsOperatingDialog.setTabOrder(self.tblJobTypes, self.chkJobTicketId)
        JobsOperatingDialog.setTabOrder(self.chkJobTicketId, self.cmbTissueType)
        JobsOperatingDialog.setTabOrder(self.cmbTissueType, self.cmbTakenTissueType)
        JobsOperatingDialog.setTabOrder(self.cmbTakenTissueType, self.cmbJobPurpose)
        JobsOperatingDialog.setTabOrder(self.cmbJobPurpose, self.chkAwaiting)
        JobsOperatingDialog.setTabOrder(self.chkAwaiting, self.chkEnueued)
        JobsOperatingDialog.setTabOrder(self.chkEnueued, self.chkInProgress)
        JobsOperatingDialog.setTabOrder(self.chkInProgress, self.chkDone)
        JobsOperatingDialog.setTabOrder(self.chkDone, self.chkOnlyUrgent)
        JobsOperatingDialog.setTabOrder(self.chkOnlyUrgent, self.chkHideDoneActions)
        JobsOperatingDialog.setTabOrder(self.chkHideDoneActions, self.cmbOrgStructure)
        JobsOperatingDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        JobsOperatingDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        JobsOperatingDialog.setTabOrder(self.cmbPerson, self.cmbSex)
        JobsOperatingDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        JobsOperatingDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        JobsOperatingDialog.setTabOrder(self.edtAgeTo, self.buttonBoxFilter)
        JobsOperatingDialog.setTabOrder(self.buttonBoxFilter, self.tblJobTickets)
        JobsOperatingDialog.setTabOrder(self.tblJobTickets, self.tblJobTicketActions)
        JobsOperatingDialog.setTabOrder(self.tblJobTicketActions, self.buttonBox)

    def retranslateUi(self, JobsOperatingDialog):
        JobsOperatingDialog.setWindowTitle(_translate("JobsOperatingDialog", "Выполнение работ", None))
        self.lblDateRangeFrom.setText(_translate("JobsOperatingDialog", "С", None))
        self.lblDateRangeTo.setText(_translate("JobsOperatingDialog", "По", None))
        self.cmbDateType.setItemText(0, _translate("JobsOperatingDialog", "Плановая дата", None))
        self.cmbDateType.setItemText(1, _translate("JobsOperatingDialog", "Дата начала", None))
        self.cmbDateType.setItemText(2, _translate("JobsOperatingDialog", "Дата окончания", None))
        self.tabDateClientFilter.setTabText(self.tabDateClientFilter.indexOf(self.tabDateFilter), _translate("JobsOperatingDialog", "&Дата", None))
        self.chkClientId.setText(_translate("JobsOperatingDialog", "Код", None))
        self.chkClientLastName.setText(_translate("JobsOperatingDialog", "Фамилия", None))
        self.chkClientFirstName.setText(_translate("JobsOperatingDialog", "Имя", None))
        self.chkClientPatrName.setText(_translate("JobsOperatingDialog", "Отчество", None))
        self.chkExternalEventId.setText(_translate("JobsOperatingDialog", "Карта", None))
        self.chkClientBirthDate.setText(_translate("JobsOperatingDialog", "Дата рождения", None))
        self.edtClientBirthDate.setDisplayFormat(_translate("JobsOperatingDialog", "dd.MM.yyyy", None))
        self.tabDateClientFilter.setTabText(self.tabDateClientFilter.indexOf(self.tabClientFilter), _translate("JobsOperatingDialog", "&Пациент", None))
        self.cmbOrgStructureType.setItemText(0, _translate("JobsOperatingDialog", "Структура ЛПУ: фильтр по назначившему", None))
        self.cmbOrgStructureType.setItemText(1, _translate("JobsOperatingDialog", "Структура ЛПУ: фильтр по исполнителю", None))
        self.cmbOrgStructureType.setItemText(2, _translate("JobsOperatingDialog", "Структура ЛПУ: по месту пребывания в стационаре", None))
        self.label_2.setText(_translate("JobsOperatingDialog", "Выбор сканера     ", None))
        self.cmbOnScanSelect.setItemText(0, _translate("JobsOperatingDialog", "для Направления", None))
        self.cmbOnScanSelect.setItemText(1, _translate("JobsOperatingDialog", "для Биоматериала", None))
        self.cmbOnScanSelect.setItemText(2, _translate("JobsOperatingDialog", "для Пробы", None))
        self.cmbOnScan.setItemText(0, _translate("JobsOperatingDialog", "Выполнить поиск направления", None))
        self.cmbOnScan.setItemText(1, _translate("JobsOperatingDialog", "Открыть редактор направления", None))
        self.cmbOnScan.setItemText(2, _translate("JobsOperatingDialog", "Открыть редактор проб", None))
        self.lblOnScan.setText(_translate("JobsOperatingDialog", "при сканировании", None))
        self.grpStaticFilter.setTitle(_translate("JobsOperatingDialog", "Фильтр", None))
        self.lblAge.setText(_translate("JobsOperatingDialog", "Во&зраст с", None))
        self.cmbPerson.setItemText(0, _translate("JobsOperatingDialog", "Врач", None))
        self.chkAwaiting.setText(_translate("JobsOperatingDialog", "&Ожидающие", None))
        self.lblOrgStructure.setText(_translate("JobsOperatingDialog", "&Подразделение", None))
        self.lblPerson.setText(_translate("JobsOperatingDialog", "&Врач", None))
        self.chkEnueued.setText(_translate("JobsOperatingDialog", "В очереди", None))
        self.lblSpeciality.setText(_translate("JobsOperatingDialog", "&Специальность", None))
        self.lblSex.setText(_translate("JobsOperatingDialog", "По&л", None))
        self.chkInProgress.setText(_translate("JobsOperatingDialog", "&Выполняемые", None))
        self.lblTissueType.setText(_translate("JobsOperatingDialog", "Биоматериал", None))
        self.chkOnlyUrgent.setText(_translate("JobsOperatingDialog", "Только &срочные", None))
        self.chkDone.setText(_translate("JobsOperatingDialog", "&Законченные", None))
        self.cmbSex.setItemText(1, _translate("JobsOperatingDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("JobsOperatingDialog", "Ж", None))
        self.chkJobTicketId.setText(_translate("JobsOperatingDialog", "Идентификатор", None))
        self.cmbSpeciality.setWhatsThis(_translate("JobsOperatingDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblJobPurpose.setText(_translate("JobsOperatingDialog", "Назначение работ", None))
        self.lblTakenTissueType.setText(_translate("JobsOperatingDialog", "Забранный биоматериал", None))
        self.chkExpired.setToolTip(_translate("JobsOperatingDialog", "Действия со статусами: начато, назначено и без результата", None))
        self.chkExpired.setText(_translate("JobsOperatingDialog", "Просроченные", None))
        self.chkHideDoneActions.setToolTip(_translate("JobsOperatingDialog", "Действия со статусами: начато, назначено и без результата", None))
        self.chkHideDoneActions.setText(_translate("JobsOperatingDialog", "Cкрыть выполненные", None))
        self.lblAgeTo.setText(_translate("JobsOperatingDialog", "по", None))
        self.lblAgeYears.setText(_translate("JobsOperatingDialog", "лет", None))
        self.cmbScanBarcode.setItemText(0, _translate("JobsOperatingDialog", "Направление", None))
        self.cmbScanBarcode.setItemText(1, _translate("JobsOperatingDialog", "Биоматериал", None))
        self.cmbScanBarcode.setItemText(2, _translate("JobsOperatingDialog", "Проба", None))
        self.lblTicketsCount.setText(_translate("JobsOperatingDialog", "Список пуст", None))
        self.lblActionsCount.setText(_translate("JobsOperatingDialog", "Список пуст", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.CalendarWidget import CCalendarWidget
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
