# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Resources\TemplateDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ResourceTemplateDialog(object):
    def setupUi(self, ResourceTemplateDialog):
        ResourceTemplateDialog.setObjectName(_fromUtf8("ResourceTemplateDialog"))
        ResourceTemplateDialog.resize(277, 273)
        self.gridLayout = QtGui.QGridLayout(ResourceTemplateDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dateRangeLayout = QtGui.QHBoxLayout()
        self.dateRangeLayout.setSpacing(4)
        self.dateRangeLayout.setObjectName(_fromUtf8("dateRangeLayout"))
        self.lblBegDate = QtGui.QLabel(ResourceTemplateDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.dateRangeLayout.addWidget(self.lblBegDate)
        self.edtBegDate = CDateEdit(ResourceTemplateDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.dateRangeLayout.addWidget(self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(ResourceTemplateDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.dateRangeLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(ResourceTemplateDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.dateRangeLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dateRangeLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.dateRangeLayout, 0, 0, 1, 3)
        self.lblAmbHours = QtGui.QLabel(ResourceTemplateDialog)
        self.lblAmbHours.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbHours.setObjectName(_fromUtf8("lblAmbHours"))
        self.gridLayout.addWidget(self.lblAmbHours, 1, 1, 1, 1)
        self.lblAmbPlan = QtGui.QLabel(ResourceTemplateDialog)
        self.lblAmbPlan.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmbPlan.setObjectName(_fromUtf8("lblAmbPlan"))
        self.gridLayout.addWidget(self.lblAmbPlan, 1, 2, 1, 1)
        self.rbSingle = QtGui.QRadioButton(ResourceTemplateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbSingle.sizePolicy().hasHeightForWidth())
        self.rbSingle.setSizePolicy(sizePolicy)
        self.rbSingle.setChecked(True)
        self.rbSingle.setObjectName(_fromUtf8("rbSingle"))
        self.gridLayout.addWidget(self.rbSingle, 2, 0, 1, 1)
        self.edtTimeRange1 = CTimeRangeEdit(ResourceTemplateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange1.sizePolicy().hasHeightForWidth())
        self.edtTimeRange1.setSizePolicy(sizePolicy)
        self.edtTimeRange1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange1.setMaxLength(13)
        self.edtTimeRange1.setObjectName(_fromUtf8("edtTimeRange1"))
        self.gridLayout.addWidget(self.edtTimeRange1, 2, 1, 1, 1)
        self.edtQuantity1 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity1.setMaximum(999999999)
        self.edtQuantity1.setObjectName(_fromUtf8("edtQuantity1"))
        self.gridLayout.addWidget(self.edtQuantity1, 2, 2, 1, 1)
        self.rbDual = QtGui.QRadioButton(ResourceTemplateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbDual.sizePolicy().hasHeightForWidth())
        self.rbDual.setSizePolicy(sizePolicy)
        self.rbDual.setChecked(False)
        self.rbDual.setObjectName(_fromUtf8("rbDual"))
        self.gridLayout.addWidget(self.rbDual, 3, 0, 1, 1)
        self.edtTimeRange2 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange2.sizePolicy().hasHeightForWidth())
        self.edtTimeRange2.setSizePolicy(sizePolicy)
        self.edtTimeRange2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange2.setMaxLength(13)
        self.edtTimeRange2.setObjectName(_fromUtf8("edtTimeRange2"))
        self.gridLayout.addWidget(self.edtTimeRange2, 3, 1, 1, 1)
        self.edtQuantity2 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity2.setEnabled(False)
        self.edtQuantity2.setMaximum(999999999)
        self.edtQuantity2.setObjectName(_fromUtf8("edtQuantity2"))
        self.gridLayout.addWidget(self.edtQuantity2, 3, 2, 1, 1)
        self.rbWeek = QtGui.QRadioButton(ResourceTemplateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbWeek.sizePolicy().hasHeightForWidth())
        self.rbWeek.setSizePolicy(sizePolicy)
        self.rbWeek.setChecked(False)
        self.rbWeek.setObjectName(_fromUtf8("rbWeek"))
        self.gridLayout.addWidget(self.rbWeek, 4, 0, 1, 1)
        self.edtTimeRange3 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange3.sizePolicy().hasHeightForWidth())
        self.edtTimeRange3.setSizePolicy(sizePolicy)
        self.edtTimeRange3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange3.setMaxLength(13)
        self.edtTimeRange3.setObjectName(_fromUtf8("edtTimeRange3"))
        self.gridLayout.addWidget(self.edtTimeRange3, 4, 1, 1, 1)
        self.edtQuantity3 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity3.setEnabled(False)
        self.edtQuantity3.setMaximum(999999999)
        self.edtQuantity3.setObjectName(_fromUtf8("edtQuantity3"))
        self.gridLayout.addWidget(self.edtQuantity3, 4, 2, 1, 1)
        self.edtTimeRange4 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange4.sizePolicy().hasHeightForWidth())
        self.edtTimeRange4.setSizePolicy(sizePolicy)
        self.edtTimeRange4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange4.setMaxLength(13)
        self.edtTimeRange4.setObjectName(_fromUtf8("edtTimeRange4"))
        self.gridLayout.addWidget(self.edtTimeRange4, 5, 1, 1, 1)
        self.edtQuantity4 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity4.setEnabled(False)
        self.edtQuantity4.setMaximum(999999999)
        self.edtQuantity4.setObjectName(_fromUtf8("edtQuantity4"))
        self.gridLayout.addWidget(self.edtQuantity4, 5, 2, 1, 1)
        self.edtTimeRange5 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange5.sizePolicy().hasHeightForWidth())
        self.edtTimeRange5.setSizePolicy(sizePolicy)
        self.edtTimeRange5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange5.setMaxLength(13)
        self.edtTimeRange5.setObjectName(_fromUtf8("edtTimeRange5"))
        self.gridLayout.addWidget(self.edtTimeRange5, 6, 1, 1, 1)
        self.edtQuantity5 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity5.setEnabled(False)
        self.edtQuantity5.setMaximum(999999999)
        self.edtQuantity5.setObjectName(_fromUtf8("edtQuantity5"))
        self.gridLayout.addWidget(self.edtQuantity5, 6, 2, 1, 1)
        self.edtTimeRange6 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange6.sizePolicy().hasHeightForWidth())
        self.edtTimeRange6.setSizePolicy(sizePolicy)
        self.edtTimeRange6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange6.setMaxLength(13)
        self.edtTimeRange6.setObjectName(_fromUtf8("edtTimeRange6"))
        self.gridLayout.addWidget(self.edtTimeRange6, 7, 1, 1, 1)
        self.edtQuantity6 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity6.setEnabled(False)
        self.edtQuantity6.setMaximum(999999999)
        self.edtQuantity6.setObjectName(_fromUtf8("edtQuantity6"))
        self.gridLayout.addWidget(self.edtQuantity6, 7, 2, 1, 1)
        self.edtTimeRange7 = CTimeRangeEdit(ResourceTemplateDialog)
        self.edtTimeRange7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTimeRange7.sizePolicy().hasHeightForWidth())
        self.edtTimeRange7.setSizePolicy(sizePolicy)
        self.edtTimeRange7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtTimeRange7.setMaxLength(13)
        self.edtTimeRange7.setObjectName(_fromUtf8("edtTimeRange7"))
        self.gridLayout.addWidget(self.edtTimeRange7, 8, 1, 1, 1)
        self.edtQuantity7 = QtGui.QSpinBox(ResourceTemplateDialog)
        self.edtQuantity7.setEnabled(False)
        self.edtQuantity7.setMaximum(999999999)
        self.edtQuantity7.setObjectName(_fromUtf8("edtQuantity7"))
        self.gridLayout.addWidget(self.edtQuantity7, 8, 2, 1, 1)
        self.chkFillRedDays = QtGui.QCheckBox(ResourceTemplateDialog)
        self.chkFillRedDays.setObjectName(_fromUtf8("chkFillRedDays"))
        self.gridLayout.addWidget(self.chkFillRedDays, 9, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 161, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ResourceTemplateDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 3)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblAmbHours.setBuddy(self.edtTimeRange1)
        self.lblAmbPlan.setBuddy(self.edtQuantity1)

        self.retranslateUi(ResourceTemplateDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ResourceTemplateDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ResourceTemplateDialog.reject)
        QtCore.QObject.connect(self.rbSingle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange2.setDisabled)
        QtCore.QObject.connect(self.rbSingle, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity2.setDisabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange3.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange4.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange5.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity3.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity4.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity5.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange6.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity6.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTimeRange7.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtQuantity7.setEnabled)
        QtCore.QObject.connect(self.rbWeek, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFillRedDays.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ResourceTemplateDialog)
        ResourceTemplateDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ResourceTemplateDialog.setTabOrder(self.edtEndDate, self.rbSingle)
        ResourceTemplateDialog.setTabOrder(self.rbSingle, self.rbDual)
        ResourceTemplateDialog.setTabOrder(self.rbDual, self.rbWeek)
        ResourceTemplateDialog.setTabOrder(self.rbWeek, self.edtTimeRange1)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange1, self.edtQuantity1)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity1, self.edtTimeRange2)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange2, self.edtQuantity2)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity2, self.edtTimeRange3)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange3, self.edtQuantity3)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity3, self.edtTimeRange4)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange4, self.edtQuantity4)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity4, self.edtTimeRange5)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange5, self.edtQuantity5)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity5, self.edtTimeRange6)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange6, self.edtQuantity6)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity6, self.edtTimeRange7)
        ResourceTemplateDialog.setTabOrder(self.edtTimeRange7, self.edtQuantity7)
        ResourceTemplateDialog.setTabOrder(self.edtQuantity7, self.chkFillRedDays)
        ResourceTemplateDialog.setTabOrder(self.chkFillRedDays, self.buttonBox)

    def retranslateUi(self, ResourceTemplateDialog):
        ResourceTemplateDialog.setWindowTitle(_translate("ResourceTemplateDialog", "Шаблон планировщика", None))
        self.lblBegDate.setText(_translate("ResourceTemplateDialog", "В период &с", None))
        self.lblEndDate.setText(_translate("ResourceTemplateDialog", "&По", None))
        self.lblAmbHours.setText(_translate("ResourceTemplateDialog", "Часы", None))
        self.lblAmbPlan.setText(_translate("ResourceTemplateDialog", "План", None))
        self.rbSingle.setText(_translate("ResourceTemplateDialog", "&Один план", None))
        self.rbDual.setText(_translate("ResourceTemplateDialog", "&Нечет/чёт", None))
        self.rbWeek.setText(_translate("ResourceTemplateDialog", "Не&деля", None))
        self.chkFillRedDays.setText(_translate("ResourceTemplateDialog", "&Заполнять выходные дни", None))

from library.DateEdit import CDateEdit
from library.TimeEdit import CTimeRangeEdit
