# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/preferences/CalendarExceptionDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CalendarExceptionDialog(object):
    def setupUi(self, CalendarExceptionDialog):
        CalendarExceptionDialog.setObjectName(_fromUtf8("CalendarExceptionDialog"))
        CalendarExceptionDialog.resize(372, 175)
        CalendarExceptionDialog.setSizeGripEnabled(True)
        CalendarExceptionDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(CalendarExceptionDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtEndYear = QtGui.QSpinBox(CalendarExceptionDialog)
        self.edtEndYear.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndYear.sizePolicy().hasHeightForWidth())
        self.edtEndYear.setSizePolicy(sizePolicy)
        self.edtEndYear.setMinimum(1)
        self.edtEndYear.setMaximum(9999)
        self.edtEndYear.setProperty("value", 9999)
        self.edtEndYear.setObjectName(_fromUtf8("edtEndYear"))
        self.gridLayout.addWidget(self.edtEndYear, 1, 3, 1, 1)
        self.lblDay = QtGui.QLabel(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDay.sizePolicy().hasHeightForWidth())
        self.lblDay.setSizePolicy(sizePolicy)
        self.lblDay.setObjectName(_fromUtf8("lblDay"))
        self.gridLayout.addWidget(self.lblDay, 3, 0, 1, 1)
        self.lblYear = QtGui.QLabel(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblYear.sizePolicy().hasHeightForWidth())
        self.lblYear.setSizePolicy(sizePolicy)
        self.lblYear.setObjectName(_fromUtf8("lblYear"))
        self.gridLayout.addWidget(self.lblYear, 1, 0, 1, 1)
        self.edtBegYear = QtGui.QSpinBox(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegYear.sizePolicy().hasHeightForWidth())
        self.edtBegYear.setSizePolicy(sizePolicy)
        self.edtBegYear.setMinimum(1)
        self.edtBegYear.setMaximum(9999)
        self.edtBegYear.setObjectName(_fromUtf8("edtBegYear"))
        self.gridLayout.addWidget(self.edtBegYear, 1, 1, 1, 1)
        self.lblDow = QtGui.QLabel(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDow.sizePolicy().hasHeightForWidth())
        self.lblDow.setSizePolicy(sizePolicy)
        self.lblDow.setObjectName(_fromUtf8("lblDow"))
        self.gridLayout.addWidget(self.lblDow, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.chkEndYearDiffer = QtGui.QCheckBox(CalendarExceptionDialog)
        self.chkEndYearDiffer.setObjectName(_fromUtf8("chkEndYearDiffer"))
        self.gridLayout.addWidget(self.chkEndYearDiffer, 1, 2, 1, 1)
        self.lblName = QtGui.QLabel(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.edtDay = QtGui.QSpinBox(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDay.sizePolicy().hasHeightForWidth())
        self.edtDay.setSizePolicy(sizePolicy)
        self.edtDay.setMinimum(1)
        self.edtDay.setMaximum(31)
        self.edtDay.setObjectName(_fromUtf8("edtDay"))
        self.gridLayout.addWidget(self.edtDay, 3, 1, 1, 1)
        self.lblMonth = QtGui.QLabel(CalendarExceptionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMonth.sizePolicy().hasHeightForWidth())
        self.lblMonth.setSizePolicy(sizePolicy)
        self.lblMonth.setObjectName(_fromUtf8("lblMonth"))
        self.gridLayout.addWidget(self.lblMonth, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.edtName = QtGui.QLineEdit(CalendarExceptionDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 0, 1, 1, 4)
        self.cmbMonth = QtGui.QComboBox(CalendarExceptionDialog)
        self.cmbMonth.setObjectName(_fromUtf8("cmbMonth"))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMonth, 2, 1, 1, 4)
        self.cmbDow = QtGui.QComboBox(CalendarExceptionDialog)
        self.cmbDow.setObjectName(_fromUtf8("cmbDow"))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.cmbDow.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDow, 4, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(CalendarExceptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 5)
        self.lblDay.setBuddy(self.edtDay)
        self.lblYear.setBuddy(self.edtBegYear)
        self.lblDow.setBuddy(self.cmbDow)
        self.lblName.setBuddy(self.edtName)
        self.lblMonth.setBuddy(self.cmbMonth)

        self.retranslateUi(CalendarExceptionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CalendarExceptionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CalendarExceptionDialog.reject)
        QtCore.QObject.connect(self.chkEndYearDiffer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndYear.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CalendarExceptionDialog)
        CalendarExceptionDialog.setTabOrder(self.edtName, self.edtBegYear)
        CalendarExceptionDialog.setTabOrder(self.edtBegYear, self.chkEndYearDiffer)
        CalendarExceptionDialog.setTabOrder(self.chkEndYearDiffer, self.edtEndYear)
        CalendarExceptionDialog.setTabOrder(self.edtEndYear, self.cmbMonth)
        CalendarExceptionDialog.setTabOrder(self.cmbMonth, self.edtDay)
        CalendarExceptionDialog.setTabOrder(self.edtDay, self.cmbDow)
        CalendarExceptionDialog.setTabOrder(self.cmbDow, self.buttonBox)

    def retranslateUi(self, CalendarExceptionDialog):
        CalendarExceptionDialog.setWindowTitle(_translate("CalendarExceptionDialog", "Dialog", None))
        self.lblDay.setText(_translate("CalendarExceptionDialog", "&День", None))
        self.lblYear.setText(_translate("CalendarExceptionDialog", "&Год с ", None))
        self.lblDow.setText(_translate("CalendarExceptionDialog", "&Числить как", None))
        self.chkEndYearDiffer.setText(_translate("CalendarExceptionDialog", "по", None))
        self.lblName.setText(_translate("CalendarExceptionDialog", "&Наименование", None))
        self.lblMonth.setText(_translate("CalendarExceptionDialog", "&Месяц", None))
        self.cmbMonth.setItemText(0, _translate("CalendarExceptionDialog", "Январь", None))
        self.cmbMonth.setItemText(1, _translate("CalendarExceptionDialog", "Февраль", None))
        self.cmbMonth.setItemText(2, _translate("CalendarExceptionDialog", "Март", None))
        self.cmbMonth.setItemText(3, _translate("CalendarExceptionDialog", "Апрель", None))
        self.cmbMonth.setItemText(4, _translate("CalendarExceptionDialog", "Май", None))
        self.cmbMonth.setItemText(5, _translate("CalendarExceptionDialog", "Июнь", None))
        self.cmbMonth.setItemText(6, _translate("CalendarExceptionDialog", "Июль", None))
        self.cmbMonth.setItemText(7, _translate("CalendarExceptionDialog", "Август", None))
        self.cmbMonth.setItemText(8, _translate("CalendarExceptionDialog", "Сентябрь", None))
        self.cmbMonth.setItemText(9, _translate("CalendarExceptionDialog", "Октябрь", None))
        self.cmbMonth.setItemText(10, _translate("CalendarExceptionDialog", "Ноябрь", None))
        self.cmbMonth.setItemText(11, _translate("CalendarExceptionDialog", "Декабрь", None))
        self.cmbDow.setItemText(0, _translate("CalendarExceptionDialog", "Понедельник", None))
        self.cmbDow.setItemText(1, _translate("CalendarExceptionDialog", "Вторник", None))
        self.cmbDow.setItemText(2, _translate("CalendarExceptionDialog", "Среда", None))
        self.cmbDow.setItemText(3, _translate("CalendarExceptionDialog", "Четверг", None))
        self.cmbDow.setItemText(4, _translate("CalendarExceptionDialog", "Пятница", None))
        self.cmbDow.setItemText(5, _translate("CalendarExceptionDialog", "Суббота", None))
        self.cmbDow.setItemText(6, _translate("CalendarExceptionDialog", "Воскресенье", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CalendarExceptionDialog = QtGui.QDialog()
    ui = Ui_CalendarExceptionDialog()
    ui.setupUi(CalendarExceptionDialog)
    CalendarExceptionDialog.show()
    sys.exit(app.exec_())

