# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/preferences/connection.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_connectionDialog(object):
    def setupUi(self, connectionDialog):
        connectionDialog.setObjectName(_fromUtf8("connectionDialog"))
        connectionDialog.resize(185, 257)
        connectionDialog.setSizeGripEnabled(False)
        self.gridlayout = QtGui.QGridLayout(connectionDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.groupBox = QtGui.QGroupBox(connectionDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setMargin(4)
        self.gridlayout1.setSpacing(4)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.edtPassword = QtGui.QLineEdit(self.groupBox)
        self.edtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.edtPassword.setObjectName(_fromUtf8("edtPassword"))
        self.gridlayout1.addWidget(self.edtPassword, 1, 1, 1, 1)
        self.edtUserName = QtGui.QLineEdit(self.groupBox)
        self.edtUserName.setObjectName(_fromUtf8("edtUserName"))
        self.gridlayout1.addWidget(self.edtUserName, 0, 1, 1, 1)
        self.lblPassword = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPassword.sizePolicy().hasHeightForWidth())
        self.lblPassword.setSizePolicy(sizePolicy)
        self.lblPassword.setMinimumSize(QtCore.QSize(40, 0))
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.gridlayout1.addWidget(self.lblPassword, 1, 0, 1, 1)
        self.lblUserName = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUserName.sizePolicy().hasHeightForWidth())
        self.lblUserName.setSizePolicy(sizePolicy)
        self.lblUserName.setMinimumSize(QtCore.QSize(40, 0))
        self.lblUserName.setObjectName(_fromUtf8("lblUserName"))
        self.gridlayout1.addWidget(self.lblUserName, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.grpServer = QtGui.QGroupBox(connectionDialog)
        self.grpServer.setObjectName(_fromUtf8("grpServer"))
        self.gridlayout2 = QtGui.QGridLayout(self.grpServer)
        self.gridlayout2.setMargin(4)
        self.gridlayout2.setSpacing(4)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.lblDriverName = QtGui.QLabel(self.grpServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDriverName.sizePolicy().hasHeightForWidth())
        self.lblDriverName.setSizePolicy(sizePolicy)
        self.lblDriverName.setMinimumSize(QtCore.QSize(40, 0))
        self.lblDriverName.setObjectName(_fromUtf8("lblDriverName"))
        self.gridlayout2.addWidget(self.lblDriverName, 0, 0, 1, 1)
        self.edtServerPort = QtGui.QSpinBox(self.grpServer)
        self.edtServerPort.setMaximum(99999)
        self.edtServerPort.setObjectName(_fromUtf8("edtServerPort"))
        self.gridlayout2.addWidget(self.edtServerPort, 2, 1, 1, 1)
        self.lblServerName = QtGui.QLabel(self.grpServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServerName.sizePolicy().hasHeightForWidth())
        self.lblServerName.setSizePolicy(sizePolicy)
        self.lblServerName.setMinimumSize(QtCore.QSize(40, 0))
        self.lblServerName.setObjectName(_fromUtf8("lblServerName"))
        self.gridlayout2.addWidget(self.lblServerName, 1, 0, 1, 1)
        self.cmbDriverName = QtGui.QComboBox(self.grpServer)
        self.cmbDriverName.setObjectName(_fromUtf8("cmbDriverName"))
        self.cmbDriverName.addItem(_fromUtf8(""))
        self.cmbDriverName.addItem(_fromUtf8(""))
        self.gridlayout2.addWidget(self.cmbDriverName, 0, 1, 1, 1)
        self.lblServerPort = QtGui.QLabel(self.grpServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServerPort.sizePolicy().hasHeightForWidth())
        self.lblServerPort.setSizePolicy(sizePolicy)
        self.lblServerPort.setMinimumSize(QtCore.QSize(40, 0))
        self.lblServerPort.setObjectName(_fromUtf8("lblServerPort"))
        self.gridlayout2.addWidget(self.lblServerPort, 2, 0, 1, 1)
        self.edtServerName = QtGui.QLineEdit(self.grpServer)
        self.edtServerName.setObjectName(_fromUtf8("edtServerName"))
        self.gridlayout2.addWidget(self.edtServerName, 1, 1, 1, 1)
        self.edtDatabaseName = QtGui.QLineEdit(self.grpServer)
        self.edtDatabaseName.setObjectName(_fromUtf8("edtDatabaseName"))
        self.gridlayout2.addWidget(self.edtDatabaseName, 3, 1, 1, 1)
        self.lblDatabaseName = QtGui.QLabel(self.grpServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatabaseName.sizePolicy().hasHeightForWidth())
        self.lblDatabaseName.setSizePolicy(sizePolicy)
        self.lblDatabaseName.setMinimumSize(QtCore.QSize(40, 0))
        self.lblDatabaseName.setObjectName(_fromUtf8("lblDatabaseName"))
        self.gridlayout2.addWidget(self.lblDatabaseName, 3, 0, 1, 1)
        self.chkCompressData = QtGui.QCheckBox(self.grpServer)
        self.chkCompressData.setToolTip(_fromUtf8(""))
        self.chkCompressData.setObjectName(_fromUtf8("chkCompressData"))
        self.gridlayout2.addWidget(self.chkCompressData, 4, 1, 1, 1)
        self.gridlayout.addWidget(self.grpServer, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(connectionDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 2, 0, 1, 1)
        self.lblPassword.setBuddy(self.edtPassword)
        self.lblUserName.setBuddy(self.edtUserName)
        self.lblDriverName.setBuddy(self.cmbDriverName)
        self.lblServerName.setBuddy(self.edtServerName)
        self.lblServerPort.setBuddy(self.edtServerPort)
        self.lblDatabaseName.setBuddy(self.edtDatabaseName)

        self.retranslateUi(connectionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), connectionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), connectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(connectionDialog)
        connectionDialog.setTabOrder(self.cmbDriverName, self.edtServerName)
        connectionDialog.setTabOrder(self.edtServerName, self.edtServerPort)
        connectionDialog.setTabOrder(self.edtServerPort, self.edtDatabaseName)
        connectionDialog.setTabOrder(self.edtDatabaseName, self.chkCompressData)
        connectionDialog.setTabOrder(self.chkCompressData, self.edtUserName)
        connectionDialog.setTabOrder(self.edtUserName, self.edtPassword)

    def retranslateUi(self, connectionDialog):
        connectionDialog.setWindowTitle(_translate("connectionDialog", "Настройки базы данных", None))
        self.groupBox.setTitle(_translate("connectionDialog", "Пользователь", None))
        self.lblPassword.setText(_translate("connectionDialog", "&Пароль", None))
        self.lblUserName.setText(_translate("connectionDialog", "&Имя", None))
        self.grpServer.setTitle(_translate("connectionDialog", "Сервер", None))
        self.lblDriverName.setText(_translate("connectionDialog", "&Тип", None))
        self.lblServerName.setText(_translate("connectionDialog", "&Адрес ", None))
        self.cmbDriverName.setItemText(0, _translate("connectionDialog", "MySQL", None))
        self.cmbDriverName.setItemText(1, _translate("connectionDialog", "PostgreSQL", None))
        self.lblServerPort.setText(_translate("connectionDialog", "&Порт", None))
        self.edtServerName.setText(_translate("connectionDialog", "localhost", None))
        self.lblDatabaseName.setText(_translate("connectionDialog", "&База", None))
        self.chkCompressData.setText(_translate("connectionDialog", "Сжимать данные", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    connectionDialog = QtGui.QDialog()
    ui = Ui_connectionDialog()
    ui.setupUi(connectionDialog)
    connectionDialog.show()
    sys.exit(app.exec_())

