# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Quoting\ClientQuotingComboBoxPopup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(473, 300)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabQuoting = QtGui.QWidget()
        self.tabQuoting.setObjectName(_fromUtf8("tabQuoting"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabQuoting)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblClientQuoting = CTableView(self.tabQuoting)
        self.tblClientQuoting.setObjectName(_fromUtf8("tblClientQuoting"))
        self.gridLayout_2.addWidget(self.tblClientQuoting, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabQuoting, _fromUtf8(""))
        self.tabFind = QtGui.QWidget()
        self.tabFind.setObjectName(_fromUtf8("tabFind"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabFind)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pnlDates = QtGui.QWidget(self.tabFind)
        self.pnlDates.setObjectName(_fromUtf8("pnlDates"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlDates)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkBegDate = QtGui.QCheckBox(self.pnlDates)
        self.chkBegDate.setObjectName(_fromUtf8("chkBegDate"))
        self.horizontalLayout.addWidget(self.chkBegDate)
        self.edtBegDate = CDateEdit(self.pnlDates)
        self.edtBegDate.setEnabled(False)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout.addWidget(self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(self.pnlDates)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.horizontalLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(self.pnlDates)
        self.edtEndDate.setEnabled(False)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.pnlDates, 1, 0, 1, 2)
        self.chkStatus = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkStatus.sizePolicy().hasHeightForWidth())
        self.chkStatus.setSizePolicy(sizePolicy)
        self.chkStatus.setObjectName(_fromUtf8("chkStatus"))
        self.gridLayout_3.addWidget(self.chkStatus, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 2)
        self.cmbStatus = QtGui.QComboBox(self.tabFind)
        self.cmbStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStatus.sizePolicy().hasHeightForWidth())
        self.cmbStatus.setSizePolicy(sizePolicy)
        self.cmbStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbStatus, 3, 1, 1, 1)
        self.pnlButtonBox = QtGui.QWidget(self.tabFind)
        self.pnlButtonBox.setObjectName(_fromUtf8("pnlButtonBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pnlButtonBox)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(273, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(self.pnlButtonBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_3.addWidget(self.pnlButtonBox, 6, 0, 1, 2)
        self.chkClass = QtGui.QCheckBox(self.tabFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClass.sizePolicy().hasHeightForWidth())
        self.chkClass.setSizePolicy(sizePolicy)
        self.chkClass.setChecked(True)
        self.chkClass.setObjectName(_fromUtf8("chkClass"))
        self.gridLayout_3.addWidget(self.chkClass, 0, 0, 1, 1)
        self.cmbClass = QtGui.QComboBox(self.tabFind)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout_3.addWidget(self.cmbClass, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabFind, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.chkClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbClass.setEnabled)
        QtCore.QObject.connect(self.chkStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbStatus.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDate.setEnabled)
        QtCore.QObject.connect(self.chkBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tblClientQuoting, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.chkClass)
        Form.setTabOrder(self.chkClass, self.cmbClass)
        Form.setTabOrder(self.cmbClass, self.chkBegDate)
        Form.setTabOrder(self.chkBegDate, self.edtBegDate)
        Form.setTabOrder(self.edtBegDate, self.edtEndDate)
        Form.setTabOrder(self.edtEndDate, self.chkStatus)
        Form.setTabOrder(self.chkStatus, self.cmbStatus)
        Form.setTabOrder(self.cmbStatus, self.buttonBox)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabQuoting), _translate("Form", "&Квоты", None))
        self.chkBegDate.setText(_translate("Form", "Период действия с: ", None))
        self.lblEndDate.setText(_translate("Form", "по: ", None))
        self.chkStatus.setText(_translate("Form", "Статус", None))
        self.cmbStatus.setItemText(0, _translate("Form", "Отменено", None))
        self.cmbStatus.setItemText(1, _translate("Form", "Ожидание", None))
        self.cmbStatus.setItemText(2, _translate("Form", "Активный талон", None))
        self.cmbStatus.setItemText(3, _translate("Form", "Талон для заполнения", None))
        self.cmbStatus.setItemText(4, _translate("Form", "Заблокированный талон", None))
        self.cmbStatus.setItemText(5, _translate("Form", "Отказано", None))
        self.cmbStatus.setItemText(6, _translate("Form", "Необходимо согласовать дату обслуживания", None))
        self.cmbStatus.setItemText(7, _translate("Form", "Дата обслуживания на согласовании", None))
        self.cmbStatus.setItemText(8, _translate("Form", "Дата обслуживания согласована", None))
        self.cmbStatus.setItemText(9, _translate("Form", "Пролечен", None))
        self.cmbStatus.setItemText(10, _translate("Form", "Обслуживание отложено", None))
        self.cmbStatus.setItemText(11, _translate("Form", "Отказ пациента", None))
        self.cmbStatus.setItemText(12, _translate("Form", "Импортировано из ВТМП", None))
        self.chkClass.setText(_translate("Form", "Класс", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFind), _translate("Form", "&Поиск", None))

from library.DateEdit import CDateEdit
from library.TableView import CTableView
