# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client_eln\appendix\fsselnv2\app\WorkSpace.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CWorkSpace(object):
    def setupUi(self, CWorkSpace):
        CWorkSpace.setObjectName(_fromUtf8("CWorkSpace"))
        CWorkSpace.resize(558, 587)
        self.gridLayout = QtGui.QGridLayout(CWorkSpace)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabMain = QtGui.QTabWidget(CWorkSpace)
        self.tabMain.setDocumentMode(False)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabNumbersRegistry = QtGui.QWidget()
        self.tabNumbersRegistry.setObjectName(_fromUtf8("tabNumbersRegistry"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabNumbersRegistry)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblNumbersRegistry = CTableView(self.tabNumbersRegistry)
        self.tblNumbersRegistry.setObjectName(_fromUtf8("tblNumbersRegistry"))
        self.gridLayout_5.addWidget(self.tblNumbersRegistry, 1, 0, 1, 2)
        self.btnRequestNumbers = QtGui.QPushButton(self.tabNumbersRegistry)
        self.btnRequestNumbers.setObjectName(_fromUtf8("btnRequestNumbers"))
        self.gridLayout_5.addWidget(self.btnRequestNumbers, 3, 0, 1, 2)
        self.lblSizeOfNumbersRegistry = QtGui.QLabel(self.tabNumbersRegistry)
        self.lblSizeOfNumbersRegistry.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSizeOfNumbersRegistry.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblSizeOfNumbersRegistry.setLineWidth(1)
        self.lblSizeOfNumbersRegistry.setObjectName(_fromUtf8("lblSizeOfNumbersRegistry"))
        self.gridLayout_5.addWidget(self.lblSizeOfNumbersRegistry, 2, 0, 1, 2)
        self.tabMain.addTab(self.tabNumbersRegistry, _fromUtf8(""))
        self.tabReadyToSend = QtGui.QWidget()
        self.tabReadyToSend.setObjectName(_fromUtf8("tabReadyToSend"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabReadyToSend)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grpReadyFilter = QtGui.QGroupBox(self.tabReadyToSend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpReadyFilter.sizePolicy().hasHeightForWidth())
        self.grpReadyFilter.setSizePolicy(sizePolicy)
        self.grpReadyFilter.setObjectName(_fromUtf8("grpReadyFilter"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grpReadyFilter)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.edtReadyNumber = QtGui.QLineEdit(self.grpReadyFilter)
        self.edtReadyNumber.setObjectName(_fromUtf8("edtReadyNumber"))
        self.gridLayout_7.addWidget(self.edtReadyNumber, 5, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 8, 0, 1, 2)
        self.buttonBoxReady = CApplyResetDialogButtonBox(self.grpReadyFilter)
        self.buttonBoxReady.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxReady.setObjectName(_fromUtf8("buttonBoxReady"))
        self.gridLayout_7.addWidget(self.buttonBoxReady, 9, 0, 1, 2)
        self.cmbReadyOrgStructure = COrgStructureComboBox(self.grpReadyFilter)
        self.cmbReadyOrgStructure.setObjectName(_fromUtf8("cmbReadyOrgStructure"))
        self.gridLayout_7.addWidget(self.cmbReadyOrgStructure, 1, 0, 1, 2)
        self.lblReadyBegDate = QtGui.QLabel(self.grpReadyFilter)
        self.lblReadyBegDate.setObjectName(_fromUtf8("lblReadyBegDate"))
        self.gridLayout_7.addWidget(self.lblReadyBegDate, 6, 0, 1, 1)
        self.lblReadyPerson = QtGui.QLabel(self.grpReadyFilter)
        self.lblReadyPerson.setObjectName(_fromUtf8("lblReadyPerson"))
        self.gridLayout_7.addWidget(self.lblReadyPerson, 2, 0, 1, 2)
        self.lblReadyOrgStructure = QtGui.QLabel(self.grpReadyFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReadyOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblReadyOrgStructure.setSizePolicy(sizePolicy)
        self.lblReadyOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblReadyOrgStructure.setObjectName(_fromUtf8("lblReadyOrgStructure"))
        self.gridLayout_7.addWidget(self.lblReadyOrgStructure, 0, 0, 1, 2)
        self.edtReadyBegDate = CDateEdit(self.grpReadyFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReadyBegDate.sizePolicy().hasHeightForWidth())
        self.edtReadyBegDate.setSizePolicy(sizePolicy)
        self.edtReadyBegDate.setCalendarPopup(True)
        self.edtReadyBegDate.setObjectName(_fromUtf8("edtReadyBegDate"))
        self.gridLayout_7.addWidget(self.edtReadyBegDate, 6, 1, 1, 1)
        self.lblReadyEndDate = QtGui.QLabel(self.grpReadyFilter)
        self.lblReadyEndDate.setObjectName(_fromUtf8("lblReadyEndDate"))
        self.gridLayout_7.addWidget(self.lblReadyEndDate, 7, 0, 1, 1)
        self.edtReadyEndDate = CDateEdit(self.grpReadyFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReadyEndDate.sizePolicy().hasHeightForWidth())
        self.edtReadyEndDate.setSizePolicy(sizePolicy)
        self.edtReadyEndDate.setCalendarPopup(True)
        self.edtReadyEndDate.setObjectName(_fromUtf8("edtReadyEndDate"))
        self.gridLayout_7.addWidget(self.edtReadyEndDate, 7, 1, 1, 1)
        self.lblReadyNumber = QtGui.QLabel(self.grpReadyFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReadyNumber.sizePolicy().hasHeightForWidth())
        self.lblReadyNumber.setSizePolicy(sizePolicy)
        self.lblReadyNumber.setObjectName(_fromUtf8("lblReadyNumber"))
        self.gridLayout_7.addWidget(self.lblReadyNumber, 4, 0, 1, 2)
        self.cmbReadyPerson = CPersonComboBoxEx(self.grpReadyFilter)
        self.cmbReadyPerson.setObjectName(_fromUtf8("cmbReadyPerson"))
        self.gridLayout_7.addWidget(self.cmbReadyPerson, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.grpReadyFilter, 0, 0, 3, 1)
        self.btnSend = QtGui.QPushButton(self.tabReadyToSend)
        self.btnSend.setEnabled(True)
        self.btnSend.setObjectName(_fromUtf8("btnSend"))
        self.gridLayout_4.addWidget(self.btnSend, 2, 1, 1, 2)
        self.tblReadyTempInvalidDocuments = CTableView(self.tabReadyToSend)
        self.tblReadyTempInvalidDocuments.setObjectName(_fromUtf8("tblReadyTempInvalidDocuments"))
        self.gridLayout_4.addWidget(self.tblReadyTempInvalidDocuments, 0, 1, 1, 2)
        self.lblRowsInReadyTempInvalidDocuments = QtGui.QLabel(self.tabReadyToSend)
        self.lblRowsInReadyTempInvalidDocuments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblRowsInReadyTempInvalidDocuments.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblRowsInReadyTempInvalidDocuments.setObjectName(_fromUtf8("lblRowsInReadyTempInvalidDocuments"))
        self.gridLayout_4.addWidget(self.lblRowsInReadyTempInvalidDocuments, 1, 1, 1, 2)
        self.tabMain.addTab(self.tabReadyToSend, _fromUtf8(""))
        self.tabExpired = QtGui.QWidget()
        self.tabExpired.setObjectName(_fromUtf8("tabExpired"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabExpired)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblExpiredTempInvalidDocuments = CTableView(self.tabExpired)
        self.tblExpiredTempInvalidDocuments.setObjectName(_fromUtf8("tblExpiredTempInvalidDocuments"))
        self.gridLayout_3.addWidget(self.tblExpiredTempInvalidDocuments, 0, 1, 1, 1)
        self.btnCheckExpiredDocuments = QtGui.QPushButton(self.tabExpired)
        self.btnCheckExpiredDocuments.setObjectName(_fromUtf8("btnCheckExpiredDocuments"))
        self.gridLayout_3.addWidget(self.btnCheckExpiredDocuments, 2, 1, 1, 1)
        self.grpExpiredFilter = QtGui.QGroupBox(self.tabExpired)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpExpiredFilter.sizePolicy().hasHeightForWidth())
        self.grpExpiredFilter.setSizePolicy(sizePolicy)
        self.grpExpiredFilter.setObjectName(_fromUtf8("grpExpiredFilter"))
        self.gridLayout_9 = QtGui.QGridLayout(self.grpExpiredFilter)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 8, 0, 1, 2)
        self.lblExpiredOrgStructure = QtGui.QLabel(self.grpExpiredFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpiredOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblExpiredOrgStructure.setSizePolicy(sizePolicy)
        self.lblExpiredOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblExpiredOrgStructure.setObjectName(_fromUtf8("lblExpiredOrgStructure"))
        self.gridLayout_9.addWidget(self.lblExpiredOrgStructure, 0, 0, 1, 2)
        self.cmbExpiredOrgStructure = COrgStructureComboBox(self.grpExpiredFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbExpiredOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbExpiredOrgStructure.setSizePolicy(sizePolicy)
        self.cmbExpiredOrgStructure.setObjectName(_fromUtf8("cmbExpiredOrgStructure"))
        self.gridLayout_9.addWidget(self.cmbExpiredOrgStructure, 1, 0, 1, 2)
        self.lblExpiredPerson = QtGui.QLabel(self.grpExpiredFilter)
        self.lblExpiredPerson.setObjectName(_fromUtf8("lblExpiredPerson"))
        self.gridLayout_9.addWidget(self.lblExpiredPerson, 2, 0, 1, 2)
        self.buttonBoxExpired = CApplyResetDialogButtonBox(self.grpExpiredFilter)
        self.buttonBoxExpired.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxExpired.setObjectName(_fromUtf8("buttonBoxExpired"))
        self.gridLayout_9.addWidget(self.buttonBoxExpired, 9, 0, 1, 2)
        self.lblExpiredDays = QtGui.QLabel(self.grpExpiredFilter)
        self.lblExpiredDays.setObjectName(_fromUtf8("lblExpiredDays"))
        self.gridLayout_9.addWidget(self.lblExpiredDays, 4, 0, 1, 2)
        self.edtExpiredDays = QtGui.QSpinBox(self.grpExpiredFilter)
        self.edtExpiredDays.setMinimum(1)
        self.edtExpiredDays.setMaximum(99999)
        self.edtExpiredDays.setProperty("value", 30)
        self.edtExpiredDays.setObjectName(_fromUtf8("edtExpiredDays"))
        self.gridLayout_9.addWidget(self.edtExpiredDays, 5, 0, 1, 2)
        self.cmbExpiredPerson = CPersonComboBoxEx(self.grpExpiredFilter)
        self.cmbExpiredPerson.setObjectName(_fromUtf8("cmbExpiredPerson"))
        self.gridLayout_9.addWidget(self.cmbExpiredPerson, 3, 0, 1, 2)
        self.lblExpiredFullName = QtGui.QLabel(self.grpExpiredFilter)
        self.lblExpiredFullName.setObjectName(_fromUtf8("lblExpiredFullName"))
        self.gridLayout_9.addWidget(self.lblExpiredFullName, 6, 0, 1, 1)
        self.edtExpiredFullName = QtGui.QLineEdit(self.grpExpiredFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExpiredFullName.sizePolicy().hasHeightForWidth())
        self.edtExpiredFullName.setSizePolicy(sizePolicy)
        self.edtExpiredFullName.setObjectName(_fromUtf8("edtExpiredFullName"))
        self.gridLayout_9.addWidget(self.edtExpiredFullName, 7, 0, 1, 2)
        self.gridLayout_3.addWidget(self.grpExpiredFilter, 0, 0, 3, 1)
        self.lblRowsInExpiredTempInvalidDocuments = QtGui.QLabel(self.tabExpired)
        self.lblRowsInExpiredTempInvalidDocuments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblRowsInExpiredTempInvalidDocuments.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblRowsInExpiredTempInvalidDocuments.setObjectName(_fromUtf8("lblRowsInExpiredTempInvalidDocuments"))
        self.gridLayout_3.addWidget(self.lblRowsInExpiredTempInvalidDocuments, 1, 1, 1, 1)
        self.tabMain.addTab(self.tabExpired, _fromUtf8(""))
        self.tabHistory = QtGui.QWidget()
        self.tabHistory.setEnabled(True)
        self.tabHistory.setObjectName(_fromUtf8("tabHistory"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabHistory)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.grpHistoryFilter = QtGui.QGroupBox(self.tabHistory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpHistoryFilter.sizePolicy().hasHeightForWidth())
        self.grpHistoryFilter.setSizePolicy(sizePolicy)
        self.grpHistoryFilter.setObjectName(_fromUtf8("grpHistoryFilter"))
        self.gridLayout_8 = QtGui.QGridLayout(self.grpHistoryFilter)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblHistoryBegDate = QtGui.QLabel(self.grpHistoryFilter)
        self.lblHistoryBegDate.setObjectName(_fromUtf8("lblHistoryBegDate"))
        self.gridLayout_8.addWidget(self.lblHistoryBegDate, 6, 0, 1, 1)
        self.edtHistoryBegDate = CDateEdit(self.grpHistoryFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHistoryBegDate.sizePolicy().hasHeightForWidth())
        self.edtHistoryBegDate.setSizePolicy(sizePolicy)
        self.edtHistoryBegDate.setCalendarPopup(True)
        self.edtHistoryBegDate.setObjectName(_fromUtf8("edtHistoryBegDate"))
        self.gridLayout_8.addWidget(self.edtHistoryBegDate, 6, 1, 1, 1)
        self.lblHistoryEndDate = QtGui.QLabel(self.grpHistoryFilter)
        self.lblHistoryEndDate.setObjectName(_fromUtf8("lblHistoryEndDate"))
        self.gridLayout_8.addWidget(self.lblHistoryEndDate, 7, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 8, 0, 1, 2)
        self.edtHistoryEndDate = CDateEdit(self.grpHistoryFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHistoryEndDate.sizePolicy().hasHeightForWidth())
        self.edtHistoryEndDate.setSizePolicy(sizePolicy)
        self.edtHistoryEndDate.setCalendarPopup(True)
        self.edtHistoryEndDate.setObjectName(_fromUtf8("edtHistoryEndDate"))
        self.gridLayout_8.addWidget(self.edtHistoryEndDate, 7, 1, 1, 1)
        self.lblHistoryNumber = QtGui.QLabel(self.grpHistoryFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistoryNumber.sizePolicy().hasHeightForWidth())
        self.lblHistoryNumber.setSizePolicy(sizePolicy)
        self.lblHistoryNumber.setObjectName(_fromUtf8("lblHistoryNumber"))
        self.gridLayout_8.addWidget(self.lblHistoryNumber, 4, 0, 1, 2)
        self.edtHistoryNumber = QtGui.QLineEdit(self.grpHistoryFilter)
        self.edtHistoryNumber.setObjectName(_fromUtf8("edtHistoryNumber"))
        self.gridLayout_8.addWidget(self.edtHistoryNumber, 5, 0, 1, 2)
        self.buttonBoxHistory = CApplyResetDialogButtonBox(self.grpHistoryFilter)
        self.buttonBoxHistory.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxHistory.setObjectName(_fromUtf8("buttonBoxHistory"))
        self.gridLayout_8.addWidget(self.buttonBoxHistory, 9, 0, 1, 2)
        self.cmbHistoryOrgStructure = COrgStructureComboBox(self.grpHistoryFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbHistoryOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbHistoryOrgStructure.setSizePolicy(sizePolicy)
        self.cmbHistoryOrgStructure.setObjectName(_fromUtf8("cmbHistoryOrgStructure"))
        self.gridLayout_8.addWidget(self.cmbHistoryOrgStructure, 1, 0, 1, 2)
        self.lblHistoryOrgStructure = QtGui.QLabel(self.grpHistoryFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistoryOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblHistoryOrgStructure.setSizePolicy(sizePolicy)
        self.lblHistoryOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblHistoryOrgStructure.setObjectName(_fromUtf8("lblHistoryOrgStructure"))
        self.gridLayout_8.addWidget(self.lblHistoryOrgStructure, 0, 0, 1, 2)
        self.lblHistoryPerson = QtGui.QLabel(self.grpHistoryFilter)
        self.lblHistoryPerson.setObjectName(_fromUtf8("lblHistoryPerson"))
        self.gridLayout_8.addWidget(self.lblHistoryPerson, 2, 0, 1, 2)
        self.cmbHistoryPerson = CPersonComboBoxEx(self.grpHistoryFilter)
        self.cmbHistoryPerson.setObjectName(_fromUtf8("cmbHistoryPerson"))
        self.gridLayout_8.addWidget(self.cmbHistoryPerson, 3, 0, 1, 2)
        self.gridLayout_2.addWidget(self.grpHistoryFilter, 0, 0, 3, 1)
        self.tblTempInvalidDocumentExports = CInDocTableView(self.tabHistory)
        self.tblTempInvalidDocumentExports.setObjectName(_fromUtf8("tblTempInvalidDocumentExports"))
        self.gridLayout_2.addWidget(self.tblTempInvalidDocumentExports, 0, 1, 3, 1)
        self.tabMain.addTab(self.tabHistory, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabMain, 0, 0, 1, 1)
        self.lblReadyBegDate.setBuddy(self.edtReadyBegDate)
        self.lblReadyPerson.setBuddy(self.cmbReadyPerson)
        self.lblReadyOrgStructure.setBuddy(self.cmbReadyOrgStructure)
        self.lblReadyEndDate.setBuddy(self.edtReadyEndDate)
        self.lblReadyNumber.setBuddy(self.edtReadyNumber)
        self.lblExpiredOrgStructure.setBuddy(self.cmbReadyOrgStructure)
        self.lblExpiredPerson.setBuddy(self.cmbHistoryPerson)
        self.lblExpiredDays.setBuddy(self.edtExpiredDays)
        self.lblExpiredFullName.setBuddy(self.edtExpiredFullName)
        self.lblHistoryBegDate.setBuddy(self.edtReadyBegDate)
        self.lblHistoryEndDate.setBuddy(self.edtReadyEndDate)
        self.lblHistoryNumber.setBuddy(self.edtReadyNumber)
        self.lblHistoryOrgStructure.setBuddy(self.cmbReadyOrgStructure)
        self.lblHistoryPerson.setBuddy(self.cmbHistoryPerson)

        self.retranslateUi(CWorkSpace)
        self.tabMain.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(CWorkSpace)
        CWorkSpace.setTabOrder(self.tabMain, self.tblNumbersRegistry)
        CWorkSpace.setTabOrder(self.tblNumbersRegistry, self.btnRequestNumbers)
        CWorkSpace.setTabOrder(self.btnRequestNumbers, self.cmbReadyOrgStructure)
        CWorkSpace.setTabOrder(self.cmbReadyOrgStructure, self.cmbReadyPerson)
        CWorkSpace.setTabOrder(self.cmbReadyPerson, self.edtReadyNumber)
        CWorkSpace.setTabOrder(self.edtReadyNumber, self.edtReadyBegDate)
        CWorkSpace.setTabOrder(self.edtReadyBegDate, self.edtReadyEndDate)
        CWorkSpace.setTabOrder(self.edtReadyEndDate, self.buttonBoxReady)
        CWorkSpace.setTabOrder(self.buttonBoxReady, self.tblReadyTempInvalidDocuments)
        CWorkSpace.setTabOrder(self.tblReadyTempInvalidDocuments, self.btnSend)
        CWorkSpace.setTabOrder(self.btnSend, self.cmbHistoryOrgStructure)
        CWorkSpace.setTabOrder(self.cmbHistoryOrgStructure, self.cmbHistoryPerson)
        CWorkSpace.setTabOrder(self.cmbHistoryPerson, self.edtHistoryNumber)
        CWorkSpace.setTabOrder(self.edtHistoryNumber, self.edtHistoryBegDate)
        CWorkSpace.setTabOrder(self.edtHistoryBegDate, self.edtHistoryEndDate)
        CWorkSpace.setTabOrder(self.edtHistoryEndDate, self.buttonBoxHistory)
        CWorkSpace.setTabOrder(self.buttonBoxHistory, self.tblTempInvalidDocumentExports)
        CWorkSpace.setTabOrder(self.tblTempInvalidDocumentExports, self.cmbExpiredOrgStructure)
        CWorkSpace.setTabOrder(self.cmbExpiredOrgStructure, self.cmbExpiredPerson)
        CWorkSpace.setTabOrder(self.cmbExpiredPerson, self.edtExpiredDays)
        CWorkSpace.setTabOrder(self.edtExpiredDays, self.buttonBoxExpired)
        CWorkSpace.setTabOrder(self.buttonBoxExpired, self.tblExpiredTempInvalidDocuments)
        CWorkSpace.setTabOrder(self.tblExpiredTempInvalidDocuments, self.btnCheckExpiredDocuments)

    def retranslateUi(self, CWorkSpace):
        CWorkSpace.setWindowTitle(_translate("CWorkSpace", "Dialog", None))
        self.btnRequestNumbers.setText(_translate("CWorkSpace", "&Запросить номера в сервисе СФР", None))
        self.lblSizeOfNumbersRegistry.setText(_translate("CWorkSpace", "…", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabNumbersRegistry), _translate("CWorkSpace", "&Реестр номеров ЛН", None))
        self.grpReadyFilter.setTitle(_translate("CWorkSpace", "Фильтр", None))
        self.lblReadyBegDate.setText(_translate("CWorkSpace", "&Дата c", None))
        self.lblReadyPerson.setText(_translate("CWorkSpace", "&Врач", None))
        self.lblReadyOrgStructure.setText(_translate("CWorkSpace", "Под&разделение", None))
        self.edtReadyBegDate.setDisplayFormat(_translate("CWorkSpace", "dd.MM.yyyy", None))
        self.lblReadyEndDate.setText(_translate("CWorkSpace", "&по", None))
        self.edtReadyEndDate.setDisplayFormat(_translate("CWorkSpace", "dd.MM.yyyy", None))
        self.lblReadyNumber.setText(_translate("CWorkSpace", "&Номер", None))
        self.btnSend.setText(_translate("CWorkSpace", "&Передать в СФР", None))
        self.lblRowsInReadyTempInvalidDocuments.setText(_translate("CWorkSpace", "…", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabReadyToSend), _translate("CWorkSpace", "&Готово к передаче", None))
        self.btnCheckExpiredDocuments.setText(_translate("CWorkSpace", "&Запросить состояние в СФР", None))
        self.grpExpiredFilter.setTitle(_translate("CWorkSpace", "Фильтр", None))
        self.lblExpiredOrgStructure.setText(_translate("CWorkSpace", "Под&разделение", None))
        self.lblExpiredPerson.setText(_translate("CWorkSpace", "&Врач", None))
        self.lblExpiredDays.setText(_translate("CWorkSpace", "&Просрочено дней, более ", None))
        self.lblExpiredFullName.setText(_translate("CWorkSpace", "&ФИО получателя", None))
        self.lblRowsInExpiredTempInvalidDocuments.setText(_translate("CWorkSpace", "…", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabExpired), _translate("CWorkSpace", "&Контроль открытых ЭЛН", None))
        self.grpHistoryFilter.setTitle(_translate("CWorkSpace", "Фильтр", None))
        self.lblHistoryBegDate.setText(_translate("CWorkSpace", "&Дата c", None))
        self.edtHistoryBegDate.setDisplayFormat(_translate("CWorkSpace", "dd.MM.yyyy", None))
        self.lblHistoryEndDate.setText(_translate("CWorkSpace", "&по", None))
        self.edtHistoryEndDate.setDisplayFormat(_translate("CWorkSpace", "dd.MM.yyyy", None))
        self.lblHistoryNumber.setText(_translate("CWorkSpace", "&Номер", None))
        self.lblHistoryOrgStructure.setText(_translate("CWorkSpace", "Под&разделение", None))
        self.lblHistoryPerson.setText(_translate("CWorkSpace", "&Врач", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabHistory), _translate("CWorkSpace", "&История обмена", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
