# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\appendix\kladr_update\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(647, 586)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridlayout = QtGui.QGridLayout(self.centralWidget)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.vboxlayout.addWidget(self.label_4)
        self.editServer = QtGui.QLineEdit(self.layoutWidget)
        self.editServer.setObjectName(_fromUtf8("editServer"))
        self.vboxlayout.addWidget(self.editServer)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vboxlayout.addWidget(self.label_3)
        self.editUser = QtGui.QLineEdit(self.layoutWidget)
        self.editUser.setEnabled(True)
        self.editUser.setObjectName(_fromUtf8("editUser"))
        self.vboxlayout.addWidget(self.editUser)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vboxlayout.addWidget(self.label_2)
        self.editPassword = QtGui.QLineEdit(self.layoutWidget)
        self.editPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.editPassword.setObjectName(_fromUtf8("editPassword"))
        self.vboxlayout.addWidget(self.editPassword)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.vboxlayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.editDatabase = QtGui.QLineEdit(self.layoutWidget)
        self.editDatabase.setEnabled(True)
        self.editDatabase.setObjectName(_fromUtf8("editDatabase"))
        self.horizontalLayout_4.addWidget(self.editDatabase)
        self.vboxlayout.addLayout(self.horizontalLayout_4)
        self.gridlayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushReverse = QtGui.QPushButton(self.centralWidget)
        self.pushReverse.setObjectName(_fromUtf8("pushReverse"))
        self.horizontalLayout.addWidget(self.pushReverse)
        self.pushTest = QtGui.QPushButton(self.centralWidget)
        self.pushTest.setObjectName(_fromUtf8("pushTest"))
        self.horizontalLayout.addWidget(self.pushTest)
        self.pushParseAddress = QtGui.QPushButton(self.centralWidget)
        self.pushParseAddress.setObjectName(_fromUtf8("pushParseAddress"))
        self.horizontalLayout.addWidget(self.pushParseAddress)
        self.btnClose = QtGui.QPushButton(self.centralWidget)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridlayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineKLADRDir = QtGui.QLineEdit(self.centralWidget)
        self.lineKLADRDir.setObjectName(_fromUtf8("lineKLADRDir"))
        self.horizontalLayout_2.addWidget(self.lineKLADRDir)
        self.pushKLADRDir = QtGui.QPushButton(self.centralWidget)
        self.pushKLADRDir.setObjectName(_fromUtf8("pushKLADRDir"))
        self.horizontalLayout_2.addWidget(self.pushKLADRDir)
        self.pushUpdateKLADR = QtGui.QPushButton(self.centralWidget)
        self.pushUpdateKLADR.setObjectName(_fromUtf8("pushUpdateKLADR"))
        self.horizontalLayout_2.addWidget(self.pushUpdateKLADR)
        self.gridlayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineOKATODir = QtGui.QLineEdit(self.centralWidget)
        self.lineOKATODir.setObjectName(_fromUtf8("lineOKATODir"))
        self.horizontalLayout_3.addWidget(self.lineOKATODir)
        self.pushOKATODir = QtGui.QPushButton(self.centralWidget)
        self.pushOKATODir.setObjectName(_fromUtf8("pushOKATODir"))
        self.horizontalLayout_3.addWidget(self.pushOKATODir)
        self.pushUpdateOKATO = QtGui.QPushButton(self.centralWidget)
        self.pushUpdateOKATO.setObjectName(_fromUtf8("pushUpdateOKATO"))
        self.horizontalLayout_3.addWidget(self.pushUpdateOKATO)
        self.gridlayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.log = QtGui.QTextBrowser(self.centralWidget)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridlayout.addWidget(self.log, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.close)
        QtCore.QObject.connect(self.pushUpdateKLADR, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.updateKLADR)
        QtCore.QObject.connect(self.pushUpdateOKATO, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.updateOKATO)
        QtCore.QObject.connect(self.pushTest, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.test)
        QtCore.QObject.connect(self.pushReverse, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.rollback)
        QtCore.QObject.connect(self.pushParseAddress, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.parseAddresses)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Обновление КЛАДР", None))
        self.label_4.setText(_translate("MainWindow", "Имя сервера:", None))
        self.editServer.setText(_translate("MainWindow", "localhost", None))
        self.label_3.setText(_translate("MainWindow", "Имя пользователя:", None))
        self.editUser.setText(_translate("MainWindow", "dbuser", None))
        self.label_2.setText(_translate("MainWindow", "Пароль:", None))
        self.label_5.setText(_translate("MainWindow", "Имя базы данных КЛАДР: kladr", None))
        self.label.setText(_translate("MainWindow", "Имя базы данных ЛПУ:", None))
        self.editDatabase.setText(_translate("MainWindow", "s11", None))
        self.pushReverse.setText(_translate("MainWindow", "Откат обновления", None))
        self.pushTest.setText(_translate("MainWindow", "Проверить целостность БД", None))
        self.pushParseAddress.setText(_translate("MainWindow", "Разбор адресов", None))
        self.btnClose.setText(_translate("MainWindow", "Выйти", None))
        self.pushKLADRDir.setText(_translate("MainWindow", "Выбрать каталог...", None))
        self.pushUpdateKLADR.setText(_translate("MainWindow", "Обновить КЛАДР", None))
        self.pushOKATODir.setText(_translate("MainWindow", "Выбрать каталог...", None))
        self.pushUpdateOKATO.setText(_translate("MainWindow", "Обновить ОКАТО", None))

