# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\RefBooks\DocumentType\RBDocumentTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(400, 353)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout = QtGui.QGridLayout(self.tabMain)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 2, 1, 2)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 2, 1, 2)
        self.chkCitizenship = QtGui.QCheckBox(self.tabMain)
        self.chkCitizenship.setText(_fromUtf8(""))
        self.chkCitizenship.setObjectName(_fromUtf8("chkCitizenship"))
        self.gridLayout.addWidget(self.chkCitizenship, 12, 2, 1, 2)
        self.lblCitizenship = QtGui.QLabel(self.tabMain)
        self.lblCitizenship.setObjectName(_fromUtf8("lblCitizenship"))
        self.gridLayout.addWidget(self.lblCitizenship, 12, 0, 1, 1)
        self.lblLeftPartRegExp = QtGui.QLabel(self.tabMain)
        self.lblLeftPartRegExp.setObjectName(_fromUtf8("lblLeftPartRegExp"))
        self.gridLayout.addWidget(self.lblLeftPartRegExp, 6, 0, 1, 2)
        self.btnTestNumber = QtGui.QPushButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTestNumber.sizePolicy().hasHeightForWidth())
        self.btnTestNumber.setSizePolicy(sizePolicy)
        self.btnTestNumber.setObjectName(_fromUtf8("btnTestNumber"))
        self.gridLayout.addWidget(self.btnTestNumber, 11, 3, 1, 1)
        self.chkHasRightPart = QtGui.QCheckBox(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkHasRightPart.sizePolicy().hasHeightForWidth())
        self.chkHasRightPart.setSizePolicy(sizePolicy)
        self.chkHasRightPart.setText(_fromUtf8(""))
        self.chkHasRightPart.setCheckable(True)
        self.chkHasRightPart.setChecked(True)
        self.chkHasRightPart.setObjectName(_fromUtf8("chkHasRightPart"))
        self.gridLayout.addWidget(self.chkHasRightPart, 7, 2, 1, 1)
        self.cmbGroup = CRBComboBox(self.tabMain)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridLayout.addWidget(self.cmbGroup, 5, 2, 1, 2)
        self.edtLeftPartRegExp = QtGui.QLineEdit(self.tabMain)
        self.edtLeftPartRegExp.setMaxLength(128)
        self.edtLeftPartRegExp.setObjectName(_fromUtf8("edtLeftPartRegExp"))
        self.gridLayout.addWidget(self.edtLeftPartRegExp, 6, 2, 1, 1)
        self.label = QtGui.QLabel(self.tabMain)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.edtFederalCode = QtGui.QLineEdit(self.tabMain)
        self.edtFederalCode.setEnabled(True)
        self.edtFederalCode.setObjectName(_fromUtf8("edtFederalCode"))
        self.gridLayout.addWidget(self.edtFederalCode, 3, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(103, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 1, 1, 2)
        self.edtPartSeparator = QtGui.QLineEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPartSeparator.sizePolicy().hasHeightForWidth())
        self.edtPartSeparator.setSizePolicy(sizePolicy)
        self.edtPartSeparator.setMaxLength(1)
        self.edtPartSeparator.setObjectName(_fromUtf8("edtPartSeparator"))
        self.gridLayout.addWidget(self.edtPartSeparator, 9, 2, 1, 2)
        self.btnTestRightPart = QtGui.QPushButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTestRightPart.sizePolicy().hasHeightForWidth())
        self.btnTestRightPart.setSizePolicy(sizePolicy)
        self.btnTestRightPart.setObjectName(_fromUtf8("btnTestRightPart"))
        self.gridLayout.addWidget(self.btnTestRightPart, 10, 3, 1, 1)
        self.lblRightPartRegExp = QtGui.QLabel(self.tabMain)
        self.lblRightPartRegExp.setObjectName(_fromUtf8("lblRightPartRegExp"))
        self.gridLayout.addWidget(self.lblRightPartRegExp, 10, 0, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        self.lblRegionalCode.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout.addWidget(self.lblRegionalCode, 4, 0, 1, 2)
        self.lblPartSeparator = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPartSeparator.sizePolicy().hasHeightForWidth())
        self.lblPartSeparator.setSizePolicy(sizePolicy)
        self.lblPartSeparator.setObjectName(_fromUtf8("lblPartSeparator"))
        self.gridLayout.addWidget(self.lblPartSeparator, 9, 0, 1, 2)
        self.btnTestLeftPart = QtGui.QPushButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTestLeftPart.sizePolicy().hasHeightForWidth())
        self.btnTestLeftPart.setSizePolicy(sizePolicy)
        self.btnTestLeftPart.setObjectName(_fromUtf8("btnTestLeftPart"))
        self.gridLayout.addWidget(self.btnTestLeftPart, 6, 3, 1, 1)
        self.edtRightPartRegExp = QtGui.QLineEdit(self.tabMain)
        self.edtRightPartRegExp.setMaxLength(128)
        self.edtRightPartRegExp.setObjectName(_fromUtf8("edtRightPartRegExp"))
        self.gridLayout.addWidget(self.edtRightPartRegExp, 10, 2, 1, 1)
        self.edtNumberRegExp = QtGui.QLineEdit(self.tabMain)
        self.edtNumberRegExp.setMaxLength(128)
        self.edtNumberRegExp.setObjectName(_fromUtf8("edtNumberRegExp"))
        self.gridLayout.addWidget(self.edtNumberRegExp, 11, 2, 1, 1)
        self.lblFinance = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 5, 0, 1, 2)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setEnabled(True)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout.addWidget(self.edtRegionalCode, 4, 2, 1, 2)
        self.lblNumberRegExp = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNumberRegExp.sizePolicy().hasHeightForWidth())
        self.lblNumberRegExp.setSizePolicy(sizePolicy)
        self.lblNumberRegExp.setObjectName(_fromUtf8("lblNumberRegExp"))
        self.gridLayout.addWidget(self.lblNumberRegExp, 11, 0, 1, 1)
        self.lblFederalCode = QtGui.QLabel(self.tabMain)
        self.lblFederalCode.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFederalCode.sizePolicy().hasHeightForWidth())
        self.lblFederalCode.setSizePolicy(sizePolicy)
        self.lblFederalCode.setObjectName(_fromUtf8("lblFederalCode"))
        self.gridLayout.addWidget(self.lblFederalCode, 3, 0, 1, 2)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout.addWidget(self.lblTitle, 2, 0, 1, 1)
        self.edtTitle = QtGui.QLineEdit(self.tabMain)
        self.edtTitle.setObjectName(_fromUtf8("edtTitle"))
        self.gridLayout.addWidget(self.edtTitle, 2, 2, 1, 2)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.lblName.setBuddy(self.edtName)
        self.lblCitizenship.setBuddy(self.chkCitizenship)
        self.lblLeftPartRegExp.setBuddy(self.edtLeftPartRegExp)
        self.label.setBuddy(self.chkHasRightPart)
        self.lblRightPartRegExp.setBuddy(self.edtRightPartRegExp)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblPartSeparator.setBuddy(self.edtPartSeparator)
        self.lblFinance.setBuddy(self.cmbGroup)
        self.lblNumberRegExp.setBuddy(self.edtNumberRegExp)
        self.lblFederalCode.setBuddy(self.edtFederalCode)
        self.lblCode.setBuddy(self.edtCode)
        self.lblTitle.setBuddy(self.edtTitle)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QObject.connect(self.chkHasRightPart, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtRightPartRegExp.setEnabled)
        QtCore.QObject.connect(self.chkHasRightPart, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnTestRightPart.setEnabled)
        QtCore.QObject.connect(self.chkHasRightPart, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblPartSeparator.setEnabled)
        QtCore.QObject.connect(self.chkHasRightPart, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtPartSeparator.setEnabled)
        QtCore.QObject.connect(self.chkHasRightPart, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblRightPartRegExp.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtFederalCode)
        ItemEditorDialog.setTabOrder(self.edtFederalCode, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.cmbGroup)
        ItemEditorDialog.setTabOrder(self.cmbGroup, self.edtLeftPartRegExp)
        ItemEditorDialog.setTabOrder(self.edtLeftPartRegExp, self.btnTestLeftPart)
        ItemEditorDialog.setTabOrder(self.btnTestLeftPart, self.chkHasRightPart)
        ItemEditorDialog.setTabOrder(self.chkHasRightPart, self.edtPartSeparator)
        ItemEditorDialog.setTabOrder(self.edtPartSeparator, self.edtRightPartRegExp)
        ItemEditorDialog.setTabOrder(self.edtRightPartRegExp, self.btnTestRightPart)
        ItemEditorDialog.setTabOrder(self.btnTestRightPart, self.edtNumberRegExp)
        ItemEditorDialog.setTabOrder(self.edtNumberRegExp, self.btnTestNumber)
        ItemEditorDialog.setTabOrder(self.btnTestNumber, self.chkCitizenship)
        ItemEditorDialog.setTabOrder(self.chkCitizenship, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.lblCitizenship.setText(_translate("ItemEditorDialog", "Гражданство Р&Ф", None))
        self.lblLeftPartRegExp.setText(_translate("ItemEditorDialog", "&Левая часть серии", None))
        self.btnTestNumber.setText(_translate("ItemEditorDialog", "Проверить", None))
        self.label.setText(_translate("ItemEditorDialog", "Серия из двух &частей", None))
        self.btnTestRightPart.setText(_translate("ItemEditorDialog", "Проверить", None))
        self.lblRightPartRegExp.setText(_translate("ItemEditorDialog", "&Правая часть серии", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Территориальный код", None))
        self.lblPartSeparator.setText(_translate("ItemEditorDialog", "&Разделитель", None))
        self.btnTestLeftPart.setText(_translate("ItemEditorDialog", "Проверить", None))
        self.lblFinance.setText(_translate("ItemEditorDialog", "&Группа документов", None))
        self.lblNumberRegExp.setText(_translate("ItemEditorDialog", "Но&мер", None))
        self.lblFederalCode.setText(_translate("ItemEditorDialog", "&Федеральный код", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblTitle.setText(_translate("ItemEditorDialog", "Наименование для печати", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "&Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "&Идентификация", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
