# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBRelative.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(555, 279)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 0, 1, 1, 3)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout_2.addWidget(self.lblRegionalCode, 1, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout_2.addWidget(self.edtRegionalCode, 1, 1, 1, 3)
        self.lblRegionalReverseCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalReverseCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalReverseCode.setSizePolicy(sizePolicy)
        self.lblRegionalReverseCode.setObjectName(_fromUtf8("lblRegionalReverseCode"))
        self.gridLayout_2.addWidget(self.lblRegionalReverseCode, 2, 0, 1, 1)
        self.edtRegionalReverseCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalReverseCode.setObjectName(_fromUtf8("edtRegionalReverseCode"))
        self.gridLayout_2.addWidget(self.edtRegionalReverseCode, 2, 1, 1, 3)
        self.lblLeftName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftName.sizePolicy().hasHeightForWidth())
        self.lblLeftName.setSizePolicy(sizePolicy)
        self.lblLeftName.setObjectName(_fromUtf8("lblLeftName"))
        self.gridLayout_2.addWidget(self.lblLeftName, 3, 0, 1, 1)
        self.edtLeftName = QtGui.QLineEdit(self.tabMain)
        self.edtLeftName.setObjectName(_fromUtf8("edtLeftName"))
        self.gridLayout_2.addWidget(self.edtLeftName, 3, 1, 1, 1)
        self.lblRightName = QtGui.QLabel(self.tabMain)
        self.lblRightName.setObjectName(_fromUtf8("lblRightName"))
        self.gridLayout_2.addWidget(self.lblRightName, 3, 2, 1, 1)
        self.edtRightName = QtGui.QLineEdit(self.tabMain)
        self.edtRightName.setObjectName(_fromUtf8("edtRightName"))
        self.gridLayout_2.addWidget(self.edtRightName, 3, 3, 1, 1)
        self.lblGenetic = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGenetic.sizePolicy().hasHeightForWidth())
        self.lblGenetic.setSizePolicy(sizePolicy)
        self.lblGenetic.setObjectName(_fromUtf8("lblGenetic"))
        self.gridLayout_2.addWidget(self.lblGenetic, 4, 0, 1, 1)
        self.chkDirectGeneticRelation = QtGui.QCheckBox(self.tabMain)
        self.chkDirectGeneticRelation.setObjectName(_fromUtf8("chkDirectGeneticRelation"))
        self.gridLayout_2.addWidget(self.chkDirectGeneticRelation, 4, 1, 1, 1)
        self.chkBackwardGeneticRelation = QtGui.QCheckBox(self.tabMain)
        self.chkBackwardGeneticRelation.setObjectName(_fromUtf8("chkBackwardGeneticRelation"))
        self.gridLayout_2.addWidget(self.chkBackwardGeneticRelation, 4, 3, 1, 1)
        self.lblRepresentative = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRepresentative.sizePolicy().hasHeightForWidth())
        self.lblRepresentative.setSizePolicy(sizePolicy)
        self.lblRepresentative.setObjectName(_fromUtf8("lblRepresentative"))
        self.gridLayout_2.addWidget(self.lblRepresentative, 5, 0, 1, 1)
        self.chkDirectRepresentativeRelation = QtGui.QCheckBox(self.tabMain)
        self.chkDirectRepresentativeRelation.setObjectName(_fromUtf8("chkDirectRepresentativeRelation"))
        self.gridLayout_2.addWidget(self.chkDirectRepresentativeRelation, 5, 1, 1, 1)
        self.chkBackwardRepresentativeRelation = QtGui.QCheckBox(self.tabMain)
        self.chkBackwardRepresentativeRelation.setObjectName(_fromUtf8("chkBackwardRepresentativeRelation"))
        self.gridLayout_2.addWidget(self.chkBackwardRepresentativeRelation, 5, 3, 1, 1)
        self.lblEpidemic = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEpidemic.sizePolicy().hasHeightForWidth())
        self.lblEpidemic.setSizePolicy(sizePolicy)
        self.lblEpidemic.setObjectName(_fromUtf8("lblEpidemic"))
        self.gridLayout_2.addWidget(self.lblEpidemic, 6, 0, 1, 1)
        self.chkDirectEpidemicRelation = QtGui.QCheckBox(self.tabMain)
        self.chkDirectEpidemicRelation.setObjectName(_fromUtf8("chkDirectEpidemicRelation"))
        self.gridLayout_2.addWidget(self.chkDirectEpidemicRelation, 6, 1, 1, 1)
        self.chkBackwardEpidemicRelation = QtGui.QCheckBox(self.tabMain)
        self.chkBackwardEpidemicRelation.setObjectName(_fromUtf8("chkBackwardEpidemicRelation"))
        self.gridLayout_2.addWidget(self.chkBackwardEpidemicRelation, 6, 3, 1, 1)
        self.lblDonation = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDonation.sizePolicy().hasHeightForWidth())
        self.lblDonation.setSizePolicy(sizePolicy)
        self.lblDonation.setObjectName(_fromUtf8("lblDonation"))
        self.gridLayout_2.addWidget(self.lblDonation, 7, 0, 1, 1)
        self.chkDirectDonationRelation = QtGui.QCheckBox(self.tabMain)
        self.chkDirectDonationRelation.setObjectName(_fromUtf8("chkDirectDonationRelation"))
        self.gridLayout_2.addWidget(self.chkDirectDonationRelation, 7, 1, 1, 1)
        self.chkBackwardDonationRelation = QtGui.QCheckBox(self.tabMain)
        self.chkBackwardDonationRelation.setObjectName(_fromUtf8("chkBackwardDonationRelation"))
        self.gridLayout_2.addWidget(self.chkBackwardDonationRelation, 7, 3, 1, 1)
        self.lblLeftSex = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftSex.sizePolicy().hasHeightForWidth())
        self.lblLeftSex.setSizePolicy(sizePolicy)
        self.lblLeftSex.setObjectName(_fromUtf8("lblLeftSex"))
        self.gridLayout_2.addWidget(self.lblLeftSex, 8, 0, 1, 1)
        self.cmbLeftSex = QtGui.QComboBox(self.tabMain)
        self.cmbLeftSex.setObjectName(_fromUtf8("cmbLeftSex"))
        self.cmbLeftSex.addItem(_fromUtf8(""))
        self.cmbLeftSex.setItemText(0, _fromUtf8(""))
        self.cmbLeftSex.addItem(_fromUtf8(""))
        self.cmbLeftSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbLeftSex, 8, 1, 1, 1)
        self.lblRightSex = QtGui.QLabel(self.tabMain)
        self.lblRightSex.setObjectName(_fromUtf8("lblRightSex"))
        self.gridLayout_2.addWidget(self.lblRightSex, 8, 2, 1, 1)
        self.cmbRightSex = QtGui.QComboBox(self.tabMain)
        self.cmbRightSex.setObjectName(_fromUtf8("cmbRightSex"))
        self.cmbRightSex.addItem(_fromUtf8(""))
        self.cmbRightSex.setItemText(0, _fromUtf8(""))
        self.cmbRightSex.addItem(_fromUtf8(""))
        self.cmbRightSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbRightSex, 8, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(241, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.lblCode.setBuddy(self.edtCode)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblRegionalReverseCode.setBuddy(self.edtRegionalReverseCode)
        self.lblLeftName.setBuddy(self.edtLeftName)
        self.lblRightName.setBuddy(self.edtRightName)
        self.lblGenetic.setBuddy(self.chkDirectGeneticRelation)
        self.lblRepresentative.setBuddy(self.chkDirectRepresentativeRelation)
        self.lblEpidemic.setBuddy(self.chkDirectEpidemicRelation)
        self.lblDonation.setBuddy(self.chkDirectDonationRelation)
        self.lblLeftSex.setBuddy(self.cmbLeftSex)
        self.lblRightSex.setBuddy(self.cmbRightSex)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.edtRegionalReverseCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalReverseCode, self.edtLeftName)
        ItemEditorDialog.setTabOrder(self.edtLeftName, self.chkDirectGeneticRelation)
        ItemEditorDialog.setTabOrder(self.chkDirectGeneticRelation, self.chkDirectRepresentativeRelation)
        ItemEditorDialog.setTabOrder(self.chkDirectRepresentativeRelation, self.chkDirectEpidemicRelation)
        ItemEditorDialog.setTabOrder(self.chkDirectEpidemicRelation, self.chkDirectDonationRelation)
        ItemEditorDialog.setTabOrder(self.chkDirectDonationRelation, self.cmbLeftSex)
        ItemEditorDialog.setTabOrder(self.cmbLeftSex, self.edtRightName)
        ItemEditorDialog.setTabOrder(self.edtRightName, self.chkBackwardGeneticRelation)
        ItemEditorDialog.setTabOrder(self.chkBackwardGeneticRelation, self.chkBackwardRepresentativeRelation)
        ItemEditorDialog.setTabOrder(self.chkBackwardRepresentativeRelation, self.chkBackwardEpidemicRelation)
        ItemEditorDialog.setTabOrder(self.chkBackwardEpidemicRelation, self.chkBackwardDonationRelation)
        ItemEditorDialog.setTabOrder(self.chkBackwardDonationRelation, self.cmbRightSex)
        ItemEditorDialog.setTabOrder(self.cmbRightSex, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Региональный код отношения", None))
        self.lblRegionalReverseCode.setText(_translate("ItemEditorDialog", "Региональный код &обратного отношения", None))
        self.lblLeftName.setText(_translate("ItemEditorDialog", "&Субьект отношения", None))
        self.edtLeftName.setToolTip(_translate("ItemEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">(лат.) предметы, всякое лицо, вещь, о коих говорится.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">--</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Словарь Даля </span></p></body></html>", None))
        self.lblRightName.setText(_translate("ItemEditorDialog", "&Объект отношения", None))
        self.edtRightName.setToolTip(_translate("ItemEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">(лат.) предмет противоположный субъекту.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">--</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Словарь Даля</span></p></body></html>", None))
        self.lblGenetic.setText(_translate("ItemEditorDialog", "&Генетическая связь", None))
        self.chkDirectGeneticRelation.setToolTip(_translate("ItemEditorDialog", "Передача генетического материала от субъекта к объекту", None))
        self.chkDirectGeneticRelation.setText(_translate("ItemEditorDialog", "Прямая", None))
        self.chkBackwardGeneticRelation.setToolTip(_translate("ItemEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Передача генетического материала от объекта к субъекту</span></p></body></html>", None))
        self.chkBackwardGeneticRelation.setText(_translate("ItemEditorDialog", "Обратная", None))
        self.lblRepresentative.setText(_translate("ItemEditorDialog", "&Представительская связь", None))
        self.chkDirectRepresentativeRelation.setToolTip(_translate("ItemEditorDialog", "Субъект является представителем объекта", None))
        self.chkDirectRepresentativeRelation.setText(_translate("ItemEditorDialog", "Прямая", None))
        self.chkBackwardRepresentativeRelation.setToolTip(_translate("ItemEditorDialog", "Объект является представителем субъекта", None))
        self.chkBackwardRepresentativeRelation.setText(_translate("ItemEditorDialog", "Обратная", None))
        self.lblEpidemic.setText(_translate("ItemEditorDialog", "&Эпид.контактирование", None))
        self.chkDirectEpidemicRelation.setToolTip(_translate("ItemEditorDialog", "Возможна передача от субъекта к объекту", None))
        self.chkDirectEpidemicRelation.setText(_translate("ItemEditorDialog", "Прямое", None))
        self.chkBackwardEpidemicRelation.setToolTip(_translate("ItemEditorDialog", "Возможна передача от объекта к субъекту", None))
        self.chkBackwardEpidemicRelation.setText(_translate("ItemEditorDialog", "Обратное", None))
        self.lblDonation.setText(_translate("ItemEditorDialog", "&Донорство", None))
        self.chkDirectDonationRelation.setToolTip(_translate("ItemEditorDialog", "Передача органов от субъекта к объекту", None))
        self.chkDirectDonationRelation.setText(_translate("ItemEditorDialog", "Прямое", None))
        self.chkBackwardDonationRelation.setToolTip(_translate("ItemEditorDialog", "Передача органов от объекта к субъекту", None))
        self.chkBackwardDonationRelation.setText(_translate("ItemEditorDialog", "Обратное", None))
        self.lblLeftSex.setText(_translate("ItemEditorDialog", "Пол субъекта", None))
        self.cmbLeftSex.setItemText(1, _translate("ItemEditorDialog", "мужской", None))
        self.cmbLeftSex.setItemText(2, _translate("ItemEditorDialog", "женский", None))
        self.lblRightSex.setText(_translate("ItemEditorDialog", "Пол объекта", None))
        self.cmbRightSex.setItemText(1, _translate("ItemEditorDialog", "мужской", None))
        self.cmbRightSex.setItemText(2, _translate("ItemEditorDialog", "женский", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "&Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "&Идентификация", None))

from library.InDocTable import CInDocTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

