# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBNetEditor.ui'
#
# Created: Wed Feb 19 22:52:32 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RBNetEditorDialog(object):
    def setupUi(self, RBNetEditorDialog):
        RBNetEditorDialog.setObjectName(_fromUtf8("RBNetEditorDialog"))
        RBNetEditorDialog.resize(320, 151)
        RBNetEditorDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(RBNetEditorDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.edtEndAgeCount = QtGui.QLineEdit(RBNetEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridlayout.addWidget(self.edtEndAgeCount, 3, 5, 1, 1)
        self.edtBegAgeCount = QtGui.QLineEdit(RBNetEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridlayout.addWidget(self.edtBegAgeCount, 3, 2, 1, 1)
        self.lblSex = QtGui.QLabel(RBNetEditorDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 2, 0, 1, 1)
        self.lblAgeSep = QtGui.QLabel(RBNetEditorDialog)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridlayout.addWidget(self.lblAgeSep, 3, 3, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(RBNetEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbBegAgeUnit, 3, 1, 1, 1)
        self.lblName = QtGui.QLabel(RBNetEditorDialog)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridlayout.addWidget(self.lblName, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(151, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 3, 6, 1, 1)
        self.lblAge = QtGui.QLabel(RBNetEditorDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 3, 0, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(RBNetEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbEndAgeUnit, 3, 4, 1, 1)
        self.cmbSex = QtGui.QComboBox(RBNetEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 2, 2, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(20, 71, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.lblCode = QtGui.QLabel(RBNetEditorDialog)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridlayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(RBNetEditorDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridlayout.addWidget(self.edtName, 1, 1, 1, 6)
        self.edtCode = QtGui.QLineEdit(RBNetEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridlayout.addWidget(self.edtCode, 0, 1, 1, 6)
        self.buttonBox = QtGui.QDialogButtonBox(RBNetEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 5, 0, 1, 7)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblName.setBuddy(self.edtName)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblCode.setBuddy(self.edtCode)

        self.retranslateUi(RBNetEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBNetEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBNetEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RBNetEditorDialog)
        RBNetEditorDialog.setTabOrder(self.edtCode, self.edtName)
        RBNetEditorDialog.setTabOrder(self.edtName, self.cmbSex)
        RBNetEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        RBNetEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        RBNetEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        RBNetEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)

    def retranslateUi(self, RBNetEditorDialog):
        RBNetEditorDialog.setWindowTitle(QtGui.QApplication.translate("RBNetEditorDialog", "ChangeMe!", None, QtGui.QApplication.UnicodeUTF8))
        self.edtEndAgeCount.setInputMask(QtGui.QApplication.translate("RBNetEditorDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtBegAgeCount.setInputMask(QtGui.QApplication.translate("RBNetEditorDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSex.setText(QtGui.QApplication.translate("RBNetEditorDialog", "&Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAgeSep.setText(QtGui.QApplication.translate("RBNetEditorDialog", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBegAgeUnit.setItemText(1, QtGui.QApplication.translate("RBNetEditorDialog", "Д", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBegAgeUnit.setItemText(2, QtGui.QApplication.translate("RBNetEditorDialog", "Н", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBegAgeUnit.setItemText(3, QtGui.QApplication.translate("RBNetEditorDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBegAgeUnit.setItemText(4, QtGui.QApplication.translate("RBNetEditorDialog", "Г", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("RBNetEditorDialog", "На&именование", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAge.setText(QtGui.QApplication.translate("RBNetEditorDialog", "&Возраст", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbEndAgeUnit.setItemText(1, QtGui.QApplication.translate("RBNetEditorDialog", "Д", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbEndAgeUnit.setItemText(2, QtGui.QApplication.translate("RBNetEditorDialog", "Н", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbEndAgeUnit.setItemText(3, QtGui.QApplication.translate("RBNetEditorDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbEndAgeUnit.setItemText(4, QtGui.QApplication.translate("RBNetEditorDialog", "Г", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(1, QtGui.QApplication.translate("RBNetEditorDialog", "М", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(2, QtGui.QApplication.translate("RBNetEditorDialog", "Ж", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("RBNetEditorDialog", "&Код", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    RBNetEditorDialog = QtGui.QDialog()
    ui = Ui_RBNetEditorDialog()
    ui.setupUi(RBNetEditorDialog)
    RBNetEditorDialog.show()
    sys.exit(app.exec_())

