# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\client\RefBooks\EventType\EventFilterDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventFilterDialog(object):
    def setupUi(self, EventFilterDialog):
        EventFilterDialog.setObjectName(_fromUtf8("EventFilterDialog"))
        EventFilterDialog.resize(412, 390)
        self.gridlayout = QtGui.QGridLayout(EventFilterDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.buttonBox = QtGui.QDialogButtonBox(EventFilterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 20, 0, 1, 3)
        self.lbRegionalCode = QtGui.QLabel(EventFilterDialog)
        self.lbRegionalCode.setObjectName(_fromUtf8("lbRegionalCode"))
        self.gridlayout.addWidget(self.lbRegionalCode, 4, 0, 1, 1)
        self.edtAge = QtGui.QLineEdit(EventFilterDialog)
        self.edtAge.setObjectName(_fromUtf8("edtAge"))
        self.gridlayout.addWidget(self.edtAge, 10, 1, 1, 2)
        self.edtPeriod = QtGui.QLineEdit(EventFilterDialog)
        self.edtPeriod.setObjectName(_fromUtf8("edtPeriod"))
        self.gridlayout.addWidget(self.edtPeriod, 11, 1, 1, 2)
        self.edtEGISZ = QtGui.QLineEdit(EventFilterDialog)
        self.edtEGISZ.setObjectName(_fromUtf8("edtEGISZ"))
        self.gridlayout.addWidget(self.edtEGISZ, 3, 1, 1, 2)
        self.lbMedicalAidKind = QtGui.QLabel(EventFilterDialog)
        self.lbMedicalAidKind.setObjectName(_fromUtf8("lbMedicalAidKind"))
        self.gridlayout.addWidget(self.lbMedicalAidKind, 7, 0, 1, 1)
        self.lbEGISZ = QtGui.QLabel(EventFilterDialog)
        self.lbEGISZ.setObjectName(_fromUtf8("lbEGISZ"))
        self.gridlayout.addWidget(self.lbEGISZ, 3, 0, 1, 1)
        self.cmbPurpose = CRBComboBox(EventFilterDialog)
        self.cmbPurpose.setObjectName(_fromUtf8("cmbPurpose"))
        self.gridlayout.addWidget(self.cmbPurpose, 5, 1, 1, 2)
        self.lbProfile = QtGui.QLabel(EventFilterDialog)
        self.lbProfile.setObjectName(_fromUtf8("lbProfile"))
        self.gridlayout.addWidget(self.lbProfile, 6, 0, 1, 1)
        self.cmbProfile = CRBComboBox(EventFilterDialog)
        self.cmbProfile.setObjectName(_fromUtf8("cmbProfile"))
        self.cmbProfile.addItem(_fromUtf8(""))
        self.cmbProfile.addItem(_fromUtf8(""))
        self.cmbProfile.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbProfile, 6, 1, 1, 2)
        self.lbSex = QtGui.QLabel(EventFilterDialog)
        self.lbSex.setObjectName(_fromUtf8("lbSex"))
        self.gridlayout.addWidget(self.lbSex, 9, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(EventFilterDialog)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridlayout.addWidget(self.edtRegionalCode, 4, 1, 1, 2)
        self.lbMedicalAidType = QtGui.QLabel(EventFilterDialog)
        self.lbMedicalAidType.setObjectName(_fromUtf8("lbMedicalAidType"))
        self.gridlayout.addWidget(self.lbMedicalAidType, 8, 0, 1, 1)
        self.cmbMedicalAidKind = CRBComboBox(EventFilterDialog)
        self.cmbMedicalAidKind.setObjectName(_fromUtf8("cmbMedicalAidKind"))
        self.cmbMedicalAidKind.addItem(_fromUtf8(""))
        self.cmbMedicalAidKind.addItem(_fromUtf8(""))
        self.cmbMedicalAidKind.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbMedicalAidKind, 7, 1, 1, 2)
        self.lbMaxDuration = QtGui.QLabel(EventFilterDialog)
        self.lbMaxDuration.setObjectName(_fromUtf8("lbMaxDuration"))
        self.gridlayout.addWidget(self.lbMaxDuration, 18, 0, 1, 1)
        self.lbMinDuration = QtGui.QLabel(EventFilterDialog)
        self.lbMinDuration.setObjectName(_fromUtf8("lbMinDuration"))
        self.gridlayout.addWidget(self.lbMinDuration, 17, 0, 1, 1)
        self.cmbMedicalAidType = CRBComboBox(EventFilterDialog)
        self.cmbMedicalAidType.setObjectName(_fromUtf8("cmbMedicalAidType"))
        self.gridlayout.addWidget(self.cmbMedicalAidType, 8, 1, 1, 2)
        self.edtMinDuration = QtGui.QLineEdit(EventFilterDialog)
        self.edtMinDuration.setObjectName(_fromUtf8("edtMinDuration"))
        self.gridlayout.addWidget(self.edtMinDuration, 17, 1, 1, 2)
        self.lbCode = QtGui.QLabel(EventFilterDialog)
        self.lbCode.setObjectName(_fromUtf8("lbCode"))
        self.gridlayout.addWidget(self.lbCode, 1, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(EventFilterDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.gridlayout.addWidget(self.cmbSex, 9, 1, 1, 2)
        self.lbAge = QtGui.QLabel(EventFilterDialog)
        self.lbAge.setObjectName(_fromUtf8("lbAge"))
        self.gridlayout.addWidget(self.lbAge, 10, 0, 1, 1)
        self.lbPeriod = QtGui.QLabel(EventFilterDialog)
        self.lbPeriod.setObjectName(_fromUtf8("lbPeriod"))
        self.gridlayout.addWidget(self.lbPeriod, 11, 0, 1, 1)
        self.edtMaxDuration = QtGui.QLineEdit(EventFilterDialog)
        self.edtMaxDuration.setObjectName(_fromUtf8("edtMaxDuration"))
        self.gridlayout.addWidget(self.edtMaxDuration, 18, 1, 1, 2)
        self.edtName = QtGui.QLineEdit(EventFilterDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridlayout.addWidget(self.edtName, 2, 1, 1, 2)
        self.lbPurpose = QtGui.QLabel(EventFilterDialog)
        self.lbPurpose.setObjectName(_fromUtf8("lbPurpose"))
        self.gridlayout.addWidget(self.lbPurpose, 5, 0, 1, 1)
        self.lbSingleInPeriod = QtGui.QLabel(EventFilterDialog)
        self.lbSingleInPeriod.setObjectName(_fromUtf8("lbSingleInPeriod"))
        self.gridlayout.addWidget(self.lbSingleInPeriod, 16, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 19, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(EventFilterDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridlayout.addWidget(self.edtCode, 1, 1, 1, 2)
        self.cmbSingleInPeriod = QtGui.QComboBox(EventFilterDialog)
        self.cmbSingleInPeriod.setObjectName(_fromUtf8("cmbSingleInPeriod"))
        self.gridlayout.addWidget(self.cmbSingleInPeriod, 16, 1, 1, 2)
        self.lbName = QtGui.QLabel(EventFilterDialog)
        self.lbName.setObjectName(_fromUtf8("lbName"))
        self.gridlayout.addWidget(self.lbName, 2, 0, 1, 1)
        self.lbEGISZ.setBuddy(self.edtEGISZ)
        self.lbProfile.setBuddy(self.cmbProfile)
        self.lbSex.setBuddy(self.cmbMedicalAidType)
        self.lbMedicalAidType.setBuddy(self.cmbMedicalAidType)
        self.lbCode.setBuddy(self.edtCode)
        self.lbAge.setBuddy(self.edtAge)
        self.lbPeriod.setBuddy(self.edtPeriod)
        self.lbName.setBuddy(self.edtName)

        self.retranslateUi(EventFilterDialog)
        self.cmbProfile.setCurrentIndex(-1)
        self.cmbMedicalAidKind.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), EventFilterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EventFilterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EventFilterDialog)
        EventFilterDialog.setTabOrder(self.edtCode, self.edtAge)
        EventFilterDialog.setTabOrder(self.edtAge, self.edtPeriod)
        EventFilterDialog.setTabOrder(self.edtPeriod, self.buttonBox)

    def retranslateUi(self, EventFilterDialog):
        EventFilterDialog.setWindowTitle(_translate("EventFilterDialog", "Фильтр событий", None))
        self.lbRegionalCode.setText(_translate("EventFilterDialog", "Региональный код", None))
        self.lbMedicalAidKind.setText(_translate("EventFilterDialog", "Вид помощи", None))
        self.lbEGISZ.setText(_translate("EventFilterDialog", "&Код ЕГИСЗ", None))
        self.lbProfile.setText(_translate("EventFilterDialog", "&Профиль", None))
        self.cmbProfile.setItemText(0, _translate("EventFilterDialog", "не задано", None))
        self.cmbProfile.setItemText(1, _translate("EventFilterDialog", "Нет", None))
        self.cmbProfile.setItemText(2, _translate("EventFilterDialog", "Да", None))
        self.lbSex.setText(_translate("EventFilterDialog", "Пол", None))
        self.lbMedicalAidType.setText(_translate("EventFilterDialog", "Тип помощи", None))
        self.cmbMedicalAidKind.setItemText(0, _translate("EventFilterDialog", "не задано", None))
        self.cmbMedicalAidKind.setItemText(1, _translate("EventFilterDialog", "Не активна", None))
        self.cmbMedicalAidKind.setItemText(2, _translate("EventFilterDialog", "Активна", None))
        self.lbMaxDuration.setText(_translate("EventFilterDialog", "Макс.длительность", None))
        self.lbMinDuration.setText(_translate("EventFilterDialog", "Мин.длительность", None))
        self.lbCode.setText(_translate("EventFilterDialog", "&Код", None))
        self.lbAge.setText(_translate("EventFilterDialog", "Возраст", None))
        self.lbPeriod.setText(_translate("EventFilterDialog", "Период", None))
        self.lbPurpose.setText(_translate("EventFilterDialog", "Назначение", None))
        self.lbSingleInPeriod.setText(_translate("EventFilterDialog", "Раз в", None))
        self.lbName.setText(_translate("EventFilterDialog", "&Наименование", None))

from library.crbcombobox import CRBComboBox
