# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBVisitTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(484, 334)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtNewServicePrefix = QtGui.QLineEdit(self.tabMain)
        self.edtNewServicePrefix.setEnabled(False)
        self.edtNewServicePrefix.setObjectName(_fromUtf8("edtNewServicePrefix"))
        self.gridLayout_2.addWidget(self.edtNewServicePrefix, 6, 1, 1, 1)
        self.rbModifyByRegExp = QtGui.QRadioButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbModifyByRegExp.sizePolicy().hasHeightForWidth())
        self.rbModifyByRegExp.setSizePolicy(sizePolicy)
        self.rbModifyByRegExp.setObjectName(_fromUtf8("rbModifyByRegExp"))
        self.gridLayout_2.addWidget(self.rbModifyByRegExp, 7, 0, 1, 1)
        self.rbRemoveService = QtGui.QRadioButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbRemoveService.sizePolicy().hasHeightForWidth())
        self.rbRemoveService.setSizePolicy(sizePolicy)
        self.rbRemoveService.setObjectName(_fromUtf8("rbRemoveService"))
        self.gridLayout_2.addWidget(self.rbRemoveService, 4, 0, 1, 1)
        self.rbModifyService = QtGui.QRadioButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbModifyService.sizePolicy().hasHeightForWidth())
        self.rbModifyService.setSizePolicy(sizePolicy)
        self.rbModifyService.setObjectName(_fromUtf8("rbModifyService"))
        self.gridLayout_2.addWidget(self.rbModifyService, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.rbReplaceService = QtGui.QRadioButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbReplaceService.sizePolicy().hasHeightForWidth())
        self.rbReplaceService.setSizePolicy(sizePolicy)
        self.rbReplaceService.setObjectName(_fromUtf8("rbReplaceService"))
        self.gridLayout_2.addWidget(self.rbReplaceService, 5, 0, 1, 1)
        self.rbNoModifyService = QtGui.QRadioButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbNoModifyService.sizePolicy().hasHeightForWidth())
        self.rbNoModifyService.setSizePolicy(sizePolicy)
        self.rbNoModifyService.setObjectName(_fromUtf8("rbNoModifyService"))
        self.gridLayout_2.addWidget(self.rbNoModifyService, 3, 0, 1, 1)
        self.edtNewServiceName = QtGui.QLineEdit(self.tabMain)
        self.edtNewServiceName.setEnabled(False)
        self.edtNewServiceName.setObjectName(_fromUtf8("edtNewServiceName"))
        self.gridLayout_2.addWidget(self.edtNewServiceName, 5, 1, 1, 1)
        self.btnRegExpTest = QtGui.QPushButton(self.tabMain)
        self.btnRegExpTest.setEnabled(False)
        self.btnRegExpTest.setObjectName(_fromUtf8("btnRegExpTest"))
        self.gridLayout_2.addWidget(self.btnRegExpTest, 7, 2, 1, 1)
        self.edtRegExp = QtGui.QPlainTextEdit(self.tabMain)
        self.edtRegExp.setEnabled(False)
        self.edtRegExp.setObjectName(_fromUtf8("edtRegExp"))
        self.gridLayout_2.addWidget(self.edtRegExp, 7, 1, 2, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout_2.addWidget(self.lblRegionalCode, 2, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 0, 1, 1, 2)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 1, 1, 1, 2)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout_2.addWidget(self.edtRegionalCode, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblName.setBuddy(self.edtName)
        self.lblCode.setBuddy(self.edtCode)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.rbReplaceService, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtNewServiceName.setEnabled)
        QtCore.QObject.connect(self.rbModifyService, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtNewServicePrefix.setEnabled)
        QtCore.QObject.connect(self.rbModifyByRegExp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnRegExpTest.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QObject.connect(self.rbModifyByRegExp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtRegExp.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.rbNoModifyService)
        ItemEditorDialog.setTabOrder(self.rbNoModifyService, self.rbRemoveService)
        ItemEditorDialog.setTabOrder(self.rbRemoveService, self.rbReplaceService)
        ItemEditorDialog.setTabOrder(self.rbReplaceService, self.edtNewServiceName)
        ItemEditorDialog.setTabOrder(self.edtNewServiceName, self.rbModifyService)
        ItemEditorDialog.setTabOrder(self.rbModifyService, self.edtNewServicePrefix)
        ItemEditorDialog.setTabOrder(self.edtNewServicePrefix, self.rbModifyByRegExp)
        ItemEditorDialog.setTabOrder(self.rbModifyByRegExp, self.edtRegExp)
        ItemEditorDialog.setTabOrder(self.edtRegExp, self.btnRegExpTest)
        ItemEditorDialog.setTabOrder(self.btnRegExpTest, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.rbModifyByRegExp.setText(_translate("ItemEditorDialog", "Регулярное выражение", None))
        self.rbRemoveService.setText(_translate("ItemEditorDialog", "Удаляет услугу", None))
        self.rbModifyService.setText(_translate("ItemEditorDialog", "Изменяет префикс кода услуги", None))
        self.rbReplaceService.setText(_translate("ItemEditorDialog", "Заменяет код услуги на", None))
        self.rbNoModifyService.setText(_translate("ItemEditorDialog", "Не меняет услугу", None))
        self.btnRegExpTest.setText(_translate("ItemEditorDialog", "Испытание", None))
        self.edtRegExp.setToolTip(_translate("ItemEditorDialog", "<html><head/><body><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Регулярное выражение задаётся в виде<br/>/</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">искомое</span><span style=\" font-family:\'MS Shell Dlg 2\';\">/</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">заменяющее</span><span style=\" font-family:\'MS Shell Dlg 2\';\">/<br/>при этом используются регулярные выражения Qt.</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Можно задать несколько выражений, по выражению на строку. В этом случае делаются последовательные попытки замены, после первой успешной замены попытки прекращаются.</span></p></body></html>", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Региональный код", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "&Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "&Идентификация", None))

from library.InDocTable import CInDocTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

