# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\RefBooks\AppointmentPurpose\RBAppointmentPurposeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBAppointmentPurposeEditorDialog(object):
    def setupUi(self, RBAppointmentPurposeEditorDialog):
        RBAppointmentPurposeEditorDialog.setObjectName(_fromUtf8("RBAppointmentPurposeEditorDialog"))
        RBAppointmentPurposeEditorDialog.resize(438, 347)
        RBAppointmentPurposeEditorDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(RBAppointmentPurposeEditorDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblCode = QtGui.QLabel(RBAppointmentPurposeEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(RBAppointmentPurposeEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 1, 1, 1)
        self.lblName = QtGui.QLabel(RBAppointmentPurposeEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(RBAppointmentPurposeEditorDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(RBAppointmentPurposeEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(RBAppointmentPurposeEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabClient = QtGui.QWidget()
        self.tabClient.setObjectName(_fromUtf8("tabClient"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabClient)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblSex = QtGui.QLabel(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout_2.addWidget(self.lblSex, 0, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbSex, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(321, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 5)
        self.lblAge = QtGui.QLabel(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout_2.addWidget(self.lblAge, 1, 0, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbBegAgeUnit, 1, 1, 1, 1)
        self.edtBegAgeCount = QtGui.QLineEdit(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout_2.addWidget(self.edtBegAgeCount, 1, 2, 1, 1)
        self.lblAgeSep = QtGui.QLabel(self.tabClient)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout_2.addWidget(self.lblAgeSep, 1, 3, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbEndAgeUnit, 1, 4, 1, 1)
        self.edtEndAgeCount = QtGui.QLineEdit(self.tabClient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout_2.addWidget(self.edtEndAgeCount, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 221, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.edtBegAgeCount.raise_()
        self.cmbBegAgeUnit.raise_()
        self.lblAge.raise_()
        self.edtEndAgeCount.raise_()
        self.lblSex.raise_()
        self.cmbSex.raise_()
        self.cmbEndAgeUnit.raise_()
        self.lblAgeSep.raise_()
        self.tabWidget.addTab(self.tabClient, _fromUtf8(""))
        self.tabEnablement = QtGui.QWidget()
        self.tabEnablement.setObjectName(_fromUtf8("tabEnablement"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabEnablement)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chkEnablePrimaryRecord = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnablePrimaryRecord.setChecked(True)
        self.chkEnablePrimaryRecord.setObjectName(_fromUtf8("chkEnablePrimaryRecord"))
        self.gridLayout_3.addWidget(self.chkEnablePrimaryRecord, 0, 0, 1, 2)
        self.chkForExternalSchedule = QtGui.QCheckBox(self.tabEnablement)
        self.chkForExternalSchedule.setObjectName(_fromUtf8("chkForExternalSchedule"))
        self.gridLayout_3.addWidget(self.chkForExternalSchedule, 8, 0, 1, 2)
        self.cmbRequiredReferralType = QtGui.QComboBox(self.tabEnablement)
        self.cmbRequiredReferralType.setObjectName(_fromUtf8("cmbRequiredReferralType"))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.cmbRequiredReferralType.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbRequiredReferralType, 7, 1, 1, 1)
        self.lblRequiredReferralType = QtGui.QLabel(self.tabEnablement)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRequiredReferralType.sizePolicy().hasHeightForWidth())
        self.lblRequiredReferralType.setSizePolicy(sizePolicy)
        self.lblRequiredReferralType.setObjectName(_fromUtf8("lblRequiredReferralType"))
        self.gridLayout_3.addWidget(self.lblRequiredReferralType, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 104, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 10, 1, 1, 1)
        self.chkEnableRecordViaInternet = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnableRecordViaInternet.setChecked(True)
        self.chkEnableRecordViaInternet.setObjectName(_fromUtf8("chkEnableRecordViaInternet"))
        self.gridLayout_3.addWidget(self.chkEnableRecordViaInternet, 5, 0, 1, 2)
        self.chkEnableRecordViaCallCenter = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnableRecordViaCallCenter.setChecked(True)
        self.chkEnableRecordViaCallCenter.setObjectName(_fromUtf8("chkEnableRecordViaCallCenter"))
        self.gridLayout_3.addWidget(self.chkEnableRecordViaCallCenter, 4, 0, 1, 2)
        self.chkEnableRecordViaInfomat = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnableRecordViaInfomat.setChecked(True)
        self.chkEnableRecordViaInfomat.setObjectName(_fromUtf8("chkEnableRecordViaInfomat"))
        self.gridLayout_3.addWidget(self.chkEnableRecordViaInfomat, 3, 0, 1, 2)
        self.chkEnableConsultancyRecord = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnableConsultancyRecord.setChecked(True)
        self.chkEnableConsultancyRecord.setObjectName(_fromUtf8("chkEnableConsultancyRecord"))
        self.gridLayout_3.addWidget(self.chkEnableConsultancyRecord, 2, 0, 1, 2)
        self.chkEnableOwnRecord = QtGui.QCheckBox(self.tabEnablement)
        self.chkEnableOwnRecord.setChecked(True)
        self.chkEnableOwnRecord.setObjectName(_fromUtf8("chkEnableOwnRecord"))
        self.gridLayout_3.addWidget(self.chkEnableOwnRecord, 1, 0, 1, 2)
        self.line = QtGui.QFrame(self.tabEnablement)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 6, 0, 1, 2)
        self.chkRequireClientAttach = QtGui.QCheckBox(self.tabEnablement)
        self.chkRequireClientAttach.setChecked(True)
        self.chkRequireClientAttach.setObjectName(_fromUtf8("chkRequireClientAttach"))
        self.gridLayout_3.addWidget(self.chkRequireClientAttach, 9, 0, 1, 2)
        self.tabWidget.addTab(self.tabEnablement, _fromUtf8(""))
        self.tabFeatures = QtGui.QWidget()
        self.tabFeatures.setObjectName(_fromUtf8("tabFeatures"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabFeatures)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(20, 250, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 3, 1, 1, 1)
        self.cmbMedicalAidProfile = CRBComboBox(self.tabFeatures)
        self.cmbMedicalAidProfile.setObjectName(_fromUtf8("cmbMedicalAidProfile"))
        self.gridLayout_4.addWidget(self.cmbMedicalAidProfile, 1, 1, 1, 1)
        self.lblMedicalAidProfile = QtGui.QLabel(self.tabFeatures)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidProfile.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidProfile.setSizePolicy(sizePolicy)
        self.lblMedicalAidProfile.setObjectName(_fromUtf8("lblMedicalAidProfile"))
        self.gridLayout_4.addWidget(self.lblMedicalAidProfile, 1, 0, 1, 1)
        self.cmbFinance = CRBComboBox(self.tabFeatures)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_4.addWidget(self.cmbFinance, 2, 1, 1, 1)
        self.lblFinance = QtGui.QLabel(self.tabFeatures)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_4.addWidget(self.lblFinance, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabFeatures, _fromUtf8(""))
        self.tabServices = QtGui.QWidget()
        self.tabServices.setObjectName(_fromUtf8("tabServices"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabServices)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblServices = CInDocTableView(self.tabServices)
        self.tblServices.setObjectName(_fromUtf8("tblServices"))
        self.gridLayout_5.addWidget(self.tblServices, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabServices, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblRequiredReferralType.setBuddy(self.cmbRequiredReferralType)
        self.lblMedicalAidProfile.setBuddy(self.cmbMedicalAidProfile)
        self.lblFinance.setBuddy(self.cmbFinance)

        self.retranslateUi(RBAppointmentPurposeEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBAppointmentPurposeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBAppointmentPurposeEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RBAppointmentPurposeEditorDialog)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.edtCode, self.edtName)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.edtName, self.tabWidget)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.tabWidget, self.cmbSex)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.edtEndAgeCount, self.chkEnablePrimaryRecord)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnablePrimaryRecord, self.chkEnableOwnRecord)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnableOwnRecord, self.chkEnableConsultancyRecord)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnableConsultancyRecord, self.chkEnableRecordViaInfomat)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnableRecordViaInfomat, self.chkEnableRecordViaCallCenter)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnableRecordViaCallCenter, self.chkEnableRecordViaInternet)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkEnableRecordViaInternet, self.cmbRequiredReferralType)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbRequiredReferralType, self.chkForExternalSchedule)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkForExternalSchedule, self.chkRequireClientAttach)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.chkRequireClientAttach, self.cmbMedicalAidProfile)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbMedicalAidProfile, self.cmbFinance)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.cmbFinance, self.tblServices)
        RBAppointmentPurposeEditorDialog.setTabOrder(self.tblServices, self.buttonBox)

    def retranslateUi(self, RBAppointmentPurposeEditorDialog):
        RBAppointmentPurposeEditorDialog.setWindowTitle(_translate("RBAppointmentPurposeEditorDialog", "ChangeMe!", None))
        self.lblCode.setText(_translate("RBAppointmentPurposeEditorDialog", "&Код", None))
        self.lblName.setText(_translate("RBAppointmentPurposeEditorDialog", "&Наименование", None))
        self.lblSex.setText(_translate("RBAppointmentPurposeEditorDialog", "&Пол", None))
        self.cmbSex.setItemText(1, _translate("RBAppointmentPurposeEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("RBAppointmentPurposeEditorDialog", "Ж", None))
        self.lblAge.setText(_translate("RBAppointmentPurposeEditorDialog", "&Возраст", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("RBAppointmentPurposeEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("RBAppointmentPurposeEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("RBAppointmentPurposeEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("RBAppointmentPurposeEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("RBAppointmentPurposeEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("RBAppointmentPurposeEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("RBAppointmentPurposeEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("RBAppointmentPurposeEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("RBAppointmentPurposeEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("RBAppointmentPurposeEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("RBAppointmentPurposeEditorDialog", "000; ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClient), _translate("RBAppointmentPurposeEditorDialog", "Пациент", None))
        self.chkEnablePrimaryRecord.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись в &регистратуре", None))
        self.chkForExternalSchedule.setText(_translate("RBAppointmentPurposeEditorDialog", "Для отображения на стендовом расписании", None))
        self.cmbRequiredReferralType.setItemText(0, _translate("RBAppointmentPurposeEditorDialog", "не требуется", None))
        self.cmbRequiredReferralType.setItemText(1, _translate("RBAppointmentPurposeEditorDialog", "на госпитальную комиссию", None))
        self.cmbRequiredReferralType.setItemText(2, _translate("RBAppointmentPurposeEditorDialog", "на восстановительное лечение", None))
        self.cmbRequiredReferralType.setItemText(3, _translate("RBAppointmentPurposeEditorDialog", "на обследование", None))
        self.cmbRequiredReferralType.setItemText(4, _translate("RBAppointmentPurposeEditorDialog", "на консультацию", None))
        self.cmbRequiredReferralType.setItemText(5, _translate("RBAppointmentPurposeEditorDialog", "на исследование (типа МРТ/КТ)", None))
        self.lblRequiredReferralType.setText(_translate("RBAppointmentPurposeEditorDialog", "Направление", None))
        self.chkEnableRecordViaInternet.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись через &интернет", None))
        self.chkEnableRecordViaCallCenter.setToolTip(_translate("RBAppointmentPurposeEditorDialog", "Код должности 6000", None))
        self.chkEnableRecordViaCallCenter.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись через call-&центр", None))
        self.chkEnableRecordViaInfomat.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись через ин&фомат", None))
        self.chkEnableConsultancyRecord.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись для к&онсультации", None))
        self.chkEnableOwnRecord.setText(_translate("RBAppointmentPurposeEditorDialog", "Разрешена запись к &самому себе", None))
        self.chkRequireClientAttach.setToolTip(_translate("RBAppointmentPurposeEditorDialog", "Для записи через интернет и т.п. \n"
"требуется прикрепление пациента \n"
"или адрес в зоне обслуживания", None))
        self.chkRequireClientAttach.setText(_translate("RBAppointmentPurposeEditorDialog", "Для записи через интернет и т.п. требуется прикрепление пациента", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEnablement), _translate("RBAppointmentPurposeEditorDialog", "Разрешения", None))
        self.lblMedicalAidProfile.setText(_translate("RBAppointmentPurposeEditorDialog", "Профиль мед.помощи", None))
        self.lblFinance.setText(_translate("RBAppointmentPurposeEditorDialog", "Тип финансирования", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFeatures), _translate("RBAppointmentPurposeEditorDialog", "Особенности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServices), _translate("RBAppointmentPurposeEditorDialog", "Услуги", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
