# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/natkuch/s11/RefBooks/RBJobTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(515, 411)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(ItemEditorDialog)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabJobType = QtGui.QWidget()
        self.tabJobType.setObjectName(_fromUtf8("tabJobType"))
        self.gridLayout = QtGui.QGridLayout(self.tabJobType)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblActionDateChanger = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionDateChanger.sizePolicy().hasHeightForWidth())
        self.lblActionDateChanger.setSizePolicy(sizePolicy)
        self.lblActionDateChanger.setObjectName(_fromUtf8("lblActionDateChanger"))
        self.gridLayout.addWidget(self.lblActionDateChanger, 10, 0, 1, 1)
        self.cmbActionDateChanger = QtGui.QComboBox(self.tabJobType)
        self.cmbActionDateChanger.setObjectName(_fromUtf8("cmbActionDateChanger"))
        self.cmbActionDateChanger.addItem(_fromUtf8(""))
        self.cmbActionDateChanger.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActionDateChanger, 10, 1, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabJobType)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 1, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout.addWidget(self.lblRegionalCode, 2, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabJobType)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout.addWidget(self.edtRegionalCode, 2, 1, 1, 1)
        self.cmbActionStatusChanger = CActionStatusComboBox(self.tabJobType)
        self.cmbActionStatusChanger.setObjectName(_fromUtf8("cmbActionStatusChanger"))
        self.gridLayout.addWidget(self.cmbActionStatusChanger, 7, 1, 1, 1)
        self.lblActionPersonChanger = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionPersonChanger.sizePolicy().hasHeightForWidth())
        self.lblActionPersonChanger.setSizePolicy(sizePolicy)
        self.lblActionPersonChanger.setObjectName(_fromUtf8("lblActionPersonChanger"))
        self.gridLayout.addWidget(self.lblActionPersonChanger, 9, 0, 1, 1)
        self.cmbActionPersonChanger = QtGui.QComboBox(self.tabJobType)
        self.cmbActionPersonChanger.setObjectName(_fromUtf8("cmbActionPersonChanger"))
        self.cmbActionPersonChanger.addItem(_fromUtf8(""))
        self.cmbActionPersonChanger.addItem(_fromUtf8(""))
        self.cmbActionPersonChanger.addItem(_fromUtf8(""))
        self.cmbActionPersonChanger.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbActionPersonChanger, 9, 1, 1, 1)
        self.lblNote = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNote.sizePolicy().hasHeightForWidth())
        self.lblNote.setSizePolicy(sizePolicy)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 15, 0, 1, 1)
        self.lblActionStatusChanger = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionStatusChanger.sizePolicy().hasHeightForWidth())
        self.lblActionStatusChanger.setSizePolicy(sizePolicy)
        self.lblActionStatusChanger.setObjectName(_fromUtf8("lblActionStatusChanger"))
        self.gridLayout.addWidget(self.lblActionStatusChanger, 7, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabJobType)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 0, 1, 1)
        self.edtNote = QtGui.QTextEdit(self.tabJobType)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 15, 1, 2, 1)
        self.edtCapacity = QtGui.QSpinBox(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCapacity.sizePolicy().hasHeightForWidth())
        self.edtCapacity.setSizePolicy(sizePolicy)
        self.edtCapacity.setMinimum(1)
        self.edtCapacity.setProperty("value", 1)
        self.edtCapacity.setObjectName(_fromUtf8("edtCapacity"))
        self.gridLayout.addWidget(self.edtCapacity, 3, 1, 1, 1)
        self.lblCapacity = QtGui.QLabel(self.tabJobType)
        self.lblCapacity.setObjectName(_fromUtf8("lblCapacity"))
        self.gridLayout.addWidget(self.lblCapacity, 3, 0, 1, 1)
        self.lblListContext = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblListContext.sizePolicy().hasHeightForWidth())
        self.lblListContext.setSizePolicy(sizePolicy)
        self.lblListContext.setObjectName(_fromUtf8("lblListContext"))
        self.gridLayout.addWidget(self.lblListContext, 12, 0, 1, 1)
        self.edtListContext = QtGui.QLineEdit(self.tabJobType)
        self.edtListContext.setObjectName(_fromUtf8("edtListContext"))
        self.gridLayout.addWidget(self.edtListContext, 12, 1, 1, 1)
        self.lblTicketDuartion = QtGui.QLabel(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTicketDuartion.sizePolicy().hasHeightForWidth())
        self.lblTicketDuartion.setSizePolicy(sizePolicy)
        self.lblTicketDuartion.setObjectName(_fromUtf8("lblTicketDuartion"))
        self.gridLayout.addWidget(self.lblTicketDuartion, 11, 0, 1, 1)
        self.edtTicketDuration = QtGui.QSpinBox(self.tabJobType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTicketDuration.sizePolicy().hasHeightForWidth())
        self.edtTicketDuration.setSizePolicy(sizePolicy)
        self.edtTicketDuration.setObjectName(_fromUtf8("edtTicketDuration"))
        self.gridLayout.addWidget(self.edtTicketDuration, 11, 1, 1, 1)
        self.lblManualExecutionAssignments = QtGui.QLabel(self.tabJobType)
        self.lblManualExecutionAssignments.setObjectName(_fromUtf8("lblManualExecutionAssignments"))
        self.gridLayout.addWidget(self.lblManualExecutionAssignments, 8, 0, 1, 1)
        self.chkManualExecutionAssignments = QtGui.QCheckBox(self.tabJobType)
        self.chkManualExecutionAssignments.setText(_fromUtf8(""))
        self.chkManualExecutionAssignments.setObjectName(_fromUtf8("chkManualExecutionAssignments"))
        self.gridLayout.addWidget(self.chkManualExecutionAssignments, 8, 1, 1, 1)
        self.tabWidget.addTab(self.tabJobType, _fromUtf8(""))
        self.tabActionTypes = QtGui.QWidget()
        self.tabActionTypes.setObjectName(_fromUtf8("tabActionTypes"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabActionTypes)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblJobTypeActions = CInDocTableView(self.tabActionTypes)
        self.tblJobTypeActions.setObjectName(_fromUtf8("tblJobTypeActions"))
        self.verticalLayout_2.addWidget(self.tblJobTypeActions)
        self.tabWidget.addTab(self.tabActionTypes, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblActionDateChanger.setBuddy(self.cmbActionDateChanger)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblActionPersonChanger.setBuddy(self.cmbActionPersonChanger)
        self.lblNote.setBuddy(self.edtNote)
        self.lblActionStatusChanger.setBuddy(self.cmbActionStatusChanger)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblCapacity.setBuddy(self.edtCapacity)
        self.lblListContext.setBuddy(self.edtListContext)
        self.lblTicketDuartion.setBuddy(self.edtTicketDuration)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.edtCapacity)
        ItemEditorDialog.setTabOrder(self.edtCapacity, self.cmbActionStatusChanger)
        ItemEditorDialog.setTabOrder(self.cmbActionStatusChanger, self.chkManualExecutionAssignments)
        ItemEditorDialog.setTabOrder(self.chkManualExecutionAssignments, self.cmbActionPersonChanger)
        ItemEditorDialog.setTabOrder(self.cmbActionPersonChanger, self.cmbActionDateChanger)
        ItemEditorDialog.setTabOrder(self.cmbActionDateChanger, self.edtTicketDuration)
        ItemEditorDialog.setTabOrder(self.edtTicketDuration, self.edtListContext)
        ItemEditorDialog.setTabOrder(self.edtListContext, self.edtNote)
        ItemEditorDialog.setTabOrder(self.edtNote, self.tblJobTypeActions)
        ItemEditorDialog.setTabOrder(self.tblJobTypeActions, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "Тип работы", None))
        self.lblActionDateChanger.setText(_translate("ItemEditorDialog", "Модификатор &даты действия", None))
        self.cmbActionDateChanger.setItemText(0, _translate("ItemEditorDialog", "Не меняется", None))
        self.cmbActionDateChanger.setItemText(1, _translate("ItemEditorDialog", "Дата окончания", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Региональный код", None))
        self.lblActionPersonChanger.setText(_translate("ItemEditorDialog", "Модификатор &исполнителя действия", None))
        self.cmbActionPersonChanger.setItemText(0, _translate("ItemEditorDialog", "Не меняется", None))
        self.cmbActionPersonChanger.setItemText(1, _translate("ItemEditorDialog", "Пользователь", None))
        self.cmbActionPersonChanger.setItemText(2, _translate("ItemEditorDialog", "Назначивший действие", None))
        self.cmbActionPersonChanger.setItemText(3, _translate("ItemEditorDialog", "Ответственный за событие", None))
        self.lblNote.setText(_translate("ItemEditorDialog", "&Примечание", None))
        self.lblActionStatusChanger.setText(_translate("ItemEditorDialog", "Модификатор &статуса действия", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.edtCapacity.setToolTip(_translate("ItemEditorDialog", "<html><head/><body><p>Для групповых действий: максимальный размер группы</p><p>Для прочих: 1</p></body></html>", None))
        self.lblCapacity.setText(_translate("ItemEditorDialog", "&Ёмкость", None))
        self.lblListContext.setText(_translate("ItemEditorDialog", "Контекст &печати списка", None))
        self.lblTicketDuartion.setText(_translate("ItemEditorDialog", "&Длительность номерка", None))
        self.edtTicketDuration.setToolTip(_translate("ItemEditorDialog", "<html><head/><body><p>Длительность выполнения работы, в днях</p></body></html>", None))
        self.lblManualExecutionAssignments.setText(_translate("ItemEditorDialog", "Предлагать ручное выполнение назначений", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJobType), _translate("ItemEditorDialog", "Тип работы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActionTypes), _translate("ItemEditorDialog", "Действия", None))

from Events.ActionStatus import CActionStatusComboBox
from library.InDocTable import CInDocTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

