# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\HospitalBeds\HospitalizationTransferDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HospitalizationTransferDialog(object):
    def setupUi(self, HospitalizationTransferDialog):
        HospitalizationTransferDialog.setObjectName(_fromUtf8("HospitalizationTransferDialog"))
        HospitalizationTransferDialog.resize(531, 616)
        self.gridLayout = QtGui.QGridLayout(HospitalizationTransferDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblPerson = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 3, 0, 1, 1)
        self.cmbMKBResult = CRBComboBox(HospitalizationTransferDialog)
        self.cmbMKBResult.setObjectName(_fromUtf8("cmbMKBResult"))
        self.gridLayout.addWidget(self.cmbMKBResult, 8, 1, 1, 3)
        self.edtTime = QtGui.QTimeEdit(HospitalizationTransferDialog)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 4, 1, 1)
        self.lblMKBResult = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblMKBResult.setObjectName(_fromUtf8("lblMKBResult"))
        self.gridLayout.addWidget(self.lblMKBResult, 8, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(HospitalizationTransferDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 1, 1, 1, 4)
        self.lblDateTime = QtGui.QLabel(HospitalizationTransferDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateTime.sizePolicy().hasHeightForWidth())
        self.lblDateTime.setSizePolicy(sizePolicy)
        self.lblDateTime.setObjectName(_fromUtf8("lblDateTime"))
        self.gridLayout.addWidget(self.lblDateTime, 0, 0, 1, 1)
        self.lblMesSpecification = QtGui.QLabel(HospitalizationTransferDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMesSpecification.sizePolicy().hasHeightForWidth())
        self.lblMesSpecification.setSizePolicy(sizePolicy)
        self.lblMesSpecification.setObjectName(_fromUtf8("lblMesSpecification"))
        self.gridLayout.addWidget(self.lblMesSpecification, 10, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(HospitalizationTransferDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 3, 1, 1, 4)
        self.cmbDiseaseCharacter = CRBComboBox(HospitalizationTransferDialog)
        self.cmbDiseaseCharacter.setObjectName(_fromUtf8("cmbDiseaseCharacter"))
        self.gridLayout.addWidget(self.cmbDiseaseCharacter, 7, 1, 1, 3)
        self.line = QtGui.QFrame(HospitalizationTransferDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 12, 0, 1, 5)
        self.lblDiagnosis = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblDiagnosis.setEnabled(True)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.gridLayout.addWidget(self.lblDiagnosis, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 16, 0, 1, 1)
        self.lblMes = QtGui.QLabel(HospitalizationTransferDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMes.sizePolicy().hasHeightForWidth())
        self.lblMes.setSizePolicy(sizePolicy)
        self.lblMes.setObjectName(_fromUtf8("lblMes"))
        self.gridLayout.addWidget(self.lblMes, 9, 0, 1, 1)
        self.edtDiagnosis = CICDCodeEditEx(HospitalizationTransferDialog)
        self.edtDiagnosis.setEnabled(True)
        self.edtDiagnosis.setObjectName(_fromUtf8("edtDiagnosis"))
        self.gridLayout.addWidget(self.edtDiagnosis, 5, 1, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(HospitalizationTransferDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 17, 0, 1, 5)
        self.cmbMesSpecification = CRBComboBox(HospitalizationTransferDialog)
        self.cmbMesSpecification.setObjectName(_fromUtf8("cmbMesSpecification"))
        self.gridLayout.addWidget(self.cmbMesSpecification, 10, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(HospitalizationTransferDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.lblDiagnosisEnd = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblDiagnosisEnd.setEnabled(True)
        self.lblDiagnosisEnd.setObjectName(_fromUtf8("lblDiagnosisEnd"))
        self.gridLayout.addWidget(self.lblDiagnosisEnd, 6, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 8, 4, 1, 1)
        self.chkDropFeed = QtGui.QCheckBox(HospitalizationTransferDialog)
        self.chkDropFeed.setChecked(True)
        self.chkDropFeed.setObjectName(_fromUtf8("chkDropFeed"))
        self.gridLayout.addWidget(self.chkDropFeed, 13, 0, 1, 4)
        self.lblDiseaseCharacter = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblDiseaseCharacter.setObjectName(_fromUtf8("lblDiseaseCharacter"))
        self.gridLayout.addWidget(self.lblDiseaseCharacter, 7, 0, 1, 1)
        self.cmbMes = CMESComboBox(HospitalizationTransferDialog)
        self.cmbMes.setObjectName(_fromUtf8("cmbMes"))
        self.gridLayout.addWidget(self.cmbMes, 9, 1, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 7, 4, 1, 1)
        self.edtDiagnosisEnd = CICDCodeEditEx(HospitalizationTransferDialog)
        self.edtDiagnosisEnd.setEnabled(True)
        self.edtDiagnosisEnd.setObjectName(_fromUtf8("edtDiagnosisEnd"))
        self.gridLayout.addWidget(self.edtDiagnosisEnd, 6, 1, 1, 3)
        self.lblResultEvent = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblResultEvent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResultEvent.setObjectName(_fromUtf8("lblResultEvent"))
        self.gridLayout.addWidget(self.lblResultEvent, 11, 0, 1, 1)
        self.cmbResultEvent = CRBComboBox(HospitalizationTransferDialog)
        self.cmbResultEvent.setObjectName(_fromUtf8("cmbResultEvent"))
        self.cmbResultEvent.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbResultEvent, 11, 1, 1, 4)
        self.edtDate = CDateEdit(HospitalizationTransferDialog)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 1, 1, 2)
        self.chkDropPatron = QtGui.QCheckBox(HospitalizationTransferDialog)
        self.chkDropPatron.setObjectName(_fromUtf8("chkDropPatron"))
        self.gridLayout.addWidget(self.chkDropPatron, 14, 0, 1, 2)
        self.cmbExecPerson = CPersonComboBoxEx(HospitalizationTransferDialog)
        self.cmbExecPerson.setObjectName(_fromUtf8("cmbExecPerson"))
        self.gridLayout.addWidget(self.cmbExecPerson, 4, 1, 1, 4)
        self.lblExecPerson = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblExecPerson.setObjectName(_fromUtf8("lblExecPerson"))
        self.gridLayout.addWidget(self.lblExecPerson, 4, 0, 1, 1)
        self.lblHospitalBed = QtGui.QLabel(HospitalizationTransferDialog)
        self.lblHospitalBed.setObjectName(_fromUtf8("lblHospitalBed"))
        self.gridLayout.addWidget(self.lblHospitalBed, 2, 0, 1, 1)
        self.cmbHospitalBed = CHospitalBedFindComboBox(HospitalizationTransferDialog)
        self.cmbHospitalBed.setObjectName(_fromUtf8("cmbHospitalBed"))
        self.gridLayout.addWidget(self.cmbHospitalBed, 2, 1, 1, 4)
        self.lblMKBResult.setBuddy(self.cmbDiseaseCharacter)
        self.lblMesSpecification.setBuddy(self.cmbMesSpecification)
        self.lblDiagnosis.setBuddy(self.edtDiagnosisEnd)
        self.lblMes.setBuddy(self.cmbMes)
        self.lblDiagnosisEnd.setBuddy(self.edtDiagnosisEnd)
        self.lblDiseaseCharacter.setBuddy(self.cmbDiseaseCharacter)
        self.lblResultEvent.setBuddy(self.cmbResultEvent)

        self.retranslateUi(HospitalizationTransferDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), HospitalizationTransferDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), HospitalizationTransferDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(HospitalizationTransferDialog)
        HospitalizationTransferDialog.setTabOrder(self.edtDate, self.edtTime)
        HospitalizationTransferDialog.setTabOrder(self.edtTime, self.cmbOrgStructure)
        HospitalizationTransferDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        HospitalizationTransferDialog.setTabOrder(self.cmbPerson, self.cmbExecPerson)
        HospitalizationTransferDialog.setTabOrder(self.cmbExecPerson, self.edtDiagnosis)
        HospitalizationTransferDialog.setTabOrder(self.edtDiagnosis, self.edtDiagnosisEnd)
        HospitalizationTransferDialog.setTabOrder(self.edtDiagnosisEnd, self.cmbDiseaseCharacter)
        HospitalizationTransferDialog.setTabOrder(self.cmbDiseaseCharacter, self.cmbMKBResult)
        HospitalizationTransferDialog.setTabOrder(self.cmbMKBResult, self.cmbMes)
        HospitalizationTransferDialog.setTabOrder(self.cmbMes, self.cmbMesSpecification)
        HospitalizationTransferDialog.setTabOrder(self.cmbMesSpecification, self.cmbResultEvent)
        HospitalizationTransferDialog.setTabOrder(self.cmbResultEvent, self.chkDropFeed)
        HospitalizationTransferDialog.setTabOrder(self.chkDropFeed, self.chkDropPatron)
        HospitalizationTransferDialog.setTabOrder(self.chkDropPatron, self.buttonBox)

    def retranslateUi(self, HospitalizationTransferDialog):
        HospitalizationTransferDialog.setWindowTitle(_translate("HospitalizationTransferDialog", "Параметры перевода", None))
        self.lblPerson.setText(_translate("HospitalizationTransferDialog", "Переводящий врач", None))
        self.lblMKBResult.setText(_translate("HospitalizationTransferDialog", "Исход", None))
        self.lblDateTime.setText(_translate("HospitalizationTransferDialog", "Дата и время", None))
        self.lblMesSpecification.setText(_translate("HospitalizationTransferDialog", "Результат МЭС", None))
        self.lblDiagnosis.setText(_translate("HospitalizationTransferDialog", "Диагноз", None))
        self.lblMes.setText(_translate("HospitalizationTransferDialog", "МЭС", None))
        self.lblOrgStructure.setText(_translate("HospitalizationTransferDialog", "Подразделение", None))
        self.lblDiagnosisEnd.setText(_translate("HospitalizationTransferDialog", "Диагноз закл.", None))
        self.chkDropFeed.setText(_translate("HospitalizationTransferDialog", "Отменить питание после перевода", None))
        self.lblDiseaseCharacter.setText(_translate("HospitalizationTransferDialog", "Характер", None))
        self.lblResultEvent.setText(_translate("HospitalizationTransferDialog", "Результа&т", None))
        self.cmbResultEvent.setWhatsThis(_translate("HospitalizationTransferDialog", "результат осмотра", None))
        self.cmbResultEvent.setItemText(0, _translate("HospitalizationTransferDialog", "Результат", None))
        self.chkDropPatron.setText(_translate("HospitalizationTransferDialog", "Убрать лицо по уходу после перевода", None))
        self.lblExecPerson.setText(_translate("HospitalizationTransferDialog", "Лечащий врач", None))
        self.lblHospitalBed.setText(_translate("HospitalizationTransferDialog", "Койка", None))

from HospitalBeds.HospitalBedFindComboBox import CHospitalBedFindComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.MES.MESComboBox import CMESComboBox
from library.crbcombobox import CRBComboBox
