# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\HospitalBeds\HospitalizationEventDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HospitalizationEventDialog(object):
    def setupUi(self, HospitalizationEventDialog):
        HospitalizationEventDialog.setObjectName(_fromUtf8("HospitalizationEventDialog"))
        HospitalizationEventDialog.resize(686, 422)
        self.gridLayout = QtGui.QGridLayout(HospitalizationEventDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(HospitalizationEventDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabHospitalizationEvent = QtGui.QWidget()
        self.tabHospitalizationEvent.setObjectName(_fromUtf8("tabHospitalizationEvent"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabHospitalizationEvent)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblHospitalizationEvent = CClientsTableView(self.tabHospitalizationEvent)
        self.tblHospitalizationEvent.setObjectName(_fromUtf8("tblHospitalizationEvent"))
        self.vboxlayout.addWidget(self.tblHospitalizationEvent)
        self.tabWidget.addTab(self.tabHospitalizationEvent, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCompulsoryPolisSerial = QtGui.QLabel(self.tabSearch)
        self.lblCompulsoryPolisSerial.setObjectName(_fromUtf8("lblCompulsoryPolisSerial"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisSerial, 7, 9, 1, 1)
        self.lblSex = QtGui.QLabel(self.tabSearch)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout_2.addWidget(self.lblSex, 5, 5, 1, 1)
        self.chkFilterId = QtGui.QCheckBox(self.tabSearch)
        self.chkFilterId.setObjectName(_fromUtf8("chkFilterId"))
        self.gridLayout_2.addWidget(self.chkFilterId, 0, 0, 1, 2)
        self.cmbFilterAccountingSystem = CRBComboBox(self.tabSearch)
        self.cmbFilterAccountingSystem.setEnabled(False)
        self.cmbFilterAccountingSystem.setObjectName(_fromUtf8("cmbFilterAccountingSystem"))
        self.gridLayout_2.addWidget(self.cmbFilterAccountingSystem, 0, 3, 1, 13)
        self.edtFilterId = QtGui.QLineEdit(self.tabSearch)
        self.edtFilterId.setEnabled(False)
        self.edtFilterId.setMaxLength(16)
        self.edtFilterId.setObjectName(_fromUtf8("edtFilterId"))
        self.gridLayout_2.addWidget(self.edtFilterId, 1, 0, 1, 16)
        self.cmbFilterSex = QtGui.QComboBox(self.tabSearch)
        self.cmbFilterSex.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbFilterSex.setSizePolicy(sizePolicy)
        self.cmbFilterSex.setMinimumSize(QtCore.QSize(45, 0))
        self.cmbFilterSex.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbFilterSex, 5, 6, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnScan = QtGui.QPushButton(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScan.sizePolicy().hasHeightForWidth())
        self.btnScan.setSizePolicy(sizePolicy)
        self.btnScan.setMinimumSize(QtCore.QSize(100, 0))
        self.btnScan.setObjectName(_fromUtf8("btnScan"))
        self.horizontalLayout.addWidget(self.btnScan)
        self.btnApply = QtGui.QPushButton(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApply.sizePolicy().hasHeightForWidth())
        self.btnApply.setSizePolicy(sizePolicy)
        self.btnApply.setMinimumSize(QtCore.QSize(100, 0))
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout.addWidget(self.btnApply)
        self.btnReset = QtGui.QPushButton(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset.sizePolicy().hasHeightForWidth())
        self.btnReset.setSizePolicy(sizePolicy)
        self.btnReset.setMinimumSize(QtCore.QSize(100, 0))
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.horizontalLayout.addWidget(self.btnReset)
        self.btnRegistry = QtGui.QPushButton(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegistry.sizePolicy().hasHeightForWidth())
        self.btnRegistry.setSizePolicy(sizePolicy)
        self.btnRegistry.setMinimumSize(QtCore.QSize(100, 0))
        self.btnRegistry.setObjectName(_fromUtf8("btnRegistry"))
        self.horizontalLayout.addWidget(self.btnRegistry)
        self.btnClose = QtGui.QPushButton(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setMinimumSize(QtCore.QSize(100, 0))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridLayout_2.addLayout(self.horizontalLayout, 14, 0, 1, 16)
        self.lblPolicyEndDate = QtGui.QLabel(self.tabSearch)
        self.lblPolicyEndDate.setObjectName(_fromUtf8("lblPolicyEndDate"))
        self.gridLayout_2.addWidget(self.lblPolicyEndDate, 8, 5, 1, 1)
        self.edtPolicyBegDate = CDateEdit(self.tabSearch)
        self.edtPolicyBegDate.setEnabled(False)
        self.edtPolicyBegDate.setMinimumSize(QtCore.QSize(94, 0))
        self.edtPolicyBegDate.setCalendarPopup(True)
        self.edtPolicyBegDate.setObjectName(_fromUtf8("edtPolicyBegDate"))
        self.gridLayout_2.addWidget(self.edtPolicyBegDate, 8, 4, 1, 1)
        self.edtCompulsoryPolisNumber = QtGui.QLineEdit(self.tabSearch)
        self.edtCompulsoryPolisNumber.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCompulsoryPolisNumber.sizePolicy().hasHeightForWidth())
        self.edtCompulsoryPolisNumber.setSizePolicy(sizePolicy)
        self.edtCompulsoryPolisNumber.setObjectName(_fromUtf8("edtCompulsoryPolisNumber"))
        self.gridLayout_2.addWidget(self.edtCompulsoryPolisNumber, 7, 14, 1, 2)
        self.lblCompulsoryPolisNumber = QtGui.QLabel(self.tabSearch)
        self.lblCompulsoryPolisNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCompulsoryPolisNumber.setObjectName(_fromUtf8("lblCompulsoryPolisNumber"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisNumber, 7, 13, 1, 1)
        self.edtCompulsoryPolisSerial = CPolicySerialEdit(self.tabSearch)
        self.edtCompulsoryPolisSerial.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCompulsoryPolisSerial.sizePolicy().hasHeightForWidth())
        self.edtCompulsoryPolisSerial.setSizePolicy(sizePolicy)
        self.edtCompulsoryPolisSerial.setObjectName(_fromUtf8("edtCompulsoryPolisSerial"))
        self.gridLayout_2.addWidget(self.edtCompulsoryPolisSerial, 7, 10, 1, 3)
        self.cmbFilterPolicyKind = CRBComboBox(self.tabSearch)
        self.cmbFilterPolicyKind.setEnabled(False)
        self.cmbFilterPolicyKind.setObjectName(_fromUtf8("cmbFilterPolicyKind"))
        self.gridLayout_2.addWidget(self.cmbFilterPolicyKind, 8, 14, 1, 2)
        self.cmbCompulsoryPolisType = CRBComboBox(self.tabSearch)
        self.cmbCompulsoryPolisType.setEnabled(False)
        self.cmbCompulsoryPolisType.setObjectName(_fromUtf8("cmbCompulsoryPolisType"))
        self.gridLayout_2.addWidget(self.cmbCompulsoryPolisType, 7, 4, 1, 5)
        self.edtNumber = QtGui.QLineEdit(self.tabSearch)
        self.edtNumber.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNumber.sizePolicy().hasHeightForWidth())
        self.edtNumber.setSizePolicy(sizePolicy)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout_2.addWidget(self.edtNumber, 6, 14, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 13, 0, 1, 1)
        self.lblNumber = QtGui.QLabel(self.tabSearch)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout_2.addWidget(self.lblNumber, 6, 13, 1, 1)
        self.edtRightSerial = QtGui.QLineEdit(self.tabSearch)
        self.edtRightSerial.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRightSerial.sizePolicy().hasHeightForWidth())
        self.edtRightSerial.setSizePolicy(sizePolicy)
        self.edtRightSerial.setObjectName(_fromUtf8("edtRightSerial"))
        self.gridLayout_2.addWidget(self.edtRightSerial, 6, 12, 1, 1)
        self.edtLeftSerial = QtGui.QLineEdit(self.tabSearch)
        self.edtLeftSerial.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtLeftSerial.sizePolicy().hasHeightForWidth())
        self.edtLeftSerial.setSizePolicy(sizePolicy)
        self.edtLeftSerial.setObjectName(_fromUtf8("edtLeftSerial"))
        self.gridLayout_2.addWidget(self.edtLeftSerial, 6, 10, 1, 2)
        self.lblSerial = QtGui.QLabel(self.tabSearch)
        self.lblSerial.setObjectName(_fromUtf8("lblSerial"))
        self.gridLayout_2.addWidget(self.lblSerial, 6, 9, 1, 1)
        self.cmbDocType = CRBComboBox(self.tabSearch)
        self.cmbDocType.setEnabled(False)
        self.cmbDocType.setObjectName(_fromUtf8("cmbDocType"))
        self.gridLayout_2.addWidget(self.cmbDocType, 6, 4, 1, 5)
        self.chkFilterDocument = QtGui.QCheckBox(self.tabSearch)
        self.chkFilterDocument.setObjectName(_fromUtf8("chkFilterDocument"))
        self.gridLayout_2.addWidget(self.chkFilterDocument, 6, 0, 1, 4)
        self.edtBirthDate = CDateEdit(self.tabSearch)
        self.edtBirthDate.setCalendarPopup(True)
        self.edtBirthDate.setObjectName(_fromUtf8("edtBirthDate"))
        self.gridLayout_2.addWidget(self.edtBirthDate, 5, 4, 1, 1)
        self.lblBirthDate = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBirthDate.sizePolicy().hasHeightForWidth())
        self.lblBirthDate.setSizePolicy(sizePolicy)
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.gridLayout_2.addWidget(self.lblBirthDate, 5, 0, 1, 4)
        self.edtPatrName = QtGui.QLineEdit(self.tabSearch)
        self.edtPatrName.setObjectName(_fromUtf8("edtPatrName"))
        self.gridLayout_2.addWidget(self.edtPatrName, 4, 4, 1, 12)
        self.lblPatrName = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPatrName.sizePolicy().hasHeightForWidth())
        self.lblPatrName.setSizePolicy(sizePolicy)
        self.lblPatrName.setObjectName(_fromUtf8("lblPatrName"))
        self.gridLayout_2.addWidget(self.lblPatrName, 4, 0, 1, 2)
        self.edtFirstName = QtGui.QLineEdit(self.tabSearch)
        self.edtFirstName.setObjectName(_fromUtf8("edtFirstName"))
        self.gridLayout_2.addWidget(self.edtFirstName, 3, 4, 1, 12)
        self.lblFirstName = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFirstName.sizePolicy().hasHeightForWidth())
        self.lblFirstName.setSizePolicy(sizePolicy)
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.gridLayout_2.addWidget(self.lblFirstName, 3, 0, 1, 1)
        self.edtLastName = QtGui.QLineEdit(self.tabSearch)
        self.edtLastName.setObjectName(_fromUtf8("edtLastName"))
        self.gridLayout_2.addWidget(self.edtLastName, 2, 4, 1, 12)
        self.edtPolicyEndDate = CDateEdit(self.tabSearch)
        self.edtPolicyEndDate.setEnabled(False)
        self.edtPolicyEndDate.setMinimumSize(QtCore.QSize(94, 0))
        self.edtPolicyEndDate.setCalendarPopup(True)
        self.edtPolicyEndDate.setObjectName(_fromUtf8("edtPolicyEndDate"))
        self.gridLayout_2.addWidget(self.edtPolicyEndDate, 8, 6, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 7, 1, 1)
        self.lblPolicyKind = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPolicyKind.sizePolicy().hasHeightForWidth())
        self.lblPolicyKind.setSizePolicy(sizePolicy)
        self.lblPolicyKind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPolicyKind.setObjectName(_fromUtf8("lblPolicyKind"))
        self.gridLayout_2.addWidget(self.lblPolicyKind, 8, 10, 1, 4)
        self.cmbCompulsoryPolisCompany = CInsurerComboBox(self.tabSearch)
        self.cmbCompulsoryPolisCompany.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCompulsoryPolisCompany.sizePolicy().hasHeightForWidth())
        self.cmbCompulsoryPolisCompany.setSizePolicy(sizePolicy)
        self.cmbCompulsoryPolisCompany.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbCompulsoryPolisCompany.setObjectName(_fromUtf8("cmbCompulsoryPolisCompany"))
        self.gridLayout_2.addWidget(self.cmbCompulsoryPolisCompany, 9, 4, 1, 12)
        self.lblPolicyBegDate = QtGui.QLabel(self.tabSearch)
        self.lblPolicyBegDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPolicyBegDate.setObjectName(_fromUtf8("lblPolicyBegDate"))
        self.gridLayout_2.addWidget(self.lblPolicyBegDate, 8, 0, 1, 4)
        self.lblCompulsoryPolisCompany = QtGui.QLabel(self.tabSearch)
        self.lblCompulsoryPolisCompany.setObjectName(_fromUtf8("lblCompulsoryPolisCompany"))
        self.gridLayout_2.addWidget(self.lblCompulsoryPolisCompany, 9, 0, 1, 4)
        self.edtContact = QtGui.QLineEdit(self.tabSearch)
        self.edtContact.setObjectName(_fromUtf8("edtContact"))
        self.gridLayout_2.addWidget(self.edtContact, 10, 4, 2, 12)
        self.edtKey = QtGui.QLineEdit(self.tabSearch)
        self.edtKey.setEnabled(False)
        self.edtKey.setObjectName(_fromUtf8("edtKey"))
        self.gridLayout_2.addWidget(self.edtKey, 12, 4, 1, 12)
        self.chkKey = QtGui.QCheckBox(self.tabSearch)
        self.chkKey.setObjectName(_fromUtf8("chkKey"))
        self.gridLayout_2.addWidget(self.chkKey, 12, 0, 1, 4)
        self.lblContact = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContact.sizePolicy().hasHeightForWidth())
        self.lblContact.setSizePolicy(sizePolicy)
        self.lblContact.setObjectName(_fromUtf8("lblContact"))
        self.gridLayout_2.addWidget(self.lblContact, 10, 0, 1, 4)
        self.lblLastName = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLastName.sizePolicy().hasHeightForWidth())
        self.lblLastName.setSizePolicy(sizePolicy)
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.gridLayout_2.addWidget(self.lblLastName, 2, 0, 1, 4)
        self.chkFilterPolicy = QtGui.QCheckBox(self.tabSearch)
        self.chkFilterPolicy.setObjectName(_fromUtf8("chkFilterPolicy"))
        self.gridLayout_2.addWidget(self.chkFilterPolicy, 7, 0, 1, 4)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.lblCompulsoryPolisSerial.setBuddy(self.edtCompulsoryPolisSerial)
        self.lblCompulsoryPolisNumber.setBuddy(self.edtCompulsoryPolisNumber)
        self.lblFirstName.setBuddy(self.edtFirstName)
        self.lblCompulsoryPolisCompany.setBuddy(self.cmbCompulsoryPolisCompany)
        self.lblLastName.setBuddy(self.edtLastName)

        self.retranslateUi(HospitalizationEventDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtKey.setEnabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtContact.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbCompulsoryPolisCompany.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtPolicyBegDate.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtPolicyEndDate.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterPolicyKind.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFilterPolicy.setDisabled)
        QtCore.QObject.connect(self.chkFilterPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbCompulsoryPolisType.setEnabled)
        QtCore.QObject.connect(self.chkFilterPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCompulsoryPolisSerial.setEnabled)
        QtCore.QObject.connect(self.chkFilterPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCompulsoryPolisNumber.setEnabled)
        QtCore.QObject.connect(self.chkFilterDocument, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDocType.setEnabled)
        QtCore.QObject.connect(self.chkFilterDocument, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLeftSerial.setEnabled)
        QtCore.QObject.connect(self.chkFilterDocument, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtRightSerial.setEnabled)
        QtCore.QObject.connect(self.chkFilterDocument, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtNumber.setEnabled)
        QtCore.QObject.connect(self.chkFilterId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAccountingSystem.setEnabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFilterDocument.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbCompulsoryPolisType.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCompulsoryPolisSerial.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCompulsoryPolisNumber.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDocType.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLeftSerial.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtRightSerial.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtNumber.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBirthDate.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterSex.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtPatrName.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFirstName.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLastName.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterId.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkFilterId.setDisabled)
        QtCore.QObject.connect(self.chkKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAccountingSystem.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(HospitalizationEventDialog)
        HospitalizationEventDialog.setTabOrder(self.tblHospitalizationEvent, self.edtLastName)
        HospitalizationEventDialog.setTabOrder(self.edtLastName, self.edtFirstName)
        HospitalizationEventDialog.setTabOrder(self.edtFirstName, self.edtPatrName)
        HospitalizationEventDialog.setTabOrder(self.edtPatrName, self.edtBirthDate)
        HospitalizationEventDialog.setTabOrder(self.edtBirthDate, self.cmbDocType)
        HospitalizationEventDialog.setTabOrder(self.cmbDocType, self.edtLeftSerial)
        HospitalizationEventDialog.setTabOrder(self.edtLeftSerial, self.cmbCompulsoryPolisType)
        HospitalizationEventDialog.setTabOrder(self.cmbCompulsoryPolisType, self.edtCompulsoryPolisSerial)
        HospitalizationEventDialog.setTabOrder(self.edtCompulsoryPolisSerial, self.btnApply)
        HospitalizationEventDialog.setTabOrder(self.btnApply, self.btnReset)
        HospitalizationEventDialog.setTabOrder(self.btnReset, self.btnRegistry)
        HospitalizationEventDialog.setTabOrder(self.btnRegistry, self.btnClose)
        HospitalizationEventDialog.setTabOrder(self.btnClose, self.tabWidget)
        HospitalizationEventDialog.setTabOrder(self.tabWidget, self.chkFilterId)
        HospitalizationEventDialog.setTabOrder(self.chkFilterId, self.cmbFilterAccountingSystem)
        HospitalizationEventDialog.setTabOrder(self.cmbFilterAccountingSystem, self.edtFilterId)
        HospitalizationEventDialog.setTabOrder(self.edtFilterId, self.cmbFilterSex)
        HospitalizationEventDialog.setTabOrder(self.cmbFilterSex, self.edtPolicyBegDate)
        HospitalizationEventDialog.setTabOrder(self.edtPolicyBegDate, self.edtCompulsoryPolisNumber)
        HospitalizationEventDialog.setTabOrder(self.edtCompulsoryPolisNumber, self.chkFilterPolicy)
        HospitalizationEventDialog.setTabOrder(self.chkFilterPolicy, self.edtNumber)
        HospitalizationEventDialog.setTabOrder(self.edtNumber, self.edtRightSerial)
        HospitalizationEventDialog.setTabOrder(self.edtRightSerial, self.chkFilterDocument)
        HospitalizationEventDialog.setTabOrder(self.chkFilterDocument, self.edtPolicyEndDate)
        HospitalizationEventDialog.setTabOrder(self.edtPolicyEndDate, self.cmbFilterPolicyKind)
        HospitalizationEventDialog.setTabOrder(self.cmbFilterPolicyKind, self.cmbCompulsoryPolisCompany)
        HospitalizationEventDialog.setTabOrder(self.cmbCompulsoryPolisCompany, self.edtContact)
        HospitalizationEventDialog.setTabOrder(self.edtContact, self.chkKey)
        HospitalizationEventDialog.setTabOrder(self.chkKey, self.edtKey)

    def retranslateUi(self, HospitalizationEventDialog):
        HospitalizationEventDialog.setWindowTitle(_translate("HospitalizationEventDialog", "Госпитализация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospitalizationEvent), _translate("HospitalizationEventDialog", "Результат поиска", None))
        self.lblCompulsoryPolisSerial.setText(_translate("HospitalizationEventDialog", "Серия", None))
        self.lblSex.setText(_translate("HospitalizationEventDialog", "Пол", None))
        self.chkFilterId.setText(_translate("HospitalizationEventDialog", "Код", None))
        self.cmbFilterSex.setItemText(1, _translate("HospitalizationEventDialog", "М", None))
        self.cmbFilterSex.setItemText(2, _translate("HospitalizationEventDialog", "Ж", None))
        self.btnScan.setText(_translate("HospitalizationEventDialog", "Сканировать", None))
        self.btnApply.setText(_translate("HospitalizationEventDialog", "Искать", None))
        self.btnReset.setText(_translate("HospitalizationEventDialog", "Сбросить", None))
        self.btnRegistry.setText(_translate("HospitalizationEventDialog", "Регистрация (F9)", None))
        self.btnRegistry.setShortcut(_translate("HospitalizationEventDialog", "F9", None))
        self.btnClose.setText(_translate("HospitalizationEventDialog", "Закрыть", None))
        self.lblPolicyEndDate.setText(_translate("HospitalizationEventDialog", "по", None))
        self.edtPolicyBegDate.setDisplayFormat(_translate("HospitalizationEventDialog", "dd.MM.yyyy", None))
        self.lblCompulsoryPolisNumber.setText(_translate("HospitalizationEventDialog", "Номер", None))
        self.lblNumber.setText(_translate("HospitalizationEventDialog", "Номер", None))
        self.lblSerial.setText(_translate("HospitalizationEventDialog", "Серия", None))
        self.chkFilterDocument.setText(_translate("HospitalizationEventDialog", "Документ", None))
        self.edtBirthDate.setDisplayFormat(_translate("HospitalizationEventDialog", "dd.MM.yyyy", None))
        self.lblBirthDate.setText(_translate("HospitalizationEventDialog", "Дата рождения", None))
        self.lblPatrName.setText(_translate("HospitalizationEventDialog", "Отчество", None))
        self.lblFirstName.setText(_translate("HospitalizationEventDialog", "Имя", None))
        self.edtPolicyEndDate.setDisplayFormat(_translate("HospitalizationEventDialog", "dd.MM.yyyy", None))
        self.lblPolicyKind.setText(_translate("HospitalizationEventDialog", "Вид полиса", None))
        self.lblPolicyBegDate.setText(_translate("HospitalizationEventDialog", "с", None))
        self.lblCompulsoryPolisCompany.setText(_translate("HospitalizationEventDialog", "СМО", None))
        self.edtKey.setToolTip(_translate("HospitalizationEventDialog", "<html><head/><body><p>инициалы: ФИО<br/>инициалы и дата рождения: ФИОДДММГГ[ГГ]<br/>сокращение: Фам Им Отч<br/>сокращение и дата рождения: Фам Им Отч ДДММГГ[ГГ]</p></body></html>", None))
        self.chkKey.setText(_translate("HospitalizationEventDialog", "Поиск по ключу", None))
        self.lblContact.setText(_translate("HospitalizationEventDialog", "Контакт", None))
        self.lblLastName.setText(_translate("HospitalizationEventDialog", "Фамилия", None))
        self.chkFilterPolicy.setText(_translate("HospitalizationEventDialog", "Полис", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("HospitalizationEventDialog", "&Поиск", None))

from Orgs.OrgComboBox import CInsurerComboBox
from Registry.PolicySerialEdit import CPolicySerialEdit
from Registry.RegistryTable import CClientsTableView
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
