# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\HospitalBeds\HospitalBedFindComboBoxPopup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HospitalBedFindComboBoxPopup(object):
    def setupUi(self, HospitalBedFindComboBoxPopup):
        HospitalBedFindComboBoxPopup.setObjectName(_fromUtf8("HospitalBedFindComboBoxPopup"))
        HospitalBedFindComboBoxPopup.resize(403, 232)
        self.gridlayout = QtGui.QGridLayout(HospitalBedFindComboBoxPopup)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(HospitalBedFindComboBoxPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabHospitalBedFind = QtGui.QWidget()
        self.tabHospitalBedFind.setObjectName(_fromUtf8("tabHospitalBedFind"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabHospitalBedFind)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblHospitalBedFind = QtGui.QTreeView(self.tabHospitalBedFind)
        self.tblHospitalBedFind.setObjectName(_fromUtf8("tblHospitalBedFind"))
        self.tblHospitalBedFind.header().setVisible(False)
        self.vboxlayout.addWidget(self.tblHospitalBedFind)
        self.tabWidget.addTab(self.tabHospitalBedFind, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbTypeBed = CRBComboBox(self.tabSearch)
        self.cmbTypeBed.setObjectName(_fromUtf8("cmbTypeBed"))
        self.gridLayout.addWidget(self.cmbTypeBed, 3, 1, 1, 6)
        self.lblIsPermanentBed = QtGui.QLabel(self.tabSearch)
        self.lblIsPermanentBed.setObjectName(_fromUtf8("lblIsPermanentBed"))
        self.gridLayout.addWidget(self.lblIsPermanentBed, 4, 0, 1, 1)
        self.cmbIsPermanentBed = QtGui.QComboBox(self.tabSearch)
        self.cmbIsPermanentBed.setObjectName(_fromUtf8("cmbIsPermanentBed"))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.cmbIsPermanentBed.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbIsPermanentBed, 4, 1, 1, 6)
        spacerItem = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 3)
        self.edtAgeToBed = QtGui.QSpinBox(self.tabSearch)
        self.edtAgeToBed.setObjectName(_fromUtf8("edtAgeToBed"))
        self.gridLayout.addWidget(self.edtAgeToBed, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(33, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.lblHospitalBedProfile = QtGui.QLabel(self.tabSearch)
        self.lblHospitalBedProfile.setObjectName(_fromUtf8("lblHospitalBedProfile"))
        self.gridLayout.addWidget(self.lblHospitalBedProfile, 2, 0, 1, 1)
        self.lblOrgStructureBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructureBed.sizePolicy().hasHeightForWidth())
        self.lblOrgStructureBed.setSizePolicy(sizePolicy)
        self.lblOrgStructureBed.setObjectName(_fromUtf8("lblOrgStructureBed"))
        self.gridLayout.addWidget(self.lblOrgStructureBed, 0, 0, 1, 1)
        self.cmbOrgStructureBed = COrgStructureComboBox(self.tabSearch)
        self.cmbOrgStructureBed.setObjectName(_fromUtf8("cmbOrgStructureBed"))
        self.gridLayout.addWidget(self.cmbOrgStructureBed, 0, 1, 1, 6)
        self.lblSexBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSexBed.sizePolicy().hasHeightForWidth())
        self.lblSexBed.setSizePolicy(sizePolicy)
        self.lblSexBed.setObjectName(_fromUtf8("lblSexBed"))
        self.gridLayout.addWidget(self.lblSexBed, 1, 0, 1, 1)
        self.cmbSexBed = QtGui.QComboBox(self.tabSearch)
        self.cmbSexBed.setObjectName(_fromUtf8("cmbSexBed"))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.cmbSexBed.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSexBed, 1, 1, 1, 1)
        self.lblAgeBed = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeBed.sizePolicy().hasHeightForWidth())
        self.lblAgeBed.setSizePolicy(sizePolicy)
        self.lblAgeBed.setObjectName(_fromUtf8("lblAgeBed"))
        self.gridLayout.addWidget(self.lblAgeBed, 1, 2, 1, 1)
        self.cmbHospitalBedProfile = CRBComboBox(self.tabSearch)
        self.cmbHospitalBedProfile.setObjectName(_fromUtf8("cmbHospitalBedProfile"))
        self.gridLayout.addWidget(self.cmbHospitalBedProfile, 2, 1, 1, 6)
        self.lblTypeBed = QtGui.QLabel(self.tabSearch)
        self.lblTypeBed.setObjectName(_fromUtf8("lblTypeBed"))
        self.gridLayout.addWidget(self.lblTypeBed, 3, 0, 1, 1)
        self.edtAgeForBed = QtGui.QSpinBox(self.tabSearch)
        self.edtAgeForBed.setMaximum(150)
        self.edtAgeForBed.setObjectName(_fromUtf8("edtAgeForBed"))
        self.gridLayout.addWidget(self.edtAgeForBed, 1, 3, 1, 1)
        self.lblAgeTo = QtGui.QLabel(self.tabSearch)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.gridLayout.addWidget(self.lblAgeTo, 1, 4, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 3, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(HospitalBedFindComboBoxPopup)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HospitalBedFindComboBoxPopup)
        HospitalBedFindComboBoxPopup.setTabOrder(self.tabWidget, self.cmbOrgStructureBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbOrgStructureBed, self.cmbSexBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbSexBed, self.edtAgeForBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.edtAgeForBed, self.edtAgeToBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.edtAgeToBed, self.cmbHospitalBedProfile)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbHospitalBedProfile, self.cmbTypeBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbTypeBed, self.cmbIsPermanentBed)
        HospitalBedFindComboBoxPopup.setTabOrder(self.cmbIsPermanentBed, self.buttonBox)
        HospitalBedFindComboBoxPopup.setTabOrder(self.buttonBox, self.tblHospitalBedFind)

    def retranslateUi(self, HospitalBedFindComboBoxPopup):
        HospitalBedFindComboBoxPopup.setWindowTitle(_translate("HospitalBedFindComboBoxPopup", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospitalBedFind), _translate("HospitalBedFindComboBoxPopup", "Результат поиска", None))
        self.lblIsPermanentBed.setText(_translate("HospitalBedFindComboBoxPopup", "Штат", None))
        self.cmbIsPermanentBed.setItemText(0, _translate("HospitalBedFindComboBoxPopup", "Все", None))
        self.cmbIsPermanentBed.setItemText(1, _translate("HospitalBedFindComboBoxPopup", "Нет", None))
        self.cmbIsPermanentBed.setItemText(2, _translate("HospitalBedFindComboBoxPopup", "Да", None))
        self.lblHospitalBedProfile.setText(_translate("HospitalBedFindComboBoxPopup", "Профиль", None))
        self.lblOrgStructureBed.setText(_translate("HospitalBedFindComboBoxPopup", "Подразделение", None))
        self.lblSexBed.setText(_translate("HospitalBedFindComboBoxPopup", "Пол", None))
        self.cmbSexBed.setItemText(0, _translate("HospitalBedFindComboBoxPopup", "нет", None))
        self.cmbSexBed.setItemText(1, _translate("HospitalBedFindComboBoxPopup", "М", None))
        self.cmbSexBed.setItemText(2, _translate("HospitalBedFindComboBoxPopup", "Ж", None))
        self.lblAgeBed.setText(_translate("HospitalBedFindComboBoxPopup", "Возраст от", None))
        self.lblTypeBed.setText(_translate("HospitalBedFindComboBoxPopup", "Тип", None))
        self.lblAgeTo.setText(_translate("HospitalBedFindComboBoxPopup", "до", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("HospitalBedFindComboBoxPopup", "&Поиск", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.crbcombobox import CRBComboBox
