# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\HospitalBeds\PlanOperatingDayPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlanOperatingDayPage(object):
    def setupUi(self, PlanOperatingDayPage):
        PlanOperatingDayPage.setObjectName(_fromUtf8("PlanOperatingDayPage"))
        PlanOperatingDayPage.resize(962, 439)
        self.gridLayout = QtGui.QGridLayout(PlanOperatingDayPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(PlanOperatingDayPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edtOperatingPlanDate = CDateEdit(PlanOperatingDayPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOperatingPlanDate.sizePolicy().hasHeightForWidth())
        self.edtOperatingPlanDate.setSizePolicy(sizePolicy)
        self.edtOperatingPlanDate.setCalendarPopup(True)
        self.edtOperatingPlanDate.setObjectName(_fromUtf8("edtOperatingPlanDate"))
        self.horizontalLayout.addWidget(self.edtOperatingPlanDate)
        self.btnAddRecords = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnAddRecords.setObjectName(_fromUtf8("btnAddRecords"))
        self.horizontalLayout.addWidget(self.btnAddRecords)
        self.lblOrgStructureName = QtGui.QLabel(PlanOperatingDayPage)
        self.lblOrgStructureName.setText(_fromUtf8(""))
        self.lblOrgStructureName.setObjectName(_fromUtf8("lblOrgStructureName"))
        self.horizontalLayout.addWidget(self.lblOrgStructureName)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblLine = QtGui.QFrame(PlanOperatingDayPage)
        self.lblLine.setFrameShape(QtGui.QFrame.VLine)
        self.lblLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblLine.setObjectName(_fromUtf8("lblLine"))
        self.horizontalLayout_2.addWidget(self.lblLine)
        self.chkStrictDate = QtGui.QCheckBox(PlanOperatingDayPage)
        self.chkStrictDate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkStrictDate.setChecked(True)
        self.chkStrictDate.setObjectName(_fromUtf8("chkStrictDate"))
        self.horizontalLayout_2.addWidget(self.chkStrictDate)
        self.lblFilter1 = QtGui.QLabel(PlanOperatingDayPage)
        self.lblFilter1.setText(_fromUtf8(""))
        self.lblFilter1.setObjectName(_fromUtf8("lblFilter1"))
        self.horizontalLayout_2.addWidget(self.lblFilter1)
        self.lblActionStatus = QtGui.QLabel(PlanOperatingDayPage)
        self.lblActionStatus.setObjectName(_fromUtf8("lblActionStatus"))
        self.horizontalLayout_2.addWidget(self.lblActionStatus)
        self.cmbActionStatus = CActionStatusComboBox(PlanOperatingDayPage)
        self.cmbActionStatus.setMinimumSize(QtCore.QSize(125, 0))
        self.cmbActionStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbActionStatus.setObjectName(_fromUtf8("cmbActionStatus"))
        self.horizontalLayout_2.addWidget(self.cmbActionStatus)
        self.lblFilter2 = QtGui.QLabel(PlanOperatingDayPage)
        self.lblFilter2.setText(_fromUtf8(""))
        self.lblFilter2.setObjectName(_fromUtf8("lblFilter2"))
        self.horizontalLayout_2.addWidget(self.lblFilter2)
        self.btnReset = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.horizontalLayout_2.addWidget(self.btnReset)
        self.btnApply = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout_2.addWidget(self.btnApply)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 7)
        self.lblCreateDate = QtGui.QLabel(PlanOperatingDayPage)
        self.lblCreateDate.setText(_fromUtf8(""))
        self.lblCreateDate.setObjectName(_fromUtf8("lblCreateDate"))
        self.gridLayout.addWidget(self.lblCreateDate, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.btnOperatingDayPrint = CPrintButton(PlanOperatingDayPage)
        self.btnOperatingDayPrint.setObjectName(_fromUtf8("btnOperatingDayPrint"))
        self.gridLayout.addWidget(self.btnOperatingDayPrint, 2, 6, 1, 1)
        self.lblModifyPerson = QtGui.QLabel(PlanOperatingDayPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModifyPerson.sizePolicy().hasHeightForWidth())
        self.lblModifyPerson.setSizePolicy(sizePolicy)
        self.lblModifyPerson.setObjectName(_fromUtf8("lblModifyPerson"))
        self.gridLayout.addWidget(self.lblModifyPerson, 2, 2, 1, 1)
        self.lblModifyDate = QtGui.QLabel(PlanOperatingDayPage)
        self.lblModifyDate.setText(_fromUtf8(""))
        self.lblModifyDate.setObjectName(_fromUtf8("lblModifyDate"))
        self.gridLayout.addWidget(self.lblModifyDate, 2, 3, 1, 1)
        self.btnSave = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.gridLayout.addWidget(self.btnSave, 2, 7, 1, 1)
        self.tabWidget = QtGui.QTabWidget(PlanOperatingDayPage)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPlanOperatingDay = QtGui.QWidget()
        self.tabPlanOperatingDay.setObjectName(_fromUtf8("tabPlanOperatingDay"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabPlanOperatingDay)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblPlanOperatingDay = CPlanOperatingDayInDocTableView(self.tabPlanOperatingDay)
        self.tblPlanOperatingDay.setObjectName(_fromUtf8("tblPlanOperatingDay"))
        self.gridLayout_2.addWidget(self.tblPlanOperatingDay, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPlanOperatingDay, _fromUtf8(""))
        self.tabOutsideOperatingDay = QtGui.QWidget()
        self.tabOutsideOperatingDay.setObjectName(_fromUtf8("tabOutsideOperatingDay"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabOutsideOperatingDay)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblOutsideOperatingDay = CPlanOperatingDayInDocTableView(self.tabOutsideOperatingDay)
        self.tblOutsideOperatingDay.setObjectName(_fromUtf8("tblOutsideOperatingDay"))
        self.gridLayout_3.addWidget(self.tblOutsideOperatingDay, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOutsideOperatingDay, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 9)
        self.lblCreatePerson = QtGui.QLabel(PlanOperatingDayPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCreatePerson.sizePolicy().hasHeightForWidth())
        self.lblCreatePerson.setSizePolicy(sizePolicy)
        self.lblCreatePerson.setObjectName(_fromUtf8("lblCreatePerson"))
        self.gridLayout.addWidget(self.lblCreatePerson, 2, 0, 1, 1)
        self.btnClose = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 2, 8, 1, 1)
        self.btnSurgeryJournal = QtGui.QPushButton(PlanOperatingDayPage)
        self.btnSurgeryJournal.setObjectName(_fromUtf8("btnSurgeryJournal"))
        self.gridLayout.addWidget(self.btnSurgeryJournal, 2, 5, 1, 1)

        self.retranslateUi(PlanOperatingDayPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlanOperatingDayPage)
        PlanOperatingDayPage.setTabOrder(self.edtOperatingPlanDate, self.tabWidget)
        PlanOperatingDayPage.setTabOrder(self.tabWidget, self.tblPlanOperatingDay)
        PlanOperatingDayPage.setTabOrder(self.tblPlanOperatingDay, self.btnAddRecords)
        PlanOperatingDayPage.setTabOrder(self.btnAddRecords, self.btnSurgeryJournal)
        PlanOperatingDayPage.setTabOrder(self.btnSurgeryJournal, self.btnOperatingDayPrint)
        PlanOperatingDayPage.setTabOrder(self.btnOperatingDayPrint, self.btnSave)
        PlanOperatingDayPage.setTabOrder(self.btnSave, self.btnClose)
        PlanOperatingDayPage.setTabOrder(self.btnClose, self.tblOutsideOperatingDay)
        PlanOperatingDayPage.setTabOrder(self.tblOutsideOperatingDay, self.chkStrictDate)
        PlanOperatingDayPage.setTabOrder(self.chkStrictDate, self.cmbActionStatus)
        PlanOperatingDayPage.setTabOrder(self.cmbActionStatus, self.btnReset)
        PlanOperatingDayPage.setTabOrder(self.btnReset, self.btnApply)

    def retranslateUi(self, PlanOperatingDayPage):
        PlanOperatingDayPage.setWindowTitle(_translate("PlanOperatingDayPage", "План операционного дня", None))
        self.label.setText(_translate("PlanOperatingDayPage", "на дату", None))
        self.edtOperatingPlanDate.setDisplayFormat(_translate("PlanOperatingDayPage", "dd.MM.yyyy", None))
        self.btnAddRecords.setText(_translate("PlanOperatingDayPage", "Добавить", None))
        self.chkStrictDate.setToolTip(_translate("PlanOperatingDayPage", "<html><head/><body><p>Включен - строгое соответствие даты назначения действия дате отбора.</p><p>Выключен - дата назначения действия меньше или равна дате отбора.</p></body></html>", None))
        self.chkStrictDate.setText(_translate("PlanOperatingDayPage", "Строго Дата отбора", None))
        self.lblActionStatus.setText(_translate("PlanOperatingDayPage", "Состояние", None))
        self.btnReset.setText(_translate("PlanOperatingDayPage", "Сбросить", None))
        self.btnApply.setText(_translate("PlanOperatingDayPage", "Применить", None))
        self.btnOperatingDayPrint.setText(_translate("PlanOperatingDayPage", "Печать", None))
        self.lblModifyPerson.setText(_translate("PlanOperatingDayPage", "Изменил: ", None))
        self.btnSave.setText(_translate("PlanOperatingDayPage", "Сохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlanOperatingDay), _translate("PlanOperatingDayPage", "План", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutsideOperatingDay), _translate("PlanOperatingDayPage", "Вне плана", None))
        self.lblCreatePerson.setText(_translate("PlanOperatingDayPage", "Автор: ", None))
        self.btnClose.setText(_translate("PlanOperatingDayPage", "Отмена", None))
        self.btnSurgeryJournal.setText(_translate("PlanOperatingDayPage", "Журнал операций", None))

from Events.ActionStatus import CActionStatusComboBox
from HospitalBeds.PlanOperatingDayInDocTableView import CPlanOperatingDayInDocTableView
from library.DateEdit import CDateEdit
from library.PrintTemplates import CPrintButton
