# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBHospitalBedProfileEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(400, 317)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(ItemEditorDialog)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblEndDate = QtGui.QLabel(self.tabMain)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 8, 0, 1, 1)
        self.edtEndDate = CDateEdit(self.tabMain)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_2.addWidget(self.edtEndDate, 8, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout_2.addWidget(self.lblRegionalCode, 2, 0, 1, 1)
        self.lblService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblService.sizePolicy().hasHeightForWidth())
        self.lblService.setSizePolicy(sizePolicy)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout_2.addWidget(self.lblService, 3, 0, 1, 1)
        self.lblMedicalAidProfile = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidProfile.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidProfile.setSizePolicy(sizePolicy)
        self.lblMedicalAidProfile.setObjectName(_fromUtf8("lblMedicalAidProfile"))
        self.gridLayout_2.addWidget(self.lblMedicalAidProfile, 4, 0, 1, 1)
        self.lblEmsProfileCode = QtGui.QLabel(self.tabMain)
        self.lblEmsProfileCode.setObjectName(_fromUtf8("lblEmsProfileCode"))
        self.gridLayout_2.addWidget(self.lblEmsProfileCode, 5, 0, 1, 1)
        self.lblUsishCode = QtGui.QLabel(self.tabMain)
        self.lblUsishCode.setObjectName(_fromUtf8("lblUsishCode"))
        self.gridLayout_2.addWidget(self.lblUsishCode, 6, 0, 1, 1)
        self.lblTfomsCode = QtGui.QLabel(self.tabMain)
        self.lblTfomsCode.setObjectName(_fromUtf8("lblTfomsCode"))
        self.gridLayout_2.addWidget(self.lblTfomsCode, 7, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(307, 63, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 8, 2, 1, 1)
        self.edtTfomsCode = QtGui.QLineEdit(self.tabMain)
        self.edtTfomsCode.setObjectName(_fromUtf8("edtTfomsCode"))
        self.gridLayout_2.addWidget(self.edtTfomsCode, 7, 1, 1, 2)
        self.edtUsishCode = QtGui.QLineEdit(self.tabMain)
        self.edtUsishCode.setObjectName(_fromUtf8("edtUsishCode"))
        self.gridLayout_2.addWidget(self.edtUsishCode, 6, 1, 1, 2)
        self.edtEmsProfileCode = QtGui.QLineEdit(self.tabMain)
        self.edtEmsProfileCode.setObjectName(_fromUtf8("edtEmsProfileCode"))
        self.gridLayout_2.addWidget(self.edtEmsProfileCode, 5, 1, 1, 2)
        self.cmbMedicalAidProfile = CRBComboBox(self.tabMain)
        self.cmbMedicalAidProfile.setObjectName(_fromUtf8("cmbMedicalAidProfile"))
        self.gridLayout_2.addWidget(self.cmbMedicalAidProfile, 4, 1, 1, 2)
        self.cmbService = CRBComboBox(self.tabMain)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout_2.addWidget(self.cmbService, 3, 1, 1, 2)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout_2.addWidget(self.edtRegionalCode, 2, 1, 1, 2)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 1, 1, 1, 2)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 0, 1, 1, 2)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblService.setBuddy(self.cmbService)
        self.lblMedicalAidProfile.setBuddy(self.cmbMedicalAidProfile)
        self.lblEmsProfileCode.setBuddy(self.edtEmsProfileCode)
        self.lblUsishCode.setBuddy(self.edtUsishCode)
        self.lblTfomsCode.setBuddy(self.edtTfomsCode)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.cmbService)
        ItemEditorDialog.setTabOrder(self.cmbService, self.cmbMedicalAidProfile)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidProfile, self.edtEmsProfileCode)
        ItemEditorDialog.setTabOrder(self.edtEmsProfileCode, self.edtUsishCode)
        ItemEditorDialog.setTabOrder(self.edtUsishCode, self.edtTfomsCode)
        ItemEditorDialog.setTabOrder(self.edtTfomsCode, self.edtEndDate)
        ItemEditorDialog.setTabOrder(self.edtEndDate, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblEndDate.setText(_translate("ItemEditorDialog", "Дата закрытия", None))
        self.edtEndDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Региональный код", None))
        self.lblService.setText(_translate("ItemEditorDialog", "Базовая &услуга", None))
        self.lblMedicalAidProfile.setText(_translate("ItemEditorDialog", "&Профиль медицинской помощи", None))
        self.lblEmsProfileCode.setText(_translate("ItemEditorDialog", "Код профиля в бюро госпитализации", None))
        self.lblUsishCode.setText(_translate("ItemEditorDialog", "Код ЕГИСЗ", None))
        self.lblTfomsCode.setText(_translate("ItemEditorDialog", "Код ТФОМС", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "&Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "&Идентификация", None))

from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

