# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\Surveillance\SurveillancePlanningEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SurveillancePlanningEditDialog(object):
    def setupUi(self, SurveillancePlanningEditDialog):
        SurveillancePlanningEditDialog.setObjectName(_fromUtf8("SurveillancePlanningEditDialog"))
        SurveillancePlanningEditDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SurveillancePlanningEditDialog.resize(904, 885)
        self.gridLayout = QtGui.QGridLayout(SurveillancePlanningEditDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(SurveillancePlanningEditDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grpPlanningSurveillance = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPlanningSurveillance.sizePolicy().hasHeightForWidth())
        self.grpPlanningSurveillance.setSizePolicy(sizePolicy)
        self.grpPlanningSurveillance.setAlignment(QtCore.Qt.AlignCenter)
        self.grpPlanningSurveillance.setObjectName(_fromUtf8("grpPlanningSurveillance"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpPlanningSurveillance)
        self.gridLayout_2.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblPlanningSurveillance = CInDocTableView(self.grpPlanningSurveillance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPlanningSurveillance.sizePolicy().hasHeightForWidth())
        self.tblPlanningSurveillance.setSizePolicy(sizePolicy)
        self.tblPlanningSurveillance.setObjectName(_fromUtf8("tblPlanningSurveillance"))
        self.gridLayout_2.addWidget(self.tblPlanningSurveillance, 0, 0, 1, 1)
        self.grpControlSurveillance = QtGui.QGroupBox(self.splitter)
        self.grpControlSurveillance.setAlignment(QtCore.Qt.AlignCenter)
        self.grpControlSurveillance.setObjectName(_fromUtf8("grpControlSurveillance"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpControlSurveillance)
        self.gridLayout_4.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblControlSurveillance = CVisitInDocTableView(self.grpControlSurveillance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblControlSurveillance.sizePolicy().hasHeightForWidth())
        self.tblControlSurveillance.setSizePolicy(sizePolicy)
        self.tblControlSurveillance.setObjectName(_fromUtf8("tblControlSurveillance"))
        self.gridLayout_4.addWidget(self.tblControlSurveillance, 0, 0, 1, 1)
        self.grpMeasuresSurveillance = QtGui.QGroupBox(self.splitter)
        self.grpMeasuresSurveillance.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMeasuresSurveillance.setObjectName(_fromUtf8("grpMeasuresSurveillance"))
        self.gridLayout1 = QtGui.QGridLayout(self.grpMeasuresSurveillance)
        self.gridLayout1.setMargin(1)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.tabMeasuresContent = QtGui.QTabWidget(self.grpMeasuresSurveillance)
        self.tabMeasuresContent.setTabPosition(QtGui.QTabWidget.North)
        self.tabMeasuresContent.setObjectName(_fromUtf8("tabMeasuresContent"))
        self.tabMeasuresStatus = QtGui.QWidget()
        self.tabMeasuresStatus.setObjectName(_fromUtf8("tabMeasuresStatus"))
        self._8 = QtGui.QGridLayout(self.tabMeasuresStatus)
        self._8.setMargin(2)
        self._8.setSpacing(2)
        self._8.setObjectName(_fromUtf8("_8"))
        self.frmMeasuresStatusFilter = QtGui.QGroupBox(self.tabMeasuresStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresStatusFilter.sizePolicy().hasHeightForWidth())
        self.frmMeasuresStatusFilter.setSizePolicy(sizePolicy)
        self.frmMeasuresStatusFilter.setObjectName(_fromUtf8("frmMeasuresStatusFilter"))
        self._9 = QtGui.QGridLayout(self.frmMeasuresStatusFilter)
        self._9.setMargin(2)
        self._9.setSpacing(2)
        self._9.setObjectName(_fromUtf8("_9"))
        self.lblMeasuresStatusBegDate = QtGui.QLabel(self.frmMeasuresStatusFilter)
        self.lblMeasuresStatusBegDate.setObjectName(_fromUtf8("lblMeasuresStatusBegDate"))
        self._9.addWidget(self.lblMeasuresStatusBegDate, 0, 0, 1, 1)
        self.edtMeasuresStatusBegDate = CDateEdit(self.frmMeasuresStatusFilter)
        self.edtMeasuresStatusBegDate.setCalendarPopup(True)
        self.edtMeasuresStatusBegDate.setObjectName(_fromUtf8("edtMeasuresStatusBegDate"))
        self._9.addWidget(self.edtMeasuresStatusBegDate, 0, 1, 1, 1)
        self.lblMeasuresStatusEndDate = QtGui.QLabel(self.frmMeasuresStatusFilter)
        self.lblMeasuresStatusEndDate.setObjectName(_fromUtf8("lblMeasuresStatusEndDate"))
        self._9.addWidget(self.lblMeasuresStatusEndDate, 0, 2, 1, 1)
        self.edtMeasuresStatusEndDate = CDateEdit(self.frmMeasuresStatusFilter)
        self.edtMeasuresStatusEndDate.setCalendarPopup(True)
        self.edtMeasuresStatusEndDate.setObjectName(_fromUtf8("edtMeasuresStatusEndDate"))
        self._9.addWidget(self.edtMeasuresStatusEndDate, 0, 3, 1, 1)
        self.cmbMeasuresStatusGroup = CActionTypeComboBox(self.frmMeasuresStatusFilter)
        self.cmbMeasuresStatusGroup.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbMeasuresStatusGroup.setObjectName(_fromUtf8("cmbMeasuresStatusGroup"))
        self.cmbMeasuresStatusGroup.addItem(_fromUtf8(""))
        self._9.addWidget(self.cmbMeasuresStatusGroup, 0, 4, 1, 1)
        self.edtMeasuresStatusOffice = QtGui.QLineEdit(self.frmMeasuresStatusFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMeasuresStatusOffice.sizePolicy().hasHeightForWidth())
        self.edtMeasuresStatusOffice.setSizePolicy(sizePolicy)
        self.edtMeasuresStatusOffice.setMinimumSize(QtCore.QSize(60, 0))
        self.edtMeasuresStatusOffice.setMaxLength(10)
        self.edtMeasuresStatusOffice.setReadOnly(False)
        self.edtMeasuresStatusOffice.setObjectName(_fromUtf8("edtMeasuresStatusOffice"))
        self._9.addWidget(self.edtMeasuresStatusOffice, 0, 5, 1, 1)
        self.cmbMeasuresStatusOrgStructure = COrgStructureComboBox(self.frmMeasuresStatusFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeasuresStatusOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMeasuresStatusOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMeasuresStatusOrgStructure.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbMeasuresStatusOrgStructure.setObjectName(_fromUtf8("cmbMeasuresStatusOrgStructure"))
        self._9.addWidget(self.cmbMeasuresStatusOrgStructure, 0, 6, 1, 1)
        self.btnMeasuresStatusButtonBox = QtGui.QDialogButtonBox(self.frmMeasuresStatusFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasuresStatusButtonBox.sizePolicy().hasHeightForWidth())
        self.btnMeasuresStatusButtonBox.setSizePolicy(sizePolicy)
        self.btnMeasuresStatusButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnMeasuresStatusButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnMeasuresStatusButtonBox.setObjectName(_fromUtf8("btnMeasuresStatusButtonBox"))
        self._9.addWidget(self.btnMeasuresStatusButtonBox, 0, 8, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._9.addItem(spacerItem, 0, 7, 1, 1)
        self._8.addWidget(self.frmMeasuresStatusFilter, 0, 0, 1, 1)
        self.frmMeasuresStatusAction = QtGui.QFrame(self.tabMeasuresStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresStatusAction.sizePolicy().hasHeightForWidth())
        self.frmMeasuresStatusAction.setSizePolicy(sizePolicy)
        self.frmMeasuresStatusAction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMeasuresStatusAction.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMeasuresStatusAction.setObjectName(_fromUtf8("frmMeasuresStatusAction"))
        self._10 = QtGui.QGridLayout(self.frmMeasuresStatusAction)
        self._10.setMargin(0)
        self._10.setSpacing(0)
        self._10.setObjectName(_fromUtf8("_10"))
        self.splitterMeasuresStatusAction = QtGui.QSplitter(self.frmMeasuresStatusAction)
        self.splitterMeasuresStatusAction.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMeasuresStatusAction.setObjectName(_fromUtf8("splitterMeasuresStatusAction"))
        self.tblMeasuresStatusActions = CRegistryActionsTableView(self.splitterMeasuresStatusAction)
        self.tblMeasuresStatusActions.setObjectName(_fromUtf8("tblMeasuresStatusActions"))
        self.tblMeasuresStatusActionProperties = CActionPropertiesTableView(self.splitterMeasuresStatusAction)
        self.tblMeasuresStatusActionProperties.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblMeasuresStatusActionProperties.setObjectName(_fromUtf8("tblMeasuresStatusActionProperties"))
        self._10.addWidget(self.splitterMeasuresStatusAction, 0, 0, 1, 1)
        self._8.addWidget(self.frmMeasuresStatusAction, 1, 0, 1, 1)
        self.tabMeasuresContent.addTab(self.tabMeasuresStatus, _fromUtf8(""))
        self.tabMeasuresDiagnostic = QtGui.QWidget()
        self.tabMeasuresDiagnostic.setObjectName(_fromUtf8("tabMeasuresDiagnostic"))
        self._11 = QtGui.QGridLayout(self.tabMeasuresDiagnostic)
        self._11.setMargin(2)
        self._11.setSpacing(2)
        self._11.setObjectName(_fromUtf8("_11"))
        self.frmMeasuresDiagnosticFilter = QtGui.QGroupBox(self.tabMeasuresDiagnostic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresDiagnosticFilter.sizePolicy().hasHeightForWidth())
        self.frmMeasuresDiagnosticFilter.setSizePolicy(sizePolicy)
        self.frmMeasuresDiagnosticFilter.setObjectName(_fromUtf8("frmMeasuresDiagnosticFilter"))
        self._12 = QtGui.QGridLayout(self.frmMeasuresDiagnosticFilter)
        self._12.setMargin(2)
        self._12.setSpacing(2)
        self._12.setObjectName(_fromUtf8("_12"))
        self.lblMeasuresDiagnosticBegDate = QtGui.QLabel(self.frmMeasuresDiagnosticFilter)
        self.lblMeasuresDiagnosticBegDate.setObjectName(_fromUtf8("lblMeasuresDiagnosticBegDate"))
        self._12.addWidget(self.lblMeasuresDiagnosticBegDate, 0, 0, 1, 1)
        self.edtMeasuresDiagnosticBegDate = CDateEdit(self.frmMeasuresDiagnosticFilter)
        self.edtMeasuresDiagnosticBegDate.setCalendarPopup(True)
        self.edtMeasuresDiagnosticBegDate.setObjectName(_fromUtf8("edtMeasuresDiagnosticBegDate"))
        self._12.addWidget(self.edtMeasuresDiagnosticBegDate, 0, 1, 1, 1)
        self.lblMeasuresDiagnosticEndDate = QtGui.QLabel(self.frmMeasuresDiagnosticFilter)
        self.lblMeasuresDiagnosticEndDate.setObjectName(_fromUtf8("lblMeasuresDiagnosticEndDate"))
        self._12.addWidget(self.lblMeasuresDiagnosticEndDate, 0, 2, 1, 1)
        self.edtMeasuresDiagnosticEndDate = CDateEdit(self.frmMeasuresDiagnosticFilter)
        self.edtMeasuresDiagnosticEndDate.setCalendarPopup(True)
        self.edtMeasuresDiagnosticEndDate.setObjectName(_fromUtf8("edtMeasuresDiagnosticEndDate"))
        self._12.addWidget(self.edtMeasuresDiagnosticEndDate, 0, 3, 1, 1)
        self.cmbMeasuresDiagnosticGroup = CActionTypeComboBox(self.frmMeasuresDiagnosticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeasuresDiagnosticGroup.sizePolicy().hasHeightForWidth())
        self.cmbMeasuresDiagnosticGroup.setSizePolicy(sizePolicy)
        self.cmbMeasuresDiagnosticGroup.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbMeasuresDiagnosticGroup.setObjectName(_fromUtf8("cmbMeasuresDiagnosticGroup"))
        self.cmbMeasuresDiagnosticGroup.addItem(_fromUtf8(""))
        self._12.addWidget(self.cmbMeasuresDiagnosticGroup, 0, 4, 1, 1)
        self.edtMeasuresDiagnosticOffice = QtGui.QLineEdit(self.frmMeasuresDiagnosticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMeasuresDiagnosticOffice.sizePolicy().hasHeightForWidth())
        self.edtMeasuresDiagnosticOffice.setSizePolicy(sizePolicy)
        self.edtMeasuresDiagnosticOffice.setMinimumSize(QtCore.QSize(60, 0))
        self.edtMeasuresDiagnosticOffice.setMaxLength(10)
        self.edtMeasuresDiagnosticOffice.setReadOnly(False)
        self.edtMeasuresDiagnosticOffice.setObjectName(_fromUtf8("edtMeasuresDiagnosticOffice"))
        self._12.addWidget(self.edtMeasuresDiagnosticOffice, 0, 5, 1, 1)
        self.cmbMeasuresDiagnosticOrgStructure = COrgStructureComboBox(self.frmMeasuresDiagnosticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeasuresDiagnosticOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMeasuresDiagnosticOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMeasuresDiagnosticOrgStructure.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbMeasuresDiagnosticOrgStructure.setObjectName(_fromUtf8("cmbMeasuresDiagnosticOrgStructure"))
        self._12.addWidget(self.cmbMeasuresDiagnosticOrgStructure, 0, 6, 1, 1)
        self.btnMeasuresDiagnosticButtonBox = QtGui.QDialogButtonBox(self.frmMeasuresDiagnosticFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasuresDiagnosticButtonBox.sizePolicy().hasHeightForWidth())
        self.btnMeasuresDiagnosticButtonBox.setSizePolicy(sizePolicy)
        self.btnMeasuresDiagnosticButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnMeasuresDiagnosticButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnMeasuresDiagnosticButtonBox.setObjectName(_fromUtf8("btnMeasuresDiagnosticButtonBox"))
        self._12.addWidget(self.btnMeasuresDiagnosticButtonBox, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._12.addItem(spacerItem1, 0, 7, 1, 1)
        self._11.addWidget(self.frmMeasuresDiagnosticFilter, 0, 0, 1, 1)
        self.frmMeasuresDiagnosticAction = QtGui.QFrame(self.tabMeasuresDiagnostic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresDiagnosticAction.sizePolicy().hasHeightForWidth())
        self.frmMeasuresDiagnosticAction.setSizePolicy(sizePolicy)
        self.frmMeasuresDiagnosticAction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMeasuresDiagnosticAction.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMeasuresDiagnosticAction.setObjectName(_fromUtf8("frmMeasuresDiagnosticAction"))
        self._13 = QtGui.QGridLayout(self.frmMeasuresDiagnosticAction)
        self._13.setMargin(0)
        self._13.setSpacing(0)
        self._13.setObjectName(_fromUtf8("_13"))
        self.splitterMeasuresDiagnosticAction = QtGui.QSplitter(self.frmMeasuresDiagnosticAction)
        self.splitterMeasuresDiagnosticAction.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMeasuresDiagnosticAction.setObjectName(_fromUtf8("splitterMeasuresDiagnosticAction"))
        self.tblMeasuresDiagnosticActions = CRegistryActionsTableView(self.splitterMeasuresDiagnosticAction)
        self.tblMeasuresDiagnosticActions.setObjectName(_fromUtf8("tblMeasuresDiagnosticActions"))
        self.tblMeasuresDiagnosticActionProperties = CActionPropertiesTableView(self.splitterMeasuresDiagnosticAction)
        self.tblMeasuresDiagnosticActionProperties.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblMeasuresDiagnosticActionProperties.setObjectName(_fromUtf8("tblMeasuresDiagnosticActionProperties"))
        self._13.addWidget(self.splitterMeasuresDiagnosticAction, 0, 0, 1, 1)
        self._11.addWidget(self.frmMeasuresDiagnosticAction, 1, 0, 1, 1)
        self.tabMeasuresContent.addTab(self.tabMeasuresDiagnostic, _fromUtf8(""))
        self.tabMeasuresCure = QtGui.QWidget()
        self.tabMeasuresCure.setObjectName(_fromUtf8("tabMeasuresCure"))
        self._14 = QtGui.QGridLayout(self.tabMeasuresCure)
        self._14.setMargin(2)
        self._14.setSpacing(2)
        self._14.setObjectName(_fromUtf8("_14"))
        self.frmMeasuresCureFilter = QtGui.QGroupBox(self.tabMeasuresCure)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresCureFilter.sizePolicy().hasHeightForWidth())
        self.frmMeasuresCureFilter.setSizePolicy(sizePolicy)
        self.frmMeasuresCureFilter.setObjectName(_fromUtf8("frmMeasuresCureFilter"))
        self._15 = QtGui.QGridLayout(self.frmMeasuresCureFilter)
        self._15.setMargin(2)
        self._15.setSpacing(2)
        self._15.setObjectName(_fromUtf8("_15"))
        self.cmbMeasuresCureGroup = CActionTypeComboBox(self.frmMeasuresCureFilter)
        self.cmbMeasuresCureGroup.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbMeasuresCureGroup.setObjectName(_fromUtf8("cmbMeasuresCureGroup"))
        self.cmbMeasuresCureGroup.addItem(_fromUtf8(""))
        self._15.addWidget(self.cmbMeasuresCureGroup, 0, 4, 1, 1)
        self.lblMeasuresCureBegDate = QtGui.QLabel(self.frmMeasuresCureFilter)
        self.lblMeasuresCureBegDate.setObjectName(_fromUtf8("lblMeasuresCureBegDate"))
        self._15.addWidget(self.lblMeasuresCureBegDate, 0, 0, 1, 1)
        self.edtMeasuresCureBegDate = CDateEdit(self.frmMeasuresCureFilter)
        self.edtMeasuresCureBegDate.setCalendarPopup(True)
        self.edtMeasuresCureBegDate.setObjectName(_fromUtf8("edtMeasuresCureBegDate"))
        self._15.addWidget(self.edtMeasuresCureBegDate, 0, 1, 1, 1)
        self.lblMeasuresCureEndDate = QtGui.QLabel(self.frmMeasuresCureFilter)
        self.lblMeasuresCureEndDate.setObjectName(_fromUtf8("lblMeasuresCureEndDate"))
        self._15.addWidget(self.lblMeasuresCureEndDate, 0, 2, 1, 1)
        self.edtMeasuresCureEndDate = CDateEdit(self.frmMeasuresCureFilter)
        self.edtMeasuresCureEndDate.setCalendarPopup(True)
        self.edtMeasuresCureEndDate.setObjectName(_fromUtf8("edtMeasuresCureEndDate"))
        self._15.addWidget(self.edtMeasuresCureEndDate, 0, 3, 1, 1)
        self.edtMeasuresCureOffice = QtGui.QLineEdit(self.frmMeasuresCureFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMeasuresCureOffice.sizePolicy().hasHeightForWidth())
        self.edtMeasuresCureOffice.setSizePolicy(sizePolicy)
        self.edtMeasuresCureOffice.setMinimumSize(QtCore.QSize(60, 0))
        self.edtMeasuresCureOffice.setMaxLength(10)
        self.edtMeasuresCureOffice.setReadOnly(False)
        self.edtMeasuresCureOffice.setObjectName(_fromUtf8("edtMeasuresCureOffice"))
        self._15.addWidget(self.edtMeasuresCureOffice, 0, 5, 1, 1)
        self.cmbMeasuresCureOrgStructure = COrgStructureComboBox(self.frmMeasuresCureFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeasuresCureOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMeasuresCureOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMeasuresCureOrgStructure.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbMeasuresCureOrgStructure.setObjectName(_fromUtf8("cmbMeasuresCureOrgStructure"))
        self._15.addWidget(self.cmbMeasuresCureOrgStructure, 0, 6, 1, 1)
        self.btnMeasuresCureButtonBox = QtGui.QDialogButtonBox(self.frmMeasuresCureFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasuresCureButtonBox.sizePolicy().hasHeightForWidth())
        self.btnMeasuresCureButtonBox.setSizePolicy(sizePolicy)
        self.btnMeasuresCureButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnMeasuresCureButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnMeasuresCureButtonBox.setObjectName(_fromUtf8("btnMeasuresCureButtonBox"))
        self._15.addWidget(self.btnMeasuresCureButtonBox, 0, 8, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._15.addItem(spacerItem2, 0, 7, 1, 1)
        self._14.addWidget(self.frmMeasuresCureFilter, 0, 0, 1, 1)
        self.frmMeasuresCureAction = QtGui.QFrame(self.tabMeasuresCure)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresCureAction.sizePolicy().hasHeightForWidth())
        self.frmMeasuresCureAction.setSizePolicy(sizePolicy)
        self.frmMeasuresCureAction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMeasuresCureAction.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMeasuresCureAction.setObjectName(_fromUtf8("frmMeasuresCureAction"))
        self._16 = QtGui.QGridLayout(self.frmMeasuresCureAction)
        self._16.setMargin(0)
        self._16.setSpacing(0)
        self._16.setObjectName(_fromUtf8("_16"))
        self.splitterMeasuresCureAction = QtGui.QSplitter(self.frmMeasuresCureAction)
        self.splitterMeasuresCureAction.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMeasuresCureAction.setObjectName(_fromUtf8("splitterMeasuresCureAction"))
        self.tblMeasuresCureActions = CRegistryActionsTableView(self.splitterMeasuresCureAction)
        self.tblMeasuresCureActions.setObjectName(_fromUtf8("tblMeasuresCureActions"))
        self.tblMeasuresCureActionProperties = CActionPropertiesTableView(self.splitterMeasuresCureAction)
        self.tblMeasuresCureActionProperties.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblMeasuresCureActionProperties.setObjectName(_fromUtf8("tblMeasuresCureActionProperties"))
        self._16.addWidget(self.splitterMeasuresCureAction, 0, 0, 1, 1)
        self._14.addWidget(self.frmMeasuresCureAction, 1, 0, 1, 1)
        self.tabMeasuresContent.addTab(self.tabMeasuresCure, _fromUtf8(""))
        self.tabMeasuresMisc = QtGui.QWidget()
        self.tabMeasuresMisc.setObjectName(_fromUtf8("tabMeasuresMisc"))
        self._17 = QtGui.QGridLayout(self.tabMeasuresMisc)
        self._17.setMargin(2)
        self._17.setSpacing(2)
        self._17.setObjectName(_fromUtf8("_17"))
        self.frmMeasuresMiscFilter = QtGui.QGroupBox(self.tabMeasuresMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresMiscFilter.sizePolicy().hasHeightForWidth())
        self.frmMeasuresMiscFilter.setSizePolicy(sizePolicy)
        self.frmMeasuresMiscFilter.setObjectName(_fromUtf8("frmMeasuresMiscFilter"))
        self._18 = QtGui.QGridLayout(self.frmMeasuresMiscFilter)
        self._18.setMargin(2)
        self._18.setSpacing(2)
        self._18.setObjectName(_fromUtf8("_18"))
        self.lblMeasuresMiscBegDate = QtGui.QLabel(self.frmMeasuresMiscFilter)
        self.lblMeasuresMiscBegDate.setObjectName(_fromUtf8("lblMeasuresMiscBegDate"))
        self._18.addWidget(self.lblMeasuresMiscBegDate, 0, 0, 1, 1)
        self.edtMeasuresMiscBegDate = CDateEdit(self.frmMeasuresMiscFilter)
        self.edtMeasuresMiscBegDate.setCalendarPopup(True)
        self.edtMeasuresMiscBegDate.setObjectName(_fromUtf8("edtMeasuresMiscBegDate"))
        self._18.addWidget(self.edtMeasuresMiscBegDate, 0, 1, 1, 1)
        self.lblMeasuresMiscEndDate = QtGui.QLabel(self.frmMeasuresMiscFilter)
        self.lblMeasuresMiscEndDate.setObjectName(_fromUtf8("lblMeasuresMiscEndDate"))
        self._18.addWidget(self.lblMeasuresMiscEndDate, 0, 2, 1, 1)
        self.edtMeasuresMiscEndDate = CDateEdit(self.frmMeasuresMiscFilter)
        self.edtMeasuresMiscEndDate.setCalendarPopup(True)
        self.edtMeasuresMiscEndDate.setObjectName(_fromUtf8("edtMeasuresMiscEndDate"))
        self._18.addWidget(self.edtMeasuresMiscEndDate, 0, 3, 1, 1)
        self.cmbMeasuresMiscGroup = CActionTypeComboBox(self.frmMeasuresMiscFilter)
        self.cmbMeasuresMiscGroup.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbMeasuresMiscGroup.setObjectName(_fromUtf8("cmbMeasuresMiscGroup"))
        self.cmbMeasuresMiscGroup.addItem(_fromUtf8(""))
        self._18.addWidget(self.cmbMeasuresMiscGroup, 0, 4, 1, 1)
        self.edtMeasuresMiscOffice = QtGui.QLineEdit(self.frmMeasuresMiscFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMeasuresMiscOffice.sizePolicy().hasHeightForWidth())
        self.edtMeasuresMiscOffice.setSizePolicy(sizePolicy)
        self.edtMeasuresMiscOffice.setMinimumSize(QtCore.QSize(60, 0))
        self.edtMeasuresMiscOffice.setMaxLength(10)
        self.edtMeasuresMiscOffice.setReadOnly(False)
        self.edtMeasuresMiscOffice.setObjectName(_fromUtf8("edtMeasuresMiscOffice"))
        self._18.addWidget(self.edtMeasuresMiscOffice, 0, 5, 1, 1)
        self.cmbMeasuresMiscOrgStructure = COrgStructureComboBox(self.frmMeasuresMiscFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMeasuresMiscOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbMeasuresMiscOrgStructure.setSizePolicy(sizePolicy)
        self.cmbMeasuresMiscOrgStructure.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbMeasuresMiscOrgStructure.setObjectName(_fromUtf8("cmbMeasuresMiscOrgStructure"))
        self._18.addWidget(self.cmbMeasuresMiscOrgStructure, 0, 6, 1, 1)
        self.btnMeasuresMiscButtonBox = QtGui.QDialogButtonBox(self.frmMeasuresMiscFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasuresMiscButtonBox.sizePolicy().hasHeightForWidth())
        self.btnMeasuresMiscButtonBox.setSizePolicy(sizePolicy)
        self.btnMeasuresMiscButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnMeasuresMiscButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnMeasuresMiscButtonBox.setObjectName(_fromUtf8("btnMeasuresMiscButtonBox"))
        self._18.addWidget(self.btnMeasuresMiscButtonBox, 0, 8, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._18.addItem(spacerItem3, 0, 7, 1, 1)
        self._17.addWidget(self.frmMeasuresMiscFilter, 0, 0, 1, 1)
        self.frmMeasuresMiscAction = QtGui.QFrame(self.tabMeasuresMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmMeasuresMiscAction.sizePolicy().hasHeightForWidth())
        self.frmMeasuresMiscAction.setSizePolicy(sizePolicy)
        self.frmMeasuresMiscAction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMeasuresMiscAction.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMeasuresMiscAction.setObjectName(_fromUtf8("frmMeasuresMiscAction"))
        self._19 = QtGui.QGridLayout(self.frmMeasuresMiscAction)
        self._19.setMargin(0)
        self._19.setSpacing(0)
        self._19.setObjectName(_fromUtf8("_19"))
        self.splitterMeasuresMiscAction = QtGui.QSplitter(self.frmMeasuresMiscAction)
        self.splitterMeasuresMiscAction.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMeasuresMiscAction.setObjectName(_fromUtf8("splitterMeasuresMiscAction"))
        self.tblMeasuresMiscActions = CRegistryActionsTableView(self.splitterMeasuresMiscAction)
        self.tblMeasuresMiscActions.setObjectName(_fromUtf8("tblMeasuresMiscActions"))
        self.tblMeasuresMiscActionProperties = CActionPropertiesTableView(self.splitterMeasuresMiscAction)
        self.tblMeasuresMiscActionProperties.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblMeasuresMiscActionProperties.setObjectName(_fromUtf8("tblMeasuresMiscActionProperties"))
        self._19.addWidget(self.splitterMeasuresMiscAction, 0, 0, 1, 1)
        self._17.addWidget(self.frmMeasuresMiscAction, 1, 0, 1, 1)
        self.tabMeasuresContent.addTab(self.tabMeasuresMisc, _fromUtf8(""))
        self.gridLayout1.addWidget(self.tabMeasuresContent, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(SurveillancePlanningEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(SurveillancePlanningEditDialog)
        self.tabMeasuresContent.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SurveillancePlanningEditDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SurveillancePlanningEditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SurveillancePlanningEditDialog)
        SurveillancePlanningEditDialog.setTabOrder(self.tblPlanningSurveillance, self.tblControlSurveillance)
        SurveillancePlanningEditDialog.setTabOrder(self.tblControlSurveillance, self.buttonBox)

    def retranslateUi(self, SurveillancePlanningEditDialog):
        SurveillancePlanningEditDialog.setWindowTitle(_translate("SurveillancePlanningEditDialog", "Планирование профилактического наблюдения", None))
        self.grpPlanningSurveillance.setTitle(_translate("SurveillancePlanningEditDialog", "&Контрольные карты диспансерного наблюдения", None))
        self.grpControlSurveillance.setTitle(_translate("SurveillancePlanningEditDialog", "&Планирование и контроль посещений", None))
        self.grpMeasuresSurveillance.setTitle(_translate("SurveillancePlanningEditDialog", "Лечебно-профилактические мероприятия", None))
        self.frmMeasuresStatusFilter.setTitle(_translate("SurveillancePlanningEditDialog", "Фильтр", None))
        self.lblMeasuresStatusBegDate.setText(_translate("SurveillancePlanningEditDialog", "С", None))
        self.edtMeasuresStatusBegDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.lblMeasuresStatusEndDate.setText(_translate("SurveillancePlanningEditDialog", "По", None))
        self.edtMeasuresStatusEndDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.cmbMeasuresStatusGroup.setItemText(0, _translate("SurveillancePlanningEditDialog", "Тип (группа?)", None))
        self.tabMeasuresContent.setTabText(self.tabMeasuresContent.indexOf(self.tabMeasuresStatus), _translate("SurveillancePlanningEditDialog", "Статус", None))
        self.frmMeasuresDiagnosticFilter.setTitle(_translate("SurveillancePlanningEditDialog", "Фильтр", None))
        self.lblMeasuresDiagnosticBegDate.setText(_translate("SurveillancePlanningEditDialog", "С", None))
        self.edtMeasuresDiagnosticBegDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.lblMeasuresDiagnosticEndDate.setText(_translate("SurveillancePlanningEditDialog", "По", None))
        self.edtMeasuresDiagnosticEndDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.cmbMeasuresDiagnosticGroup.setItemText(0, _translate("SurveillancePlanningEditDialog", "Тип (группа?)", None))
        self.tabMeasuresContent.setTabText(self.tabMeasuresContent.indexOf(self.tabMeasuresDiagnostic), _translate("SurveillancePlanningEditDialog", "Диагностика", None))
        self.frmMeasuresCureFilter.setTitle(_translate("SurveillancePlanningEditDialog", "Фильтр", None))
        self.cmbMeasuresCureGroup.setItemText(0, _translate("SurveillancePlanningEditDialog", "Тип (группа?)", None))
        self.lblMeasuresCureBegDate.setText(_translate("SurveillancePlanningEditDialog", "С", None))
        self.edtMeasuresCureBegDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.lblMeasuresCureEndDate.setText(_translate("SurveillancePlanningEditDialog", "По", None))
        self.edtMeasuresCureEndDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.tabMeasuresContent.setTabText(self.tabMeasuresContent.indexOf(self.tabMeasuresCure), _translate("SurveillancePlanningEditDialog", "Лечение", None))
        self.frmMeasuresMiscFilter.setTitle(_translate("SurveillancePlanningEditDialog", "Фильтр", None))
        self.lblMeasuresMiscBegDate.setText(_translate("SurveillancePlanningEditDialog", "С", None))
        self.edtMeasuresMiscBegDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.lblMeasuresMiscEndDate.setText(_translate("SurveillancePlanningEditDialog", "По", None))
        self.edtMeasuresMiscEndDate.setDisplayFormat(_translate("SurveillancePlanningEditDialog", "dd.MM.yyyy", None))
        self.cmbMeasuresMiscGroup.setItemText(0, _translate("SurveillancePlanningEditDialog", "Тип (группа?)", None))
        self.tabMeasuresContent.setTabText(self.tabMeasuresContent.indexOf(self.tabMeasuresMisc), _translate("SurveillancePlanningEditDialog", "Мероприятия", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTypeComboBox import CActionTypeComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Registry.RegistryTable import CRegistryActionsTableView
from Registry.VisitInDocTableView import CVisitInDocTableView
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
