# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\appendix\mes\CSGEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CSGEditor(object):
    def setupUi(self, CSGEditor):
        CSGEditor.setObjectName(_fromUtf8("CSGEditor"))
        CSGEditor.resize(786, 440)
        self.gridLayout_4 = QtGui.QGridLayout(CSGEditor)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(CSGEditor)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblCSGSex = QtGui.QLabel(self.layoutWidget)
        self.lblCSGSex.setObjectName(_fromUtf8("lblCSGSex"))
        self.gridLayout.addWidget(self.lblCSGSex, 2, 0, 1, 1)
        self.lblCSGCode = QtGui.QLabel(self.layoutWidget)
        self.lblCSGCode.setObjectName(_fromUtf8("lblCSGCode"))
        self.gridLayout.addWidget(self.lblCSGCode, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 7, 1, 1)
        self.edtEndAgeCount = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout.addWidget(self.edtEndAgeCount, 3, 6, 1, 1)
        self.lblCSGAge = QtGui.QLabel(self.layoutWidget)
        self.lblCSGAge.setObjectName(_fromUtf8("lblCSGAge"))
        self.gridLayout.addWidget(self.lblCSGAge, 3, 0, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEndAgeUnit, 3, 5, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBegAgeUnit, 3, 1, 1, 1)
        self.chkCSGInternal = QtGui.QCheckBox(self.layoutWidget)
        self.chkCSGInternal.setObjectName(_fromUtf8("chkCSGInternal"))
        self.gridLayout.addWidget(self.chkCSGInternal, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(561, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 3, 1, 5)
        self.lblAgeSep = QtGui.QLabel(self.layoutWidget)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout.addWidget(self.lblAgeSep, 3, 4, 1, 1)
        self.chkCSGActiviti = QtGui.QCheckBox(self.layoutWidget)
        self.chkCSGActiviti.setObjectName(_fromUtf8("chkCSGActiviti"))
        self.gridLayout.addWidget(self.chkCSGActiviti, 6, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(601, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 5)
        self.cmbCSGSex = QtGui.QComboBox(self.layoutWidget)
        self.cmbCSGSex.setObjectName(_fromUtf8("cmbCSGSex"))
        self.cmbCSGSex.addItem(_fromUtf8(""))
        self.cmbCSGSex.setItemText(0, _fromUtf8(""))
        self.cmbCSGSex.addItem(_fromUtf8(""))
        self.cmbCSGSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbCSGSex, 2, 1, 1, 1)
        self.lblCSGNote = QtGui.QLabel(self.layoutWidget)
        self.lblCSGNote.setObjectName(_fromUtf8("lblCSGNote"))
        self.gridLayout.addWidget(self.lblCSGNote, 4, 0, 1, 1)
        self.edtCSGNote = QtGui.QTextEdit(self.layoutWidget)
        self.edtCSGNote.setObjectName(_fromUtf8("edtCSGNote"))
        self.gridLayout.addWidget(self.edtCSGNote, 4, 1, 1, 7)
        self.edtCSGCode = QtGui.QLineEdit(self.layoutWidget)
        self.edtCSGCode.setObjectName(_fromUtf8("edtCSGCode"))
        self.gridLayout.addWidget(self.edtCSGCode, 0, 1, 1, 7)
        self.edtBegAgeCount = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout.addWidget(self.edtBegAgeCount, 3, 3, 1, 1)
        self.lblCSGName = QtGui.QLabel(self.layoutWidget)
        self.lblCSGName.setObjectName(_fromUtf8("lblCSGName"))
        self.gridLayout.addWidget(self.lblCSGName, 1, 0, 1, 1)
        self.edtCSGName = QtGui.QLineEdit(self.layoutWidget)
        self.edtCSGName.setObjectName(_fromUtf8("edtCSGName"))
        self.gridLayout.addWidget(self.edtCSGName, 1, 1, 1, 7)
        self.lblMRBMESGroup = QtGui.QLabel(self.layoutWidget)
        self.lblMRBMESGroup.setObjectName(_fromUtf8("lblMRBMESGroup"))
        self.gridLayout.addWidget(self.lblMRBMESGroup, 5, 0, 1, 1)
        self.cmbMRBMESGroup = CRBComboBox(self.layoutWidget)
        self.cmbMRBMESGroup.setObjectName(_fromUtf8("cmbMRBMESGroup"))
        self.gridLayout.addWidget(self.cmbMRBMESGroup, 5, 1, 1, 7)
        self.chkPolyTrauma = QtGui.QCheckBox(self.layoutWidget)
        self.chkPolyTrauma.setObjectName(_fromUtf8("chkPolyTrauma"))
        self.gridLayout.addWidget(self.chkPolyTrauma, 6, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabCSGDiagnosisEx = QtGui.QWidget()
        self.tabCSGDiagnosisEx.setObjectName(_fromUtf8("tabCSGDiagnosisEx"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabCSGDiagnosisEx)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblCSGDiagnosisEx = CInDocTableView(self.tabCSGDiagnosisEx)
        self.tblCSGDiagnosisEx.setObjectName(_fromUtf8("tblCSGDiagnosisEx"))
        self.gridLayout_2.addWidget(self.tblCSGDiagnosisEx, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCSGDiagnosisEx, _fromUtf8(""))
        self.tabCSGServicesEx = QtGui.QWidget()
        self.tabCSGServicesEx.setObjectName(_fromUtf8("tabCSGServicesEx"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCSGServicesEx)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblCSGServicesEx = CInDocTableView(self.tabCSGServicesEx)
        self.tblCSGServicesEx.setObjectName(_fromUtf8("tblCSGServicesEx"))
        self.gridLayout_3.addWidget(self.tblCSGServicesEx, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCSGServicesEx, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 2, 2)
        self.buttonBox = QtGui.QDialogButtonBox(CSGEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)

        self.retranslateUi(CSGEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CSGEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CSGEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(CSGEditor)
        CSGEditor.setTabOrder(self.buttonBox, self.edtCSGCode)
        CSGEditor.setTabOrder(self.edtCSGCode, self.edtCSGName)
        CSGEditor.setTabOrder(self.edtCSGName, self.cmbCSGSex)
        CSGEditor.setTabOrder(self.cmbCSGSex, self.cmbBegAgeUnit)
        CSGEditor.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        CSGEditor.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        CSGEditor.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        CSGEditor.setTabOrder(self.edtEndAgeCount, self.edtCSGNote)
        CSGEditor.setTabOrder(self.edtCSGNote, self.cmbMRBMESGroup)
        CSGEditor.setTabOrder(self.cmbMRBMESGroup, self.chkCSGActiviti)
        CSGEditor.setTabOrder(self.chkCSGActiviti, self.chkCSGInternal)
        CSGEditor.setTabOrder(self.chkCSGInternal, self.chkPolyTrauma)
        CSGEditor.setTabOrder(self.chkPolyTrauma, self.tabWidget)
        CSGEditor.setTabOrder(self.tabWidget, self.tblCSGDiagnosisEx)
        CSGEditor.setTabOrder(self.tblCSGDiagnosisEx, self.tblCSGServicesEx)

    def retranslateUi(self, CSGEditor):
        CSGEditor.setWindowTitle(_translate("CSGEditor", "Редактор КСГ", None))
        self.lblCSGSex.setText(_translate("CSGEditor", "Пол", None))
        self.lblCSGCode.setText(_translate("CSGEditor", "Код", None))
        self.edtEndAgeCount.setInputMask(_translate("CSGEditor", "000; ", None))
        self.lblCSGAge.setText(_translate("CSGEditor", "Возраст", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("CSGEditor", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("CSGEditor", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("CSGEditor", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("CSGEditor", "Г", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("CSGEditor", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("CSGEditor", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("CSGEditor", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("CSGEditor", "Г", None))
        self.chkCSGInternal.setText(_translate("CSGEditor", "Внутренний", None))
        self.lblAgeSep.setText(_translate("CSGEditor", "по", None))
        self.chkCSGActiviti.setText(_translate("CSGEditor", "Активно", None))
        self.cmbCSGSex.setItemText(1, _translate("CSGEditor", "М", None))
        self.cmbCSGSex.setItemText(2, _translate("CSGEditor", "Ж", None))
        self.lblCSGNote.setText(_translate("CSGEditor", "Доп.условие", None))
        self.edtBegAgeCount.setInputMask(_translate("CSGEditor", "000; ", None))
        self.lblCSGName.setText(_translate("CSGEditor", "Название", None))
        self.lblMRBMESGroup.setText(_translate("CSGEditor", "Профиль", None))
        self.chkPolyTrauma.setText(_translate("CSGEditor", "Политравма", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCSGDiagnosisEx), _translate("CSGEditor", "МКБ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCSGServicesEx), _translate("CSGEditor", "Услуги", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
