# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\appendix\mes\Editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MESEditor(object):
    def setupUi(self, MESEditor):
        MESEditor.setObjectName(_fromUtf8("MESEditor"))
        MESEditor.resize(1125, 491)
        self.gridLayout_4 = QtGui.QGridLayout(MESEditor)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(MESEditor)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.lblKSG = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblKSG.sizePolicy().hasHeightForWidth())
        self.lblKSG.setSizePolicy(sizePolicy)
        self.lblKSG.setObjectName(_fromUtf8("lblKSG"))
        self.gridLayout_3.addWidget(self.lblKSG, 1, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.layoutWidget)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_3.addWidget(self.edtName, 3, 1, 1, 2)
        self.edtCode = QtGui.QLineEdit(self.layoutWidget)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_3.addWidget(self.edtCode, 2, 1, 1, 2)
        self.cmbKSG = CRBComboBox(self.layoutWidget)
        self.cmbKSG.setObjectName(_fromUtf8("cmbKSG"))
        self.gridLayout_3.addWidget(self.cmbKSG, 1, 1, 1, 2)
        self.cmbGroup = CRBComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGroup.sizePolicy().hasHeightForWidth())
        self.cmbGroup.setSizePolicy(sizePolicy)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridLayout_3.addWidget(self.cmbGroup, 0, 1, 1, 2)
        self.textDescription = QtGui.QTextEdit(self.layoutWidget)
        self.textDescription.setObjectName(_fromUtf8("textDescription"))
        self.gridLayout_3.addWidget(self.textDescription, 4, 1, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.spinMin = QtGui.QSpinBox(self.layoutWidget)
        self.spinMin.setMaximum(1000)
        self.spinMin.setObjectName(_fromUtf8("spinMin"))
        self.horizontalLayout.addWidget(self.spinMin)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.spinMax = QtGui.QSpinBox(self.layoutWidget)
        self.spinMax.setMinimum(1)
        self.spinMax.setMaximum(1000)
        self.spinMax.setObjectName(_fromUtf8("spinMax"))
        self.horizontalLayout.addWidget(self.spinMax)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.spinAvg = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinAvg.setDecimals(4)
        self.spinAvg.setMaximum(999.9999)
        self.spinAvg.setObjectName(_fromUtf8("spinAvg"))
        self.horizontalLayout.addWidget(self.spinAvg)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.lblEndDate = QtGui.QLabel(self.layoutWidget)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.horizontalLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(self.layoutWidget)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 1, 1, 2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 19, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.edtModel = QtGui.QLineEdit(self.layoutWidget1)
        self.edtModel.setObjectName(_fromUtf8("edtModel"))
        self.horizontalLayout_2.addWidget(self.edtModel)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.edtTariff = QtGui.QLineEdit(self.layoutWidget1)
        self.edtTariff.setObjectName(_fromUtf8("edtTariff"))
        self.horizontalLayout_2.addWidget(self.edtTariff)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinKSG = QtGui.QSpinBox(self.layoutWidget1)
        self.spinKSG.setProperty("value", 1)
        self.spinKSG.setObjectName(_fromUtf8("spinKSG"))
        self.horizontalLayout_2.addWidget(self.spinKSG)
        self.lblPeriodicity = QtGui.QLabel(self.layoutWidget1)
        self.lblPeriodicity.setObjectName(_fromUtf8("lblPeriodicity"))
        self.horizontalLayout_2.addWidget(self.lblPeriodicity)
        self.edtPeriodicity = QtGui.QSpinBox(self.layoutWidget1)
        self.edtPeriodicity.setMaximum(999)
        self.edtPeriodicity.setObjectName(_fromUtf8("edtPeriodicity"))
        self.horizontalLayout_2.addWidget(self.edtPeriodicity)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)
        self.chkActive = QtGui.QCheckBox(self.layoutWidget1)
        self.chkActive.setChecked(True)
        self.chkActive.setObjectName(_fromUtf8("chkActive"))
        self.gridLayout_2.addWidget(self.chkActive, 1, 0, 1, 1)
        self.chkInternal = QtGui.QCheckBox(self.layoutWidget1)
        self.chkInternal.setObjectName(_fromUtf8("chkInternal"))
        self.gridLayout_2.addWidget(self.chkInternal, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget1)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMKB = QtGui.QWidget()
        self.tabMKB.setObjectName(_fromUtf8("tabMKB"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabMKB)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblMKB = CInDocTableView(self.tabMKB)
        self.tblMKB.setObjectName(_fromUtf8("tblMKB"))
        self.verticalLayout_2.addWidget(self.tblMKB)
        self.tabWidget.addTab(self.tabMKB, _fromUtf8(""))
        self.tabServices = QtGui.QWidget()
        self.tabServices.setObjectName(_fromUtf8("tabServices"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabServices)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblServices = CInDocTableView(self.tabServices)
        self.tblServices.setObjectName(_fromUtf8("tblServices"))
        self.verticalLayout_3.addWidget(self.tblServices)
        self.tabWidget.addTab(self.tabServices, _fromUtf8(""))
        self.tabVisits = QtGui.QWidget()
        self.tabVisits.setObjectName(_fromUtf8("tabVisits"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabVisits)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblVisits = CInDocTableView(self.tabVisits)
        self.tblVisits.setObjectName(_fromUtf8("tblVisits"))
        self.verticalLayout_4.addWidget(self.tblVisits)
        self.tabWidget.addTab(self.tabVisits, _fromUtf8(""))
        self.tabEquipment = QtGui.QWidget()
        self.tabEquipment.setObjectName(_fromUtf8("tabEquipment"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabEquipment)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tblEquipment = CInDocTableView(self.tabEquipment)
        self.tblEquipment.setObjectName(_fromUtf8("tblEquipment"))
        self.verticalLayout_5.addWidget(self.tblEquipment)
        self.tabWidget.addTab(self.tabEquipment, _fromUtf8(""))
        self.tabMedicament = QtGui.QWidget()
        self.tabMedicament.setObjectName(_fromUtf8("tabMedicament"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabMedicament)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tblMedicament = CInDocTableView(self.tabMedicament)
        self.tblMedicament.setObjectName(_fromUtf8("tblMedicament"))
        self.verticalLayout_6.addWidget(self.tblMedicament)
        self.tabWidget.addTab(self.tabMedicament, _fromUtf8(""))
        self.tabBlood = QtGui.QWidget()
        self.tabBlood.setObjectName(_fromUtf8("tabBlood"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabBlood)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tblBlood = CInDocTableView(self.tabBlood)
        self.tblBlood.setObjectName(_fromUtf8("tblBlood"))
        self.verticalLayout_7.addWidget(self.tblBlood)
        self.tabWidget.addTab(self.tabBlood, _fromUtf8(""))
        self.tabNutrient = QtGui.QWidget()
        self.tabNutrient.setObjectName(_fromUtf8("tabNutrient"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabNutrient)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tblNutrient = CInDocTableView(self.tabNutrient)
        self.tblNutrient.setObjectName(_fromUtf8("tblNutrient"))
        self.verticalLayout_8.addWidget(self.tblNutrient)
        self.tabWidget.addTab(self.tabNutrient, _fromUtf8(""))
        self.tabLimitedBySexAge = QtGui.QWidget()
        self.tabLimitedBySexAge.setObjectName(_fromUtf8("tabLimitedBySexAge"))
        self.gridLayout = QtGui.QGridLayout(self.tabLimitedBySexAge)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblLimitedBySexAge = CInDocTableView(self.tabLimitedBySexAge)
        self.tblLimitedBySexAge.setObjectName(_fromUtf8("tblLimitedBySexAge"))
        self.gridLayout.addWidget(self.tblLimitedBySexAge, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLimitedBySexAge, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.chkPolyTrauma = QtGui.QCheckBox(self.layoutWidget1)
        self.chkPolyTrauma.setObjectName(_fromUtf8("chkPolyTrauma"))
        self.gridLayout_2.addWidget(self.chkPolyTrauma, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(MESEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(MESEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MESEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MESEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(MESEditor)
        MESEditor.setTabOrder(self.cmbGroup, self.cmbKSG)
        MESEditor.setTabOrder(self.cmbKSG, self.edtCode)
        MESEditor.setTabOrder(self.edtCode, self.edtName)
        MESEditor.setTabOrder(self.edtName, self.textDescription)
        MESEditor.setTabOrder(self.textDescription, self.spinMin)
        MESEditor.setTabOrder(self.spinMin, self.spinMax)
        MESEditor.setTabOrder(self.spinMax, self.spinAvg)
        MESEditor.setTabOrder(self.spinAvg, self.edtEndDate)
        MESEditor.setTabOrder(self.edtEndDate, self.edtModel)
        MESEditor.setTabOrder(self.edtModel, self.edtTariff)
        MESEditor.setTabOrder(self.edtTariff, self.spinKSG)
        MESEditor.setTabOrder(self.spinKSG, self.edtPeriodicity)
        MESEditor.setTabOrder(self.edtPeriodicity, self.chkActive)
        MESEditor.setTabOrder(self.chkActive, self.chkInternal)
        MESEditor.setTabOrder(self.chkInternal, self.chkPolyTrauma)
        MESEditor.setTabOrder(self.chkPolyTrauma, self.tabWidget)
        MESEditor.setTabOrder(self.tabWidget, self.tblMKB)
        MESEditor.setTabOrder(self.tblMKB, self.tblServices)
        MESEditor.setTabOrder(self.tblServices, self.tblEquipment)
        MESEditor.setTabOrder(self.tblEquipment, self.tblMedicament)
        MESEditor.setTabOrder(self.tblMedicament, self.tblBlood)
        MESEditor.setTabOrder(self.tblBlood, self.tblNutrient)
        MESEditor.setTabOrder(self.tblNutrient, self.tblLimitedBySexAge)
        MESEditor.setTabOrder(self.tblLimitedBySexAge, self.tblVisits)
        MESEditor.setTabOrder(self.tblVisits, self.buttonBox)

    def retranslateUi(self, MESEditor):
        MESEditor.setWindowTitle(_translate("MESEditor", "Редактирование МЭС", None))
        self.label.setText(_translate("MESEditor", "Профиль:", None))
        self.label_2.setText(_translate("MESEditor", "Код:", None))
        self.label_3.setText(_translate("MESEditor", "Наименование:", None))
        self.label_4.setText(_translate("MESEditor", "Описание:", None))
        self.label_8.setText(_translate("MESEditor", "Длительность:", None))
        self.lblKSG.setText(_translate("MESEditor", "КСГ:", None))
        self.label_9.setText(_translate("MESEditor", "минимальная", None))
        self.label_10.setText(_translate("MESEditor", "максимальная", None))
        self.label_11.setText(_translate("MESEditor", "средняя", None))
        self.lblEndDate.setText(_translate("MESEditor", "Дата окончания", None))
        self.edtEndDate.setDisplayFormat(_translate("MESEditor", "dd.MM.yyyy", None))
        self.label_5.setText(_translate("MESEditor", "Модель пациента:", None))
        self.label_6.setText(_translate("MESEditor", "Тариф:", None))
        self.label_7.setText(_translate("MESEditor", "Норматив визитов:", None))
        self.lblPeriodicity.setText(_translate("MESEditor", "Периодичность", None))
        self.chkActive.setText(_translate("MESEditor", "активно", None))
        self.chkInternal.setText(_translate("MESEditor", "внутренний", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMKB), _translate("MESEditor", "МКБ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServices), _translate("MESEditor", "Услуги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVisits), _translate("MESEditor", "Визиты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquipment), _translate("MESEditor", "Оборудование", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicament), _translate("MESEditor", "Медикаменты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBlood), _translate("MESEditor", "Препараты крови", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNutrient), _translate("MESEditor", "Питательные средства", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLimitedBySexAge), _translate("MESEditor", "Ограничение по полу и возрасту", None))
        self.chkPolyTrauma.setText(_translate("MESEditor", "Политравма", None))

from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
