# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\appendix\mes\MesList.ui'
#
# Created: Wed May 17 12:18:28 2023
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1175, 772)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabMESCSGWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMESCSGWidget.sizePolicy().hasHeightForWidth())
        self.tabMESCSGWidget.setSizePolicy(sizePolicy)
        self.tabMESCSGWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabMESCSGWidget.setObjectName(_fromUtf8("tabMESCSGWidget"))
        self.tabMES = QtGui.QWidget()
        self.tabMES.setObjectName(_fromUtf8("tabMES"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tabMES)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.splitter_2 = QtGui.QSplitter(self.tabMES)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.textInfo = QtGui.QTextBrowser(self.splitter_2)
        self.textInfo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textInfo.sizePolicy().hasHeightForWidth())
        self.textInfo.setSizePolicy(sizePolicy)
        self.textInfo.setMinimumSize(QtCore.QSize(0, 260))
        self.textInfo.setBaseSize(QtCore.QSize(0, 0))
        self.textInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textInfo.setObjectName(_fromUtf8("textInfo"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.mesView = CMesListTableView(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesView.sizePolicy().hasHeightForWidth())
        self.mesView.setSizePolicy(sizePolicy)
        self.mesView.setMinimumSize(QtCore.QSize(500, 0))
        self.mesView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mesView.setObjectName(_fromUtf8("mesView"))
        self.verticalLayout_12.addWidget(self.mesView)
        self.lblCount = QtGui.QLabel(self.groupBox_2)
        self.lblCount.setObjectName(_fromUtf8("lblCount"))
        self.verticalLayout_12.addWidget(self.lblCount)
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMKB = QtGui.QWidget()
        self.tabMKB.setObjectName(_fromUtf8("tabMKB"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabMKB)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableMKB = CTableView(self.tabMKB)
        self.tableMKB.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableMKB.setObjectName(_fromUtf8("tableMKB"))
        self.verticalLayout_3.addWidget(self.tableMKB)
        self.tabWidget.addTab(self.tabMKB, _fromUtf8(""))
        self.tabServices = QtGui.QWidget()
        self.tabServices.setObjectName(_fromUtf8("tabServices"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabServices)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableServices = CTableView(self.tabServices)
        self.tableServices.setObjectName(_fromUtf8("tableServices"))
        self.verticalLayout_4.addWidget(self.tableServices)
        self.tabWidget.addTab(self.tabServices, _fromUtf8(""))
        self.tabVisits = QtGui.QWidget()
        self.tabVisits.setObjectName(_fromUtf8("tabVisits"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabVisits)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableVisits = QtGui.QTableView(self.tabVisits)
        self.tableVisits.setObjectName(_fromUtf8("tableVisits"))
        self.verticalLayout_5.addWidget(self.tableVisits)
        self.tabWidget.addTab(self.tabVisits, _fromUtf8(""))
        self.tabEquipment = QtGui.QWidget()
        self.tabEquipment.setObjectName(_fromUtf8("tabEquipment"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabEquipment)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tableEquipment = QtGui.QTableView(self.tabEquipment)
        self.tableEquipment.setObjectName(_fromUtf8("tableEquipment"))
        self.verticalLayout_6.addWidget(self.tableEquipment)
        self.tabWidget.addTab(self.tabEquipment, _fromUtf8(""))
        self.tabMedicament = QtGui.QWidget()
        self.tabMedicament.setObjectName(_fromUtf8("tabMedicament"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabMedicament)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tableMedicament = QtGui.QTableView(self.tabMedicament)
        self.tableMedicament.setObjectName(_fromUtf8("tableMedicament"))
        self.verticalLayout_7.addWidget(self.tableMedicament)
        self.tabWidget.addTab(self.tabMedicament, _fromUtf8(""))
        self.tabBlood = QtGui.QWidget()
        self.tabBlood.setObjectName(_fromUtf8("tabBlood"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabBlood)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tableBlood = QtGui.QTableView(self.tabBlood)
        self.tableBlood.setObjectName(_fromUtf8("tableBlood"))
        self.verticalLayout_8.addWidget(self.tableBlood)
        self.tabWidget.addTab(self.tabBlood, _fromUtf8(""))
        self.tabNutrient = QtGui.QWidget()
        self.tabNutrient.setObjectName(_fromUtf8("tabNutrient"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabNutrient)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tableNutrient = QtGui.QTableView(self.tabNutrient)
        self.tableNutrient.setObjectName(_fromUtf8("tableNutrient"))
        self.verticalLayout_9.addWidget(self.tableNutrient)
        self.tabWidget.addTab(self.tabNutrient, _fromUtf8(""))
        self.tabLimitedBySexAge = QtGui.QWidget()
        self.tabLimitedBySexAge.setObjectName(_fromUtf8("tabLimitedBySexAge"))
        self.gridLayout = QtGui.QGridLayout(self.tabLimitedBySexAge)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableLimitedBySexAge = QtGui.QTableView(self.tabLimitedBySexAge)
        self.tableLimitedBySexAge.setObjectName(_fromUtf8("tableLimitedBySexAge"))
        self.gridLayout.addWidget(self.tableLimitedBySexAge, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLimitedBySexAge, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.splitter_2)
        self.tabMESCSGWidget.addTab(self.tabMES, _fromUtf8(""))
        self.tabCSG = QtGui.QWidget()
        self.tabCSG.setObjectName(_fromUtf8("tabCSG"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabCSG)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitter_3 = QtGui.QSplitter(self.tabCSG)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.txtCSGBrowser = QtGui.QTextBrowser(self.splitter_3)
        self.txtCSGBrowser.setObjectName(_fromUtf8("txtCSGBrowser"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblCSGList = CCSGListTableView(self.layoutWidget1)
        self.tblCSGList.setObjectName(_fromUtf8("tblCSGList"))
        self.gridLayout_4.addWidget(self.tblCSGList, 0, 0, 1, 1)
        self.lblCountCSG = QtGui.QLabel(self.layoutWidget1)
        self.lblCountCSG.setObjectName(_fromUtf8("lblCountCSG"))
        self.gridLayout_4.addWidget(self.lblCountCSG, 1, 0, 1, 1)
        self.tabSubCSG = QtGui.QTabWidget(self.splitter_3)
        self.tabSubCSG.setObjectName(_fromUtf8("tabSubCSG"))
        self.tabCSGDiagnosis = QtGui.QWidget()
        self.tabCSGDiagnosis.setObjectName(_fromUtf8("tabCSGDiagnosis"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabCSGDiagnosis)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblCSGDiagnosis = CTableView(self.tabCSGDiagnosis)
        self.tblCSGDiagnosis.setObjectName(_fromUtf8("tblCSGDiagnosis"))
        self.gridLayout_7.addWidget(self.tblCSGDiagnosis, 0, 0, 1, 1)
        self.tabSubCSG.addTab(self.tabCSGDiagnosis, _fromUtf8(""))
        self.tabCSGService = QtGui.QWidget()
        self.tabCSGService.setObjectName(_fromUtf8("tabCSGService"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabCSGService)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblCSGService = CTableView(self.tabCSGService)
        self.tblCSGService.setObjectName(_fromUtf8("tblCSGService"))
        self.gridLayout_8.addWidget(self.tblCSGService, 0, 0, 1, 1)
        self.tabSubCSG.addTab(self.tabCSGService, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabMESCSGWidget.addTab(self.tabCSG, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabMESCSGWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnEdit = QtGui.QPushButton(self.layoutWidget)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.horizontalLayout_2.addWidget(self.btnEdit)
        self.btnPrint = QtGui.QPushButton(self.layoutWidget)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.horizontalLayout_2.addWidget(self.btnPrint)
        self.btnFind = QtGui.QPushButton(self.layoutWidget)
        self.btnFind.setObjectName(_fromUtf8("btnFind"))
        self.horizontalLayout_2.addWidget(self.btnFind)
        self.btnAdd = QtGui.QPushButton(self.layoutWidget)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupFilter = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFilter.sizePolicy().hasHeightForWidth())
        self.groupFilter.setSizePolicy(sizePolicy)
        self.groupFilter.setObjectName(_fromUtf8("groupFilter"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupFilter)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkGroup = QtGui.QCheckBox(self.groupFilter)
        self.checkGroup.setObjectName(_fromUtf8("checkGroup"))
        self.verticalLayout.addWidget(self.checkGroup)
        self.cmbGroup = CRBComboBox(self.groupFilter)
        self.cmbGroup.setEnabled(False)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.verticalLayout.addWidget(self.cmbGroup)
        self.checkCode = QtGui.QCheckBox(self.groupFilter)
        self.checkCode.setObjectName(_fromUtf8("checkCode"))
        self.verticalLayout.addWidget(self.checkCode)
        self.edtCode = QtGui.QLineEdit(self.groupFilter)
        self.edtCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCode.sizePolicy().hasHeightForWidth())
        self.edtCode.setSizePolicy(sizePolicy)
        self.edtCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.verticalLayout.addWidget(self.edtCode)
        self.checkName = QtGui.QCheckBox(self.groupFilter)
        self.checkName.setObjectName(_fromUtf8("checkName"))
        self.verticalLayout.addWidget(self.checkName)
        self.edtName = QtGui.QLineEdit(self.groupFilter)
        self.edtName.setEnabled(False)
        self.edtName.setMaximumSize(QtCore.QSize(500, 16777215))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.verticalLayout.addWidget(self.edtName)
        self.checkMKB = QtGui.QCheckBox(self.groupFilter)
        self.checkMKB.setObjectName(_fromUtf8("checkMKB"))
        self.verticalLayout.addWidget(self.checkMKB)
        self.edtMKB = QtGui.QLineEdit(self.groupFilter)
        self.edtMKB.setEnabled(False)
        self.edtMKB.setObjectName(_fromUtf8("edtMKB"))
        self.verticalLayout.addWidget(self.edtMKB)
        self.checkMKBEx = QtGui.QCheckBox(self.groupFilter)
        self.checkMKBEx.setObjectName(_fromUtf8("checkMKBEx"))
        self.verticalLayout.addWidget(self.checkMKBEx)
        self.edtMKBEx = QtGui.QLineEdit(self.groupFilter)
        self.edtMKBEx.setEnabled(False)
        self.edtMKBEx.setObjectName(_fromUtf8("edtMKBEx"))
        self.verticalLayout.addWidget(self.edtMKBEx)
        self.groupBox_3 = QtGui.QGroupBox(self.groupFilter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbActiveAll = QtGui.QRadioButton(self.groupBox_3)
        self.rbActiveAll.setObjectName(_fromUtf8("rbActiveAll"))
        self.horizontalLayout.addWidget(self.rbActiveAll)
        self.rbActive = QtGui.QRadioButton(self.groupBox_3)
        self.rbActive.setChecked(True)
        self.rbActive.setObjectName(_fromUtf8("rbActive"))
        self.horizontalLayout.addWidget(self.rbActive)
        self.rbNotActive = QtGui.QRadioButton(self.groupBox_3)
        self.rbNotActive.setObjectName(_fromUtf8("rbNotActive"))
        self.horizontalLayout.addWidget(self.rbNotActive)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupFilter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rbInternalAll = QtGui.QRadioButton(self.groupBox_4)
        self.rbInternalAll.setChecked(True)
        self.rbInternalAll.setObjectName(_fromUtf8("rbInternalAll"))
        self.horizontalLayout_4.addWidget(self.rbInternalAll)
        self.rbInternal = QtGui.QRadioButton(self.groupBox_4)
        self.rbInternal.setObjectName(_fromUtf8("rbInternal"))
        self.horizontalLayout_4.addWidget(self.rbInternal)
        self.rbExternal = QtGui.QRadioButton(self.groupBox_4)
        self.rbExternal.setObjectName(_fromUtf8("rbExternal"))
        self.horizontalLayout_4.addWidget(self.rbExternal)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnClear = QtGui.QPushButton(self.groupFilter)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.horizontalLayout_3.addWidget(self.btnClear)
        self.btnUpdate = QtGui.QPushButton(self.groupFilter)
        self.btnUpdate.setAutoDefault(False)
        self.btnUpdate.setDefault(False)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout_3.addWidget(self.btnUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuReference = QtGui.QMenu(self.menubar)
        self.menuReference.setObjectName(_fromUtf8("menuReference"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuExchange = QtGui.QMenu(self.menubar)
        self.menuExchange.setObjectName(_fromUtf8("menuExchange"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_connection = QtGui.QAction(MainWindow)
        self.action_connection.setObjectName(_fromUtf8("action_connection"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_connect = QtGui.QAction(MainWindow)
        self.action_connect.setObjectName(_fromUtf8("action_connect"))
        self.action_add = QtGui.QAction(MainWindow)
        self.action_add.setObjectName(_fromUtf8("action_add"))
        self.action_edit = QtGui.QAction(MainWindow)
        self.action_edit.setObjectName(_fromUtf8("action_edit"))
        self.action_find = QtGui.QAction(MainWindow)
        self.action_find.setObjectName(_fromUtf8("action_find"))
        self.action_print = QtGui.QAction(MainWindow)
        self.action_print.setObjectName(_fromUtf8("action_print"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_Qt = QtGui.QAction(MainWindow)
        self.action_Qt.setObjectName(_fromUtf8("action_Qt"))
        self.action_rbVisitType = QtGui.QAction(MainWindow)
        self.action_rbVisitType.setObjectName(_fromUtf8("action_rbVisitType"))
        self.action_rbBloodPreparation = QtGui.QAction(MainWindow)
        self.action_rbBloodPreparation.setObjectName(_fromUtf8("action_rbBloodPreparation"))
        self.action_rbBloodPreparationType = QtGui.QAction(MainWindow)
        self.action_rbBloodPreparationType.setObjectName(_fromUtf8("action_rbBloodPreparationType"))
        self.action_rbEquipment = QtGui.QAction(MainWindow)
        self.action_rbEquipment.setObjectName(_fromUtf8("action_rbEquipment"))
        self.action_rbEquipmentGroup = QtGui.QAction(MainWindow)
        self.action_rbEquipmentGroup.setObjectName(_fromUtf8("action_rbEquipmentGroup"))
        self.action_rbMedicamentDosageForm = QtGui.QAction(MainWindow)
        self.action_rbMedicamentDosageForm.setObjectName(_fromUtf8("action_rbMedicamentDosageForm"))
        self.action_rbMedicamentGroup = QtGui.QAction(MainWindow)
        self.action_rbMedicamentGroup.setObjectName(_fromUtf8("action_rbMedicamentGroup"))
        self.action_rbMesGroup = QtGui.QAction(MainWindow)
        self.action_rbMesGroup.setObjectName(_fromUtf8("action_rbMesGroup"))
        self.action_rbNutrientGroup = QtGui.QAction(MainWindow)
        self.action_rbNutrientGroup.setObjectName(_fromUtf8("action_rbNutrientGroup"))
        self.action_rbServiceGroup = QtGui.QAction(MainWindow)
        self.action_rbServiceGroup.setObjectName(_fromUtf8("action_rbServiceGroup"))
        self.action_rbMedicament = QtGui.QAction(MainWindow)
        self.action_rbMedicament.setObjectName(_fromUtf8("action_rbMedicament"))
        self.action_rbNutrient = QtGui.QAction(MainWindow)
        self.action_rbNutrient.setObjectName(_fromUtf8("action_rbNutrient"))
        self.action_rbService = QtGui.QAction(MainWindow)
        self.action_rbService.setObjectName(_fromUtf8("action_rbService"))
        self.action_rbSpeciality = QtGui.QAction(MainWindow)
        self.action_rbSpeciality.setObjectName(_fromUtf8("action_rbSpeciality"))
        self.actImportXML = QtGui.QAction(MainWindow)
        self.actImportXML.setObjectName(_fromUtf8("actImportXML"))
        self.actExportXML = QtGui.QAction(MainWindow)
        self.actExportXML.setObjectName(_fromUtf8("actExportXML"))
        self.actMesKSG = QtGui.QAction(MainWindow)
        self.actMesKSG.setObjectName(_fromUtf8("actMesKSG"))
        self.action_disconnect = QtGui.QAction(MainWindow)
        self.action_disconnect.setObjectName(_fromUtf8("action_disconnect"))
        self.menuHelp.addAction(self.action_about)
        self.menuHelp.addAction(self.action_Qt)
        self.menuReference.addAction(self.action_rbMesGroup)
        self.menuReference.addAction(self.actMesKSG)
        self.menuReference.addAction(self.action_rbVisitType)
        self.menuReference.addAction(self.action_rbBloodPreparation)
        self.menuReference.addAction(self.action_rbBloodPreparationType)
        self.menuReference.addAction(self.action_rbEquipment)
        self.menuReference.addAction(self.action_rbEquipmentGroup)
        self.menuReference.addAction(self.action_rbMedicament)
        self.menuReference.addAction(self.action_rbMedicamentDosageForm)
        self.menuReference.addAction(self.action_rbMedicamentGroup)
        self.menuReference.addAction(self.action_rbNutrient)
        self.menuReference.addAction(self.action_rbNutrientGroup)
        self.menuReference.addAction(self.action_rbService)
        self.menuReference.addAction(self.action_rbServiceGroup)
        self.menuReference.addAction(self.action_rbSpeciality)
        self.menuSettings.addAction(self.action_connection)
        self.menu.addAction(self.action_connect)
        self.menu.addAction(self.action_disconnect)
        self.menu.addAction(self.action_add)
        self.menu.addAction(self.action_edit)
        self.menu.addAction(self.action_find)
        self.menu.addAction(self.action_print)
        self.menu.addAction(self.action_exit)
        self.menuExchange.addAction(self.actImportXML)
        self.menuExchange.addAction(self.actExportXML)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuReference.menuAction())
        self.menubar.addAction(self.menuExchange.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMESCSGWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabSubCSG.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.checkGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbGroup.setEnabled)
        QtCore.QObject.connect(self.checkCode, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCode.setEnabled)
        QtCore.QObject.connect(self.checkName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtName.setEnabled)
        QtCore.QObject.connect(self.checkMKB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKB.setEnabled)
        QtCore.QObject.connect(self.checkMKBEx, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKBEx.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabMESCSGWidget, self.mesView)
        MainWindow.setTabOrder(self.mesView, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tableMKB)
        MainWindow.setTabOrder(self.tableMKB, self.tableServices)
        MainWindow.setTabOrder(self.tableServices, self.tableVisits)
        MainWindow.setTabOrder(self.tableVisits, self.tableEquipment)
        MainWindow.setTabOrder(self.tableEquipment, self.tableMedicament)
        MainWindow.setTabOrder(self.tableMedicament, self.tableBlood)
        MainWindow.setTabOrder(self.tableBlood, self.tableNutrient)
        MainWindow.setTabOrder(self.tableNutrient, self.tableLimitedBySexAge)
        MainWindow.setTabOrder(self.tableLimitedBySexAge, self.txtCSGBrowser)
        MainWindow.setTabOrder(self.txtCSGBrowser, self.tblCSGList)
        MainWindow.setTabOrder(self.tblCSGList, self.tabSubCSG)
        MainWindow.setTabOrder(self.tabSubCSG, self.tblCSGDiagnosis)
        MainWindow.setTabOrder(self.tblCSGDiagnosis, self.tblCSGService)
        MainWindow.setTabOrder(self.tblCSGService, self.btnEdit)
        MainWindow.setTabOrder(self.btnEdit, self.btnPrint)
        MainWindow.setTabOrder(self.btnPrint, self.btnFind)
        MainWindow.setTabOrder(self.btnFind, self.btnAdd)
        MainWindow.setTabOrder(self.btnAdd, self.checkGroup)
        MainWindow.setTabOrder(self.checkGroup, self.cmbGroup)
        MainWindow.setTabOrder(self.cmbGroup, self.checkCode)
        MainWindow.setTabOrder(self.checkCode, self.edtCode)
        MainWindow.setTabOrder(self.edtCode, self.checkName)
        MainWindow.setTabOrder(self.checkName, self.edtName)
        MainWindow.setTabOrder(self.edtName, self.checkMKB)
        MainWindow.setTabOrder(self.checkMKB, self.edtMKB)
        MainWindow.setTabOrder(self.edtMKB, self.checkMKBEx)
        MainWindow.setTabOrder(self.checkMKBEx, self.edtMKBEx)
        MainWindow.setTabOrder(self.edtMKBEx, self.rbActiveAll)
        MainWindow.setTabOrder(self.rbActiveAll, self.rbActive)
        MainWindow.setTabOrder(self.rbActive, self.rbNotActive)
        MainWindow.setTabOrder(self.rbNotActive, self.rbInternalAll)
        MainWindow.setTabOrder(self.rbInternalAll, self.rbInternal)
        MainWindow.setTabOrder(self.rbInternal, self.rbExternal)
        MainWindow.setTabOrder(self.rbExternal, self.btnClear)
        MainWindow.setTabOrder(self.btnClear, self.btnUpdate)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактор", None))
        self.lblCount.setText(_translate("MainWindow", "В списке 0 записей", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMKB), _translate("MainWindow", "МКБ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServices), _translate("MainWindow", "Услуги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVisits), _translate("MainWindow", "Визиты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquipment), _translate("MainWindow", "Оборудование", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicament), _translate("MainWindow", "Медикаменты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBlood), _translate("MainWindow", "Препараты крови", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNutrient), _translate("MainWindow", "Питательные средства", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLimitedBySexAge), _translate("MainWindow", "Ограничение по полу и возрасту", None))
        self.tabMESCSGWidget.setTabText(self.tabMESCSGWidget.indexOf(self.tabMES), _translate("MainWindow", "Список МЭС", None))
        self.lblCountCSG.setText(_translate("MainWindow", "В списке 0 записей", None))
        self.tabSubCSG.setTabText(self.tabSubCSG.indexOf(self.tabCSGDiagnosis), _translate("MainWindow", "МКБ", None))
        self.tabSubCSG.setTabText(self.tabSubCSG.indexOf(self.tabCSGService), _translate("MainWindow", "Услуги", None))
        self.tabMESCSGWidget.setTabText(self.tabMESCSGWidget.indexOf(self.tabCSG), _translate("MainWindow", "Список КСГ", None))
        self.btnEdit.setText(_translate("MainWindow", "Редактировать (F4)", None))
        self.btnEdit.setShortcut(_translate("MainWindow", "F4", None))
        self.btnPrint.setText(_translate("MainWindow", "Печать (F6)", None))
        self.btnPrint.setShortcut(_translate("MainWindow", "F6", None))
        self.btnFind.setText(_translate("MainWindow", "Поиск (F7)", None))
        self.btnFind.setShortcut(_translate("MainWindow", "F7", None))
        self.btnAdd.setText(_translate("MainWindow", "Добавить (F9)", None))
        self.btnAdd.setShortcut(_translate("MainWindow", "F9", None))
        self.groupFilter.setTitle(_translate("MainWindow", "Фильтр", None))
        self.checkGroup.setText(_translate("MainWindow", "Группа:", None))
        self.checkCode.setText(_translate("MainWindow", "Код начинается с:", None))
        self.checkName.setText(_translate("MainWindow", "Имя содержит:", None))
        self.checkMKB.setText(_translate("MainWindow", "Код МКБ начинается с:", None))
        self.checkMKBEx.setText(_translate("MainWindow", "Доп.код МКБ начинается с:", None))
        self.rbActiveAll.setText(_translate("MainWindow", "все", None))
        self.rbActive.setText(_translate("MainWindow", "активные", None))
        self.rbNotActive.setText(_translate("MainWindow", "неактивные", None))
        self.rbInternalAll.setText(_translate("MainWindow", "все", None))
        self.rbInternal.setText(_translate("MainWindow", "внутренние", None))
        self.rbExternal.setText(_translate("MainWindow", "внешние", None))
        self.btnClear.setText(_translate("MainWindow", "Сбросить", None))
        self.btnUpdate.setText(_translate("MainWindow", "Применить", None))
        self.btnUpdate.setShortcut(_translate("MainWindow", "Return", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь", None))
        self.menuReference.setTitle(_translate("MainWindow", "Справочники", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Настройки", None))
        self.menu.setTitle(_translate("MainWindow", "Действия", None))
        self.menuExchange.setTitle(_translate("MainWindow", "Обмен", None))
        self.action.setText(_translate("MainWindow", "проверочка", None))
        self.action_connection.setText(_translate("MainWindow", "Соединение с БД", None))
        self.action_about.setText(_translate("MainWindow", "О программе", None))
        self.action_connect.setText(_translate("MainWindow", "Подключиться к БД", None))
        self.action_add.setText(_translate("MainWindow", "Новый МЭС", None))
        self.action_edit.setText(_translate("MainWindow", "Редактировать", None))
        self.action_find.setText(_translate("MainWindow", "Поиск", None))
        self.action_print.setText(_translate("MainWindow", "Печать", None))
        self.action_exit.setText(_translate("MainWindow", "Выход", None))
        self.action_Qt.setText(_translate("MainWindow", "О Qt", None))
        self.action_rbVisitType.setText(_translate("MainWindow", "Типы визитов", None))
        self.action_rbBloodPreparation.setText(_translate("MainWindow", "Препараты крови", None))
        self.action_rbBloodPreparationType.setText(_translate("MainWindow", "Типы препаратов крови", None))
        self.action_rbEquipment.setText(_translate("MainWindow", "Типы оборудования", None))
        self.action_rbEquipmentGroup.setText(_translate("MainWindow", "Группы типов оборудования", None))
        self.action_rbMedicamentDosageForm.setText(_translate("MainWindow", "Лекарственные формы", None))
        self.action_rbMedicamentGroup.setText(_translate("MainWindow", "Фармацевтические группы", None))
        self.action_rbMesGroup.setText(_translate("MainWindow", "Группы МЭС", None))
        self.action_rbNutrientGroup.setText(_translate("MainWindow", "Группы питательных средств", None))
        self.action_rbServiceGroup.setText(_translate("MainWindow", "Группы услуг", None))
        self.action_rbMedicament.setText(_translate("MainWindow", "Медикаменты", None))
        self.action_rbNutrient.setText(_translate("MainWindow", "Питательные средства", None))
        self.action_rbService.setText(_translate("MainWindow", "Услуги", None))
        self.action_rbSpeciality.setText(_translate("MainWindow", "Специальности", None))
        self.actImportXML.setText(_translate("MainWindow", "Импорт из XML", None))
        self.actExportXML.setText(_translate("MainWindow", "Экспорт в XML", None))
        self.actMesKSG.setText(_translate("MainWindow", "КСГ", None))
        self.action_disconnect.setText(_translate("MainWindow", "Отключиться от БД", None))

from library.crbcombobox import CRBComboBox
from appendix.mes.CSGListTableView import CCSGListTableView
from library.TableView import CTableView
from appendix.mes.MesListTableView import CMesListTableView
