# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RBNomenclatureFilter.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemFilterDialog(object):
    def setupUi(self, ItemFilterDialog):
        ItemFilterDialog.setObjectName(_fromUtf8("ItemFilterDialog"))
        ItemFilterDialog.resize(392, 289)
        ItemFilterDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ItemFilterDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblClass = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClass.sizePolicy().hasHeightForWidth())
        self.lblClass.setSizePolicy(sizePolicy)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 0, 0, 1, 1)
        self.cmbClass = CRBComboBox(ItemFilterDialog)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout.addWidget(self.cmbClass, 0, 1, 1, 1)
        self.lblKind = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblKind.sizePolicy().hasHeightForWidth())
        self.lblKind.setSizePolicy(sizePolicy)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout.addWidget(self.lblKind, 1, 0, 1, 1)
        self.cmbKind = CRBComboBox(ItemFilterDialog)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.gridLayout.addWidget(self.cmbKind, 1, 1, 1, 1)
        self.lblType = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 2, 0, 1, 1)
        self.cmbType = CRBComboBox(ItemFilterDialog)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout.addWidget(self.cmbType, 2, 1, 1, 1)
        self.lblCode = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 3, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(ItemFilterDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 3, 1, 1, 1)
        self.lblName = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 4, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(ItemFilterDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 4, 1, 1, 1)
        self.lblInternationalNonproprietaryName = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInternationalNonproprietaryName.sizePolicy().hasHeightForWidth())
        self.lblInternationalNonproprietaryName.setSizePolicy(sizePolicy)
        self.lblInternationalNonproprietaryName.setObjectName(_fromUtf8("lblInternationalNonproprietaryName"))
        self.gridLayout.addWidget(self.lblInternationalNonproprietaryName, 5, 0, 1, 1)
        self.edtInternationalNonproprietaryName = QtGui.QLineEdit(ItemFilterDialog)
        self.edtInternationalNonproprietaryName.setObjectName(_fromUtf8("edtInternationalNonproprietaryName"))
        self.gridLayout.addWidget(self.edtInternationalNonproprietaryName, 5, 1, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout.addWidget(self.lblRegionalCode, 6, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(ItemFilterDialog)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout.addWidget(self.edtRegionalCode, 6, 1, 1, 1)
        self.lblATC = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblATC.sizePolicy().hasHeightForWidth())
        self.lblATC.setSizePolicy(sizePolicy)
        self.lblATC.setObjectName(_fromUtf8("lblATC"))
        self.gridLayout.addWidget(self.lblATC, 7, 0, 1, 1)
        self.edtATC = QtGui.QLineEdit(ItemFilterDialog)
        self.edtATC.setObjectName(_fromUtf8("edtATC"))
        self.gridLayout.addWidget(self.edtATC, 7, 1, 1, 1)
        self.lblProducer = QtGui.QLabel(ItemFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProducer.sizePolicy().hasHeightForWidth())
        self.lblProducer.setSizePolicy(sizePolicy)
        self.lblProducer.setObjectName(_fromUtf8("lblProducer"))
        self.gridLayout.addWidget(self.lblProducer, 8, 0, 1, 1)
        self.edtProducer = QtGui.QLineEdit(ItemFilterDialog)
        self.edtProducer.setObjectName(_fromUtf8("edtProducer"))
        self.gridLayout.addWidget(self.edtProducer, 8, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemFilterDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 2)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblKind.setBuddy(self.cmbKind)
        self.lblType.setBuddy(self.cmbType)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblInternationalNonproprietaryName.setBuddy(self.edtInternationalNonproprietaryName)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblATC.setBuddy(self.edtATC)
        self.lblProducer.setBuddy(self.edtProducer)

        self.retranslateUi(ItemFilterDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemFilterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemFilterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemFilterDialog)

    def retranslateUi(self, ItemFilterDialog):
        ItemFilterDialog.setWindowTitle(_translate("ItemFilterDialog", "ChangeMe!", None))
        self.lblClass.setText(_translate("ItemFilterDialog", "&Класс", None))
        self.lblKind.setText(_translate("ItemFilterDialog", "&Вид", None))
        self.lblType.setText(_translate("ItemFilterDialog", "&Тип", None))
        self.lblCode.setText(_translate("ItemFilterDialog", "&Код", None))
        self.lblName.setText(_translate("ItemFilterDialog", "&Наименование содержит", None))
        self.lblInternationalNonproprietaryName.setText(_translate("ItemFilterDialog", "&МНН содержит", None))
        self.lblRegionalCode.setText(_translate("ItemFilterDialog", "&Региональный код", None))
        self.lblATC.setText(_translate("ItemFilterDialog", "Код &АТХ", None))
        self.lblProducer.setText(_translate("ItemFilterDialog", "&Производитель", None))

from library.crbcombobox import CRBComboBox
