# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBDiet.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBDiet(object):
    def setupUi(self, RBDiet):
        RBDiet.setObjectName(_fromUtf8("RBDiet"))
        RBDiet.resize(515, 188)
        RBDiet.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(RBDiet)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtEndAgeCount = QtGui.QLineEdit(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout.addWidget(self.edtEndAgeCount, 4, 8, 1, 1)
        self.edtBegAgeCount = QtGui.QLineEdit(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout.addWidget(self.edtBegAgeCount, 4, 4, 1, 2)
        self.lblName = QtGui.QLabel(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 2)
        self.lblBegDate = QtGui.QLabel(RBDiet)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 2, 0, 1, 2)
        self.edtBegDate = CDateEdit(RBDiet)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 2, 2, 1, 3)
        self.cmbEndAgeUnit = QtGui.QComboBox(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEndAgeUnit, 4, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 5)
        self.edtEndDate = CDateEdit(RBDiet)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 3, 2, 1, 3)
        self.cmbBegAgeUnit = QtGui.QComboBox(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBegAgeUnit, 4, 2, 1, 2)
        self.lblAgeSep = QtGui.QLabel(RBDiet)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout.addWidget(self.lblAgeSep, 4, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 9, 1, 1)
        self.lblAge = QtGui.QLabel(RBDiet)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 4, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(103, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(RBDiet)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 3, 0, 1, 2)
        self.lblCode = QtGui.QLabel(RBDiet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 0, 0, 1, 2)
        self.edtCode = QtGui.QLineEdit(RBDiet)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 0, 2, 1, 8)
        self.edtName = QtGui.QLineEdit(RBDiet)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 2, 1, 8)
        self.buttonBox = QtGui.QDialogButtonBox(RBDiet)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 10)
        self.lblName.setBuddy(self.edtName)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblCode.setBuddy(self.edtCode)

        self.retranslateUi(RBDiet)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBDiet.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBDiet.reject)
        QtCore.QMetaObject.connectSlotsByName(RBDiet)
        RBDiet.setTabOrder(self.edtCode, self.edtName)
        RBDiet.setTabOrder(self.edtName, self.edtBegDate)
        RBDiet.setTabOrder(self.edtBegDate, self.edtEndDate)
        RBDiet.setTabOrder(self.edtEndDate, self.cmbBegAgeUnit)
        RBDiet.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        RBDiet.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        RBDiet.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        RBDiet.setTabOrder(self.edtEndAgeCount, self.buttonBox)

    def retranslateUi(self, RBDiet):
        RBDiet.setWindowTitle(_translate("RBDiet", "ChangeMe!", None))
        self.edtEndAgeCount.setInputMask(_translate("RBDiet", "000; ", None))
        self.edtBegAgeCount.setInputMask(_translate("RBDiet", "000; ", None))
        self.lblName.setText(_translate("RBDiet", "&Наименование", None))
        self.lblBegDate.setText(_translate("RBDiet", "&Дата начала", None))
        self.edtBegDate.setDisplayFormat(_translate("RBDiet", "dd.MM.yyyy", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("RBDiet", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("RBDiet", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("RBDiet", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("RBDiet", "Г", None))
        self.edtEndDate.setDisplayFormat(_translate("RBDiet", "dd.MM.yyyy", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("RBDiet", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("RBDiet", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("RBDiet", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("RBDiet", "Г", None))
        self.lblAgeSep.setText(_translate("RBDiet", "по", None))
        self.lblAge.setText(_translate("RBDiet", "В&озраст", None))
        self.lblEndDate.setText(_translate("RBDiet", "Д&ата окончания", None))
        self.lblCode.setText(_translate("RBDiet", "&Код", None))

from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    RBDiet = QtGui.QDialog()
    ui = Ui_RBDiet()
    ui.setupUi(RBDiet)
    RBDiet.show()
    sys.exit(app.exec_())

