# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Events\AmbCardJournalPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AmbCardJournalPage(object):
    def setupUi(self, AmbCardJournalPage):
        AmbCardJournalPage.setObjectName(_fromUtf8("AmbCardJournalPage"))
        AmbCardJournalPage.resize(1048, 697)
        self.verticalLayout_2 = QtGui.QVBoxLayout(AmbCardJournalPage)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(AmbCardJournalPage)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pnlFilter = QtGui.QWidget(self.splitter_2)
        self.pnlFilter.setObjectName(_fromUtf8("pnlFilter"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pnlFilter)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblRelation = QtGui.QLabel(self.pnlFilter)
        self.lblRelation.setObjectName(_fromUtf8("lblRelation"))
        self.gridLayout_3.addWidget(self.lblRelation, 1, 0, 1, 1)
        self.cmbRelation = QtGui.QComboBox(self.pnlFilter)
        self.cmbRelation.setObjectName(_fromUtf8("cmbRelation"))
        self.cmbRelation.addItem(_fromUtf8(""))
        self.cmbRelation.addItem(_fromUtf8(""))
        self.cmbRelation.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbRelation, 1, 1, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblBegDateTime = QtGui.QLabel(self.pnlFilter)
        self.lblBegDateTime.setObjectName(_fromUtf8("lblBegDateTime"))
        self.horizontalLayout.addWidget(self.lblBegDateTime)
        self.frmEndDateTime = QtGui.QFrame(self.pnlFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtBegDate = CDateEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_4.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_4.addWidget(self.edtBegTime)
        self.horizontalLayout.addWidget(self.frmEndDateTime)
        self.lblEndDateTime = QtGui.QLabel(self.pnlFilter)
        self.lblEndDateTime.setObjectName(_fromUtf8("lblEndDateTime"))
        self.horizontalLayout.addWidget(self.lblEndDateTime)
        self.frmBegDateTime = QtGui.QFrame(self.pnlFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtEndDate = CDateEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_3.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_3.addWidget(self.edtEndTime)
        self.horizontalLayout.addWidget(self.frmBegDateTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.filterButtonBox = QtGui.QDialogButtonBox(self.pnlFilter)
        self.filterButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.filterButtonBox.setObjectName(_fromUtf8("filterButtonBox"))
        self.gridLayout_3.addWidget(self.filterButtonBox, 3, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.pnlFilter)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pnlEvents = QtGui.QWidget(self.splitter)
        self.pnlEvents.setObjectName(_fromUtf8("pnlEvents"))
        self.gridLayout = QtGui.QGridLayout(self.pnlEvents)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblLPU = QtGui.QLabel(self.pnlEvents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLPU.sizePolicy().hasHeightForWidth())
        self.lblLPU.setSizePolicy(sizePolicy)
        self.lblLPU.setObjectName(_fromUtf8("lblLPU"))
        self.gridLayout.addWidget(self.lblLPU, 0, 0, 1, 1)
        self.lblEventSetPerson = QtGui.QLabel(self.pnlEvents)
        self.lblEventSetPerson.setObjectName(_fromUtf8("lblEventSetPerson"))
        self.gridLayout.addWidget(self.lblEventSetPerson, 1, 0, 1, 1)
        self.lblEventType = QtGui.QLabel(self.pnlEvents)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 2, 0, 1, 1)
        self.cmbLPU = CPolyclinicComboBox(self.pnlEvents)
        self.cmbLPU.setObjectName(_fromUtf8("cmbLPU"))
        self.gridLayout.addWidget(self.cmbLPU, 0, 1, 1, 1)
        self.tblEvents = CTableView(self.pnlEvents)
        self.tblEvents.setObjectName(_fromUtf8("tblEvents"))
        self.gridLayout.addWidget(self.tblEvents, 3, 0, 1, 2)
        self.cmbEventSetPerson = CPersonComboBoxEx(self.pnlEvents)
        self.cmbEventSetPerson.setObjectName(_fromUtf8("cmbEventSetPerson"))
        self.gridLayout.addWidget(self.cmbEventSetPerson, 1, 1, 1, 1)
        self.cmbEventType = CRBComboBox(self.pnlEvents)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 2, 1, 1, 1)
        self.pnlActions = QtGui.QWidget(self.splitter)
        self.pnlActions.setObjectName(_fromUtf8("pnlActions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pnlActions)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblClass = QtGui.QLabel(self.pnlActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClass.sizePolicy().hasHeightForWidth())
        self.lblClass.setSizePolicy(sizePolicy)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout_2.addWidget(self.lblClass, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbClass = QtGui.QComboBox(self.pnlActions)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.cmbClass.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbClass)
        self.cbHaveTemplate = QtGui.QCheckBox(self.pnlActions)
        self.cbHaveTemplate.setChecked(True)
        self.cbHaveTemplate.setObjectName(_fromUtf8("cbHaveTemplate"))
        self.horizontalLayout_2.addWidget(self.cbHaveTemplate)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.lblActionType = QtGui.QLabel(self.pnlActions)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout_2.addWidget(self.lblActionType, 1, 0, 1, 1)
        self.cmbActionType = CActionTypeComboBox(self.pnlActions)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout_2.addWidget(self.cmbActionType, 1, 1, 1, 1)
        self.lblScene = QtGui.QLabel(self.pnlActions)
        self.lblScene.setObjectName(_fromUtf8("lblScene"))
        self.gridLayout_2.addWidget(self.lblScene, 2, 0, 1, 1)
        self.cmbScene = CRBComboBox(self.pnlActions)
        self.cmbScene.setObjectName(_fromUtf8("cmbScene"))
        self.gridLayout_2.addWidget(self.cmbScene, 2, 1, 1, 1)
        self.tblActions = CTableView(self.pnlActions)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.gridLayout_2.addWidget(self.tblActions, 3, 0, 1, 2)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 3)
        self.pnlAmbCardReport = QtGui.QWidget(self.splitter_2)
        self.pnlAmbCardReport.setObjectName(_fromUtf8("pnlAmbCardReport"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pnlAmbCardReport)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.txtAmbCardReport = CReportBrowser(self.pnlAmbCardReport)
        self.txtAmbCardReport.setObjectName(_fromUtf8("txtAmbCardReport"))
        self.gridLayout_4.addWidget(self.txtAmbCardReport, 1, 0, 1, 3)
        self.btnBack = QtGui.QPushButton(self.pnlAmbCardReport)
        self.btnBack.setEnabled(False)
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        self.gridLayout_4.addWidget(self.btnBack, 2, 0, 1, 1)
        self.btnNext = QtGui.QPushButton(self.pnlAmbCardReport)
        self.btnNext.setEnabled(False)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.gridLayout_4.addWidget(self.btnNext, 2, 2, 1, 1)
        self.btnSelect = QtGui.QPushButton(self.pnlAmbCardReport)
        self.btnSelect.setObjectName(_fromUtf8("btnSelect"))
        self.gridLayout_4.addWidget(self.btnSelect, 2, 1, 1, 1)
        self.lblTemplateName = QtGui.QLabel(self.pnlAmbCardReport)
        self.lblTemplateName.setObjectName(_fromUtf8("lblTemplateName"))
        self.gridLayout_4.addWidget(self.lblTemplateName, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter_2)

        self.retranslateUi(AmbCardJournalPage)
        QtCore.QMetaObject.connectSlotsByName(AmbCardJournalPage)
        AmbCardJournalPage.setTabOrder(self.edtBegDate, self.edtBegTime)
        AmbCardJournalPage.setTabOrder(self.edtBegTime, self.edtEndDate)
        AmbCardJournalPage.setTabOrder(self.edtEndDate, self.edtEndTime)
        AmbCardJournalPage.setTabOrder(self.edtEndTime, self.cmbLPU)
        AmbCardJournalPage.setTabOrder(self.cmbLPU, self.cmbEventSetPerson)
        AmbCardJournalPage.setTabOrder(self.cmbEventSetPerson, self.cmbEventType)
        AmbCardJournalPage.setTabOrder(self.cmbEventType, self.tblEvents)
        AmbCardJournalPage.setTabOrder(self.tblEvents, self.cmbClass)
        AmbCardJournalPage.setTabOrder(self.cmbClass, self.cmbActionType)
        AmbCardJournalPage.setTabOrder(self.cmbActionType, self.cmbScene)
        AmbCardJournalPage.setTabOrder(self.cmbScene, self.tblActions)
        AmbCardJournalPage.setTabOrder(self.tblActions, self.filterButtonBox)
        AmbCardJournalPage.setTabOrder(self.filterButtonBox, self.txtAmbCardReport)

    def retranslateUi(self, AmbCardJournalPage):
        AmbCardJournalPage.setWindowTitle(_translate("AmbCardJournalPage", "Form", None))
        self.lblRelation.setText(_translate("AmbCardJournalPage", "Связь с текущим Событием", None))
        self.cmbRelation.setItemText(0, _translate("AmbCardJournalPage", "Прямая", None))
        self.cmbRelation.setItemText(1, _translate("AmbCardJournalPage", "Обратная", None))
        self.cmbRelation.setItemText(2, _translate("AmbCardJournalPage", "Нет связи", None))
        self.lblBegDateTime.setText(_translate("AmbCardJournalPage", "С", None))
        self.edtBegDate.setWhatsThis(_translate("AmbCardJournalPage", "дата окончания осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("AmbCardJournalPage", "HH:mm", None))
        self.lblEndDateTime.setText(_translate("AmbCardJournalPage", "по", None))
        self.edtEndDate.setWhatsThis(_translate("AmbCardJournalPage", "дата начала осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("AmbCardJournalPage", "HH:mm", None))
        self.lblLPU.setText(_translate("AmbCardJournalPage", "ЛПУ", None))
        self.lblEventSetPerson.setText(_translate("AmbCardJournalPage", "Направитель", None))
        self.lblEventType.setText(_translate("AmbCardJournalPage", "Тип события", None))
        self.lblClass.setText(_translate("AmbCardJournalPage", "Класс", None))
        self.cmbClass.setItemText(0, _translate("AmbCardJournalPage", "Нет", None))
        self.cmbClass.setItemText(1, _translate("AmbCardJournalPage", "Статус", None))
        self.cmbClass.setItemText(2, _translate("AmbCardJournalPage", "Диагностика", None))
        self.cmbClass.setItemText(3, _translate("AmbCardJournalPage", "Лечение", None))
        self.cmbClass.setItemText(4, _translate("AmbCardJournalPage", "Прочие мероприятия", None))
        self.cbHaveTemplate.setText(_translate("AmbCardJournalPage", "Только заполненные шаблоны", None))
        self.lblActionType.setText(_translate("AmbCardJournalPage", "Тип действия", None))
        self.lblScene.setText(_translate("AmbCardJournalPage", "Место выполнения", None))
        self.btnBack.setText(_translate("AmbCardJournalPage", "<   Назад", None))
        self.btnNext.setText(_translate("AmbCardJournalPage", "Вперёд  >", None))
        self.btnSelect.setText(_translate("AmbCardJournalPage", "Шаблон", None))
        self.lblTemplateName.setText(_translate("AmbCardJournalPage", "TextLabel", None))

from Events.ActionTypeComboBox import CActionTypeComboBox
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Reports.ReportBrowser import CReportBrowser
from library.DateEdit import CDateEdit
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
