# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/natkuch/s11/Events/ActionTemplateCreateDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionTemplateCreateDialog(object):
    def setupUi(self, ActionTemplateCreateDialog):
        ActionTemplateCreateDialog.setObjectName(_fromUtf8("ActionTemplateCreateDialog"))
        ActionTemplateCreateDialog.resize(347, 310)
        ActionTemplateCreateDialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(ActionTemplateCreateDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbOwner = CPersonComboBoxEx(ActionTemplateCreateDialog)
        self.cmbOwner.setObjectName(_fromUtf8("cmbOwner"))
        self.gridLayout.addWidget(self.cmbOwner, 9, 2, 1, 6)
        self.rbVisibleToOrgStructure = QtGui.QRadioButton(ActionTemplateCreateDialog)
        self.rbVisibleToOrgStructure.setObjectName(_fromUtf8("rbVisibleToOrgStructure"))
        self.gridLayout.addWidget(self.rbVisibleToOrgStructure, 8, 0, 1, 2)
        self.rbVisibleToAll = QtGui.QRadioButton(ActionTemplateCreateDialog)
        self.rbVisibleToAll.setObjectName(_fromUtf8("rbVisibleToAll"))
        self.gridLayout.addWidget(self.rbVisibleToAll, 12, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ActionTemplateCreateDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 0, 1, 8)
        self.lblDiagnosis = QtGui.QLabel(ActionTemplateCreateDialog)
        self.lblDiagnosis.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagnosis.sizePolicy().hasHeightForWidth())
        self.lblDiagnosis.setSizePolicy(sizePolicy)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.gridLayout.addWidget(self.lblDiagnosis, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(ActionTemplateCreateDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 8)
        self.edtMKBList = QtGui.QLineEdit(ActionTemplateCreateDialog)
        self.edtMKBList.setEnabled(False)
        self.edtMKBList.setMinimumSize(QtCore.QSize(200, 0))
        self.edtMKBList.setObjectName(_fromUtf8("edtMKBList"))
        self.gridLayout.addWidget(self.edtMKBList, 5, 1, 1, 7)
        self.rbVisibleToOwner = QtGui.QRadioButton(ActionTemplateCreateDialog)
        self.rbVisibleToOwner.setChecked(True)
        self.rbVisibleToOwner.setObjectName(_fromUtf8("rbVisibleToOwner"))
        self.gridLayout.addWidget(self.rbVisibleToOwner, 9, 0, 1, 2)
        self.lblName = QtGui.QLabel(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.line = QtGui.QFrame(ActionTemplateCreateDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 8)
        self.edtName = QtGui.QLineEdit(ActionTemplateCreateDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 0, 1, 1, 7)
        self.lblVisibleTo = QtGui.QLabel(ActionTemplateCreateDialog)
        self.lblVisibleTo.setObjectName(_fromUtf8("lblVisibleTo"))
        self.gridLayout.addWidget(self.lblVisibleTo, 7, 0, 1, 8)
        self.edtEndAgeCount = QtGui.QLineEdit(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridLayout.addWidget(self.edtEndAgeCount, 4, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(203, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 7, 1, 1)
        self.lblAgeSep = QtGui.QLabel(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeSep.sizePolicy().hasHeightForWidth())
        self.lblAgeSep.setSizePolicy(sizePolicy)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridLayout.addWidget(self.lblAgeSep, 4, 4, 1, 1)
        self.cmbEndAgeUnit = QtGui.QComboBox(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEndAgeUnit, 4, 5, 1, 1)
        self.lblAge = QtGui.QLabel(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 4, 0, 1, 1)
        self.lblSex = QtGui.QLabel(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 3, 0, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBegAgeUnit, 4, 1, 1, 2)
        self.cmbSex = QtGui.QComboBox(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 3, 1, 1, 2)
        self.edtBegAgeCount = QtGui.QLineEdit(ActionTemplateCreateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridLayout.addWidget(self.edtBegAgeCount, 4, 3, 1, 1)
        self.lblCase = QtGui.QLabel(ActionTemplateCreateDialog)
        self.lblCase.setObjectName(_fromUtf8("lblCase"))
        self.gridLayout.addWidget(self.lblCase, 2, 0, 1, 8)
        spacerItem1 = QtGui.QSpacerItem(415, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 5)
        self.rbVisibleToSpeciality = QtGui.QRadioButton(ActionTemplateCreateDialog)
        self.rbVisibleToSpeciality.setObjectName(_fromUtf8("rbVisibleToSpeciality"))
        self.gridLayout.addWidget(self.rbVisibleToSpeciality, 10, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 13, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 10, 7, 1, 1)
        self.cmbSpeciality = CRBComboBox(ActionTemplateCreateDialog)
        self.cmbSpeciality.setEnabled(False)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 10, 2, 1, 5)
        self.cmbOrgStructure = COrgStructureComboBox(ActionTemplateCreateDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 8, 2, 1, 6)
        self.rbVisibleToSNILS = QtGui.QRadioButton(ActionTemplateCreateDialog)
        self.rbVisibleToSNILS.setObjectName(_fromUtf8("rbVisibleToSNILS"))
        self.gridLayout.addWidget(self.rbVisibleToSNILS, 11, 0, 1, 8)
        self.lblDiagnosis.setBuddy(self.edtMKBList)
        self.lblName.setBuddy(self.edtName)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblSex.setBuddy(self.cmbSex)

        self.retranslateUi(ActionTemplateCreateDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActionTemplateCreateDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActionTemplateCreateDialog.reject)
        QtCore.QObject.connect(self.rbVisibleToOwner, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOwner.setEnabled)
        QtCore.QObject.connect(self.rbVisibleToSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSpeciality.setEnabled)
        QtCore.QObject.connect(self.rbVisibleToOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbOrgStructure.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ActionTemplateCreateDialog)
        ActionTemplateCreateDialog.setTabOrder(self.edtName, self.cmbSex)
        ActionTemplateCreateDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        ActionTemplateCreateDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        ActionTemplateCreateDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        ActionTemplateCreateDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        ActionTemplateCreateDialog.setTabOrder(self.edtEndAgeCount, self.edtMKBList)
        ActionTemplateCreateDialog.setTabOrder(self.edtMKBList, self.rbVisibleToOrgStructure)
        ActionTemplateCreateDialog.setTabOrder(self.rbVisibleToOrgStructure, self.cmbOrgStructure)
        ActionTemplateCreateDialog.setTabOrder(self.cmbOrgStructure, self.rbVisibleToOwner)
        ActionTemplateCreateDialog.setTabOrder(self.rbVisibleToOwner, self.cmbOwner)
        ActionTemplateCreateDialog.setTabOrder(self.cmbOwner, self.rbVisibleToSpeciality)
        ActionTemplateCreateDialog.setTabOrder(self.rbVisibleToSpeciality, self.cmbSpeciality)
        ActionTemplateCreateDialog.setTabOrder(self.cmbSpeciality, self.rbVisibleToAll)
        ActionTemplateCreateDialog.setTabOrder(self.rbVisibleToAll, self.buttonBox)

    def retranslateUi(self, ActionTemplateCreateDialog):
        ActionTemplateCreateDialog.setWindowTitle(_translate("ActionTemplateCreateDialog", "Создание шаблона действия", None))
        self.rbVisibleToOrgStructure.setText(_translate("ActionTemplateCreateDialog", "Подразделение", None))
        self.rbVisibleToAll.setText(_translate("ActionTemplateCreateDialog", "Все", None))
        self.lblDiagnosis.setText(_translate("ActionTemplateCreateDialog", "&Диагнозы", None))
        self.rbVisibleToOwner.setText(_translate("ActionTemplateCreateDialog", "Врач", None))
        self.lblName.setText(_translate("ActionTemplateCreateDialog", "На&именование", None))
        self.lblVisibleTo.setText(_translate("ActionTemplateCreateDialog", "Этот шаблон могут применять:", None))
        self.edtEndAgeCount.setInputMask(_translate("ActionTemplateCreateDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("ActionTemplateCreateDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ActionTemplateCreateDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ActionTemplateCreateDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ActionTemplateCreateDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ActionTemplateCreateDialog", "Г", None))
        self.lblAge.setText(_translate("ActionTemplateCreateDialog", "&Возраст", None))
        self.lblSex.setText(_translate("ActionTemplateCreateDialog", "&Пол", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ActionTemplateCreateDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ActionTemplateCreateDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ActionTemplateCreateDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ActionTemplateCreateDialog", "Г", None))
        self.cmbSex.setItemText(1, _translate("ActionTemplateCreateDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ActionTemplateCreateDialog", "Ж", None))
        self.edtBegAgeCount.setInputMask(_translate("ActionTemplateCreateDialog", "000; ", None))
        self.lblCase.setText(_translate("ActionTemplateCreateDialog", "Этот шаблон можно применять в случаях:", None))
        self.rbVisibleToSpeciality.setText(_translate("ActionTemplateCreateDialog", "Специальность", None))
        self.rbVisibleToSNILS.setText(_translate("ActionTemplateCreateDialog", "По СНИЛС", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ActionTemplateCreateDialog = QtGui.QDialog()
    ui = Ui_ActionTemplateCreateDialog()
    ui.setupUi(ActionTemplateCreateDialog)
    ActionTemplateCreateDialog.show()
    sys.exit(app.exec_())

