# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\Events\ActionsPage.ui'
#
# Created: Thu Aug 17 14:35:36 2023
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionsPageWidget(object):
    def setupUi(self, ActionsPageWidget):
        ActionsPageWidget.setObjectName(_fromUtf8("ActionsPageWidget"))
        ActionsPageWidget.resize(1324, 725)
        self.gridLayoutAP = QtGui.QGridLayout(ActionsPageWidget)
        self.gridLayoutAP.setMargin(4)
        self.gridLayoutAP.setSpacing(4)
        self.gridLayoutAP.setObjectName(_fromUtf8("gridLayoutAP"))
        self.splitterAP = QtGui.QSplitter(ActionsPageWidget)
        self.splitterAP.setOrientation(QtCore.Qt.Horizontal)
        self.splitterAP.setChildrenCollapsible(False)
        self.splitterAP.setObjectName(_fromUtf8("splitterAP"))
        self.tblAPActions = CActionsTableView(self.splitterAP)
        self.tblAPActions.setObjectName(_fromUtf8("tblAPActions"))
        self.frameAP = QtGui.QFrame(self.splitterAP)
        self.frameAP.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAP.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameAP.setObjectName(_fromUtf8("frameAP"))
        self.gridLayout = QtGui.QGridLayout(self.frameAP)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnPlanNextAction = QtGui.QToolButton(self.frameAP)
        self.btnPlanNextAction.setEnabled(False)
        self.btnPlanNextAction.setObjectName(_fromUtf8("btnPlanNextAction"))
        self.gridLayout.addWidget(self.btnPlanNextAction, 8, 13, 1, 1)
        self.lblAPStatus = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPStatus.sizePolicy().hasHeightForWidth())
        self.lblAPStatus.setSizePolicy(sizePolicy)
        self.lblAPStatus.setObjectName(_fromUtf8("lblAPStatus"))
        self.gridLayout.addWidget(self.lblAPStatus, 3, 0, 1, 1)
        self.btnAPNomenclatureExpense = QtGui.QPushButton(self.frameAP)
        self.btnAPNomenclatureExpense.setObjectName(_fromUtf8("btnAPNomenclatureExpense"))
        self.gridLayout.addWidget(self.btnAPNomenclatureExpense, 8, 14, 1, 1)
        self.lblAPDirectionDate = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPDirectionDate.sizePolicy().hasHeightForWidth())
        self.lblAPDirectionDate.setSizePolicy(sizePolicy)
        self.lblAPDirectionDate.setObjectName(_fromUtf8("lblAPDirectionDate"))
        self.gridLayout.addWidget(self.lblAPDirectionDate, 0, 0, 1, 1)
        self.btnNextAction = QtGui.QPushButton(self.frameAP)
        self.btnNextAction.setEnabled(False)
        self.btnNextAction.setObjectName(_fromUtf8("btnNextAction"))
        self.gridLayout.addWidget(self.btnNextAction, 8, 11, 1, 1)
        self.lblAPCoordDate = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPCoordDate.sizePolicy().hasHeightForWidth())
        self.lblAPCoordDate.setSizePolicy(sizePolicy)
        self.lblAPCoordDate.setObjectName(_fromUtf8("lblAPCoordDate"))
        self.gridLayout.addWidget(self.lblAPCoordDate, 13, 0, 1, 1)
        self.lblAPPerson = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPerson.sizePolicy().hasHeightForWidth())
        self.lblAPPerson.setSizePolicy(sizePolicy)
        self.lblAPPerson.setObjectName(_fromUtf8("lblAPPerson"))
        self.gridLayout.addWidget(self.lblAPPerson, 6, 0, 1, 1)
        self.lblAPOrg = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOrg.sizePolicy().hasHeightForWidth())
        self.lblAPOrg.setSizePolicy(sizePolicy)
        self.lblAPOrg.setObjectName(_fromUtf8("lblAPOrg"))
        self.gridLayout.addWidget(self.lblAPOrg, 2, 0, 1, 1)
        self.lblAPNote = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPNote.sizePolicy().hasHeightForWidth())
        self.lblAPNote.setSizePolicy(sizePolicy)
        self.lblAPNote.setObjectName(_fromUtf8("lblAPNote"))
        self.gridLayout.addWidget(self.lblAPNote, 8, 0, 1, 1)
        self.cmbAPOrg = CPolyclinicComboBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPOrg.sizePolicy().hasHeightForWidth())
        self.cmbAPOrg.setSizePolicy(sizePolicy)
        self.cmbAPOrg.setObjectName(_fromUtf8("cmbAPOrg"))
        self.cmbAPOrg.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAPOrg, 2, 1, 1, 2)
        self.btnAPSelectOrg = QtGui.QToolButton(self.frameAP)
        self.btnAPSelectOrg.setObjectName(_fromUtf8("btnAPSelectOrg"))
        self.gridLayout.addWidget(self.btnAPSelectOrg, 2, 3, 1, 1)
        self.lblAPCoordText = QtGui.QLabel(self.frameAP)
        self.lblAPCoordText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAPCoordText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAPCoordText.setText(_fromUtf8(""))
        self.lblAPCoordText.setObjectName(_fromUtf8("lblAPCoordText"))
        self.gridLayout.addWidget(self.lblAPCoordText, 13, 2, 1, 9)
        self.tblAPProps = CActionPropertiesTableView(self.frameAP)
        self.tblAPProps.setEnabled(False)
        self.tblAPProps.setAutoScroll(True)
        self.tblAPProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setObjectName(_fromUtf8("tblAPProps"))
        self.gridLayout.addWidget(self.tblAPProps, 16, 0, 1, 15)
        self.btnAPQueueManagement = QtGui.QPushButton(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAPQueueManagement.sizePolicy().hasHeightForWidth())
        self.btnAPQueueManagement.setSizePolicy(sizePolicy)
        self.btnAPQueueManagement.setObjectName(_fromUtf8("btnAPQueueManagement"))
        self.gridLayout.addWidget(self.btnAPQueueManagement, 8, 12, 1, 1)
        self.edtAPNote = QtGui.QLineEdit(self.frameAP)
        self.edtAPNote.setObjectName(_fromUtf8("edtAPNote"))
        self.gridLayout.addWidget(self.edtAPNote, 8, 1, 1, 10)
        self.lblAPOrgStructure = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblAPOrgStructure.setSizePolicy(sizePolicy)
        self.lblAPOrgStructure.setObjectName(_fromUtf8("lblAPOrgStructure"))
        self.gridLayout.addWidget(self.lblAPOrgStructure, 7, 0, 1, 1)
        self.lblActionSpecification = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionSpecification.sizePolicy().hasHeightForWidth())
        self.lblActionSpecification.setSizePolicy(sizePolicy)
        self.lblActionSpecification.setObjectName(_fromUtf8("lblActionSpecification"))
        self.gridLayout.addWidget(self.lblActionSpecification, 14, 0, 1, 2)
        self.cmbActionSpecification = CRBComboBox(self.frameAP)
        self.cmbActionSpecification.setObjectName(_fromUtf8("cmbActionSpecification"))
        self.gridLayout.addWidget(self.cmbActionSpecification, 14, 2, 1, 9)
        self.pnlMainAPMKBWidgets = QtGui.QWidget(self.frameAP)
        self.pnlMainAPMKBWidgets.setObjectName(_fromUtf8("pnlMainAPMKBWidgets"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.pnlMainAPMKBWidgets)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pnlAPMKBWidgets = QtGui.QWidget(self.pnlMainAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlAPMKBWidgets.sizePolicy().hasHeightForWidth())
        self.pnlAPMKBWidgets.setSizePolicy(sizePolicy)
        self.pnlAPMKBWidgets.setObjectName(_fromUtf8("pnlAPMKBWidgets"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.pnlAPMKBWidgets)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lblAPMorphologyMKB = QtGui.QLabel(self.pnlAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.lblAPMorphologyMKB.setObjectName(_fromUtf8("lblAPMorphologyMKB"))
        self.horizontalLayout_9.addWidget(self.lblAPMorphologyMKB)
        self.cmbAPMorphologyMKB = CICDMorphologyCodeEditEx(self.pnlAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.cmbAPMorphologyMKB.setMinimumSize(QtCore.QSize(0, 0))
        self.cmbAPMorphologyMKB.setObjectName(_fromUtf8("cmbAPMorphologyMKB"))
        self.horizontalLayout_9.addWidget(self.cmbAPMorphologyMKB)
        self.lblAPMKB = QtGui.QLabel(self.pnlAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMKB.setSizePolicy(sizePolicy)
        self.lblAPMKB.setObjectName(_fromUtf8("lblAPMKB"))
        self.horizontalLayout_9.addWidget(self.lblAPMKB)
        self.cmbAPMKB = CICDCodeEditEx(self.pnlAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMKB.setSizePolicy(sizePolicy)
        self.cmbAPMKB.setObjectName(_fromUtf8("cmbAPMKB"))
        self.horizontalLayout_9.addWidget(self.cmbAPMKB)
        self.horizontalLayout_10.addWidget(self.pnlAPMKBWidgets)
        self.lblAPMKBExSubclass = QtGui.QLabel(self.pnlMainAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKBExSubclass.sizePolicy().hasHeightForWidth())
        self.lblAPMKBExSubclass.setSizePolicy(sizePolicy)
        self.lblAPMKBExSubclass.setObjectName(_fromUtf8("lblAPMKBExSubclass"))
        self.horizontalLayout_10.addWidget(self.lblAPMKBExSubclass)
        self.cmbAPMKBExSubclass = CMKBExSubclassComboBox(self.pnlMainAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMKBExSubclass.sizePolicy().hasHeightForWidth())
        self.cmbAPMKBExSubclass.setSizePolicy(sizePolicy)
        self.cmbAPMKBExSubclass.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbAPMKBExSubclass.setObjectName(_fromUtf8("cmbAPMKBExSubclass"))
        self.horizontalLayout_10.addWidget(self.cmbAPMKBExSubclass)
        self.lblAPMKBText = QtGui.QLabel(self.pnlMainAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKBText.sizePolicy().hasHeightForWidth())
        self.lblAPMKBText.setSizePolicy(sizePolicy)
        self.lblAPMKBText.setText(_fromUtf8(""))
        self.lblAPMKBText.setWordWrap(True)
        self.lblAPMKBText.setObjectName(_fromUtf8("lblAPMKBText"))
        self.horizontalLayout_10.addWidget(self.lblAPMKBText)
        self.gridLayout.addWidget(self.pnlMainAPMKBWidgets, 2, 8, 1, 7)
        self.frmAPButtonsBar = QtGui.QFrame(self.frameAP)
        self.frmAPButtonsBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPButtonsBar.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPButtonsBar.setLineWidth(0)
        self.frmAPButtonsBar.setObjectName(_fromUtf8("frmAPButtonsBar"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmAPButtonsBar)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAPHospitalOrderSelect = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPHospitalOrderSelect.setObjectName(_fromUtf8("btnAPHospitalOrderSelect"))
        self.horizontalLayout_4.addWidget(self.btnAPHospitalOrderSelect)
        self.btnAPPrint = CPrintButton(self.frmAPButtonsBar)
        self.btnAPPrint.setObjectName(_fromUtf8("btnAPPrint"))
        self.horizontalLayout_4.addWidget(self.btnAPPrint)
        self.btnAPLoadTemplate = CActionTemplateSelectButton(self.frmAPButtonsBar)
        self.btnAPLoadTemplate.setObjectName(_fromUtf8("btnAPLoadTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadTemplate)
        self.btnAPSaveAsTemplate = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPSaveAsTemplate.setObjectName(_fromUtf8("btnAPSaveAsTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPSaveAsTemplate)
        self.btnAPLoadPrevAction = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPLoadPrevAction.setEnabled(False)
        self.btnAPLoadPrevAction.setObjectName(_fromUtf8("btnAPLoadPrevAction"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadPrevAction)
        self.btnAPAttachedFiles = CAttachButton(self.frmAPButtonsBar)
        self.btnAPAttachedFiles.setFlat(False)
        self.btnAPAttachedFiles.setObjectName(_fromUtf8("btnAPAttachedFiles"))
        self.horizontalLayout_4.addWidget(self.btnAPAttachedFiles)
        spacerItem = QtGui.QSpacerItem(145, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addWidget(self.frmAPButtonsBar, 17, 0, 1, 15)
        self.frmAPCoordDate = QtGui.QFrame(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPCoordDate.sizePolicy().hasHeightForWidth())
        self.frmAPCoordDate.setSizePolicy(sizePolicy)
        self.frmAPCoordDate.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPCoordDate.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPCoordDate.setObjectName(_fromUtf8("frmAPCoordDate"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmAPCoordDate)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtAPCoordDate = CDateEdit(self.frmAPCoordDate)
        self.edtAPCoordDate.setEnabled(False)
        self.edtAPCoordDate.setCalendarPopup(True)
        self.edtAPCoordDate.setObjectName(_fromUtf8("edtAPCoordDate"))
        self.horizontalLayout_6.addWidget(self.edtAPCoordDate)
        self.edtAPCoordTime = QtGui.QTimeEdit(self.frmAPCoordDate)
        self.edtAPCoordTime.setEnabled(False)
        self.edtAPCoordTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPCoordTime.setObjectName(_fromUtf8("edtAPCoordTime"))
        self.horizontalLayout_6.addWidget(self.edtAPCoordTime)
        self.gridLayout.addWidget(self.frmAPCoordDate, 13, 1, 1, 1)
        self.frmTop = QtGui.QWidget(self.frameAP)
        self.frmTop.setObjectName(_fromUtf8("frmTop"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmTop)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frmAPDirectionDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPDirectionDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPDirectionDateTime.setSizePolicy(sizePolicy)
        self.frmAPDirectionDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPDirectionDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPDirectionDateTime.setObjectName(_fromUtf8("frmAPDirectionDateTime"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmAPDirectionDateTime)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtAPDirectionDate = CDateEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDirectionDate.sizePolicy().hasHeightForWidth())
        self.edtAPDirectionDate.setSizePolicy(sizePolicy)
        self.edtAPDirectionDate.setCalendarPopup(True)
        self.edtAPDirectionDate.setObjectName(_fromUtf8("edtAPDirectionDate"))
        self.horizontalLayout.addWidget(self.edtAPDirectionDate)
        self.edtAPDirectionTime = CTimeEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDirectionTime.sizePolicy().hasHeightForWidth())
        self.edtAPDirectionTime.setSizePolicy(sizePolicy)
        self.edtAPDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPDirectionTime.setObjectName(_fromUtf8("edtAPDirectionTime"))
        self.horizontalLayout.addWidget(self.edtAPDirectionTime)
        self.horizontalLayout_7.addWidget(self.frmAPDirectionDateTime)
        self.chkAPIsUrgent = QtGui.QCheckBox(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAPIsUrgent.sizePolicy().hasHeightForWidth())
        self.chkAPIsUrgent.setSizePolicy(sizePolicy)
        self.chkAPIsUrgent.setObjectName(_fromUtf8("chkAPIsUrgent"))
        self.horizontalLayout_7.addWidget(self.chkAPIsUrgent)
        self.lblAPSetPerson = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPSetPerson.sizePolicy().hasHeightForWidth())
        self.lblAPSetPerson.setSizePolicy(sizePolicy)
        self.lblAPSetPerson.setObjectName(_fromUtf8("lblAPSetPerson"))
        self.horizontalLayout_7.addWidget(self.lblAPSetPerson)
        self.cmbAPSetPerson = CPersonWithOrgListComboBoxEx(self.frmTop)
        self.cmbAPSetPerson.setObjectName(_fromUtf8("cmbAPSetPerson"))
        self.cmbAPSetPerson.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmbAPSetPerson)
        self.lblAPPlannedEndDate = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.lblAPPlannedEndDate.setSizePolicy(sizePolicy)
        self.lblAPPlannedEndDate.setObjectName(_fromUtf8("lblAPPlannedEndDate"))
        self.horizontalLayout_7.addWidget(self.lblAPPlannedEndDate)
        self.frmAPPlannedEndDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPPlannedEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPPlannedEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPPlannedEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPPlannedEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPPlannedEndDateTime.setObjectName(_fromUtf8("frmAPPlannedEndDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmAPPlannedEndDateTime)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtAPPlannedEndDate = CDateEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.edtAPPlannedEndDate.setSizePolicy(sizePolicy)
        self.edtAPPlannedEndDate.setCalendarPopup(True)
        self.edtAPPlannedEndDate.setObjectName(_fromUtf8("edtAPPlannedEndDate"))
        self.horizontalLayout_5.addWidget(self.edtAPPlannedEndDate)
        self.edtAPPlannedEndTime = QtGui.QTimeEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPlannedEndTime.sizePolicy().hasHeightForWidth())
        self.edtAPPlannedEndTime.setSizePolicy(sizePolicy)
        self.edtAPPlannedEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPPlannedEndTime.setObjectName(_fromUtf8("edtAPPlannedEndTime"))
        self.horizontalLayout_5.addWidget(self.edtAPPlannedEndTime)
        self.horizontalLayout_7.addWidget(self.frmAPPlannedEndDateTime)
        self.gridLayout.addWidget(self.frmTop, 0, 1, 1, 14)
        self.frmMiddle = QtGui.QWidget(self.frameAP)
        self.frmMiddle.setObjectName(_fromUtf8("frmMiddle"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmMiddle)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.cmbAPStatus = CActionStatusComboBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPStatus.sizePolicy().hasHeightForWidth())
        self.cmbAPStatus.setSizePolicy(sizePolicy)
        self.cmbAPStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbAPStatus.setObjectName(_fromUtf8("cmbAPStatus"))
        self.horizontalLayout_8.addWidget(self.cmbAPStatus)
        self.frmAPBegDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPBegDateTime.setSizePolicy(sizePolicy)
        self.frmAPBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPBegDateTime.setObjectName(_fromUtf8("frmAPBegDateTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmAPBegDateTime)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblAPBegDate = QtGui.QLabel(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPBegDate.sizePolicy().hasHeightForWidth())
        self.lblAPBegDate.setSizePolicy(sizePolicy)
        self.lblAPBegDate.setObjectName(_fromUtf8("lblAPBegDate"))
        self.horizontalLayout_2.addWidget(self.lblAPBegDate)
        self.edtAPBegDate = CDateEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegDate.sizePolicy().hasHeightForWidth())
        self.edtAPBegDate.setSizePolicy(sizePolicy)
        self.edtAPBegDate.setCalendarPopup(True)
        self.edtAPBegDate.setObjectName(_fromUtf8("edtAPBegDate"))
        self.horizontalLayout_2.addWidget(self.edtAPBegDate)
        self.edtAPBegTime = CTimeEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegTime.sizePolicy().hasHeightForWidth())
        self.edtAPBegTime.setSizePolicy(sizePolicy)
        self.edtAPBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPBegTime.setObjectName(_fromUtf8("edtAPBegTime"))
        self.horizontalLayout_2.addWidget(self.edtAPBegTime)
        self.horizontalLayout_8.addWidget(self.frmAPBegDateTime)
        self.frmAPEndDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPEndDateTime.setObjectName(_fromUtf8("frmAPEndDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmAPEndDateTime)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblAPEndDate = QtGui.QLabel(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPEndDate.sizePolicy().hasHeightForWidth())
        self.lblAPEndDate.setSizePolicy(sizePolicy)
        self.lblAPEndDate.setObjectName(_fromUtf8("lblAPEndDate"))
        self.horizontalLayout_3.addWidget(self.lblAPEndDate)
        self.edtAPEndDate = CDateEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPEndDate.sizePolicy().hasHeightForWidth())
        self.edtAPEndDate.setSizePolicy(sizePolicy)
        self.edtAPEndDate.setCalendarPopup(True)
        self.edtAPEndDate.setObjectName(_fromUtf8("edtAPEndDate"))
        self.horizontalLayout_3.addWidget(self.edtAPEndDate)
        self.edtAPEndTime = CTimeEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPEndTime.sizePolicy().hasHeightForWidth())
        self.edtAPEndTime.setSizePolicy(sizePolicy)
        self.edtAPEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPEndTime.setObjectName(_fromUtf8("edtAPEndTime"))
        self.horizontalLayout_3.addWidget(self.edtAPEndTime)
        self.horizontalLayout_8.addWidget(self.frmAPEndDateTime)
        self.lblAPAmount = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAmount.sizePolicy().hasHeightForWidth())
        self.lblAPAmount.setSizePolicy(sizePolicy)
        self.lblAPAmount.setObjectName(_fromUtf8("lblAPAmount"))
        self.horizontalLayout_8.addWidget(self.lblAPAmount)
        self.edtAPAmount = QtGui.QDoubleSpinBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPAmount.sizePolicy().hasHeightForWidth())
        self.edtAPAmount.setSizePolicy(sizePolicy)
        self.edtAPAmount.setMaximum(999.99)
        self.edtAPAmount.setObjectName(_fromUtf8("edtAPAmount"))
        self.horizontalLayout_8.addWidget(self.edtAPAmount)
        self.lblAPUet = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPUet.sizePolicy().hasHeightForWidth())
        self.lblAPUet.setSizePolicy(sizePolicy)
        self.lblAPUet.setObjectName(_fromUtf8("lblAPUet"))
        self.horizontalLayout_8.addWidget(self.lblAPUet)
        self.edtAPUet = QtGui.QDoubleSpinBox(self.frmMiddle)
        self.edtAPUet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPUet.sizePolicy().hasHeightForWidth())
        self.edtAPUet.setSizePolicy(sizePolicy)
        self.edtAPUet.setReadOnly(True)
        self.edtAPUet.setMaximum(1000.0)
        self.edtAPUet.setSingleStep(0.5)
        self.edtAPUet.setObjectName(_fromUtf8("edtAPUet"))
        self.horizontalLayout_8.addWidget(self.edtAPUet)
        self.lblAPOffice = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOffice.sizePolicy().hasHeightForWidth())
        self.lblAPOffice.setSizePolicy(sizePolicy)
        self.lblAPOffice.setObjectName(_fromUtf8("lblAPOffice"))
        self.horizontalLayout_8.addWidget(self.lblAPOffice)
        self.edtAPOffice = QtGui.QLineEdit(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPOffice.sizePolicy().hasHeightForWidth())
        self.edtAPOffice.setSizePolicy(sizePolicy)
        self.edtAPOffice.setMaxLength(16)
        self.edtAPOffice.setObjectName(_fromUtf8("edtAPOffice"))
        self.horizontalLayout_8.addWidget(self.edtAPOffice)
        self.gridLayout.addWidget(self.frmMiddle, 3, 1, 1, 14)
        self.pnlCSG = QtGui.QWidget(self.frameAP)
        self.pnlCSG.setObjectName(_fromUtf8("pnlCSG"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.pnlCSG)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lblCSG = QtGui.QLabel(self.pnlCSG)
        self.lblCSG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCSG.sizePolicy().hasHeightForWidth())
        self.lblCSG.setSizePolicy(sizePolicy)
        self.lblCSG.setMinimumSize(QtCore.QSize(35, 0))
        self.lblCSG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCSG.setObjectName(_fromUtf8("lblCSG"))
        self.horizontalLayout_12.addWidget(self.lblCSG)
        self.cmbCSG = CActionCSGComboBox(self.pnlCSG)
        self.cmbCSG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCSG.sizePolicy().hasHeightForWidth())
        self.cmbCSG.setSizePolicy(sizePolicy)
        self.cmbCSG.setObjectName(_fromUtf8("cmbCSG"))
        self.horizontalLayout_12.addWidget(self.cmbCSG)
        self.gridLayout.addWidget(self.pnlCSG, 13, 11, 1, 4)
        self.cmbAPPerson = CPersonWithOrgListComboBoxEx(self.frameAP)
        self.cmbAPPerson.setObjectName(_fromUtf8("cmbAPPerson"))
        self.cmbAPPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAPPerson, 6, 1, 1, 14)
        self.cmbAPOrgStructure = COrgStructureComboBox(self.frameAP)
        self.cmbAPOrgStructure.setObjectName(_fromUtf8("cmbAPOrgStructure"))
        self.gridLayout.addWidget(self.cmbAPOrgStructure, 7, 1, 1, 2)
        self.lblAPAssistant = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAssistant.sizePolicy().hasHeightForWidth())
        self.lblAPAssistant.setSizePolicy(sizePolicy)
        self.lblAPAssistant.setObjectName(_fromUtf8("lblAPAssistant"))
        self.gridLayout.addWidget(self.lblAPAssistant, 7, 3, 1, 1)
        self.cmbAPAssistant = CPersonWithOrgListComboBoxEx(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPAssistant.sizePolicy().hasHeightForWidth())
        self.cmbAPAssistant.setSizePolicy(sizePolicy)
        self.cmbAPAssistant.setObjectName(_fromUtf8("cmbAPAssistant"))
        self.cmbAPAssistant.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAPAssistant, 7, 4, 1, 1)
        self.lblAPQuantity = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPQuantity.sizePolicy().hasHeightForWidth())
        self.lblAPQuantity.setSizePolicy(sizePolicy)
        self.lblAPQuantity.setObjectName(_fromUtf8("lblAPQuantity"))
        self.gridLayout.addWidget(self.lblAPQuantity, 7, 5, 1, 1)
        self.edtAPQuantity = QtGui.QDoubleSpinBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPQuantity.sizePolicy().hasHeightForWidth())
        self.edtAPQuantity.setSizePolicy(sizePolicy)
        self.edtAPQuantity.setMaximum(999.99)
        self.edtAPQuantity.setObjectName(_fromUtf8("edtAPQuantity"))
        self.gridLayout.addWidget(self.edtAPQuantity, 7, 6, 1, 1)
        self.lblAPDuration = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPDuration.sizePolicy().hasHeightForWidth())
        self.lblAPDuration.setSizePolicy(sizePolicy)
        self.lblAPDuration.setObjectName(_fromUtf8("lblAPDuration"))
        self.gridLayout.addWidget(self.lblAPDuration, 7, 7, 1, 1)
        self.edtAPDuration = QtGui.QSpinBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDuration.sizePolicy().hasHeightForWidth())
        self.edtAPDuration.setSizePolicy(sizePolicy)
        self.edtAPDuration.setObjectName(_fromUtf8("edtAPDuration"))
        self.gridLayout.addWidget(self.edtAPDuration, 7, 8, 1, 1)
        self.lblAPPeriodicity = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPeriodicity.sizePolicy().hasHeightForWidth())
        self.lblAPPeriodicity.setSizePolicy(sizePolicy)
        self.lblAPPeriodicity.setObjectName(_fromUtf8("lblAPPeriodicity"))
        self.gridLayout.addWidget(self.lblAPPeriodicity, 7, 9, 1, 1)
        self.edtAPPeriodicity = QtGui.QSpinBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPeriodicity.sizePolicy().hasHeightForWidth())
        self.edtAPPeriodicity.setSizePolicy(sizePolicy)
        self.edtAPPeriodicity.setObjectName(_fromUtf8("edtAPPeriodicity"))
        self.gridLayout.addWidget(self.edtAPPeriodicity, 7, 10, 1, 1)
        self.lblAPAliquoticity = QtGui.QLabel(self.frameAP)
        self.lblAPAliquoticity.setObjectName(_fromUtf8("lblAPAliquoticity"))
        self.gridLayout.addWidget(self.lblAPAliquoticity, 7, 11, 1, 1)
        self.edtAPAliquoticity = QtGui.QSpinBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPAliquoticity.sizePolicy().hasHeightForWidth())
        self.edtAPAliquoticity.setSizePolicy(sizePolicy)
        self.edtAPAliquoticity.setObjectName(_fromUtf8("edtAPAliquoticity"))
        self.gridLayout.addWidget(self.edtAPAliquoticity, 7, 12, 1, 1)
        self.gridLayoutAP.addWidget(self.splitterAP, 0, 0, 1, 1)
        self.lblAPStatus.setBuddy(self.cmbAPStatus)
        self.lblAPDirectionDate.setBuddy(self.edtAPDirectionDate)
        self.lblAPCoordDate.setBuddy(self.edtAPCoordDate)
        self.lblAPPerson.setBuddy(self.cmbAPPerson)
        self.lblAPNote.setBuddy(self.edtAPNote)
        self.lblActionSpecification.setBuddy(self.cmbActionSpecification)
        self.lblAPMKBExSubclass.setBuddy(self.cmbAPMKBExSubclass)
        self.lblAPSetPerson.setBuddy(self.cmbAPSetPerson)
        self.lblAPPlannedEndDate.setBuddy(self.edtAPPlannedEndDate)
        self.lblAPBegDate.setBuddy(self.edtAPBegDate)
        self.lblAPEndDate.setBuddy(self.edtAPEndDate)
        self.lblAPAmount.setBuddy(self.edtAPAmount)
        self.lblAPUet.setBuddy(self.edtAPUet)
        self.lblAPOffice.setBuddy(self.edtAPOffice)
        self.lblCSG.setBuddy(self.cmbCSG)
        self.lblAPAssistant.setBuddy(self.cmbAPAssistant)

        self.retranslateUi(ActionsPageWidget)
        QtCore.QMetaObject.connectSlotsByName(ActionsPageWidget)
        ActionsPageWidget.setTabOrder(self.tblAPActions, self.edtAPDirectionDate)
        ActionsPageWidget.setTabOrder(self.edtAPDirectionDate, self.edtAPDirectionTime)
        ActionsPageWidget.setTabOrder(self.edtAPDirectionTime, self.chkAPIsUrgent)
        ActionsPageWidget.setTabOrder(self.chkAPIsUrgent, self.cmbAPSetPerson)
        ActionsPageWidget.setTabOrder(self.cmbAPSetPerson, self.edtAPPlannedEndDate)
        ActionsPageWidget.setTabOrder(self.edtAPPlannedEndDate, self.edtAPPlannedEndTime)
        ActionsPageWidget.setTabOrder(self.edtAPPlannedEndTime, self.cmbAPOrg)
        ActionsPageWidget.setTabOrder(self.cmbAPOrg, self.btnAPSelectOrg)
        ActionsPageWidget.setTabOrder(self.btnAPSelectOrg, self.cmbAPMorphologyMKB)
        ActionsPageWidget.setTabOrder(self.cmbAPMorphologyMKB, self.cmbAPMKB)
        ActionsPageWidget.setTabOrder(self.cmbAPMKB, self.cmbAPMKBExSubclass)
        ActionsPageWidget.setTabOrder(self.cmbAPMKBExSubclass, self.cmbAPStatus)
        ActionsPageWidget.setTabOrder(self.cmbAPStatus, self.edtAPBegDate)
        ActionsPageWidget.setTabOrder(self.edtAPBegDate, self.edtAPBegTime)
        ActionsPageWidget.setTabOrder(self.edtAPBegTime, self.edtAPEndDate)
        ActionsPageWidget.setTabOrder(self.edtAPEndDate, self.edtAPEndTime)
        ActionsPageWidget.setTabOrder(self.edtAPEndTime, self.edtAPAmount)
        ActionsPageWidget.setTabOrder(self.edtAPAmount, self.edtAPUet)
        ActionsPageWidget.setTabOrder(self.edtAPUet, self.edtAPOffice)
        ActionsPageWidget.setTabOrder(self.edtAPOffice, self.cmbAPPerson)
        ActionsPageWidget.setTabOrder(self.cmbAPPerson, self.edtAPNote)
        ActionsPageWidget.setTabOrder(self.edtAPNote, self.btnNextAction)
        ActionsPageWidget.setTabOrder(self.btnNextAction, self.btnPlanNextAction)
        ActionsPageWidget.setTabOrder(self.btnPlanNextAction, self.btnAPNomenclatureExpense)
        ActionsPageWidget.setTabOrder(self.btnAPNomenclatureExpense, self.edtAPCoordDate)
        ActionsPageWidget.setTabOrder(self.edtAPCoordDate, self.edtAPCoordTime)
        ActionsPageWidget.setTabOrder(self.edtAPCoordTime, self.cmbCSG)
        ActionsPageWidget.setTabOrder(self.cmbCSG, self.tblAPProps)
        ActionsPageWidget.setTabOrder(self.tblAPProps, self.btnAPHospitalOrderSelect)
        ActionsPageWidget.setTabOrder(self.btnAPHospitalOrderSelect, self.btnAPPrint)
        ActionsPageWidget.setTabOrder(self.btnAPPrint, self.btnAPLoadTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPLoadTemplate, self.btnAPSaveAsTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPSaveAsTemplate, self.btnAPLoadPrevAction)
        ActionsPageWidget.setTabOrder(self.btnAPLoadPrevAction, self.btnAPAttachedFiles)

    def retranslateUi(self, ActionsPageWidget):
        ActionsPageWidget.setWindowTitle(_translate("ActionsPageWidget", "Form", None))
        self.btnPlanNextAction.setText(_translate("ActionsPageWidget", "...", None))
        self.lblAPStatus.setText(_translate("ActionsPageWidget", "Состояние", None))
        self.btnAPNomenclatureExpense.setText(_translate("ActionsPageWidget", "Списание ЛСиИМН", None))
        self.lblAPDirectionDate.setText(_translate("ActionsPageWidget", "Назначено", None))
        self.btnNextAction.setText(_translate("ActionsPageWidget", "Действие", None))
        self.lblAPCoordDate.setText(_translate("ActionsPageWidget", "Согласовано", None))
        self.lblAPPerson.setText(_translate("ActionsPageWidget", "Исполнитель", None))
        self.lblAPOrg.setText(_translate("ActionsPageWidget", "Место выполнения", None))
        self.lblAPNote.setText(_translate("ActionsPageWidget", "Примечания", None))
        self.cmbAPOrg.setItemText(0, _translate("ActionsPageWidget", "Организация", None))
        self.btnAPSelectOrg.setText(_translate("ActionsPageWidget", "...", None))
        self.btnAPQueueManagement.setText(_translate("ActionsPageWidget", "УО", None))
        self.lblAPOrgStructure.setText(_translate("ActionsPageWidget", "Подразделение", None))
        self.lblActionSpecification.setText(_translate("ActionsPageWidget", "Особенность выполнения действия", None))
        self.lblAPMorphologyMKB.setText(_translate("ActionsPageWidget", "Морфология МКБ", None))
        self.lblAPMKB.setText(_translate("ActionsPageWidget", "Диагноз", None))
        self.lblAPMKBExSubclass.setText(_translate("ActionsPageWidget", "РСК", None))
        self.btnAPHospitalOrderSelect.setText(_translate("ActionsPageWidget", "Госпитализация", None))
        self.btnAPPrint.setText(_translate("ActionsPageWidget", "Печать", None))
        self.btnAPLoadTemplate.setText(_translate("ActionsPageWidget", "Загрузить шаблон", None))
        self.btnAPSaveAsTemplate.setText(_translate("ActionsPageWidget", "Сохранить шаблон", None))
        self.btnAPLoadPrevAction.setText(_translate("ActionsPageWidget", "Копировать из предыдущего", None))
        self.btnAPAttachedFiles.setText(_translate("ActionsPageWidget", "Прикреплённые файлы", None))
        self.edtAPCoordDate.setWhatsThis(_translate("ActionsPageWidget", "дата начала осмотра", None))
        self.edtAPCoordTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.edtAPDirectionDate.setWhatsThis(_translate("ActionsPageWidget", "дата начала осмотра", None))
        self.edtAPDirectionTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.chkAPIsUrgent.setText(_translate("ActionsPageWidget", "Срочно", None))
        self.lblAPSetPerson.setText(_translate("ActionsPageWidget", "Назначил", None))
        self.cmbAPSetPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPPlannedEndDate.setText(_translate("ActionsPageWidget", "План", None))
        self.edtAPPlannedEndTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPBegDate.setText(_translate("ActionsPageWidget", "Начато", None))
        self.edtAPBegDate.setWhatsThis(_translate("ActionsPageWidget", "дата окончания осмотра", None))
        self.edtAPBegTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPEndDate.setText(_translate("ActionsPageWidget", "Выполнено", None))
        self.edtAPEndTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPAmount.setText(_translate("ActionsPageWidget", "Количество", None))
        self.lblAPUet.setText(_translate("ActionsPageWidget", "УЕТ", None))
        self.lblAPOffice.setText(_translate("ActionsPageWidget", "Кабинет", None))
        self.lblCSG.setText(_translate("ActionsPageWidget", "КСГ", None))
        self.cmbAPPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPAssistant.setText(_translate("ActionsPageWidget", "Ассистент", None))
        self.cmbAPAssistant.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPQuantity.setText(_translate("ActionsPageWidget", "Кол-во процедур", None))
        self.lblAPDuration.setToolTip(_translate("ActionsPageWidget", "Длительность курса лечения в днях.", None))
        self.lblAPDuration.setText(_translate("ActionsPageWidget", "Длительность", None))
        self.edtAPDuration.setToolTip(_translate("ActionsPageWidget", "Длительность курса лечения в днях.", None))
        self.lblAPPeriodicity.setToolTip(_translate("ActionsPageWidget", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.lblAPPeriodicity.setText(_translate("ActionsPageWidget", "Интервал", None))
        self.edtAPPeriodicity.setToolTip(_translate("ActionsPageWidget", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.lblAPAliquoticity.setToolTip(_translate("ActionsPageWidget", "Сколько раз в сутки.", None))
        self.lblAPAliquoticity.setText(_translate("ActionsPageWidget", "Кратность", None))
        self.edtAPAliquoticity.setToolTip(_translate("ActionsPageWidget", "Сколько раз в сутки.", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from library.crbcombobox import CRBComboBox
from library.ICDMorphologyCodeEdit import CICDMorphologyCodeEditEx
from library.MKBExSubclassComboBox import CMKBExSubclassComboBox
from Orgs.PersonComboBoxEx import CPersonWithOrgListComboBoxEx
from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTemplateChoose import CActionTemplateSelectButton
from library.Attach.AttachButton import CAttachButton
from library.PrintTemplates import CPrintButton
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Events.ActionsTable import CActionsTableView
from library.TimeEdit import CTimeEdit
from Events.ActionStatus import CActionStatusComboBox
from library.ICDCodeEdit import CICDCodeEditEx
from library.DateEdit import CDateEdit
from Events.Utils import CActionCSGComboBox
