# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Events\EventNotesPage.ui'
#
# Created: Sun Nov 18 18:34:34 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventNotesPageWidget(object):
    def setupUi(self, EventNotesPageWidget):
        EventNotesPageWidget.setObjectName(_fromUtf8("EventNotesPageWidget"))
        EventNotesPageWidget.resize(782, 643)
        self.verticalLayout = QtGui.QVBoxLayout(EventNotesPageWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrEventNotesPage = QtGui.QScrollArea(EventNotesPageWidget)
        self.scrEventNotesPage.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrEventNotesPage.setLineWidth(0)
        self.scrEventNotesPage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrEventNotesPage.setWidgetResizable(True)
        self.scrEventNotesPage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrEventNotesPage.setObjectName(_fromUtf8("scrEventNotesPage"))
        self.scrEventNotesPageInterior = QtGui.QWidget()
        self.scrEventNotesPageInterior.setGeometry(QtCore.QRect(0, 0, 782, 643))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrEventNotesPageInterior.sizePolicy().hasHeightForWidth())
        self.scrEventNotesPageInterior.setSizePolicy(sizePolicy)
        self.scrEventNotesPageInterior.setObjectName(_fromUtf8("scrEventNotesPageInterior"))
        self.gridLayout = QtGui.QGridLayout(self.scrEventNotesPageInterior)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEventModifyPersonValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyPersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyPersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyPersonValue.setText(_fromUtf8(""))
        self.lblEventModifyPersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyPersonValue.setObjectName(_fromUtf8("lblEventModifyPersonValue"))
        self.gridLayout.addWidget(self.lblEventModifyPersonValue, 10, 1, 1, 2)
        self.lblEventCreatePerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreatePerson.setObjectName(_fromUtf8("lblEventCreatePerson"))
        self.gridLayout.addWidget(self.lblEventCreatePerson, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.lblRelegateOrg = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblRelegateOrg.setObjectName(_fromUtf8("lblRelegateOrg"))
        self.gridLayout.addWidget(self.lblRelegateOrg, 3, 0, 1, 1)
        self.lblEventCreateDateTime = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreateDateTime.setObjectName(_fromUtf8("lblEventCreateDateTime"))
        self.gridLayout.addWidget(self.lblEventCreateDateTime, 7, 0, 1, 1)
        self.lblEventModifyDateTime = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyDateTime.setObjectName(_fromUtf8("lblEventModifyDateTime"))
        self.gridLayout.addWidget(self.lblEventModifyDateTime, 9, 0, 1, 1)
        self.lblCureMethod = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblCureMethod.setObjectName(_fromUtf8("lblCureMethod"))
        self.gridLayout.addWidget(self.lblCureMethod, 13, 0, 1, 1)
        self.lblEventCuratorIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCuratorIdValue.setObjectName(_fromUtf8("lblEventCuratorIdValue"))
        self.gridLayout.addWidget(self.lblEventCuratorIdValue, 6, 0, 1, 1)
        self.cmbCureMethod = CRBComboBox(self.scrEventNotesPageInterior)
        self.cmbCureMethod.setObjectName(_fromUtf8("cmbCureMethod"))
        self.gridLayout.addWidget(self.cmbCureMethod, 13, 1, 1, 2)
        self.lblExpertPerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblExpertPerson.setObjectName(_fromUtf8("lblExpertPerson"))
        self.gridLayout.addWidget(self.lblExpertPerson, 16, 0, 1, 1)
        self.lblPatientModel = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblPatientModel.setObjectName(_fromUtf8("lblPatientModel"))
        self.gridLayout.addWidget(self.lblPatientModel, 11, 0, 1, 1)
        self.cmbEventAssistant = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbEventAssistant.setEnabled(False)
        self.cmbEventAssistant.setObjectName(_fromUtf8("cmbEventAssistant"))
        self.gridLayout.addWidget(self.cmbEventAssistant, 5, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 206, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 19, 0, 1, 1)
        self.lblEventModifyPerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyPerson.setObjectName(_fromUtf8("lblEventModifyPerson"))
        self.gridLayout.addWidget(self.lblEventModifyPerson, 10, 0, 1, 1)
        self.cmbPatientModel = CPatientModelComboBox(self.scrEventNotesPageInterior)
        self.cmbPatientModel.setObjectName(_fromUtf8("cmbPatientModel"))
        self.gridLayout.addWidget(self.cmbPatientModel, 11, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 15, 2, 1, 1)
        self.lblEventAssistantIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventAssistantIdValue.setObjectName(_fromUtf8("lblEventAssistantIdValue"))
        self.gridLayout.addWidget(self.lblEventAssistantIdValue, 5, 0, 1, 1)
        self.lblEventModifyDateTimeValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventModifyDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyDateTimeValue.setText(_fromUtf8(""))
        self.lblEventModifyDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyDateTimeValue.setObjectName(_fromUtf8("lblEventModifyDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventModifyDateTimeValue, 9, 1, 1, 1)
        self.lblEventNote = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventNote.sizePolicy().hasHeightForWidth())
        self.lblEventNote.setSizePolicy(sizePolicy)
        self.lblEventNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEventNote.setObjectName(_fromUtf8("lblEventNote"))
        self.gridLayout.addWidget(self.lblEventNote, 18, 0, 1, 1)
        self.lblIsClosed = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblIsClosed.setObjectName(_fromUtf8("lblIsClosed"))
        self.gridLayout.addWidget(self.lblIsClosed, 14, 0, 1, 1)
        self.edtEventNote = QtGui.QTextEdit(self.scrEventNotesPageInterior)
        self.edtEventNote.setObjectName(_fromUtf8("edtEventNote"))
        self.gridLayout.addWidget(self.edtEventNote, 18, 1, 2, 2)
        self.lblEventCreateDateTimeValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreateDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreateDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventCreateDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreateDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreateDateTimeValue.setText(_fromUtf8(""))
        self.lblEventCreateDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreateDateTimeValue.setObjectName(_fromUtf8("lblEventCreateDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventCreateDateTimeValue, 7, 1, 1, 1)
        self.cmbEventCurator = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbEventCurator.setEnabled(False)
        self.cmbEventCurator.setObjectName(_fromUtf8("cmbEventCurator"))
        self.gridLayout.addWidget(self.cmbEventCurator, 6, 1, 1, 2)
        self.lblCureType = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblCureType.setObjectName(_fromUtf8("lblCureType"))
        self.gridLayout.addWidget(self.lblCureType, 12, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 9, 2, 1, 1)
        self.lblRelegate = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblRelegate.setObjectName(_fromUtf8("lblRelegate"))
        self.gridLayout.addWidget(self.lblRelegate, 4, 0, 1, 1)
        self.cmbCureType = CRBComboBox(self.scrEventNotesPageInterior)
        self.cmbCureType.setObjectName(_fromUtf8("cmbCureType"))
        self.gridLayout.addWidget(self.cmbCureType, 12, 1, 1, 2)
        self.chkExpose = QtGui.QCheckBox(self.scrEventNotesPageInterior)
        self.chkExpose.setText(_fromUtf8(""))
        self.chkExpose.setObjectName(_fromUtf8("chkExpose"))
        self.gridLayout.addWidget(self.chkExpose, 17, 1, 1, 1)
        self.cmbExpertPerson = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbExpertPerson.setObjectName(_fromUtf8("cmbExpertPerson"))
        self.gridLayout.addWidget(self.cmbExpertPerson, 16, 1, 1, 2)
        self.edtExpertiseDate = CDateEdit(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExpertiseDate.sizePolicy().hasHeightForWidth())
        self.edtExpertiseDate.setSizePolicy(sizePolicy)
        self.edtExpertiseDate.setCalendarPopup(True)
        self.edtExpertiseDate.setObjectName(_fromUtf8("edtExpertiseDate"))
        self.gridLayout.addWidget(self.edtExpertiseDate, 15, 1, 1, 1)
        self.chkIsClosed = QtGui.QCheckBox(self.scrEventNotesPageInterior)
        self.chkIsClosed.setText(_fromUtf8(""))
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout.addWidget(self.chkIsClosed, 14, 1, 1, 1)
        self.lblExpose = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblExpose.setObjectName(_fromUtf8("lblExpose"))
        self.gridLayout.addWidget(self.lblExpose, 17, 0, 1, 1)
        self.lblExpertiseDate = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblExpertiseDate.setObjectName(_fromUtf8("lblExpertiseDate"))
        self.gridLayout.addWidget(self.lblExpertiseDate, 15, 0, 1, 1)
        self.lblEventCreatePersonValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreatePersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreatePersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreatePersonValue.setText(_fromUtf8(""))
        self.lblEventCreatePersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreatePersonValue.setObjectName(_fromUtf8("lblEventCreatePersonValue"))
        self.gridLayout.addWidget(self.lblEventCreatePersonValue, 8, 1, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbRelegateOrg = CPolyclinicComboBox(self.scrEventNotesPageInterior)
        self.cmbRelegateOrg.setEnabled(True)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.horizontalLayout_2.addWidget(self.cmbRelegateOrg)
        self.btnSelectRelegateOrg = QtGui.QToolButton(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectRelegateOrg.sizePolicy().hasHeightForWidth())
        self.btnSelectRelegateOrg.setSizePolicy(sizePolicy)
        self.btnSelectRelegateOrg.setObjectName(_fromUtf8("btnSelectRelegateOrg"))
        self.horizontalLayout_2.addWidget(self.btnSelectRelegateOrg)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblEventIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventIdValue.sizePolicy().hasHeightForWidth())
        self.lblEventIdValue.setSizePolicy(sizePolicy)
        self.lblEventIdValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventIdValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventIdValue.setText(_fromUtf8(""))
        self.lblEventIdValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventIdValue.setObjectName(_fromUtf8("lblEventIdValue"))
        self.horizontalLayout_3.addWidget(self.lblEventIdValue)
        self.lblPrevEvent = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPrevEvent.sizePolicy().hasHeightForWidth())
        self.lblPrevEvent.setSizePolicy(sizePolicy)
        self.lblPrevEvent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPrevEvent.setObjectName(_fromUtf8("lblPrevEvent"))
        self.horizontalLayout_3.addWidget(self.lblPrevEvent)
        self.edtPrevEventInfo = QtGui.QLineEdit(self.scrEventNotesPageInterior)
        self.edtPrevEventInfo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPrevEventInfo.sizePolicy().hasHeightForWidth())
        self.edtPrevEventInfo.setSizePolicy(sizePolicy)
        self.edtPrevEventInfo.setObjectName(_fromUtf8("edtPrevEventInfo"))
        self.horizontalLayout_3.addWidget(self.edtPrevEventInfo)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtEventSrcDate = CDateEdit(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSrcDate.sizePolicy().hasHeightForWidth())
        self.edtEventSrcDate.setSizePolicy(sizePolicy)
        self.edtEventSrcDate.setCalendarPopup(True)
        self.edtEventSrcDate.setObjectName(_fromUtf8("edtEventSrcDate"))
        self.horizontalLayout.addWidget(self.edtEventSrcDate)
        self.lblN = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblN.sizePolicy().hasHeightForWidth())
        self.lblN.setSizePolicy(sizePolicy)
        self.lblN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblN.setObjectName(_fromUtf8("lblN"))
        self.horizontalLayout.addWidget(self.lblN)
        self.edtEventSrcNumber = QtGui.QLineEdit(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSrcNumber.sizePolicy().hasHeightForWidth())
        self.edtEventSrcNumber.setSizePolicy(sizePolicy)
        self.edtEventSrcNumber.setObjectName(_fromUtf8("edtEventSrcNumber"))
        self.horizontalLayout.addWidget(self.edtEventSrcNumber)
        self.lblRelegatePerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRelegatePerson.sizePolicy().hasHeightForWidth())
        self.lblRelegatePerson.setSizePolicy(sizePolicy)
        self.lblRelegatePerson.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRelegatePerson.setObjectName(_fromUtf8("lblRelegatePerson"))
        self.horizontalLayout.addWidget(self.lblRelegatePerson)
        self.cmbRelegatePerson = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRelegatePerson.sizePolicy().hasHeightForWidth())
        self.cmbRelegatePerson.setSizePolicy(sizePolicy)
        self.cmbRelegatePerson.setObjectName(_fromUtf8("cmbRelegatePerson"))
        self.horizontalLayout.addWidget(self.cmbRelegatePerson)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 2)
        self.lblClientRelationConsents = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblClientRelationConsents.setObjectName(_fromUtf8("lblClientRelationConsents"))
        self.gridLayout.addWidget(self.lblClientRelationConsents, 2, 0, 1, 1)
        self.lblEventId = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventId.setObjectName(_fromUtf8("lblEventId"))
        self.gridLayout.addWidget(self.lblEventId, 0, 0, 1, 1)
        self.cmbClientRelationConsents = CClientRelationComboBoxPatron(self.scrEventNotesPageInterior)
        self.cmbClientRelationConsents.setObjectName(_fromUtf8("cmbClientRelationConsents"))
        self.gridLayout.addWidget(self.cmbClientRelationConsents, 2, 1, 1, 2)
        self.lblEventExternalId = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventExternalId.setObjectName(_fromUtf8("lblEventExternalId"))
        self.gridLayout.addWidget(self.lblEventExternalId, 1, 0, 1, 1)
        self.edtEventExternalIdValue = QtGui.QLineEdit(self.scrEventNotesPageInterior)
        self.edtEventExternalIdValue.setEnabled(False)
        self.edtEventExternalIdValue.setObjectName(_fromUtf8("edtEventExternalIdValue"))
        self.gridLayout.addWidget(self.edtEventExternalIdValue, 1, 1, 1, 2)
        self.btnAttachedFiles = CAttachButton(self.scrEventNotesPageInterior)
        self.btnAttachedFiles.setFlat(False)
        self.btnAttachedFiles.setObjectName(_fromUtf8("btnAttachedFiles"))
        self.gridLayout.addWidget(self.btnAttachedFiles, 20, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 20, 2, 1, 1)
        self.scrEventNotesPage.setWidget(self.scrEventNotesPageInterior)
        self.verticalLayout.addWidget(self.scrEventNotesPage)
        self.lblRelegateOrg.setBuddy(self.cmbRelegateOrg)
        self.lblCureMethod.setBuddy(self.cmbCureMethod)
        self.lblEventCuratorIdValue.setBuddy(self.cmbEventCurator)
        self.lblPatientModel.setBuddy(self.cmbPatientModel)
        self.lblEventAssistantIdValue.setBuddy(self.cmbEventAssistant)
        self.lblEventNote.setBuddy(self.edtEventNote)
        self.lblCureType.setBuddy(self.cmbCureType)
        self.lblEventExternalId.setBuddy(self.edtEventExternalIdValue)

        self.retranslateUi(EventNotesPageWidget)
        QtCore.QMetaObject.connectSlotsByName(EventNotesPageWidget)
        EventNotesPageWidget.setTabOrder(self.edtPrevEventInfo, self.edtEventExternalIdValue)
        EventNotesPageWidget.setTabOrder(self.edtEventExternalIdValue, self.cmbClientRelationConsents)
        EventNotesPageWidget.setTabOrder(self.cmbClientRelationConsents, self.cmbRelegateOrg)
        EventNotesPageWidget.setTabOrder(self.cmbRelegateOrg, self.btnSelectRelegateOrg)
        EventNotesPageWidget.setTabOrder(self.btnSelectRelegateOrg, self.edtEventSrcDate)
        EventNotesPageWidget.setTabOrder(self.edtEventSrcDate, self.edtEventSrcNumber)
        EventNotesPageWidget.setTabOrder(self.edtEventSrcNumber, self.cmbRelegatePerson)
        EventNotesPageWidget.setTabOrder(self.cmbRelegatePerson, self.cmbEventAssistant)
        EventNotesPageWidget.setTabOrder(self.cmbEventAssistant, self.cmbEventCurator)
        EventNotesPageWidget.setTabOrder(self.cmbEventCurator, self.cmbPatientModel)
        EventNotesPageWidget.setTabOrder(self.cmbPatientModel, self.cmbCureType)
        EventNotesPageWidget.setTabOrder(self.cmbCureType, self.cmbCureMethod)
        EventNotesPageWidget.setTabOrder(self.cmbCureMethod, self.chkIsClosed)
        EventNotesPageWidget.setTabOrder(self.chkIsClosed, self.edtExpertiseDate)
        EventNotesPageWidget.setTabOrder(self.edtExpertiseDate, self.cmbExpertPerson)
        EventNotesPageWidget.setTabOrder(self.cmbExpertPerson, self.edtEventNote)

    def retranslateUi(self, EventNotesPageWidget):
        EventNotesPageWidget.setWindowTitle(_translate("EventNotesPageWidget", "Form", None))
        self.lblEventCreatePerson.setText(_translate("EventNotesPageWidget", "Автор", None))
        self.lblRelegateOrg.setText(_translate("EventNotesPageWidget", "Направитель", None))
        self.lblEventCreateDateTime.setText(_translate("EventNotesPageWidget", "Дата и время создания", None))
        self.lblEventModifyDateTime.setText(_translate("EventNotesPageWidget", "Дата и время последнего изменения", None))
        self.lblCureMethod.setText(_translate("EventNotesPageWidget", "Метод лечения", None))
        self.lblEventCuratorIdValue.setText(_translate("EventNotesPageWidget", "Куратор", None))
        self.lblExpertPerson.setText(_translate("EventNotesPageWidget", "Эксперт", None))
        self.lblPatientModel.setText(_translate("EventNotesPageWidget", "Модель пациента", None))
        self.lblEventModifyPerson.setText(_translate("EventNotesPageWidget", "Автор последнего изменения", None))
        self.lblEventAssistantIdValue.setText(_translate("EventNotesPageWidget", "Ассистент", None))
        self.lblEventNote.setText(_translate("EventNotesPageWidget", "Примечания", None))
        self.lblIsClosed.setText(_translate("EventNotesPageWidget", "Событие закрыто", None))
        self.lblCureType.setText(_translate("EventNotesPageWidget", "Вид лечения", None))
        self.lblRelegate.setText(_translate("EventNotesPageWidget", "Направление", None))
        self.edtExpertiseDate.setDisplayFormat(_translate("EventNotesPageWidget", "dd.MM.yyyy", None))
        self.lblExpose.setText(_translate("EventNotesPageWidget", "Выставлять в счёт", None))
        self.lblExpertiseDate.setText(_translate("EventNotesPageWidget", "Дата экспертизы случая", None))
        self.btnSelectRelegateOrg.setText(_translate("EventNotesPageWidget", "...", None))
        self.lblPrevEvent.setText(_translate("EventNotesPageWidget", "предыдущее событие", None))
        self.edtEventSrcDate.setDisplayFormat(_translate("EventNotesPageWidget", "dd.MM.yyyy", None))
        self.lblN.setText(_translate("EventNotesPageWidget", "№", None))
        self.lblRelegatePerson.setText(_translate("EventNotesPageWidget", "Направил", None))
        self.lblClientRelationConsents.setText(_translate("EventNotesPageWidget", "Лицо по уходу", None))
        self.lblEventId.setText(_translate("EventNotesPageWidget", "Код карточки", None))
        self.lblEventExternalId.setToolTip(_translate("EventNotesPageWidget", "Внешний идентификатор записи", None))
        self.lblEventExternalId.setText(_translate("EventNotesPageWidget", "Номер документа", None))
        self.btnAttachedFiles.setText(_translate("EventNotesPageWidget", "Прикреплённые файлы", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.Attach.AttachButton import CAttachButton
from Registry.Utils import CClientRelationComboBoxPatron
from Events.widgets.PatientModelComboBox import CPatientModelComboBox
from library.DateEdit import CDateEdit
