# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/natkuch/s11/Events/EventVoucherPage.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventVoucherPageWidget(object):
    def setupUi(self, EventVoucherPageWidget):
        EventVoucherPageWidget.setObjectName(_fromUtf8("EventVoucherPageWidget"))
        EventVoucherPageWidget.resize(801, 402)
        self.gridLayout_3 = QtGui.QGridLayout(EventVoucherPageWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrEventVoucherPage = QtGui.QScrollArea(EventVoucherPageWidget)
        self.scrEventVoucherPage.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrEventVoucherPage.setLineWidth(0)
        self.scrEventVoucherPage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrEventVoucherPage.setWidgetResizable(True)
        self.scrEventVoucherPage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrEventVoucherPage.setObjectName(_fromUtf8("scrEventVoucherPage"))
        self.scrEventVoucherPageInterior = QtGui.QWidget()
        self.scrEventVoucherPageInterior.setGeometry(QtCore.QRect(0, 0, 785, 416))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrEventVoucherPageInterior.sizePolicy().hasHeightForWidth())
        self.scrEventVoucherPageInterior.setSizePolicy(sizePolicy)
        self.scrEventVoucherPageInterior.setObjectName(_fromUtf8("scrEventVoucherPageInterior"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrEventVoucherPageInterior)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grpVoucher = QtGui.QGroupBox(self.scrEventVoucherPageInterior)
        self.grpVoucher.setObjectName(_fromUtf8("grpVoucher"))
        self.gridLayout = QtGui.QGridLayout(self.grpVoucher)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblVoucherOrgs = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherOrgs.setObjectName(_fromUtf8("lblVoucherOrgs"))
        self.gridLayout.addWidget(self.lblVoucherOrgs, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cmbVoucherOrgs = CPolyclinicComboBox(self.grpVoucher)
        self.cmbVoucherOrgs.setObjectName(_fromUtf8("cmbVoucherOrgs"))
        self.horizontalLayout_3.addWidget(self.cmbVoucherOrgs)
        self.btnSelectVoucherOrg = QtGui.QToolButton(self.grpVoucher)
        self.btnSelectVoucherOrg.setObjectName(_fromUtf8("btnSelectVoucherOrg"))
        self.horizontalLayout_3.addWidget(self.btnSelectVoucherOrg)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 2)
        self.lblVoucherFinance = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherFinance.setObjectName(_fromUtf8("lblVoucherFinance"))
        self.gridLayout.addWidget(self.lblVoucherFinance, 1, 0, 1, 1)
        self.cmbVoucherFinance = CRBComboBox(self.grpVoucher)
        self.cmbVoucherFinance.setObjectName(_fromUtf8("cmbVoucherFinance"))
        self.gridLayout.addWidget(self.cmbVoucherFinance, 1, 1, 1, 2)
        self.lblVoucherSerial = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherSerial.setObjectName(_fromUtf8("lblVoucherSerial"))
        self.gridLayout.addWidget(self.lblVoucherSerial, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtVoucherSerial = QtGui.QLineEdit(self.grpVoucher)
        self.edtVoucherSerial.setObjectName(_fromUtf8("edtVoucherSerial"))
        self.horizontalLayout_4.addWidget(self.edtVoucherSerial)
        self.lblVoucherNumber = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherNumber.setObjectName(_fromUtf8("lblVoucherNumber"))
        self.horizontalLayout_4.addWidget(self.lblVoucherNumber)
        self.edtVoucherNumber = QtGui.QLineEdit(self.grpVoucher)
        self.edtVoucherNumber.setObjectName(_fromUtf8("edtVoucherNumber"))
        self.horizontalLayout_4.addWidget(self.edtVoucherNumber)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 2)
        self.lblVoucherBegDate = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherBegDate.setObjectName(_fromUtf8("lblVoucherBegDate"))
        self.gridLayout.addWidget(self.lblVoucherBegDate, 3, 0, 1, 1)
        self.edtVoucherBegDate = CDateEdit(self.grpVoucher)
        self.edtVoucherBegDate.setCalendarPopup(True)
        self.edtVoucherBegDate.setObjectName(_fromUtf8("edtVoucherBegDate"))
        self.gridLayout.addWidget(self.edtVoucherBegDate, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.lblVoucherEndDate = QtGui.QLabel(self.grpVoucher)
        self.lblVoucherEndDate.setObjectName(_fromUtf8("lblVoucherEndDate"))
        self.gridLayout.addWidget(self.lblVoucherEndDate, 4, 0, 1, 1)
        self.edtVoucherEndDate = CDateEdit(self.grpVoucher)
        self.edtVoucherEndDate.setCalendarPopup(True)
        self.edtVoucherEndDate.setObjectName(_fromUtf8("edtVoucherEndDate"))
        self.gridLayout.addWidget(self.edtVoucherEndDate, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.grpVoucher, 0, 0, 1, 1)
        self.grpDirection = QtGui.QGroupBox(self.scrEventVoucherPageInterior)
        self.grpDirection.setObjectName(_fromUtf8("grpDirection"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpDirection)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblDirectionCity = QtGui.QLabel(self.grpDirection)
        self.lblDirectionCity.setObjectName(_fromUtf8("lblDirectionCity"))
        self.gridLayout_2.addWidget(self.lblDirectionCity, 0, 0, 1, 1)
        self.cmbDirectionCity = CKLADRComboBox(self.grpDirection)
        self.cmbDirectionCity.setObjectName(_fromUtf8("cmbDirectionCity"))
        self.gridLayout_2.addWidget(self.cmbDirectionCity, 0, 1, 1, 1)
        self.lblDirectionRegion = QtGui.QLabel(self.grpDirection)
        self.lblDirectionRegion.setObjectName(_fromUtf8("lblDirectionRegion"))
        self.gridLayout_2.addWidget(self.lblDirectionRegion, 1, 0, 1, 1)
        self.cmbDirectionRegion = CKladrOkatoComboBox(self.grpDirection)
        self.cmbDirectionRegion.setObjectName(_fromUtf8("cmbDirectionRegion"))
        self.gridLayout_2.addWidget(self.cmbDirectionRegion, 1, 1, 1, 1)
        self.lblDirectionOrgs = QtGui.QLabel(self.grpDirection)
        self.lblDirectionOrgs.setObjectName(_fromUtf8("lblDirectionOrgs"))
        self.gridLayout_2.addWidget(self.lblDirectionOrgs, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbDirectionOrgs = CPolyclinicComboBox(self.grpDirection)
        self.cmbDirectionOrgs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDirectionOrgs.sizePolicy().hasHeightForWidth())
        self.cmbDirectionOrgs.setSizePolicy(sizePolicy)
        self.cmbDirectionOrgs.setObjectName(_fromUtf8("cmbDirectionOrgs"))
        self.horizontalLayout_2.addWidget(self.cmbDirectionOrgs)
        self.btnSelectDirectionOrg = QtGui.QToolButton(self.grpDirection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectDirectionOrg.sizePolicy().hasHeightForWidth())
        self.btnSelectDirectionOrg.setSizePolicy(sizePolicy)
        self.btnSelectDirectionOrg.setObjectName(_fromUtf8("btnSelectDirectionOrg"))
        self.horizontalLayout_2.addWidget(self.btnSelectDirectionOrg)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.lblDirectionPerson = QtGui.QLabel(self.grpDirection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDirectionPerson.sizePolicy().hasHeightForWidth())
        self.lblDirectionPerson.setSizePolicy(sizePolicy)
        self.lblDirectionPerson.setObjectName(_fromUtf8("lblDirectionPerson"))
        self.gridLayout_2.addWidget(self.lblDirectionPerson, 3, 0, 1, 1)
        self.cmbDirectionPerson = CPersonComboBoxEx(self.grpDirection)
        self.cmbDirectionPerson.setObjectName(_fromUtf8("cmbDirectionPerson"))
        self.gridLayout_2.addWidget(self.cmbDirectionPerson, 3, 1, 1, 1)
        self.lblDirectionNumber = QtGui.QLabel(self.grpDirection)
        self.lblDirectionNumber.setObjectName(_fromUtf8("lblDirectionNumber"))
        self.gridLayout_2.addWidget(self.lblDirectionNumber, 4, 0, 1, 1)
        self.edtDirectionNumber = QtGui.QLineEdit(self.grpDirection)
        self.edtDirectionNumber.setObjectName(_fromUtf8("edtDirectionNumber"))
        self.gridLayout_2.addWidget(self.edtDirectionNumber, 4, 1, 1, 1)
        self.lblDirectionDate = QtGui.QLabel(self.grpDirection)
        self.lblDirectionDate.setObjectName(_fromUtf8("lblDirectionDate"))
        self.gridLayout_2.addWidget(self.lblDirectionDate, 5, 0, 1, 1)
        self.edtDirectionDate = CDateEdit(self.grpDirection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDirectionDate.sizePolicy().hasHeightForWidth())
        self.edtDirectionDate.setSizePolicy(sizePolicy)
        self.edtDirectionDate.setCalendarPopup(True)
        self.edtDirectionDate.setObjectName(_fromUtf8("edtDirectionDate"))
        self.gridLayout_2.addWidget(self.edtDirectionDate, 5, 1, 1, 1)
        self.lblDirectionMKB = QtGui.QLabel(self.grpDirection)
        self.lblDirectionMKB.setObjectName(_fromUtf8("lblDirectionMKB"))
        self.gridLayout_2.addWidget(self.lblDirectionMKB, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtDirectionMKB = CICDCodeEditEx(self.grpDirection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDirectionMKB.sizePolicy().hasHeightForWidth())
        self.edtDirectionMKB.setSizePolicy(sizePolicy)
        self.edtDirectionMKB.setObjectName(_fromUtf8("edtDirectionMKB"))
        self.horizontalLayout.addWidget(self.edtDirectionMKB)
        self.lblDirectionMKBText = QtGui.QLabel(self.grpDirection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDirectionMKBText.sizePolicy().hasHeightForWidth())
        self.lblDirectionMKBText.setSizePolicy(sizePolicy)
        self.lblDirectionMKBText.setText(_fromUtf8(""))
        self.lblDirectionMKBText.setObjectName(_fromUtf8("lblDirectionMKBText"))
        self.horizontalLayout.addWidget(self.lblDirectionMKBText)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.gridLayout_4.addWidget(self.grpDirection, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.scrEventVoucherPage.setWidget(self.scrEventVoucherPageInterior)
        self.gridLayout_3.addWidget(self.scrEventVoucherPage, 0, 0, 1, 1)

        self.retranslateUi(EventVoucherPageWidget)
        QtCore.QMetaObject.connectSlotsByName(EventVoucherPageWidget)
        EventVoucherPageWidget.setTabOrder(self.cmbVoucherOrgs, self.btnSelectVoucherOrg)
        EventVoucherPageWidget.setTabOrder(self.btnSelectVoucherOrg, self.cmbVoucherFinance)
        EventVoucherPageWidget.setTabOrder(self.cmbVoucherFinance, self.edtVoucherSerial)
        EventVoucherPageWidget.setTabOrder(self.edtVoucherSerial, self.edtVoucherNumber)
        EventVoucherPageWidget.setTabOrder(self.edtVoucherNumber, self.edtVoucherBegDate)
        EventVoucherPageWidget.setTabOrder(self.edtVoucherBegDate, self.edtVoucherEndDate)
        EventVoucherPageWidget.setTabOrder(self.edtVoucherEndDate, self.cmbDirectionCity)
        EventVoucherPageWidget.setTabOrder(self.cmbDirectionCity, self.cmbDirectionRegion)
        EventVoucherPageWidget.setTabOrder(self.cmbDirectionRegion, self.cmbDirectionOrgs)
        EventVoucherPageWidget.setTabOrder(self.cmbDirectionOrgs, self.btnSelectDirectionOrg)
        EventVoucherPageWidget.setTabOrder(self.btnSelectDirectionOrg, self.cmbDirectionPerson)
        EventVoucherPageWidget.setTabOrder(self.cmbDirectionPerson, self.edtDirectionNumber)
        EventVoucherPageWidget.setTabOrder(self.edtDirectionNumber, self.edtDirectionDate)
        EventVoucherPageWidget.setTabOrder(self.edtDirectionDate, self.edtDirectionMKB)
        EventVoucherPageWidget.setTabOrder(self.edtDirectionMKB, self.scrEventVoucherPage)

    def retranslateUi(self, EventVoucherPageWidget):
        EventVoucherPageWidget.setWindowTitle(_translate("EventVoucherPageWidget", "Form", None))
        self.grpVoucher.setTitle(_translate("EventVoucherPageWidget", "Данные путевки", None))
        self.lblVoucherOrgs.setText(_translate("EventVoucherPageWidget", "Организация", None))
        self.btnSelectVoucherOrg.setText(_translate("EventVoucherPageWidget", "...", None))
        self.lblVoucherFinance.setText(_translate("EventVoucherPageWidget", "Источник финансирования", None))
        self.lblVoucherSerial.setText(_translate("EventVoucherPageWidget", "Серия", None))
        self.lblVoucherNumber.setText(_translate("EventVoucherPageWidget", "Номер", None))
        self.edtVoucherNumber.setInputMask(_translate("EventVoucherPageWidget", "999999999999999; ", None))
        self.lblVoucherBegDate.setText(_translate("EventVoucherPageWidget", "Дата начала", None))
        self.edtVoucherBegDate.setDisplayFormat(_translate("EventVoucherPageWidget", "dd.MM.yyyy", None))
        self.lblVoucherEndDate.setText(_translate("EventVoucherPageWidget", "Дата окончания", None))
        self.edtVoucherEndDate.setDisplayFormat(_translate("EventVoucherPageWidget", "dd.MM.yyyy", None))
        self.grpDirection.setTitle(_translate("EventVoucherPageWidget", "Данные направителя", None))
        self.lblDirectionCity.setText(_translate("EventVoucherPageWidget", "Субъект", None))
        self.lblDirectionRegion.setText(_translate("EventVoucherPageWidget", "Район", None))
        self.lblDirectionOrgs.setText(_translate("EventVoucherPageWidget", "Направившая МО", None))
        self.btnSelectDirectionOrg.setText(_translate("EventVoucherPageWidget", "...", None))
        self.lblDirectionPerson.setText(_translate("EventVoucherPageWidget", "Направил", None))
        self.lblDirectionNumber.setText(_translate("EventVoucherPageWidget", "Номер направления", None))
        self.lblDirectionDate.setText(_translate("EventVoucherPageWidget", "Дата направления", None))
        self.edtDirectionDate.setDisplayFormat(_translate("EventVoucherPageWidget", "dd.MM.yyyy", None))
        self.lblDirectionMKB.setText(_translate("EventVoucherPageWidget", "Диагноз направителя", None))

from KLADR.kladrComboxes import CKLADRComboBox, CKladrOkatoComboBox
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EventVoucherPageWidget = QtGui.QWidget()
    ui = Ui_EventVoucherPageWidget()
    ui.setupUi(EventVoucherPageWidget)
    EventVoucherPageWidget.show()
    sys.exit(app.exec_())

