# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/natkuch/s11/Events/EventVoucherNotesPage.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventVoucherNotesPageWidget(object):
    def setupUi(self, EventVoucherNotesPageWidget):
        EventVoucherNotesPageWidget.setObjectName(_fromUtf8("EventVoucherNotesPageWidget"))
        EventVoucherNotesPageWidget.resize(675, 580)
        self.verticalLayout = QtGui.QVBoxLayout(EventVoucherNotesPageWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrEventNotesPage = QtGui.QScrollArea(EventVoucherNotesPageWidget)
        self.scrEventNotesPage.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrEventNotesPage.setLineWidth(0)
        self.scrEventNotesPage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrEventNotesPage.setWidgetResizable(True)
        self.scrEventNotesPage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrEventNotesPage.setObjectName(_fromUtf8("scrEventNotesPage"))
        self.scrEventNotesPageInterior = QtGui.QWidget()
        self.scrEventNotesPageInterior.setGeometry(QtCore.QRect(0, 0, 675, 580))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrEventNotesPageInterior.sizePolicy().hasHeightForWidth())
        self.scrEventNotesPageInterior.setSizePolicy(sizePolicy)
        self.scrEventNotesPageInterior.setObjectName(_fromUtf8("scrEventNotesPageInterior"))
        self.gridLayout = QtGui.QGridLayout(self.scrEventNotesPageInterior)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEventAssistantIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventAssistantIdValue.setObjectName(_fromUtf8("lblEventAssistantIdValue"))
        self.gridLayout.addWidget(self.lblEventAssistantIdValue, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 206, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 0, 1, 1)
        self.lblEventModifyPersonValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyPersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyPersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyPersonValue.setText(_fromUtf8(""))
        self.lblEventModifyPersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyPersonValue.setObjectName(_fromUtf8("lblEventModifyPersonValue"))
        self.gridLayout.addWidget(self.lblEventModifyPersonValue, 6, 1, 1, 5)
        self.lblEventCreateDateTimeValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreateDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreateDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventCreateDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreateDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreateDateTimeValue.setText(_fromUtf8(""))
        self.lblEventCreateDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreateDateTimeValue.setObjectName(_fromUtf8("lblEventCreateDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventCreateDateTimeValue, 3, 1, 1, 1)
        self.lblEventId = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventId.setObjectName(_fromUtf8("lblEventId"))
        self.gridLayout.addWidget(self.lblEventId, 0, 0, 1, 1)
        self.cmbEventAssistant = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbEventAssistant.setEnabled(False)
        self.cmbEventAssistant.setObjectName(_fromUtf8("cmbEventAssistant"))
        self.gridLayout.addWidget(self.cmbEventAssistant, 1, 1, 1, 5)
        self.edtPrevEventInfo = QtGui.QLineEdit(self.scrEventNotesPageInterior)
        self.edtPrevEventInfo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPrevEventInfo.sizePolicy().hasHeightForWidth())
        self.edtPrevEventInfo.setSizePolicy(sizePolicy)
        self.edtPrevEventInfo.setObjectName(_fromUtf8("edtPrevEventInfo"))
        self.gridLayout.addWidget(self.edtPrevEventInfo, 0, 4, 1, 2)
        self.cmbPatientModel = CPatientModelComboBox(self.scrEventNotesPageInterior)
        self.cmbPatientModel.setObjectName(_fromUtf8("cmbPatientModel"))
        self.gridLayout.addWidget(self.cmbPatientModel, 7, 1, 1, 5)
        self.chkIsClosed = QtGui.QCheckBox(self.scrEventNotesPageInterior)
        self.chkIsClosed.setText(_fromUtf8(""))
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout.addWidget(self.chkIsClosed, 10, 1, 1, 3)
        self.lblCureType = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblCureType.setObjectName(_fromUtf8("lblCureType"))
        self.gridLayout.addWidget(self.lblCureType, 8, 0, 1, 1)
        self.lblEventCuratorIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCuratorIdValue.setObjectName(_fromUtf8("lblEventCuratorIdValue"))
        self.gridLayout.addWidget(self.lblEventCuratorIdValue, 2, 0, 1, 1)
        self.lblEventModifyDateTimeValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventModifyDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyDateTimeValue.setText(_fromUtf8(""))
        self.lblEventModifyDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyDateTimeValue.setObjectName(_fromUtf8("lblEventModifyDateTimeValue"))
        self.gridLayout.addWidget(self.lblEventModifyDateTimeValue, 5, 1, 1, 1)
        self.lblEventModifyPerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyPerson.setObjectName(_fromUtf8("lblEventModifyPerson"))
        self.gridLayout.addWidget(self.lblEventModifyPerson, 6, 0, 1, 1)
        self.lblPatientModel = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblPatientModel.setObjectName(_fromUtf8("lblPatientModel"))
        self.gridLayout.addWidget(self.lblPatientModel, 7, 0, 1, 1)
        self.cmbEventCurator = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbEventCurator.setEnabled(False)
        self.cmbEventCurator.setObjectName(_fromUtf8("cmbEventCurator"))
        self.gridLayout.addWidget(self.cmbEventCurator, 2, 1, 1, 5)
        self.lblEventCreatePersonValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreatePersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreatePersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreatePersonValue.setText(_fromUtf8(""))
        self.lblEventCreatePersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreatePersonValue.setObjectName(_fromUtf8("lblEventCreatePersonValue"))
        self.gridLayout.addWidget(self.lblEventCreatePersonValue, 4, 1, 1, 5)
        self.lblEventModifyDateTime = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventModifyDateTime.setObjectName(_fromUtf8("lblEventModifyDateTime"))
        self.gridLayout.addWidget(self.lblEventModifyDateTime, 5, 0, 1, 1)
        self.lblEventNote = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventNote.sizePolicy().hasHeightForWidth())
        self.lblEventNote.setSizePolicy(sizePolicy)
        self.lblEventNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEventNote.setObjectName(_fromUtf8("lblEventNote"))
        self.gridLayout.addWidget(self.lblEventNote, 13, 0, 1, 1)
        self.lblEventCreateDateTime = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreateDateTime.setObjectName(_fromUtf8("lblEventCreateDateTime"))
        self.gridLayout.addWidget(self.lblEventCreateDateTime, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 4)
        self.lblEventCreatePerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblEventCreatePerson.setObjectName(_fromUtf8("lblEventCreatePerson"))
        self.gridLayout.addWidget(self.lblEventCreatePerson, 4, 0, 1, 1)
        self.cmbExpertPerson = CPersonComboBoxEx(self.scrEventNotesPageInterior)
        self.cmbExpertPerson.setObjectName(_fromUtf8("cmbExpertPerson"))
        self.gridLayout.addWidget(self.cmbExpertPerson, 12, 1, 1, 5)
        self.cmbCureType = CRBComboBox(self.scrEventNotesPageInterior)
        self.cmbCureType.setObjectName(_fromUtf8("cmbCureType"))
        self.gridLayout.addWidget(self.cmbCureType, 8, 1, 1, 5)
        self.lblCureMethod = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblCureMethod.setObjectName(_fromUtf8("lblCureMethod"))
        self.gridLayout.addWidget(self.lblCureMethod, 9, 0, 1, 1)
        self.cmbCureMethod = CRBComboBox(self.scrEventNotesPageInterior)
        self.cmbCureMethod.setObjectName(_fromUtf8("cmbCureMethod"))
        self.gridLayout.addWidget(self.cmbCureMethod, 9, 1, 1, 5)
        self.lblIsClosed = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblIsClosed.setObjectName(_fromUtf8("lblIsClosed"))
        self.gridLayout.addWidget(self.lblIsClosed, 10, 0, 1, 1)
        self.lblExpertiseDate = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblExpertiseDate.setObjectName(_fromUtf8("lblExpertiseDate"))
        self.gridLayout.addWidget(self.lblExpertiseDate, 11, 0, 1, 1)
        self.edtExpertiseDate = CDateEdit(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExpertiseDate.sizePolicy().hasHeightForWidth())
        self.edtExpertiseDate.setSizePolicy(sizePolicy)
        self.edtExpertiseDate.setCalendarPopup(True)
        self.edtExpertiseDate.setObjectName(_fromUtf8("edtExpertiseDate"))
        self.gridLayout.addWidget(self.edtExpertiseDate, 11, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 11, 2, 1, 4)
        self.lblExpertPerson = QtGui.QLabel(self.scrEventNotesPageInterior)
        self.lblExpertPerson.setObjectName(_fromUtf8("lblExpertPerson"))
        self.gridLayout.addWidget(self.lblExpertPerson, 12, 0, 1, 1)
        self.edtEventNote = QtGui.QTextEdit(self.scrEventNotesPageInterior)
        self.edtEventNote.setObjectName(_fromUtf8("edtEventNote"))
        self.gridLayout.addWidget(self.edtEventNote, 13, 1, 2, 5)
        self.btnAttachedFiles = CAttachButton(self.scrEventNotesPageInterior)
        self.btnAttachedFiles.setFlat(False)
        self.btnAttachedFiles.setObjectName(_fromUtf8("btnAttachedFiles"))
        self.gridLayout.addWidget(self.btnAttachedFiles, 15, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 4)
        self.lblEventIdValue = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventIdValue.sizePolicy().hasHeightForWidth())
        self.lblEventIdValue.setSizePolicy(sizePolicy)
        self.lblEventIdValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventIdValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventIdValue.setText(_fromUtf8(""))
        self.lblEventIdValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventIdValue.setObjectName(_fromUtf8("lblEventIdValue"))
        self.gridLayout.addWidget(self.lblEventIdValue, 0, 1, 1, 1)
        self.lblPrevEvent = QtGui.QLabel(self.scrEventNotesPageInterior)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPrevEvent.sizePolicy().hasHeightForWidth())
        self.lblPrevEvent.setSizePolicy(sizePolicy)
        self.lblPrevEvent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPrevEvent.setObjectName(_fromUtf8("lblPrevEvent"))
        self.gridLayout.addWidget(self.lblPrevEvent, 0, 2, 1, 2)
        self.scrEventNotesPage.setWidget(self.scrEventNotesPageInterior)
        self.verticalLayout.addWidget(self.scrEventNotesPage)
        self.lblEventAssistantIdValue.setBuddy(self.cmbEventAssistant)
        self.lblCureType.setBuddy(self.cmbCureType)
        self.lblEventCuratorIdValue.setBuddy(self.cmbEventCurator)
        self.lblPatientModel.setBuddy(self.cmbPatientModel)
        self.lblEventNote.setBuddy(self.edtEventNote)
        self.lblCureMethod.setBuddy(self.cmbCureMethod)

        self.retranslateUi(EventVoucherNotesPageWidget)
        QtCore.QMetaObject.connectSlotsByName(EventVoucherNotesPageWidget)
        EventVoucherNotesPageWidget.setTabOrder(self.edtPrevEventInfo, self.cmbEventAssistant)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbEventAssistant, self.cmbEventCurator)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbEventCurator, self.cmbPatientModel)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbPatientModel, self.cmbCureType)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbCureType, self.cmbCureMethod)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbCureMethod, self.chkIsClosed)
        EventVoucherNotesPageWidget.setTabOrder(self.chkIsClosed, self.edtExpertiseDate)
        EventVoucherNotesPageWidget.setTabOrder(self.edtExpertiseDate, self.cmbExpertPerson)
        EventVoucherNotesPageWidget.setTabOrder(self.cmbExpertPerson, self.edtEventNote)
        EventVoucherNotesPageWidget.setTabOrder(self.edtEventNote, self.btnAttachedFiles)
        EventVoucherNotesPageWidget.setTabOrder(self.btnAttachedFiles, self.scrEventNotesPage)

    def retranslateUi(self, EventVoucherNotesPageWidget):
        EventVoucherNotesPageWidget.setWindowTitle(_translate("EventVoucherNotesPageWidget", "Form", None))
        self.lblEventAssistantIdValue.setText(_translate("EventVoucherNotesPageWidget", "Ассистент", None))
        self.lblEventId.setText(_translate("EventVoucherNotesPageWidget", "Код карточки", None))
        self.lblCureType.setText(_translate("EventVoucherNotesPageWidget", "Вид лечения", None))
        self.lblEventCuratorIdValue.setText(_translate("EventVoucherNotesPageWidget", "Куратор", None))
        self.lblEventModifyPerson.setText(_translate("EventVoucherNotesPageWidget", "Автор последнего изменения", None))
        self.lblPatientModel.setText(_translate("EventVoucherNotesPageWidget", "Модель пациента", None))
        self.lblEventModifyDateTime.setText(_translate("EventVoucherNotesPageWidget", "Дата и время последнего изменения", None))
        self.lblEventNote.setText(_translate("EventVoucherNotesPageWidget", "Примечания", None))
        self.lblEventCreateDateTime.setText(_translate("EventVoucherNotesPageWidget", "Дата и время создания", None))
        self.lblEventCreatePerson.setText(_translate("EventVoucherNotesPageWidget", "Автор", None))
        self.lblCureMethod.setText(_translate("EventVoucherNotesPageWidget", "Метод лечения", None))
        self.lblIsClosed.setText(_translate("EventVoucherNotesPageWidget", "Событие закрыто", None))
        self.lblExpertiseDate.setText(_translate("EventVoucherNotesPageWidget", "Дата экспертизы случая", None))
        self.edtExpertiseDate.setDisplayFormat(_translate("EventVoucherNotesPageWidget", "dd.MM.yyyy", None))
        self.lblExpertPerson.setText(_translate("EventVoucherNotesPageWidget", "Эксперт", None))
        self.btnAttachedFiles.setText(_translate("EventVoucherNotesPageWidget", "Прикреплённые файлы", None))
        self.lblPrevEvent.setText(_translate("EventVoucherNotesPageWidget", "предыдущее событие", None))

from Events.widgets.PatientModelComboBox import CPatientModelComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.Attach.AttachButton import CAttachButton
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EventVoucherNotesPageWidget = QtGui.QWidget()
    ui = Ui_EventVoucherNotesPageWidget()
    ui.setupUi(EventVoucherNotesPageWidget)
    EventVoucherNotesPageWidget.show()
    sys.exit(app.exec_())

