# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dmitrii/s11/Events/LLO78RegistryWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LLO78RegistryDialog(object):
    def setupUi(self, LLO78RegistryDialog):
        LLO78RegistryDialog.setObjectName(_fromUtf8("LLO78RegistryDialog"))
        LLO78RegistryDialog.resize(856, 783)
        LLO78RegistryDialog.setSizeGripEnabled(False)
        self.gridLayout_5 = QtGui.QGridLayout(LLO78RegistryDialog)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblRequestedLP = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRequestedLP.sizePolicy().hasHeightForWidth())
        self.lblRequestedLP.setSizePolicy(sizePolicy)
        self.lblRequestedLP.setObjectName(_fromUtf8("lblRequestedLP"))
        self.gridLayout.addWidget(self.lblRequestedLP, 0, 0, 1, 1)
        self.edtRequestedLP = QtGui.QLineEdit(self.groupBox_3)
        self.edtRequestedLP.setObjectName(_fromUtf8("edtRequestedLP"))
        self.gridLayout.addWidget(self.edtRequestedLP, 0, 1, 1, 1)
        self.btnFindLPs = QtGui.QPushButton(self.groupBox_3)
        self.btnFindLPs.setObjectName(_fromUtf8("btnFindLPs"))
        self.gridLayout.addWidget(self.btnFindLPs, 0, 2, 1, 1)
        self.tblRequestedLPs = QtGui.QTableWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblRequestedLPs.sizePolicy().hasHeightForWidth())
        self.tblRequestedLPs.setSizePolicy(sizePolicy)
        self.tblRequestedLPs.setMinimumSize(QtCore.QSize(0, 0))
        self.tblRequestedLPs.setRowCount(0)
        self.tblRequestedLPs.setColumnCount(0)
        self.tblRequestedLPs.setObjectName(_fromUtf8("tblRequestedLPs"))
        self.tblRequestedLPs.horizontalHeader().setCascadingSectionResizes(True)
        self.tblRequestedLPs.horizontalHeader().setStretchLastSection(True)
        self.tblRequestedLPs.verticalHeader().setCascadingSectionResizes(False)
        self.tblRequestedLPs.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblRequestedLPs, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 4)
        self.btnSignAndRegistrateRecipe = QtGui.QPushButton(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSignAndRegistrateRecipe.sizePolicy().hasHeightForWidth())
        self.btnSignAndRegistrateRecipe.setSizePolicy(sizePolicy)
        self.btnSignAndRegistrateRecipe.setObjectName(_fromUtf8("btnSignAndRegistrateRecipe"))
        self.gridLayout_5.addWidget(self.btnSignAndRegistrateRecipe, 3, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(459, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblDischargeAttribute = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDischargeAttribute.sizePolicy().hasHeightForWidth())
        self.lblDischargeAttribute.setSizePolicy(sizePolicy)
        self.lblDischargeAttribute.setObjectName(_fromUtf8("lblDischargeAttribute"))
        self.gridLayout_6.addWidget(self.lblDischargeAttribute, 0, 0, 1, 1)
        self.cmbDischargeAttribute = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDischargeAttribute.sizePolicy().hasHeightForWidth())
        self.cmbDischargeAttribute.setSizePolicy(sizePolicy)
        self.cmbDischargeAttribute.setObjectName(_fromUtf8("cmbDischargeAttribute"))
        self.cmbDischargeAttribute.addItem(_fromUtf8(""))
        self.cmbDischargeAttribute.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbDischargeAttribute, 1, 0, 1, 1)
        self.lblDischargeType = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDischargeType.sizePolicy().hasHeightForWidth())
        self.lblDischargeType.setSizePolicy(sizePolicy)
        self.lblDischargeType.setObjectName(_fromUtf8("lblDischargeType"))
        self.gridLayout_6.addWidget(self.lblDischargeType, 2, 0, 1, 1)
        self.cmbDischargeType = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDischargeType.sizePolicy().hasHeightForWidth())
        self.cmbDischargeType.setSizePolicy(sizePolicy)
        self.cmbDischargeType.setObjectName(_fromUtf8("cmbDischargeType"))
        self.cmbDischargeType.addItem(_fromUtf8(""))
        self.cmbDischargeType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbDischargeType, 3, 0, 1, 1)
        self.lblLPQuantity = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLPQuantity.sizePolicy().hasHeightForWidth())
        self.lblLPQuantity.setSizePolicy(sizePolicy)
        self.lblLPQuantity.setObjectName(_fromUtf8("lblLPQuantity"))
        self.gridLayout_6.addWidget(self.lblLPQuantity, 4, 0, 1, 1)
        self.lblUseMethod = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUseMethod.sizePolicy().hasHeightForWidth())
        self.lblUseMethod.setSizePolicy(sizePolicy)
        self.lblUseMethod.setObjectName(_fromUtf8("lblUseMethod"))
        self.gridLayout_6.addWidget(self.lblUseMethod, 6, 0, 1, 1)
        self.edtUseMethod = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUseMethod.sizePolicy().hasHeightForWidth())
        self.edtUseMethod.setSizePolicy(sizePolicy)
        self.edtUseMethod.setObjectName(_fromUtf8("edtUseMethod"))
        self.gridLayout_6.addWidget(self.edtUseMethod, 7, 0, 1, 1)
        self.lblRecipeExpirationDate = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecipeExpirationDate.sizePolicy().hasHeightForWidth())
        self.lblRecipeExpirationDate.setSizePolicy(sizePolicy)
        self.lblRecipeExpirationDate.setObjectName(_fromUtf8("lblRecipeExpirationDate"))
        self.gridLayout_6.addWidget(self.lblRecipeExpirationDate, 8, 0, 1, 1)
        self.cmbRecipeExpirationDate = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRecipeExpirationDate.sizePolicy().hasHeightForWidth())
        self.cmbRecipeExpirationDate.setSizePolicy(sizePolicy)
        self.cmbRecipeExpirationDate.setObjectName(_fromUtf8("cmbRecipeExpirationDate"))
        self.cmbRecipeExpirationDate.addItem(_fromUtf8(""))
        self.cmbRecipeExpirationDate.addItem(_fromUtf8(""))
        self.cmbRecipeExpirationDate.addItem(_fromUtf8(""))
        self.cmbRecipeExpirationDate.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbRecipeExpirationDate, 9, 0, 1, 1)
        self.chkTypeOfProtocol = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkTypeOfProtocol.sizePolicy().hasHeightForWidth())
        self.chkTypeOfProtocol.setSizePolicy(sizePolicy)
        self.chkTypeOfProtocol.setObjectName(_fromUtf8("chkTypeOfProtocol"))
        self.gridLayout_6.addWidget(self.chkTypeOfProtocol, 10, 0, 1, 1)
        self.dsbLPQuantity = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsbLPQuantity.setDecimals(3)
        self.dsbLPQuantity.setMaximum(999999999.99)
        self.dsbLPQuantity.setObjectName(_fromUtf8("dsbLPQuantity"))
        self.gridLayout_6.addWidget(self.dsbLPQuantity, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 2, 1, 2)
        self.btnCancelRecipeRegistration = QtGui.QPushButton(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancelRecipeRegistration.sizePolicy().hasHeightForWidth())
        self.btnCancelRecipeRegistration.setSizePolicy(sizePolicy)
        self.btnCancelRecipeRegistration.setObjectName(_fromUtf8("btnCancelRecipeRegistration"))
        self.gridLayout_5.addWidget(self.btnCancelRecipeRegistration, 3, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblMissedTypesInfo = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMissedTypesInfo.sizePolicy().hasHeightForWidth())
        self.lblMissedTypesInfo.setSizePolicy(sizePolicy)
        self.lblMissedTypesInfo.setText(_fromUtf8(""))
        self.lblMissedTypesInfo.setObjectName(_fromUtf8("lblMissedTypesInfo"))
        self.gridLayout_2.addWidget(self.lblMissedTypesInfo, 1, 0, 1, 1)
        self.tblSocStatusTypes = CTableView(self.groupBox)
        self.tblSocStatusTypes.setAutoScroll(False)
        self.tblSocStatusTypes.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblSocStatusTypes.setObjectName(_fromUtf8("tblSocStatusTypes"))
        self.tblSocStatusTypes.horizontalHeader().setCascadingSectionResizes(True)
        self.tblSocStatusTypes.horizontalHeader().setStretchLastSection(True)
        self.tblSocStatusTypes.verticalHeader().setCascadingSectionResizes(False)
        self.tblSocStatusTypes.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tblSocStatusTypes, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(LLO78RegistryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblMKB = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMKB.sizePolicy().hasHeightForWidth())
        self.lblMKB.setSizePolicy(sizePolicy)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout_3.addWidget(self.lblMKB, 0, 0, 1, 1)
        self.cmbMKB = CICDCodeEditEx(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKB.sizePolicy().hasHeightForWidth())
        self.cmbMKB.setSizePolicy(sizePolicy)
        self.cmbMKB.setObjectName(_fromUtf8("cmbMKB"))
        self.gridLayout_3.addWidget(self.cmbMKB, 0, 1, 1, 1)
        self.btnMkbSearch = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMkbSearch.sizePolicy().hasHeightForWidth())
        self.btnMkbSearch.setSizePolicy(sizePolicy)
        self.btnMkbSearch.setObjectName(_fromUtf8("btnMkbSearch"))
        self.gridLayout_3.addWidget(self.btnMkbSearch, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(666, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 4)
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.btnSignAndRegistrateRecipe.raise_()
        self.groupBox_4.raise_()
        self.btnCancelRecipeRegistration.raise_()

        self.retranslateUi(LLO78RegistryDialog)
        QtCore.QMetaObject.connectSlotsByName(LLO78RegistryDialog)

    def retranslateUi(self, LLO78RegistryDialog):
        LLO78RegistryDialog.setWindowTitle(_translate("LLO78RegistryDialog", "Регистрация рецепта", None))
        self.groupBox_3.setTitle(_translate("LLO78RegistryDialog", "Выписка", None))
        self.lblRequestedLP.setText(_translate("LLO78RegistryDialog", "Запрашиваемый препарат", None))
        self.btnFindLPs.setText(_translate("LLO78RegistryDialog", "Найти ЛП в сервисе ЛЛО", None))
        self.btnSignAndRegistrateRecipe.setText(_translate("LLO78RegistryDialog", "Подписать и зарегистрировать рецепт", None))
        self.groupBox_4.setTitle(_translate("LLO78RegistryDialog", "Другое", None))
        self.lblDischargeAttribute.setText(_translate("LLO78RegistryDialog", "Наименование ЛС в рецепте", None))
        self.cmbDischargeAttribute.setItemText(0, _translate("LLO78RegistryDialog", "МНН", None))
        self.cmbDischargeAttribute.setItemText(1, _translate("LLO78RegistryDialog", "ТРН", None))
        self.lblDischargeType.setText(_translate("LLO78RegistryDialog", "Тип выписки", None))
        self.cmbDischargeType.setItemText(0, _translate("LLO78RegistryDialog", "Упаковка", None))
        self.cmbDischargeType.setItemText(1, _translate("LLO78RegistryDialog", "Единицы ЛП и МИ", None))
        self.lblLPQuantity.setText(_translate("LLO78RegistryDialog", "Количество", None))
        self.lblUseMethod.setText(_translate("LLO78RegistryDialog", "Способ применения", None))
        self.lblRecipeExpirationDate.setText(_translate("LLO78RegistryDialog", "Срок действия рецепта", None))
        self.cmbRecipeExpirationDate.setItemText(0, _translate("LLO78RegistryDialog", "5 дней", None))
        self.cmbRecipeExpirationDate.setItemText(1, _translate("LLO78RegistryDialog", "10 дней", None))
        self.cmbRecipeExpirationDate.setItemText(2, _translate("LLO78RegistryDialog", "1 месяц", None))
        self.cmbRecipeExpirationDate.setItemText(3, _translate("LLO78RegistryDialog", "3 месяца", None))
        self.chkTypeOfProtocol.setText(_translate("LLO78RegistryDialog", "Наличие протокола ВК", None))
        self.btnCancelRecipeRegistration.setText(_translate("LLO78RegistryDialog", "Отмена", None))
        self.groupBox.setTitle(_translate("LLO78RegistryDialog", "Льгота", None))
        self.groupBox_2.setTitle(_translate("LLO78RegistryDialog", "Диагноз", None))
        self.lblMKB.setText(_translate("LLO78RegistryDialog", "Код МКБ", None))
        self.btnMkbSearch.setText(_translate("LLO78RegistryDialog", "...", None))
        self.label.setText(_translate("LLO78RegistryDialog", "Поиск доступных диагнозов по выбранной льготе", None))

from library.ICDCodeEdit import CICDCodeEditEx
from library.TableView import CTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    LLO78RegistryDialog = QtGui.QDialog()
    ui = Ui_LLO78RegistryDialog()
    ui.setupUi(LLO78RegistryDialog)
    LLO78RegistryDialog.show()
    sys.exit(app.exec_())

