# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/RefBooks/RBServiceEditor.ui'
#
# Created: Tue Apr 19 12:42:54 2016
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(623, 518)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblServiceGroup = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServiceGroup.sizePolicy().hasHeightForWidth())
        self.lblServiceGroup.setSizePolicy(sizePolicy)
        self.lblServiceGroup.setObjectName(_fromUtf8("lblServiceGroup"))
        self.gridLayout_2.addWidget(self.lblServiceGroup, 0, 0, 1, 2)
        self.cmbServiceGroup = CRBComboBox(ItemEditorDialog)
        self.cmbServiceGroup.setObjectName(_fromUtf8("cmbServiceGroup"))
        self.gridLayout_2.addWidget(self.cmbServiceGroup, 0, 2, 1, 1)
        self.lblCode = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 1, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(ItemEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 1, 2, 1, 1)
        self.edtName = QtGui.QTextEdit(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtName.sizePolicy().hasHeightForWidth())
        self.edtName.setSizePolicy(sizePolicy)
        self.edtName.setMinimumSize(QtCore.QSize(0, 66))
        self.edtName.setMaximumSize(QtCore.QSize(16777215, 66))
        self.edtName.setSizeIncrement(QtCore.QSize(0, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 2, 2, 2, 1)
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 2))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.gridLayout = QtGui.QGridLayout(self.tabInfo)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtBegDate = CDateEdit(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.edtUetChildDoctor = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetChildDoctor.sizePolicy().hasHeightForWidth())
        self.edtUetChildDoctor.setSizePolicy(sizePolicy)
        self.edtUetChildDoctor.setObjectName(_fromUtf8("edtUetChildDoctor"))
        self.gridLayout.addWidget(self.edtUetChildDoctor, 11, 1, 1, 1)
        self.edtUetAdultDoctor = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetAdultDoctor.sizePolicy().hasHeightForWidth())
        self.edtUetAdultDoctor.setSizePolicy(sizePolicy)
        self.edtUetAdultDoctor.setObjectName(_fromUtf8("edtUetAdultDoctor"))
        self.gridLayout.addWidget(self.edtUetAdultDoctor, 10, 1, 1, 1)
        self.lblUetChildDoctor = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetChildDoctor.sizePolicy().hasHeightForWidth())
        self.lblUetChildDoctor.setSizePolicy(sizePolicy)
        self.lblUetChildDoctor.setObjectName(_fromUtf8("lblUetChildDoctor"))
        self.gridLayout.addWidget(self.lblUetChildDoctor, 11, 0, 1, 1)
        self.lblUetAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.lblUetAvarageMedWorker.setSizePolicy(sizePolicy)
        self.lblUetAvarageMedWorker.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblUetAvarageMedWorker.setWordWrap(False)
        self.lblUetAvarageMedWorker.setObjectName(_fromUtf8("lblUetAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetAvarageMedWorker, 9, 2, 1, 3)
        self.edtEndDate = CDateEdit(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setMaximumDate(QtCore.QDate(2200, 12, 31))
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblUetChildAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        self.lblUetChildAvarageMedWorker.setObjectName(_fromUtf8("lblUetChildAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetChildAvarageMedWorker, 11, 2, 1, 1)
        self.edtSuperviseComplexityFactor = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSuperviseComplexityFactor.sizePolicy().hasHeightForWidth())
        self.edtSuperviseComplexityFactor.setSizePolicy(sizePolicy)
        self.edtSuperviseComplexityFactor.setDecimals(2)
        self.edtSuperviseComplexityFactor.setMaximum(9999.99)
        self.edtSuperviseComplexityFactor.setObjectName(_fromUtf8("edtSuperviseComplexityFactor"))
        self.gridLayout.addWidget(self.edtSuperviseComplexityFactor, 8, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 0, 1, 1)
        self.edtUetAdultAvarageMedWorker = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetAdultAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.edtUetAdultAvarageMedWorker.setSizePolicy(sizePolicy)
        self.edtUetAdultAvarageMedWorker.setObjectName(_fromUtf8("edtUetAdultAvarageMedWorker"))
        self.gridLayout.addWidget(self.edtUetAdultAvarageMedWorker, 10, 3, 1, 1)
        self.edtInfis = QtGui.QLineEdit(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtInfis.sizePolicy().hasHeightForWidth())
        self.edtInfis.setSizePolicy(sizePolicy)
        self.edtInfis.setObjectName(_fromUtf8("edtInfis"))
        self.gridLayout.addWidget(self.edtInfis, 2, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblQualityLevel = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQualityLevel.sizePolicy().hasHeightForWidth())
        self.lblQualityLevel.setSizePolicy(sizePolicy)
        self.lblQualityLevel.setObjectName(_fromUtf8("lblQualityLevel"))
        self.gridLayout.addWidget(self.lblQualityLevel, 7, 0, 1, 1)
        self.lblUetAdultAvarageMedWorker = QtGui.QLabel(self.tabInfo)
        self.lblUetAdultAvarageMedWorker.setObjectName(_fromUtf8("lblUetAdultAvarageMedWorker"))
        self.gridLayout.addWidget(self.lblUetAdultAvarageMedWorker, 10, 2, 1, 1)
        self.lblSuperviseComplexityFactor = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSuperviseComplexityFactor.sizePolicy().hasHeightForWidth())
        self.lblSuperviseComplexityFactor.setSizePolicy(sizePolicy)
        self.lblSuperviseComplexityFactor.setObjectName(_fromUtf8("lblSuperviseComplexityFactor"))
        self.gridLayout.addWidget(self.lblSuperviseComplexityFactor, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 11, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 3)
        self.edtUetChildAvarageMedWorker = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUetChildAvarageMedWorker.sizePolicy().hasHeightForWidth())
        self.edtUetChildAvarageMedWorker.setSizePolicy(sizePolicy)
        self.edtUetChildAvarageMedWorker.setObjectName(_fromUtf8("edtUetChildAvarageMedWorker"))
        self.gridLayout.addWidget(self.edtUetChildAvarageMedWorker, 11, 3, 1, 1)
        self.edtQualityLevel = QtGui.QDoubleSpinBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtQualityLevel.sizePolicy().hasHeightForWidth())
        self.edtQualityLevel.setSizePolicy(sizePolicy)
        self.edtQualityLevel.setDecimals(3)
        self.edtQualityLevel.setMaximum(999999.999)
        self.edtQualityLevel.setObjectName(_fromUtf8("edtQualityLevel"))
        self.gridLayout.addWidget(self.edtQualityLevel, 7, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 3)
        self.lblBegDate = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblLicense = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLicense.sizePolicy().hasHeightForWidth())
        self.lblLicense.setSizePolicy(sizePolicy)
        self.lblLicense.setObjectName(_fromUtf8("lblLicense"))
        self.gridLayout.addWidget(self.lblLicense, 5, 0, 1, 1)
        self.lblUetDoctor = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetDoctor.sizePolicy().hasHeightForWidth())
        self.lblUetDoctor.setSizePolicy(sizePolicy)
        self.lblUetDoctor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblUetDoctor.setWordWrap(False)
        self.lblUetDoctor.setObjectName(_fromUtf8("lblUetDoctor"))
        self.gridLayout.addWidget(self.lblUetDoctor, 9, 0, 1, 2)
        self.lblInfis = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfis.sizePolicy().hasHeightForWidth())
        self.lblInfis.setSizePolicy(sizePolicy)
        self.lblInfis.setObjectName(_fromUtf8("lblInfis"))
        self.gridLayout.addWidget(self.lblInfis, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 10, 4, 1, 1)
        self.cmbLicense = QtGui.QComboBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLicense.sizePolicy().hasHeightForWidth())
        self.cmbLicense.setSizePolicy(sizePolicy)
        self.cmbLicense.setObjectName(_fromUtf8("cmbLicense"))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.cmbLicense.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbLicense, 5, 1, 1, 4)
        self.lblUetAdultDoctor = QtGui.QLabel(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUetAdultDoctor.sizePolicy().hasHeightForWidth())
        self.lblUetAdultDoctor.setSizePolicy(sizePolicy)
        self.lblUetAdultDoctor.setObjectName(_fromUtf8("lblUetAdultDoctor"))
        self.gridLayout.addWidget(self.lblUetAdultDoctor, 10, 0, 1, 1)
        self.chkEisLegacy = QtGui.QCheckBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEisLegacy.sizePolicy().hasHeightForWidth())
        self.chkEisLegacy.setSizePolicy(sizePolicy)
        self.chkEisLegacy.setObjectName(_fromUtf8("chkEisLegacy"))
        self.gridLayout.addWidget(self.chkEisLegacy, 3, 1, 1, 4)
        self.chkNomenclatureLegacy = QtGui.QCheckBox(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkNomenclatureLegacy.sizePolicy().hasHeightForWidth())
        self.chkNomenclatureLegacy.setSizePolicy(sizePolicy)
        self.chkNomenclatureLegacy.setObjectName(_fromUtf8("chkNomenclatureLegacy"))
        self.gridLayout.addWidget(self.chkNomenclatureLegacy, 4, 1, 1, 4)
        self.edtNote = QtGui.QLineEdit(self.tabInfo)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 12, 1, 1, 4)
        self.lblNote = QtGui.QLabel(self.tabInfo)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 12, 0, 1, 1)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabContent = QtGui.QWidget()
        self.tabContent.setObjectName(_fromUtf8("tabContent"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabContent)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblServices = CInDocTableView(self.tabContent)
        self.tblServices.setObjectName(_fromUtf8("tblServices"))
        self.verticalLayout.addWidget(self.tblServices)
        self.tabWidget.addTab(self.tabContent, _fromUtf8(""))
        self.tabMedicalAidProfiles = QtGui.QWidget()
        self.tabMedicalAidProfiles.setObjectName(_fromUtf8("tabMedicalAidProfiles"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabMedicalAidProfiles)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblProfiles = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProfiles.sizePolicy().hasHeightForWidth())
        self.lblProfiles.setSizePolicy(sizePolicy)
        self.lblProfiles.setObjectName(_fromUtf8("lblProfiles"))
        self.gridLayout_3.addWidget(self.lblProfiles, 0, 0, 1, 1)
        self.cmbMedicalAidProfile = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidProfile.setObjectName(_fromUtf8("cmbMedicalAidProfile"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidProfile, 0, 1, 1, 1)
        self.tblMedicalAidProfiles = CInDocTableView(self.tabMedicalAidProfiles)
        self.tblMedicalAidProfiles.setObjectName(_fromUtf8("tblMedicalAidProfiles"))
        self.gridLayout_3.addWidget(self.tblMedicalAidProfiles, 3, 0, 1, 2)
        self.lblMedicalAidProfile = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidProfile.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidProfile.setSizePolicy(sizePolicy)
        self.lblMedicalAidProfile.setObjectName(_fromUtf8("lblMedicalAidProfile"))
        self.gridLayout_3.addWidget(self.lblMedicalAidProfile, 2, 0, 1, 1)
        self.cmbMedicalAidType = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidType.setObjectName(_fromUtf8("cmbMedicalAidType"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidType, 2, 1, 1, 1)
        self.cmbMedicalAidKind = CRBComboBox(self.tabMedicalAidProfiles)
        self.cmbMedicalAidKind.setObjectName(_fromUtf8("cmbMedicalAidKind"))
        self.gridLayout_3.addWidget(self.cmbMedicalAidKind, 1, 1, 1, 1)
        self.lblMedicalAidKind = QtGui.QLabel(self.tabMedicalAidProfiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidKind.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidKind.setSizePolicy(sizePolicy)
        self.lblMedicalAidKind.setObjectName(_fromUtf8("lblMedicalAidKind"))
        self.gridLayout_3.addWidget(self.lblMedicalAidKind, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabMedicalAidProfiles, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_4.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 4, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 5, 0, 1, 3)
        self.lblName = QtGui.QLabel(ItemEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 2, 0, 2, 2)
        self.lblServiceGroup.setBuddy(self.cmbServiceGroup)
        self.lblCode.setBuddy(self.edtCode)
        self.lblUetChildDoctor.setBuddy(self.edtUetChildDoctor)
        self.lblUetChildAvarageMedWorker.setBuddy(self.edtUetChildAvarageMedWorker)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblQualityLevel.setBuddy(self.edtQualityLevel)
        self.lblUetAdultAvarageMedWorker.setBuddy(self.edtUetAdultAvarageMedWorker)
        self.lblSuperviseComplexityFactor.setBuddy(self.edtSuperviseComplexityFactor)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblLicense.setBuddy(self.cmbLicense)
        self.lblInfis.setBuddy(self.edtInfis)
        self.lblUetAdultDoctor.setBuddy(self.edtUetAdultDoctor)
        self.lblNote.setBuddy(self.edtNote)
        self.lblProfiles.setBuddy(self.cmbMedicalAidProfile)
        self.lblMedicalAidProfile.setBuddy(self.cmbMedicalAidType)
        self.lblMedicalAidKind.setBuddy(self.cmbMedicalAidKind)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.cmbServiceGroup, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.tabWidget)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtBegDate)
        ItemEditorDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ItemEditorDialog.setTabOrder(self.edtEndDate, self.edtInfis)
        ItemEditorDialog.setTabOrder(self.edtInfis, self.chkEisLegacy)
        ItemEditorDialog.setTabOrder(self.chkEisLegacy, self.chkNomenclatureLegacy)
        ItemEditorDialog.setTabOrder(self.chkNomenclatureLegacy, self.cmbLicense)
        ItemEditorDialog.setTabOrder(self.cmbLicense, self.edtQualityLevel)
        ItemEditorDialog.setTabOrder(self.edtQualityLevel, self.edtSuperviseComplexityFactor)
        ItemEditorDialog.setTabOrder(self.edtSuperviseComplexityFactor, self.edtUetAdultDoctor)
        ItemEditorDialog.setTabOrder(self.edtUetAdultDoctor, self.edtUetAdultAvarageMedWorker)
        ItemEditorDialog.setTabOrder(self.edtUetAdultAvarageMedWorker, self.edtUetChildDoctor)
        ItemEditorDialog.setTabOrder(self.edtUetChildDoctor, self.edtUetChildAvarageMedWorker)
        ItemEditorDialog.setTabOrder(self.edtUetChildAvarageMedWorker, self.edtNote)
        ItemEditorDialog.setTabOrder(self.edtNote, self.tblServices)
        ItemEditorDialog.setTabOrder(self.tblServices, self.cmbMedicalAidProfile)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidProfile, self.cmbMedicalAidKind)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidKind, self.cmbMedicalAidType)
        ItemEditorDialog.setTabOrder(self.cmbMedicalAidType, self.tblMedicalAidProfiles)
        ItemEditorDialog.setTabOrder(self.tblMedicalAidProfiles, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblServiceGroup.setText(_translate("ItemEditorDialog", "&Группа", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.edtBegDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lblUetChildDoctor.setText(_translate("ItemEditorDialog", "Детский", None))
        self.lblUetAvarageMedWorker.setText(_translate("ItemEditorDialog", "УЕТ для среднего медицинского персонала", None))
        self.edtEndDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lblUetChildAvarageMedWorker.setText(_translate("ItemEditorDialog", "Детский", None))
        self.lblEndDate.setText(_translate("ItemEditorDialog", "Конечная дата", None))
        self.lblQualityLevel.setText(_translate("ItemEditorDialog", "Уровень качества лечения", None))
        self.lblUetAdultAvarageMedWorker.setText(_translate("ItemEditorDialog", "Взрослый", None))
        self.lblSuperviseComplexityFactor.setText(_translate("ItemEditorDialog", "Коэффициент сложности курации", None))
        self.lblBegDate.setText(_translate("ItemEditorDialog", "Начальная дата", None))
        self.lblLicense.setText(_translate("ItemEditorDialog", "&Лицензирование", None))
        self.lblUetDoctor.setText(_translate("ItemEditorDialog", "УЕТ для врача", None))
        self.lblInfis.setText(_translate("ItemEditorDialog", "Код &ИНФИС", None))
        self.cmbLicense.setItemText(0, _translate("ItemEditorDialog", "не требуется", None))
        self.cmbLicense.setItemText(1, _translate("ItemEditorDialog", "требуется лицензия", None))
        self.cmbLicense.setItemText(2, _translate("ItemEditorDialog", "требуется персональный сертификат", None))
        self.lblUetAdultDoctor.setText(_translate("ItemEditorDialog", "Взрослый", None))
        self.chkEisLegacy.setText(_translate("ItemEditorDialog", "&Унаследовано из ЕИС", None))
        self.chkNomenclatureLegacy.setText(_translate("ItemEditorDialog", "Унаследовано из номенклатуры минздрава", None))
        self.lblNote.setText(_translate("ItemEditorDialog", "Примечание", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("ItemEditorDialog", "Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContent), _translate("ItemEditorDialog", "Состав", None))
        self.lblProfiles.setText(_translate("ItemEditorDialog", "Профиль по умолчанию", None))
        self.lblMedicalAidProfile.setText(_translate("ItemEditorDialog", "Тип по умолчанию", None))
        self.lblMedicalAidKind.setText(_translate("ItemEditorDialog", "Вид по умолчанию", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalAidProfiles), _translate("ItemEditorDialog", "Профили, виды и типы помощи", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "Идентификация", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ItemEditorDialog = QtGui.QDialog()
    ui = Ui_ItemEditorDialog()
    ui.setupUi(ItemEditorDialog)
    ItemEditorDialog.show()
    sys.exit(app.exec_())

