# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\soc-inform\RefBooks\OrgStructure\OrgStructureEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(788, 762)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout = QtGui.QGridLayout(self.tabMain)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbChief = CPersonComboBoxEx(self.tabMain)
        self.cmbChief.setObjectName(_fromUtf8("cmbChief"))
        self.gridLayout.addWidget(self.cmbChief, 10, 1, 1, 2)
        self.edtBookkeeperCode = QtGui.QLineEdit(self.tabMain)
        self.edtBookkeeperCode.setToolTip(_fromUtf8(""))
        self.edtBookkeeperCode.setMaxLength(16)
        self.edtBookkeeperCode.setObjectName(_fromUtf8("edtBookkeeperCode"))
        self.gridLayout.addWidget(self.edtBookkeeperCode, 4, 1, 1, 2)
        self.edtNote = QtGui.QPlainTextEdit(self.tabMain)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 28, 1, 2, 2)
        self.lblAreaType = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAreaType.sizePolicy().hasHeightForWidth())
        self.lblAreaType.setSizePolicy(sizePolicy)
        self.lblAreaType.setObjectName(_fromUtf8("lblAreaType"))
        self.gridLayout.addWidget(self.lblAreaType, 18, 0, 1, 1)
        self.lblPhone = QtGui.QLabel(self.tabMain)
        self.lblPhone.setObjectName(_fromUtf8("lblPhone"))
        self.gridLayout.addWidget(self.lblPhone, 7, 0, 1, 1)
        self.chkMainStocks = QtGui.QCheckBox(self.tabMain)
        self.chkMainStocks.setEnabled(False)
        self.chkMainStocks.setObjectName(_fromUtf8("chkMainStocks"))
        self.gridLayout.addWidget(self.chkMainStocks, 22, 1, 1, 1)
        self.chkHasHospitalBeds = QtGui.QCheckBox(self.tabMain)
        self.chkHasHospitalBeds.setObjectName(_fromUtf8("chkHasHospitalBeds"))
        self.gridLayout.addWidget(self.chkHasHospitalBeds, 19, 1, 1, 2)
        self.edtInfisDepTypeCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisDepTypeCode.setToolTip(_fromUtf8(""))
        self.edtInfisDepTypeCode.setMaxLength(16)
        self.edtInfisDepTypeCode.setObjectName(_fromUtf8("edtInfisDepTypeCode"))
        self.gridLayout.addWidget(self.edtInfisDepTypeCode, 14, 1, 1, 2)
        self.edtTfomsCode = QtGui.QLineEdit(self.tabMain)
        self.edtTfomsCode.setToolTip(_fromUtf8(""))
        self.edtTfomsCode.setMaxLength(32)
        self.edtTfomsCode.setObjectName(_fromUtf8("edtTfomsCode"))
        self.gridLayout.addWidget(self.edtTfomsCode, 17, 1, 1, 2)
        self.cmbParent = CDbComboBox(self.tabMain)
        self.cmbParent.setEnabled(False)
        self.cmbParent.setFrame(True)
        self.cmbParent.setObjectName(_fromUtf8("cmbParent"))
        self.gridLayout.addWidget(self.cmbParent, 1, 1, 1, 2)
        self.cmbNet = CRBComboBox(self.tabMain)
        self.cmbNet.setObjectName(_fromUtf8("cmbNet"))
        self.gridLayout.addWidget(self.cmbNet, 9, 1, 1, 2)
        self.cmbOrganisation = COrgComboBox(self.tabMain)
        self.cmbOrganisation.setEnabled(True)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout.addWidget(self.cmbOrganisation, 0, 1, 1, 1)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 3, 0, 1, 1)
        self.edtPhone = QtGui.QLineEdit(self.tabMain)
        self.edtPhone.setMaxLength(64)
        self.edtPhone.setObjectName(_fromUtf8("edtPhone"))
        self.gridLayout.addWidget(self.edtPhone, 7, 1, 1, 2)
        self.edtInfisCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisCode.setMaxLength(16)
        self.edtInfisCode.setObjectName(_fromUtf8("edtInfisCode"))
        self.gridLayout.addWidget(self.edtInfisCode, 12, 1, 1, 2)
        self.lblHeadNurse = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHeadNurse.sizePolicy().hasHeightForWidth())
        self.lblHeadNurse.setSizePolicy(sizePolicy)
        self.lblHeadNurse.setObjectName(_fromUtf8("lblHeadNurse"))
        self.gridLayout.addWidget(self.lblHeadNurse, 11, 0, 1, 1)
        self.lblName_2 = QtGui.QLabel(self.tabMain)
        self.lblName_2.setObjectName(_fromUtf8("lblName_2"))
        self.gridLayout.addWidget(self.lblName_2, 28, 0, 1, 1)
        self.edtAddress = QtGui.QLineEdit(self.tabMain)
        self.edtAddress.setMaxLength(250)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.gridLayout.addWidget(self.edtAddress, 6, 1, 1, 2)
        self.lblInfisDepTypeCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisDepTypeCode.sizePolicy().hasHeightForWidth())
        self.lblInfisDepTypeCode.setSizePolicy(sizePolicy)
        self.lblInfisDepTypeCode.setObjectName(_fromUtf8("lblInfisDepTypeCode"))
        self.gridLayout.addWidget(self.lblInfisDepTypeCode, 14, 0, 1, 1)
        self.lblInfisInternalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisInternalCode.sizePolicy().hasHeightForWidth())
        self.lblInfisInternalCode.setSizePolicy(sizePolicy)
        self.lblInfisInternalCode.setObjectName(_fromUtf8("lblInfisInternalCode"))
        self.gridLayout.addWidget(self.lblInfisInternalCode, 13, 0, 1, 1)
        self.edtInfisTariffCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisTariffCode.setToolTip(_fromUtf8(""))
        self.edtInfisTariffCode.setMaxLength(16)
        self.edtInfisTariffCode.setObjectName(_fromUtf8("edtInfisTariffCode"))
        self.gridLayout.addWidget(self.edtInfisTariffCode, 16, 1, 1, 2)
        self.lblParent = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblParent.sizePolicy().hasHeightForWidth())
        self.lblParent.setSizePolicy(sizePolicy)
        self.lblParent.setObjectName(_fromUtf8("lblParent"))
        self.gridLayout.addWidget(self.lblParent, 1, 0, 1, 1)
        self.lblTfomsCode = QtGui.QLabel(self.tabMain)
        self.lblTfomsCode.setObjectName(_fromUtf8("lblTfomsCode"))
        self.gridLayout.addWidget(self.lblTfomsCode, 17, 0, 1, 1)
        self.lblOrganisation = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisation.sizePolicy().hasHeightForWidth())
        self.lblOrganisation.setSizePolicy(sizePolicy)
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout.addWidget(self.lblOrganisation, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setMaxLength(64)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 2, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 29, 0, 1, 1)
        self.lblType = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 8, 0, 1, 1)
        self.edtWarnAboutExpirationDateDrugStock = QtGui.QSpinBox(self.tabMain)
        self.edtWarnAboutExpirationDateDrugStock.setEnabled(False)
        self.edtWarnAboutExpirationDateDrugStock.setMaximum(999999999)
        self.edtWarnAboutExpirationDateDrugStock.setObjectName(_fromUtf8("edtWarnAboutExpirationDateDrugStock"))
        self.gridLayout.addWidget(self.edtWarnAboutExpirationDateDrugStock, 23, 2, 1, 1)
        self.edtEmsProfileCode = QtGui.QLineEdit(self.tabMain)
        self.edtEmsProfileCode.setEnabled(False)
        self.edtEmsProfileCode.setObjectName(_fromUtf8("edtEmsProfileCode"))
        self.gridLayout.addWidget(self.edtEmsProfileCode, 20, 1, 1, 2)
        self.chkHasStocks = QtGui.QCheckBox(self.tabMain)
        self.chkHasStocks.setObjectName(_fromUtf8("chkHasStocks"))
        self.gridLayout.addWidget(self.chkHasStocks, 21, 1, 1, 2)
        self.cmbAreaType = QtGui.QComboBox(self.tabMain)
        self.cmbAreaType.setObjectName(_fromUtf8("cmbAreaType"))
        self.cmbAreaType.addItem(_fromUtf8(""))
        self.cmbAreaType.addItem(_fromUtf8(""))
        self.cmbAreaType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAreaType, 18, 1, 1, 2)
        self.lblInfisCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisCode.sizePolicy().hasHeightForWidth())
        self.lblInfisCode.setSizePolicy(sizePolicy)
        self.lblInfisCode.setObjectName(_fromUtf8("lblInfisCode"))
        self.gridLayout.addWidget(self.lblInfisCode, 12, 0, 1, 1)
        self.edtInfisInternalCode = QtGui.QLineEdit(self.tabMain)
        self.edtInfisInternalCode.setMaxLength(16)
        self.edtInfisInternalCode.setObjectName(_fromUtf8("edtInfisInternalCode"))
        self.gridLayout.addWidget(self.edtInfisInternalCode, 13, 1, 1, 2)
        self.btnSelectOrganisation = QtGui.QToolButton(self.tabMain)
        self.btnSelectOrganisation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout.addWidget(self.btnSelectOrganisation, 0, 2, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 2, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setMaxLength(256)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 3, 1, 1, 2)
        self.chkWarnAboutExpirationDateDrugStock = QtGui.QCheckBox(self.tabMain)
        self.chkWarnAboutExpirationDateDrugStock.setEnabled(False)
        self.chkWarnAboutExpirationDateDrugStock.setObjectName(_fromUtf8("chkWarnAboutExpirationDateDrugStock"))
        self.gridLayout.addWidget(self.chkWarnAboutExpirationDateDrugStock, 23, 1, 1, 1)
        self.lblBookkeeperCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBookkeeperCode.sizePolicy().hasHeightForWidth())
        self.lblBookkeeperCode.setSizePolicy(sizePolicy)
        self.lblBookkeeperCode.setObjectName(_fromUtf8("lblBookkeeperCode"))
        self.gridLayout.addWidget(self.lblBookkeeperCode, 4, 0, 1, 1)
        self.lblInfisTariffCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfisTariffCode.sizePolicy().hasHeightForWidth())
        self.lblInfisTariffCode.setSizePolicy(sizePolicy)
        self.lblInfisTariffCode.setObjectName(_fromUtf8("lblInfisTariffCode"))
        self.gridLayout.addWidget(self.lblInfisTariffCode, 16, 0, 1, 1)
        self.lblNet = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNet.sizePolicy().hasHeightForWidth())
        self.lblNet.setSizePolicy(sizePolicy)
        self.lblNet.setObjectName(_fromUtf8("lblNet"))
        self.gridLayout.addWidget(self.lblNet, 9, 0, 1, 1)
        self.cmbHeadNurse = CPersonComboBoxEx(self.tabMain)
        self.cmbHeadNurse.setObjectName(_fromUtf8("cmbHeadNurse"))
        self.gridLayout.addWidget(self.cmbHeadNurse, 11, 1, 1, 2)
        self.lblAddress = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAddress.sizePolicy().hasHeightForWidth())
        self.lblAddress.setSizePolicy(sizePolicy)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout.addWidget(self.lblAddress, 6, 0, 1, 1)
        self.lblChief = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblChief.sizePolicy().hasHeightForWidth())
        self.lblChief.setSizePolicy(sizePolicy)
        self.lblChief.setObjectName(_fromUtf8("lblChief"))
        self.gridLayout.addWidget(self.lblChief, 10, 0, 1, 1)
        self.lblEmsProfileCode = QtGui.QLabel(self.tabMain)
        self.lblEmsProfileCode.setEnabled(False)
        self.lblEmsProfileCode.setObjectName(_fromUtf8("lblEmsProfileCode"))
        self.gridLayout.addWidget(self.lblEmsProfileCode, 20, 0, 1, 1)
        self.cmbType = QtGui.QComboBox(self.tabMain)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbType, 8, 1, 1, 2)
        self.chkFAP = QtGui.QCheckBox(self.tabMain)
        self.chkFAP.setObjectName(_fromUtf8("chkFAP"))
        self.gridLayout.addWidget(self.chkFAP, 25, 1, 1, 1)
        self.chkAvailableForExternal = QtGui.QCheckBox(self.tabMain)
        self.chkAvailableForExternal.setObjectName(_fromUtf8("chkAvailableForExternal"))
        self.gridLayout.addWidget(self.chkAvailableForExternal, 24, 1, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabAddress = QtGui.QWidget()
        self.tabAddress.setEnabled(True)
        self.tabAddress.setObjectName(_fromUtf8("tabAddress"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabAddress)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblAddress = CTableView(self.tabAddress)
        self.tblAddress.setEnabled(False)
        self.tblAddress.setObjectName(_fromUtf8("tblAddress"))
        self.gridLayout_2.addWidget(self.tblAddress, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAddress, _fromUtf8(""))
        self.tablPlacements = QtGui.QWidget()
        self.tablPlacements.setObjectName(_fromUtf8("tablPlacements"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tablPlacements)
        self.gridLayout_12.setMargin(4)
        self.gridLayout_12.setSpacing(4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tblPlacements = CInDocTableView(self.tablPlacements)
        self.tblPlacements.setObjectName(_fromUtf8("tblPlacements"))
        self.gridLayout_12.addWidget(self.tblPlacements, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tablPlacements, _fromUtf8(""))
        self.tabHospitalBeds = QtGui.QWidget()
        self.tabHospitalBeds.setEnabled(True)
        self.tabHospitalBeds.setObjectName(_fromUtf8("tabHospitalBeds"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabHospitalBeds)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.vsplitter = QtGui.QSplitter(self.tabHospitalBeds)
        self.vsplitter.setOrientation(QtCore.Qt.Vertical)
        self.vsplitter.setChildrenCollapsible(False)
        self.vsplitter.setObjectName(_fromUtf8("vsplitter"))
        self.tblHospitalBeds = CInDocTableView(self.vsplitter)
        self.tblHospitalBeds.setEnabled(True)
        self.tblHospitalBeds.setObjectName(_fromUtf8("tblHospitalBeds"))
        self.tblInvoluteBeds = CInDocTableView(self.vsplitter)
        self.tblInvoluteBeds.setEnabled(True)
        self.tblInvoluteBeds.setObjectName(_fromUtf8("tblInvoluteBeds"))
        self.gridLayout_4.addWidget(self.vsplitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabHospitalBeds, _fromUtf8(""))
        self.tabJobs = QtGui.QWidget()
        self.tabJobs.setObjectName(_fromUtf8("tabJobs"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabJobs)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cmbJobTimelinePeriod = QtGui.QComboBox(self.tabJobs)
        self.cmbJobTimelinePeriod.setObjectName(_fromUtf8("cmbJobTimelinePeriod"))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.cmbJobTimelinePeriod.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbJobTimelinePeriod, 0, 0, 1, 1)
        self.lblJobTimelineCustomLength = QtGui.QLabel(self.tabJobs)
        self.lblJobTimelineCustomLength.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJobTimelineCustomLength.sizePolicy().hasHeightForWidth())
        self.lblJobTimelineCustomLength.setSizePolicy(sizePolicy)
        self.lblJobTimelineCustomLength.setObjectName(_fromUtf8("lblJobTimelineCustomLength"))
        self.gridLayout_6.addWidget(self.lblJobTimelineCustomLength, 0, 1, 1, 1)
        self.edtJobTimelineCustomLength = QtGui.QSpinBox(self.tabJobs)
        self.edtJobTimelineCustomLength.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtJobTimelineCustomLength.sizePolicy().hasHeightForWidth())
        self.edtJobTimelineCustomLength.setSizePolicy(sizePolicy)
        self.edtJobTimelineCustomLength.setMinimum(3)
        self.edtJobTimelineCustomLength.setMaximum(31)
        self.edtJobTimelineCustomLength.setProperty("value", 3)
        self.edtJobTimelineCustomLength.setObjectName(_fromUtf8("edtJobTimelineCustomLength"))
        self.gridLayout_6.addWidget(self.edtJobTimelineCustomLength, 0, 2, 1, 1)
        self.chkJobFillRedDays = QtGui.QCheckBox(self.tabJobs)
        self.chkJobFillRedDays.setObjectName(_fromUtf8("chkJobFillRedDays"))
        self.gridLayout_6.addWidget(self.chkJobFillRedDays, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(126, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 4, 1, 1)
        self.tblJobs = COrgSrtuctureJobsView(self.tabJobs)
        self.tblJobs.setObjectName(_fromUtf8("tblJobs"))
        self.gridLayout_6.addWidget(self.tblJobs, 1, 0, 1, 5)
        self.tabWidget.addTab(self.tabJobs, _fromUtf8(""))
        self.tabGaps = QtGui.QWidget()
        self.tabGaps.setObjectName(_fromUtf8("tabGaps"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabGaps)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblGaps = CInDocTableView(self.tabGaps)
        self.tblGaps.setEnabled(True)
        self.tblGaps.setObjectName(_fromUtf8("tblGaps"))
        self.gridLayout_5.addWidget(self.tblGaps, 1, 0, 1, 1)
        self.chkInheritGaps = QtGui.QCheckBox(self.tabGaps)
        self.chkInheritGaps.setObjectName(_fromUtf8("chkInheritGaps"))
        self.gridLayout_5.addWidget(self.chkInheritGaps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGaps, _fromUtf8(""))
        self.tabEventTypes = QtGui.QWidget()
        self.tabEventTypes.setObjectName(_fromUtf8("tabEventTypes"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabEventTypes)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.chkInheritEventTypes = QtGui.QCheckBox(self.tabEventTypes)
        self.chkInheritEventTypes.setObjectName(_fromUtf8("chkInheritEventTypes"))
        self.gridLayout_7.addWidget(self.chkInheritEventTypes, 0, 0, 1, 1)
        self.tblEventTypes = CInDocTableView(self.tabEventTypes)
        self.tblEventTypes.setEnabled(True)
        self.tblEventTypes.setObjectName(_fromUtf8("tblEventTypes"))
        self.gridLayout_7.addWidget(self.tblEventTypes, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabEventTypes, _fromUtf8(""))
        self.tabActionTypes = QtGui.QWidget()
        self.tabActionTypes.setObjectName(_fromUtf8("tabActionTypes"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabActionTypes)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblQuotaType = QtGui.QLabel(self.tabActionTypes)
        self.lblQuotaType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblQuotaType.setObjectName(_fromUtf8("lblQuotaType"))
        self.gridLayout_8.addWidget(self.lblQuotaType, 0, 2, 1, 1)
        self.chkInheritActionTypes = QtGui.QCheckBox(self.tabActionTypes)
        self.chkInheritActionTypes.setObjectName(_fromUtf8("chkInheritActionTypes"))
        self.gridLayout_8.addWidget(self.chkInheritActionTypes, 0, 4, 1, 1)
        self.cmbTissueType = CRBComboBox(self.tabActionTypes)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout_8.addWidget(self.cmbTissueType, 1, 1, 1, 1)
        self.cmbServiceType = CActionServiceTypeComboBox(self.tabActionTypes)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridLayout_8.addWidget(self.cmbServiceType, 1, 3, 1, 1)
        self.tblActionTypes = CInDocTableView(self.tabActionTypes)
        self.tblActionTypes.setEnabled(True)
        self.tblActionTypes.setObjectName(_fromUtf8("tblActionTypes"))
        self.gridLayout_8.addWidget(self.tblActionTypes, 3, 0, 1, 5)
        self.lblService = QtGui.QLabel(self.tabActionTypes)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridLayout_8.addWidget(self.lblService, 0, 0, 1, 1)
        self.cmbService = CRBComboBox(self.tabActionTypes)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridLayout_8.addWidget(self.cmbService, 0, 1, 1, 1)
        self.cmbQuotaType = CRBComboBox(self.tabActionTypes)
        self.cmbQuotaType.setObjectName(_fromUtf8("cmbQuotaType"))
        self.gridLayout_8.addWidget(self.cmbQuotaType, 0, 3, 1, 1)
        self.lblTissueType = QtGui.QLabel(self.tabActionTypes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueType.sizePolicy().hasHeightForWidth())
        self.lblTissueType.setSizePolicy(sizePolicy)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout_8.addWidget(self.lblTissueType, 1, 0, 1, 1)
        self.lblServiceType = QtGui.QLabel(self.tabActionTypes)
        self.lblServiceType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblServiceType.setObjectName(_fromUtf8("lblServiceType"))
        self.gridLayout_8.addWidget(self.lblServiceType, 1, 2, 1, 1)
        self.lblActionTypeCode = QtGui.QLabel(self.tabActionTypes)
        self.lblActionTypeCode.setObjectName(_fromUtf8("lblActionTypeCode"))
        self.gridLayout_8.addWidget(self.lblActionTypeCode, 2, 0, 1, 1)
        self.edtActionTypeCode = QtGui.QLineEdit(self.tabActionTypes)
        self.edtActionTypeCode.setObjectName(_fromUtf8("edtActionTypeCode"))
        self.gridLayout_8.addWidget(self.edtActionTypeCode, 2, 1, 1, 1)
        self.lblActionTypeName = QtGui.QLabel(self.tabActionTypes)
        self.lblActionTypeName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblActionTypeName.setObjectName(_fromUtf8("lblActionTypeName"))
        self.gridLayout_8.addWidget(self.lblActionTypeName, 2, 2, 1, 1)
        self.edtActionTypeName = QtGui.QLineEdit(self.tabActionTypes)
        self.edtActionTypeName.setObjectName(_fromUtf8("edtActionTypeName"))
        self.gridLayout_8.addWidget(self.edtActionTypeName, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabActionTypes, _fromUtf8(""))
        self.tabDisabledAttendance = QtGui.QWidget()
        self.tabDisabledAttendance.setObjectName(_fromUtf8("tabDisabledAttendance"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabDisabledAttendance)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblDisabledAttendance = CInDocTableView(self.tabDisabledAttendance)
        self.tblDisabledAttendance.setObjectName(_fromUtf8("tblDisabledAttendance"))
        self.gridLayout_9.addWidget(self.tblDisabledAttendance, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDisabledAttendance, _fromUtf8(""))
        self.tabStocks = QtGui.QWidget()
        self.tabStocks.setObjectName(_fromUtf8("tabStocks"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabStocks)
        self.gridLayout_10.setMargin(4)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tblStocks = CInDocTableView(self.tabStocks)
        self.tblStocks.setObjectName(_fromUtf8("tblStocks"))
        self.gridLayout_10.addWidget(self.tblStocks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabStocks, _fromUtf8(""))
        self.tabEquipment = QtGui.QWidget()
        self.tabEquipment.setObjectName(_fromUtf8("tabEquipment"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabEquipment)
        self.gridLayout_11.setMargin(4)
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblEquipments = CInDocTableView(self.tabEquipment)
        self.tblEquipments.setObjectName(_fromUtf8("tblEquipments"))
        self.gridLayout_11.addWidget(self.tblEquipments, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabEquipment, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_13.setMargin(4)
        self.gridLayout_13.setSpacing(4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_13.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.lblAreaType.setBuddy(self.cmbAreaType)
        self.lblPhone.setBuddy(self.edtPhone)
        self.lblName.setBuddy(self.edtName)
        self.lblHeadNurse.setBuddy(self.cmbHeadNurse)
        self.lblName_2.setBuddy(self.edtNote)
        self.lblInfisDepTypeCode.setBuddy(self.edtInfisDepTypeCode)
        self.lblInfisInternalCode.setBuddy(self.edtInfisInternalCode)
        self.lblParent.setBuddy(self.cmbParent)
        self.lblTfomsCode.setBuddy(self.edtTfomsCode)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblType.setBuddy(self.cmbType)
        self.lblInfisCode.setBuddy(self.edtInfisCode)
        self.lblCode.setBuddy(self.edtCode)
        self.lblBookkeeperCode.setBuddy(self.edtBookkeeperCode)
        self.lblInfisTariffCode.setBuddy(self.edtInfisTariffCode)
        self.lblNet.setBuddy(self.cmbNet)
        self.lblAddress.setBuddy(self.edtAddress)
        self.lblChief.setBuddy(self.cmbChief)
        self.lblEmsProfileCode.setBuddy(self.edtEmsProfileCode)
        self.lblJobTimelineCustomLength.setBuddy(self.edtJobTimelineCustomLength)
        self.lblQuotaType.setBuddy(self.cmbQuotaType)
        self.lblService.setBuddy(self.cmbService)
        self.lblTissueType.setBuddy(self.cmbTissueType)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QObject.connect(self.chkHasHospitalBeds, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEmsProfileCode.setEnabled)
        QtCore.QObject.connect(self.chkHasHospitalBeds, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblEmsProfileCode.setEnabled)
        QtCore.QObject.connect(self.chkWarnAboutExpirationDateDrugStock, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtWarnAboutExpirationDateDrugStock.setEnabled)
        QtCore.QObject.connect(self.chkHasStocks, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkWarnAboutExpirationDateDrugStock.setEnabled)
        QtCore.QObject.connect(self.chkHasStocks, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtWarnAboutExpirationDateDrugStock.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.cmbOrganisation)
        ItemEditorDialog.setTabOrder(self.cmbOrganisation, self.btnSelectOrganisation)
        ItemEditorDialog.setTabOrder(self.btnSelectOrganisation, self.cmbParent)
        ItemEditorDialog.setTabOrder(self.cmbParent, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtBookkeeperCode)
        ItemEditorDialog.setTabOrder(self.edtBookkeeperCode, self.edtAddress)
        ItemEditorDialog.setTabOrder(self.edtAddress, self.edtPhone)
        ItemEditorDialog.setTabOrder(self.edtPhone, self.cmbType)
        ItemEditorDialog.setTabOrder(self.cmbType, self.cmbNet)
        ItemEditorDialog.setTabOrder(self.cmbNet, self.cmbChief)
        ItemEditorDialog.setTabOrder(self.cmbChief, self.cmbHeadNurse)
        ItemEditorDialog.setTabOrder(self.cmbHeadNurse, self.edtInfisCode)
        ItemEditorDialog.setTabOrder(self.edtInfisCode, self.edtInfisInternalCode)
        ItemEditorDialog.setTabOrder(self.edtInfisInternalCode, self.edtInfisDepTypeCode)
        ItemEditorDialog.setTabOrder(self.edtInfisDepTypeCode, self.edtInfisTariffCode)
        ItemEditorDialog.setTabOrder(self.edtInfisTariffCode, self.edtTfomsCode)
        ItemEditorDialog.setTabOrder(self.edtTfomsCode, self.cmbAreaType)
        ItemEditorDialog.setTabOrder(self.cmbAreaType, self.chkHasHospitalBeds)
        ItemEditorDialog.setTabOrder(self.chkHasHospitalBeds, self.edtEmsProfileCode)
        ItemEditorDialog.setTabOrder(self.edtEmsProfileCode, self.chkHasStocks)
        ItemEditorDialog.setTabOrder(self.chkHasStocks, self.chkMainStocks)
        ItemEditorDialog.setTabOrder(self.chkMainStocks, self.chkWarnAboutExpirationDateDrugStock)
        ItemEditorDialog.setTabOrder(self.chkWarnAboutExpirationDateDrugStock, self.edtWarnAboutExpirationDateDrugStock)
        ItemEditorDialog.setTabOrder(self.edtWarnAboutExpirationDateDrugStock, self.edtNote)
        ItemEditorDialog.setTabOrder(self.edtNote, self.tblAddress)
        ItemEditorDialog.setTabOrder(self.tblAddress, self.tblPlacements)
        ItemEditorDialog.setTabOrder(self.tblPlacements, self.tblHospitalBeds)
        ItemEditorDialog.setTabOrder(self.tblHospitalBeds, self.tblInvoluteBeds)
        ItemEditorDialog.setTabOrder(self.tblInvoluteBeds, self.cmbJobTimelinePeriod)
        ItemEditorDialog.setTabOrder(self.cmbJobTimelinePeriod, self.edtJobTimelineCustomLength)
        ItemEditorDialog.setTabOrder(self.edtJobTimelineCustomLength, self.chkJobFillRedDays)
        ItemEditorDialog.setTabOrder(self.chkJobFillRedDays, self.tblJobs)
        ItemEditorDialog.setTabOrder(self.tblJobs, self.chkInheritGaps)
        ItemEditorDialog.setTabOrder(self.chkInheritGaps, self.tblGaps)
        ItemEditorDialog.setTabOrder(self.tblGaps, self.chkInheritEventTypes)
        ItemEditorDialog.setTabOrder(self.chkInheritEventTypes, self.tblEventTypes)
        ItemEditorDialog.setTabOrder(self.tblEventTypes, self.cmbService)
        ItemEditorDialog.setTabOrder(self.cmbService, self.cmbQuotaType)
        ItemEditorDialog.setTabOrder(self.cmbQuotaType, self.chkInheritActionTypes)
        ItemEditorDialog.setTabOrder(self.chkInheritActionTypes, self.cmbTissueType)
        ItemEditorDialog.setTabOrder(self.cmbTissueType, self.cmbServiceType)
        ItemEditorDialog.setTabOrder(self.cmbServiceType, self.edtActionTypeCode)
        ItemEditorDialog.setTabOrder(self.edtActionTypeCode, self.edtActionTypeName)
        ItemEditorDialog.setTabOrder(self.edtActionTypeName, self.tblActionTypes)
        ItemEditorDialog.setTabOrder(self.tblActionTypes, self.tblDisabledAttendance)
        ItemEditorDialog.setTabOrder(self.tblDisabledAttendance, self.tblStocks)
        ItemEditorDialog.setTabOrder(self.tblStocks, self.tblEquipments)
        ItemEditorDialog.setTabOrder(self.tblEquipments, self.buttonBox)
        ItemEditorDialog.setTabOrder(self.buttonBox, self.tblIdentification)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.cmbChief.setWhatsThis(_translate("ItemEditorDialog", "врач отвечающий за осмотр (терапевт)", None))
        self.lblAreaType.setText(_translate("ItemEditorDialog", "&Участок", None))
        self.lblPhone.setText(_translate("ItemEditorDialog", "Теле&фон", None))
        self.chkMainStocks.setText(_translate("ItemEditorDialog", "Является основным складом", None))
        self.chkHasHospitalBeds.setText(_translate("ItemEditorDialog", "Имеет койки", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.edtInfisCode.setToolTip(_translate("ItemEditorDialog", "код отделения для экспорта в счета", None))
        self.lblHeadNurse.setText(_translate("ItemEditorDialog", "Старшая &медсестра", None))
        self.lblName_2.setText(_translate("ItemEditorDialog", "&Примечание", None))
        self.lblInfisDepTypeCode.setText(_translate("ItemEditorDialog", "Код &типа отделения по ИнФИС", None))
        self.lblInfisInternalCode.setText(_translate("ItemEditorDialog", "\"Внутренний\" &код по ИнФИС", None))
        self.lblParent.setText(_translate("ItemEditorDialog", "&Вышестоящее подразделение", None))
        self.lblTfomsCode.setText(_translate("ItemEditorDialog", "Код ТФОМС", None))
        self.lblOrganisation.setText(_translate("ItemEditorDialog", "&ЛПУ", None))
        self.lblType.setText(_translate("ItemEditorDialog", "&Тип", None))
        self.chkHasStocks.setText(_translate("ItemEditorDialog", "Имеет склад", None))
        self.cmbAreaType.setItemText(0, _translate("ItemEditorDialog", "Не является", None))
        self.cmbAreaType.setItemText(1, _translate("ItemEditorDialog", "Терапевтический", None))
        self.cmbAreaType.setItemText(2, _translate("ItemEditorDialog", "Прочий", None))
        self.lblInfisCode.setText(_translate("ItemEditorDialog", "Код отделения по &ИнФИС", None))
        self.edtInfisInternalCode.setToolTip(_translate("ItemEditorDialog", "код участка (педиатрического/терапевтического/ВОП)", None))
        self.btnSelectOrganisation.setText(_translate("ItemEditorDialog", "...", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.chkWarnAboutExpirationDateDrugStock.setText(_translate("ItemEditorDialog", "Предупреждать об истечении срока годности препарата", None))
        self.lblBookkeeperCode.setText(_translate("ItemEditorDialog", "Код для &бухгалтерии", None))
        self.lblInfisTariffCode.setToolTip(_translate("ItemEditorDialog", "HSOBJECT", None))
        self.lblInfisTariffCode.setText(_translate("ItemEditorDialog", "&Селектор тарифа для ИнФИС", None))
        self.lblNet.setText(_translate("ItemEditorDialog", "&Сеть", None))
        self.cmbHeadNurse.setWhatsThis(_translate("ItemEditorDialog", "врач отвечающий за осмотр (терапевт)", None))
        self.lblAddress.setText(_translate("ItemEditorDialog", "&Адрес", None))
        self.lblChief.setText(_translate("ItemEditorDialog", "&Зав.отделением", None))
        self.lblEmsProfileCode.setText(_translate("ItemEditorDialog", "Код профиля в бюро госпитализации", None))
        self.cmbType.setItemText(0, _translate("ItemEditorDialog", "Амбулатория", None))
        self.cmbType.setItemText(1, _translate("ItemEditorDialog", "Стационар", None))
        self.cmbType.setItemText(2, _translate("ItemEditorDialog", "Скорая помощь", None))
        self.cmbType.setItemText(3, _translate("ItemEditorDialog", "Мобильная станция", None))
        self.cmbType.setItemText(4, _translate("ItemEditorDialog", "Приемное отделение стационара", None))
        self.chkFAP.setText(_translate("ItemEditorDialog", "Является ФАПом", None))
        self.chkAvailableForExternal.setText(_translate("ItemEditorDialog", "Информация о подразделении доступна для внешних систем", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAddress), _translate("ItemEditorDialog", "Зона обслуживания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tablPlacements), _translate("ItemEditorDialog", "Помещения", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHospitalBeds), _translate("ItemEditorDialog", "Койки", None))
        self.cmbJobTimelinePeriod.setItemText(0, _translate("ItemEditorDialog", "Один план", None))
        self.cmbJobTimelinePeriod.setItemText(1, _translate("ItemEditorDialog", "Нечет/чет", None))
        self.cmbJobTimelinePeriod.setItemText(2, _translate("ItemEditorDialog", "Произвольный график", None))
        self.cmbJobTimelinePeriod.setItemText(3, _translate("ItemEditorDialog", "Одна неделя", None))
        self.cmbJobTimelinePeriod.setItemText(4, _translate("ItemEditorDialog", "Две недели", None))
        self.cmbJobTimelinePeriod.setItemText(5, _translate("ItemEditorDialog", "Три недели", None))
        self.cmbJobTimelinePeriod.setItemText(6, _translate("ItemEditorDialog", "Четыре недели", None))
        self.lblJobTimelineCustomLength.setText(_translate("ItemEditorDialog", "длительность", None))
        self.chkJobFillRedDays.setText(_translate("ItemEditorDialog", "Заполнять выходные и праздничные дни", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJobs), _translate("ItemEditorDialog", "Работы", None))
        self.chkInheritGaps.setText(_translate("ItemEditorDialog", "Наследует перерывы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGaps), _translate("ItemEditorDialog", "Перерывы", None))
        self.chkInheritEventTypes.setText(_translate("ItemEditorDialog", "Наследует типы событий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEventTypes), _translate("ItemEditorDialog", "Типы событий", None))
        self.lblQuotaType.setText(_translate("ItemEditorDialog", "Вид квоты", None))
        self.chkInheritActionTypes.setText(_translate("ItemEditorDialog", "Наследует типы действий", None))
        self.lblService.setText(_translate("ItemEditorDialog", "Профиль оплаты", None))
        self.lblTissueType.setText(_translate("ItemEditorDialog", "Тип биоматериала", None))
        self.lblServiceType.setText(_translate("ItemEditorDialog", "Вид услуги", None))
        self.lblActionTypeCode.setText(_translate("ItemEditorDialog", "Код типа действия", None))
        self.lblActionTypeName.setText(_translate("ItemEditorDialog", "Наименование типа действия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActionTypes), _translate("ItemEditorDialog", "Типы действий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDisabledAttendance), _translate("ItemEditorDialog", "Запрет обслуживания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStocks), _translate("ItemEditorDialog", "Склад", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquipment), _translate("ItemEditorDialog", "Использование оборудования", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "Идентификация", None))

from Events.ActionServiceType import CActionServiceTypeComboBox
from Orgs.OrgComboBox import COrgComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Resources.OrgStructureJobs import COrgSrtuctureJobsView
from library.DbComboBox import CDbComboBox
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
